api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

Insights has a standard for responses that we are supposed to follow.
That standard includes allowing for pagination in requests and returning
a block of navigation links in responses.
This commit also removes the account number as a path parameter from the
API.  The account number that is delivered via the x-rh-identity header
is the only account the API will service.

Add pagination information; remove account number from API.

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
src/main/java/org/candlepin/subscriptions/db/model/AccountMaxValues.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryRepository.java
src/main/java/org/candlepin/subscriptions/retention/TallyRetentionPolicy.java
src/main/java/org/candlepin/subscriptions/tally/UsageSnapshotProducer.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/main/java/org/candlepin/subscriptions/tally/facts/normalizer/RhsmFactNormalizer.java
src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/MonthlySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/QuarterlySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/WeeklySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/YearlySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/util/ApplicationClock.java
src/main/resources/liquibase/201906181633-create-schema.xml
src/main/resources/liquibase/201907121110-add-snapshot-date-index.xml
src/test/java/org/candlepin/subscriptions/FixedClockConfiguration.java
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/retention/TallyRetentionPolicyTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/normalizer/RhsmFactNormalizerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/MonthlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/QuarterlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/WeeklySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/YearlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/util/ApplicationClockTest.java

Snapshot rolling is the concept of rolling snapshot data finer grained
snapshots to larger grained snapshots. For example, rolling daily
snapshots into weekly snapshots. Or, weekly snapshots into monthly
snapshots.
Roller implementation details:
* DAILY - Pulls data from the inventory service and for each host
found, it computes the max cores/instances and creates a new
daily snapshot.
* WEEKLY - Finds the maximum cores/instances from the existing daily
snapshots for the current week and creates/updates the snapshot for
the week.
* MONTHLY - Finds the maximum cores/instances from the existing daily
snapshots for the current month and creates/updates the snapshot for
the month.
* YEARLY - Finds the maximum cores/instances from the existing monthly
snapshots for the current year and …

Implemented snapshot rolling

---

Jenkinsfile

The project link produced after quality gate has run was incorrect. Updated to point at the correct location.
If you take a look at the 'Detals' page on jenkins, take a look at the link output from the 'SonarQube Quality Gate' 'Print Message' dropdown.

Fixed sonarcloud.io project link

---

src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
src/main/java/org/candlepin/subscriptions/db/model/AccountMaxValues.java
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/tally/ProductUsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/normalizer/RhsmFactNormalizer.java
src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRoller.java
src/main/resources/liquibase/201907121757-add-sockets-column.xml
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/ProductUsageCalculationTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/normalizer/RhsmFactNormalizerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/MonthlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/QuarterlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/WeeklySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/YearlySnapshotRollerTest.java

Sockets are counted from inventory hosts and stored in the
daily snapshots. When the daily snapshots are rolled, the
max value of the sockets for the time period is used.

Count sockets and add to snapshots and rollups

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/resteasy/OffsetDateTimeParamConverterProvider.java
src/main/java/org/candlepin/subscriptions/resteasy/PageLinkCreator.java
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/resteasy/IdentityHeaderAuthFilterTest.java
src/test/java/org/candlepin/subscriptions/resteasy/PageLinkCreatorTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/MonthlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/QuarterlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/WeeklySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/YearlySnapshotRollerTest.java

This PR does several things:
1) Adds example output to the OpenAPI spec.
2) Implements the resource using the repository.
3) Makes beginning and ending required in the API.
4) Fixes date parsing.
I'm going to work on some sample data and some Ansible scripts to get those deployed in the C-I environment in our deploy repo.
I could be convinced to split this into smaller PRs if desired.

Implement TallyResource and provide examples

---

src/main/java/org/candlepin/subscriptions/tally/facts/normalizer/RhsmFactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/normalizer/RhsmFactNormalizerTest.java

Fixes
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.time.OffsetDateTime
at org.candlepin.subscriptions.tally.facts.normalizer.RhsmFactNormalizer.normalize(RhsmFactNormalizer.java:67)
```

Parse sync timestamps as Strings

---

src/main/java/org/candlepin/subscriptions/jobs/JobsConfiguration.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java

A configuration property (rhsm-subscriptions.enableJobProcessing=true|false)
was added to disable job scheduling when the application is started.
This allows dedicating an application instance to handling requests
while not having the burden of running jobs.
**NOTE:**
When jobs are disabled, we are unfortunately still spinning up a quartz scheduler. To avoid this, we would have to find a way to remove the quartz config from the application.yaml and move it to our properties file. I've left this out of the PR given our time constraints. I'd prefer to make this change at a later date, but let me know if we should invest the time to do it now.

Disable jobs via config property

---

src/main/java/org/candlepin/subscriptions/jackson/ObjectMapperContextResolver.java
src/test/java/org/candlepin/subscriptions/jackson/ObjectMapperContextResolverTest.java
src/test/java/org/candlepin/subscriptions/jackson/TestPojo.java

There is a trade off with this fix in that properties with
empty string values will be included in the JSON output,
but any properties with a null value will not.

Include empty collections in JSON data

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/controller/TallyRetentionController.java
src/main/java/org/candlepin/subscriptions/files/FileAccountListSource.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryRepository.java
src/main/java/org/candlepin/subscriptions/tally/AccountListSource.java
src/main/java/org/candlepin/subscriptions/tally/DatabaseAccountListSource.java
src/main/java/org/candlepin/subscriptions/tally/UsageSnapshotProducer.java
src/main/resources/rhsm-subscriptions.properties
src/test/java/org/candlepin/subscriptions/controller/TallyRetentionControllerTest.java
src/test/java/org/candlepin/subscriptions/files/FileAccountListSourceTest.java

I refactored so that `AccountListSource` is just a generic interface,
and now the `ApplicationConfiguration` configures a `FileAccountListSource`
if `rhsm-subscriptions.accountListResourceLocation` is specified,
or a `DatabaseAccountListSource` otherwise.

Add DatabaseAccountListSource

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

I recommend you set up the service to hit our inventory DB clone, and see that the service still records fresh snapshots. You can look for or create records in inventory service that have product IDs reported to use as a test case for the query.

Process system profile only if it has RHEL IDs

---

src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsSource.java

Since we are parsing json, the ObjectMapper was converting the
boolean strings to actual Boolean objects.

Fixed casting issue when reading identity header

---

src/main/java/org/candlepin/subscriptions/controller/TallyRetentionController.java
src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java

Spring does not honor @Transactional when the method it is on
is called from within the same class. In this particular case,
we would have to mark purgeSnapshots to make it work. Since we
want a transaction around the purge for each account, the
annotation was placed on the repository method itself.
See Pitfall#2:
https://codete.com/blog/5-common-spring-transactional-pitfalls/

Fixed missing transaction issue when purging snapshots

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/VersionResource.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java
src/test/java/org/candlepin/subscriptions/resource/VersionResourceTest.java

1. Deploy the application
```
$ ./gradlew clean bootRun --args="--server.port=9166"
```
2. Compare the actuator output with the Version resource output
```
$ diff -s <(curl -s http://localhost:9166/api/rhsm-subscriptions/v1/version) <(curl -s http://localhost:9166/actuator/info)
Files /proc/self/fd/11 and /proc/self/fd/12 are identical
```
3. Examine the Version resource output yourself
```
$ curl -s http://localhost:9166/api/rhsm-subscriptions/v1/version
```

Create Version resource that echoes the same data as the info actuator

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/tally/filler/DailyReportFiller.java
src/main/java/org/candlepin/subscriptions/tally/filler/MonthlyReportFiller.java
src/main/java/org/candlepin/subscriptions/tally/filler/QuarterlyReportFiller.java
src/main/java/org/candlepin/subscriptions/tally/filler/ReportFiller.java
src/main/java/org/candlepin/subscriptions/tally/filler/ReportFillerFactory.java
src/main/java/org/candlepin/subscriptions/tally/filler/WeeklyReportFiller.java
src/main/java/org/candlepin/subscriptions/tally/filler/YearlyReportFiller.java
src/main/java/org/candlepin/subscriptions/util/ApplicationClock.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/Assertions.java
src/test/java/org/candlepin/subscriptions/tally/filler/DailyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/MonthlyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/QuarterlyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/ReportFillerFactoryTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/WeeklyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/YearlyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/util/ApplicationClockTest.java

When paging parameters are not included in tally report request,
paging is ignored and the report will have any gaps in the snapshots
filled with dummy snapshots for the requested range.

Optionally fill in gaps in tally report periods

---

src/main/resources/liquibase/201909162045-add-capacity-table.xml
src/main/resources/liquibase/changelog.xml

The intention for a given subscription, which can be identified by a
subscription ID, to collect each applicable product's contributing
socket count, and whether the subscription provides unlimited guests
(VDC-style SKUs).
This does not handle any local caching of product data, which we may
elect to do in the future in order to improve performance.
This table is intentionally denormalized, as we intend to start out by
using denormalized views of subscription data from Candlepin pools.

Add subscription_capacity table

---

src/main/java/org/candlepin/subscriptions/capacity/CapacityProductExtractor.java
src/test/java/org/candlepin/subscriptions/capacity/CapacityProductExtractorTest.java

This is decoupled from the actual pool/subscription representation, and
is intended to plugged into later work.

Add logic to get effective products for a subscription

---

src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsSource.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationManager.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java
src/main/java/org/candlepin/subscriptions/security/auth/AdminOnly.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsSourceTest.java

* The following resources are now restricted to admin-only
+ GET /tally/products/:product_id
+ GET /capacity/products/:product_id
* New annotation AdminOnly can be applied to any resource method to
restrict it to admin users only.
* Fixed bug where granted authorities were not getting passed along
in the auth token.
* Added dev-mode=[true|false] that will grant all roles to a user
provided that an identity header is specified with at least the
account number.
```bash
$ echo eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjUzNTUzNzUiLCAidXNlciI6eyJpc19vcmdfYWRtaW4iOnRydWV9fX0K | base64 --decode
{"identity":{"account_number":"5355375", "user":{"is_org_admin":true}}}
$ curl -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjUzNTUzNzUiLCAidXNlciI6eyJpc19vcmdfYWRtaW4iOnRydWV9fX0K" …
```

Restrict tally/capacity report API to admins

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/resource/IngressResource.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java
src/main/resources/rhsm-subscriptions.properties
src/test/resources/test.properties

The idea is that we will have at least two deployment types (think
subscriptions vs. subscriptions-jobs deployment configs). In the general
API case, the API will not be present. In the other case, we'll
configure the server to require client cert auth (and actually the
endpoint).
To test the stub endpoint, set `rhsm-subscriptions.enableIngressEndpoint=true`
in `config/application.properties`

Add ingress API and implementations

---

src/main/java/org/candlepin/subscriptions/capacity/CapacityProductExtractor.java
src/main/resources/product_id_to_products_map.yaml
src/test/java/org/candlepin/subscriptions/capacity/CapacityProductExtractorTest.java
src/test/resources/test_product_id_to_products_map.yaml

Since the RHEL provided with a Satellite 6 instance is meant to be tied
to the Satellite 6 usage, we don't want to consider it in the general
capacity calculations.

Skip Satellite 6 offerings in capacity calculations.

---

src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java

This fixes:
```
javax.validation.ConstraintDeclarationException: HV000151: A method overriding another method must not redefine the parameter constraint configuration, but method TallyResource#getTallyReport(String, String, OffsetDateTime, OffsetDateTime, Integer, Integer) redefines the configuration of TallyApi#getTallyReport(String, String, OffsetDateTime, OffsetDateTime, Integer, Integer).
```
errors (and similar for capacity).

Apply @Min to resource impls

---

src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/capacity/CapacityProductExtractorTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
src/test/resources/test_product_id_to_products_map.yaml

Since RHEL is provided with Satellite, we do not want
to include a snapshot for RHEL as well. Therefore, we filter
the RHEL product when normalizing the product facts.

Skip RHEL when Satellite product is present

---

src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/controller/PoolIngressController.java
src/main/java/org/candlepin/subscriptions/files/ProductWhitelist.java
src/main/java/org/candlepin/subscriptions/resource/IngressResource.java
src/test/java/org/candlepin/subscriptions/controller/PoolIngressControllerTest.java
src/test/java/org/candlepin/subscriptions/files/ProductWhitelistTest.java

PoolIngressController performs the high-level logic of mapping Candlepin
pools to subscription capacities.
To test, use `rhsm-subscriptions.enableIngressEndpoint=true` in
`config/application.properties`
This JSON should demonstrate the endpoint in action (swagger-ui
recommended):
```json
[
{
"accountNumber": "123456",
"activeSubscription": true,
"startDate": "2019-10-07T19:06:08.816Z",
"endDate": "2019-10-07T19:06:08.816Z",
"quantity": 100,
"productId": "RH0000001",
"productAttributes": [
{
"name": "sockets",
"value": "12"
}
],
"providedProducts": [
{
"productId": "71"
}
],
"derivedProvidedProducts": [
{
"productId": "71"
}
],
"subscriptionId": "4",
"type": "NORMAL"
}
]
```

Add PoolIngressController and use in resource

---

src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepository.java
src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacity.java
src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityKey.java
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationManager.java
src/main/resources/liquibase/201910291044-alter-capacity-pk-and-tally-idx.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/controller/PoolIngressControllerTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/MonthlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/QuarterlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/WeeklySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/YearlySnapshotRollerTest.java

In certain cases, a pool may be missing an account number.  For example,
if a customer acquires a developer subscription and then buys from Red
Hat, the developer subscription won't be updated with their account
number.  Consequently, relying on the account number as a component
of a primary key in a table is undesirable.
This patch changes the capacity table to use the orgId (which should
always be present) as a part of the composite primary key.
Additionally, it ties the principal to the orgId from the authentication
header and performs necessary queries with it.

Use orgId over accountNumber.

---

insights-inventory-client/src/main/java/org/candlepin/insights/inventory/client/StubHostsApi.java

Inventory API has changed which broke our stub implementation.
This patch fixes the issue

Fixed broken inventory API stub class

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationManager.java
src/main/java/org/candlepin/subscriptions/security/InsightsUserPrincipal.java
src/main/resources/liquibase/201911061510-drop-account-not-null.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationManagerTest.java
src/test/java/org/candlepin/subscriptions/security/WithMockInsightsUserSecurityContextFactory.java
src/test/java/org/candlepin/subscriptions/security/WithMockRedHatPrincipal.java
src/test/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/MonthlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/QuarterlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/WeeklySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/YearlySnapshotRollerTest.java

Testing the tally change
------------------------
Try the tally API via deployment with `./gradlew bootRun` followed by invocation of APIs through swagger-ui. Be sure to try both tally and capacity APIs.
Testing the DB change
---------------------
Try:
```
liquibase --username rhsm-subscriptions --classpath=/usr/share/java/postgresql-jdbc.jar --url jdbc:postgresql://localhost:5432/rhsm-subscriptions --changeLogFile liquibase/changelog.xml update
```
Observe that the not null constraint is dropped via:
```
psql -U rhsm-subscriptions -h localhost -c '\d subscription_capacity'
```
Note: I added a new annotation: `@WithMockRedHatPrincipal` to replace `@WithMockUser`.

Rework tally to use account number, drop account not null

---

src/main/java/org/candlepin/subscriptions/tally/collector/ProductUsageCollectorFactory.java

Without this, we don't apply the same hypervisor counting to RHEL for
x86, etc.

Apply RHEL collector to RHEL for $arch

---

src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/exception/ErrorCode.java
src/main/java/org/candlepin/subscriptions/files/ReportingAccountWhitelist.java
src/main/java/org/candlepin/subscriptions/security/RestAccessDeniedHandler.java
src/main/java/org/candlepin/subscriptions/security/WhitelistedAccountReportAccessService.java
src/main/java/org/candlepin/subscriptions/security/auth/AdminOnly.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

Both APIs are now restricted to users having the admin role
as well as their account must be in the configured white list
file.
APIs can now be restricted in this mannor by annotating the API
method with the new annotation: @AdminWithWhitelistedAccountOnly
The white list can be configured by adding a new property to the
config file as follows:
rhsm-subscriptions.reporting_account_whitelist_resource_location=file:<PATH_TO_YOUR_ACCOUNT_LIST_FILE>
This file simply contains a list of accounts that are allowed to access the reporting APIs.
NOTE: When the application is running in dev mode, the account WILL NOT be checked when
the API is invoked.

Restrict Tally/Capacity APIs to admin + account whitelist

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/files/Cache.java
src/main/java/org/candlepin/subscriptions/files/FileAccountListSource.java
src/main/java/org/candlepin/subscriptions/files/PerLineFileSource.java
src/main/java/org/candlepin/subscriptions/files/ProductWhitelist.java
src/main/java/org/candlepin/subscriptions/files/ReportingAccountWhitelist.java
src/main/java/org/candlepin/subscriptions/files/RoleToProductsMapSource.java
src/main/java/org/candlepin/subscriptions/files/YamlFileSource.java
src/test/java/org/candlepin/subscriptions/capacity/CapacityProductExtractorTest.java
src/test/java/org/candlepin/subscriptions/files/CacheTest.java
src/test/java/org/candlepin/subscriptions/files/FileAccountListSourceTest.java
src/test/java/org/candlepin/subscriptions/files/PerLineFileResourceTest.java
src/test/java/org/candlepin/subscriptions/files/ProductIdToProductsMapSourceTest.java
src/test/java/org/candlepin/subscriptions/files/ProductWhitelistTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
src/test/java/org/candlepin/subscriptions/util/TestClock.java

Testing
-------
Create an empty account list in `/tmp/accounts.txt`:
```
touch /tmp/accounts.txt
```
Set up `config/application.properties` with the following:
```
rhsm-subscriptions.account_list_resource_location=file:/tmp/accounts.txt
rhsm-subscriptions.account_list_cache_ttl=30s
rhsm-subscriptions.jobs.captureSnapshotSchedule=* * * * * ?
rhsm-subscriptions.enableJobProcessing=true
```
Run the application (`./gradlew bootRun`). Update `/tmp/accounts.txt`
after it has started:
```
echo "123456" > /tmp/accounts.txt
```
Observe that until the cache expires (30 seconds), account count is 0. After the cache expires, the file will be re-read. and the account count will go to 1.

Add cache with default 5m ttl for maps and lists

---

.s2i/bin/assemble

Such as:
- `registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift`
- `registry.redhat.io/openjdk/openjdk-8-rhel8`
Also, it stays compatible with `docker.io/fabric8/s2i-java`
To test, try:
```
s2i build . registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift test
```
(modify the image reference as desired) followed by running the resulting container image:
```
docker run --rm test
```
Note: if you want to try the registry.redhat.io image, you'll need to do `docker login registry.redhat.io` first.
The primary difference between those images and the fabric8 ones we've been using is that the RHEL-based ones don't directly support gradle, so we have to be explicit about build steps.

Make the source compatible with RHEL-based java images

---

build.gradle
cloudigrade-client/cloudigrade-api-spec.yaml
cloudigrade-client/cloudigrade-client-config.json
settings.gradle

Cloudigrade does not do spec-first development.  They provide an OpenAPI
specification in JSON that is generated from the source code.
Unfortunately, the generated file does not work properly.  I ran into
multiple issues where OpenAPI complained about having to use
UNKNOWN_BASE_TYPE when generating a client.
Since Cloudigrade is stable and we only use a piece of the API, I've
addressed the issue by simply defining our own specification file.  We
are obligated to keep this file in sync with any changes to the
Cloudigrade API, but hopefully Cloudigrade will move toward a spec-first
development model and then we can consume a working OpenAPI definition
from them.

Generate a client for the Cloudigrade concurrent resource.

---

build.gradle
config/checkstyle/checkstyle.xml
src/main/java/org/candlepin/subscriptions/db/model/HardwareMeasurement.java
src/main/java/org/candlepin/subscriptions/db/model/HardwareMeasurementType.java
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/liquibase/LiquibaseCustomTask.java
src/main/java/org/candlepin/subscriptions/liquibase/MigrateTallyColumnsTask.java
src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
src/main/resources/liquibase/202001141534-add-snapshot-measurements-table.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/SnapshotRollerTestHelper.java

The measurements are now stored in snapshot_measurements and mapped with
JPA as embedded object which keeps them tightly coupled to the actual
Snapshot object (e.g. deletions cascade automatically).  The
measurements exist in a map off the snapshot where they are enumerated
by category (physical, total, hypervisor).
----
Note: the trigger functionality doesn't run during tests.  Since those are just temporary procedures that are part of the migration path, it didn't seem necessary to add them during the tests.  If others desire, I can rewrite the functions in whatever the HSQLDB equivalent is so they will be there during tests.
A side-effect of using stored procedures is that there's no real unit testing for the triggers.  I have tested them myself manually and would recommend that the …

Migrate tally_snapshot measurements (core, etc.) to a new table.

---

src/main/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapper.java
src/test/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapperTest.java

This is necessary as Candlepin pools are made artificially larger than
subscription quantities by a factor of the instance multiplier.

Divide effective capacity by instance_multiplier

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/ClassificationProxyRepository.java
src/main/java/org/candlepin/subscriptions/tally/ClassifiedInventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/InventoryHostFactTestHelper.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

Systems that report through system_profile advertise their type through
the "infrastructure_type" setting.  We need to take that into
consideration during fact normalization and during classification.

Consider infrastructure_type when classifying as virtual.

---

build.gradle
src/main/java/org/candlepin/subscriptions/db/PostgresTlsDataSourceProperties.java
src/main/java/org/candlepin/subscriptions/db/PostgresTlsHikariDataSourceFactoryBean.java
src/main/java/org/candlepin/subscriptions/db/RhsmSubscriptionsDataSourceConfiguration.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryDataSourceConfiguration.java
src/main/java/org/candlepin/subscriptions/jobs/JobsConfiguration.java
src/main/java/org/candlepin/subscriptions/validator/VerificationMode.java
src/main/java/org/candlepin/subscriptions/validator/VerificationModeValidator.java
src/test/resources/test.properties

Enable SSL on postgresql:
* Set `ssl = on` in `postgresql.conf`.  Set `ssl_cert_file` and `ssl_key_file`.
* To create a self-signed certificate:
```
openssl req -new -x509 -days 365 -nodes -text -out self-signed.crt -keyout self-signed.key -subj "/CN=localhost"
```
* To create a CA and a leaf certificate:
```
openssl req -new -nodes -text -out root.csr -keyout root.key -subj "/CN=Test CA"
openssl x509 -req -in root.csr -text -days 3650 -extensions v3_ca   -signkey root.key -out root.crt
openssl req -new -nodes -text -out leaf.csr -keyout leaf.key -subj "/CN=localhost"
openssl x509 -req -in leaf.csr -text -days 365 -CA root.crt -CAkey root.key -CAcreateserial -out leaf.crt
```
You can then experiment with the `root.crt` and `self-signed.crt`.  If you're using `leaf.crt` on PostgreSQLand …

Add configuration settings to allow for a TLS connection to PostgreSQL.

---

.gitmodules
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryRepository.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/ClassificationProxyRepository.java
src/test/java/org/candlepin/subscriptions/tally/ClassificationProxyRepositoryTest.java

Any host that has been culled does not get included in the produced
snapshots. A host's culled timestamp is determined via the host's
stale_timestamp as per HBI's formula:
culled_timestamp = stale_timestamp + <offset_in_days>
The application's configuration allows us to tune <offset_in_days>
in case the HBI's above changes later. The default offset is 14 days.
NOTE:
This PR filters by stale_timestamp at the query level as well as at
the processing level. This is done so that should we move away from
querying the HBI DB directly, it will will not get missed. It also
acts as a safe guard.

Ignore hosts that have been culled in HBI

---

src/main/java/org/candlepin/subscriptions/db/model/ServiceLevel.java
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/AccountUsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/ClassifiedInventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/UsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/collector/ProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
src/main/resources/liquibase/202003021107-make-tally-sla-non-null.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/AccountUsageCalculationTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryHostFactTestHelper.java
src/test/java/org/candlepin/subscriptions/tally/UsageCalculationTest.java
src/test/java/org/candlepin/subscriptions/tally/collector/Assertions.java
src/test/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/SnapshotRollerTester.java

I added an enum: `org.candlepin.subscriptions.db.model.ServiceLevel` which represents all possible values, including special values `UNSPECIFIED` and `ANY`. `ANY` is used to collect all SLAs into Snapshot records.
I renamed `ProductUsageCalculation` to `UsageCalculation` as introducing SLA as a discriminator made it so that UsageCalculations are keyed on the (product, SLA) tuple.
I also modified the table to make the SLA column non-nullable and defaulted existing data to `_ANY`.  FYI, the changeset on a test table w/ ~3.6 million rows took ~233 seconds to complete.
I made testing changes to try to keep it easy to add more fields to the tuple in the future.

Add SLA to tally snapshots

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
src/main/java/org/candlepin/subscriptions/db/model/ServiceLevel.java
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/SnapshotRollerTester.java

If null is specified for the sla query parameter, we default to a
value of _ANY, which will be set by the snapshot rollers as a
placeholder for the default sla snapshot total.

Add the sla query parameter and include it in the tally response

---

src/main/java/org/candlepin/subscriptions/tally/filler/ReportFiller.java
src/test/java/org/candlepin/subscriptions/tally/filler/DailyReportFillerTest.java

If for any reason we end up with multiple snapshots that match a given date, then this change only emits the "larger" where one of `instances` or `sockets` or `cores` is larger.

1811717: Filter out redundant snapshots

---

api/rhsm-subscriptions-api-spec.yaml
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

By setting `default: 0` in the spec, this is taken care of during construction.

Zero out TallySnapshot responses

---

src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/jobs/JobsConfiguration.java
src/main/java/org/candlepin/subscriptions/resource/IngressResource.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java
src/main/java/org/candlepin/subscriptions/task/TaskManager.java
src/main/java/org/candlepin/subscriptions/task/TaskQueueConfiguration.java
src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskQueueConfiguration.java
src/main/resources/application.yaml
src/main/resources/rhsm-subscriptions.properties
src/test/resources/kafka_schema_registry_test.properties
src/test/resources/kafka_test.properties
src/test/resources/test.properties

The following profiles now exist:
- api: instance should service API requests
- capacity-ingress: instance should accept capacity records
- scheduler: instance should schedule tasks
- worker: instance should pick up tasks from kafka and run them, implies kafka-queue
- in-memory-queue: instance should queue and run tasks in-memory
- kafka-queue: instance should queue tasks to kafka, but doesn't necessarily run them
If you run `./gradlew bootRun`, it will default to:
- api
- capacity-ingress
- scheduler
- in-memory-queue
Below commands show some ways to set profiles, and the combinations I think we need.
```sh
./gradlew bootRun --args=--spring.profiles.active=api  # accept requests and consume tasks from kafka
./gradlew bootRun --args=--spring.profiles.active=capacity-ingress  # accept …
```

Refactor into spring profiles

---

src/main/java/org/candlepin/subscriptions/BootApplication.java
src/main/java/org/candlepin/subscriptions/jobs/JobsConfiguration.java

To test, place `spring.quartz.job-store-type=foobar` in `config/application.properties`.
Note that this property causes a startup issue when run with:
```sh
./gradlew bootRun --args=--spring.profiles.active=scheduler,worker
```
but does not cause a startup issue when run with:
```sh
./gradlew bootRun --args=--spring.profiles.active=api
```

Only import QuartzAutoConfiguration in scheduler profile

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

Only count a system as the specified units. If the unit is not recognized, then log a warning.

Respect SYSPURPOSE_UNITS if present

---

src/main/java/org/candlepin/subscriptions/db/AccountConfigRepository.java
src/main/java/org/candlepin/subscriptions/db/model/OrgConfigRepository.java
src/main/java/org/candlepin/subscriptions/db/model/config/AccountConfig.java
src/main/java/org/candlepin/subscriptions/db/model/config/BaseConfig.java
src/main/java/org/candlepin/subscriptions/db/model/config/OptInType.java
src/main/java/org/candlepin/subscriptions/db/model/config/OrgConfig.java
src/main/resources/liquibase/202003261146-add-table-for-account-config.xml
src/main/resources/liquibase/202003271146-add-table-for-org-config.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/AccountConfigRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/OrgConfigRepositoryTest.java

A AccountConfig entry represents an account/org pair and
the functionality that is allowed for that pair. For example,
should data sync be enabled in tally/conduit? Or is reporting
enabled for that account in tally.
The intent here is to allow a single record to enable the
various configurable bits across both tally and conduit.
**NOTE** This PR is targeting a feature branch `feature/opt-in`

Add DB schema and repository for AdminConfig (opt-in)

---

src/main/java/org/candlepin/subscriptions/liquibase/ConfigUpdateException.java
src/main/java/org/candlepin/subscriptions/liquibase/LoadConfigsTask.java
src/main/java/org/candlepin/subscriptions/util/LiquibaseUpdateOnly.java
src/main/resources/liquibase/202004011513-load-org-account-config.xml
src/main/resources/liquibase/changelog.xml

To test using our internal config repo:
```sh
SWATCH_ACCOUNT_CONFIG_PATH=~/rhsm-conduit-deploy/roles/subscriptions/templates/reporting-api-account-whitelist.txt.j2 SWATCH_ORG_CONFIG_PATH=~/rhsm-conduit-deploy/roles/rhsm-conduit/templates/org_sync_list.csv.j2 ./gradlew bootRun '--args=--spring.profiles.active=liquibase-only --server.port=8090'
```

Add liquibase-only profile and config update task

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/controller/TallyRetentionController.java
src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
src/main/java/org/candlepin/subscriptions/files/FileAccountListSource.java
src/main/java/org/candlepin/subscriptions/files/FileAccountSyncListSource.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryRepository.java
src/main/java/org/candlepin/subscriptions/jobs/PurgeSnapshotsJob.java
src/main/java/org/candlepin/subscriptions/security/WhitelistedAccountReportAccessService.java
src/main/java/org/candlepin/subscriptions/tally/AccountListSource.java
src/main/java/org/candlepin/subscriptions/tally/AccountListSourceException.java
src/main/java/org/candlepin/subscriptions/tally/DatabaseAccountListSource.java
src/main/java/org/candlepin/subscriptions/task/TaskManager.java
src/test/java/org/candlepin/subscriptions/controller/TallyRetentionControllerTest.java
src/test/java/org/candlepin/subscriptions/files/FileAccountSyncListSourceTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/task/TaskManagerTest.java

* AccountListSource now general interface for account lists
* File based account list source now combines sync list and
reporting whitelist file sources.
To enable this  functionality, do not include the **_rhsm-subscriptions.accountListResourceLocation_** property in the config file. Otherwise the account sync list and the reporting sync list will be required as files.
You can manually add/update entries to the DB table (account_confg) to play with this feature.
```sql
insert into account_config (account_number, sync_enabled, reporting_enabled, opt_in_type, created, updated) values ('123456, TRUE, TRUE, 'DB', '2020-04-02 10:04:21.763-03', '2020-04-02 10:04:21.763-03');
```

Support use of the AccountConfig repository as the account source

---

src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/security/AntiCsrfFilter.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java

Testing is a little bit complex. Locally I did this:
1. Add an entry to `/etc/hosts`: `127.0.0.1 testcloud.redhat.com`
2. Install nginx (dnf installable), and create a config file that looks
like this (as test.conf):
```nginx
events {
worker_connections 1024;
}
http {
server {
listen 443;
location / {
proxy_pass http://localhost:8080;
}
}
}
```
3. Run nginx: `sudo nginx -c $(pwd)/test.conf`
4. Run the service with profile api:
```sh
./gradlew bootRun --args=--spring.profiles.active=api
```
5. Note that you can't PUT without a valid Origin or Referer (e.g.):
```sh
curl -H "Origin: cloud.redhat.com" -X PUT "http://testcloud.redhat.com:443/api/rhsm-subscriptions/v1/opt-in" -H  "accept: application/vnd.api+json" -H  "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eX …
```

Add a custom filter to prevent CSRF

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/security/auth/AdminOnly.java
src/main/java/org/candlepin/subscriptions/security/auth/ReportingAdminOnly.java
src/main/resources/rhsm-subscriptions.properties

TODO: I want to add some unit tests but those are taking me a little bit to figure out with our custom security stuff.   I'll add them in a separate commit if necessary. 
Also note that `orgAdminRequired` is `false` by default in `ApplicationProperties` but `true` in `rhsm-subscriptions.properties`.  Since our deployment uses its own version of `rhsm-subscriptions.properties` this set up allows tests and developer deployment to continue to work normally.
* In `config/application.properties` set 
```
rhsm-subscriptions.dev-mode=false
rhsm-subscriptions.org-admin-required=false
```
* Start the application
* Run tests against the GET for tally (ReportingAdminOnly) and the opt-in resource (AdminOnly).  Note I run my application on port 9166; you may need to adjust or just start with …

Add configuration setting to disable org admin checks.

---

build.gradle
rbac-client/rbac-client-config.json
rbac-client/src/main/java/org/candlepin/insights/rbac/client/RbacApi.java
rbac-client/src/main/java/org/candlepin/insights/rbac/client/RbacApiException.java
rbac-client/src/main/java/org/candlepin/insights/rbac/client/RbacApiImpl.java
rbac-client/src/main/java/org/candlepin/insights/rbac/client/RbacServiceProperties.java
rbac-client/src/main/java/org/candlepin/insights/rbac/client/StubRbacApi.java
settings.gradle
src/main/java/org/candlepin/rbac/RBACApiClient.java
src/main/java/org/candlepin/rbac/RbacApiFactory.java
src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationManager.java
src/main/resources/rhsm-subscriptions.properties
src/test/java/org/candlepin/subscriptions/security/WithMockInsightsUserSecurityContextFactory.java

This PR adds the RBAC generated API to the project.
* There are multiple API resources generated from the service's openapi spec,
so a single RbacApi interface was introduced to define the cumulative
operations that we will be using in rhsm-subscriptions. The default
implementation instantiates any instances of the generated RBAC API
objects that are required using the same ApiClient.
* The generated client is extended in order to pass the identity
header along with every request.
* The IdentityHeaderAuthenticationManager now puts the header bytes
into the InsightsUserPrincipal so that it can be recalled by any
client that requires it.
**Testing**
I used the debug pod to gain access to the RBAC API on rhsm-ci and forwarded the port locally to test against a local deployment of …

Add RBAC client

---

src/main/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapper.java
src/test/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapperTest.java

This change handles VDC-style SKUs (those which have derived products and are socket based), and also prevents any negative values from being used for capacity.

1824384: Handle unlimited capacity SKUs properly

---

src/main/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapper.java
src/test/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapperTest.java

Actually at the moment, there's no real use for capturing virt-unlimited due to the way we handle capacity (we count hypervisor capacity, not guest capacity).

1824384: Stop handling virt-unlimited specially

---

src/main/java/org/candlepin/subscriptions/inventory/db/InventoryRepository.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

In order to test, I set up two mocked accounts in the inventory DB
Both have:
1. 2 Guests with reported 2 and 4 sockets each
2. 1 physical system with 8 sockets.
3. 1 RHEV-based hypervisor (runs on RHEL) with reported 16 sockets
4. 1 non-RHEV based hypervisor with reported 32 sockets.
The only difference is in how the hypervisor is reported:
- foobar1 uses Satellite
- foobar2 uses rhsm-conduit
SQL below:
```sql
-- guest of hypervisor_uuid11, reported by satellite
insert into hosts (id, account, facts, canonical_facts, system_profile_facts, created_on, modified_on, stale_timestamp, reporter) values ('698758a0-69db-43ec-a106-0b960c552d47', 'foobar1', '{"satellite":{"virtual_host_uuid":"hypervisor_uuid11"},"rhsm":{"RH_PROD":[69]}}','{"subscription_manager_id":"guest11"}', …
```

1824308: Handle Satellite hypervisor mappings

---

build.gradle
rbac-client/src/main/java/org/candlepin/insights/rbac/client/RbacApiClient.java
rbac-client/src/main/java/org/candlepin/insights/rbac/client/RbacApiFactory.java
src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java

@mstead what do you think?  There's a little redundancy with the reimplementation of the `getIdentityHeader` method but personally, I think it's worth it to keep all the RBAC stuff contained in one project.

Move RBAC related classes underneath RBAC project.

---

rbac-client/src/main/java/org/candlepin/insights/rbac/client/RbacService.java
rbac-client/src/main/java/org/candlepin/insights/rbac/client/StubRbacApi.java
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/exception/ErrorCode.java
src/main/java/org/candlepin/subscriptions/exception/ExternalServiceException.java
src/main/java/org/candlepin/subscriptions/exception/OptInRequiredException.java
src/main/java/org/candlepin/subscriptions/exception/mapper/BaseExceptionMapper.java
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/resource/OptInResource.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsSource.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationFilter.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationManager.java
src/main/java/org/candlepin/subscriptions/security/InsightsUserPrincipal.java
src/main/java/org/candlepin/subscriptions/security/OptInFilter.java
src/main/java/org/candlepin/subscriptions/security/RestAccessDeniedHandler.java
src/main/java/org/candlepin/subscriptions/security/RoleProvider.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java
src/main/java/org/candlepin/subscriptions/security/WhitelistedAccountReportAccessService.java
src/main/java/org/candlepin/subscriptions/security/auth/AdminOnly.java
src/main/java/org/candlepin/subscriptions/security/auth/OptInRoleRequired.java
src/main/java/org/candlepin/subscriptions/security/auth/ReportingAccessRequired.java
src/main/java/org/candlepin/subscriptions/security/auth/ReportingAdminOnly.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsSourceTest.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationFilterTest.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationManagerTest.java
src/test/java/org/candlepin/subscriptions/security/WithMockRedHatPrincipal.java
src/test/java/org/candlepin/subscriptions/security/auth/OptInRoleRequiredTest.java
src/test/java/org/candlepin/subscriptions/security/auth/ReportingAccessRequiredTest.java

There are two key pieces to this PR.
**1) Prevent the security checks from happening multiple times per filter**
When the CSRF filter was added, security checks were being performed
multiple times per request, resulting in processing the identity header
multiple times. This was happening because we were setting the decoded
header as the principal and then replacing it with the InsightsUserPrincipal
once the header JSON was was processed. Spring security was checking
to see if the principal had changed between filters and because it was
replaced, it checked it twice.
This PR does the header parsing and principal generation in the
IdentityHeaderAuthenticationFilter. This is in turn passed to the
IdentityHeaderAuthenticationManager which simply validates the data
in the principal and throws …

Integrate RBAC permissions into application spring roles

---

src/main/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapper.java
src/main/java/org/candlepin/subscriptions/capacity/CapacityProductExtractor.java
src/main/java/org/candlepin/subscriptions/controller/PoolIngressController.java
src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepository.java
src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacity.java
src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityKey.java
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapperTest.java
src/test/java/org/candlepin/subscriptions/capacity/CapacityProductExtractorTest.java
src/test/java/org/candlepin/subscriptions/controller/PoolIngressControllerTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
src/test/resources/test_product_id_to_products_map.yaml

Because OpenShift subscriptions run on RHEL, and include RHEL, to simplify tracking, filter out RHEL during Tally or during Capacity calculations.
Also, because this is a change that can cause some pre-existing records to need to be removed, I changed the `PoolIngressController` accordingly.
I had to change `SubscriptionCapacityKey` to an `@EmbeddedId` to make it easier to use as a quick lookup.
Because deletion requires us to query for pre-existing records, I feel this is an area that we should monitor the performance of. Accordingly I added a few metrics:
- `rhsm-subscriptions.capacity.ingress` - timer for how long it takes to
process an ingress request
- `rhsm-subscriptions.capacity.records_{created,updated,deleted}` -
counts of capacity record CUD operations
- …

Adjustment: OpenShift subscriptions include RHEL

---

src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/UsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/collector/ProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryHostFactTestHelper.java
src/test/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollectorTest.java

Specifically this is accomplished by capturing two mappings during tally:
1. A mapping of hypervisor UUIDs to the usage keys (buckets) that a hypervisor contributes to.
2. A per-account mapping of hypervisor UUIDs to normalized facts.
Then as a post-processing step during Tally, the product usage collectors are called once per usage key per hypervisor, in order to adjust the tallies as needed.
I also adjusted the general hypervisor counting, to make sure that hypervisors are counted as physical during the regular tally.
Note that I adjusted the default product collector to simply add to virtual any system reported as virtual.
I only modified the RHEL collector to handle the mapped hypervisor-guest bits, as RHEL is the only product we currently have a requirement to handle hypervisor-guest …

Make hypervisors contribute to their guests usage

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapper.java
src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepository.java
src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
src/main/java/org/candlepin/subscriptions/db/model/ServiceLevel.java
src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacity.java
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/db/model/Usage.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/tally/AccountUsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/UsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
src/test/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapperTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/tally/AccountUsageCalculationTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryHostFactTestHelper.java
src/test/java/org/candlepin/subscriptions/tally/UsageCalculationTest.java
src/test/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/SnapshotRollerTester.java

To test, run the app, trigger a tally via `jconsole`, and try the API via swagger-ui.
If you want to verify the SYSPURPOSE_USAGE field, you can mock up an existing consumer's record in your local inventory DB, e.g.:
```sql
insert into hosts (id, account, facts, canonical_facts, system_profile_facts, created_on, modified_on, stale_timestamp, reporter) values ('56e25bd8-8828-43d0-a114-4c06d6b3d535', 'foobar2', '{"rhsm":{"SYSPURPOSE_USAGE": "Production", "VM_HOST_UUID":"hypervisor_uuid21","RH_PROD":[69]}}','{"subscription_manager_id":"guest21"}', '{"cores_per_socket":2,"number_of_sockets":2,"infrastructure_type":"virtual"}', now(), now(), now(), 'test');
```

Add usage to tally snapshots and API

---

src/main/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapper.java
src/test/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapperTest.java

To test, `./gradlew bootRun` and then POST pool(s) with usage attribute,
and see that they are recorded in the db:
```
curl -X POST "http://localhost:8080/api/rhsm-subscriptions/v1/ingress/candlepin_pools/org1" -H  "accept: */*" -H  "Content-Type: application/json" -d "[{\"accountNumber\":\"account1\",\"activeSubscription\":true,\"startDate\":\"2020-01-01T00:00:00Z\",\"endDate\":\"2023-01-01T00:00:00Z\",\"quantity\":1,\"productId\":\"RH000test\",\"productAttributes\":[{\"name\":\"sockets\",\"value\":\"10\"},{\"name\":\"usage\",\"value\":\"Production\"}],\"providedProducts\":[{\"productId\":\"69\"},{\"productId\":\"290\"}],\"subscriptionId\":\"subscription1\",\"type\":\"NORMAL\"}]"
```
Or you can use swagger UI with the JSON:
```json
[
{
"accountNumber": "account1",
"activeSubscription": …
```

Extract usage from Candlepin pools

---

src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationFilter.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java

Since our API uses the API gateway for auth, we don't need to use sessions anyways.
Also, made a small tweak to prevent double rbac calls.
I noticed during debugging that the filter was appearing in two chains, once for its configuration in `SecurityConfig.configure` and once by virtue of being a `GenericFilterBean`. I removed the `@Bean` annotation to reduce its use to one time per request.
To verify, you can add run via debug or place a logging statement and verify that the stub RBAC service is called exactly once per request.
If desired, you can also clear cookies for localhost and verify that they do not return when using swagger-ui.

Configure Spring Security to stop using sessions

---

src/main/java/org/candlepin/subscriptions/db/model/ServiceLevel.java
src/main/java/org/candlepin/subscriptions/db/model/Usage.java
src/test/java/org/candlepin/subscriptions/db/model/ServiceLevelTest.java
src/test/java/org/candlepin/subscriptions/db/model/UsageTest.java

This is a follow-on to #136.
This was causing issues like the following in rhsm-ci:
```
java.lang.IllegalStateException: Duplicate key TallySnapshot{id=REDACTED, snapshotDate=2020-05-01T00:00Z, granularity=MONTHLY, accountNumber=REDACTED, productId='RHEL', serviceLevel='UNSPECIFIED', usage='UNSPECIFIED'}
```

Make JPA converters handle _ANY value

---

README.md
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/resource/OptInResource.java
src/main/java/org/candlepin/subscriptions/security/RoleProvider.java
src/main/java/org/candlepin/subscriptions/security/auth/ReportingAccessRequired.java
src/main/java/org/candlepin/subscriptions/security/auth/SubscriptionWatchAdminOnly.java
src/main/resources/rhsm-subscriptions.properties
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsSourceTest.java
src/test/java/org/candlepin/subscriptions/security/WithMockRedHatPrincipal.java
src/test/java/org/candlepin/subscriptions/security/auth/ReportingAccessRequiredTest.java
src/test/java/org/candlepin/subscriptions/security/auth/SubscriptionWatchAdminOnlyTest.java

* Removed orgAdminRequired functionality now that RBAC is in place.
* Add SWATCH_ADMIN_ROLE instead of granting opt-in and reporting roles.
NOTE:
* The ReportinAccessRequired annotation is required to support the
account whitelist check when a report is requested. It now checks
that the user has the SWATCH_ADMIN_ROLE as well as checks that the
account is in the whitelist.
See #121 and #133

Clean up roles and authorization

---

Jenkinsfile

This should ensure that even if the webhook isn't functioning correctly,
we can still get a relatively timely finish of the pipeline.
This changes the max time to 20 minutes, with up to 4 checks with 5
minutes between each.
Note that currently we've been seeing occasional issues where the
webhook is delivered to Jenkins successfully (verified via Jenkins
logs), and yet the related job is not notified/updated.

Retry SonarQube quality gate check a few times

---

src/main/java/org/candlepin/subscriptions/resource/HostsResource.java

To test, deploy with `rhsm-subscriptions.rbacApplicationName=insights`
and observe you cannot access the APIs.
Then deploy without the rbac application name overridden, observe that
you can access the APIs.

Apply access check to hosts APIs

---

README.md
src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/files/ProductWhitelist.java
src/main/resources/rhsm-subscriptions.properties
src/test/java/org/candlepin/subscriptions/files/ProductWhitelistTest.java

I put all of the variables we currently had configured via deployment automation and a few we use regularly during development.
Configuration is still overridable via properties files, so the current `spring.config.additional-location` approach should work, until we move to just environment variables.
See README.md for documentation.

Move config to env vars

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/controller/TallySnapshotController.java
src/main/java/org/candlepin/subscriptions/db/HostRepository.java
src/main/java/org/candlepin/subscriptions/db/model/AppliedHost.java
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/db/model/HostHardwareType.java
src/main/java/org/candlepin/subscriptions/db/model/HostTallyBucket.java
src/main/java/org/candlepin/subscriptions/db/model/TallyHostView.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryDatabaseOperations.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryTransactionWrapper.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/UsageSnapshotProducer.java
src/main/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/collector/ProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
src/main/java/org/candlepin/subscriptions/task/TaskFactory.java
src/main/java/org/candlepin/subscriptions/task/tasks/UpdateAccountSnapshotsTask.java
src/main/resources/liquibase/202007140728-change-id-column-on-hosts-table.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryHostFactTestHelper.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

* Pull Insights ID from inventory and store cores/sockets applied
during tally on buckets.
* Use the HBI record ID as the Host.id since the insights_id is
not guaranteed to exist based on what apps have reported hosts
to inventory.
- When migrating the DB, it felt easier to just recreate the hosts
and host_tally_buckets tables as we have yet to store data via the
repository at this point. This was required since we changed the
primary key and changing it became a little complicated.
- Track guest counts on hypervisors during collection.
- Delete all existing Host records before performing calculation
- Snapshot and Host creation/update was broken into separate transactions
* T1: Update Hosts and perform account calculations.
* T2: Roll the existing snapshots based on the new calculations …

Store system table (Hosts) data during tally

---

bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/db/model/TallyHostView.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java

Fixes:
```
{"errors":[{"status":"500","code":"SUBSCRIPTIONS1000","title":"An internal server error has occurred. Check the server logs for further details.","detail":"Null return value from advice does not match primitive return type for: public abstract int org.candlepin.subscriptions.db.model.TallyHostView.getNumberOfGuests()"}]}
```
To test, use (updated) `bin/insert-mock-hosts --num-physical 1`, then hit the API for that record. With the fix no more error, without it, sadness.

Fix 500 error with null numberOfGuests

---

src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java

This also makes the defaulting to "_ANY" common to the ResourceUtils method, rather than having it per-resource class. (Meaning this commit fixes the mapping for the hosts API)
(edited 2020-07-28)

1827686: Fix capacity handling when sla/usage not specified

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/exception/mapper/BadRequestExceptionMapper.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java
src/main/java/org/candlepin/subscriptions/resteasy/EnumParamConverterProvider.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java

To test, use swagger-UI with some hosts inserted via
`bin/insert-mock-hosts`.

Add optional sort and dir params to host API

---

src/main/resources/logback-spring.xml
templates/rhsm-subscriptions-api.yml
templates/rhsm-subscriptions-capacity-ingress.yml
templates/rhsm-subscriptions-worker.yml

Based on work done originally by @patrickeasters in an internal repo.
Note I adjusted all total CPU to be below 2 cores total, and all pods
below 2000Mi total memory.

Add splunk sidecar to templates

---

api/rhsm-subscriptions-api-spec.yaml
bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/db/HostRepository.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java

Related: RedHatInsights/curiosity-frontend#383
The filter takes two values: `cores`, `sockets` and filters out systems that have a value of 0 of that UOM.
To test:
```
bin/insert-mock-hosts --num-physical 1 --cores 1 --sockets 0
bin/insert-mock-hosts --num-physical 1 --cores 0 --sockets 1
```
Then, deploy:
```
RBAC_USE_STUB=true ./gradlew bootRun
```
And finally, try with and without the uom filter (swagger-ui an option too):
```
curl -X GET "http://localhost:8080/api/rhsm-subscriptions/v1/hosts/products/RHEL" -H  "accept: application/vnd.api+json" -H  "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo"
curl -X GET …
```

Add uom filter to hosts API

---

src/main/java/org/candlepin/subscriptions/db/HostRepository.java
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/resources/liquibase/202009041415-use-uuid-for-id-on-hosts-table.xml
src/main/resources/liquibase/changelog.xml
src/main/resources/rhsm-subscriptions.properties
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java

This PR addresses a few items that improves the host import process.
1. When an ID is manually set on the Host record, spring-data
repositories will always do a merge when saving an entity.
This results in a select being executed every time a new
host is created which in not necessary since we are
deleting all hosts for an account before a tally is run.
By using a generated ID and storing the inventory_id as a
separate property, we avoid the select statements, which
improves the overall performance.
2. The delete all hosts by account number query has
been improved quite a bit shaving a little more time off the
overall tally run.
3. Batch insert is now enabled when persisting to the DB.

Insert host performance improvements

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java

NOTE: Not necessary to have @Min or @Max on the resource class so I removed it.
Test with something like:
```bash
$ curl -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjY2NzY1ODYiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTMyODQyMzQifX19" "http://localhost:8080/api/rhsm-subscriptions/v1/hosts/products/RHEL?limit=101"
{"errors":[{"status":"400","code":"SUBSCRIPTIONS1002","title":"Client request failed validation.","detail":"getHosts.limit: must be less than or equal to 100"}]}
```

Set max page limit to 100 on getHosts API

---

api/rhsm-subscriptions-api-spec.yaml

Test with something like:
```bash
$ curl -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjY2NzY1ODYiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTMyODQyMzQifX19" "http://localhost:8080/api/rhsm-subscriptions/v1/hosts/1234/guests?limit=200"
```

Set max limit of 100 on getHypervisorGuests API

---

src/main/java/org/candlepin/subscriptions/db/CustomizedSubscriptionCapacityRepositoryImpl.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepositoryTest.java

Previously, we were treating `UNSPECIFIED` the same as `ANY`.
To test, insert a couple of records into the capacity table:
```sql
INSERT INTO subscription_capacity (account_number, product_id, subscription_id, owner_id, physical_sockets, virtual_sockets, has_unlimited_guest_sockets, begin_date, end_date, physical_cores, virtual_cores, sku, sla, usage) VALUES ('account123', 'RHEL', '1827686_prem', 'org123', 5, null, false, '2010-01-01 00:00:00', '2030-01-01 00:00:00', null, null, null, 'Premium', null);
INSERT INTO subscription_capacity (account_number, product_id, subscription_id, owner_id, physical_sockets, virtual_sockets, has_unlimited_guest_sockets, begin_date, end_date, physical_cores, virtual_cores, sku, sla, usage) VALUES ('account123', 'RHEL', '1827686_unspec_sla', 'org123', 5, …
```

1827686: Handle UNSPECIFIED values in capacity queries

---

build.gradle
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/jmx/OptInJmxBean.java
src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsService.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationFilter.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationProvider.java
src/main/java/org/candlepin/subscriptions/security/InsightsUserPrincipal.java
src/main/java/org/candlepin/subscriptions/security/RhAssociatePrincipal.java
src/main/java/org/candlepin/subscriptions/security/RhIdentity.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java
src/main/java/org/candlepin/subscriptions/security/X509Principal.java
src/main/java/org/candlepin/subscriptions/util/HawtioConfiguration.java
src/main/resources/application.yaml
src/main/resources/rhsm-subscriptions.properties
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsServiceTest.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationFilterTest.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationProviderTest.java
templates/rhsm-subscriptions-worker.yml

In order to activate jolokia on an actuator, I added a dep for jolokia-core, and modified the application.yaml to enable the endpoint.
I added logging of the principal to the JMX endpoints, which will give us a nice logged record of what principal hit the endpoint. Given that the messages use the toString, the logging will work with either a RhAssociate (internal SAML) or X509 Principal (mTLS) is used.
When either of the two new principal types is used, RBAC is skipped, and a role - `RH_INTERNAL` is added instead.
I changed `IdentityHeaderAuthenticationDetailsSource` to `IdentityHeaderAuthenticationDetailsService`, a change that was
hinted at by @awood. This allowed some separation of creation of the principal and population of the roles. I did not pursue moving the opt-in check into this …

Support SAML-auth and mTLS auth for Jolokia

---

src/main/java/org/candlepin/subscriptions/util/HawtioConfiguration.java

For reasons I still don't completely understand, when you put the
management bits on a different port, the bean is not visible to the
spring context. I spent some time trying to understand exactly why (I
suspect its something like an altogether separate spring context?), but
ultimately, since we're only looking at exposing hawtio on instances
where they're the same, this workaround is acceptable.
To test, try on master:
```
MANAGEMENT_SERVER_PORT=8081 ./gradlew bootRun
```
and observe that it fails to start.
Try again with this fix, and you'll see the app starts up.
Also observe with the fix, without overriding the management port, the
base path override still functions.

Override hawtio base path only when management on same port

---

src/main/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollectorTest.java

Instead of throwing an exception when collecting for a 0 socket
RHEL hypervisor, create the bucket with 0 sockets allowing it to
be filtered by the API as it currently does.
Previously, the exception was not being handled correctly leading to
an entire tally run failing for an account reporting one of these
hypervisors.

1878665: No longer throw exception collection 0 socket RHEL hypervisor

---

Jenkinsfile
podman_run.sh

This makes it easier to reproduce a Jenkins failure locally, and allows us to more easily update the base we are running on top of,
specifically, when we go to Java 11, it will simply be a matter of replacing `registry.access.redhat.com/ubi8/openjdk-8` with `registry.access.redhat.com/ubi8/openjdk-11`.

Jenkins: Run all gradle steps inside container

---

Dockerfile
Dockerfile.test
build.gradle
config/checkstyle/checkstyle.xml
podman_run.sh
src/main/java/org/candlepin/subscriptions/task/TaskManager.java

This change does the following:
1. Move to registry.access.redhat.com/ubi8/openjdk-11 for all container images.
2. Update build.gradle pass `--release 8` to javac, to keep compiling against Java 8.
3. Update checkstyle config to be jdk11 compatible, by using `config_loc` variable.
4. Update podman command to use the user's UID properly (attempted to do this before, but got it wrong).
5. Update podman command w/ `--rm` to cleanup after itself.
6. Change hacky counting in TaskManager, that for some reason failed tests w/ JDK11.
There is still work to do to fully move to Java 11, but this will get us on an updated JDK in the short-term.
@mstead @awood this is more-or-less a follow-up to #191, I wanted to discover the scope of a JDK11 MVP, and this seemed small enough, I went ahead and made a …

Switch to JDK11, but compile against Java 8

---

src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java

When executing a JMX operation via JConsole an Authentication object
is not available in the security context. Because of this there is
no principal to output in the log. In this case we will only print
null.
To test:
Run the app, then launch JConsole and trigger a tally run via JMX.

Fix NPE when running JMX operations via JConsole

---

src/main/resources/arch_to_product_map.yaml

Cloudigrade detects ARM machines as arm64, as discovered in testing.

Map "arm64" to RHEL for ARM

---

src/main/java/org/candlepin/subscriptions/db/AccountConfigRepository.java
src/main/java/org/candlepin/subscriptions/jmx/OptInJmxBean.java
src/test/java/org/candlepin/subscriptions/db/AccountConfigRepositoryTest.java

To test, run with `./gradlew bootRun`.
Then open http://localhost:8080/actuator/hawtio/jmx/attributes?nid=root-org.candlepin.subscriptions.jmx-OptInJmxBean-optInJmxBean&pref=Connect
Observe the values of two fields:
- Current week opt in count
- Last week opt in count
In a terminal, simulate an opt-in:
```
echo "insert into account_config(account_number, sync_enabled, reporting_enabled, opt_in_type, created, updated) values ('optin0', true, true, 'API', now(), now());" | psql -h localhost -U rhsm-subscriptions
```
and observe that `Current week opt in count` is incremented by one (5 second polling interval in hawtio by default).
Insert a record to mock a previous week's opt-in:
```
echo "insert into account_config(account_number, sync_enabled, reporting_enabled, opt_in_type, created, …
```

Add opt in stats to OptInJmxBean

---

src/main/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapper.java
src/main/resources/liquibase/202010080931-fix-capacity-unspecified.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapperTest.java

Instead of null, for consistency, they should be empty string.
Prior work in #183 doesn't fix the issue described without this change
as well.
To test try:
```
curl -X POST "http://localhost:8080/api/rhsm-subscriptions/v1/ingress/candlepin_pools/org1" -H  "accept: */*" -H  "Content-Type: application/json" -d "[{\"accountNumber\":\"account1\",\"activeSubscription\":true,\"startDate\":\"2020-01-01T00:00:00Z\",\"endDate\":\"2023-01-01T00:00:00Z\",\"quantity\":1,\"productId\":\"RH000test\",\"productAttributes\":[{\"name\":\"sockets\",\"value\":\"10\"},{\"name\":\"usage\",\"value\":\"Production\"}],\"providedProducts\":[{\"productId\":\"69\"},{\"productId\":\"290\"}],\"subscriptionId\":\"subscription1\",\"type\":\"NORMAL\"}]"
```
and observe that the SLA written in the DB is '' rather than …

1827686: Fix capacity SLA/Usage UNSPECIFIED values

---

src/main/java/org/candlepin/subscriptions/security/AntiCsrfFilter.java
src/main/java/org/candlepin/subscriptions/security/GetVerbIncludingAntiCsrfFilter.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java

This commit adds a special version of AntiCsrfFilter that includes GET
requests.  Normally GET requests are exempted from CSRF checks as GET
requests are not intended to modify state on the server.  However, with
Jolokia even GET requests can actually cause a JMX bean invocation.
Note browsers don't send Origin or Referer headers when making GET
requests so hitting `/actuator/jolokia` will fail the CSRF filter.
Use curl instead or proxy your JMX request by using the /actuator/hawtio
endpoint.
---
Test Requests (DEV_MODE must be false):
1. No auth, but origin for Jolokia GET: `curl -v -H "Origin: localhost:8080" -X GET "http://localhost:8080/actuator/jolokia"`
Expect: Access allowed
Actual: Access allowed
2. No auth, no origin for Jolokia GET: `curl -v -X GET …

Apply AntiCsrfFilter check to all Jolokia requests.

---

src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

Older versions of satellite will not send the infrastructure type
to inventory, so when a host's facts are normalized, consider the
host as virtual if satellite reported the host's hypervisor UUID.

1884770: Consider host as virtual when satellite maps hypervisor

---

cloudigrade-client/cloudigrade-api-spec.yaml
src/main/java/org/candlepin/subscriptions/tally/CloudigradeAccountUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/CloudigradeAccountUsageCollectorTest.java

We plan to support serviceType in the future, but we don't yet, but cloudigrade is already collecting it, so we need to simply skip any
entries with a `service_type` other than `_ANY`.
Without this change, even when service type is unset, we end up with two values for it: `''` (unset), and `_ANY` (any/all service types). This was causing us to double count machines.

Cloudigrade: skip serviceType for now

---

src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java

That way, there is always a consistent ordering from the API. Without this change, the DB is free to (and has according to ENT-3168), return hosts in a non-deterministic, and unfortunately, inconsistent order which order which causes issues with the table display.

Always sort hosts by ID initially

---

api/rhsm-subscriptions-api-spec.yaml

This makes it so that if you're serving on a non-standard port swagger-ui will still function.
Also went ahead and noted that the ingress APIs are not user-facing.

Fixup openapi spec path to be more useful

---

src/main/java/org/candlepin/subscriptions/db/model/HardwareMeasurementType.java
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/resources/liquibase/202011090921-re-add-hypervisor-type.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

I found that we didn't include 202010291320-rename-measurement-type.xml
in changelog.xml in #208, doh!
This caused attempts to tally or retrieve tallies to fail due to
unexpected values.
However, given that we plan to start differentiating HYPERVISOR and
VIRTUAL, it no longer makes sense to just remove the value.
So instead this PR re-adds the type, and simply maps either HYPERVISOR
or VIRTUAL to the `hypervisor_sockets` or `hypervisor_cores`, etc.
values in the API for tally.
This also ensures that both HYPERVISOR and VIRTUAL are tolerated for
inserts into hardware measurements by updating the trigger
To test, use the following SQL to insert a snapshot into the DB that has
the HYPERVISOR and VIRTUAL enum values (observe that you cannot insert
VIRTUAL, until liquibase runs):
```
insert …
```

Reintroduce HYPERVISOR measurement type

---

src/main/java/org/candlepin/subscriptions/tally/CloudigradeAccountUsageCollector.java

To test, run org.candlepin.subscriptions.tally.CloudigradeAccountUsageCollectorTest in IDEA and observe the logging output.

Do not log stack trace on warning for unknown role

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

Two flags added:
- `has_cloudigrade_data`: true if cloudigrade data was included in the
snapshot, false otherwise.
- `has_cloudigrade_mismatch`: true if there was cloudigrade data and
the instance count differed from HBI data, false otherwise.

Add flags for cloudigrade to API snapshots

---

container-compose.yml

This makes it so that the default configs can reach kafka.
Might need to remove and recreate the pod (easiest via `podman-compose
down; podman-compose up -d`)

podman-compose: Advertise kafka on 9092

---

src/main/java/org/candlepin/subscriptions/security/OptInChecker.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java
src/test/java/org/candlepin/subscriptions/security/OptInCheckerTest.java
src/test/java/org/candlepin/subscriptions/security/WithInvalidPrincipal.java
src/test/java/org/candlepin/subscriptions/security/WithInvalidPrincipalSecurityContextFactory.java

Rather than use a specific filter for the opt-in check, we can use
Spring Security's authorization facilities.  This leads to a cleaner
design and a less confusing architecture.

Incorporate opt-in checks into the Spring Security authorization layer

---

src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java

Accidentally ended up in the wrong package in #211. This caused it to be
omitted from the `api` profile.
Testing
-------
Run using `SPRING_PROFILES_ACTIVE=api RBAC_USE_STUB=true ./gradlew
bootRun`.
Try:
```
curl -v "http://localhost:8080/api/rhsm-subscriptions/v1/capacity/products/RHEL?granularity=daily&beginning=2017-07-21T17%3A32%3A28Z&ending=2017-07-21T17%3A32%3A28Z" -H  "accept: application/vnd.api+json" -H  "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo"
```
Without the change you get a 404. With you get a 200.

Move CapacityResource to resource package

---

api/rhsm-subscriptions-api-spec.yaml
build.gradle
src/main/java/org/candlepin/subscriptions/db/HostRepository.java
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/resources/liquibase/202012141133-enforce-display-name-not-null.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java

Add support for `display_name_contains` as an optional query param for GET `/hosts/products/{product_id}`.
Expanded the jpql `@Query` in HostRepository.  A potential item for future improvement would be to update the related `@Entity` classes and their relationships, and refactor use spring data's `Specification` api to dynamically build the WHERE expressions and not have to explicitly concern ourselves with the optional query params coming into the endpoint being null/empty/converting to "_ANY", etc.

lburnett/filter hosts by display name [ENT-3195]

---

build.gradle
schemas/event.yaml
src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java
src/main/java/org/candlepin/subscriptions/db/RhsmSubscriptionsDataSourceConfiguration.java
src/main/java/org/candlepin/subscriptions/db/model/EventRecord.java
src/main/java/org/candlepin/subscriptions/db/model/EventRecordConverter.java
src/main/java/org/candlepin/subscriptions/event/EventController.java
src/main/java/org/candlepin/subscriptions/jmx/EventJmxBean.java
src/main/java/org/candlepin/subscriptions/resteasy/ObjectMapperContextResolver.java
src/main/java/org/candlepin/subscriptions/resteasy/ResteasyConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/main/resources/application.yaml
src/main/resources/liquibase/202011130945-add-events-table.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/EventRecordRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/model/EventRecordTest.java
src/test/java/org/candlepin/subscriptions/resteasy/ObjectMapperContextResolverTest.java

I added a gradle plugin for json schema POJO generation.
I modified our postgresql connection settings to tolerate strings in the JSONB field (other solutions were overly complex). (They get implicitly cast by postgres with `stringtype=unspecified`).
I employed two strategies in the schema:
1. When a field was an enum, '' semantically means "unset this field", while `null` or omitted means the event does not modify the field.
2. For non-enums, Optional.empty() (`null` in JSON) means "unset this field", while omitting the field will result in `null` in Java, meaning do not modify the field.
Note I preferred to use Optional on the enums as well, but couldn't find a good way to do that. In both cases, the advice to producers would be to omit the field if they don't have the info.
To test, …

Add event JSON schema and DB object

---

src/main/java/org/candlepin/subscriptions/db/HostRepository.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java

Quick fix to sanitize a null input and set it to an empty string.

Default displayNameContains to empty string to appease database libraries.

---

src/main/resources/product_id_to_products_map.yaml

Also remove the version number from Satellite product name.
This basically follows the pattern from RHEL to have one product to roll up everything as well as sub products for different versions.

Add Satellite primary product to find all satellite server & capsule instances.

---

templates/rhsm-conduit.yaml
templates/rhsm-subscriptions-api.yml
templates/rhsm-subscriptions-capacity-ingress.yml
templates/rhsm-subscriptions-scheduler.yml
templates/rhsm-subscriptions-worker.yml

Also went ahead and pivoted to SPRING_PROFILES_ACTIVE rather than the Java property for consistency.
With this change, liquibase updates always run first to completion before the pod starts (meaning timeouts of liquibase changes should not be an issue).
Note that with this change, to view logs of the liquibase run, will need to use syntax like:
```
oc logs -f rhsm-subscriptions-api-61-4sd9r -c liquibase
```
To test, you can use our deploy job to deploy to the CI environment: https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/swatch-deploy-ci/build?delay=0sec (picking this branch).

Add initContainer for liquibase updates

---

container-compose.yml

I only noticed b/c `podman-compose down` followed by `podman-compose up` broke my dev setup.
So, the difference between `5432` and `5432:5432`:
- `5432` instructs podman to pick an arbitrary port to map to a container's port `5432`
- `5432:5432` instructs podman to map the host's port `5432` to a container's port `5432`
podman v2.2.0+ ensures that the arbitrary port is random.
See containers/podman#7947

Force compose to use conventional ports

---

.gitignore

Spring Boot reads local configuration out of a directory named config.  However, Gradle also looks for project configurations (most notably Checkstyle configuration) in the config directory.  This commit hides everything under the config directory except what Gradle is going to use.

Hide Spring Boot local config files from git

---

src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/resources/application-worker.yaml
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java

To test, try:
```
SPRING_PROFILES_ACTIVE=capture-snapshots,kafka-queue ACCOUNT_BATCH_SIZE=40 ./gradlew bootRun
```
followed by:
```
SPRING_PROFILES_ACTIVE=worker,kafka-queue ACCOUNT_BATCH_SIZE=1 ./gradlew bootRun
```
and observe the log messages about ignored messages, beginning with
"Skipping message"
This test also illustrates that the ACCOUNT_BATCH_SIZE is set properly
for both worker and capture-snapshots profiles.

Set ACCOUNT_BATCH_SIZE globally, filter larger messages

---

templates/rhsm-subscriptions-api.yml
templates/rhsm-subscriptions-worker.yml

Also add a template param for this, so we can adjust without a code update.

ENT-3424: Up max http header size to 48000

---

build.gradle
src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
src/test/java/org/candlepin/subscriptions/conduit/inventory/DefaultInventoryServiceTest.java

I had to bump the systemprofile schema used. Note I didn't bump to latest as there is a problematic definition - NestedObject - which openapi-generator throws exceptions about.

RHCLOUD-12116: add owner_id to rhsm-conduit

---

src/main/resources/application-orgsync.yaml
src/main/resources/application-rhsm-conduit.yaml
templates/rhsm-conduit.yaml

- Specify the topic in orgsync profile properties
- Move the schedule to orgsync profile properties
- Add truststore config to rhsm-conduit profile properties
- Add truststore config to OpenShift template
- Add kafka-queue profile to the cronjob
These are little details that were missed in #199.
To verify, see rhsm-ci environment (I deployed this branch there), specifically see logs from the rhsm-conduit pod and cron-sync pod.
If needed, you can redeploy via https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/swatch-deploy-ci/
Also if needed you can use `oc edit CronJob/rhsm-conduit-cron-sync` to schedule the job for earlier :-)

ENT-3518: various rhsm-conduit fixes

---

build.gradle
marketplace-client/marketplace-api-spec.yaml
marketplace-client/marketplace-client-config.json
settings.gradle
src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceApiFactory.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceJmxBean.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProperties.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceService.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceWorkerConfiguration.java
src/main/resources/application-marketplace.yaml

The overall workflow is as follows:
1. A Marketplace offering is defined.
2. The charge ID(s) from the defined offering are provided for Subscription Watch configuration
(comes from https://sandbox.marketplace.redhat.com/en-us/commerce/edition-charge-editor).
Because this charge ID is consistent, we should eventually create a config value for it.
(this field is out of the scope of this change).
3. A user subscribes via the Marketplace UI.
4. A notification is sent to RH backend systems.
5. (Details TBD) Subscription Watch retrieves one or more subscription IDs to be used for integration with the Marketplace API.
6. Subscription Watch emits usage events to the Marketplace API.
The Marketplace UI can be used to verify charges: https://sandbox.marketplace.redhat.com/en-us/account/pending-char …

Add Marketplace API client

---

build.gradle
src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaConfigurator.java
src/test/java/org/candlepin/subscriptions/capacity/PoolIngressControllerTest.java
src/test/java/org/candlepin/subscriptions/cloudigrade/CloudigradeServiceTest.java
src/test/java/org/candlepin/subscriptions/conduit/HbiObjectMapperTest.java
src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
src/test/java/org/candlepin/subscriptions/conduit/inventory/client/ApiClientTest.java
src/test/java/org/candlepin/subscriptions/conduit/rhsm/RhsmServiceTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/OpenApiSpecControllerTest.java
src/test/java/org/candlepin/subscriptions/resource/OptInResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/VersionResourceTest.java
src/test/java/org/candlepin/subscriptions/resteasy/ObjectMapperContextResolverTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionServiceTest.java
src/test/java/org/candlepin/subscriptions/tally/CloudigradeAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManagerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/HourlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/MonthlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/QuarterlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/WeeklySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/YearlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/tasks/TallyTaskFactoryTest.java
src/test/java/org/candlepin/subscriptions/task/TaskWorkerTest.java
src/test/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskQueueSchemaRegistryTest.java
src/test/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskQueueTest.java

I had to replace org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2 with org.springframework.kafka.support.serializer.ErrorHandlingDeserializer (apparently these have the same semantics as Javadocs suggest for a while ErrorHandlingDeserializer2 just subclassed the other).
I removed some unneeded dependency version overrides, namely:
- hamcrest
- junit
- micrometer-registry-prometheus
- mockito
- snakeyaml
In doing so the spring dep bom updated them for us :-)
I had to separate profiles used in `@ActiveProfiles` annotations (e.g. `{"api", "test"}` instead of `"api,test"`. Apparently older spring boot tolerated either.
Closes #266

Update to spring boot 2.4.2

---

build.gradle
src/test/java/org/candlepin/subscriptions/db/model/GranularityTest.java
src/test/java/org/candlepin/subscriptions/db/model/ServiceLevelTest.java
src/test/java/org/candlepin/subscriptions/db/model/UsageTest.java

I replaced StringUtils.EMPTY that was used in a few places in unit tests only with `""` (the String literal).
Closes #271

Remove unused cloudwatch deps

---

build.gradle

Note that they are included in spring-boot-dependencies... With the
override removed, they are automatically updated to latest versions.
Closes #278
Closes #279

Stop overriding postgresql and spring-data versions

---

bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/db/HostRepository.java
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java

There were a couple optimizations to be had to make this performant:
- Made the HostTallyBuckets work properly with the `equals/hashCode` methods
- Gather all stale host records and remove them at the end
I also had to clear the buckets list to be recalculated each time (though you can see that Hibernate does not issue extraneous DML).
I made a couple of changes to the `insert-mock-hosts` script to make testing easier (see below).
Testing
-------
First, for each, clear out some data in rhsm-subscriptions:
```sql
truncate tally_snapshots cascade;
truncate hosts cascade;
truncate account_config;
```
Then, use the `insert-mock-hosts` script to set up one of the test cases below:
A few large accounts (10 accounts with 100,000 hosts each in HBI):
```
bin/insert-mock-hosts --hbi --clear …
```

Make InventoryAccountCollector remove only stale data

---

build.gradle

Because there are two different openApiGenerate tasks running during our
build of the api subproject, they write some of the same files and
invalidate gradle's up-to-date checking.
By having one of them use a separate folder, no files are overwritten,
and the incremental build doesn't need to always run this task.

Generate openapi JSON to separate folder to cache

---

src/main/java/org/candlepin/subscriptions/metering/service/prometheus/config/PrometheusServiceConfiguration.java

Duplicate bean name was causing a startup issue when running with default profiles.
Deploy as follows:
```bash
./gradlew clean bootRun
```
Before this patch, the application will not start and complains about eventController bean.
Application should start after this patch is applied.

Fix bean issue with default profiles

---

src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java

1. Product ID was too long
2. The service type didn't match what we used in the metrics gathering
phase.

Tweak MetricUsageCollector Strings

---

src/main/java/org/candlepin/subscriptions/db/HostRepository.java
src/main/java/org/candlepin/subscriptions/db/model/Account.java
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/db/model/HostBucketKey.java
src/main/java/org/candlepin/subscriptions/db/model/HostTallyBucket.java
src/main/java/org/candlepin/subscriptions/db/model/TallyHostView.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/test/java/org/candlepin/subscriptions/db/AccountRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java

Prior to the change, if a host had tally buckets added, then they would not receive the proper host_id populated. Apparently, it not intended to map the `@ManyToOne` in an embedded ID. See the javadoc for `@MapsId` for a proper example. I tried several variations; `@MapsId` isn't picked up if applied to the `@EmbeddedId`.
I also noted that the HashMap for instances was causing extra unnecessary update statements, so I tweaked its JPA config too.

Fix JPA mapping to address NPE during account merge

---

src/main/java/org/candlepin/subscriptions/metering/profile/OpenShiftWorkerProfile.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/config/PrometheusServiceConfiguration.java

Both OpenShiftWorkerProfile and OpenShiftJobProfile inherit
PrometheusServiceConfiguration but only the worker profiles needs the
metering controller.
Also add the EnableRetry annotation to actually turn on Spring Retry
AOP.

Move bean definition out of low level profile.

---

build.gradle
config/checkstyle/checkstyle.xml
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsJob.java
src/main/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManager.java
src/main/java/org/candlepin/subscriptions/tally/tasks/CaptureMetricsSnapshotTask.java
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManagerTest.java

Produce hourly tally for all configured accounts
Add metric-lookup-range-duration configuration to be used when scheduling hourly snapshot job
Queue up an hourly tally for all configured accounts and expose operation via the TallyJmxBean
Also produce hourly snapshots during the CaptureSnapshotsJob
**Note: Refactoring to minimize some duplicate code in CaptureSnapshotsJob is getting kicked down the road because of timelines, that work is captured in a new card in the backlog ENT-3561**

ENT-3542 & ENT-3263: Produce hourly tally for all configured accounts and implement prometheus latency setting

---

src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java

Now that we are storing host records from more than just HBI,
inventory ID may be null. Filter is so that we do not get
duplicate keys during the stream mapping.

Filter out hosts with null inventory IDs when collecting from inventory

---

src/main/resources/product_profile_registry.yaml

This is necessary to get the snapshot rollers to produce at HOURLY granularity.
Note I chose the names of the roles based on what is in the `subscription_labels` `product` label, which will allow us to populate `role` via product without transformation.

Add product profile for OpenShift metrics

---

src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

Found this issue while reading through some code. Fixed the issue and strengthened the unit test.

Bug Fix: Properly set hypervisor instance counts in snapshot API model

---

src/main/java/org/candlepin/subscriptions/metering/job/OpenShiftMeteringJob.java
src/main/java/org/candlepin/subscriptions/metering/profile/OpenShiftJobProfile.java
src/test/java/org/candlepin/subscriptions/metering/job/OpenShiftMeteringJobTest.java

When the job is run, the range used for metrics gathering is now calculated
using the rhsm-subscriptions.prometheusLatencyDuration config property.
**TESTING**
```bash
PROMETHEUS_LATENCY_DURATION=4h RHSM_SUBSCRIPTIONS_METERING_PROMETHEUS_METRIC_OPENSHIFT_STEP=3600 RHSM_SUBSCRIPTIONS_METERING_PROMETHEUS_METRIC_OPENSHIFT_RANGE_IN_MINUTES=60 PROM_AUTH_TOKEN="$(echo $PROM_TOKEN)" PROM_URL="https://telemeter-lts.datahub.redhat.com/api/v1" ./gradlew clean bootRun --args="--spring.profiles.active=openshift-metering-job"
```
Check that the log message printed by the job shows the expected range.

ENT-3586: OpenShiftMeteringJob now accounts for prometheus latency

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/test/java/org/candlepin/subscriptions/db/model/TallySnapshotTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

TASK: https://issues.redhat.com/browse/ENT-3516
Also moved some TallySnapshot model tests out
of the resource test and into its own test class.
**NOTE:** I noticed in the results that the snapshot report filler is not properly setting the snapshot dates on 'dummy' snapshot records. I will create a new card to get this regression addressed.
To test, insert some events into the DB with this SQL:
Run the app:
```bash
$ DEV_MODE=true ./gradlew clean bootRun
```
Insert the following records:
```sql
insert into events(id, account_number, timestamp, data) values ('033a45b7-e8c4-440a-b0bb-76c3f3f67d85','account123', '2021-01-01T00:00Z', '{"account_number":"account123","event_id":"033a45b7-e8c4-440a-b0bb-76c3f3f67d85","service_type":"OpenShift …
```

ENT-3516: Add core_hours to Tally API

---

src/main/resources/application-purge-snapshots.yaml

Because of leap year, we would have needed to do at least 366, but I
like round numbers so I went with 370.  A little buffer might be helpful
anyway.

Retain a year's worth of daily snapshots

---

src/main/java/org/candlepin/subscriptions/db/model/HostTallyBucket.java
src/test/java/org/candlepin/subscriptions/db/model/HostTallyBucketTest.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java

Added a line to HostTallyBucket.setHost() which sets the hostID
of the HostBucketKey.

ENT-3592: fix DataIntegrityViolation.

---

src/main/java/org/candlepin/subscriptions/tally/filler/ReportFiller.java
src/main/java/org/candlepin/subscriptions/tally/filler/ReportFillerFactory.java
src/test/java/org/candlepin/subscriptions/tally/filler/HourlyReportFillerTest.java

Previously, when a tally report was run at an HOURLY granularity, all 'stub' snapshots that filled a report's time range all started at midnight. This fix ensures that the dates are properly adjusted when filling reports.
**HOW TO TEST**
Launch the app.
```bash
$ DEV_MODE=true ./gradlew clean bootRun
```
Pick an account and generate a valid header value for curl requests.
```bash
echo -n '{"identity":{"account_number":"6274079", "internal":{"org_id":"2144245"}}}' | base64 -w 0
```
Opt in with the account you used above.
```bash
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean","operation":"createOrUpdateOptInConfig(java.lang.String,java.lang.String,bool …
```

ENT-3595: Properly set stub snapshot dates for filled Hourly report

---

src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/db/model/InstanceMonthlyTotalKey.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/resources/liquibase/202102260917-add-instance-monthly-totals.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java

The way these are captured are generally, as an event is processed, the measurements are added to the monthly totals.
In the case that any host record appears to be newer than the time range being processed, we assume that the monthly totals need to be recalculated in full, and the date range of events is expanded to cover whole months.
Testing
-------
1. Clear some data and then ensure opted in:
```sql
truncate table events;
truncate table tally_snapshots cascade;
truncate table hosts cascade;
insert into account_config(account_number, sync_enabled, reporting_enabled, opt_in_type, created, updated) VALUES ('account123', true, true, 'DB', now(), now());
```
2. Insert some events:
```sql
insert into events(id, account_number, timestamp, data) values …
```

ENT-3576: Add monthlyTotals measurements to Host

---

src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusService.java
src/main/resources/application-openshift-metering-worker.yaml
src/test/java/org/candlepin/subscriptions/metering/MeteringEventFactoryTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusServiceTest.java

This PR addresses a few things:
* Updated the PromQL query to closer represent the core hours metrics.
* Addresses some query encoding issues that were uncovered when the query was updated.
* Because we are taking the average over an hour, we need to set the event
date to the start of the hour that the query is averaging over. For
example, the query might return a metric at time of 3pm, but the value
is actually the average b/w 2pm and 3pm. We set the event timestamp to
the start 2pm and have it expire at 3pm. We adjust this by the configured
step of the query.
**HOW TO TEST**
The steps on #322 is a good way to test this.

MON-1507: Update promql query for OpenShift

---

api/rhsm-subscriptions-api-spec.yaml
build.gradle
src/main/java/org/candlepin/subscriptions/db/HostRepository.java
src/main/java/org/candlepin/subscriptions/db/HostSpecification.java
src/main/java/org/candlepin/subscriptions/db/SearchCriteria.java
src/main/java/org/candlepin/subscriptions/db/SearchOperation.java
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/db/model/HostBucketKey.java
src/main/java/org/candlepin/subscriptions/db/model/HostTallyBucket.java
src/main/java/org/candlepin/subscriptions/db/model/TallyHostView.java
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusService.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/resources/application-openshift-metering-worker.yaml
src/test/java/org/candlepin/subscriptions/metering/MeteringEventFactoryTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusServiceTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java

Update host APIs for monthly core-hours
* Quick & dirty implementation for including month core-hours in the payload of GET /hosts.
* Added optional `beginning` and `ending` query parameters to the API.  These are ignored if the product_id isn't `OpenShift-dedicated-metrics` or `OpenShift-metrics`.
* When the product_id is one of these, validation is in place to make sure that `ending` doesn't come before `beginning`, and that `beginning` and `ending` are of the same month. There's a very strong assumption here that the UI is always going to pass the first timestamp of a month and the last timestamp of the same month.
* Also as a part of this PR, I introduced using JPA Specifications/Criteria to the `HostRepository` class.  This will be helpful/reused when we come back to do the …

ENT-3517: add core hours hosts apis

---

bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/resources/liquibase/202103031601-modify-hosts-instance-id-not-null.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/AccountRepositoryTest.java

Prior to this change, Account failed to load when existing records with null instance_id are present, with an error: `org.hibernate.HibernateException: null index column for collection`
There are a few changes related:
1) Update existing data by setting the value of `instance_id` to inventory_id for existing records (those with `instance_type='HBI_HOST'`).
2) Add a not null constraint to prevent future bad data.
3) Adjust Host so that when populating from inventory records, `instance_id` is populated.
Testing
-------
On `develop`, (*not* this branch), insert some mock hosts:
```
bin/insert-mock-hosts --num-physical 4
```
Insert some events:
```sql
insert into events(id, account_number, timestamp, data) values ('033a45b7-e8c4-440a-b0bb-76c3f3f67d85','account123', '2021-01-01T00:00Z', …
```

ENT-3599: Make instance_id not null; populate from inventory_id when appropriate

---

src/main/java/org/candlepin/subscriptions/resource/HostsResource.java

I made a bad suggestion in #309, and thought I had tested it :-/. Doh!

Use Optional.ofNullable instead of Optional.of in hosts API

---

src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java
src/main/java/org/candlepin/subscriptions/db/model/EventKey.java
src/main/java/org/candlepin/subscriptions/db/model/EventRecord.java
src/main/java/org/candlepin/subscriptions/event/EventController.java
src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/MetricProperties.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/resources/liquibase/202102251446-add-constraints-indexes-fields-to-events.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/EventRecordRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/model/EventKeyTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java

When metric data is being processed, update existing events and
delete any that are stale from a previous run. If the metering
process is re-run then event data should be in sync afterwards.
Prior to this change, duplicate events would be created as if
the metering process was run twice.
https://issues.redhat.com/browse/ENT-3587
**NOTE:** I've merged the required database changes from #318 into this branch so they can be merged together.
**TESTING**
1) See https://docs.engineering.redhat.com/display/ENT/Prometheus+Metrics for getting an auth token for thanos. I like to export it into a variable so my startup command remains the same.
```bash
export PROM_TOKEN=<YOUR_TOKEN_FROM_ABOVE>
```
2) After getting your token, deploy the app. Using  a step of 300 will create way more events for the …

ENT-3587: Properly create/update events when processing OpenShift metrics

---

src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java

For verification, I recommend invoking the hourly tally as described in https://issues.redhat.com/browse/ENT-3622, and observing it doesn't cause issues. Note I've deployed to CI environment (rhsm-subscriptions-worker-155-sxstk); deploy job can be used to redeploy to CI for verification if desired.

ENT-3622: Emit a TallySummary event for each TallySnapshot

---

src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/HourlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/MonthlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/QuarterlySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/SnapshotRollerTester.java
src/test/java/org/candlepin/subscriptions/tally/roller/WeeklySnapshotRollerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/YearlySnapshotRollerTest.java

This handles two cases that shouldn't happen, but have shown problems
during testing:
1. When more than one host record exists for a single inventory ID.
2. When more than one snapshot exists for a given granularity and usage key and timeframe.
Testing:
insert some problematic data:
```
bin/insert-mock-hosts --num-physical=4 --clear
```
```
echo "update hosts set inventory_id='$(uuidgen)' where 1=1;" | psql -h localhost rhsm-subscriptions -U rhsm-subscriptions
echo "insert into tally_snapshots(id, product_id, account_number, granularity, snapshot_date, sla, usage) values ('$(uuidgen)', 'RHEL', 'account123', 'DAILY', now(), '', '');" | psql -h localhost rhsm-subscriptions -U rhsm-subscriptions
echo "insert into tally_snapshots(id, product_id, account_number, granularity, snapshot_date, …
```

ENT-3619: Handle duplicate snapshots and hosts

---

src/main/java/org/candlepin/subscriptions/util/ApplicationClock.java
src/test/java/org/candlepin/subscriptions/FixedClockConfiguration.java
src/test/java/org/candlepin/subscriptions/util/ApplicationClockTest.java

The code was originally written:
LocalDateTime.ofEpochSecond(time.longValue(), 0,
OffsetDateTime.now(zone).getOffset()).atZone(zone);
This old code takes the offset of the current timezone at the instant
the code is run.  The issue is that time zone offsets change.  Instead
the instant of time needs to be converted according to the time zone
rules that were applicable during that specific instant:
Instant.ofEpochSecond(time).atZone(zone);
The most common change is daylight saving time, but political decisions
can also result in changes.  For example, in 2011 Samoa switched its
time zone offset. Originally, Samoa had its primary economic interaction
with the United States, but had slowly shifted to be more engaged with
Australia, so the government decided to change the timezone offset to …

Fix epoch conversion to use relevant zone offset.

---

src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java

There were a couple issues with dates that needed to
be addressed. An extra hour was getting added to the
metric lookup dates when the end date was at the top
of an hour.
Also, when looking up existing dates, we need to account for
the start date shift when metrics are transformed into
Events. Because of this, we were trying to create new
Events, when we should have been updating the existing ones.
**TESTING**
Deploy the app and hit the JMX endpoint twice for a single account.
```bash
$ DEV_MODE=true PROM_URL="http://localhost:8082/api/v1" ./gradlew clean bootRun
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.metering.jmx:name=openshiftJmxBean,type=OpenShiftJmxBean","operation":"performOpen …
```

ENT-3639: Fix constraint violation adding metric Events

---

schemas/event.yaml
src/main/java/org/candlepin/subscriptions/files/ProductProfile.java
src/main/java/org/candlepin/subscriptions/files/ProductProfileRegistry.java
src/main/java/org/candlepin/subscriptions/files/SubscriptionWatchProduct.java
src/main/java/org/candlepin/subscriptions/files/SyspurposeRole.java
src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/main/resources/product_profile_registry.yaml
src/test/java/org/candlepin/subscriptions/files/ProductProfileRegistrySourceTest.java
src/test/java/org/candlepin/subscriptions/files/ProductProfileRegistryTest.java
src/test/java/org/candlepin/subscriptions/files/ProductProfileTest.java
src/test/java/org/candlepin/subscriptions/metering/MeteringEventFactoryTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
src/test/resources/test_product_profile_registry.yaml

The PR addresses 3 issues that came out of the reported bug in ENT-3618. Details can be found [here](https://issues.redhat.com/browse/ENT-3618?focusedCommentId=15901338&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15901338)
As they were all related, I've included the fixes in the same PR but 3 commits.
In summary, this PR fixes:
1) No more ProductId not found warning message for OpenShift metering products.
2) Snapshots produced from OpenShift metric events should now properly update the swatch product IDs for osd and ocp metrics.
**HOW TO TEST**
Get your token [here](https://docs.engineering.redhat.com/display/ENT/Prometheus+Metrics) and export to $PROM_TOKEN.
Run the app as follows:
```bash
$ DEV_MODE=true PROM_AUTH_TOKEN="$(echo $PROM_TOKEN)" …
```

ENT-3618: Properly map swatch product IDs for OpenShift based on the 'product' label from Prometheus metrics.

---

src/main/java/org/candlepin/subscriptions/BootApplication.java
src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/test/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategyTest.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java

1. Force the JVM to operate in UTC, otherwise there are subtle bugs when running on a non-UTC system, because ApplicationClock forces UTC, and Hibernate returns values in the system timezone.
2. Rework MetricUsageCollector to partition hours up-front, and deal with clearing monthly totals as needed up-front.
3. Rework MetricUsageCollector to handle stale hosts by maintaining a running lookup of active instances and tallying from the lookup rather than from latest account state.
4. Ensure CombiningRollupSnapshotStrategy fetches existing snapshots for all product IDs being tallied.
5. Fix a redunant loop over products in CombiningRollupSnapshotStrategy.
6. Filter out running calculations not having any usage.
Testing
-------
1. Insert some events into the DB:
```sql
INSERT INTO events (id, …
```

Fix issues in MetricUsageCollector

---

build.gradle
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/tasks/CaptureMetricsSnapshotTask.java

On the develop branch, if you follow the instructions below for seeding data, then running some tallies, RHEL Hourly snapshots were being produced...this first query and table of results below is an example.  I don't have instructions included for putting test data into the insights database for the HBI portion of this.....but you'll need that in order to get RHEL snapshots.
```sql
SELECT DISTINCT product_id,
--account_number,
granularity
FROM tally_snapshots
WHERE sla = '_ANY'
AND usage = '_ANY'
AND granularity = 'HOURLY'
--AND account_number = 'account123'
GROUP BY product_id,
--account_number,
granularity
ORDER BY --account_number,
granularity ASC;
```
```
+---------------------------+-----------+
|product_id                 |granularity|
+---------------------------+-----------+ …
```

ENT-3633 - (bug) Hourly snapshots being produced for non-openshift products

---

marketplace-client/marketplace-api-spec.yaml
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceJmxBean.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProducer.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProperties.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceService.java
src/main/resources/application-marketplace.yaml
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceProducerTest.java

This also makes necessary updates to Marketplace API client.
The MarketplaceProducer component doesn't do much, it really just wraps up usage reporting with a retry.
I added some custom metrics so we can see at a glance how this component is performing (via `@Timed` annotations).
Testing
-------
Much of this is repeated from #235...
First, get a marketplace API key and export it as an env var for convenience:
```
export MARKETPLACE_API_KEY=$KEYGOESHERE
```
Then run the service.
```
DEV_MODE=true MARKETPLACE_URL=https://sandbox.marketplace.redhat.com SPRING_PROFILES_ACTIVE=marketplace ./gradlew bootRun
```
Then, emit a usage event manually via
http://localhost:8080/actuator/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.marketplace-MarketplaceJmxBean-marketplaceJmxBean
Replace …

ENT-3265: Add MarketplaceProducer

---

src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/MetricProperties.java
src/main/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManager.java
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManagerTest.java
templates/rhsm-subscriptions-scheduler.yml

ENT-3570: Adjust config for event pipeline.  
This change delays the latency window by an hour, with the goal of making sure all metering tasks are finished before the tally starts.

ENT-3570: Adjust config for event pipeline

---

README.md
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProperties.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceWorker.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceWorkerConfiguration.java
src/main/resources/application-marketplace.yaml
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceWorkerTest.java
templates/marketplace-worker.yml

Note that the payload mapper is currently stubbed out. Temporarily, `MARKETPLACE_MAPPER_STUB_EMPTY` (default true) controls whether the payload emitted is empty or not.
Testing
-------
Run via 
```
MARKETPLACE_MAPPER_STUB_EMPTY=false MARKETPLACE_MAX_ATTEMPTS=1 DEV_MODE=true MARKETPLACE_URL=http://localhost:8088/does-not-exist ./gradlew bootRun
```
Insert some events:
```sql
INSERT INTO events (id, account_number, timestamp, data, event_type, event_source, instance_id) VALUES ('1edc517a-d049-4361-9804-e4111ce061ae', 'account123', '2021-03-10 19:00:00.000000', '{"role":"ocp","sla": "Premium", "usage": "Development/Test", "event_id": "1edc517a-d049-4361-9804-e4111ce061ae", "timestamp": "2021-03-10T19:00:00Z", "event_type": "snapshot", "expiration": "2021-03-10T20:00:00Z", "instance_id": …
```

ENT-3266: Add MarketplaceWorker and template

---

src/main/resources/application.yaml

These schedules are only used in dev mode. There is no
need to have these run as frequenty as they are configured.
Often times it actually gets in the way of tracing logs or
modifying data. This patch reduces the frequency that they
get run and by default sets them to run early morning.

Configure jobs to run less frequently in dev mode

---

build.gradle

Behavior around sorting changed and broke our unit tests.

Revert spring-data-jpa to 2.4.5

---

src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManager.java
src/main/java/org/candlepin/subscriptions/util/ApplicationClock.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/util/ApplicationClockTest.java

Daily snapshot values increase when the date changes. Properly set the
dates when updating instance measurements.
```bash
$ podman-compose down; podman-compose up -d
$ DEV_MODE=true  PROM_URL="http://localhost:8082/api/v1" ./gradlew clean bootRun
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean","operation":"createOrUpdateOptInConfig(java.lang.String,java.lang.String,boolean,boolean,boolean)","arguments":["6661312","123456",true,true,true]}'
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.metering.jmx:name=openshiftJmxBean,type=OpenShiftJmxBean","operatio …
```

ENT-3627: Fix Daily Metric Tally Increases

---

src/main/java/org/candlepin/subscriptions/db/AccountConfigRepository.java
src/main/java/org/candlepin/subscriptions/db/model/OrgConfigRepository.java
src/main/java/org/candlepin/subscriptions/db/model/config/OptInType.java
src/main/java/org/candlepin/subscriptions/metering/profile/OpenShiftWorkerProfile.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/MetricProperties.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSource.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusService.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManager.java
src/main/java/org/candlepin/subscriptions/metering/task/OpenShiftTasksConfiguration.java
src/main/java/org/candlepin/subscriptions/security/OptInController.java
src/main/resources/application-openshift-metering-worker.yaml
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/db/OrgConfigRepositoryTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSourceTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusServiceTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManagerTest.java
src/test/java/org/candlepin/subscriptions/security/OptInControllerTest.java

[ENT-3635](https://issues.redhat.com/browse/ENT-3635)
When OpenShift metrics collection is triggered for all accounts
(via the job or jmx), the account list is pulled from Prometheus using the
subscription_labels metric, matching on the billing_model="marketplace"
label, and will be included in the list of accounts that has
OpenShift metering enabled.
When an OpenShift metering task is executed for an account, we first
make sure that it is opted in, and then gather the meterics.
Currently there doesn't seem to be any accounts in subscription_labels that have a _billing_model_ label set to _marketplace_. As such, you will have to modify the PromQL so that it will actually match some of them.
First you'll need to set up access to a Prometheus server. See …

ENT-3635: Get OpenShift metering accounts from Prometheus

---

src/main/java/org/candlepin/subscriptions/files/ProductProfile.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceJmxBean.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapper.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProperties.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceWorker.java
src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
src/main/resources/application-marketplace.yaml
src/test/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapperTest.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceWorkerTest.java

* Run with `marketplace` profile enabled
* Use debug log level
* Invoke the `submitTallySummary` JMX endpoint with this payload
(org.candlepin.subscriptons.marketplace -> MarketplaceJmxBean -> Operations -> submitTallySummary(String))
```javascript
{
"account_number": "account123",
"tally_snapshots": [
{
"id": "c204074d-626f-4272-aa05-b6d69d6de16a",
"snapshot_date": 1615406400,
"product_id": "OpenShift-metrics",
"usage": "Production",
"sla": "Premium",
"granularity": "Hourly",
"tally_measurements": [
{
"hardware_measurement_type": "TOTAL",
"uom": "Cores",
"value": 36
},
{
"hardware_measurement_type": "PHYSICAL",
"uom": "Cores",
"value": 36
}
]
}
]
}
```
ORRRRR
If you have TallySummary messages in a kafka topic, the MarketplaceWorker will pick them up now.
You should see a debug log …

ENT-3264: Marketplace Payload Mapper

---

src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManager.java
src/main/java/org/candlepin/subscriptions/tally/tasks/CaptureMetricsSnapshotTask.java

When start/end time validation fails when running hourly
tally via JMX, the logs can lead you to believe that the
task was queued and never got picked up.
This patch improves logging when validation fails and also
strengthens overall logging around the hourly tally.

ENT-3695: Improve logging around hourly tally via JMX

---

src/main/resources/application.yaml
templates/rhsm-subscriptions-scheduler.yml

1. Apply token-refresher sidecar to metrics cronjob
Follow-on to #349.
To test, run the CI deploy job against this branch (only the scheduler needs to be deployed), and then tweak the metrics cronjob schedule to the near-future (hint: `oc edit CronJob/openshift-metrics-cron`).
Then verify via logs that the tasks were queued up as expected.
2. Add `OPENSHIFT_ENABLED_ACCOUNT_PROMQL` to make account promql easier to use; override to use `standard` billing_model for now.

Tweak cronjob for queuing metrics gathering

---

src/main/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapper.java

Before this change:
```
Caused by: org.candlepin.subscriptions.marketplace.ApiException: {"status":"failed","message":"Validation errors exist","errorDetails":[{"path":"$.data[0].additionalAttributes","type":"type","message":"$.data[0].additionalAttributes: null found, object expected"}],"data":[]}
```
After this change, marketplace API calls succeed.

Fix null additionalAttributes with Marketplace

---

src/main/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapper.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapperTest.java

Otherwise, we end up sending usage from a long, long time ago...

Map times on the snapshot as milliseconds since epoch

---

src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProducer.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProperties.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceService.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceUsageSubmissionException.java
src/main/resources/application-marketplace.yaml
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceProducerTest.java
templates/marketplace-worker.yml

[ENT-3609: Address marketplace API call failures](https://issues.redhat.com/browse/ENT-3609)
The strategy is to log and move on whenever there is an issue, as well as to capture metrics.
Three metrics were added:
- `rhsm_subscriptions_marketplace_batch_rejected_total`
- `rhsm_subscriptions_marketplace_batch_unverified_total`
- `rhsm_subscriptions_marketplace_batch_accepted_total`
(Prometheus names above; see MarketplaceProducer for micrometer names)
I replaced the mapper stubbed boolean that was stale with a boolean to toggle batch verification (in case we want to turn it off for some reason).
Testing
-------
Unit testing covers all scenarios, it's hard to test locally, here's an example of testing failure scenario though:
```
MARKETPLACE_MAX_ATTEMPTS=1 …
```

ENT-3609: Add verification and metrics for marketplace batches

---

src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceJmxBean.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProducer.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceJmxBeanTest.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceProducerTest.java

Rather than continually fail a marketplace initial request, log and move on. This essentially applies the behavior described in #373 more consistently.
There are essentially three failure modes:
1. Initial marketplace call fails, retries will happen until exhausted, then the snapshot ID and error will be logged, counted as rejected.
2. Initial call succeeds, but batch is rejected, the error will be logged, the error and batchId will be logged for investigation, counted as rejected.
3. Initial call succeeds, but the batch is not confirmed within a reasonable time; the batch ID will be logged for investigation, counted as "unverified".
The first one is addressed by this change. The other two were already handled.
Testing
-------
```
DEV_MODE=true MARKETPLACE_MAX_ATTEMPTS=1 …
```

ENT-3707: Tweak marketplace error handling for failed requests

---

src/main/resources/application-openshift-metering-worker.yaml
templates/metrics-worker.yml

* Updated the PromQL to filter by billing_model="marketplace"
* Added support to allow overriding the billing_model filter.
CARD: [ENT-3636](https://issues.redhat.com/browse/ENT-3636)
https://gitlab.cee.redhat.com/rhsm/swatch-deploy-ci/-/merge_requests/5
1. Turn debugging on and launch the app.
```bash
$ DEV_MODE=true PROM_URL="http://localhost:8082/api/v1" ./gradlew clean bootRun
```
2. Gather metrics from prometheus
```bash
curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.metering.jmx:name=openshiftJmxBean,type=OpenShiftJmxBean","operation":"performCustomOpenshiftMeteringForAccount(java.lang.String, java.lang.String, java.lang.Integer)","arguments":["6661312", null, 18000]}'
```
3. Note that …

ENT-3636: Filter openshift clusters by billing_model label

---

src/main/resources/product_profile_registry.yaml

To unblock dev-instance of marketplace-worker

Use same metricId for OCP (temporarily)

---

src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/java/org/candlepin/subscriptions/util/DateRange.java
src/test/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategyTest.java
src/test/java/org/candlepin/subscriptions/util/DateRangeTest.java

[BUG ENT-3713](https://issues.redhat.com/browse/ENT-3713)
**NOTE: THERE WILL BE A FOLLOW ON PR THAT WILL ADD CONSTRAINTS TO THE tally_snapshots TABLE AND TO CLEAN UP EXISTING DUPLICATE DATA. THIS PR WILL AT LEAST STOP THE BLEEDING.**
Roll hourly snapshots based on date range of calculations
Duplicate snapshots were getting created when events were processed
and snapshots were rolled due to date ranges.
Given that the date range can be modified when the calculations are
being done, use the range provided by the resulting calculations so
we are sure that the entire range is covered.
Start with a fresh database and ensure you have prometheus server available.
```bash
$ dropdb -U rhsm-subscriptions rhsm-subscriptions && createdb -U rhsm-subscriptions rhsm-subscriptions
```
**From the …

ENT-3713: [PART 1/2] Fix duplicate snapshot generation when rolling hourly snapshots

---

templates/marketplace-worker.yml
templates/metrics-worker.yml

Noticed that the metrics-worker and marketplace-worker have had the splunk forwarder crashing with OOM in our staging environment.
Not pressing. I'll manually override these in stage in short-term.

Bump splunk forwarder memory limits

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/conduit/rhsm/RhsmClientConfiguration.java
src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
src/main/java/org/candlepin/subscriptions/exception/ErrorCode.java
src/main/java/org/candlepin/subscriptions/http/HttpClient.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapper.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProperties.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionCollector.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionIdProvider.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusService.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionService.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceConfiguration.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceProperties.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/util/ApplicationClock.java
src/main/resources/application-marketplace.yaml
src/main/resources/application-worker.yaml
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionCollectorTest.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionIdProviderTest.java
src/test/resources/application-test.yaml
subscription-client/subscription-api-spec.yaml
templates/marketplace-worker.yml

* Make sure there are offerings in the offering table that matches our SKUs of interest.  See JIRA ticket comments for insert statements for testing
* Find an account to use that has subscriptions (https://webadmin.corp.qa.redhat.com/subscription-admin).  See JIRA ticket comments for account numbers I used
* Get OCP or OSD events into your table for the associated account number
* Make sure the account_config table has your account opted in
* Kick off an hourly tally for a time frame that encompasses the events in your event table
Assuming that your subscriptions table was empty to start with, after this logic executes you will see an entry in the rhsm-subscription.subscription table that matches a subscription fetched from the subscription service
```bash
curl --cert-type P12 --cert …
```

ENT-3341, ENT-3744: Implement MarketplaceSubscriptionIdCollector

---

src/main/java/org/candlepin/subscriptions/capacity/IngressResource.java

Generated api spec appears to have added `@NonNull` that was not previously present, which broke capacity-ingress API.
I suspect this is due to a library update we did at some point.
Testing
-------
```
curl -X 'POST' \
'http://localhost:8080/api/rhsm-subscriptions/v1/ingress/candlepin_pools/org123' \
-H 'accept: */*' \
-H 'Content-Type: application/json' \
-d '[
{
"accountNumber": "string",
"activeSubscription": true,
"startDate": "2021-04-13T00:27:44.588Z",
"endDate": "2021-04-13T00:27:44.588Z",
"quantity": 0,
"productId": "string",
"productAttributes": [
{
"name": "string",
"value": "string"
}
],
"providedProducts": [
{
"productId": "string"
}
],
"derivedProvidedProducts": [
{
"productId": "string"
}
],
"subscriptionId": "string",
"type": "string"
}
]'
```
Before the change (e.g. on …

ENT-3767: Fix HV000151 regression on capacity ingress API

---

src/main/resources/liquibase/202104051823-add-constraints-to-tally-snapshots.xml
src/main/resources/liquibase/changelog.xml

A follow on to [BUG ENT-3713](https://issues.redhat.com/browse/ENT-3713)
Added constraints to the tally_snapshots table to
prevent duplicate data. It also cleans up any duplicate
snapshots that exist in the DB due to the bug being in the
wild for a little while.
Grab a copy of the CI database and load it into a local database. Please reach out if you are not able to get one. Some tips can be found [HERE](https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=ENT&title=RDS+Operations+and+Hints)
Make note of the total number of snapshots in the database.
```sql
-- QUERY #1
select count(*) from tally_snapshots;
```
List any duplicate snapshots and count how many other snapshots are duplicated with each. No results here and the database is in good shape.
```sql
-- QUERY #2
select …
```

ENT-3713: [Part 2/2] Add constraints to tally_snapshots table

---

build.gradle
rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/X509ApiClientFactoryConfiguration.java
settings.gradle
src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/jmx/JmxBeansConfiguration.java
src/main/java/org/candlepin/subscriptions/jmx/OptInJmxBean.java
src/main/java/org/candlepin/subscriptions/metering/profile/OpenShiftWorkerProfile.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/java/org/candlepin/subscriptions/security/OptInController.java
src/main/java/org/candlepin/subscriptions/user/AccountApiFactory.java
src/main/java/org/candlepin/subscriptions/user/AccountService.java
src/main/java/org/candlepin/subscriptions/user/StubAccountApi.java
src/main/java/org/candlepin/subscriptions/user/UserServiceClientConfiguration.java
src/main/java/org/candlepin/subscriptions/user/UserServiceProperties.java
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
src/test/java/org/candlepin/subscriptions/security/OptInControllerTest.java
src/test/resources/application-test.yaml
templates/metrics-worker.yml
templates/rhsm-subscriptions-worker.yml
user-client/user-api-spec.yaml
user-client/user-client-config.json

I also added a few corresponding methods to the opt-in JMX bean.
The lookup only happens if the account doesn't already have an opt-in record.
Testing
-------
1. Clear the account_config and org_config tables:
```sql
truncate table account_config;
truncate table org_config;
```
2. Run the application with modified PromQL and connected to the QA user
service - replace `$RHSM_KEYSTORE` and `$RHSM_KEYSTORE_PASSWORD`:
Run a proxy to prometheus per (internal) https://docs.engineering.redhat.com/display/ENT/Connecting+to+Observatorium+to+Fetch+Prometheus+Metrics
```
OPENSHIFT_MAX_ATTEMPTS=1 \
RHSM_SUBSCRIPTIONS_METERING_PROMETHEUS_METRIC_OPENSHIFT_ENABLED_ACCOUNT_PROM_Q_L="group(min_over_time(subscription_labels{ebs_account != '', billing_model='standard'}[1h])) by …
```

ENT-3667: lookup orgId when performing auto-opt-in

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/conduit/inventory/ConduitFacts.java
src/main/java/org/candlepin/subscriptions/jmx/JmxProperties.java
src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/tally/TallyTaskFactory.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/tasks/CaptureMetricsSnapshotTask.java
src/main/java/org/candlepin/subscriptions/validator/IpAddress.java
src/main/java/org/candlepin/subscriptions/validator/IpAddressValidator.java
src/main/java/org/candlepin/subscriptions/validator/Iso8601.java
src/main/java/org/candlepin/subscriptions/validator/Iso8601Format.java
src/main/java/org/candlepin/subscriptions/validator/Iso8601Validator.java
src/main/java/org/candlepin/subscriptions/validator/ParameterDuration.java
src/main/java/org/candlepin/subscriptions/validator/ParameterDurationValidator.java
src/main/java/org/candlepin/subscriptions/validator/ValidatorConfiguration.java
src/main/resources/application-worker.yaml
src/test/java/org/candlepin/subscriptions/validator/IpAddressValidatorTest.java
src/test/java/org/candlepin/subscriptions/validator/Iso8601ValidatorTest.java
src/test/java/org/candlepin/subscriptions/validator/ParameterDurationValidatorTest.java

1. Start the app with a useful value for the duration limit.  You can specify hours like "8h" if you want.
```
$ ./gradlew bootRun --args="--rhsm-subscriptions.jmx.tallyBean.hourlyTallyDurationLimitDays=1"
```
2. Submit a request outside the valid range.
```
$ curl -v 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean","operation":"tallyAccountByHourly(java.lang.String,java.lang.String,java.lang.String)","arguments":["1234","2020-08-02T14:00Z","2020-08-09T15:00Z"]}'
```
3. You will receive a ConstraintViolationException as a result with a helpful error message
4. The response will be a 500 error, but that's a function of Jolokia.  We already have a mapper in …

ENT-3689 Awood/batch size limit

---

src/main/resources/application.yaml

TBH, I'm unsure why this works, but the pattern was applied to
subscription service and worked there, and works repeated here...
Fixes:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Failed to bind properties under 'rhsm-subscriptions.user-service.keystore' to java.io.File:
Property: rhsm-subscriptions.user-service.keystore
Value: ${RHSM_KEYSTORE:}
Origin: class path resource [application.yaml] from rhsm-subscriptions-1.0.40-SNAPSHOT.jar - 130:15
Reason: failed to convert java.lang.String to java.io.File
```
I already deployed to our CI environment to verify.

Fix error when user service keystore unspecified

---

src/test/java/org/candlepin/subscriptions/db/AccountRepositoryTest.java

Without this fix, OptInControllerTest was failing when run after the AccountRepositoryTest, because the AccountRepositoryTest left the account_config table non-empty.

Fix intermittent test failure due to DB pollution

---

src/main/java/org/candlepin/subscriptions/conduit/inventory/kafka/HostOperationMessage.java
src/main/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryService.java

Testing
-------
Trigger the rhsm-conduit sync (stubbed API is fine).
View the messages in the Kafka topics ui at localhost:3030, observe the
new field/value.

ENT-3738: Add platform_metadata as now required by HBI

---

src/main/resources/application.yaml

Really weird issue.  For some reason, unit tests fail to run for me _within IntelliJ only_ if I am missing this notation.  They work fine on the command line with or without it, but running the tests in the IDE without it fails with the error 
```
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.io.File] for value '';
```
Ideally, I think we would actually have the property in HttpClient be a string and load it ourselves as a `Resource` since that allows for things like reading stuff off the classpath or from URLs or from InputStreams in test cases.

Prefix keystore property with Spring Resource notation

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java

Filter out 'marketplace' billing_model from the HBI data.
```sql
-- BILLING_MODEL = standard
insert into hosts( id, account, display_name, facts, canonical_facts, system_profile_facts, created_on, modified_on, stale_timestamp, reporter) values ( '8e8a5cd2-8603-4669-8d51-4f64a4bf7f85', 'bananas123', 'grapefruit0', '{ "satellite": { "virtual_host_uuid": "hypervisor_uuid0" }, "rhsm": { "RH_PROD": [ 69 ], "BILLING_MODEL": "standard" } }', '{"subscription_manager_id":"guest0"}', '{"cores_per_socket":2,"number_of_sockets":2,"infrastructure_type":"virtual"}', now(), now(), now(), 'test' );
-- BILLING_MODEL = marketplace
insert into hosts( id, account, display_name, facts, canonical_facts, system_profile_facts, created_on, modified_on, stale_timestamp, reporter) values ( …
```

ENT-3751: Update Rhsm API to Filter Out Billing Model

---

src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java

[ENT-3736 DETAILS](https://issues.redhat.com/browse/ENT-3736)
Update the API Host's coreHours based on the the specified date
range in the request, instead of using the first monthly total
found.
I recommend starting with a fresh DB
```bash
$ dropdb -U rhsm-subscriptions rhsm-subscriptions && createdb -U rhsm-subscriptions rhsm-subscriptions
```
Deploy the app now so the schema is re-created.
```bash
$ DEV_MODE=true ./gradlew clean bootRun
```
Add events spanning a month boundary.
```sql
insert into events(id, account_number, timestamp, instance_id, data) values ('033a45b7-e8c4-440a-b0bb-76c3f3f67d85','account123', '2021-03-31T22:00Z', '4e8534b5-42b5-4f00-9969-29046e2b1986', '{"account_number":"account123","event_id":"033a45b7-e8c4-440a-b0bb-76c3f3f67d85","service_type":"OpenShift …
```

ENT-3736: Update API Host coreHours using queried month

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java

We got the params out of order when adding billing model. Doh!
Testing
-------
Insert some data into the HBI hosts table locally:
```sql
INSERT INTO hosts (id, account, display_name, created_on, modified_on, facts, tags, canonical_facts, system_profile_facts, ansible_host, stale_timestamp, reporter) VALUES ('4137e66e-2ff4-4cb5-9068-395c7db7f3a7', '6661312', '4137e66e-2ff4-4cb5-9068-395c7db7f3a7', '2021-04-17 13:39:51.414184', '2021-04-18 00:31:37.741987', '{"rhsm": {"orgId": "13259775", "RH_PROD": [], "CPU_SOCKETS": 1, "SYNC_TIMESTAMP": "2021-04-18T00:31:37.632438Z", "SYSPURPOSE_ADDONS": []}}', '{}', '{"bios_uuid": "59052905-eda0-4b29-8fa9-e58376de29d7", "subscription_manager_id": "6221b689-d5df-4342-ada5-194028699ea0"}', '{"owner_id": "6221b689-d5df-4342-ada5-194028699ea0", …
```

ENT-3791: Fix InventoryHostFacts constructor param ordering

---

src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java
src/main/java/org/candlepin/subscriptions/db/model/EventRecord.java
src/main/java/org/candlepin/subscriptions/jobs/JobProperties.java
src/main/java/org/candlepin/subscriptions/retention/EventRecordsRetentionProperties.java
src/main/java/org/candlepin/subscriptions/retention/PurgeEventRecordsJob.java
src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
src/main/resources/application-purge-snapshots.yaml
src/test/java/org/candlepin/subscriptions/db/EventRecordRepositoryTest.java
templates/rhsm-subscriptions-scheduler.yml

- Have events in rhsm-subscriptions.events table
Purge EventRecord entries on the same schedule as the PurgeSnapshotsJob
- Pick a duration for how far back you want to purge events and set rhsm-subscriptions.metering.prometheus.metric.eventRetentionDuration
- Change the cron schedule for rhsm-subscriptions.jobs.purge-snapshot-schedule so the job gets ran
- After a cycle of the job completes (log statements in the console), check your events table and confirm that expected  events were deleted

ENT-3339: Implement EventPurger

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/jobs/JobProperties.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/java/org/candlepin/subscriptions/tally/job/CaptureHourlySnapshotsConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/job/CaptureHourlySnapshotsJob.java
src/main/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManager.java
src/main/java/org/candlepin/subscriptions/tally/tasks/CaptureMetricsSnapshotTask.java
src/main/java/org/candlepin/subscriptions/util/ApplicationClock.java
src/main/java/org/candlepin/subscriptions/util/DateRange.java
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManagerTest.java
templates/rhsm-subscriptions-scheduler.yml

Marketplace is expecting to be receiving payloads hourly so this patch
sets the metric range duration property to one hour.

ENT-3706: Separate hourly tally cron job and shorten to 1 hour

---

src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/tally/filler/ReportFiller.java
src/main/java/org/candlepin/subscriptions/tally/filler/ReportFillerFactory.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/DailyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/HourlyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/MonthlyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/QuarterlyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/WeeklyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/YearlyReportFillerTest.java

This introduces into the TallyResource the concept of "running total format". Running total format is currently enabled when the product ID supports hourly granularity.
Running total format does two things:
1. It transforms tally snapshot data by making it additive (snapshot for a given date is the sum of previous dates in the response.
2. It alters the filler to use previous snapshots for generating snapshots (rather than 0-valued snapshots).
Another related change I made was if we are producing a default snapshot for a given timestamp in the future, the values are set to `null`. This should cause the graph to omit the data point (making the dropoff abrupt at the edge of data).
Testing Suggestions
-------------------
Deploy via `RBAC_USE_STUB=true ./gradlew bootRun`
Truncate existing …

ENT-3674: Change PAYG tally output to running total format

---

src/main/java/org/candlepin/subscriptions/tally/filler/ReportFiller.java

Tiny follow-up to #415
Without this change, days without any recorded usage show up in the tooltip as "no data", rather than the cumulative total.
See https://github.com/RedHatInsights/curiosity-frontend/pull/282 for explanation of GUI logic wrt `has_data`.

Show tooltip for all running total values

---

templates/rhsm-subscriptions-scheduler.yml

Because intellij likes to add characters by itself when you hit enter

Fixing syntax issue with the rhsm-subscriptions-scheduler os template

---

README.md

I extracted the profiles using the following command
```
grep -rh '@Profile' **/*.java | cut -d\" -f2- | tr -d ' '\"\)\} | tr ',' '\n' | sort | uniq
```
This greps for @Profile annotations then takes the annotation
arguments and removes quotes, spaces, parenthesis, and curly braces.
Commas are converted to newlines and then the list of individual
profiles is sorted and deduplicated.

Document all existing Spring profiles in README.md

---

README.md
dashboards/grafana-dashboard-subscription-watch.configmap.yaml

There will be an associated app-interface MR to get them deployed.
I used a unique UID and updated name so that we can have these land and then remove the old swatch dashboard, separately.
To test, first extract the JSON from the configmap:
```
oc convert -f dashboards/grafana-dashboard-subscription-watch.configmap.yaml -o go-template --template='{{ index .data "subscription-watch.json" }}' > subscription-watch.json
```
Then with the stage grafana instance, add a dashboard by importing this JSON file. Confirm overwrite if needed.
Then, review the individual panels as desired.

ENT-3314: Migrate dashboards to code repo, update

---

src/test/resources/application-test.yaml

A few failing tests have come up when running them locally
and were caused by what appears to be updates to various
jpa/hibernate libs. The app is run locally in UTC, and this
change ensures that the DB will be run in UTC as well. This
also mirrors how the application is currently deployed.
To test, run the tests locally, before and after this fix is applied.

Set database to UTC during testing

---

templates/rhsm-subscriptions-scheduler.yml

Cron expressions in k8s are:
```
minute hour day_of_month month day_of_week
```
whereas w/ Spring `@Scheduled` they are:
```
second minute hour day_of_month month day_of_week
```
So the current cronjob schedule was set for nightly rather than for
hourly.

Fix hourly tally CronJob schedule expression

---

templates/rhsm-subscriptions-scheduler.yml

Didn't realize `@` is a reserved character in YAML.
Per https://stackoverflow.com/a/20255637, it doesn't have a real meaning, but is preserved for future use. FYI, backtick (`) also is.

Quote `@hourly`

---

src/main/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapper.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionCollector.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionIdProvider.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionService.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapperTest.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionCollectorTest.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionIdProviderTest.java
subscription-client/subscription-api-spec.yaml

https://issues.redhat.com/browse/ENT-3743
Use the user service to determine the org ID for an account
and use it to find the subscriptions for the org as it is
more reliable.
```sql
TRUNCATE events cascade;
TRUNCATE subscription cascade;
TRUNCATE sku_child_sku cascade;
TRUNCATE offering cascade;
insert into events(id, account_number, timestamp, instance_id, data) values ('033a45b7-e8c4-440a-b0bb-76c3f3f67d85','6043640', '2021-04-16T22:00Z', '4e8534b5-42b5-4f00-9969-29046e2b1986', '{"account_number":"6043640","event_id":"033a45b7-e8c4-440a-b0bb-76c3f3f67d85","service_type":"OpenShift Cluster","instance_id":"4e8534b5-42b5-4f00-9969-29046e2b1986","measurements": [{"uom":"Cores","value":4.0}], "timestamp": "2021-04-16T22:00Z", "role" : "osd"}');
insert into events(id, account_number, …
```

ENT-3743: Lookup sub IDs by orgId instead of account

---

src/main/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManager.java
templates/rhsm-subscriptions-scheduler.yml

Currently we do not have access to job logs in splunk. These
logs are important when trying to determine whether a
particular process has been run for a particular account.
By configuring a Splunk sidecar for each job, it will give
us access to important logging info that will help with debugging
issues.
Testing this is a little painful and should be done CI environment.
1. Do a deployment of the job templates to the CI environment via Jenkins ([HERE](https://stage-jenkins-csb-smqe.apps.ocp4.prod.psi.redhat.com/job/Swatch%20deploy%20CI/))
* Click 'Build With Parameters', enter this PR's branch, select only DEPLOY_SUBSCRIPTIONS_SCHEDULER box.
2. Once the build completes, wait for the top of the hour when a job runs. Check the OpenShift console for CI and ensure that after the job runs, a …

ENT-3815: Add splunk sidecar configuration to jobs to help with debugging

---

src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManagerTest.java

In #410, we changed the default range to 1h in ApplicationProperties. However, we didn't change it in the YAML file.
I'm thinking to avoid this type of gotcha in the future, we should avoid setting a default value in Properties classes, and only keep a value in the YAML. I'll create a backlog task for this.
Testing
-------
Ensure you have some records in the account_config table:
```
cat << EOF | psql -h localhost -U rhsm-subscriptions
INSERT INTO public.account_config (account_number, sync_enabled, reporting_enabled, opt_in_type, created, updated) VALUES ('account123', true, true, 'JMX', now(), now());
EOF
```
Run the following *without the change* (on `develop` branch):
```
SPRING_PROFILES_ACTIVE=capture-hourly-snapshots,kafka-queue ./gradlew bootRun
```
Observe messages such as:
``` …
```

ENT-3866: Default metric range lookup to 1h in YAML

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

Testing
-------
Insert a mocked Satellite record into local HBI DB.
```
cat <<EOF | psql -h localhost -U insights
insert into hosts(id, account, display_name, created_on, modified_on, facts, tags, canonical_facts,
system_profile_facts, ansible_host, stale_timestamp, reporter)
values ('7ff17db8-3c3b-429f-8eea-b026655d10b6', 'account123', 'sat-host', now(), now(), '{
"satellite": {
"system_purpose_role": "Red Hat Enterprise Linux Server",
"system_purpose_sla": "Premium",
"system_purpose_usage": "Production"
}
}', null, '{}', '{"cores_per_socket": 2, "sockets": 1}', null, now() + '7 days', 'satellite');
EOF
```
Run tally for the account:
```
curl -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean","operation":"ta …
```

ENT-3543: Handle satellite syspurpose attributes

---

api/rhsm-subscriptions-api-spec.yaml
schemas/event.yaml
schemas/tally_summary.yaml

This is a preparatory PR to thread new instance_hours to the API, database, and event.  I don't believe there are any unit tests for this, as it is a form of preparation for adding functionality.

ENT-3837: Add instance_hours as a metric type across data models (DB, API, event)

---

src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java

This adds the start of OfferingSyncController. Currently this will only sync offerings, it will not pull updated offerings from upstream, as that will arrive in a later story, ENT-2664.
Currently the controller is disabled, via an option added to ApplicationProperties.

ENT-2658: Add offering sync controller

---

.dockerignore
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/http/HttpClientProperties.java
src/main/java/org/candlepin/subscriptions/rbac/RbacApiFactory.java
src/main/java/org/candlepin/subscriptions/rbac/RbacProperties.java
src/main/java/org/candlepin/subscriptions/rbac/StubRbacApi.java
src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsService.java
src/main/java/org/candlepin/subscriptions/security/RoleProvider.java
src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java
src/main/java/org/candlepin/subscriptions/security/auth/SubscriptionWatchAdminOnly.java
src/main/resources/application-api.yaml
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsServiceTest.java

I also did some light refactoring around the RBAC properties, primarily pulling all rbac properties into a single properties class.
Testing
-------
Launch and run the following steps with two different configurations:
1. `RBAC_USE_STUB=true ./gradlew bootRun` (stub returns
`subscriptions:*:*`).
2. `RBAC_USE_STUB=true RBAC_STUB_PERMISSIONS=subscriptions:reports:read
./gradlew bootRun`.
(you can try other arguments to RBAC_STUB_PERMISSIONS if desired)
Verify that the following two APIs still work (this hits both the security SPEL expressions we use):
1. Opt-in:
```
curl -X PUT \
'http://localhost:8080/api/rhsm-subscriptions/v1/opt-in?enable_tally_sync=true&enable_tally_reporting=true&enable_conduit_sync=true' \
-H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eX …
```

ENT-3824: Support subscriptions:reports:read permission

---

build.gradle
src/main/java/org/candlepin/subscriptions/BootApplication.java
src/main/java/org/candlepin/subscriptions/liquibase/LiquibaseCustomTask.java
src/main/java/org/candlepin/subscriptions/liquibase/LoadConfigsTask.java
src/main/java/org/candlepin/subscriptions/liquibase/MigrateTallyColumnsTask.java
src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java

1. Because spring-boot 2.5 comes with newer liquibase, needed to change how we fetch the logger in custom tasks.
2. Since newer liquibase comes with liquibase hub, I added a system property to disable it (otherwise we get an unnecessary warning in our logs).
3. Newer promtheus client surfaces a conflict in the naming of one of our custom metrics that was actually a copy-paste error anyways. Startup failed otherwise.
4. Add `jackson-module-kotlin` as a dep in order to avoid warnings. `spring-kafka` upgrade added kotlin deps, causing messages like:
```
WARN org.springframework.http.converter.json.Jackson2ObjectMapperBuilder - For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
```
After these changes are applied we can merge …

Make compatible with Spring Boot 2.5

---

templates/marketplace-worker.yml

https://issues.redhat.com/browse/ENT-3890
Otherwise, the defaults of localhost were being used, resulting in errors like:
```
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:443 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused) at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
org.springframework.kafka.listener.ListenerExecutionFailedException: Listener method 'public void org.candlepin.subscriptions.marketplace.MarketplaceWorker.receive(org.candlepin.subscriptions.json.TallySummary)' threw exception; nested exception is javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request; nested exception is …
```

ENT-3890: Add user service env vars to marketplace-worker

---

.dockerignore
build.gradle

https://issues.redhat.com/browse/ENT-3928
Otherwise, we end up with two different JARs in the image, and the ubi8 java image doesn't know which one to run.
This started to happen because Spring Boot 2.5 no longer automatically disables the default jar.
See:
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes#gradle-default-jar-and-war-tasks
- https://docs.spring.io/spring-boot/docs/2.5.0/gradle-plugin/reference/htmlsingle/#packaging-executable.and-plain-archives
NOTE: I also symlinked `.gitignore` to `.dockerignore` to make building a pristine container image locally easier (syntax is compatible). Without this change, you needed to build from a clean checkout.
Testing
-------
On `develop`, run `./gradlew clean assemble`, observe that two jars are produced …

ENT-3928: Disable the plain jar

---

.gitignore

OpenShift v3 builds were failing due to this.
Possibly due to https://github.com/containers/buildah/issues/2686

Remove open paren from .dockerignore comment

---

templates/marketplace-worker.yml

Similar to #409.
Testing
---------
First, observe the logs of the marketplace-worker from `develop`; note that messages like:
```
org.candlepin.subscriptions.exception.SubscriptionsException: Error looking up orgId
...
Caused by: org.candlepin.subscriptions.user.ApiException: <HTML><HEAD>
```
occur.
Next, deploy this branch to CI, and observe that this message does not occur, instead you see normal operation (e.g.
```
[thread=marketplace-worker-5-C-1] [level=DEBUG] [category=org.candlepin.subscriptions.marketplace.MarketplacePayloadMapper]  - UsageRequest class UsageRequest {     data: [] }
```

ENT-3890: Add keystore params to marketplace worker

---

src/main/java/org/candlepin/subscriptions/files/ProductMappingConfiguration.java

Using `ResourceUtils.getFile()` for a file that is on the classpath, and not the filesystem won't work. Doh!
Testing
-------
`./gradlew assemble` from `develop`, run `java -jar build/libs/rhsm-subscriptions-1.0.53-SNAPSHOT.jar`, observe message w/
```
java.io.FileNotFoundException: class path resource [tag_profile.yaml] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/deployments/rhsm-subscriptions-1.0.53-SNAPSHOT.jar!/BOOT-INF/classes!/tag_profile.yaml
```
Repeat steps with this branch, observe that the app starts without errors.

ENT-3973: Fix TagProfile loading from classpath

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/test/java/org/candlepin/subscriptions/db/model/TallySnapshotTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

Testing
-------
Mock some data for instance hours:
```
cat <<EOF | psql -h localhost -U rhsm-subscriptions
insert into tally_snapshots(id, product_id, account_number, granularity, owner_id, instance_count,
snapshot_date, sla, usage)
values ('b099d1fc-118f-4255-8500-aa7f9660663d', 'OpenShift-metrics', 'account123', 'DAILY', 'org123', 1, '2017-07-29',
'_ANY', '_ANY');
insert into tally_measurements(snapshot_id, measurement_type, uom, value)
values ('b099d1fc-118f-4255-8500-aa7f9660663d', 'TOTAL', 'INSTANCE_HOURS', 4.0);
EOF
```
Hit the API:
```
curl 'http://localhost:8080/api/rhsm-subscriptions/v1/tally/products/OpenShift-metrics?granularity=Daily&sla=_ANY&usage=_ANY&beginning=2017-07-29T00%3A00%3A00Z&ending=2017-07-30T23%3A59%3A59Z&use_running_totals_format=false'   -H 'accept: …
```

ENT-3842: Add {total_,}instance_hours to tally API

---

src/main/java/org/candlepin/subscriptions/jmx/OfferingJmxBean.java
src/test/java/org/candlepin/subscriptions/jmx/OfferingJmxBeanTest.java

Implements `String syncOffering(String sku)`.
* When successful, the details of the upstream offering will be
persisted in swatch's database, and the details of the offering
are returned.
* If the offering was not found upstream, or was not allowlisted, then
the following json message is returned:
`{"message": "offeringSku=$SKU was not found/allowlisted."}`

ENT-3972 Add OfferingJmxBean

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/db/HostRepository.java
src/main/java/org/candlepin/subscriptions/db/TagProfileLookup.java
src/main/java/org/candlepin/subscriptions/db/TagProfileLookupImpl.java
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/files/TagProfile.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/metering/profile/MeteringJobProfile.java
src/main/java/org/candlepin/subscriptions/metering/profile/OpenShiftWorkerProfile.java
src/main/java/org/candlepin/subscriptions/resource/ApiConfiguration.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java

https://issues.redhat.com/browse/ENT-3949
Note that I explored a couple of different options. The tricky thing with dynamic metrics and our data model is the join seen in
HostSpecification, where a single metric/UOM is joined against for filtering and sorting.
I considered generating joins dynamically based on the ProductProfile, but it got messy quickly, so I instead opted to change the single UOM used in the join dynamically, defaulting to the first configured UOM for a tag, or specified by the sort param.
I named this new parameter "reference UOM".
There is one gap here: if a multi-metric product has *missing* metrics for a given instance, then that instance may be incorrectly filtered out. If we encounter such a use case in the future, I think we should revisit the specification …

ENT-3949: Add support for instance-hours to hosts API

---

build.gradle

https://issues.redhat.com/browse/ENT-4025
The idea is that we split development efforts in two:
1. Changes against `develop` per usual.
2. Fixes against the current release "train" (that hasn't graduated to prod yet).
Updated processes below:
Begin a new release train
```
git fetch  # ensure we have latest state
git checkout release
git merge --ff-only origin/develop  # FF the release branch to latest develop, if this fails, we should merge release into develop first
```
Bugfixing current release train
-------------------------------
1. Fix should initially land with a PR against `release`.
2. Fix should subsequently land in `develop` via a PR merging `release` into `develop` (ideally handled by the same author as the `release` PR).
Tagging a release candidate …

ENT-4025: Change config to release from `release` branch

---

src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusService.java

It appears that the latest upgrade of the telemeter
APIs address the really long and bloated response
message and body when an error occurs on the query
API. Now that this has been fixed, we can include
the actual cause of the error in our logs!
1. Force error in account lookup query in application.yaml
```
...
metric:
accountQueryTemplates:
default: >-
${OPENSHIFT_ENABLED_ACCOUNT_PROMQL:group(min_over_te(#{metric.queryParams[prometheusMetadataMetric]}{product='#{metric.queryParams[product]}', ebs_account != '', billing_model='marketplace'}[1h]))
by (ebs_account)}
...
```
2. Launch the app
```bash
$ USER_USE_STUB=true PROM_URL="http://localhost:8082/api/metrics/v1/telemeter/api/v1" DEV_MODE=true ./gradlew clean bootRun
```
3. Kick off a metering task and watch the logs for the error. …

No longer suppress Prometheus API errors

---

build.gradle

Notably, when called from any given project, the task will now do that project and any subprojects' dependencies. In other words, called from the root as `./gradlew -q :dependencyJson`, you'll get output for any services we have in the repo.
Called from a given subproject, you'll get a report for that specific component. (e.g. `./gradlew -q rhsm-client:dependencyJson` outputs only the deps for that subproject/library).
This allows us to use in the short term the same script/tooling as we have been (with minor tweaks) for reporting out dependencies.
I switched to using the `default` configuration, as this includes both compile-time and run-time deps. What we had before seemed to be missing some deps!
Also, I modified the code to walk the dependency tree, as I found out the methods we were …

Make various fixes to dependencyJson task

---

templates/rhsm-subscriptions-capacity-ingress.yml

Fixes bug by https://github.com/RedHatInsights/rhsm-subscriptions/pull/475 being merged
If you have CRC running on your local, you can test using the `oc process` command to reproduce/test
`oc process -f rhsm-subscriptions-capacity-ingress.yml`
```
error: failed to read input object (not a Template?): unable to decode "rhsm-subscriptions-capacity-ingress.yml": v1.Template.Parameters: []v1.Parameter: v1.Parameter.Value: ReadString: expects " or n, but found f, error found in #10 byte of ...|,"value":false}]}|..., bigger context ...|10"},{"name":"SUBSCRIPTION_SYNC_ENABLED","value":false}]}|...
```

ENT-4100: Fix syntax issue with capacity template causing CI deployment failure

---

src/main/resources/liquibase/202107140929-ent-4055-cleanup-event-data.xml
src/main/resources/liquibase/changelog.xml

When adding support for instance_hours metering, we changed
the event_source and event_type to be more metric specific.
After it was deployed, when metrics gathering happens
the metrics for a given month would include any older events
with the old static source and type, causing the instance
hours to be doubled.
This patch adds a liquibase changeset that re-aligns the
event table's data with what is now expected in terms of
event_type and event_source.
Because there are environments that already have the
instance_hours functionality running, this patch is a
little cumbersome.
First the unique constraint on the events table has to be
removed because converting old records to the new style
can cause duplicate records once the data updates are run.
We then need to remove the duplicates and …

ENT-4055: Update event source/type in existing data

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorkerConfiguration.java

Remove redundant kafkaConsumerRegistry from SubscriptionWorkerConfiguration as there is an existing one in KafkaConfiguration
Fix issue caused by https://issues.redhat.com/browse/ENT-4145

Remove redundant kafkaConsumerRegistry 

---

src/main/java/org/candlepin/subscriptions/exception/mapper/BaseExceptionMapper.java
src/main/java/org/candlepin/subscriptions/logback/OnMdcEvaluator.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/resteasy/EnumParamConverterProvider.java
src/main/resources/logback-spring.xml

The reason for this is that frequently the location an exception is
created is quite distant from the location where it is logged.  Our
exceptions are generally logged in the BaseExceptionMapper class but the
application class that threw the exception has no way of communicating
that the exception thrown is mundane and does not warrant a stacktrace.
The MDC (mapped diagnostic context) is a thread local data structure
that we can use as a communications channel.
This commit creates an OnMdcEvaluator that suppresses stacktraces from
error log messages based on the content of the MDC.  The intent is for
the developer to drop a known key set to "true" into the MDC at the time
an exception is thrown.  If the OnMdcEvaluator is set to look for that
key, the stacktrace will be suppressed.
This …

Suppress certain stacktraces from error messages.

---

rhsm-client/src/test/java/org/candlepin/subscriptions/conduit/rhsm/client/X509ApiClientFactoryTest.java

OpenJDK behavior changed w/ https://bugs.openjdk.java.net/browse/JDK-8263435
11.0.12 onwards produces a cause of SocketException, older produces SSLException.
Using IOException (superclass of both) makes the test less brittle.
Notably, this test fails currently w/ latest openjdk... I noticed the
test passes with downgraded openjdk-11-java package. This modification
will pass with either version.

Make client cert missing test assert IOException

---

src/main/java/org/candlepin/subscriptions/metering/job/MeteringJob.java
src/main/java/org/candlepin/subscriptions/metering/profile/MeteringJobProfile.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/MetricProperties.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManager.java
src/main/resources/application-metering-job.yaml
src/test/java/org/candlepin/subscriptions/metering/job/MeteringJobTest.java

Since we require that the job runs each hour, if a required
service should go down when the job is run, we should retry
the operation to ensure that we do not miss a metrics update.
This was done in an attempt to avoid issues such as the one
outlined in: ENT-3815
A simple way of testing retry is to stop the token refresher pod and start the app with the job profile. The job will fail and will begin to retry. Restart the refresher pod and the job should start working correctly.

ENT-3815: Add retry to MeteringJob

---

swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacity.java

- Capacity calculation changes made after ENT-2659 and ENT-2660 introduced a bug where SubscriptionCapacity did not take multiply subscription quantity.
- This PR fixes that bug

Fix socket and cores calculation include quantity

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/SubscriptionResource.java
src/test/java/org/candlepin/subscriptions/resource/SubscriptionResourceTest.java

For MVP, the UI will not allow customers to filter by dates to get the skuCapacityReport. Updated the beginning and ending fields to be Nullable.

Make report beginning and ending not required 

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationConfiguration.java
src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationWorker.java
src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/capacity/IngressResource.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceConfiguration.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorker.java
src/main/java/org/candlepin/subscriptions/util/UtilConfiguration.java
swatch-core/src/main/java/org/candlepin/subscriptions/util/HawtioConfiguration.java

Mostly issues introduced in #500.
To reproduce, first you need a very specific set of env vars.
capacity-ingress has issues, because it has different ports for management (8080) and ingress (8443) when deployed in our OpenShift environments. `MANAGEMENT_SERVER_PORT=8081` mimics this.
marketplace deployment had issues related to missing beans from the `capacity` package.
Testing
-------
```
MANAGEMENT_SERVER_PORT=8081 DEV_MODE=false SPRING_PROFILES_ACTIVE=capacity-ingress ./gradlew :bootRun
```
fails to start without this PR.
Others have issues because `SubscriptionServiceConfiguration` had `@Profile("capacity-ingress")` added.
```
DEV_MODE=false SPRING_PROFILES_ACTIVE=marketplace ./gradlew :bootRun
```
fails to start without this PR.

Fix issues with missing beans

---

README.md

Instead of `You can also use docker if don't want to or are unable to use podman` it was `You can also use docker if don't want to or are unable to use docker` before. This PR fixes that typo.

Update README to fix typo where I said docker instead of podman

---

build.gradle
swatch-system-conduit/build.gradle

https://issues.redhat.com/browse/ENT-4235
Happened because we missed pulling in the jackson provider for resteasy, so the client wasn't able to deserialize the JSON returned by the client.
NOTE: Using `RHSM_USE_STUB=true` does not exercise the resteasy response handling... which is probably why this wasn't caught in development.
Testing
-------
I found the easiest way to reproduce and test the fix was to use wiremock standalone to mock an api response. Download the wiremock standalone jar:
```
curl -O https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8-standalone/2.30.1/wiremock-jre8-standalone-2.30.1.jar
```
Create a mappings file for wiremock to configure it to return a canned response to the feed API endpoint:
```
mkdir mappings
cat <<EOF > mappings/rhsm.json
{ …
```

ENT-4235: swatch-system-conduit: Add resteasy-jackson2-provider

---

src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationConfiguration.java
src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/test/java/org/candlepin/subscriptions/task/TaskWorkerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskProducerConfiguration.java

https://issues.redhat.com/browse/ENT-4234
Run the following ways (to mimic profiles used during deployment).
Each should start the application successfully. The job profiles will automatically exit; running services will need to be interrupted/killed manually.
```
SPRING_PROFILES_ACTIVE=api ./gradlew :bootRun
SPRING_PROFILES_ACTIVE=capacity-ingress ./gradlew :bootRun
SPRING_PROFILES_ACTIVE=capture-hourly-snapshots,kafka-queue ./gradlew :bootRun
SPRING_PROFILES_ACTIVE=capture-snapshots,kafka-queue ./gradlew :bootRun
SPRING_PROFILES_ACTIVE=liquibase-only ./gradlew :bootRun
SPRING_PROFILES_ACTIVE=marketplace,kafka-queue ./gradlew :bootRun
SPRING_PROFILES_ACTIVE=metering-job,kafka-queue ./gradlew :bootRun
SPRING_PROFILES_ACTIVE=openshift-metering-worker,kafka-queue ./gradlew :bootRun …
```

ENT-4234: Move kafka producer beans for capacity reconciliation

---

build_deploy.sh

https://issues.redhat.com/browse/ENT-4284
Basically the immediately following push commands fail because they try to push images that weren't tagged correctly.
Testing
--------
Because it's inconvenient to log into quay if you haven't before, I recommend simply prefixing the docker commands in `build_deploy.sh` with `echo `, and then running as ` QUAY_USER=foo QUAY_TOKEN=foo sh build_deploy.sh`.
Observe the updated commands echoed:
```
+ echo docker --config=/home/khowell/github/rhsm-subscriptions/.docker tag quay.io/cloudservices/swatch-system-conduit:7779a51 quay.io/cloudservices/swatch-system-conduit:latest
docker --config=/home/khowell/github/rhsm-subscriptions/.docker tag quay.io/cloudservices/swatch-system-conduit:7779a51 quay.io/cloudservices/swatch-system-conduit:latest
+ echo …
```

ENT-4284: build_deploy.sh: Fix tagging commands for subprojects

---

src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
swatch-core-test/src/main/resources/application-test.yaml

This makes the topic names follow a pattern established for other topics.
The topic names are [merged into platform-mq](https://github.com/RedHatInsights/platform-mq/pull/148). This will make the names match in swatch.

Update kafka topic names for sub sync and capacity reconciliation

---

src/main/java/org/candlepin/subscriptions/event/EventController.java
src/main/java/org/candlepin/subscriptions/jmx/EventJmxBean.java
src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategyTest.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java

[Resolves ENT-4113](https://issues.redhat.com/browse/ENT-4113)
When a re-tally occurs, we make sure that any existing
snapshots are re-aligned with the existing events. We
reset the appropriate snapshot measurements to 0.0 when
a matching event no longer exists to ensure that
marketplace gets notified that the measurement has
changed.
This PR also provides changes to the EventJmxBean that allows for
better testing of the changes in this PR.
Ensure you have a fresh DB and run the application.
```bash
USER_USE_STUB=true PROM_URL="http://localhost:8082/api/metrics/v1/telemeter/api/v1" DEV_MODE=true ./gradlew clean bootRun
```
**NOTE:** MAKE SURE THAT YOU HAVE OPTED IN THE ACCOUNT NUMBER THAT IS USED IN THE FAKE DATA: 941133 
**NOTE:** The _**init_all_events.json**_ file can be downloaded …

ENT-4113: Properly re-align tally when events change

---

src/main/java/org/candlepin/subscriptions/security/ApiSecurityConfiguration.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsServiceTest.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationProviderTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/JolokiaActuatorConfiguration.java

https://issues.redhat.com/browse/ENT-4296
Testing
-------
Run with dev mode off (you may need to edit
`~/.config/spring-boot/spring-boot-devtools.yaml` or other ways you have
dev mode turned on).
```
DEV_MODE=false RHSM_USE_STUB=true ./gradlew swatch-system-conduit:bootRun
```
Confirm you see
```
Origin & Referer checking (anti-csrf) enabled for .redhat.com:443
```
in the logs (confirms you successfully turned dev mode off).
First try `release` branch, then try this branch.
```
curl \
-H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhc3NvY2lhdGUiOnsiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIn0sImF1dGhfdHlwZSI6InNhbWwtYXV0aCIsInR5cGUiOiAiQXNzb2NpYXRlIn19Cg==' \
-H "Origin: https://cloud.redhat.com" \
-H "Content-Type: application/json" \
-d '{"type":"exec","mbean": …
```

ENT-4296: Add missing beans to jolokia security config

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/capacity/files/ProductWhitelist.java
src/main/java/org/candlepin/subscriptions/product/OfferingJmxBean.java
src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
src/main/java/org/candlepin/subscriptions/product/OfferingSyncTask.java
src/main/java/org/candlepin/subscriptions/product/OfferingWorker.java
src/main/java/org/candlepin/subscriptions/product/OfferingWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/product/ProductConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/job/OfferingSyncConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/job/OfferingSyncJob.java
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/files/ProductWhitelistTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingJmxBeanTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingWorkerTest.java
swatch-core-test/src/main/resources/application-test.yaml
swatch-core/src/main/resources/swatch-core/application.yaml
templates/rhsm-subscriptions-scheduler.yml

Offerings will periodically sync via specifications in templates/rhsm-subscriptions-scheduler.yml. The job will run every 24-hours and enqueues all SKUs listed in the allowlist to be synced with upstream. Because there was yet no kafka message tasking set up to sync offerings, that is added as part of this commit.
To test the enqueueing functionality:
- Create a product allowlist file with a handful of entries. Example
allowlist.csv file:
```
MW0030
MW01484
MW01485
RH00604F5
RH00618F5
RH0180191
RH3413336
```
- Point to that allowlist.csv file in src/main/resources/application-worker.yaml:
```
...
rhsm-subscriptions:
product-whitelist-resource-location: file:/path/to/allowlist.csv
...
```
- Make sure swatch-core-src/main/resources/swatch-core/application.yaml, product section, has the …

ENT-4259 Periodically sync offerings

---

src/main/java/org/candlepin/subscriptions/tally/job/OfferingSyncConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/job/OfferingSyncJob.java
src/main/java/org/candlepin/subscriptions/tally/job/SubscriptionSyncJob.java

This is to prevent any beans the jobs use from being pulled in when other profiles are active.
Also adds "org.candlepin.subscriptions.tally.job" to the OfferingSyncConfiguration component scan so that the bean can be properly loaded when offering-sync profile is active.

ENT-4259 Add profiles to offering and subscription sync jobs

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

Add system profile arch to begin leverage for vCPU counting.
Add logic for for x86 virtual guests to get a more accurate count of vCPUs.
Add test case to test method within the normalize workflow.
Refactor vCPU counting to account for odd number value of cpu.

Add logic for vCPU counting of virtual x86 cpu.

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java

Update naming for sort parameters and fields in Json response for Subscription table api to be consistent with other apis
The final agreed upon names:
next_event_date
next_event_type
service_level
Also updated the tag for this API to be 'subscriptions'
To test, startup application locally and review update at http://localhost:8080/api-docs/index.html#/

Subscription table API naming updates

---

src/test/java/org/candlepin/subscriptions/exception/mapper/WebApplicationExceptionMapperTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/mapper/BaseExceptionMapper.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/mapper/WebApplicationExceptionMapper.java

https://issues.redhat.com/browse/ENT-3284
https://issues.redhat.com/browse/ENT-3952
I made two adjustments:
1. Use WebApplicationException's message as the error title, and the
wrapped exceptions message as the error detail (if present).
2. Log any 4xx errors (client errors) at WARN level instead of ERROR.
Testing
-------
Run the application via `RBAC_USE_STUB=true ./gradlew :bootRun`.
Try both:
```
curl \
'http://localhost:8080/api/rhsm-subscriptions/v1/foobar' \
-H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo=' \
| jq
curl \
'http://localhost:8080/api/rhsm-subscriptions/v1/capacity/products/OpenShift%20Container%20Platf …
```

ENT-3284, ENT-3952: Adjust WebApplicationException error handling

---

api/rhsm-subscriptions-api-spec.yaml

As part of a PR merged recently, I unintentionally updated subscription table api to be tagged under capacity and capacity related api to be tagged under subscription. This PR fixes that. It also updates the SkuCapacityReport examples to reflect the latest naming for next_event_date, next_event_type and service_level.

Fix issue with subscription table api tags 

---

templates/rhsm-subscriptions-capacity-ingress.yml

Enabling subscription sync by default in all environments. This [PR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/25401) will allow us to toggle it off as needed in higher envs

Enable subscription sync by default

---

src/main/java/org/candlepin/subscriptions/product/OfferingJmxBean.java
src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
src/main/java/org/candlepin/subscriptions/product/OfferingWorker.java
src/main/java/org/candlepin/subscriptions/product/SyncResult.java
src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java
src/test/java/org/candlepin/subscriptions/product/OfferingJmxBeanTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingWorkerTest.java
src/test/java/org/candlepin/subscriptions/product/UpstreamProductDataTest.java

This adds a method that was missing in the implementation for a different ticket, ENT-2664. Since this simplifies how to sync an
offering, the callers OfferingJmxBean and OfferingWorker are updated to use the new method. Unit tests have been moved around as a result: All of the conversion tests are now in UpstreamProductDataTest. Tests for if syncing should happen or not will remain in OfferingSyncCiontrollerTest.
Since syncing is only exposed by that one method, the logging around syncing is updated to make it easier to determine if an offering has been synced or not synced and why.

ENT-4319 Add syncOffering(sku) to OfferingSyncController

---

templates/rhsm-subscriptions-scheduler.yml

In a previous commit the allowlist was added to the application config but the volume was not mounted. This adds the allowlist volume.

Add allowlist volume to offering-sync cron config

---

src/test/java/org/candlepin/subscriptions/deployment/ApiDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/CapacityIngressDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/CaptureHourlySnapshotsJobDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/CaptureSnapshotsJobDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/LiquibaseDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/MarketplaceWorkerDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/MeteringJobDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/MetricsWorkerDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/OfferingSyncJobDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/PurgeSnapshotsJobDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/SubscriptionSyncJobDeploymentTest.java
src/test/java/org/candlepin/subscriptions/deployment/WorkerDeploymentTest.java
src/test/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskQueueSchemaRegistryTest.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/deployment/OrgSyncJobDeploymentTest.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/deployment/SystemConduitDeploymentTest.java

The idea is that each "Deployment Test" simply instantiates the context as is done in deployment instantiates with all necessary beans.
Note I also had to limit the TestConfiguration defined as an inner class in KafkaTaskQueueSchemaRegistryTest to the `kafka-test` profile as it was causing some issues otherwise.

Add deployment tests for each profile

---

src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

Adjust vCPU counting logic to set core values in the InventoryHost. So the same values are consistent within rhsm.
https://issues.redhat.com/browse/ENT-4348
Add new test case for rhsm facts vCU logic
Set the effective cores for virtual x86 hosts in the InventoryHost cores.

Bugfix that addresses ENT-4348.

---

templates/rhsm-subscriptions-scheduler.yml

This will set SUBSCRIPTION_SYNC_ENABLED to true for the subscription-sync cron job. With the updates to app-interface (https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/25597) which sets it to false for QA, STAGE, and PROD, this allows only CI to run the periodic subscription sync, until we're ready.

ENT-3376 Enable subscription sync for cron job

---

src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java
src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java
src/test/java/org/candlepin/subscriptions/product/UpstreamProductDataTest.java

Offerings should only sync (that is, be saved to the db) when the
fetched offering differs from the already synced offering. However,
offerings were always being synced.
The cause turned out to be that when the fetched offering is assembled
in UpstreamProductData, if there are no Usage or ServiceLevel fields
set, then they would be null. However, when the same offering is loaded
from the DB, those null fields would instead be the EMPTY enum value
instead.
The fix is to make UpstreamProductData never make Usage or ServiceLevel
be null, but instead be EMPTY.

ENT-4371 Sync EMPTY Usage and ServiceLevel not null

---

templates/rhsm-subscriptions-scheduler.yml

Not having true in single-quotes for the SUBSCRIPTION_SYNC_ENABLED param
in rhsm-subscriptions-schedule.yml apparently causes values in Openshift
deployment:
https://github.com/RedHatInsights/rhsm-subscriptions/pull/587#issuecomment-922917866

ENT-3376 Wrap true in single-quotes

---

src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java
src/main/java/org/candlepin/subscriptions/event/EventController.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java

https://issues.redhat.com/browse/ENT-4372
Otherwise, we pull in whole accounts which is wasteful (and causes
problematic amounts of load).

ENT-4372: Skip hourly processing if there are no events

---

src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java

Addressing the issue reported in https://issues.redhat.com/browse/ENT-4377.
Currently we set the value of count in meta to be equal to whatever is matched + limit applied. This PR updates that to be equal to the no of records that are matched and ignores the limit.

ENT-4377: Fix count returned in meta to be equal to the no of matched records

---

src/main/resources/application.yaml

Without this config option, subscription-sync OpenShift cron job cannot
enqueue subscription sync tasks.
For now, the subscription-sync-enabled option will remain in
application-test.yaml and application-capacity-ingress.yaml. Eventually
the option will become obsolete and can be removed from code and all
configs, or the subscription syncing functionality is fully tested and
deployed and the option can default to true and be removed from the
application-*.yaml files.

ENT-3376 Add subscription-sync-enabled to application.yaml

---

templates/rhsm-subscriptions-capacity-ingress.yml

Bumping up capacity-ingress KAFKA_MESSAGE_THREADS so it can process the
subscription syncs in less than a day.

ENT-3376 Increase capacity ingress kafka threads

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java

Currently each subscription task is taking longer than kafka timeouts
allow (currently 1hr per task). Reducing page size from 2000 to 100
for now so that the same tasks do not keep blocking the processing of
subscription sync tasks.

ENT-3315 Reduce sub-sync page size to 100

---

clients/marketplace-client/marketplace-api-spec.yaml
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceJmxBean.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProducer.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProperties.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceUsageSubmissionException.java
src/main/resources/application-marketplace.yaml
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceProducerTest.java
templates/marketplace-worker.yml

https://issues.redhat.com/browse/ENT-3870
Currently, the only way to detect a submission failed due to lack of
amendment support is to read the error message.
I re-added a dev-only endpoint in order to directly submit Marketplace
usage submission requests.
I also changed the logging to be more useful generally (see example
response below, generally `data`->`*`->`message` has useful info).
<details>
<summary>
Currently the amendment not supported response looks like
</summary>
```json
{
"status": "failed",
"message": "One or more events are in progress or failed to process.",
"errorDetails": [],
"data": [
{
"status": "failed",
"message": "Requested feature (amendments) is not available on this environment",
"batchId": REDACTED,
"payload": {
"eventId": REDACTED,
"_eventId": REDACTED, …
```

ENT-3870: Gracefully handle lack of amendment support

---

src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java

If an offering's data is changed in the course of getting synced, then
any capacities relating to that offering should be reconciled.
Because reconciling capacities could add time to an offering sync, and
because there could be many offerings to sync each day, a reconciliation
job will be enqueued into kafka per each sku.
Test overview:
- Pick an offering that has at least one or more customers
- Sync the offering, if it isn't already in the swatch DB
- Sync the subscriptions of at least one of those customers
- Change one of the details of the offering in the swatch DB
- Re-sync the offering. Because the offering was changed, the
capacities for the customer should be reconciled (async).
- Sync the offering a third time. Because the offering was not changed,
capacities for the customer …

ENT-4373 Reconcile capacities when offering synced

---

src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepositoryTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewSpecification.java

Issue: When filtering by UOM we need the JPA query to do an OR between physical and virtual sockets(or cores), but the current impl does an AND restricting the results returned if some subscription capacity records only have the virtual or physical values populated

Fix bug in filtering by UOM 

---

src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/test/java/org/candlepin/subscriptions/util/DateRangeTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/util/DateRange.java

When realigning snapshots, make sure that we only
clear the finest granularity snapshots that are
within the range of the tally. Otherwise, events
outside of that range will not be reflected in
tally.
https://issues.redhat.com/browse/ENT-4403
Start with a fresh database, then run the application.
```
dropdb -U rhsm-subscriptions rhsm-subscriptions && createdb -U rhsm-subscriptions rhsm-subscriptions
```
```
USER_USE_STUB=true DEV_MODE=true ./gradlew clean bootRun
```
1.  Opt in your account.
```
curl 'http://localhost:8080/actuator/hawtio/jolokia/' \
-H 'Content-Type: application/json' \
-d '{"type":"exec","mbean":"org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean","operation":"createOrUpdateOptInConfig(java.lang.String,java.lang.String,boolean,boolean,boolean)","argument …
```

ENT-4403: Fixed baseline hourly tally

---

src/test/java/org/candlepin/subscriptions/metering/RhosakTagProfileTest.java
swatch-core/schemas/event.yaml
swatch-core/schemas/tally_summary.yaml
swatch-core/src/main/resources/tag_profile.yaml

https://issues.redhat.com/browse/ENT-4333
This PR configures/enables the metering of RHOSAK data storage, which will produce metering events for this metric.
1. Get connected to the testing telemeter instance (see: [Connecting To Observatorium](https://docs.engineering.redhat.com/display/ENT/Connecting+to+Observatorium+to+Fetch+Prometheus+Metrics) )
2. Add 'Eval' to the PromQL template in **_application-openshift-metering-worker.yaml_** so that the Kafka cluster metrics get picked up by the query.
```diff
-            min_over_time(#{metric.queryParams[prometheusMetadataMetric]}{product="#{metric.queryParams[product]}", ebs_account="#{runtime[account]}", billing_model="marketplace", support=~"Premium|Standard|Self-Support|None"}[1h])
+ …
```

ENT-4333: Add metering configuration for RHOSAK data storage

---

src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceProperties.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepository.java
templates/rhsm-subscriptions-capacity-ingress.yml

The following changes are made to improve performance on per-org
subscription syncs:
- Use SubscriptionCapacityRepository's
findByKeyOwnerIdAndKeySubscriptionIdIn(
String ownerId, List<String> subscriptionIds) method instead of
findByKeySubscriptionId(String subscriptionId), since the former
can take advantage of the (owner_id, product_id, subscription_id)
primary key
- Subs expired longer than 2 months or future dated subs more than 2
months from now will not be synced.
- Fetch more subs-per-page (again)
To test locally:
```bash
curl 'http://localhost:8080/actuator/hawtio/jolokia/?maxDepth=7&maxCollectionSize=50000&ignoreErrors=true&canonicalNaming=false' \
-H 'Accept: application/json' \
-H 'Content-Type: text/json' \
--data-raw …
```

ENT-4406 Speed up per-org subscription syncs

---

src/test/java/org/candlepin/subscriptions/metering/RhosakTagProfileTest.java
swatch-core/src/main/resources/tag_profile.yaml

https://issues.redhat.com/browse/ENT-4333
This PR configures/enables the metering of RHOSAK data storage, which will produce metering events for this metric.
1. Get connected to the testing telemeter instance (see: [Connecting To Observatorium](https://docs.engineering.redhat.com/display/ENT/Connecting+to+Observatorium+to+Fetch+Prometheus+Metrics) )
2. Add 'Eval' to the PromQL template in **_application-openshift-metering-worker.yaml_** so that the Kafka cluster metrics get picked up by the query.
```diff
-            min_over_time(#{metric.queryParams[prometheusMetadataMetric]}{product="#{metric.queryParams[product]}", ebs_account="#{runtime[account]}", billing_model="marketplace", support=~"Premium|Standard|Self-Support|None"}[1h])
+ …
```

ENT-4334 Configured RHOSAK Cluster Hours metering

---

api/rhsm-subscriptions-api-spec.yaml
bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/java/org/candlepin/subscriptions/resource/ReportCriteria.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/resteasy/PageLinkCreator.java
src/main/java/org/candlepin/subscriptions/tally/filler/ReportFiller.java
src/main/java/org/candlepin/subscriptions/tally/filler/ReportFillerAdapter.java
src/main/java/org/candlepin/subscriptions/tally/filler/ReportFillerFactory.java
src/main/java/org/candlepin/subscriptions/tally/filler/TallyReportDataPointAdapter.java
src/main/java/org/candlepin/subscriptions/tally/filler/TallySnapshotAdapter.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/resteasy/PageLinkCreatorTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/DailyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/HourlyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/MonthlyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/QuarterlyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/WeeklyReportFillerTest.java
src/test/java/org/candlepin/subscriptions/tally/filler/YearlyReportFillerTest.java

https://issues.redhat.com/browse/ENT-4380
In doing so, I had to refactor a couple of things:
1. I refactored ReportFiller to operate on a `List<T>` where `T` can be any type, but an adapter must be built to specify how to create default `T`, extract date from `T`, and to compare `T`.
2. I refactored the parameter handling so that parsing/validation of params is done in a shared function. In doing so, I introduced a parameter object I named ReportCriteria.
Future work could:
- use `ReportCriteria` more directly in the repo.
- use `ReportCriteria` in CapacityResource.
Also, note one small deviation from the card as written: talking with @cdcabrera, he suggested use of `total_monthly` rather than `monthly_total`.
Testing (HBI-based tally)
1. Start the application: …

ENT-4380: Implement new Tally API

---

.gitignore
bin/hawtio-proxy.sh

https://issues.redhat.com/browse/ENT-4460
Essentially this uses nginx to force a couple headers and "serve" hawtio on the path turnpike would.
The script emits a message like:
```
Proxying pod marketplace-worker-241-chqb4 port 8080 at path /app/rhsm-marketplace/actuator/hawtio so that it can be reached via http://localhost:8085/app/rhsm-marketplace/actuator/hawtio
```
which shows the URL hawtio can be reached at.

ENT-4460: Add script to reach hawtio via oc-proxy and nginx

---

deploy/clowder.md
deploy/rhsm-clowdapp.yaml

https://issues.redhat.com/browse/ENT-4050
The initContainer image needs to be different than conduit, because the conduit image doesn't do liquibase (and eventually we may have a separate liquibase image for other deployments as well).
Also renamed the deployment to system-conduit for clarity
Testing
-------
After setting up bonfire, deploy to an ephemeral environment. I use increased timeout. Also, it may be worth commenting out other deployments.
```
bonfire deploy --no-remove-resources rhsm-subscriptions -t 9000
```
Then use the hawtio proxy script and try to sync an org.

ENT-4050: clowder: Set conduit initContainer image, RHSM_URL

---

bin/events.csv
bin/import_events.py
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionIdProvider.java
src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java
src/main/resources/application-marketplace.yaml
src/main/resources/liquibase/202110211313-add-rhosak-offering.xml
src/main/resources/liquibase/202110211314-add-description-column-to-offering.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/OfferingRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceSubscriptionIdProviderTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java
src/test/java/org/candlepin/subscriptions/product/UpstreamProductDataTest.java
src/test/java/org/candlepin/subscriptions/registry/TagProfileFactoryTest.java
src/test/java/org/candlepin/subscriptions/registry/TagProfileTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityView.java
swatch-core/src/main/java/org/candlepin/subscriptions/registry/TagProfile.java

There were quite a few things addressed in this PR in order to send the usage to marketplace.
* Removed the ProductProfileRegistry from the MarketplaceSubscriptionIdProvider
so that product config can all be done in the tag profile. Also updated the
offering lookup query to be based on Offering name instead of role.
* Added rhosak tag to eligible-swatch-product-ids in the marketplace config so that
it will be included in metrics that are sent to marketplace.
* Updated the product name mappings in the tag profile config to reflect the values
that will come from the product service to be ready for turning on subscription
table functionality. Also added a RHOSAK mapping.
* Updated the offering product names in DB for OCP and OSD, as well as added RHOSAK
* Set Offering name from PRODUCT_NAME …

ENT-4463 Marketplace Fixes for RHOSAK

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java

This PR is to address [ENT-4383](https://issues.redhat.com/browse/ENT-4383)
Profiles use for Testing
```
DEV_MODE=true;
USER_USE_STUB=true;
PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1
```
Get connected to the testing telemeter instance:
Uncomment 'Eval' in application-openshift-metering-worker.yaml so that the Kafka cluster metrics get picked up by the query.
```
min_over_time(#{metric.queryParams[prometheusMetadataMetric]}{product="#{metric.queryParams[product]}", ebs_account="#{runtime[account]}", billing_model="marketplace", support=~"Premium|Standard|Self-Support|None|Eval"}[1h])
```
1. Gather measurements from Telemeter:
```
curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d …
```

ENT-4383: Implementation of InstanceAPI

---

deploy/clowder.md

The environment ephemeral-41 has an rhsm-capacity-ingress pod running successfully that was done using the steps added to the clowder.md file as part of this PR.

ENT-4052: Validate/fix capacity ingress clowder deployment

---

deploy/clowder.md
deploy/rhsm-clowdapp.yaml
deploy/rhsm-eph-clowdenv.yaml

https://issues.redhat.com/browse/ENT-4053
activeDeadlineSeconds ensures they are terminated if they hang, and for metrics-cron, it ensures that the sidecar doesn't keep the job from finishing.
Note that activating sidecars requires a change the ClowdEnvironment. I added a note to clowder.md about that.
Note that offering-sync needs the allowlist populated (see #659).

ENT-4053 Add activeDeadlineSeconds to jobs, add sidecars

---

src/main/resources/liquibase/202110211313-add-rhosak-offering.xml

https://issues.redhat.com/browse/ENT-4507
Essentially, this change checks to see if the SKU has been synced
already, and marks the change as run if it has.
Testing
-------
Run w/ `SPRING_PROFILES_ACTIVE=liquibase-only ./gradlew :bootRun`...
1. Run w/ this branch to get the offering added via liquibase.
2. Remove the record that indicates the changeset was run:
```
echo "delete from databasechangelog where id='202110211313-1'" | psql -h localhost -U rhsm-subscriptions
```
3. Using `develop`, run liquibase and observe the error.
4. Using this branch, run liquibase, and observe no error.

ENT-4507 Liquibase: check if RHOSAK SKU has been synced

---

build_deploy.sh
cicd_common.sh
pr_check.sh
unit_test.sh

https://issues.redhat.com/browse/ENT-4482
Note that I added a stub unit_test.sh, as junit XML is expected by the Jenkins job which runs the pr_check.sh script
I modified the existing build_deploy.sh script to use common logic, defined in cicd_common.sh to detect services. With this change, adding a new component to the codebase is as simple as adding a Dockerfile to a subdirectory.
Testing
-------
To see the commands that will happen, you can insert:
```
oc() {
echo "oc $@"
}
docker() {
echo "docker $@"
}
podman() {
echo "podman $@"
}
```
to `pr_check.sh` (before any other commands). This will defang those commands, outputting the commands with arguments, instead of actually executing them.
Then to mimic a run from CI:
```
ghprbPullId=42 RH_REGISTRY_USER=foo RH_REGISTRY_TOKEN=bar …
```

ENT-4482: Add temporary quay image build/push to pr_check.sh

---

clients/marketplace-client/marketplace-api-spec.yaml
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProducer.java

https://issues.redhat.com/browse/ENT-4236
I also added chargeId as a field to the UsageMeasurement, as I found during experimentation that the `metricId` is returned as `chargeId`.
Testing
-------
Run (replace `$MARKETPLACE_API_KEY` with a sandbox token):
```
MARKETPLACE_URL=https://sandbox.marketplace.redhat.com \
MARKETPLACE_API_KEY=$MARKETPLACE_API_KEY \
./gradlew bootRun
```
Using the [marketplaceJmxBean](http://localhost:8080/actuator/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.marketplace-MarketplaceJmxBean-marketplaceJmxBean), submitUsage method, submit the following JSON (can create a fresh uuid via `uuidgen` as needed):
```json
{
"data": [
{
"start": 1637011016000,
"end": 1637011076000,
"subscriptionId": "this_is_not_a_real_sub!!",
"eventId": …
```

ENT-4236 Add payload to marketplace response object

---

src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManagerTest.java
templates/rhsm-subscriptions-scheduler.yml

An hourly metric value returned from prometheus for a query at 12pm - 12:59:59.999,
actually represents the metric value calculation from 11am -12pm and therefore we
set the event record's start timestamp at 11am.
Before this change, our jobs run NOW - 5h for metrics gathering and NOW - 6h for
tallying the metrics. Because of this, and the 1h event record timestamp offset,
the tally process is querying for metric events that are CURRENTLY being gathered!
Lets say that it is 12pm NOW and the jobs run. Metrics will be gathered for
7am - 7:59:59.999 and events will be created and stored with a start timestamp of
6am. The tally runs at the same time and will query for events at 6am, meaning each
tally is actually querying for metrics that may or may not exist! This tally should
occur at 5am. …

Consider Event timestamp offset when tallying hourly

---

swatch-core/src/main/java/org/candlepin/subscriptions/security/RestAccessDeniedHandler.java

AccessDenied can happen whenever a user attempts access when an organization has
not opted in. They get a warning back with the reason. As this is not an
application error we should reduce the log level so that real errors can be found
in the logs more easily.

Reduce log level for AccessDenied errors.

---

build.gradle
src/test/java/org/candlepin/subscriptions/capacity/PoolIngressControllerTest.java
src/test/java/org/candlepin/subscriptions/retention/TallyRetentionControllerTest.java
src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsServiceTest.java
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java

To be precise:
```
sed -i s/verifyZeroInteractions/verifyNoInteractions/ $(git grep -l verifyZeroInteractions)
sed -i s/mainClassName/mainClass/ build.gradle
```
`verifyZeroInteractions` was removed from the mockito version pulled in by Spring Boot 2.6. Hope to see the 2.6 dependabot PR pass once this is merged (specifically the dependencies one).
`mainClassName` was removed. Hope to see the 2.6 dependabot PR pass once this is merged (specifically the gradle plugin one).

Replace deprecated methods for Spring Boot 2.6

---

src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java

Instead of `all`
We're unsure why, but it seems when multiple rows are returned by the
subquery, at least in prod (but not locally :-/), we get no results.

Change subs query for marketplace ID to use in

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

https://issues.redhat.com/browse/ENT-4520
This PR is to zero out Marketplace instances to zero when `is_marketplace == true`.
Testing (HBI-based tally)
1.Environment Variables:
```
SPRING_PROFILES_ACTIVE=worker,api DEV_MODE=true
```
2. Local database setup:
Login into the localhost db insights role (if this is confusing just ping me).
Next insert mock data in DB
```
insert into hosts(
id,
account,
display_name,
created_on,
modified_on,
facts,
canonical_facts,
system_profile_facts,
stale_timestamp,
reporter
) values (
gen_random_uuid(),
'account123',
'marketplace-test',
now(),
now(),
'{"rhsm": {"orgId": "org123", "CPU_CORES": 4, "CPU_SOCKETS": 1, "IS_VIRTUAL": true,"SYNC_TIMESTAMP": "2020-07-01T00:00:00Z"}}'::jsonb,
'{"subscription_manager_id": "$submanId", …
```

Zero out Marketplace instances

---

src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java

https://issues.redhat.com/browse/ENT-4488
When producing tally summaries, skip any that do not have
measurements associated with them.
This was done to prevent marketplace API errors when sending
an event with 0 measurements. This can happen when event metrics
are updated via the JMX endpoint and a metric event was no longer
found during the refresh.
It is easiest to start with a fresh DB, otherwise you need to delete all of the snapshots and events for the account 'account123'.
```sql
delete from tally_snapshots where account_number='account123';
delete from events where account_number='account123';
```
```bash
$ SUBSCRIPTION_USE_STUB=true USER_USE_STUB=true USER_STUB=true DEV_MODE=true PROM_URL="http://localhost:8888/api/metrics/v1/telemeter/api/v1" ./gradlew …
```

ENT-4488 Skip sending summnary with no measurements

---

bin/insert-mock-hosts

https://issues.redhat.com/browse/ENT-4616
The insert-mock-hosts script was broken after we added
the account services aggregate. Before host records are
added to the DB, we need to create an associated
account_service record in order to comply with the required
DB constraints.
From the **develop** branch, run the following and expect a constraint violation error as shown in the [linked issue](https://issues.redhat.com/browse/ENT-4616).
```
$ bin/insert-mock-hosts --account-number zing --num-physical 10 --num-hypervisors 10
```
Check out this branch (no need to re-deploy or anything like that) and run the command again. This should result in no errors. The database can be validated by checking that the DB contains the physical and hypervisor hosts for the specified account.
```
$ …
```

ENT-4616 Fix broken insert-mock-hosts script

---

bin/import_events.py

Prereq: swatch running with jmx endpoints enabled
On develop branch, running the following doesn't work and gets a 401:
```shell
cd bin
./import_events.py --file events.csv
```
Pull this branch, then run it again and it should succeed

Update import_events.py with updated jolokia URL path and port

---

swatch-core/src/main/java/org/candlepin/subscriptions/security/SecurityProperties.java
swatch-core/src/main/resources/swatch-core/application.yaml

Lombok is weird about getters/setters for booleans that have the word "is" in them.  They don't follow the same naming convention that spring expects when doing naming matching for `@ConfigurationProperties`
Example:
```
private boolean isFruit = true;
//getter generated = isFruit(): boolean
//setter generated = setFruit(boolean): void
```
For spring to match on naming convention when reading application.properties, what's expected for a setter would be `setIsFruit(boolean)`.
Because of this, the `SecurityProperties` class was never having its default values overwritten by the env vars listed in swatch-core's application.yaml

Update attribute names to play nicely with lombok generated setters

---

templates/marketplace-worker.yml
templates/metrics-worker.yml
templates/rhsm-conduit.yaml
templates/rhsm-subscriptions-api.yml
templates/rhsm-subscriptions-capacity-ingress.yml
templates/rhsm-subscriptions-worker.yml

The web port for our apps was changed to 8000 to support clowder,
so we need to also update the target ports for our service
definitions to remain on 8080 but target 8000.
Exposed web services will expose both 8080 and 8000 to support
the async update 3scale and turnpike.

Fix routing issues for our services

---

templates/rhsm-subscriptions-api.yml

Renamed the existing RBAC parameters to fall in line
with the rename done for Clowder.

Rename RBAC template parameters in API template

---

templates/rhsm-subscriptions-worker.yml

https://issues.redhat.com/browse/ENT-4661
When the template parameter was added to the deploy template,
we forgot to also pass it as an env var for the deployment.
NOTE:
* The needful has already been done for the stage environment configuration for app-interface and the issue should be fixed on the next deployment.

ENT-4661 Set DEVTEST_EVENT_EDITING_ENABLED param as env var

---

src/main/java/org/candlepin/subscriptions/resteasy/ResteasyConfiguration.java
src/main/resources/static/api-docs/index.html

https://issues.redhat.com/browse/ENT-4670
Rather than serving the openapi docs in multiple places just to make our
old scheme of hosting them at `/api-docs/openapi.yaml`, it's easier to
just point at their location served from our API root.
Closes #735

ENT-4670 Change path for openapi.yaml in swagger-ui

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryHostFactTestHelper.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

This PR is to address -> https://issues.redhat.com/browse/ENT-4347.
Remove Rhsm core & socket reference.
Adjust Unit testing to add missing data
Add new method for null normalized core & sockets.
Refacter InventoryAccountUsageCollectorTest rhsm facts.

Remove redundant facts for Core & Sockets for rshm

---

bin/insert-mock-hosts

Issue: ENT-4708
A previous commit creates a record in the account_services table.  This
table does not exist in the insights database so the script fails when
run with the `--hbi` flag.  This commit fixes the issue.

Fix insert-mock-hosts when inserting HBI records

---

docker-compose.yml

The inventory container needs to talk to both the database container (so
it needed the correct hostname) and the kafka container (where it needed
the correct hostname and for the kafka container to expose the correct
port to the internal network).

Fix podman-compose so the inventory container works

---

clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java

https://issues.redhat.com/browse/ENT-4598
Reads the distribution.version fact and sets the major and minor version numbers of the the operation system for use in HBI.

ENT-4598 Add major and minor version attributes to operating system details of HBI messages

---

deploy/rhsm-clowdapp.yaml
src/main/java/org/candlepin/subscriptions/security/ApiSecurityConfiguration.java
swatch-core/src/main/java/org/candlepin/subscriptions/util/HawtioConfiguration.java
swatch-core/src/main/resources/META-INF/spring.factories
swatch-core/src/main/resources/swatch-core/application.yaml

https://issues.redhat.com/browse/ENT-4658
* When running Hawtio on a different management port, the order of bean initialization changed such that our 
HawtioContextListener was being instantiated before the HawtioManagementConfiguration.  Since the former
depended on a bean in the latter, this caused a start up failure.
This PR changes the annotations on the HawtioContextListener so that it will load under the same circumstances the
HawtioManagementConfiguration bean loads and the former is marked ashaving a dependency on the latter.
Additionally, when management services (Spring Actuator) are run on a different port from the main application, the
management services exist in a child context descended from the main context.  So that our configuration will exist
in that same context, we …

Correct some annotations on our Hawtio customization

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/DefaultInventoryServiceTest.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java

This hotfix is to address [ENT-4347](https://issues.redhat.com/browse/ENT-4347), as conduit was still emitting cores & sockets to HBI
Remove cores & sockets from InventoryService
Refactor test cases for KafkaEnabledInventoryServiceTest & DefaultInventoryServiceTest
Testing steps
1. Run Conduit with below Environment variables
```
DEV_MODE=true;RHSM_USE_STUB=true
```
2. Use the [API ](http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.conduit.jmx-RhsmConduitJmxBean-rhsmConduitJmxBean)to create an Event.
3. Verify that the message in Kafka UI host-ingress no longer contains cores & sockets in the facts data.

Hot-fix ENT-4347: Remove remaining cores & sockets in Conduit

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapper.java
src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/main/resources/liquibase/202202041415-add-unlimited-usage-column-to-offering-table.xml
src/main/resources/liquibase/changelog.xml
src/main/resources/product-stub-data/tree-MW00210M1_attrs-true.json
src/main/resources/product-stub-data/tree-MW00210MO_attrs-true.json
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepositoryTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java
src/test/java/org/candlepin/subscriptions/product/UpstreamProductDataTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacity.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityView.java

https://issues.redhat.com/browse/ENT-4453
Fixes errors when consuming SKU's with "Unlimited" cores capacity.
Rename "has_unlimited_guest_sockets" column to "has_unlimited_usage" in subscription_capacity table
Test Steps:
- call syncOffering() method in OfferingJmxBean with sku 'MW00210MO' or other SKU with unlimited capacity. http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.product-OfferingJmxBean-offeringJmxBean

ENT-4453: Allow unlimited capacity SKU's

---

build.gradle
deploy/clowder.md
deploy/rhsm-clowdapp.yaml
src/main/java/org/candlepin/subscriptions/jmx/AccountResetJmxBean.java
src/main/java/org/candlepin/subscriptions/tally/AccountResetService.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/AccountServiceInventoryRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/SecurityProperties.java
swatch-core/src/main/resources/swatch-core/application.yaml
templates/rhsm-subscriptions-worker.yml

Related MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/31838/diffs
Test steps:
* add event & hbi data to your instance for an account
* * found the easiest way to do this is to use the `bin/insert-mock-hosts` and `bin/import_events.py` scripts
* * probably a good idea to use an account number that's not already in your database
* use JMX to initiate an hourly tally and a "regular" tally for the account number you created data for
* * ```http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.jmx-TallyJmxBean-tallyJmxBean```
* observe & take note of tally data in database
* use new JMX endpoint to initiate resetting the account by an account number
* * ```http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.jmx-A …
```

ENT-4412 Add account reset JMX method

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java

https://issues.redhat.com/browse/ENT-4431
Allows for sorting by the total capacity of virtual/physical sockets and cores.
Test Steps:
```
- curl -X 'GET' \
'http://localhost:8000/api/rhsm-subscriptions/v1/subscriptions/products/OpenShift%20Container%20Platform?sort=total_capacity&dir=asc' \
-H 'accept: application/vnd.api+json'
```

ENT-4431: add total_capacity sort param to for subscription/products api

---

deploy/rhsm-eph-clowdenv.yaml

The Kafka version used by ephemeral-base changed so we need to update
our custom ClowdEnv accordingly.
To figure this out:
1. Export the base ClowdEnv with `bonfire process-env --namespace
ephemeral-base`
2. Convert the exported JSON to YAML using an online converter or a CLI
tool of your choice
3. Diff the ephemeral-base YAML against our custom ClowdEnv and make
necessary changes

Update our modified clowd-env with new Kafka version

---

deploy/rhsm-clowdapp.yaml

The `rhsm-subscriptions-api` pod in openshift didn't list `DEV_MODE` in the Environment tab even though it was being set in the ClowdApp.  The `rhsm-subscriptions-api` deployment didn't list the env variable as a parameter.

Update ClowdApp so api deployment honors DEV_MODE env var

---

podman_run.sh
swatch-producer-aws/build.gradle

Needed to passthrough DOCKER_HOST env var, and updated the podman_run.sh script so that it starts a temporary socket/daemon, configures testcontainers to use it, and then cleans up afterwards.
Couple of interesting bits in the podman command:
1. Disable labeling to avoid selinux issues.
2. Use host networking so that testcontainers can talk to the containers it starts.

Apply fixes to make testcontainers work in Jenkins

---

podman_run.sh
swatch-producer-aws/README.adoc
swatch-producer-aws/build.gradle
swatch-producer-aws/src/test/java/com/redhat/swatch/KafkaResource.java
swatch-producer-aws/src/test/java/com/redhat/swatch/PostgresResource.java
swatch-producer-aws/src/test/java/com/redhat/swatch/TestContainerTest.java

https://issues.redhat.com/browse/ENT-4729
Introduce Testcontainers dependencies and rework podman_run.sh script to expose podman socket for running Podman in Podman on CI.

ent-4729: Setup Testcontainers for usage in tests

---

build.gradle
buildSrc/build.gradle
gradle.properties

Note we can't use latest without updating gradle.
See https://github.com/nebula-plugins/nebula-release-plugin for additional config options.
I had to update our jgit dependency for this to work.
This would mean no more maintenance of the version in a file.
http://localhost:9000/info still works well.
Testing
-------
`git fetch` to make sure you pull down the v1.0.87 tag.
Run `./gradlew assemble`. Note the filename/versions of the built artifacts, e.g.
```
1.1.0-snapshot.202203011533.uncommitted+khowell.nebula.release.d3cb990
```
Which has the following components:
* semver compatible major, minor, patch version
* timestamp of build
* repo clean/dirty status
* branch name (normalized to replace certain characters
* git commit abbreviation
With this change, we can choose to not tag …

Switch to the nebula release plugin

---

clients-core/src/main/java/org/candlepin/subscriptions/http/HttpClient.java
clients-core/src/main/java/org/candlepin/subscriptions/http/HttpClientProperties.java
clients-core/src/test/java/org/candlepin/subscriptions/http/HttpClientTest.java
clients/rhsm-client/src/test/java/org/candlepin/subscriptions/conduit/rhsm/client/RhsmApiFactoryTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/actuator/CertInfoInquisitor.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/actuator/CertInfoEndpoint.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/actuator/CertInfoEndpointTest.java

Previously we had the keystore properties bound to a File field.  I was
seeing failures when the rhsm-conduit.rhsm.keystore property was set to
empty string which could happen during unit tests that run without a
full configuration.
Using the Spring Resource abstraction avoids this issue since Spring
isn't trying to immediately create a File object.  Instead it creates a
Resource object and we later check to make sure the Resource is valid
and readable.  As a bonus, Spring will handle opening the resource as a
stream for us so we can remove some boiler plate methods in
HttpClientProperties that were doing that.

Use Spring's Resource abstraction to handle loading keystores

---

podman_run.sh

We got into a state where the CI user can't cleanup the workspace because file permissions are off. This is addressed by having the effective UID of the container process be the same as the calling user. I found a consistent way to do this for both docker and podman is by using --user=$UID along with setting the USERNS setting for podman to `keep-id`, which can conveniently be done with an env var.

Fix permissions when podman_run.sh falls back to docker

---

swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewSpecification.java

https://issues.redhat.com/browse/ENT-4765
Test Steps:
- Add a subscription with unlimited usage to an account
- Sync capacity
- Use http://localhost:8000/api-docs/index.html#/subscriptions/getSkuCapacityReport endpoint with UOM param set to either cores or sockets
- The subscriptions with unlimited usage should be returned

ENT-4765: Include unlimited usage capacities when UOM param is sent

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/DefaultInventoryServiceTest.java

Specifically, this occurs when osVersion is populated and osName is populated, but OS name does not match (case-insensitive) "red hat enterprise linux"
See #810

[HOTFIX] conduit: Fix NPE when OS is not RHEL

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/DefaultInventoryServiceTest.java

Specifically, this occurs when osVersion is populated and osName is populated, but OS name does not match (case-insensitive) "red hat enterprise linux"

conduit: Fix NPE when OS is not RHEL

---

swatch-system-conduit/build.gradle

Current R.C. is bad, because of an oversight in #783
Compare
```
podman run --rm quay.io/cloudservices/swatch-system-conduit:0c7aaf4
```
where you'll see
```
Exception in thread "main" java.lang.ClassNotFoundException: org.candlepin.subscriptions.BootApplication
```
to an image built by this PR:
```
podman build . -f swatch-system-conduit/Dockerfile -t bootjar_fix && podman run --rm bootjar_fix
```
where you won't.

Override bootJar mainClass in rhsm-conduit

---

dependencies.gradle

See comments in dependencies.gradle for details.
If interested, you can use https://github.com/dependabot/dependabot-script to check what deps it picks up. I changed https://github.com/dependabot/dependabot-script/blob/4330ff7043b6fe2bb009005e2f5b0ca9985f32f2/update-script.rb#L80 to
```rb
dependencies.each { |d| puts "#{d.name}:#{d.version}" }
exit
```
and then edited `branch`, `package_manager`, `repo_name`, and `password`, and ran as `bundle exec ruby ./update-script.rb` to see that the resteasy deps and quarkus-bom got picked up.

Ensure dependabot picks up deps w/ shared versions

---

build.gradle
buildSrc/src/main/groovy/swatch.java-conventions.gradle
swatch-core/build.gradle
swatch-system-conduit/build.gradle

swatch-producer-aws uses a QuarkusJacoco dependency that clashes with the Jacoco plugin so this PR moves the plugin from a common config to individual projects that need it.

Remove jacoco from common gradle config and move to individual projects

---

build.gradle
dependencies.gradle
swatch-producer-aws/build.gradle

By specifying repos in a central location - dependencies.gradle, dependabot knows to consult additional maven repos.
I also found that dependabot is a bit conservative with updating versions in properties; specifically, if those versions are used by more than one dep, it skips those deps. So it kind of defeats the purpose of having a versions object.
I found there is a good workaround though: using bom artifacts instead.
I checked the results against this branch by updating the dependabot-script `update-script.rb` with the following logic:
```rb
dependencies.each { |d|
checker = Dependabot::Gradle::UpdateChecker.new(
dependency: d,
dependency_files: files,
credentials: credentials,
)
if not checker.up_to_date?
if checker.latest_resolvable_version.nil?
puts "#{d.name}:#{d.version} not up …
```

Improve dependabot compatibility

---

dependencies.gradle

Note we already weren't using it, it was just left in unintentionally.
Fixes #845.

Remove obsolete gradle-avro-plugin

---

clients/build.gradle
clients/insights-inventory-client/api.spec.yaml
clients/insights-inventory-client/system_profile.spec.yaml
clients/rbac-client/openapi.json
dependencies.gradle

Update the build to remove the download of an external API spec during
compilation. This speeds up the build and prevents the need to download
from an external repository for a source file during our compilation.
The upside is that if all the dependencies have been downloaded we
no longer make network calls during a regular build. In addition it
allows us to remove an external gradle plugin from our configuration.
This requires us to be more intentional about when we update clients
for the one of 3 updates that was pointing to the latest from a
repository instead of a particular git hash. It does bring consistency
so that now all of the API clients that we interact with are being built
in house.

Remove external api spec download during build

---

gradle.properties

Setting the build to parallel mode reduces the time required to build.
If something goes wrong with thee build process itself and you want to
run single threaded use the "--no-parallel" gradle flag to disable the
parallel build process.

Default the gradle build to parallel

---

src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java
src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
swatch-core/schemas/tally_summary.yaml

Filters out tallySnapshots by billingProvider so that RHMarketplaceProducer only consumes the appropriate snapshots.
https://issues.redhat.com/browse/ENT-4691

ENT-4691: Filter out non RH Marketplace billing providers

---

api/rhsm-subscriptions-api-spec.yaml
build.gradle
spec/error-responses.yaml
spec/openapi-paths.yaml
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/java/org/candlepin/subscriptions/security/InternalApiSecurityConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/MarketplaceResendTallyController.java
src/main/java/org/candlepin/subscriptions/tally/admin/InternalResource.java
src/main/spec/internal-tally-api.yaml
src/test/java/org/candlepin/subscriptions/tally/MarketplaceResendTallyControllerTest.java
src/test/java/org/candlepin/subscriptions/validator/UuidValidatorTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/validator/IpAddress.java
swatch-core/src/main/java/org/candlepin/subscriptions/validator/Iso8601.java
swatch-core/src/main/java/org/candlepin/subscriptions/validator/Uuid.java
swatch-core/src/main/java/org/candlepin/subscriptions/validator/UuidValidator.java

Exposing administrator REST endpoints. Unlike our other REST endpoints, this resource is meant to be deployed across all pods. With that being the case, we need to account for the contingency where a bean we depend on is not available (due to the Spring profile the pod is deployed with or for other architectural reasons). To account for this possibility, dependencies are injected as typed ObjectProviders. The provider then calls the `getIfAvailable` method with a dummy default provider.  The default provider implements or extends the dependency and has dummy implementations of the methods that
throw UnsupportedOperationExceptions.
This architecture has the potential to become very cumbersome if this resource begins to pull in a lot of dependencies. However, due to the current situation …

ENT-4698 Add admin API endpoint to resend specific tally snapshots

---

README.md
deploy/rhsm-clowdapp.yaml
swatch-core/src/main/resources/swatch-core/application.yaml
templates/rhsm-subscriptions-capacity-ingress.yml

Previously, the PSKs were stored in a JSON blob assigned to one
configuration property.  The blob was then parsed at runtime to get the
PSKs for individual applications.  Spring Boot allows us to bind
configuration properties to a map so I simplified the code to use this
functionality instead of parsing JSON.
This patch makes the deployment changes necessitated by the conversion
to using configurations properties bound to a map.

Update deployment configuration for PSK authentication

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/main/resources/liquibase/202203161423-add-billing-provider-column-to-host-table.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillingProvider.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
swatch-core/src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java

Question: Do we want to set a default value and non-null constraint on the billing provider column in the hosts table like we did in the tally_snapshots table?  Currently, this code does not since that's the way @mstead had it in his branch.

ENT-4688: add billing provider to instance api

---

swatch-producer-aws/src/main/resources/application.properties

I've seen some tests fail with bind exceptions, and https://quarkus.io/guides/getting-started-testing#controlling-the-test-port suggests we can get a randomly assigned port which should prevent collisions when e.g. multiple PRs are being tested at once.

Make quarkus choose a dynamic testing port

---

clients/subscription-client/subscription-api-spec.yaml
src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionDtoUtil.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionDtoUtilTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java

https://issues.redhat.com/browse/ENT-4686
Test Steps:
- Add test offering data:
`INSERT INTO public.offering(
sku, product_name, physical_cores, physical_sockets, virtual_cores, virtual_sockets, role, sla, usage, description)
VALUES ('sku', 'OpenShift Streams for Apache Kafka', 0, 0, 0, 0, 'rhosak', 'Premium', 'Production', 'Red Hat OpenShift Streams for Apache Kafka (Hourly)');`
- Use syncSubscription method of subscriptionJmxBean passing in '789' as subscriptionId
http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.subscription-SubscriptionJmxBean-subscriptionJmxBean
- Check that subscription was created with Aws billingProvider and billingProviderId

ENT-4686: add aws payg subscription identifiers when syncing

---

swatch-core/src/main/java/org/candlepin/subscriptions/security/JolokiaActuatorConfiguration.java

It looks like I overlooked updating these when we changed the actuator
endpoint prefix.  I modified them to use a reference to the actuator
itself rather than whatever URL it happens to be served under.

Update security settings around Jolokia

---

clients/subscription-client/subscription-api-spec.yaml
src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionDtoUtil.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/main/resources/liquibase/202204081020-add-billing-account-id-column-to-subscriptions.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionDtoUtilTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java

https://issues.redhat.com/browse/ENT-4838
Test Steps:
- Add test offering data:
`INSERT INTO public.offering(
sku, product_name, physical_cores, physical_sockets, virtual_cores, virtual_sockets, role, sla, usage, description)
VALUES ('sku', 'OpenShift Streams for Apache Kafka', 0, 0, 0, 0, 'rhosak', 'Premium', 'Production', 'Red Hat OpenShift Streams for Apache Kafka (Hourly)');`
- Use syncSubscription method of subscriptionJmxBean passing in '789' as subscriptionId
http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.subscription-SubscriptionJmxBean-subscriptionJmxBean
- Check that subscription was created with billingAccountId is populated

ENT-4838: sync awsAccountId for subscriptions

---

deploy/rhsm-clowdapp.yaml
src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
src/main/java/org/candlepin/subscriptions/tally/TallySummaryProperties.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/main/resources/application-worker.yaml
src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
templates/rhsm-subscriptions-worker.yml

https://issues.redhat.com/browse/ENT-4709
Test Steps:
- Insert Test Data: 
`INSERT INTO public.tally_snapshots(
id, product_id, account_number, granularity, owner_id, instance_count, cores, snapshot_date, sockets, physical_cores, physical_sockets, physical_instance_count, hypervisor_cores, hypervisor_sockets, hypervisor_instance_count, sla, billing_provider)
VALUES ('981c5ee6-1cee-4992-9e1e-437e4047efee', 'RHEL for x86', '6362381', 'DAILY', '13160362', 28, 599, '2021-04-16T00:00:00Z', 40, 12, 16, 4, 12, 4, 4,'Standard', '_ANY');`
`INSERT INTO public.tally_measurements(
snapshot_id, measurement_type, uom, value)
VALUES ('981c5ee6-1cee-4992-9e1e-437e4047efee', 'VIRTUAL', 'CORES', 2);`
- Stop kafka 
- Run: `curl -X 'POST' 'http://localhost:8000/api/rhsm-subscriptions/v1/internal/tally/resend' …

ENT-4709: retry tally summary messaging

---

build.gradle
buildSrc/src/main/groovy/swatch.spring-boot-conventions.gradle
src/main/java/org/candlepin/subscriptions/resource/api/ApiSpecController.java
swatch-producer-aws/build.gradle
swatch-system-conduit/build.gradle

The consoledot guidelines want the API spec to be served under
"openapi.yaml" which we can do by controlling the name of the endpoint
that serves the file in the specification itself.  There's no need to
rename the file with Gradle.

Remove Gradle renaming of our OpenAPI spec file

---

src/main/resources/application-worker.yaml

The reason to define an property that's meant to have the same name as
an environment variable is for when we would otherwise have to nest
expressions (e.g. we can't nest expressions like
${CLOUDIGRADE_INTERNAL_HOST:$CLOUDIGRADE_HOST}). That situation doesn't
apply to these properties, so we can define the defaults inline.

Express defaults directly in property value

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/main/resources/liquibase/202204131346-add-billing-account-id-column-to-hosts.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java

https://issues.redhat.com/browse/ENT-4844
Test Steps:
- Add hosts using insert-mock-hosts.py script
- Edit some to have any billing_account_id
- Use `https://petstore.swagger.io/?url=https://raw.githubusercontent.com/RedHatInsights/rhsm-subscriptions/main/api/rhsm-subscriptions-api-spec.yaml#/instances/getInstancesByProduct ` with billing_account_id param and check results for billing_account_id

ENT-4844: add billingAccountId to hosts table and Instance API

---

api/rhsm-subscriptions-api-spec.yaml

For consistency; also we actually currently 500 response w/ the case as written.

Make billing provider enums lowercase in openapi spec

---

src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/main/resources/product-stub-data/tree-MW00210M1_attrs-true.json
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java

https://issues.redhat.com/browse/ENT-4896
Testing
-------
Create an allowlist with a couple of SKUs on it:
```
echo -e 'MW00330\nMW00210MO\n' > /tmp/allowlist.txt
```
Run the app:
```
RHSM_RBAC_USE_STUB=true \
PRODUCT_WHITELIST_RESOURCE_LOCATION=file:/tmp/allowlist.txt \
```
Opt in account 123 / org 123:
```
curl   -H 'Content-Type: application/json'   -d '{
"type": "exec",
"mbean": "org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean",
"operation": "createOrUpdateOptInConfig(java.lang.String,java.lang.String,boolean,boolean,boolean)",
"arguments": [
"123",
"123",
true,
true,
true
]
}'   http://localhost:9000/hawtio/jolokia
```
Insert offerings into the DB manually:
```
curl   -H 'Content-Type: application/json'   -d "{
\"type\": …
```

ENT-4896: Sort infinite quantity subs along with quantity

---

templates/rhsm-subscriptions-capacity-ingress.yml

The HAWTIO_BASE_PATH env var is defined in the ClowdApp template, but missing from the stage/prod OS templates.  Not sure how or why that went missing, but adding it back.

ENT-4912: Pass HAWTIO_BASE_PATH to the capacity-ingress pod

---

src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/metering/jmx/MeteringJmxBean.java
src/main/java/org/candlepin/subscriptions/metering/job/MeteringJob.java
src/main/java/org/candlepin/subscriptions/metering/profile/MeteringJobProfile.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManager.java
src/main/java/org/candlepin/subscriptions/metering/task/MeteringTasksConfiguration.java
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/metering/jmx/MeteringJmxBeanTest.java
src/test/java/org/candlepin/subscriptions/metering/job/MeteringJobTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManagerTest.java
src/test/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManagerTest.java
templates/rhsm-subscriptions-scheduler.yml

https://issues.redhat.com/browse/ENT-4695
Usage metering now occurs every hour on the half hour
and is delayed by only 30 minutes relative to when the job
is run. This means that if the metering job runs at 2:30PM,
metrics will be gathered for 1pm (the 1pm - 2pm range).
**NOTE:** When the metrics query is run, it is run against the
2pm - 2:59:59.99999pm range since the query does a 1h look back
and the data actually represents usage for 1pm.
The hourly tally schedule has been updated to run with a
1h delay, relative to when the job is run. This give the
metrics tasks 30m to complete and to have events populated.
The metering job should be offset by only 1h based on when the job was run. It does not matter at what point in the current hour the job is run, the result will be the same. For …

ENT-4695: Adjust usage latency to meet AWS SLA

---

src/main/java/org/candlepin/subscriptions/tally/CloudigradeAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
src/main/java/org/candlepin/subscriptions/tally/MaxSeenSnapshotStrategy.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/HourlySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/MonthlySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/QuarterlySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/WeeklySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/YearlySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/tasks/UpdateAccountSnapshotsTask.java
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/CloudigradeAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategyTest.java
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/SnapshotRollerTester.java
src/test/java/org/candlepin/subscriptions/tally/tasks/UpdateAccountSnapshotsTaskTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java

Running tallies in batches larger than size one causes errors:
specifically postgresql can't commit the transaction and says
"terminating connection due to conflict with recovery".  This issue
happened when our read query conflicts with an appending replication
change.  See ENT-2834.
Since there are no plans to start running tallies in batches any more,
we can go ahead and change the method signatures to reflect this
reality.  Additionally, this let's us log how long a tally takes on a
per-account basis which is useful for the performance team.

ENT-4837 Do not attempt to process Tally snapshots in batches

---

deploy/clowder.md
swatch-producer-aws/deploy/clowdapp.yaml

In order to fix pod restarts due to:
```
Failed to load config value of type class java.lang.String for: SWATCH_SELF_PSK
```
Reduced initial probe delays to a more reasonable value for quicker deployment.
Updated bonfire config in clowder README. Bonfire now checks app-interface for the components and expects the same "app name" as the saas-file name in app-interface, so had to update accordingly.
Testing
------
Regenerate your bonfire config per the updated README.
```
bonfire deploy -C swatch-producer-aws -f rhsm -i quay.io/cloudservices/swatch-producer-aws=9897ac3
```
*latest doesn't work as the image tag - it'll pull an old version - above is at the time of writing the latest hash.
Observe that it deploys correctly to ephemeral. Optionally, go look at the logs in the ephemeral …

Add SWATCH_SELF_PSK to swatch-producer-aws clowdapp

---

src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java

https://issues.redhat.com/browse/ENT-4896
This is a second take (a lot of repeat from #907). In the initial solution, I made a mistake, we should put this logic against `total_capacity` sort value (instead of `quantity`).
Testing
-------
Create an allowlist with a couple of SKUs on it:
```
echo -e 'MW00330\nMW00210MO\n' > /tmp/allowlist.txt
```
Run the app:
```
RHSM_RBAC_USE_STUB=true \
PRODUCT_WHITELIST_RESOURCE_LOCATION=file:/tmp/allowlist.txt \
```
Opt in account 123 / org 123:
```
curl   -H 'Content-Type: application/json'   -d '{
"type": "exec",
"mbean": "org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean",
"operation": "createOrUpdateOptInConfig(java.lang.String,java.lang.String,boolean,boolean,boolean)",
"arguments": [
"123", …
```

ENT-4896: Apply infinite quantity sort logic to totalCapacity

---

src/main/java/org/candlepin/subscriptions/security/ApiSecurityConfiguration.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/LogPrincipalFilter.java

https://issues.redhat.com/browse/ENT-4693
Test Steps:
- Start app with default profiles
- Run against an internal endpoint and check server logs for message with path and user
`curl -X 'PUT'   'http://localhost:8000/api/rhsm-subscriptions/v1/internal/subscriptions/sync/org/123' -H 'x-rh-swatch-psk: dummy'`
- Run non internal endpoint and check that same log message does not come up
`curl -X 'GET'   'http://localhost:8000/api/rhsm-subscriptions/v1/subscriptions/products/OpenShift%20Container%20Platform'   -H 'accept: application/vnd.api+json'   -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='`

ENT-4693: Add filter for logging user requests to admin APIs

---

src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/test/java/org/candlepin/subscriptions/tally/SnapshotProducerJsonSerializationTest.java
swatch-producer-aws/deploy/clowdapp.yaml
swatch-producer-aws/src/main/java/com/redhat/swatch/processors/TallyTopicProcessor.java
swatch-producer-aws/src/main/resources/application.properties

https://issues.redhat.com/browse/ENT-4950
JSON-B (which we are using in swatch-producer-aws), does not parse dates entered as a String with the timestamp in milliseconds, such as "1649019600.000000000". We had not applied our ObjectMapper
configuration to TallySnapshot messages, otherwise they would have been omitted in ISO-8601 format, as we use:
```
objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
objectMapper.setDateFormat(new StdDateFormat().withColonInTimeZone(true));
```
This changes the TallySnapshotSummaryProducer to use our configured ObjectMapper, and adds an environment variable to swatch-producer-aws we can set temporarily to skip failures.
Testing
-------
To get into this state, it is necessary to get messages with the problematic serialization into …

ENT-4950: Serialize ISO-8601 dates in SnapshotSummaryProducer

---

src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
src/main/java/org/candlepin/subscriptions/security/ApiSecurityConfiguration.java
src/main/java/org/candlepin/subscriptions/security/auth/InternalRoleRequired.java
src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java

https://issues.redhat.com/browse/ENT-4720
Use of antMatcher/access might possibly be causing the UnsupportedOperation exception happening in stage so I'm removing it to see if it helps with the issue.
Test Steps (Regression):
- Start capacity-ingress profile
- Run with incorrect role and should get unauthorized message: `curl -X 'PUT'  'http://localhost:8000/api/rhsm-subscriptieyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='`
- Run with correct PSK and it should now work: `curl -X 'PUT'  'http://localhost:8000/api/rhsm-subscriptions/v1/internal/subscriptions/sync/org/123' -H 'x-rh-swatch-psk: dummy'`

ENT-4720: Use annotation instead of antMatcher for internal role check

---

swatch-producer-aws/deploy/clowdapp.yaml

The k8s deployment name is generated by clowder as `$clowdapp-$deploymentName`, so it was being set to `swatch-producer-aws-swatch-producer-aws`; With this change it'll get set instead to `swatch-producer-aws-service`, which is much less redundant.

Rename swatch-producer-aws clowdapp deployment service

---

swatch-producer-aws/src/main/resources/application.properties
swatch-producer-aws/src/main/resources/openapi.yaml

In order to allow us to create a route that can be used in turnpike config.
Create a nginx configuration that mimics the turnpike config (the key is that only `/api/swatch-producer-aws` is routed to our app):
```
cat <<EOF > nginx.conf
events {}
http {
server {
listen 8080;
location /api/swatch-producer-aws/ {
proxy_pass http://localhost:8000;
}
}
}
EOF
```
Run nginx:
```
podman run \
--network=host \
-v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:Z \
--rm \
-ti \
docker.io/library/nginx
```
Run the application *in production mode* (to verify swagger-ui
accessible in prod):
```
./gradlew swatch-producer-aws:quarkusBuild
QUARKUS_LOG_CONSOLE_JSON=false \
ENABLE_SPLUNK_HEC=false \
SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8080/ \
SWATCH_SELF_PSK=dummy \ …
```

ENT-4954: Make openapi and swagger-ui paths turnpike friendly

---

bin/insert-mock-hosts

`HardwareMeasurementType.CLOUD` and `HostHardwareType.VIRTUAL` do not exist.

Fix hardware and measurement type for AWS hosts in insert-mock-hosts

---

clients/prometheus-client/prometheus-api-spec.yaml
src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/test/java/org/candlepin/subscriptions/metering/MeteringEventFactoryTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
swatch-core/schemas/event.yaml

**Add billing_marketplace_account metric label to Event data**
When metrics are read from prometheus, the billing_marketplace_account
label is read from the metrics and is stored in the resulting Event
object.
To be consistent, the label value is stored in the Event as
billingAccountId.
**Remove trailling / from prometheus API paths**
The trailing / causes a / before query parameters are defined in the URL,
which trips up some web servers ( /?parameter=foo ).
Because the billing_marketplace_account is not yet available in our Observatorium environments, we will have to stub the data when testing: [Generating Prometheus Metric Data](https://docs.engineering.redhat.com/display/ENT/Generating+Prometheus+Metric+Data)
As in the doc, after generating the data, run the MeteringJob and then …

ENT-4842: Add accountBillingId to Events

---

deploy/rhsm-clowdapp.yaml

Reduces the time it takes for rhsm ClowdApp to deploy to ephemeral environments.  We were invoking our cron jobs after the deployments were finished, which made the bonfire command timeout unless you passed a --timeout flag.
Updated the default liveness/readiness probes to not wait five minutes before checking, which also makes rhsm ClowdApp report as ready faster.
Deploy with bonfire
```
bonfire deploy rhsm --no-remove-resources=rhsm-subscriptions --optional-deps-method=none \
-i quay.io/cloudservices/rhsm-subscriptions=823e65d \
-i quay.io/cloudservices/swatch-system-conduit=823e65d \
-i quay.io/cloudservices/swatch-producer-aws=823e65d
```
See that the bonfire command successfully exits
```
2022-05-05 17:46:11 [    INFO] [          MainThread] all resources being monitored reached …
```

Don't invoke cron jobs on clowdapp deployment

---

src/main/java/org/candlepin/subscriptions/metering/jmx/MeteringJmxBean.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSource.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManager.java
src/test/java/org/candlepin/subscriptions/metering/jmx/MeteringJmxBeanTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSourceTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManagerTest.java

During verification of #953, I noticed that the way the metrics ranges are handled was a bit inconsistent. Specifically, when we
persist metrics, we treat the data point timestamp as the "end" of the range and then calculate back to the beginning of the range by subtracting an hour. For a data point that represents 12pm-1pm, we record `timestamp` as `12pm` and `expiration` as `1pm`, but the handling of the active account query and task interpretation of ranges were different.
I also noticed that the JMX operation `performCustomMetering` was not functioning properly when given a range longer than 1 hour, which I addressed.
These changes make the entry points to metrics gathering also follow this convention - the start of the range and end of the range for 12pm to 1pm are consistently …

Realign and simplify range handling w/ metrics

---

deploy/rhsm-clowdapp.yaml
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionService.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceConfiguration.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceProperties.java
src/main/resources/application.yaml
swatch-core/src/main/java/org/candlepin/subscriptions/exception/SubscriptionsException.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/UnretryableException.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/UnretryableExternalServiceException.java
templates/rhsm-subscriptions-capacity-ingress.yml

I traced back the remaining kafka exceptions in stage to an ApiException from the subscription service.  This was happening because there's an orgId in stage - `lsjel`.  This happens when subscription sync cron job runs, which is why it's buried in a kafka exception.
The easiest/fastest way to produce locally though is to use the `syncSubscriptionsForOrg` jolokia endpoint.
Set environment variables to point to the stage subscription service.  Keystore and password can be found in vault.  You might want to turn on some http logging.  You can do this with `LOGGING_LEVEL_ORG_APACHE_HTTP_WIRE=debug`.
```
SUBSCRIPTION_URL=https://subscription.stage.api.redhat.com/svcrest/subscription/v5
SUBSCRIPTION_KEYSTORE=<redacted>
SUBSCRIPTION_KEYSTORE_PASSWORD=<redacted>
SPRING_PROFILES_ACTIVE …
```

ENT-4912: Protect subscription sync against failures due to invalid org/acct id

---

bin/GeneratingPrometheusMetricData.adoc

Migrate contents of a wiki page into the directory where we have tools for scripting other mock data.  Easiest way to review this is to select "View File" instead of looking at the diff.
https://github.com/RedHatInsights/rhsm-subscriptions/blob/169b6c3e2a32a64a482894f7230f97104d8b3b3f/bin/GeneratingPrometheusMetricData.adoc
https://docs.engineering.redhat.com/display/ENT/Generating+Prometheus+Metric+Data

Add documentation for generating prometheus metric data for testing

---

src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java

https://issues.redhat.com/browse/ENT-4720
Test Steps:
- Add rhosak offering to db: 
`INSERT INTO public.offering(
sku, product_name, product_family, sla, description, has_unlimited_usage)
VALUES ('MW01882', 'OpenShift Streams for Apache Kafka', 'JBoss', 'Premium', 'Red Hat OpenShift Streams for Apache Kafka (Hourly)', false);`
- Run capacity-ingress
- `curl -X 'PUT'   'http://localhost:8000/api/rhsm-subscriptions/v1/internal/subscriptions/sync/org/123' -H 'x-rh-swatch-psk: dummy'`
- Check subscriptions table that subscription with subscription_id="235252" and change quantity of that record from 1 to 2.
`UPDATE public.subscription
SET quantity=2
WHERE subscription_id = '235252';`
- Run curl again  `curl -X 'PUT'   'http://localhost:8000/api/rhsm-subscriptions/v1/internal/subscriptions/sync/ …

ENT-4720: Fetch all subscriptions at once from db for force sync

---

src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/tally/job/CaptureHourlySnapshotsJob.java
src/main/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManager.java
src/test/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManagerTest.java

https://issues.redhat.com/browse/ENT-4951
TallyJmxBean.tallyAllAccountsByHourly now supports a date range.
When no range is specified, the default is run based on NOW with
offsets applied.
When testing, monitor the logs to check the resulting dates of the Tally.
NOTES:
* Must have Events in the DB and a matching opted in account.
Hitting the JMX endpoint with null or empty start/end values will default to the same behaviour as the CaptureHourlySnapshotJob, where the start/end dates are based on NOW with the configured offsets applied. For example, running at 18:41:05pm UTC, you should expect to see:
> 2022-05-03 18:41:05,087 [thread=rhsm-subscriptions-task-processor-0-C-1] [INFO ] [org.candlepin.subscriptions.tally.TallySnapshotController] - Producing hourly snapshots for account 941133 …

ENT-4951 Add range support for hourly tally by all accounts

---

templates/rhsm-subscriptions-worker.yml

In order to hopefully stop crashlooping when the DB is too busy.
Related to troubleshooting a production issue.

Change to /health/liveness for tally livenessProbe

---

deploy/rhsm-clowdapp.yaml
swatch-core/schemas/billable_usage.yaml
swatch-core/schemas/tally_snapshot.yaml
swatch-producer-aws/src/main/java/com/redhat/swatch/processors/TallyTopicProcessor.java
swatch-producer-aws/src/test/java/com/redhat/swatch/com/redhat/swatch/processors/TallyTopicProcessorTest.java
swatch-producer-aws/src/test/java/com/redhat/swatch/files/TagProfileTest.java
templates/swatch-billing-provider-rh-marketplace.yml

I broke apart the schema files in order to minimize change
and to avoid class name conflicts with sub classes that were
being generated for TallySnapshots.
It also makes the class names a little nicer in swatch-producer-aws.
New billable-usage topic and relevant settings were added to clowdapp.
New billable-usage topic related settings rh-marketplace deploy template.

Add BillableUsage schema to swatch-core and add configuration changes.

---

src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerProperties.java
src/main/java/org/candlepin/subscriptions/tally/billing/TallySummaryMessageConsumer.java
src/main/resources/application-worker.yaml
src/main/resources/application.yaml
src/test/java/org/candlepin/subscriptions/tally/SnapshotProducerJsonSerializationTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillingProducerTest.java

https://issues.redhat.com/browse/ENT-4978
* Add secondary listener to tally summary topic.
* Implemented a bare bones BillingProducer class that listens
to the TallySummary topic and logs that a message was recieved
and then forwards to new billable usage topic:
platform.rhsm-subscriptions.billable-usage
1. Ensure you have some Events in the DB and take not of the message counts for each topic.
2. Start the app as follows:
```bash
LOGGING_LEVEL_ORG_CANDLEPIN_SUBSCRIPTIONS_TALLY_BILLING=DEBUG SUBSCRIPTION_USE_STUB=true USER_USE_STUB=true DEV_MODE=true  ./gradlew :bootRun
```
3. Run the hourly tally. BE SURE YOU TALLY AROUND THE RANGE THAT HAS EVENTS. The example below should cover any Events in may and force a fresh re-tally.
```bash
curl 'http://localhost:8080/actuator/hawtio/jolokia/' \ …
```

ENT-4978 Add BillingProducer to worker component

---

src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceWorker.java
src/main/resources/application.yaml
swatch-core/src/main/java/org/candlepin/subscriptions/task/TaskQueueProperties.java

https://issues.redhat.com/browse/ENT-4994
Testing
-------
Run the app without setting `ENABLE_TALLY_SUMMARY_LISTENER`:
```
```
Using a kafka producer, emit a message to the tally summary topic
(platform.rhsm-subscriptions.tally). (I used IntelliJ Big Data Tools
with message `{f}` (contents don't matter). Observe listener is active
and attempts to process the message.
Then run with the flag, and repeat, observing no activity:
```
ENABLE_TALLY_SUMMARY_LISTENER=false ./gradlew :bootRun
```

ENT-4994: Disable RHM tally summary listener when flag false

---

buildSrc/src/main/groovy/swatch.java-conventions.gradle

Set maxHeapSize for gradle tests
tests don't honor gradle.properties because forked JVM

Set maxHeapSize for gradle tests

---

dashboards/grafana-dashboard-subscription-watch.configmap.yaml

https://issues.redhat.com/browse/ENT-4894
Resolves a issue with the graph in grafana looking like it's climbing steadily because we made changes to the kafka consumer group id

ENT-4894: Update RH Marketplace Task Lag panel to include kafka group id in query

---

src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
swatch-core/schemas/tally_snapshot.yaml

https://issues.redhat.com/browse/ENT-4684
Refactor implementation slightly to handle filtering logic for Tally
Add new test case to test filtering by billingProvider
```
1. Start app with `DEV_MODE=DEV_MODE=true;SPRING_PROFILES_ACTIVE=worker,api
2. Insert mock events from the bin folder in your directory:
- ./import-events.py --file events.csv
3. Start tally event with the following parameters for your mock events
"acount123" , ''2021-10-01T00:00Z", "2021-10-31T00:00Z":
http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.jmx-TallyJmxBean-tallyJmxBean 
4. Use the get Tally data to show the response populate with the Instance-Hours metric:
http://localhost:8000/api/rhsm-subscriptions/v1/tally/products/rhosak/Instance-hours?granularity=Daily&billing_provider=red%2 …
```

ENT-4684: Refactor filter logic for Billing Provider

---

swatch-producer-aws/README.adoc
swatch-producer-aws/build.gradle
swatch-producer-aws/src/main/java/com/redhat/swatch/kafka/BillableUsageDeserializer.java
swatch-producer-aws/src/main/java/com/redhat/swatch/kafka/BillableUsageSerializer.java
swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java
swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProducer.java
swatch-producer-aws/src/main/java/com/redhat/swatch/resource/BillableUsageResource.java
swatch-producer-aws/src/main/resources/application.properties
swatch-producer-aws/src/main/resources/openapi.yaml
swatch-producer-aws/src/test/java/com/redhat/swatch/com/redhat/swatch/processors/BillableUsageProcessorTest.java

https://issues.redhat.com/browse/ENT-4995
The swatch-producer-aws producer was updated to allow sending
BillableUsage messages instead of TallySummary messages.
The swatch-producer-aws processor was updated to listen for
BillableUsage messages instead of TallySummary messages.
The admin API was updated to reflect billable usage and accepts
a BillableUsage payload.
1. Run `./gradlew swatch-producer-aws:wiremock` in a terminal
2. Run `./gradlew swatch-producer-aws:quarkusDev` in another (`quarkus dev` from the subdirectory works instead too).
3. Send a BillableUsage message to the topic
```bash
$ curl -X 'POST'   'http://localhost:8000/api/swatch-producer-aws/internal/aws/billable_usage'   -H 'accept: */*'   -H 'Content-Type: application/json'   -d '{
"account_number": "account123", …
```

ENT-4995 Update swatch-producer-aws to consume BillableUsage messages

---

src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
src/test/java/org/candlepin/subscriptions/metering/RhosakTagProfileTest.java
src/test/java/org/candlepin/subscriptions/registry/TagProfileFactoryTest.java
src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/registry/TagMetric.java
swatch-core/src/main/java/org/candlepin/subscriptions/registry/TagProfile.java
swatch-core/src/main/resources/tag_profile.yaml

This PR is to address sub task: https://issues.redhat.com/browse/ENT-5012 
Rename metric id to rhMarketplaceMetricId in tag_profile.yaml.
Update implementing Unit tests

ENT-5012: Refactor Metric ID to the rhMarketplaceMetricId

---

src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java

Add logic to ignore Usage metric for undefined rhmMetricId.
Update Unit test for ignoring undefined rhmMetricId.

ENT-5013: Update RHM Payload Mapper for unconfigured rhMarketplaceMetricId

---

src/test/java/org/candlepin/subscriptions/metering/RhosakTagProfileTest.java
src/test/java/org/candlepin/subscriptions/registry/TagProfileFactoryTest.java
src/test/resources/test_tag_profile.yaml
swatch-core/src/main/java/org/candlepin/subscriptions/registry/BillingWindow.java
swatch-core/src/main/resources/tag_profile.yaml

https://issues.redhat.com/browse/ENT-5011
BillingWindow is the window in which billable usage
will be sent to the marketplace instances. By default,
we send MONTHLY usage.
All existing metrics are configured to send usage in
an HOURLY billing window.

ENT-5011 Add BillingWindow configuration

---

src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java

Per discussions with the metrics team they are using the billing_marketplace and not the billing_provider metric.

Update prometheus billing_provider metric label to billing_marketplace.

---

swatch-producer-aws/src/main/java/com/redhat/swatch/files/TagProfile.java
swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java
swatch-producer-aws/src/test/java/com/redhat/swatch/com/redhat/swatch/processors/BillableUsageProcessorTest.java

Add logic to isSnapshotApplicable method to skip unconfigured dimensions
Update Unit test for BillableUsageProcessor for skipping unknown dimension.
Add new method to TagProfile.

ENT-5014: Update aws producer to ignore metrics without awsDimension

---

src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java

Spring Data deprecated getById because it didn't do what people thought
it did.  Rather than fetching the entity, getById returned a JPA proxy
object.  The method has been replaced with the more accurately named
getReferenceById.  In the case of the code this commit patches, it
appears that the original author wanted the semantics associated with
findById and got tripped up by the confusing naming.
See https://github.com/spring-projects/spring-data-jpa/issues/2232

Remove calls to deprecated Spring Data method getById

---

swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java

https://issues.redhat.com/browse/ENT-5048
Missing orderby was causing the fill in dates to get duplicated.

ENT-5048: add missing order by to tally snapshot query

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
src/main/java/org/candlepin/subscriptions/tally/billing/TallySummaryMessageConsumer.java
src/main/resources/liquibase/202206021315-add-version-to-billable-usage-tracking-table.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillingProducerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntity.java

When a metered product's billing window is configured as MONTHLY,
the ceiling of the total monthly usage up to a snapshot's date is
compared with the currently remitted montly usage and the difference
is sent as the billable amount.
billing_value = ceil(montly_total_up_to_snapshot_date) - currently_remitted
Example:
Snapshot 1:  2022-03-31T23:00
value: 0.2
monthly total: 0.2
currently remitted: 0.0
After processing:
billed value: 1.0 GB-month
remitted: 1.0 GB-month
Snapshot 2:  2022-04-01T00:00
value: 0.1200
monthly total: 0.1200
currently remitted: 0.0
After Processing:
billed value: 1.0 GB-month
remitted: 1.0 GB-month
Snapshot 3:  2022-04-01T01:00
value: 0.3000
monthly total: 0.4200
currently remitted: 1.0
After processing:
billed value: 0.0 GB-month
remitted: 1.0 GB-month
Snapshot 4: …

Support integer billing for MONTHLY billing window

---

src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java

https://issues.redhat.com/browse/ENT-5087
This was causing every subscription to be treated as needing updating, as it'd end up with BillingProvider.EMPTY when the column was null.
```
2022-06-07T20:05:39.637+0000 [thread=swatch-producer-rh-marketplace-10-C-1] [level=DEBUG] [category=org.candlepin.subscriptions.subscription.SubscriptionSyncController]  - Existing subscription in DB=Subscription(subscriptionId=123456, subscriptionNumber=7890, sku=MCT2735, ownerId=123456, quantity=1, startDate=2021-06-10T04:00Z, endDate=2022-06-09T04:00Z, billingProviderId=null, billingAccountId=null, accountNumber=123456, billingProvider=EMPTY)
```
vs.
```
2022-06-07T20:06:37.436+0000 [thread=subscription-worker-2-C-1] [level=DEBUG] [category=org.candlepin.subscriptions.subscription.SubscriptionSyncControll …
```

ENT-5087: Do not default Subscription.billingProvider

---

clients-core/src/main/java/org/candlepin/subscriptions/http/HttpClient.java

Fingers crossed this will fix all the extraneous "Cookie rejected ..." messages in stage.

Move cookie config before the httpClient is built with apacheBuilder.

---

swatch-producer-aws/deploy/clowdapp.yaml
swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java
swatch-producer-aws/src/test/java/com/redhat/swatch/com/redhat/swatch/processors/BillableUsageProcessorTest.java

Setting env var ENABLE_AWS_DRY_RUN=true will skip sending
usage to AWS and instead log the request.
1. Ensure you have events with AWS billing provider in the DB.
2. Start the proxy in a terminal: ```./gradlew :swatch-producer-aws:wiremock```
3. Run the app in another terminal: ```ENABLE_AWS_DRY_RUN=true ./gradlew :swatch-producer-aws:quarkusDev```
4. Each validated message will producer a log message as follows, and will not attempt to send to AWS Marketplace:
```
2022-06-09 15:17:10,514 INFO  [com.red.swa.pro.BillableUsageProcessor] (vert.x-worker-thread-0) [DRY RUN] Sending usage request to AWS: BatchMeterUsageRequest(UsageRecords=[UsageRecord(Timestamp=2022-06-08T18:16:49.569407Z, CustomerIdentifier=customer123, Dimension=storage_gb, Quantity=0)], ProductCode=productCode)
```

Optionally disable AWS usage send

---

src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
src/main/spec/internal-subscriptions-sync-api-spec.yaml
src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java
swatch-producer-aws/src/main/resources/application.properties
swatch-producer-aws/src/test/java/com/redhat/swatch/com/redhat/swatch/processors/BillableUsageProcessorTest.java
swatch-producer-aws/src/test/java/com/redhat/swatch/wiremock/WiremockRunner.java

Testing
-------
Insert a subscription record that matches billingAccountId "123" and one
that doesn't:
```
cat <<EOF | psql -h localhost -U rhsm-subscriptions
INSERT INTO offering(
sku, product_name, product_family, sla, usage, description, has_unlimited_usage)
VALUES ('MW01882', 'OpenShift Streams for Apache Kafka', 'JBoss', 'Premium', 'Production', 'Red Hat OpenShift Streams for Apache Kafka (Hourly)', false);
INSERT INTO subscription(
sku, owner_id, subscription_id, quantity, start_date, end_date, billing_provider_id, account_number, subscription_number, billing_provider, billing_account_id)
VALUES ('MW01882', 'org123', '12351256', '1', '2012-05-13 16:32:00+00', '2032-05-13 16:32:00+00', 'testProductCode123;customer123;sellerAccount123', 'account123', '1235153', 'aws', '123');
INSERT …
```

ENT-5091: Make awsUsageContext lookup use billingAccountId

---

src/main/java/org/candlepin/subscriptions/user/AccountService.java
src/main/java/org/candlepin/subscriptions/user/NotFoundSubscriptionsExceptionClassifier.java
src/main/java/org/candlepin/subscriptions/user/UserServiceClientConfiguration.java
src/test/java/org/candlepin/subscriptions/user/NotFoundSubscriptionsExceptionClassifierTest.java

A custom RetryPolicy allows us to limit our retries to the case where
this is a legitimate service failure instead of an account simply not
existing.

Do not retry Account Service if account is simply not found

---

templates/rhsm-subscriptions-capacity-ingress.yml

Add DEVTEST_EVENT_EDITING =false in the capacity ingress template. It allows QE to test the new internal termination API mentioned in ENT-4932.

Enable DEVTEST_EVENT_EDITING in capacity ingress template

---

clients/subscription-client/subscription-api-spec.yaml
src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionDtoUtil.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionDtoUtilTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java

https://issues.redhat.com/browse/ENT-5120
There were two mistakes:
1. `awsMarketplace` needed instead of `aws`.
2. `customerAccountID` needed instead of `customerAccountId`.
Testing
-------
Deploy the app using non-prod keystore (replace FIXME below)
```
SUBSCRIPTION_URL=https://subscription.stage.api.redhat.com/svcrest/subscription/v5 \
SUBSCRIPTION_KEYSTORE=$(pwd)/config/certs/keystore.jks \
SUBSCRIPTION_KEYSTORE_PASSWORD=FIXME \
```
Then invoke a sync of a test account in stage:
```
type=exec \
mbean=org.candlepin.subscriptions.subscription:name=subscriptionJmxBean,type=SubscriptionJmxBean \
operation='syncSubscriptionsForOrg(java.lang.String)' \
arguments:='["6592901"]'
```
Then verify that the records have …

Correct bad AWS references in Subscription client

---

README.md
dashboards/grafana-dashboard-subscription-watch.configmap.yaml

Needs updating to coincide with multi marketplace changes
Repurpose RH Marketplace Task Lag to Tally to Billable Usage Lag
Widget for RH Marketplace Billable Usage Lag
Widget for AWS Billable Usage Lag
Testing
- Log into stage grafana: https://grafana.stage.devshift.net/?orgId=1
- Left Nav -> Create -> Import
- Paste/Upload the json and click "Load"
- If you get an error about there already being a panel, change the name of the dashboard and UID, then click Import again
- After checking out the dashboard changes, clean up after yourself and delete the dashboard.
Note: Might need to make sure you're trying to import under "General" category and not the Insights folder.

ENT-4690: Update grafana dashboards

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java

https://issues.redhat.com/browse/ENT-5130
Testing
-------
Deploy locally, using nonprod keystore (replace FIXME below).
```
SUBSCRIPTION_URL=https://subscription.stage.api.redhat.com/svcrest/subscription/v5 \
USER_HOST=user.stage.api.redhat.com \
SUBSCRIPTION_KEYSTORE=$(pwd)/config/certs/keystore.jks \
SUBSCRIPTION_KEYSTORE_PASSWORD=FIXME \
```
Clear the usage column in offerings:
```
update offering set usage=null;
EOF
```
Test the getAwsUsage endpoint (replace FIXME with values from the Jira
issue):
```
http :8000/api/rhsm-subscriptions/v1/internal/subscriptions/awsUsageContext \
accept:application/json \
x-rh-swatch-psk:dummy \
accountNumber==FIXME \
date==2022-06-21T00:00Z \
productId==rhosak \ …
```

ENT-5130: Ignore Usage value on PAYG subs for now

---

src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceSubscriptionIdProvider.java

To reduce sync load.
Related: #1107

Apply paygOnly true to RHM subscription syncing

---

deploy/rhsm-clowdapp.yaml
templates/rhsm-subscriptions-capacity-ingress.yml

Because we're using Spring Resource as the datatype, it treats a path without the file: prefix as relative to the webapp root. Doh!
Testing
---------
Try locally with and without `file:` prefix, and note in logging without the prefix:
```
UMB config requires keystore and truststore - not provided or not valid.
```

Add file: prefix to UMB keystore/truststore

---

src/main/java/org/candlepin/subscriptions/umb/Identifiers.java
src/main/java/org/candlepin/subscriptions/umb/UmbSubscription.java
src/test/java/org/candlepin/subscriptions/umb/SubscriptionMessageTests.java
src/test/resources/mocked-subscription-message.xml

There were a few things wrong with the mocked message:
1. `Identifiers` can have additional elements.
2. `Subscription number` is written in an `Identifier` element.
This updates the mocked message and code appropriately.
Testing
-------
Testing via `mocked-subscription-message.xml`/unit tests.

Fix ID parsing for UMB messages

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java

No need to always update the date becuase often times that is
the only thing that would be updated. This causes a version
update which increases the likelyhood of an OptimisticLockException.
1. Import event
```
insert into events (id, account_number, "timestamp", data, event_type, event_source, instance_id) values ('6d5bb984-7c20-460a-bbb2-962e358e405d', 'account123', '2022-06-03 13:00:00+00', '{"sla": "Premium", "role": "rhosak", "event_id": "6d5bb984-7c20-460a-bbb2-962e358e405d", "timestamp": "2022-06-03T13:00:00Z", "event_type": "snapshot_redhat.com:rhosak:cluster_hour", "expiration": "2022-06-03T14:00:00Z", "instance_id": "44107058-48de-4ea2-a393-390a663b7c11", "display_name": "automation_rhosak_cluster_44107058-48de-4ea2-a393-390a663b7c11", "event_source": "prometheus", …
```

Only set remittance date when remittance has changed

---

src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
src/main/java/org/candlepin/subscriptions/tally/TallySummaryMapper.java
src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/main/java/org/candlepin/subscriptions/tally/billing/RemittanceController.java
src/main/spec/internal-tally-api-spec.yaml
src/test/java/org/candlepin/subscriptions/registry/TagProfileFactoryTest.java
src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/RemittanceControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntityPK.java
swatch-core/src/main/resources/tag_profile.yaml

https://issues.redhat.com/browse/ENT-5098
**Add endpoint to sync remittance**
The endpoint will fetch all of the latest snapshots for each
metric for an account, filter them based on the configured
billing window and billing validity, and run them through the
remittance process.
If remittance already exists for a metric, a new remittance
value will not be calculated as the metric has already been
billed.
When remittance is synced, the new remittance value is calculated
and no billable usage will be sent as we consider this usage already
billed for.
**Configured metrics to use integer billing (monthly billing window)**
**NOTE:** rhosak - Storage-gibibytes remains as HOURLY billing window due to existing
subscription constraints.
1. Clean out the applicable data so we can start fresh
``` …
```

ENT-5098 Support remittance syncing and update metrics to HOURLY billing window

---

src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/ErrorCode.java
swatch-producer-aws/src/main/java/com/redhat/swatch/exception/DefaultApiException.java
swatch-producer-aws/src/main/java/com/redhat/swatch/exception/SubscriptionRecentlyTerminatedException.java
swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java
swatch-producer-aws/src/main/java/com/redhat/swatch/resource/DefaultApiExceptionMapper.java
swatch-producer-aws/src/main/resources/application.properties
swatch-producer-aws/src/test/java/com/redhat/swatch/com/redhat/swatch/processors/BillableUsageProcessorTest.java

https://issues.redhat.com/browse/ENT-4931
Test Steps:
- Start capacity-ingress on Server port 8101: `DEV_MODE=true SERVER_PORT=8101 ./gradlew :bootRun`
- Start swatch-producer-aws: `./gradlew  quarkusDev`
- Put following billing_usage json onto topic platform.rhsm-subscriptions.billable-usage: `{"account_number":"123","org_id":"123","id":null,"billing_provider":"aws","billing_account_id":"1234567891234","snapshot_date":"2031-01-01T01:10:28Z","product_id":"rhosak","sla":"Premium","usage":null,"uom":"Storage-gibibyte-months","value":42.0}`
- Check swatch-producer-aws logs for 'Subscription recently terminated for account={} tallySnapshotId={}'

ENT-4931: Log when subscription recently terminated for awsContextLookup API

---

build.gradle
src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingController.java
src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingResource.java
src/main/spec/internal-billing-api-config.json
src/main/spec/internal-billing-api-spec.yaml
src/test/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java

https://issues.redhat.com/browse/ENT-5096
Testing Steps:
1. Insert data into local database
```
insert into public.billable_usage_remittance (account_number, org_id, product_id, metric_id, accumulation_period, sla, usage, billing_provider, billing_account_id, remitted_value, remittance_date, version) values ('account123', null, 'rhosak', 'Instance-Hours', '2022-07', '_ANY', '_ANY', 'redhat', 'dummy', 10, '2022-07-27 13:04:51.977000 +00:00', 1);
insert into public.billable_usage_remittance (account_number, org_id, product_id, metric_id, accumulation_period, sla, usage, billing_provider, billing_account_id, remitted_value, remittance_date, version) values ('account123', null, 'rhosak', 'Instance-Monthly', '2022-06', '_ANY', '_ANY', 'redhat', 'dummy', 10, '2022-06-27 13:01:26.048000 +00:00', …
```

ENT-5096: Add Internal Billing API to get remittances data.

---

src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
src/test/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategyTest.java

https://issues.redhat.com/browse/ENT-5204
Test Steps:
- Add subscription for account:
```
INSERT INTO public.subscription(
sku, owner_id, subscription_id, quantity, start_date, end_date, billing_provider_id, account_number, subscription_number, billing_provider, billing_account_id)
VALUES ('MW01882', '123', '11381020', 1, '2022-06-29 04:00:00+00', '2022-07-29 04:00:00+00', 'testProductCode123;customer123;awsSellerAccountId', '123','11381177','aws', '719247844304');
```
- Create events (I have csv file I can share)
- Start swatch: `DEV_MODE=true SERVER_PORT=8101 SUBSCRIPTION_USE_STUB=true USER_USE_STUB=true ./gradlew :bootRun`
- Start producer-aws: `ENABLE_AWS_DRY_RUN=true ./gradlew quarkusDev`
- Run hawtio endpoint for first hour where accountNumber = 123, startDateTime = …

ENT-5204: Filter out snapshot message duplicates 

---

api/rhsm-subscriptions-api-spec.yaml
bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java

https://issues.redhat.com/browse/ENT-4580
Test Steps:
- Add mock host data: `./bin/insert-mock-hosts --num-physical 2 --billing-provider 'red hat' --billing-account-id 1232 --num-guests 3`
- Call endpoint: 
```
curl -X 'GET' \
'http://localhost:8000/api/rhsm-subscriptions/v1/instances/products/RHEL?billing_provider=red%20hat&billing_account_id=1232' \
-H 'accept: application/json' \
-H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='
```
- Should see number_of_guests in response

Add number_of_guests to instance API response

---

swatch-producer-aws/deploy/clowdapp.yaml

https://issues.redhat.com/browse/ENT-5190
Links the swatch-producer-aws pods to the rhsm-quarkus service
monitor so that metrics are scraped.
No real way to test, other than deploy to stage and see what happens.

ENT-5190 Add metric labels to swatch-producer-aws

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/CustomizedSubscriptionCapacityRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/CustomizedSubscriptionCapacityRepositoryImpl.java

https://issues.redhat.com/browse/ENT-4384
Test Steps:
- Insert test data: 
```
INSERT INTO public.subscription_capacity VALUES ('account123', 'RHEL', '7025101', 'org123', 20, NULL, false, '2022-06-12 04:00:00+00', '2023-06-11 04:00:00+00', NULL, NULL, 'RH00004', 'Standard', 'Production');
INSERT INTO public.subscription_capacity VALUES ('account123', 'RHEL', '7028601', 'org123', NULL, 2, false, '2022-06-17 04:00:00+00', '2023-06-16 04:00:00+00', NULL, NULL, 'RH00004', 'Standard', 'Production');
INSERT INTO public.subscription_capacity VALUES ('account123', 'RHEL Server', '7025101', 'org123', 20, NULL, false, '2022-06-12 04:00:00+00', '2023-06-11 04:00:00+00', NULL, NULL, 'RH00004', 'Standard', 'Production');
INSERT INTO public.subscription_capacity VALUES ('account123', 'RHEL for x86', …
```

ENT-4384: Create new API for Capacity with metric ID

---

src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingResource.java

https://issues.redhat.com/browse/ENT-5096
This is to resolve a mismatch as the super class generated the parameters in a different order.

ENT-5096: Fix Mismatch position.

---

swatch-system-conduit/build.gradle
swatch-system-conduit/schemas/inventory/hbi-fact-set.yaml
swatch-system-conduit/schemas/inventory/hbi-host.yaml
swatch-system-conduit/schemas/inventory/hbi-network-interface.yaml
swatch-system-conduit/schemas/inventory/hbi-system-profile-operating-system.yaml
swatch-system-conduit/schemas/inventory/hbi-system-profile.yaml
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/ConduitFacts.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/DefaultInventoryService.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/kafka/CreateUpdateHostMessage.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/DefaultInventoryServiceTest.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java

This PR covers two things:
1) Now generates the HBI message payload for adding a Host via JSON schema definitions.
2) Adds org_id as a canonical fact in the message payload.
NOTE:
* There will be an immediate follow-on PR that will remove the DefaultInventoryService that uses the generated openapi client for HBI. I opted to send a dummy payload here instead of wasting time writing converter code for the different payloads. I also ignored the tests around this class as well.
* The openapi generated POJO contained a lot more fields than we were actually using. I only included things that we were actually setting on the newly generated POJO to keep it smaller.
The best way I could find to test this was to do so at the message payload level as I wasn't able to get an HBI instance configured …

Generate HBI message payload from JSON instead of openapi spec (also add org_id to payload)

---

docker-compose.yml
init_kafka.sh

Also, added `--ignore-formatted`, so that the pod can be stopped and started without issue.
To try the changes:
```
podman-compose down kafka
podman-compose up -d kafka
```

Move kafka commands to separate script

---

src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/resources/liquibase/202207201200-add-org-id-to-event-table.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/EventRecordRepositoryTest.java
src/test/java/org/candlepin/subscriptions/metering/MeteringEventFactoryTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
swatch-core/schemas/event.yaml
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/EventRecord.java

https://issues.redhat.com/browse/SWATCH-214
* Add org_id column to events table
* Add org_id field to JSON event schema
* Collect external_organization label value from metrics
and store on Event record.
Get connected to the testing telemeter instance (see: [Connecting To Observatorium](https://docs.engineering.redhat.com/display/ENT/Connecting+to+Observatorium+to+Fetch+Prometheus+Metrics) )
Start the application.
```
PROM_URL="http://localhost:8888/api/metrics/v1/telemeter/api/v1" DEV_MODE=true ./gradlew clean :bootRun
```
Pull down metrics for test account 10666718
```
curl 'http://localhost:9000/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.metering.jmx:name=meteringJmxBean,type=MeteringJmxBean","operation":"performMeteringF …
```

SWATCH-214 Capture org_id from metrics and store on events.

---

src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java

https://issues.redhat.com/browse/SWATCH-265
When an hourly tally is run, the org_id is pulled from the relevant Event objects and is set on the applicable Hosts when they are created/updated.
**Testing**
Copy the following to a file and Import some Events into the DB.
```
--
-- PostgreSQL database dump
--
-- Dumped from database version 13.4
-- Dumped by pg_dump version 13.4
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
--
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: …
```

SWATCH-265 Set org_id on Hosts from Events

---

Jenkinsfile
gradle.properties

Instead of using "fedora" or "fedora35" node on the SMQE jenkins instance for our **continuous-integration/jenkins/pr-merge** check for each PR, have jenkins spin up a new container to use as a build node.
"Testing"/Verification
If you click "Details" in the checks section of this PR, and then navigate to the Jenkins instance[0]  (top right corner....icon that kind of looks like logout), and then open the console output and View Full Log....you'll be able to see near the top that an agent was provisioned based on a pod spec yaml. 
If the job has been ran recently, you can actually click into the linked agent name that got spun up and see some details within Jenkins.  You can also take that name and search for it in the openshift console [1], where you can view the node and access the …

SWATCH-288: Update Jenkins pipeline to use containers as nodes

---

Jenkinsfile

Fixes issue with https://github.com/RedHatInsights/rhsm-subscriptions/pull/1257 
When working on [SWATCH-288](https://issues.redhat.com/browse/SWATCH-288), I left out one of the stages that allowed the develop/main branch jenkins jobs to upload to sonar.  That Jenkins job doesn't trigger until something lands in the develop branch, so to verify this fix will have to wait until its been merged.

[bugfix for SWATCH-288] Add Upload Branch to SonarQube stage back to Jenkinsfile

---

deploy/rhsm-clowdapp.yaml
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryServiceProperties.java
swatch-system-conduit/src/main/resources/application.yaml
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
templates/rhsm-conduit.yaml

https://issues.redhat.com/browse/SWATCH-257
1. **Description**:
- Currently, tolerate-missing-account-number has default value as false. It is set in stage as true and in prod it is set as false. This is defined in app-interface.
App-interface PR: ```https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44020```
2. **Test Steps**:
- The flag is defined in swatch-system-conduit/src/main/resources/application.yaml
- Change the Stub: StubRhsmApi
- Comment out the account number to test the above flag locally.
For false it will throw error and for true it will tolerate the missing account number.
-Run: `RHSM_USE_STUB=true DEV_MODE=true ./gradlew :swatch-system-conduit:bootRun`
Another terminal execute:
`curl -X 'POST' …

SWATCH-257: Tolerate missing accountnumber

---

src/main/resources/liquibase/202207051557-transition-deprecated-columns.xml
src/main/resources/liquibase/202207061021-migrate-cores-sockets-data.xml

Confusingly, we have a column named `instance_id` on the `hosts` table;
we also have a column named `instance_id` on `instance_measurements`.
However, the `instance_id` on `instance_measurements` references
`hosts.id` and NOT `hosts.instance_id`.
Testing
-------
Try the following sql for testing the trigger change:
```sql
insert into account_services(account_number, service_type) values ('a123', 'HBI_HOST');
insert into hosts(id, instance_id, display_name, account_number, org_id, cores, sockets)
values ('0cfbdd0e-8f5d-4152-9945-f8fd452c2b2d', 'foobar', 'foo', 'a123', 'org123', 4, null);
select * from instance_measurements;
```
The original testing instructions used the same value for both `id` and
`instance_id`, which is possibly why this wasn't caught sooner.
Note that given the …

Fix incorrect liquibase references to instance_id

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResource.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResourceTest.java

This implements the REST API for checking if an Org ID exists in the sync list in accordance with API spec.
https://issues.redhat.com/browse/SWATCH-157
Tested using test file and manually using endpoint.

SWATCH-157 Verify Org ID Exists in Sync List - API Implementation

---

.github/dependabot.yml
Dockerfile
Dockerfile.test
swatch-producer-aws/src/main/docker/Dockerfile.jvm
swatch-producer-aws/src/main/docker/Dockerfile.legacy-jar
swatch-producer-aws/src/main/docker/Dockerfile.native

Also updated the base images to the latest versions for swatch-producer-aws. To see the effect this has, see [my fork](https://github.com/kahowell/rhsm-subscriptions/pulls).

Manage base-images w/ dependabot

---

src/main/java/org/candlepin/subscriptions/security/AllowlistedAccountReportAccessService.java
src/main/java/org/candlepin/subscriptions/security/OptInController.java
src/test/java/org/candlepin/subscriptions/db/OrgConfigRepositoryTest.java
src/test/java/org/candlepin/subscriptions/security/OptInControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/OrgConfigRepository.java

https://issues.redhat.com/browse/SWATCH-174
When opt-in is checked, only the OrgConfig related to
principal is checked (opt-in considered complete).
The ReportingAccessService also needed to be updated to
account for a missing account number to allow the requests
to succeed. Since the reportingEnabled flag is associated
with the account config only, if the account was not specified
during the request, we allow reporting if the org was opted in.
**Testing**
Deploy the app from the develop branch
```
DEV_MODE=true ./gradlew clean :bootRun
```
Generate the required rh-auth tokens for testing:
```
$ echo -n '{"identity":{"account_number":"account123", "internal":{"org_id":"org123"}}}' | base64 -w 0
eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCAiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIz …
```

SWATCH-174 Tolerate missing account number for opt-in checks

---

swatch-metrics/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-178
Relates to: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44490
RHSM Stage & Prod don't connect to a clowder-deployed host-inventory app.  Because of this, there is a slightly different naming convention used to refer to the INVENTORY database secrets.
Similar approach to: https://github.com/RedHatInsights/rhsm-subscriptions/pull/1300

SWATCH-178: Enable parameterized prefix for HBI db name/password secrets

---

swatch-metrics/deploy/clowdapp.yaml

The ClowdApp operator is taking care of setting the args, image, and resources of the token-refresher sidecar.
Theoretically, if we provide the env vars necessary for the args, it'll magically start working
```
--oidc.audience=observatorium-telemeter --oidc.client-id=$(CLIENT_ID) --oidc.client-secret=$(CLIENT_SECRET) --oidc.issuer-url=$(ISSUER_URL) --url=$(URL) --web.listen=:8082
```

SWATCH-178: Define token-refresher env vars on the swatch-metrics pod

---

pr_check.sh

bonfire cicd boilerplate assumes a single clowdapp in the repo, so it
simply uses the templates from `main` branch for all other clowdapps in
a repo. This works around by manually adding args for
`--set-template-ref`

pr_check.sh: Set template ref for all clowdapps

---

src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
src/main/java/org/candlepin/subscriptions/tally/TallySummaryMapper.java
src/main/java/org/candlepin/subscriptions/tally/billing/RemittanceController.java
src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
src/test/java/org/candlepin/subscriptions/tally/TallySummaryMapperTest.java
swatch-core/schemas/tally_summary.yaml

https://issues.redhat.com/browse/SWATCH-241
* Add org_id field to TallySummary definition.
* Set orgId on TallySummary when snapshots are mapped to the summary.
**Testing Notes**
At the moment we are not really able to manually test that the orgId will be set on the TallySummary since the orgId is currently coming from the snapshots. The best we can do at the moment is to ensure that the setting of the orgId is unit tested appropriately.
**TallySnapshot.orgId will be populated by the following:**
- https://issues.redhat.com/browse/SWATCH-97
- https://issues.redhat.com/browse/SWATCH-459

SWATCH-241 Set orgId on TallySummary when mapping snapshots

---

swatch-subscription-sync/deploy/clowdapp.yaml

https://ansible.slack.com/archives/C01F7QFNATC/p1660736722070339?thread_ts=1660675926.497599&cid=C01F7QFNATC
The rhsm-clowdapp.yaml template was creating the capacity-allowlist ConfigMap with values, but then the swatch-subscription-sync was recreating the ConfigMap with a placeholder

Only define capacity-allowlist ConfigMap once

---

bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java

Refactor the orgId from facts query to host.
https://issues.redhat.com/browse/SWATCH-97
Testing Steps
1. Make sure podman creates the inventory db or else get a Host doesn't exist error in the logs.
2. Create mock host using script for insights db
```
INSERT INTO public.hosts (id, account, display_name, created_on, modified_on, facts, tags, canonical_facts, system_profile_facts, ansible_host, stale_timestamp, reporter, per_reporter_staleness, org_id) VALUES ('ad080589-fa8b-4d4b-8e16-0b6f4a3bf239', 'account123', 'physical_ncnmydit.example.com', '2022-08-02 15:02:24.347000 +00:00', '2022-08-02 00:00:00.000000 +00:00', '""', '""', '""', '""', '""', '2022-08-10 15:02:49.813000 +00:00', 'conduit', '{}', '13465533');
```
3. Make sure to create account service in the rhsm db:
```
INSERT INTO …
```

Update HBI-based tallies to populate orgId from HBI org_id column

---

templates/rhsm-subscriptions-scheduler.yml

It's a hack, but the idea is that we unsuspend by setting `DB_CHANGELOG_CLEANUP_SUSPEND: false` and then also adjust the schedule to be in the near future. (e.g. `DB_CHANGELOG_CLEANUP_SCHEDULE: 30 15 19 08 *`).
It's suspended by default so that when we roll the cronjob to prod it'll be a no-op, until we manually toggle it on.
I tested locally via creating a rhsm-db secret as follows:
```
cat <<EOF | oc create -f -
apiVersion: v1
kind: Secret
metadata:
name: rhsm-db
data:
db.host: bG9jYWxob3N0  # localhost
db.user: cGxhY2Vob2xkZXI=  # placeholder
db.name: cGxhY2Vob2xkZXI=  # placeholder
db.password: cGxhY2Vob2xkZXI=  # placeholder
EOF
```
in an ephemeral namespace, and then running:
```
oc process -p DB_CHANGELOG_CLEANUP_SUSPEND=false DB_CHANGELOG_CLEANUP_SCHEDULE='03 15 19 08 *' -p …
```

Add cronjob to cleanup databasechangeloglock

---

swatch-metrics/deploy/clowdapp.yaml

Some jobs seem to be running successfully, but are being marked as failed in stage. Removing the probes to see if it resolves this issue.

Remove probes for the metrics job

---

src/main/resources/liquibase/202208301033-default-null-hardware-measurements.xml
src/main/resources/liquibase/changelog.xml
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/HardwareMeasurement.java

Related to: https://issues.redhat.com/browse/SWATCH-468
On the main branch first
* Shove stage data into your local instance.  i posted a helper script in slack.  hit me up if you can't find it
* Run the purgesnapshot job and observe error
```bash
SPRING_PROFILES_ACTIVE="purge-snapshots,kafka-queue" DEV_MODE=true ./gradlew :bootRun
```
```
Caused by: java.lang.IllegalArgumentException: Can not set int field org.candlepin.subscriptions.db.model.HardwareMeasurement.instanceCount to null value
```
Switch branches, then retest.  Job should complete without error

Fix and prevent null values for instance_count and sockets

---

swatch-tally/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-489
Added a Job and ClowdJobInvokation to migrate org_id into the account_config table. This job will run immediately when deployed.
**Testing**
**FROM THE MAIN BRANCH**
Ensure that the following component is added to your bonfire config:
```
- name: swatch-tally
host: local
repo: /home/mstead/sandbox/swatch/subscriptions/swatch-tally
path: /deploy/clowdapp.yaml
parameters:
REPLICAS: 1
IMAGE: quay.io/cloudservices/rhsm-subscriptions
RHSM_RBAC_USE_STUB: "true"
DEV_MODE: "true"
```
Deploy to EE:
```
$ export NAMESPACE=$(bonfire namespace reserve -d 1h)
$ bonfire deploy -n $NAMESPACE rhsm \
-C rhsm --no-remove-resources=rhsm \
-C swatch-tally --no-remove-resources=swatch-tally \
--optional-deps-method=none \
-i …
```

SWATCH-489 Add Job and ClowdJobInvocation to run account_config org_id migration

---

src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java

https://issues.redhat.com/browse/SWATCH-21
Issue was actually when only virtual sockets/cores are set with no physical sockets/cores and no UOM set in request. Capacities were note being totaled correctly in this case. 
Test Steps: 
```
INSERT INTO public.offering VALUES ('RH00006S', 'RHEL Server', 'Red Hat Enterprise Linux', NULL, NULL, NULL, 2, 'Red Hat Enterprise Linux Server', 'Premium', 'Production', 'Red Hat Enterprise Linux for Virtual Datacenters with Smart Management, Premium', false);
INSERT INTO public.subscription VALUES ('RH00006S', 'org_123', '9427713', 20, '2021-08-31 04:00:00+00', '2022-08-31 04:00:00+00', NULL, NULL, '9427868', NULL, NULL);
INSERT INTO public.subscription VALUES ('RH00006S', 'org_123', '9427714', 10, '2021-09-01 04:00:00+00', …
```

SWATCH-21: Set sockets and cores when virtual UOM value is available for capacity

---

swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
swatch-system-conduit/deploy/clowdapp.yaml

@awood discovered `IMAGE` in #1283, then I decided it would be wise to
check all of our templates. I used a throwaway python script for this:
https://gist.github.com/kahowell/e9b2cf666c45f9de4770bbcedb0e8181
```
python find-dupe-template-params.py $(find -name clowdapp.yaml)
```
revealed
```
Uh-oh! IMAGE already seen in ./swatch-system-conduit/deploy/clowdapp.yaml
Uh-oh! SPLUNK_HEC_URL already seen in ./swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
```
This removes the redundant params.

Remove dupe template params

---

swatch-subscription-sync/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-546

SWATCH-546: add missing rhsm-keystore evn vars to swatch-subscription-sync

---

pr_check.sh

Currently we are using [quay.io/cloudservices/iqe-tests:latest](http://quay.io/cloudservices/iqe-tests:latest) image which comes up with all iqe plugins bundle. Rather than using common image, let's use plugin specific image quay.io/cloudservices/iqe-tests:rhsm-subscriptions to avoid issues due to other plugins.

Use IQE plugin image for tests

---

swatch-api/deploy/clowdapp.yaml
swatch-metrics/deploy/clowdapp.yaml
swatch-system-conduit/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

To test, observe the labels in an EE deployment.
```
oc get Deployment -o jsonpath='{range .items[*]}{.metadata.name}{": "}{.metadata.labels.prometheus}{"\n"}{end}'
```
should include (can ignore other deployments):
```
swatch-api-service: rhsm
swatch-metrics-service: rhsm
swatch-producer-aws-service: quarkus
swatch-producer-red-hat-marketplace-service: rhsm
swatch-subscription-sync-service: rhsm
swatch-system-conduit-service: rhsm
swatch-tally-service: rhsm
```
All `swatch-*` Deployments will have `prometheus=rhsm`, except for swatch-producer-aws, which has `prometheus=quarkus`.

Add prometheus=rhsm label where missing/misapplied

---

dashboards/grafana-dashboard-subscription-watch.configmap.yaml
swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskProcessor.java

https://issues.redhat.com/browse/SWATCH-501
I also replaced the panels for subscription syncing w/ ones for the lag
of offering sync, subscription sync, capacity reconciliation.
You can export the dashboard json by:
```
oc create --dry-run=client -f dashboards/grafana-dashboard-subscription-watch.configmap.yaml -o json | jq -r '.data["subscription-watch.json"]' > dashboard.json
```
and then import into stage grafana. Observe that all graphs are functional again.
I also removed a now-redundant timed annotation...
Spring now provides these metrics automatically:
* `spring_kafka_listener_seconds_count`
* `spring_kafka_listener_seconds_max`
* `spring_kafka_listener_seconds_sum`
I switched our dashboard to the spring-provided metric in this PR.

SWATCH-501: Update dashboards w/ post-clowder names, topics

---

src/main/resources/liquibase/202208301423-set-tally-snapshot-owner-id.xml
src/main/resources/liquibase/changelog.xml

https://issues.redhat.com/browse/SWATCH-290
Test Steps:
```
INSERT INTO public.tally_snapshots VALUES ('06197a03-de1b-49a1-9093-dd61660a8fc1', 'rhosak', 'account123', 'HOURLY', NULL, '2022-06-10 14:00:00+00', NULL, 'Premium', 'Production', 'aws', '027933477046');
INSERT INTO public.tally_snapshots VALUES ('0a4ddeb0-6bcf-493e-a71c-5fc7a987efa8', 'rhosak', '6376293', 'HOURLY', NULL, '2022-07-01 02:00:00+00', NULL, 'Premium', '_ANY', 'aws', '_ANY');
INSERT INTO public.tally_snapshots VALUES ('0beab042-b9ff-4ef3-9a3d-a924f4aa6f97', 'rhosak', '1315336', 'DAILY', NULL, '2022-06-10 00:00:00+00', NULL, 'Premium', '_ANY', '_ANY', '027933477046');
INSERT INTO public.account_config VALUES ('1315336', true, true, 'API', '2022-05-01 00:00:00+00', '2022-05-01 00:00:00+00', '123'); …
```

SWATCH-290: populate owner_id column of tally_snapshots from account_config table

---

bin/GeneratingPrometheusMetricData.adoc
bin/prometheus-mock-data.sh
src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
src/test/java/org/candlepin/subscriptions/metering/MeteringEventFactoryTest.java

https://issues.redhat.com/browse/SWATCH-531
Pretty simple change, but quite difficult to test without mocked prometheus data, so I took our notes about mocked prometheus data and used them to write a script.
The script uses a few environment variables to allow specifying certain labels, metric data. (See `bin/prometheus-mock-data.sh` for more details).
Testing
-------
Start a prometheus w/ mocked data having billing provider `rhm`:
```
BILLING_PROVIDER=rhm bin/prometheus-mock-data.sh
```
With this still running, start the service and point it at the mock data server:
```
PROM_URL="http://localhost:9090/api/v1/" ./gradlew :bootRun
```
Perform metering (adjust timestamp to be roughly the time you started the mock server):
```
type=exec \ …
```

SWATCH-531: Normalize billing provider rhm to red hat

---

swatch-tally/deploy/clowdapp.yaml

Apply POPULATOR_RUN_NUMBER to job name to ensure new job each run: the order that the job is defined, and the ClowdJobInvocation is defined is non-deterministic, which means that the CJI can get outdated definitions otherwise.
Set the timeout to double its default and add a template param so we can tweak further w/out further builds.

Address issues w/ org-id-populator job

---

swatch-core/src/main/java/org/candlepin/subscriptions/db/model/config/OptInType.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/config/OrgConfig.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResource.java
swatch-system-conduit/src/main/spec/internal-organizations-sync-api-spec.yaml
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResourceTest.java

https://issues.redhat.com/browse/SWATCH-161
Test Steps:
- Run app with `DEV_MODE=true ./gradlew :swatch-system-conduit:bootRun`
- Run new API 
`curl -X 'POST'  "http://localhost:8000/api/rhsm-subscriptions/v1/internal/organizations-sync-list?org_ids=1512&org_ids=1612&org_ids=1712" -H 'accept: application/vnd.api+json' -H 'x-rh-swatch-psk: placeholder' `
- Check db for 3 new org_config records

SWATCH-161: implement addOrgsToSyncList api

---

src/main/java/org/candlepin/subscriptions/inventory/db/InventoryDatabaseOperations.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryRepository.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/test/java/org/candlepin/subscriptions/db/AccountConfigRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java

https://issues.redhat.com/browse/SWATCH-497
**NOTE:**
* This PR requires that org_id be set on the AccountConfig (account_config table via opt-in). If the org_id is null, an exception is thrown
* The following PR should be merged and verified working before this is merged (https://github.com/RedHatInsights/rhsm-subscriptions/pull/1353)
**How To Test**
Deploy dependant services:
```
$ podman-compose up -d
```
Import some host data into the local HBI database. 
**The CSV reference here can be found in the comments of SWATCH-497.**
```
$ cat 6089719-hbi-hosts.csv | psql -h 0.0.0.0 -U insights insights -c "copy hosts(id, account, display_name, created_on, modified_on, facts, tags, canonical_facts, system_profile_facts, ansible_host, stale_timestamp, reporter, per_reporter_staleness, org_id) …
```

SWATCH-497 Update hbi queries to use org

---

build.gradle
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/metering/BaseMeteringResource.java
src/main/java/org/candlepin/subscriptions/metering/MeteringConfiguration.java
src/main/java/org/candlepin/subscriptions/metering/ResourceUtil.java
src/main/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResource.java
src/main/java/org/candlepin/subscriptions/metering/jmx/MeteringJmxBean.java
src/main/java/org/candlepin/subscriptions/metering/profile/MeteringJmxProfile.java
src/main/java/org/candlepin/subscriptions/metering/profile/OpenShiftWorkerProfile.java
src/main/java/org/candlepin/subscriptions/resource/api/ApiSpecController.java
src/main/java/org/candlepin/subscriptions/resource/api/InternalMeteringApiJsonResource.java
src/main/java/org/candlepin/subscriptions/resource/api/InternalMeteringApiYamlResource.java
src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
src/main/spec/internal-metering-api-config.json
src/main/spec/internal-metering-api-spec.yaml
src/main/spec/internal-tally-api-spec.yaml
src/test/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResourceTest.java
src/test/java/org/candlepin/subscriptions/metering/jmx/MeteringJmxBeanTest.java
src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java
swatch-core/src/main/java/org/candlepin/subscriptions/util/DateRange.java

https://issues.redhat.com/browse/SWATCH-466
An internal hourly tally API endpoint was added to run the hourly tally
operation for a single account.
Created internal metering API that will run prometheus product metering for a single account.
If the application is run with the RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS (Boolean)
env var set, the API will support synchronous operations. The
hourly tally/metering can be run synchronously if the following request header
is present:
`x-rh-swatch-synchronous-request: true`
**TESTING NOTES:**
* A telemeter instance should be set up via podman (token-refresher)
* Dates in the requests should be updated appropriately to gather current data.
**Test functionality when synchronous operations are disabled**
```
$ DEV_MODE=true …
```

SWATCH-466 Add synchronous api endpoints for tally and metrics

---

src/main/resources/liquibase/202209301035-migrate-org-id-to-hosts-table.xml
src/main/resources/liquibase/changelog.xml

https://issues.redhat.com/browse/SWATCH-134
This patch copies the org_id from the account_config table into the records of the hosts table.
1. drop and recreate the DB:
```
dropdb -U rhsm-subscriptions rhsm-subscriptions && createdb -U rhsm-subscriptions rhsm-subscriptions
```
2. Check out the `main` branch and deploy: `./gradlew clean :bootRun`
3. Populate some account/host data. From the `bin` directory, run:
```
for i in {1..10}; do \
./insert-mock-hosts --account "account-$i" --org "org-$i" --num-physical 200 --num-hypervisors 200; \
psql -U rhsm-subscriptions rhsm-subscriptions -c "insert into account_config (account_number, sync_enabled, reporting_enabled, opt_in_type, created, updated, org_id) values ('account-$i', True, True, 'JMX', '2022-08-24 17:38:01.167262+00', '2022-08-24 …
```

SWATCH-134 Migrate org_id from account_config to hosts

---

src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationConfiguration.java
src/main/java/org/candlepin/subscriptions/product/ProductConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerConfiguration.java
swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskProducerConfiguration.java

We weren't passing enough properties along into the producer config which meant producers were being instantiated without proper auth config for managed kafka.

Fix kafka producer properties building

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
swatch-core/src/main/java/org/candlepin/subscriptions/clowder/RdsSslBeanPostProcessor.java
swatch-core/src/main/resources/swatch-core/application.yaml
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/SystemConduitConfiguration.java

https://issues.redhat.com/browse/SWATCH-102
To test need to setup local database with SSL and add a mock clowder config similar to below:
```
{
"database": {
"sslMode": "require",
"rdsCa": "-----BEGIN CERTIFICATE-----placeholderCertData-----END CERTIFICATE-----\n"
}
}
```

SWATCH-102: Set database ssl properties from clowder config

---

src/main/resources/liquibase/202209301230-migrate-org-id-to-billable-usage-table.xml
src/main/resources/liquibase/changelog.xml

https://issues.redhat.com/browse/SWATCH-152
This patch copies the org_id from the account_config table into the records of the billable_usage_remittance table.
1. drop and recreate the DB:
```
dropdb -U rhsm-subscriptions rhsm-subscriptions && createdb -U rhsm-subscriptions rhsm-subscriptions
```
2. Check out the `main` branch and deploy: `./gradlew clean :bootRun`
3. Create `remittance.sql` file with the following contents.
```
insert into billable_usage_remittance (account_number,org_id,product_id,metric_id,accumulation_period,sla,usage,billing_provider,billing_account_id,remitted_value,remittance_date,version) values ('account-1','','rhosak','Storage-gibibyte-months','2022-06','Premium','Production','azure','test',1,'2022-06-08T11:43:34.243629Z',3)
;
insert into …
```

SWATCH-152 Migrate org_id from account_config to billable_usage_remittance

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionNotFoundException.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionService.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/SubscriptionsException.java

https://issues.redhat.com/browse/SWATCH-19
I also added a timer to the sync by subscription number call, so that we can monitor counts of this issue. Currently we think this only happens in preprod environments with unrealistic test data.
Note that we already had retries set up for this :-)
Testing
-------
Set up keystores/truststores to hit pre-prod RHIT subscription service, then run with:
```
```
Then use the following to mimic a missing account (notice that the command replaces "1234" with a longer string).
```
http -b :9000/hawtio/jolokia \
type=exec \
mbean=org.candlepin.subscriptions.subscription:name=subscriptionJmxBean,type=SubscriptionJmxBean \
operation='enqueueSubscriptionXml(java.lang.String)' \
arguments:="$(cat …
```

SWATCH-19: Warn when the RHIT subs service has no sub

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/test/java/org/candlepin/subscriptions/validator/MacAddressValidatorTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/validator/Iso8601Validator.java
swatch-core/src/main/java/org/candlepin/subscriptions/validator/MacAddress.java
swatch-core/src/main/java/org/candlepin/subscriptions/validator/MacAddressValidator.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/SystemConduitConfiguration.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java

HBI has their own validation regex in [SWATCH-575](https://issues.redhat.com/browse/SWATCH-575)
```
'pattern': '^([A-Fa-f0-9]{2}[:-]){5}[A-Fa-f0-9]{2}$|^([A-Fa-f0-9]{4}[.]){2}[A-Fa-f0-9]{4}$|^[A-Fa-f0-9]{12}$|^([A-Fa-f0-9]{2}[:-]){19}[A-Fa-f0-9]{2}$|^[A-Fa-f0-9]{40}$',
```
However, it seems very peculiar to me.
* `([A-Fa-f0-9]{2}[:-]){5}[A-Fa-f0-9]{2}$` - Similar to mine except this regex allows for heterogeneous delimiters (e.g. `01:23:45-67-89:aa`).  I have elected to not allow these in our code since dear God why would you want that.
* `^([A-Fa-f0-9]{4}[.]){2}[A-Fa-f0-9]{4}$` - Identical in function to the one I have for the 3 groups of 4 hex digits format
* `^[A-Fa-f0-9]{12}$` - 12 hexadecimal digits.  Identical in function to the one I have
* …

SWATCH-575: Validate Mac addresses before pushing them to HBI

---

src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/test/java/org/candlepin/subscriptions/db/model/EventKeyTest.java
swatch-core/schemas/event.yaml
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/EventKey.java

https://issues.redhat.com/browse/SWATCH-593
1. Start from a fresh DB and deploy: `PROM_URL="http://localhost:8888/api/metrics/v1/telemeter/api/v1" DEV_MODE=true ./gradlew clean :bootRun`
2. Trigger a metrics run for a test account:
```
curl -X POST -H "x-rh-swatch-psk: placeholder" "http://localhost:8000/api/rhsm-subscriptions/v1/internal/metering/rhacs?accountNumber=10769791&rangeInMinutes=120"
```
3. Ensure Events were pulled in for the account
```
rhsm-subscriptions=# select count(*) from events;
count 
-------
2
(1 row)
```
4. Re-run the metrics pull to ensure that no duplicate Events were created. The count should be the same.
5. Trigger an hourly tally run for the same account (**ADJUST THE START AND END APPROPRIATELY BASED ON YOUR EVENTS**):
```
curl -X POST -H "x-rh-swatch-psk: …
```

SWATCH-593 add org id to event key and make mandatory

---

swatch-tally/deploy/clowdapp.yaml

----
- Updating references from the old 3scale dev deployment `apicast.3scale-dev.svc.cluster.local` to the new 3scale dev deployment `gateway.3scale-dev.svc.cluster.local`
- The reason for this change is the Infrastructure Team has stood up a new 3scale (Gateway) Deployment to support service serving certificates. Currently, both the old and new deployments are running in parallel so we can aid workstreams in the change over.

Update References to 3Scale Dev Deployment

---

bin/prometheus-mock-data.sh
src/main/java/org/candlepin/subscriptions/event/EventController.java
src/main/java/org/candlepin/subscriptions/jmx/EventJmxBean.java
src/main/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResource.java
src/main/java/org/candlepin/subscriptions/metering/jmx/MeteringJmxBean.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSource.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMeteringTaskFactory.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManager.java
src/main/java/org/candlepin/subscriptions/metering/task/MeteringTasksConfiguration.java
src/main/java/org/candlepin/subscriptions/metering/task/MetricsTask.java
src/main/java/org/candlepin/subscriptions/security/OptInController.java
src/main/resources/application-openshift-metering-worker.yaml
src/main/resources/application.yaml
src/main/spec/internal-metering-api-spec.yaml
src/test/java/org/candlepin/subscriptions/db/EventRecordRepositoryTest.java
src/test/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResourceTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSourceTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusServiceTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/QueryHelper.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMeteringTaskFactoryTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManagerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/AccountConfigRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java

https://issues.redhat.com/browse/SWATCH-205
I only modified methods that are involved in metrics ingestion. Additionally, I left methods in-place used to trigger metrics ingestion for an account, modifying them to look up the orgId by opt-in.
I modified our prometheus mock data script to allow emptying fields.
Testing
=======
In the background (or separate terminal), run a prometheus instance with mocked data:
```shell
ACCOUNT='' bin/prometheus-mock-data.sh&
```
Start the server, with some debug logging enabled (so you can see the queries if desired):
```shell
LOGGING_LEVEL_ORG_CANDLEPIN=DEBUG \
PROM_URL="http://localhost:9090/api/v1" \
```
Before testing, clear the account config and org config tables.
```shell
psql -h localhost -U …
```

SWATCH-205: Gather metrics by orgId instead of accountNumber

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/java/org/candlepin/subscriptions/user/StubAccountApi.java
src/main/resources/application-openshift-metering-worker.yaml
swatch-core/src/main/resources/tag_profile.yaml

This is to address https://issues.redhat.com/browse/SWATCH-297
Add new tags for rhods in tagprofile yaml
Update ProdcutId in api-spec
Add new queryParam template for addons in metering worker yaml.
Testing Steps:
1. Setup profiles in your configuration with the following
```
DEV_MODE=true;SPRING_PROFILES_ACTIVE=openshift-metering-worker;PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1;USER_USE_STUB=true
```
2. Add the following in MeteringJMXBean to test that 'rhods' would be accepted as a query.
```
http://localhost:9000/hawtio/jolokia/exec/org.candlepin.subscriptions.metering.jmx:name=meteringJmxBean,type=MeteringJmxBean/performCustomMeteringForAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.Integer).
The parameters: 301721915996, rhods, …
```

SWATCH-297: Configure RHODS product in tag_profile

---

src/main/resources/application-openshift-metering-worker.yaml
src/test/resources/test_tag_profile.yaml
swatch-core/src/main/resources/tag_profile.yaml

https://issues.redhat.com/browse/SWATCH-577
Test Steps:
- Run local proxy to Observatorium
- Run MeteringJmxBean performCustomMetering(String, String, Integer) with values (OpenShift-dedicated-metrics, 2022-10-11T11:00:00Z, 60)
- Check db for 2 new events

SWATCH-577: replace deprecated 5mSamples prom query with default query

---

swatch-api/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-576
```bash
export NAMESPACE=$(bonfire namespace reserve)
bonfire deploy -n $NAMESPACE \
-C rhsm \
--no-remove-resources=rhsm \
-C swatch-api \
--no-remove-resources=swatch-api \
--optional-deps-method=none \
-i quay.io/cloudservices/rhsm-subscriptions=3b40fec \
-i quay.io/cloudservices/swatch-producer-aws=3b40fec \
-i quay.io/cloudservices/swatch-system-conduit=3b40fec \
rhsm
```
- A swatch-api-nginx-proxy pod is deployed and eventually gets into a ready state
- From a console in the namespace with the curl command available (you can use the new swatch-api-nginx-proxy one), you can run get a successful response from 
```bash
curl http://rhsm-subscriptions:8000/api/rhsm-subscriptions/v1/version …
```

SWATCH-576: Add nginx-proxy deployment to ClowdApp/swatch-api

---

swatch-core/schemas/event.yaml

Accidentally removed in #1504. Sorry!

Restore rhacs role in event.yaml

---

src/main/java/org/candlepin/subscriptions/resource/TallyResource.java

https://issues.redhat.com/browse/SWATCH-586
Test Steps:
- Insert Test Data:
```
INSERT INTO public.tally_snapshots VALUES ('06197a03-de1b-49a1-9093-dd61660a8fc1', 'RHEL for x86', 'account123', 'DAILY', 'org123', '2022-10-10 00:00:00+00', NULL, 'Premium', '_ANY', '_ANY', '_ANY');
INSERT INTO public.tally_snapshots VALUES ('0beab042-b9ff-4ef3-9a3d-a924f4aa6f97', 'RHEL for x86', 'account123', 'DAILY', 'org123', '2022-10-10 00:00:00+00', NULL, 'Premium', '_ANY', '_ANY', '_ANY');
INSERT INTO public.tally_measurements VALUES ('06197a03-de1b-49a1-9093-dd61660a8fc1', 'VIRTUAL', 'CORES', 1);
INSERT INTO public.tally_measurements VALUES ('0beab042-b9ff-4ef3-9a3d-a924f4aa6f97', 'HYPERVISOR', 'CORES', 6);
```
- Run curl to get hypervisor tallies (should get value of 6):
```
curl -X 'GET' \ …
```

SWATCH-586: seperate virtual and hypervisor report categories for tally api

---

swatch-tally/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-482
By default it's a no-op, by defaulting the sql used to `select 1`.
In order to use, we'll need to set the template parameters appropriately.
Specifically, `DB_CHANGELOG_CLEANUP_RUN_NUMBER` should be bumped and `DB_CHANGELOG_CLEANUP_SQL` should be set to `delete from databasechangeloglock`
Testing
-------
Deploy to ephemeral, adjust the template parameters via bonfire:
```
bonfire deploy rhsm -C rhsm -C swatch-tally \
-p swatch-tally/DB_CHANGELOG_CLEANUP_RUN_NUMBER=2 \
-p swatch-tally/DB_CHANGELOG_CLEANUP_SQL='delete from databasechangeloglock' \
--no-remove-resources=all \
-i quay.io/cloudservices/rhsm-subscriptions=latest
-f
```
Afterwards, observe the resulting pod logs (e.g. `pod/swatch-tally-db-changelog-cleanup-2-h1fx8pr-fzh6d`):
```
DELETE …
```

SWATCH-482: Add db-changelog-cleanup job

---

src/main/resources/liquibase/202208251616-migrate-cores-sockets-data.xml
src/main/resources/liquibase/changelog.xml
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/HardwareMeasurement.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java

Because the `hardware_measurements` to `tally_measurements` migrations were very large, they can't reasonably be done via liquibase without blocking CronJobs from running. Previous PRs (#1520 and follow-ons) have been written to perform the migrations async in the background. In order to unblock the current release, we want to have the readers of the data read from either `hardware_measurements` or `tally_measurements` (whichever has data). (Once the migrations are done, we'll remove this workaround).
1. Drop instances from the changelog, because it's not actually used by the UI anyways.
2. Temporarily comment out the problematic changelog.
3. Restore HardwareMeasurement JPA entity.
4. Add logic to read cores/sockets, etc. from HardwareMeasurement when apparently missing from …

Workaround some migration issues w/ HardwareMeasurement

---

src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/tally/admin/DataMigration.java
src/main/java/org/candlepin/subscriptions/tally/admin/DataMigrationRunner.java
src/main/java/org/candlepin/subscriptions/tally/admin/HardwareMeasurementMigration.java
src/main/resources/liquibase/changelog.xml

Testing
=======
Clear tally snapshots table and related:
```
truncate tally_snapshots cascade ;
```
Insert some test data:
```
insert into tally_snapshots(id, product_id, account_number, granularity, owner_id, snapshot_date, unit_of_measure, sla)
VALUES (gen_random_uuid(), 'RHEL', 'account123', 'DAILY', 'org123', now(), null, 'Premium');
insert into tally_snapshots(id, product_id, account_number, granularity, owner_id, snapshot_date, unit_of_measure, sla)
VALUES (gen_random_uuid(), 'RHEL', 'account123', 'DAILY', 'org123', now(), null, 'Premium');
insert into hardware_measurements(snapshot_id, measurement_type, cores, instance_count, sockets)
select id, 'PHYSICAL', 2, 3, 4
from tally_snapshots;
insert into tally_measurements(snapshot_id, measurement_type, uom, value)
select snapshot_id, …
```

Add data migration via JMX to workaround large datasets

---

src/main/java/org/candlepin/subscriptions/jmx/OptInJmxBean.java
src/main/java/org/candlepin/subscriptions/resource/OptInResource.java
src/main/java/org/candlepin/subscriptions/security/AllowlistedAccountReportAccessService.java
src/main/java/org/candlepin/subscriptions/security/OptInChecker.java
src/main/java/org/candlepin/subscriptions/security/OptInController.java
src/main/resources/liquibase/202210101553-make-account-config-org-id-nullable.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/AccountConfigRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/OptInResourceTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/security/OptInCheckerTest.java
src/test/java/org/candlepin/subscriptions/security/OptInControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/AccountConfigRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/DatabaseAccountListSource.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/config/AccountConfig.java

https://issues.redhat.com/browse/SWATCH-477
I had to adjust the ID for AccountConfig entity to be orgId (we had already adjusted the table primary key).
I had to make the account_number column nullable as well.
Testing
=======
Delete any existing opt-in data:
```shell
psql -h localhost -U rhsm-subscriptions -c 'truncate account_config'
psql -h localhost -U rhsm-subscriptions -c 'truncate org_config'
```
Run the server:
```shell
RHSM_RBAC_USE_STUB=true ./gradlew :bootRun
```
1. Non-opted in identity having only `org_id` can get proper response.
```shell
http :8000/api/rhsm-subscriptions/v1/opt-in \
x-rh-identity:$(echo '
{"identity":{
"type":"User",
"user":{"is_org_admin":true},
"internal":{"org_id":"org123"}
}}' | base64 -w0)
```
returns 200 having `"opt_in_complete": false`
2. Tally API …

SWATCH-477: Tolerate missing account number w/ opt-in

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/jmx/OptInJmxBean.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/java/org/candlepin/subscriptions/resource/OptInResource.java
src/main/java/org/candlepin/subscriptions/security/OptInController.java
src/main/resources/liquibase/202210101642-drop-unused-opt-in-flags.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/AccountConfigRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/OrgConfigRepositoryTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
src/test/java/org/candlepin/subscriptions/resource/OptInResourceTest.java
src/test/java/org/candlepin/subscriptions/security/OptInControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/AccountConfigRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/OrgConfigRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/config/AccountConfig.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/config/BaseConfig.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/config/OrgConfig.java

Testing
=======
Run the server:
```shell
```
Observe at http://localhost:8000/api-docs that the opt-in API no longer mentions any of the flags.
Verify that getting opt-in status still works:
```shell
http :8000/api/rhsm-subscriptions/v1/opt-in \
x-rh-identity:$(echo '
{"identity":{
"type":"User",
"user":{"is_org_admin":true},
"internal":{"org_id":"org123"}
}}' | base64 -w0)
```
Verify that opting in still works:
```shell
http PUT :8000/api/rhsm-subscriptions/v1/opt-in \
x-rh-identity:$(echo '
{"identity":{
"type":"User",
"user":{"is_org_admin":true},
"internal":{"org_id":"org123"}
}}' | base64 -w0)
```
Verify that opting out still works:
```shell
http DELETE :8000/api/rhsm-subscriptions/v1/opt-in \
x-rh-identity:$(echo '
{"identity":{
"type":"User", …
```

SWATCH-477: Remove unused opt-in flags

---

swatch-api/deploy/clowdapp.yaml
swatch-metrics/deploy/clowdapp.yaml
swatch-producer-aws/deploy/clowdapp.yaml
swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
swatch-subscription-sync/deploy/clowdapp.yaml
swatch-system-conduit/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

There was an oversight in the move to clowder, these changes need to scale replicas by template param changes.
I added it to the clowdapps, and then added the template param if missing (it was only missing in swatch-metrics and swatch-producer-aws).

Add missing replicas template param/usage

---

src/main/resources/liquibase/202210211001-set-account-services-org-id.xml
src/main/resources/liquibase/changelog.xml

https://issues.redhat.com/browse/SWATCH-583
Test Steps:
```
INSERT INTO public.account_config VALUES ('account637', true, true, 'API', '2022-05-01 00:00:00+00', '2022-05-01 00:00:00+00', 'org637');
INSERT INTO public.account_config VALUES ('account899', true, true, 'API', '2022-05-01 00:00:00+00', '2022-05-01 00:00:00+00', 'org899');
INSERT INTO public.account_config VALUES ('account765', true, true, 'API', '2022-06-06 13:45:37.020113+00', '2022-07-05 18:14:08.738855+00', 'org765');
INSERT INTO public.account_services VALUES ('account637', 'HBI_HOST', 'org637');
INSERT INTO public.account_services VALUES ('account899', 'HBI_HOST', 'org899');
INSERT INTO public.account_services VALUES ('account765', 'HBI_HOST', 'org765');
```
- Start app with DEV_MODE=true ./gradlew …

SWATCH-583: add liquibase to populate org_id on existing account_services records

---

src/main/spec/internal-subscriptions-sync-api-spec.yaml

Was causing:
```
SUBSCRIPTIONS1002: Client request failed validation. - getAwsUsageContext.orgId: must not be null
```
and
```
SWATCHAWS1004: Error looking up AWS usage context
```

Mark orgId as optional in aws usage context lookup

---

api/rhsm-subscriptions-api-spec.yaml

https://issues.redhat.com/browse/SWATCH-647
We handled missing account_number with opt-in in  https://github.com/RedHatInsights/rhsm-subscriptions/pull/1505 , But it was still marked as required in openapi spec.

SWATCH-647 - remove required account_number from optin api spec

---

src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
src/test/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategyTest.java

This corrects a bug where we were clearing hourly measurements on processing each successive hour in a given day. This was happening because we adjust the range of fetched existing snapshots to include enough to aggregate the next granularity (hourly -> daily), and we were treating all fetched snapshots as affected by the gathered usage (rather than just the given hour).
Testing
=======
Run through these steps once on `hotfix` or `main`, and then on this branch.
Run mock prometheus:
```shell
bin/prometheus-mock-data.sh
```
Clear state:
```shell
delete from tally_snapshots cascade;
delete from hosts cascade;
EOF
```
```shell
PROM_URL=http://localhost:9090/api/v1 \
``` …

SWATCH-654: bugfix: only a single set of measurements kept per day

---

src/main/java/org/candlepin/subscriptions/jmx/AccountResetJmxBean.java
src/main/java/org/candlepin/subscriptions/tally/AccountResetService.java
src/test/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepositoryTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/AccountServiceInventoryRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java

https://issues.redhat.com/browse/SWATCH-195
Test Steps:
- Add test data to be deleted:
```
INSERT INTO public.account_services VALUES ('account345', 'HBI_HOST', 'org345');
INSERT INTO public.events VALUES ('09443c41-a773-4e22-970b-07256b0bf43d', 'account345', '2021-10-18 20:00:00+00', '{"sla": "Premium", "role": "osd", "org_id": "org123", "event_id": "09443c41-a773-4e22-970b-07256b0bf43d", "timestamp": "2021-10-18T20:00:00Z", "event_type": "snapshot_redhat.com:openshift_dedicated:4cpu_hour", "expiration": "2021-10-19T20:00:00Z", "instance_id": "aeb1f778-af79-4708-8401-35a5a9e8e877", "display_name": "aeb1f778-af79-4708-8401-35a5a9e8e877", "event_source": "prometheus", "measurements": [{"uom": "Cores", "value": 8.4}], "service_type": "OpenShift Cluster", "account_number": "account123", …
```

SWATCH-195: update AccountResetJmx to reset based on orgId

---

src/main/java/org/candlepin/subscriptions/retention/PurgeSnapshotsJob.java
src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
src/test/java/org/candlepin/subscriptions/retention/TallyRetentionControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java

This is to address https://issues.redhat.com/browse/SWATCH-298
Add new method for AccountConfigRepository to provide the stream of orgs Refactor orgId reference in EventRecordRepository
Refactor TallyRetentionController to use orgId instead of account Refactor Unit test for Tally Retention lookup.
Rebased Merge Conflicts

SWATCH-298: Update Tally Retention lookup by OwnerId

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/CustomizedSubscriptionCapacityRepositoryImpl.java

https://issues.redhat.com/browse/SWATCH-622
Test Steps:
- Create or update 2 Subscriptions/Subscription_capacities, one with has_unlimited_usage = true and one with it set to false.
- Search for each using http://localhost:8000/api-docs/index.html#/capacity/getCapacityReportByMetricId and check that has_infinite_quantity is set correctly

SWATCH-622: add has_infinite_quantity to capacity metric response

---

src/main/java/org/candlepin/subscriptions/resource/ReportCriteria.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/SnapshotRollerTester.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java

https://issues.redhat.com/browse/SWATCH-262
Test Steps:
- Start app with `DEV_MODE=true ./gradlew :bootRun`
- Opt in org456:
```
curl -X 'PUT' \
'http://localhost:8000/api/rhsm-subscriptions/v1/opt-in' \
-H 'x-rh-identity: ewogICAgImlkZW50aXR5IjogewogICAgICAgICJhY2NvdW50X251bWJlciI6ICJhY2NvdW50NDU2IiwKICAgICAgICAidHlwZSI6ICJVc2VyIiwKICAgICAgICAidXNlciIgOiB7CiAgICAgICAgICAgICJpc19vcmdfYWRtaW4iOiB0cnVlCiAgICAgICAgfSwKICAgICAgICAiaW50ZXJuYWwiIDogewogICAgICAgICAgICAib3JnX2lkIjogIm9yZzQ1NiIKICAgICAgICB9CiAgICB9Cn0='
```
- Insert tally_snapshots
```
INSERT INTO public.tally_snapshots VALUES ('0beab042-b9ff-4ef3-9a3d-a924f4aa6f97', 'RHEL for x86', 'account123', 'DAILY', 'org123', '2022-10-10 00:00:00+00', NULL, 'Premium', '_ANY', '_ANY', '_ANY');
INSERT …
```

Update tally api to search by orgId instead of accountNumber

---

src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java

https://issues.redhat.com/browse/SWATCH-268
Testing
=======
Insert some hosts.
```shell
bin/insert-mock-hosts \
--num-guests=4 \
--num-hypervisors=1 \
--hypervisor-id=eb0d994a-e129-4a18-860d-3e39294f95df
```
```shell
```
Hit the hosts endpoint and ensure it works correctly:
```shell
http :8000/api/rhsm-subscriptions/v1/hosts/products/RHEL \
x-rh-identity:$(echo -n '{"identity":{
"type":"User",
"user":{"is_org_admin":true},
"internal":{"org_id":"org123"}
}}' | base64 -w0)
```
Notice account_number is not provided.
Hit the guests endpoint and ensure it works correctly:
```shell
http :8000/api/rhsm-subscriptions/v1/hosts/eb0d994a-e129-4a18-860d-3e39294f95df/guests \
x-rh-identity:$(echo -n '{"identity":{
"type":"User", …
```

SWATCH-268: Change hosts APIs underlying queries to use org_id

---

dashboards/grafana-dashboard-subscription-watch.configmap.yaml

Update the db dashboards to include a panel for the database burst balance. 
Also set default environment to production
You can export the dashboard json by:
`oc create --dry-run=client -f dashboards/grafana-dashboard-subscription-watch.configmap.yaml -o json | jq -r '.data["subscription-watch.json"]' > dashboard.json
`
and then import into stage grafana. Observe that all graphs are functional again.

Add BurstBalance to DB stats to grafana dashboard & set default environment to production

---

bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/UsageCalculationTest.java
src/test/java/org/candlepin/subscriptions/tally/collector/Assertions.java
src/test/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollectorTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/tally/UsageCalculation.java

https://issues.redhat.com/browse/SWATCH-671
We were not yet using separate tally measurement categories for hypervisor and virtual.
Testing
=======
Insert some hosts.
```shell
bin/insert-mock-hosts \
--num-hypervisors 1 \
--num-guests 4 \
--hbi \
--clear \
--org org123
bin/insert-mock-hosts \
--num-guests 1 \
--hbi \
--org org123
```
```shell
```
Ensure opt-in:
```shell
type=exec \
mbean=org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean \
operation='createOrUpdateOptInConfig(java.lang.String,java.lang.String,boolean,boolean,boolean)' \
arguments:='["account123","org123",true,true,true]'
```
Trigger a tally:
```shell
type=exec \ …
```

SWATCH-671: Separate tally measurements: virtual/hypervisors

---

src/main/resources/liquibase/202211071027-change-account_services-pkey.xml

In order to fix an issue deploying where an error like:
```
Caused by: liquibase.exception.DatabaseException: ERROR: update or delete on table "account_services" violates foreign key constraint "fk_hosts_account_services" on table "hosts"
Detail: Key (account_number, service_type)=(6356567, HBI_HOST) is still referenced from table "hosts". [Failed SQL: (0) DELETE FROM public.account_services WHERE org_id is null]
```
happens because there are host rows that reference account_services rows missing org_id in stage specifically.

Reorder account_services liquibase change

---

src/test/java/org/candlepin/subscriptions/validator/IpAddressValidatorTest.java
src/test/java/org/candlepin/subscriptions/validator/MacAddressValidatorTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/validator/IpAddressValidator.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/SystemConduitConfiguration.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/ConduitFacts.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

Also modify some of the logic around how we handle validation for lists of items versus singleton items.  We want to check lists of items for truncation ("127.0.0.1,192...") and log if the value is truncated.  For singleton items, we don't expect any commas to split on or truncation tokens.  If there happens to be a comma or truncation token, the value will fail the ordinary validation anyway.
See SWATCH-684

SWATCH-684: Add stricter validation to IP addresses in facts

---

swatch-subscription-sync/deploy/clowdapp.yaml

adding Red Hat OpenShift Container Platform for Distributed Computing (Edge Server), Premium (2 Cores or 4 vCPUs) to the allow list (and F3 variant)
see SDB-3267

SDB-3267: adding MW01382 and variant to the list

---

swatch-core/src/main/java/org/candlepin/subscriptions/logback/RhsmSplunkHecEventHeaderSerializer.java

This applies specifically to our spring-boot based deployments.
Since we were using a custom event header serializer, we need to supply `time` appropriately.
Testing
=======
Check the ephemeral deployment for this PR. Check in splunk for `namespace=${ephemeral_namespace} host=swatch-tally-service*`. Note that the timestamp emitted in `message` and recorded for the splunk event should match down to the microsecond.

Capture time properly in splunk HEC events

---

clients/subscription-client/subscription-api-spec.yaml

Per internal IT ticket, trailing slash should prevent bad re-routing when transient service failures happen.

Add trailing slash to subscription service URLs

---

src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/tally/admin/OrgIdToTallySnapshotMigration.java

This is address https://issues.redhat.com/browse/SWATCH-631
Add new migrator for OrgId to populate Tally Snapshot Add new endpoint to reference New data migration.
Adjusted query to filter properly by accountNumber
Test Steps:
1. Either clear org_id in Tally snapshot or insert test data below.
```
INSERT INTO public.tally_snapshots (id, product_id, account_number, granularity, org_id, snapshot_date, unit_of_measure, sla, usage, billing_provider, billing_account_id) VALUES ('c5310125-46bd-4991-94f8-dccadab62245', 'rhosak', 'account123', 'DAILY', '', '2021-10-31 00:00:00.000000 +00:00', null, 'Premium', '_ANY', 'red hat', 'dummyId');
INSERT INTO public.tally_snapshots (id, product_id, account_number, granularity, org_id, snapshot_date, unit_of_measure, sla, usage, billing_provider, …
```

SWATCH-631: Migrate Data for OrgId To TallySnapshot Table

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/RemittanceControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java

https://issues.redhat.com/browse/SWATCH-692
Testing
=======
(Adapted from #1177).
Clean out relevant tables:
```shell
delete from events;
delete from tally_snapshots;
delete from instance_monthly_totals;
delete from instance_measurements;
delete from billable_usage_remittance;
EOF
```
```shell
```
Load events into the DB:
```shell
bin/import-events.py --file bin/events.csv
```
Opt in all accounts from the events:
```shell
type=exec \
mbean=org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean \
operation='createOrUpdateOptInConfig(java.lang.String,java.lang.String,boolean,boolean,boolean)' \ …
```

SWATCH-692: Make BillableUsageController use orgId instead of account

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/main/resources/liquibase/202211091649-rename-physical-virtual-cores-sockets-columns.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
src/test/java/org/candlepin/subscriptions/db/OfferingRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/model/OfferingTest.java
src/test/java/org/candlepin/subscriptions/product/UpstreamProductDataTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerOnDemandTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacity.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityView.java

https://issues.redhat.com/browse/SWATCH-591
* Physical sockets are now just referred to as "sockets".
* Physical cores are now just referred to as "cores".
* Virtual sockets are now referred to as "hypervisor sockets".
* Virtual cores are now referred to as "hypervisor cores".
Note: I left the deprecated capacity API alone since it will be removed in the near future.
Testing
=======
Insert some data:
```shell
bin/insert-mock-hosts \
--num-hypervisors 1 \
--num-guests 4 \
--hbi \
--clear \
--org org123
bin/insert-mock-hosts \
--num-guests 1 \
--hbi \
--org org123
```
```shell
```
Ensure opt-in:
```shell
type=exec \
mbean=org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean \ …
```

SWATCH-591: Rename physical & virtual cores & sockets

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceProperties.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/main/resources/application.yaml
swatch-core-test/src/main/resources/application-test.yaml
swatch-subscription-sync/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-133
- Start app with: `DEV_MODE=true ./gradlew :bootRun`
- Curl: `curl   'http://localhost:8000/api/rhsm-subscriptions/v1/internal/subscriptions/awsUsageContext?orgId=123&date=2022-01-01T00%3A00Z&productId=rhosak&sla=Premium&usage=Production&accountNumber=123&awsAccountId=123'   -H 'accept: application/json'   -H 'x-rh-swatch-psk: placeholder'`
- Check logs to ensure force sync messages are not there: 
```
2022-11-21 18:51:39,058 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.subscription.SubscriptionSyncController] self- Starting force sync for orgId: 123
2022-11-21 18:51:39,069 [thread=http-nio-8000-exec-1] [INFO ] [org.candlepin.subscriptions.subscription.SubscriptionSyncController] self- Finished force sync for orgId: 123
```

SWATCH-133: add flag to enable and disable forced subscription sync for payg subs

---

swatch-metrics/deploy/clowdapp.yaml

* The token refresher sidecar doesn't create health probes and is triggering DVO check failures
* Add annotations to bypass these checks for the deployment due to the sidecar.
Related to: https://issues.redhat.com/browse/SWATCH-564

SWATCH-564: Add annotations to ignore sidecar DVO checks

---

swatch-core/src/main/resources/tag_profile.yaml

Actual SKU product name ended up different than initially expected.

Adjust RHACS product name

---

src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java

https://issues.redhat.com/browse/SWATCH-738
This issue was a regression caused by an oversight during a refactor of the InventoryAccountUsageCollector.
Generate some hosts in the HBI database.
```
./bin/insert-mock-hosts --num-hypervisors 4 --num-guests 8 --hbi --clear --org org123 --account account123
```
Delete the hosts in the Swatch DB
```
psql -U rhsm-subscriptions rhsm-subscriptions -c "delete from hosts"
```
Run the application.
```
```
Opt-int the org.
```
http :9000/hawtio/jolokia   type=exec   mbean=org.candlepin.subscriptions.jmx:name=optInJmxBean,type=OptInJmxBean   operation='createOrUpdateOptInConfig(java.lang.String,java.lang.String,boolean,boolean,boolean)'   arguments:='["account123","org123",true,true,true]'
```
Run the nightly tally for …

Delete stale hosts (no longer in HBI) during tally

---

src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/main/java/org/candlepin/subscriptions/security/OptInController.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/spec/internal-subscriptions-sync-api-spec.yaml
src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
src/test/java/org/candlepin/subscriptions/db/AccountConfigRepositoryTest.java
src/test/java/org/candlepin/subscriptions/security/OptInControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/AccountConfigRepository.java
swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java

I'm sorry about the single PR that covers the 3 cards (subtasks) but as I was working on them, they were all sort of dependant on one another and were hard to untangle without conflicts.
1. https://issues.redhat.com/browse/SWATCH-648
* Ignore account when not found during opt-in.
* Remove unnecessary account checks when metering
2. https://issues.redhat.com/browse/SWATCH-723
* Properly set account during hourly tally
We were setting account_number on account calculations based on AccountInventoryService.account which may not exist if there is no account associated with an org. This patch will set it based on the first host instance that has a value set. This way the account number is in essance coming from the event that created the host.
3. https://issues.redhat.com/browse/SWATCH-724
* …

SWATCH-648 SWATCH-723 SWATCH-724 Various fixes for account => orgId migration

---

buildSrc/src/main/groovy/swatch.java-conventions.gradle
buildSrc/src/main/groovy/swatch.spring-boot-dependencies-conventions.gradle
swatch-core-test/build.gradle
swatch-producer-aws/build.gradle

When I switched my JAVA_HOME to java 17, I got some odd errors like
```
> Could not resolve all task dependencies for configuration ':testRuntimeClasspath'.
> Could not resolve project :swatch-core-test.
Required by:
project :
> No matching variant of project :swatch-core-test was found. The consumer was configured to find a runtime of a library compatible with Java 11, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally but
...
```
which was happening because the swatch-core-test was being built w/ default compatibility (17 when JAVA_HOME points to Java 17). By applying the swatch.java-conventions, its explicitly set to Java 11, along with the rest of the swatch modules.

Add swatch.java-conventions to swatch-core-test

---

src/main/resources/liquibase/202301041519-fix-tally-snapshot-index-for-rollup-query.xml
src/main/resources/liquibase/changelog.xml

Turns out that because the unique constraint had `account_number` as one of its first columns, the query planner was unable to use this index, and instead fell back to a much less specific index.
This change reorders the columns a bit to make it hopefully less likely to need updates in the future, and removes `account_number`.
Testing
-------
Start the service on the `main` branch:
```shell
```
Next, insert some data into the tally_snapshots table (this makes the query planner more likely to actually use the index :-))
```shell
do
\$\$
begin
for i in 1..10000
loop
insert into tally_snapshots(id, product_id, account_number, granularity, org_id, snapshot_date,
unit_of_measure, sla)
values (
gen_random_uuid(),
'RHEL',
i, …
```

Fix unique tally constraint for rollup query

---

src/main/java/org/candlepin/subscriptions/product/OfferingJmxBean.java
src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
src/main/java/org/candlepin/subscriptions/product/OfferingWorker.java
src/main/java/org/candlepin/subscriptions/subscription/ActiveMQServiceConfiguration.java
src/main/java/org/candlepin/subscriptions/subscription/ActiveMQUtils.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorker.java
src/main/java/org/candlepin/subscriptions/umb/UmbProperties.java
src/test/java/org/candlepin/subscriptions/product/OfferingJmxBeanTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingWorkerTest.java
src/test/java/org/candlepin/subscriptions/umb/UmbPropertiesTest.java

https://issues.redhat.com/browse/SWATCH-358
1. Run:
```USER_USE_STUB=true SUBSCRIPTION_USE_STUB=true CG_USE_STUB=true CLOUDIGRADE_ENABLED=false DEV_MODE=true ./gradlew clean :bootRun```
2. Execute the JMX endpoint in offeringJmxBean> syncProductFromXml(String) with the content present in one of the file: 
>src/test/resources/mocked-product-message.xml
or
src/test/resources/mocked-svc-product-message.xml
3. Result in log:
```2023-01-04 21:00:56,921 [thread=org.springframework.jms.JmsListenerEndpointContainer#0-1] [INFO ] [org.candlepin.subscriptions.product.OfferingWorker] - Received UMB message for productSku=RH0180191```
5. Note: The rest of the controller syncUmbProduct code will be done as part of SWATCH-395

SWATCH-358 On OperationalProduct message listener call syncoffering

---

README.md
src/main/resources/application.yaml
swatch-metrics/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-770
The ENABLE_SYNCHRONOUS_OPERATIONS environment variable can be used to enable/disable synchronous admin operations.
The ENABLE_SYNCHRONOUS_OPERATIONS parameter can be specified in the swatch-tally and swatch-metrics templates to enable the feature when deploying.
Test that the environment variable can be used to enable this feature.
1. Deploy the app without setting the env var
```
PROM_URL="http://localhost:8888/api/metrics/v1/telemeter/api/v1" SPRING_PROFILES_ACTIVE=openshift-metering-worker,worker,kafka-queue DEV_MODE=true ./gradlew clean :bootRun
```
2. Test that the synchronous operations are disabled. 
```
curl -X POST -H "x-rh-swatch-synchronous-request: true" -H "x-rh-swatch-psk: placeholder" …
```

SWATCH-770 Allow enabling synchronous operations via template parameter

---

src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryDatabaseOperations.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryRepository.java
src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/SystemThresholdException.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/resources/application-worker.yaml
swatch-tally/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-782
`TALLY_MAX_HBI_ACCOUNT_SIZE` when overridden limits the size of accounts that will be processed. Any account going over this limit will be logged with a warning, and skipped.
Note that I intentionally set the default to `Integer.MAX_VALUE`, as this makes it easy to "disable" the check by just not overriding it, and I plan to override with a reasonable value for prod specifically via template parameter.
Testing
-------
Set up some fake HBI data:
```shell
bin/insert-mock-hosts --num-physical=2 --org=org123 --hbi
```
Run the service with a low threshold:
```shell
TALLY_MAX_HBI_ACCOUNT_SIZE=1 ./gradlew :bootRun
```
Trigger a tally:
```shell
type=exec \
mbean='org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxB …
```

SWATCH-782: Add a configurable threshold for HBI tallies

---

swatch-system-conduit/deploy/clowdapp.yaml
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/rhsm/RhsmClientConfiguration.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/rhsm/RhsmProperties.java
swatch-system-conduit/src/main/resources/application.yaml
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/rhsm/RhsmServiceTest.java

https://issues.redhat.com/browse/SWATCH-760
In order to alleviate transient connection issues that current retry settings are insufficient for.
Testing
-------
See that the following env vars are respected/validated by setting them to `placeholder` and seeing the deployment fail:
```shell
RHSM_MAX_ATTEMPTS=placeholder \
./gradlew :swatch-system-conduit:bootRun
RHSM_BACK_OFF_MAX_INTERVAL=placeholder \
./gradlew :swatch-system-conduit:bootRun
RHSM_BACK_OFF_INITIAL_INTERVAL=placeholder \
./gradlew :swatch-system-conduit:bootRun
RHSM_BACK_OFF_MULTIPLIER=placeholder \
./gradlew :swatch-system-conduit:bootRun
```
Then run with:
```shell
RHSM_URL=http://localhost:8910/does-not-exist \
RHSM_MAX_ATTEMPTS=1 \
./gradlew :swatch-system-conduit:bootRun
```
and see it fail quickly with an attempt to …

SWATCH-760: Make conduit retries configurable, bump defaults

---

swatch-tally/deploy/clowdapp.yaml

Default to empty string, this doesn't set tolerations at all (see https://github.com/RedHatInsights/clowder/blob/a85b276baf1b70f31d8fab1f325dcc5e64cc2617/controllers/cloud.redhat.com/providers/job/impl.go#L80)

Add MACHINE_POOL parameter to swatch-tally

---

swatch-tally/deploy/clowdapp.yaml

Default to empty string, this doesn't set tolerations at all (see https://github.com/RedHatInsights/clowder/blob/a85b276baf1b70f31d8fab1f325dcc5e64cc2617/controllers/cloud.redhat.com/providers/job/impl.go#L80)

[hotfix] Add MACHINE_POOL parameter to swatch-tally

---

swatch-tally/deploy/clowdapp.yaml

In order to make the jobs easier to schedule.

Apply separate memory requests/limits & machinePool to jobs

---

src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepositoryTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java

Our category filter for physical systems operated on the principle that physical systems have zero hypervisor cores and zero hypervisor sockets. This assumption is true in theory; however, we must also account for systems that have *null* hypervisor cores and *null* hypervisor sockets. In fact, looking at the production data, there are *no* records in subscriptions_capacity that have a zero for hypervisor_cores or hypervisor_sockets; they all use null instead.
This patch adds the consideration of null values when filtering for physical systems.
See https://issues.redhat.com/browse/SWATCH-761
Should also fix https://issues.redhat.com/browse/SWATCH-590
---
* The easiest test is just to take this PR as a patch, remove the patch sections under `src/main` and apply only the unit tests.  Run …

SWATCH-761: Consider null values for sockets and cores when filtering by category

---

bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/main/resources/liquibase/202301031409-update-tally-instance-view.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewSpecification.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/HardwareMeasurementType.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceView.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceViewKey.java

https://issues.redhat.com/browse/SWATCH-587
Test Steps:
- Create test hosts: `bin/insert-mock-hosts   --num-guests=1   --num-hypervisors=1   --hypervisor-id=eb0d994a-e129-4a18-860d-3e39294f95df`
- Start app with: `DEV_MODE=true ./gradlew :bootRun`
- Run curl and should get records with VIRTUAL, PHYSICAL and HYPERVISOR measurement categories:
`curl -X 'GET'   'http://localhost:8000/api/rhsm-subscriptions/v1/instances/products/RHEL'   -H 'accept: application/json'   -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='`

SWATCH-587: use tally_instance_view to get records for instance api

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/RemittanceControllerTest.java
src/test/resources/test_tag_profile.yaml
swatch-core/src/main/resources/tag_profile.yaml

This is to address  [SWATCH-729 ](https://issues.redhat.com/browse/SWATCH-729) 
This is to allow usage to calculate tag-metric for osd specifically as billing factor will be used to remove the hard coded division logic in the RHM Producer. Which is currently dividing the cores uom values for osd by 4. Billing Factor is configured for osd to be 0.25 which should give the same output and make the hard coded logic in the RHM Marketplace Mapper redundant. 
This is a followup to https://github.com/RedHatInsights/rhsm-subscriptions/pull/1661
Run workflow with 'main' and than using the data saved in the DB rerun tally with this branch. The remittance table should have billing factor updated for `osd` and the calculation should be the same for cores value.
```
select * from …
```

SWATCH-729: Migrate osd billling factor

---

swatch-subscription-sync/deploy/clowdapp.yaml

SER0710
Description : Red Hat OpenShift Platform Plus (Bare Metal Node), Self-Support (1-2 sockets, NFR, Partner Only)
SER0683
Description : Red Hat OpenShift Data Foundation Advanced, Self-Support (2 Cores, NFR, Partner Only)

Adding SKUs SER0710 and SER0683

---

clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

https://issues.redhat.com/browse/SWATCH-763
- The problem was we validate IP addresses, but since we use a different code path to populate loop back IPs, we missed to validate there.
1. There are two ways to run this code and verify:
- A: Run with stub
Run: ```RHSM_USE_STUB=true DEV_MODE=true ./gradlew :swatch-system-conduit:bootRun```
- B: Connect with actual service
Change the RHSM_URL to prod url in application.yaml instead of `http://localhost:9090`. Run the script `fetch-vault-credentials`) by changing environment and token to get prod certs and keystore.
Run: ```DEV_MODE=true ./gradlew :swatch-system-conduit:bootRun```
2. Run: ```http :8000/api/rhsm-subscriptions/v1/internal/rpc/syncOrg   x-rh-swatch-psk:placeholder   org_id=11716302```
3. In both cases it shouldn't emit message …

SWATCH-763 Error parsing IP Address on rhsm-conduit messages to HBI

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java

https://issues.redhat.com/browse/SWATCH-807
-added UOM query param to filter by
Test Steps (non PAYG filtered skips instance_monthly_totals filter by month):
- Create test hosts:` bin/insert-mock-hosts   --num-guests=1   --num-hypervisors=1   --hypervisor-id=eb0d994a-e129-4a18-860d-3e39294f95df`
- Start app with: DEV_MODE=true ./gradlew :bootRun
- Run curl and should get records with VIRTUAL, PHYSICAL and HYPERVISOR measurement categories:
- `curl -X 'GET'   'http://localhost:8000/api/rhsm-subscriptions/v1/instances/products/RHEL?uom=cores'   -H 'accept: application/json'   -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='`
Test Steps(no duplicates for non …

SWATCH-807: Don't filter by month if product is non PAYG in instance API

---

swatch-subscription-sync/deploy/clowdapp.yaml

MCT4383 - Premium: Red Hat OpenShift Platform Plus for OpenShift Container Platform, Premium (On-Demand, Production Support)

Adding Sku MCT4383

---

src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java

This is to address https://issues.redhat.com/browse/SWATCH-730
This is the last phase of changes for implementing billing factor from https://github.com/RedHatInsights/rhsm-subscriptions/pull/166.
This is regression testing only.
Run workflow with 'main' and than using the data saved in the DB rerun tally with this branch. The remittance table should have billing factor updated for `osd` and the calculation should be the same for cores value.
```
select * from billable_usage_remittance where product_id = 'OpenShift-dedicated-metrics';
```
```shell
USER_USE_STUB=true SUBSCRIPTION_USE_STUB=true CG_USE_STUB=true CLOUDIGRADE_ENABLED=false DEV_MODE=true ./gradlew clean :bootRun
```
Load events into the DB:
```shell
bin/import-events.py --file bin/events.csv
```
Opt in all …

SWATCH-730:Remove Hard coded division from RHM Producer

---

src/main/java/org/candlepin/subscriptions/product/OfferingJmxBean.java
src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java
src/main/java/org/candlepin/subscriptions/umb/Reference.java
src/main/java/org/candlepin/subscriptions/umb/UmbOperationalProduct.java
src/main/resources/liquibase/202212161446-add-derived-sku-to-offering.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/OfferingRepositoryTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java
src/test/java/org/candlepin/subscriptions/product/UpstreamProductDataTest.java
src/test/java/org/candlepin/subscriptions/umb/OperationalProductMessageTest.java
src/test/resources/mocked-product-message.xml
src/test/resources/mocked-svc-product-message.xml
swatch-core/src/main/java/org/candlepin/subscriptions/db/OfferingRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java

https://issues.redhat.com/browse/SWATCH-395
The implementation uses the RHIT product service when necessary to fetch
additional information.
I had to add a "derived_sku" column to offering to be able to detect if
derived SKU changes.
Testing
-------
Start the service:
```shell
LOGGING_LEVEL_ORG_CANDLEPIN=DEBUG \
PRODUCT_USE_STUB=true \
```
Using JMX, trigger sync the mocked product message in src/test/resources:
```shell
type=exec \
mbean=org.candlepin.subscriptions.product:name=offeringJmxBean,type=OfferingJmxBean \
operation='syncProductFromXml(java.lang.String)' \
arguments:="$(cat src/test/resources/mocked-product-message.xml | jq -R -s '[.]')"
```
You should see the product definition for RH0180191 land in the offering …

SWATCH-395: Add methods to sync offering data from UMB messages

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java

This is to address [SWATCH-764](https://issues.redhat.com/browse/SWATCH-764)
Issue: rhsm-conduit received a host that had a single digit as its `os_release` which was 5.
```
"system_profile":{"operating_system":{"name":"RHEL"},"os_release":"5","arch":"x86_64","bios_vendor":"Phoenix Technologies LTD"}
```
The current logic is that we only set system profile major and minor when we receive a string with the length of 2, which is the cause of this problem, and to prevent a edge case `"` an additional condition has been added.
Testing Steps
---
1. Run Rhsm-conduit with these environment viables or profiles:
```
DEV_MODE=true;RHSM_USE_STUB=true
```
2. Go to `StubRhsmApi` and make the `distribution.version` a single digit number.
3. Run `syncOrg(String)` in Hawtio for conduit, the input string …

Fix Missing Major release

---

clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
swatch-system-conduit/schemas/inventory/hbi-system-profile.yaml
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/main/spec/internal-organizations-sync-api-spec.yaml
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

https://issues.redhat.com/browse/SWATCH-98
- Description: You should see in the kafka queue under system_profile> is_marketplace true if "aws_billing_products" fact is present and non-empty or "azure_offer" fact is present, non-empty, and not equal to "rhel-byos". In all other cases it won't show up in the feed since it will be null. The way to test this is through stub since I checked with teamnado team and QA they don't have an org that contains above fields in RHSM API.
1. Run with stub
Run: ```RHSM_USE_STUB=true DEV_MODE=true ./gradlew :swatch-system-conduit:bootRun```
2. Run: ```http :8000/api/rhsm-subscriptions/v1/internal/rpc/syncOrg   x-rh-swatch-psk:placeholder   org_id=org123```
3. Result: 
- New message sent in Kafka queue `platform.inventory.host-ingress`
- ```0,3233,Mon Jan …
```

SWATCH-98 Populate is_marketplace if present in azure or aws facts

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java

This hot-fix is to address a prod issue for https://issues.redhat.com/browse/SWATCH-843,
as billing factor was not set in remittance table and the calculation were returning `Null` whenever we try to get the information from the latest remittance.
the following  [line.](https://github.com/RedHatInsights/rhsm-subscriptions/blob/7d3d306928fff3f3562c6e2563c9d680596531b8/src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java#L117)  was the only place billing factor is being set. instead it was pointed out that billing factor should be set from `BillableUsageCalculation` and assign billing factor outside the calculation method.

[hotfix] SWATCH-843: Hotfix to address billable usage NPE in prod

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/test/java/org/candlepin/subscriptions/tally/billing/RemittanceControllerTest.java

This hot-fix is to address a prod issue for https://issues.redhat.com/browse/SWATCH-843,
as billing factor was not set in remittance table and the calculation were returning `Null` whenever we try to get the information from the latest remittance.
the following  [line.](https://github.com/RedHatInsights/rhsm-subscriptions/blob/7d3d306928fff3f3562c6e2563c9d680596531b8/src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java#L117)  was the only place billing factor is being set. instead it was pointed out that billing factor should be set from `BillableUsageCalculation` and assign billing factor outside the calculation method.

SWATCH-843: Hotfix to address the billable usage NPE issue

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java

- and fix category to return "cloud" instead of "aws,gcp etc.."
https://issues.redhat.com/browse/SWATCH-822
Test Steps:
- Insert data: 
```
INSERT INTO public.hosts VALUES ('3f01028c-728a-454b-a801-6736e557700f', 'ff9e9f28-304d-4825-863f-cab7aaa251a8', '5925020', NULL, 'org123', 'attackiq-1.zdalisv.dfw.com', 'a337f14f-7e7e-49b8-a47c-694a087bb92e', NULL, NULL, true, NULL, 'AWS', NULL, '2023-01-17 00:55:49.420985+00', true, false, NULL, 'HBI_HOST', 'ff9e9f28-304d-4825-863f-cab7aaa251a8', NULL, NULL);
INSERT INTO public.host_tally_buckets VALUES ('3f01028c-728a-454b-a801-6736e557700f', '', 'RHEL for IBM z', '', true, 2, 1, 'AWS', '_ANY', '_ANY', 0);
INSERT INTO public.host_tally_buckets VALUES ('3f01028c-728a-454b-a801-6736e557700f', '_ANY', 'RHEL for IBM z', '', true, 2, 1, 'AWS', '_ANY', …
```

SWATCH-822: Update instance api reponse to include cloud_provider 

---

buildSrc/src/main/groovy/swatch.java-conventions.gradle
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/HypervisorReportCategory.java

* Download swatch-590.dump.gz from https://issues.redhat.com/browse/SWATCH-590
* `gunzip swatch-590.dump.gz`
* Create a test database: `createdb -h localhost -U postgres -O rhsm-subscriptions swatch590`
* Import to the test database: `psql -h localhost -U rhsm-subscriptions swatch590 -f ~/swatch-590.dump`
* Start the application against the test database: `DATABASE_DATABASE=swatch590 ./gradlew :bootRun`
* On `main`:
* Request capacity reports for a) no category, b) physical, and c) hypervisor:
```shell
http :8000/api/rhsm-subscriptions/v1/capacity/products/RHEL/Sockets granularity==daily \
beginning==2023-01-31T11:00:00.000Z ending==2023-02-01T11:59:59.999Z \
x-rh-identity:$(echo -n '{"identity":{"account_number":"7108473","type":"User","user":{"is_org_admin":true},"internal":{"org_id":"14 …
```

SWATCH-590: Correct handling of report category for capacity reports

---

pr_check.sh

Having a placeholder juint may confuse prchecks and could result in green checks even if no tests were run

Do not have a placeholder mock juint

---

Dockerfile
Dockerfile.test
swatch-producer-aws/src/main/docker/Dockerfile.jvm
swatch-producer-aws/src/main/docker/Dockerfile.legacy-jar

Bumps ubi9/openjdk-17 from 1.13-10.1669632202 to 1.13-12.1675790156.
---
updated-dependencies:
- dependency-name: ubi9/openjdk-17
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>

Consolidate some dependabot PRs

---

src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollector.java
src/main/resources/application-worker.yaml
src/test/java/org/candlepin/subscriptions/db/HostTallyBucketRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorLegacyTallyTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/TestAccountBucketTally.java
src/test/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollectorTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/HostTallyBucketRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/AccountBucketTally.java
swatch-core/src/main/java/org/candlepin/subscriptions/tally/UsageCalculation.java
swatch-tally/deploy/clowdapp.yaml

Perform the nightly tally for an org by querying the DB instead
of holding all hosts and their facts in memory to perform the
calculations.
Since everything we are tallying for an org has already been persisted
as 'buckets', we can perform our calculations via the query using
the bucket data. The query is using the cores and sockets on the bucket itself
because these fields are normailzed before being stored, unlike
the instance measurements.
An environment variable was added to allow enabling the old
legacy tally functionality should we identify any issues and would like
to disable the new tally logic.
This new tally logic should address the issue outlined in bug [SWATCH-49 Virtual satellites are not considered in tally](https://issues.redhat.com/browse/SWATCH-49) and will likely cause …

SWATCH-687 Perform nightly tallies via DB

---

bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/inventory/db/InventoryRepository.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/resources/application-worker.yaml
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java
src/test/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollatorTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
swatch-tally/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-686
By ordering records from HBI and swatch in a consistent order, and then collating the results, we
can handle updates with minimal memory usage.
I integrated with changes from #1776; this update strategy is applied only when
`legacyNightlyTallyEnabled=false`.
In order to make the logic easier to follow (and hopefully easier to re-use once we start processing
HBI events), I split the changes up as follows:
1. a new class `InventorySwatchDataCollator` that handles collation of streams of system information
from HBI and swatch.
2. methods added to InventoryAccountUsageCollector that handle reconciliation of state between HBI
and swatch
3. a coordinator method in InventoryAccountUsageCollector that invokes `InventorySwatchDataCollator`
and flushes at …

SWATCH-686: Minimize nightly memory usage by streaming system updates

---

src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/main/spec/internal-subscriptions-sync-api-spec.yaml
src/test/java/org/candlepin/subscriptions/db/OfferingRepositoryTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/OfferingRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/ErrorCode.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/MissingOfferingException.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/mapper/OfferingExceptionMapper.java

https://issues.redhat.com/browse/SWATCH-829
- **Description**: This is a new API that will allow any service to lookup the swatch product(s) associated with a given SKU. (This lookup will use the offering information already stored in the database) and map the`product_name` to a swatch `product_tag` via info in `tag_profile.yaml`. If the offering does not exist then return 404. If it does exist, then return an empty list if there are no tags found for that particular offering.
- **Test Steps**:
```
INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku) VALUES ('MW01484', 'OpenShift Dedicated', null, 0, 0, 0, 0, 'osd', 'Premium', 'Production', 'Red Hat OpenShift …
```

SWATCH-829 Endpoint that swatch contracts can use to map a SKU to the swatch product tags

---

src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java

To set the account number on the AccountUsageCalculation, we pull the account number from the NormalizedFacts of the hosts.  The code is written such that the account number is set when processing the first host and that subsequent host processing will check to make sure the account number is unchanged in the NormalizedFacts.  Any NormalizedFacts object with a differing account number results in an IllegalArgumentException.  A comment notes that "there could be stale data in inventory with no account set".
There is an edge case where the first NormalizedFacts object has no account set and the others do.  In that case, we would actually want to update the account number with the more meaningful data.  This patch alters InventoryAccountUsageController#collect() to only throw the …

SWATCH 868: Suppress warning about shifting account number for empty string

---

README.md
bin/BASILISK.csv
bin/prometheus-mock-data.sh
src/main/resources/liquibase/202302141154-add-basilisk-product.xml
src/main/resources/liquibase/changelog.xml
swatch-core/schemas/event.yaml
swatch-core/src/main/resources/tag_profile.yaml
swatch-subscription-sync/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-800
It's essentially RHOSAK, but with a different product_tag, offering name, and product/role.
We chose RHOSAK, because it's a recent PAYG implementation and has multiple metrics.
Note I also updated the mock prometheus script to use monthly storage metrics.
Testing
=======
Try running a mock prometheus w/ BASILISK data:
```shell
PRODUCT=BASILISK bin/prometheus-mock-data.sh
```
Also run our service:
```shell
```
Trigger an import of metrics (adjust the timestamp to be top of the previous hour):
```shell
type=exec \
mbean=org.candlepin.subscriptions.metering.jmx:name=meteringJmxBean,type=MeteringJmxBean \
operation='performCustomMetering(java.lang.String,java.lang.String,java.lang.Integer)' …
```

SWATCH-800: Add BASILISK placeholder PAYG product

---

api/rhsm-subscriptions-api-spec.yaml

SWATCH-800: Add BASILISK to api spec

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java

https://issues.redhat.com/browse/SWATCH-864
Test Steps
- Insert mock hosts: `bin/insert-mock-hosts --num-physical=1`
- Start app with: `DEV_MODE=true ./gradlew :bootRun`
- curl -X 'GET'   'http://localhost:8000/api/rhsm-subscriptions/v1/instances/products/RHEL?uom=cores'   -H 'accept: application/json'   -H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='
- Check that 'id' matches host id field and instance_id matches instance_id field

SWATCH-864: add instance_id and host id to instance api

---

bin/insert-mock-hosts
src/main/resources/liquibase/202302151544-remove-uuid-cast-on-instance-id-in-tally-instance-view.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceViewKey.java

https://issues.redhat.com/browse/SWATCH-869
Our instance view was casting host.instance_id to a UUID, but,
host.instance_id on the hosts table isn't always a proper UUID(
i.e OpenShift Clusters).
When querying against the view, if the instance_id stored in the
host table is not a proper UUID, it would cause an error at the DB level.
This patch removes the cast on instance_id and updates the field to a
String in the view class.
**NOTE** This PR also fixes a couple issues in the insert-mock-hosts script. The fixes are in separate commits.
**Check out this PR's branch so that the fixes are applied to the insert-mock-hosts script** and insert a couple mock hosts into the tally DB.
```
bin/insert-mock-hosts --org=123456 --num-physical=2
```
**CHECK OUT THE MAIN BRANCH**
Determine the host IDs …

SWATCH-869 Remove cast on instance_id in tally_instance_view

---

README.md
src/main/java/org/candlepin/subscriptions/ApplicationProperties.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/main/resources/application-worker.yaml
swatch-system-conduit/README.md
swatch-system-conduit/deploy/clowdapp.yaml
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/rhsm/RhsmService.java
swatch-system-conduit/src/main/resources/application.yaml
swatch-tally/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-853
Assumptions about conduit updates being processed before tally were insufficient. Accordingly, we're adding some timing slack.
Per PM input:
* Updated stale threshold to 30 hours (instead of 24 hours).
* Updated the schedule for nightly tallies to 6 am UTC, so HBI has longer to process updates before we tally.
With this change, systems that haven't checked in can take up to 30 hours before being filtered from tallies.
I also changed the stale threshold to use midnight UTC as its reference point, so that the stale threshold doesn't get offset by the tally schedule. A 30 hour threshold should mean that a system checked in more than 30 hours prior to the last sync, rather than 30 hours from the time of the tally.
Testing
=======
This is essentially …

SWATCH-853: Tally - increase timing slack with conduit

---

src/main/java/org/candlepin/subscriptions/product/UpstreamProductData.java

https://issues.redhat.com/browse/SWATCH-872
Test Steps:
- Configure app to connect to stage product service with appropriate certs.
- start app with `DEV_MODE=true ./gradlew :bootRun `
- Open http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.product-OfferingJmxBean-offeringJmxBean and call operation with sku of empty string "  ";
- Should see log similar too (unsure if we will ever get non null response body but prefer to print in case there is more detail):
```
org.candlepin.subscriptions.exception.ExternalServiceException: Unable to retrieve upstream offeringSku="". API returned status: 404, message: error, and responseBody: null
```

SWATCH-872: update exception message to print relevant product API response info

---

src/test/java/org/candlepin/subscriptions/registry/TagProfileTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/registry/TagMetaData.java
swatch-core/src/main/java/org/candlepin/subscriptions/registry/TagProfile.java
swatch-core/src/main/resources/tag_profile.yaml

TagMetaData now has a new 'contractEnabled' field that can be set for a configured tag. By default it is set to false.
The contractEnabled field can only be set to true if the billingModel field is 'PAYG'. If not, the application will fail to start up, indicating a configuration error.
The BASILISK configuration has been updated to enable contracts.
https://issues.redhat.com/browse/SWATCH-819
1. Start the application and verify that the added configuration for BASILISK does not prevent the application from starting.
```
./gradlew clean :bootRun
```
2. Verify that the app will not start when `contractEnabled` is set to `true` and `billingModel` is NOT `PAYG`. To do this, edit the `tag_profile.yaml` file and set the `billingModel` to anything other than `PAYG` for the BASILISK …

SWATCH-819 Add contractEnabled flag to TagMetaData

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java

**JIRA** https://issues.redhat.com/browse/SWATCH-902
The code was assuming that an OS version will only be made up two parts (major.minor), when in reality it could include more (i.e x.y.z).
This patch ensures that os versions such as 1.2.34, 1.2.3.45 (and so on) are considered when determining the major/minor version values.
1. Check out `main` branch
2. Update the `distribution.version` consumer fact in `StubRhsmApi.java` to reflect the release version in the error message: `5.14.0.70.22.1.rt21.94.rhel9u0`
3. Deploy the  application
```
RHSM_USE_STUB=true DEV_MODE=true ./gradlew swatch-system-conduit:bootRun
```
4. Sync an org via system-conduit
```
http :9000/hawtio/jolokia type=exec mbean=org.candlepin.subscriptions.conduit.jmx:name=rhsmConduitJmxBean,type=RhsmConduitJmxBean …
```

SWATCH-902 Fix major/minor version parsing in system-conduit

---

swatch-subscription-sync/deploy/clowdapp.yaml

RHACS is using an additional SKU. Will also create a hotfix version so we can get this update to prod faster.

SWATCH-965: Add MW02291 to allowlist

---

swatch-tally/deploy/clowdapp.yaml

In order to workaround the requirement that clowder now imposes that a ClowdApp must be ready before a CJI causes a job to be run.

SWATCH-1007 Move db changelog cleanup to its own clowdapp

---

swatch-contracts/build.gradle
swatch-contracts/src/main/java/com/redhat/swatch/rest/SwatchPskHeaderFilter.java
swatch-contracts/src/main/java/com/redhat/swatch/subscriptions/SubscriptionSyncResource.java
swatch-contracts/src/main/java/com/redhat/swatch/subscriptions/mapper/ProductTagsMapper.java
swatch-contracts/src/main/resources/application.properties
swatch-contracts/src/main/resources/swatch_contracts_openapi.yaml

This PR is to address SWATCH-830, we want swatch-contract to have the ability to sync a sku to product tag from rhsm.
Testing Steps:
We want to have data in the offerings table within `rhsm` database:
```
INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku) VALUES ('MW01485', 'OpenShift Container Platform', null, 0, 0, 0, 0, 'ocp', 'Premium', 'Production', 'Red Hat OpenShift Container Platform (Hourly)', null, null);
INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku) VALUES ('MW01484', 'OpenShift Dedicated', null, 0, 0, 0, 0, …
```

SWATCH-830: Subscriptions sync map for swatch contracts

---

docker-compose.yml

If you tear down your postgres pod you deployed with podman-compose, and try to do `podman-compose up -d` again, you start getting permission errors on the public schema.  Seems to be a change with postgres 15, so pinning the docker-compose.yaml file back to postgres-13 as a current working solution to the problem

Pin postgres13 image in podman compose

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

This PR is to address https://issues.redhat.com/browse/SWATCH-896
These changes will allow the newer tally API to display the running total amount when needed.
Testing Steps:
First populate your events table, if you don't have some already in your local DB.
```
INSERT INTO public.events (id, account_number, timestamp, data, event_type, event_source, instance_id, org_id) VALUES ('dcf4adc8-9f23-476a-9c94-9a405ce2facd', 'account123', '2021-10-30 20:00:00.000000 +00:00', '{"sla": "Premium", "role": "osd", "org_id": "org123", "event_id": "dcf4adc8-9f23-476a-9c94-9a405ce2facd", "timestamp": "2021-10-30T20:00:00Z", "event_type": "snapshot_redhat.com:openshift_dedicated:4cpu_hour", "expiration": "2021-11-01T01:00:00Z", "instance_id": "c5mu16smf1c22rn8e730", "display_name": "c5mu16smf1c22rn8e730", …
```

SWATCH-896: Add running total to newer Tally API

---

deploy/stage-internal-test-job.yaml

Fixes typo in the test marker, no tests were selected in internal test job

Fix typo in the marker for tests 

---

swatch-core/src/main/java/org/candlepin/subscriptions/exception/ErrorCode.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResource.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/jmx/RhsmConduitJmxBean.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/jmx/RhsmJmxException.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/tasks/UpdateOrgInventoryTask.java

The InventoryController will now throw an ExternalServiceException instead of a general ApiException. If a 400 is detected when listing consumers from the RHSM API, it assumes that the org does not exist and sets an appropriate error code.
Callers have been updated, where applicable, to log a warning instead of an error (logging the entire exception).
https://issues.redhat.com/browse/SWATCH-561
Launch the app with the RHSM API configured against stage and adjust the backoff interval for retry in swatch-system-conduit. The keystore/password can be found in vault (reach out if you need help with this).
```
RHSM_BACK_OFF_MAX_INTERVAL=1s RHSM_URL=${STAGE_RHSM_API_URL} RHSM_KEYSTORE=${STAGE_RHSM_API_KEYSTORE} RHSM_KEYSTORE_PASSWORD=${STAGE_RHSM_API_KEYSTORE_PASSWORD} DEV_MODE=true ./gradlew …
```

SWATCH-561 Log unknown org as WARNING when not found via RHSM API

---

src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/EntityManagerLookup.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/EntityManagerLookupImpl.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/HostApiProjection.java

https://issues.redhat.com/browse/SWATCH-1015
This PR refactors the hostRepository.findAllBy() method to remove the fetch joins that were causing OOM errors on swatch-api. Fetch joins with sorting causes hibernate to load all objects in memory to do the sorting. Instead, now we use a projection to get all the required fields in the query.
Test Steps: 
```
insert into account_services (org_id, service_type, account_number) values ('16765430', 'OpenShift Cluster', 'account123');
INSERT INTO public.hosts VALUES ('8f782362-3348-4f5c-8643-4dc1e65061ae', '', '', '', '16765430', 'automation_ocp_cluster_e25dbe5e-4130-4695-8b37-a087462cb248', '', false, '', 'CLOUD', NULL, '2023-03-03 20:00:00+00', false, false, '', 'OpenShift Cluster', 'e25dbe5e-4130-4695-8b37-a087462cb248', …
```

SWATCH-1015: Update HostRepository findAllBy to remove fetch joins to prevent OOMs

---

clients/rh-partner-gateway-client/rh-partner-gateway-api-spec.yaml
swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractMetricEntity.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractRepository.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/SubscriptionSyncResource.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/main/resources/openapi.yaml
swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointIntegrationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

https://issues.redhat.com/browse/SWATCH-805
The only way to test this is using test cases. This is because the partner gateway api isn't exposed. We can utilize the api http://localhost:8000/q/swagger-ui/#/default/post_api_rhsm_subscriptions_v1_internal_rpc_partner_contracts in future to send request to controller.
Pass in the json payload as below:
{
"action" : "contract-updated",
"redHatSubscriptionNumber" : "12400374",
"currentDimensions" : [ {
"dimensionName" : "test_dim_1",
"dimensionValue" : "5",
"expirationDate" : "2023-02-15T00:00:00Z"
}, {
"dimensionName" : "test_dim_2",
"dimensionValue" : "10",
"expirationDate" : "2023-02-15T00:00:00Z"
} ],
"cloudIdentifiers" : {
"awsCustomerId" : "EK57ooq39qs",
"productCode" : "ek1lel8qbwnqimt2wogc5nmey"
}
}
Note: The duplicate contract code …

SWATCH-805 Add server partner api to test resource

---

build.gradle
swatch-contracts/build.gradle
swatch-producer-aws/build.gradle

Specifically, this sets all gradle subprojects to use `group com.redhat.swatch`.
I also removed a couple of redundant declarations and removed an incorrect `version` declaration in swatch-contracts.
With this change, the subprojects are imported into Intellij in a consistent way. Though it may be helpful to use File -> Project Structure... -> right click -> expand all, then select all and delete to force intellij to forget old module definitions.

Fix wrong & redundant gradle project properties

---

src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java

https://issues.redhat.com/browse/SWATCH-1019
Test Steps:
```
INSERT INTO public.hosts VALUES ('ba0d9a20-ca1c-4ec6-a22d-78987a228b30', '4a1b9879-7304-4d8c-9376-48f295be780e', '11472998', '11472998', 'org123', 'virtual_xuxwxqyn.example.info', 'a66347b2-854b-4cbf-8d07-14852b8300ad', true, NULL, 'VIRTUALIZED', NULL, '2023-02-27 13:21:11.41413+00', true, false, NULL, 'HBI_HOST', '4a1b9879-7304-4d8c-9376-48f295be780e', NULL, NULL);
INSERT INTO public.host_tally_buckets VALUES ('ba0d9a20-ca1c-4ec6-a22d-78987a228b30', '_ANY', 'RHEL for x86', 'Premium', true, 2, 1, 'VIRTUAL', '_ANY', '_ANY', 0);
INSERT INTO public.host_tally_buckets VALUES ('ba0d9a20-ca1c-4ec6-a22d-78987a228b30', '', 'RHEL for x86', 'Premium', true, 2, 1, 'VIRTUAL', '_ANY', '_ANY', 0);
INSERT INTO …
```

SWATCH-1019: Fix socket sort on instance api to sort by sockets column of hosts

---

swatch-contracts/src/main/resources/application.properties

Just to unblock QE testing in stage.  There's more involved work for SWATCH-882

Enable swatch-contracts test APIs in stage

---

swatch-contracts/build.gradle

Testing
=======
Start the service:
```shell
./gradlew :swatch-contracts:quarkusDev
```
```shell
http :8000/api/swatch-contracts/internal/contracts
```
fails with a 400 response like
```json
{
"classViolations": [],
"parameterViolations": [
{
"constraintType": "PARAMETER",
"message": "must not be null",
"path": "getContract.orgId",
"value": ""
}
],
"propertyViolations": [],
"returnValueViolations": []
}
```

SWATCH-1051: Contracts: Turn on bean validation for openapi gen

---

swatch-subscription-sync/deploy/clowdapp.yaml

Adding SKU Red Hat OpenShift Platform Plus with Red Hat OpenShift Data Foundation Advanced (Bare Metal Node), Standard (1-2 sockets up to 64 cores, Academic)

Adding SKU MW01879S

---

swatch-contracts/build.gradle
swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractMetricEmbeddableId.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractMetricEntity.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractMapperTest.java

https://issues.redhat.com/browse/SWATCH-954
Clean up various warnings:
* jandex warning was resolved by removing unneeded jandex plugin.
* mapstruct warnings resolved by refactoring mapstruct usage.
* datatype warning resolved by changing metric value from `int` to `double`.
No testing instructions for this PR since there is no functionality change, only refactoring and build changes.

SWATCH-954: Cleanup swatch-contracts warnings

---

.rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml

Update the db dashboards to include a panel statistics about usage sent to AWS marketplace
Also set default environment to production
You can export the dashboard json by:
oc create --dry-run=client -f .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml -o json | jq -r '.data["subscription-watch.json"]' > dashboard.json 
and then import into stage grafana. Observe that you can see accepted & rejected message counts.

SWATCH-1074 Add batch stats block to grafana dashboard for aws marketplace

---

clients/rh-partner-gateway-client/rh-partner-gateway-api-spec.yaml
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/RhPartnerClientIntegrationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

https://issues.redhat.com/browse/SWATCH-1050
**Description:**
UMB message structure has changed. This PR takes care of the new structure and also includes changes to accommodate SKU.
**Prereq:**
- `%stage.SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8001/api/rhsm-subscriptions/v1`
- Set `server.port=8001` in application.properties or yaml for swatch-core and start the application using ` DEV_MODE=true ./gradlew :bootRun`.
- Set env variable for contract app: ENABLE_SPLUNK_HEC=false; KEYSTORE_PASSWORD=<Password>; KEYSTORE_RESOURCE=file:/home/...../rhsm-subscriptions/config/certs/keystore.jks; QUARKUS_PROFILE=stage;SWATCH_SELF_PSK=<placeholder>
- Authorize using Name: x-rh-swatch-psk as placeholder http://localhost:8000/q/swagger-ui/#/default/createPartnerEntitlementContract
Test …

SWATCH-1050 Reformat upstream UMB API mapping

---

api/rhsm-subscriptions-api-spec.yaml
swatch-core/schemas/event.yaml

Intentionally added instead of renaming BASILISK, to keep things working

SWATCH-1057 Update our schemas and API to include ROSA as a product

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointIntegrationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/repository/ContractRepositoryTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

https://issues.redhat.com/browse/SWATCH-952
The timestamp query param is used to filter to records active at that timestamp. The start date is treated as inclusive, and the end date as exclusive. In other words, `timestamp==2023-01-01T00:00Z` will match contract records that start on the `2023-01-01T00:00Z`, but not those that end on `2023-01-01T00:00Z`.
Testing
=======
Start the service via `./gradlew swatch-contracts:quarkusDev`
Insert some contracts:
```shell
insert into contracts(uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider,
billing_account_id, product_id)
VALUES ('9bf28398-d147-4a4d-97f1-2e3ab46af681', 'subscription123', now(), '2023-01-01T00:00Z', '2023-02-01T00:00Z', …
```

SWATCH-952: Implement timestamp filter for GET contracts

---

swatch-core/schemas/event.yaml

https://issues.redhat.com/browse/SWATCH-1082
Testing
=======
```shell
```
Manually create an event having `role="moa-hostedcontrolplane"`:
```shell
event=`cat <<EOF
[{
"event_source": "prometheus",
"event_type": "snapshot_redhat.com:rosa:cluster_hour",
"org_id": "org123",
"instance_id": "0688fdc4-5991-4204-8611-74ed0ac0af22",
"timestamp": "2023-03-28T06:00:00Z",
"expiration": "2023-03-28T07:00:00Z",
"display_name": "test",
"measurements": [{"uom": "Instance-hours", "value": 1}],
"role": "moa-hostedcontrolplane",
"sla": "Premium",
"service_type": "rosa Instance",
"billing_provider": "aws"
}]
EOF
`
mbean=org.candlepin.subscriptions.jmx:name=eventJmxBean,type=EventJmxBean \
type=exec \ …
```

SWATCH-1082: Fix rosa event role enum

---

bin/BASILISK.csv
src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
src/main/resources/application-worker.yaml
src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/ErrorCode.java
swatch-tally/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-1083
Also
* changed attempts to 1 for contracts retry (effectively no retry).
* fixed `bin/BASLISK.csv` to use proper storage UOM.
* added an error code to the warning/error.
Testing
=======
Run the contracts service on port 8882:
```shell
SERVER_PORT=8882 ./gradlew :swatch-contracts:quarkusDev
```
```shell
SPRING_PROFILES_ACTIVE=worker,kafka-task-queue \
SWATCH_CONTRACTS_INTERNAL_SERVICE_URL=http://localhost:8882 \
```
Import some events:
```shell
bin/import-events.py --file bin/BASILISK.csv
```
Trigger an hourly tally:
```shell
type=exec \
mbean=org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean \ …
```

SWATCH-1083: Remove retry from billing usage when missing contracts

---

dependencies.gradle
swatch-system-conduit/build.gradle
swatch-system-conduit/deploy/clowdapp.yaml
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/rhsm/RhsmService.java
swatch-system-conduit/src/main/resources/application.yaml
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/rhsm/RhsmServiceTest.java

https://issues.redhat.com/browse/SWATCH-1011
This introduces the following template params/env vars:
* `RHSM_API_LIMIT_FOR_PERIOD` - how many RHSM API operations allowed in the rate limit window.
* `RHSM_API_LIMIT_REFRESH_PERIOD` - how often the rate limit should be refreshed.
* `RHSM_API_LIMIT_TIMEOUT_DURATION` - the max time a pending RHSM API interaction should wait before timing out.
These are set by default to values that enforce an effective limit of 150 requests/second:
* limit: 150
* refresh period: 100ms
* timeout duration: 30m
Timeout chosen as 30m, as this corresponds to our kafka max poll interval (if it takes longer than that the kafka message is going to be rejected anyways)
Testing
=======
Run the application with some overrides to test the rate limiting:
```shell …
```

SWATCH-1011: Implement rate limiting for RHSM API interactions

---

src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java

https://issues.redhat.com/browse/SWATCH-1090
Test Steps:
- Insert events:
```
INSERT INTO public.events (id, account_number, "timestamp", data, event_type, event_source, instance_id, org_id) VALUES ('c107fada-5223-44c6-9ad5-b538a4fd434a', 'account123', '2023-04-05 11:00:00+00', '{"sla": "Premium", "role": "osd", "org_id": "org123", "event_id": "c107fada-5223-44c6-9ad5-b538a4fd434a", "timestamp": "2023-04-05T11:00:00Z", "event_type": "snapshot_redhat.com:openshift_dedicated:4cpu_hour", "expiration": "2023-04-05T12:00:00Z", "instance_id": "7e52a0fc-32da-49f0-83f5-ba38034780a5", "display_name": "automation_osd_cluster_7e52a0fc-32da-49f0-83f5-ba38034780a5", "event_source": "prometheus", "measurements": [{"uom": "Cores", "value": 4.0}], "service_type": "OpenShift Cluster", "account_number": …
```

Retally when start date and instance last_seen are equal

---

swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceViewKey.java

https://issues.redhat.com/browse/SWATCH-949
Test Steps:
- Start app with ` DEV_MODE=true ./gradlew :bootRun`
- Should not see any logs like: "composite-id class does not override hashCode(): org.candlepin.subscriptions.db.model.TallyInstanceViewKey "

swatch-949: add missing hashcode and equals

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/main/resources/META-INF/openapi.yaml
swatch-contracts/src/test/java/com/redhat/swatch/contract/RhPartnerClientIntegrationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

This is to create the Admin API to sync existing contracts and add new contracts if there are not already in the swatch-contract database.
https://issues.redhat.com/browse/SWATCH-839
Testing Steps:
1. Run with with these environment variables:
```
SWATCH_SELF_PSK=placeholder;KEYSTORE_RESOURCE=file:/home/<user>/IdeaProjects/rhsm-subscriptions/config/certs/keystore.jks;ENABLE_SPLUNK_HEC=false;KEYSTORE_PASSWORD=<password>;QUARKUS_PROFILE=stage
```
If you have problems access the Partner API you may need to pull credentials from vault [here](https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=ENT&title=Setting+up+non-prod+credentials)
2. Setup database with test data (both contracts and contract-metrics):
```
INSERT INTO public.contracts (uuid, subscription_number, …
```

SWATCH-839: Add new Admin Api for Contract Sync

---

deploy/stage-internal-test-job.yaml

Removes the selenium Container as the iqe plugin is set to use the selenium grid in place

Remove the Selenium container for using grid

---

clients/rhsm-client/rhsm-api-spec.yaml
clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
swatch-system-conduit/schemas/inventory/hbi-system-profile.yaml
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/main/spec/internal-organizations-sync-api-spec.yaml
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

https://issues.redhat.com/browse/SWATCH-554
**Description:**
1. We have four types of facts stored in HBI hosts. 
* Core information like orgId, IP 
* system_profile_facts json includes non-core information like os_release, 
* canonical_facts json is important for HBI but, not for swatch table. 
* facts are all other information. Facts used to store all values initially and later separated out.
2. We also have two parts to this kind of card. 
* conduit changes include ingesting RHSM feed and then publish it to Kafka queue for HBI
* Rhsm monolith gets the information from HBI table and then store it on our table or send it to analytics team. To pull the information we use InventoryHostFacts and InventoryHost entity. Example https://github.com/RedHatInsights/rhsm-subscriptions/pull/2043
3. …

SWATCH-554 Add 'releaseVer' to rhsm-conduit in facts

---

swatch-tally/deploy/clowdapp.yaml

#References
https://issues.redhat.com/browse/SWATCH-1148
Bug fix for: [SWATCH-1042](https://issues.redhat.com/browse/SWATCH-1042)
The swatch-tally-service requires the Origin header when requests are made to internal endpoints so that the AntiCsrfFilter allows the request.
This was not detected in EE since the swatch-tally-service is running in DEV_MODE when deployed to EE, and the AntiCsrfFilter is disabled.
When testing locally, even with DEV_MODE disabled, deploying with 'capacity-ingress' profile active (i.e default deploy activates all profiles), the anti CSRF filter is disabled. 
No real way to test the job itself other than by merging and deploying.
This is sorta reproducible locally hitting the endpoint manually.
1. Deploy the app with the following profiles.
``` …
```

SWATCH-1148: Fix tally snapshot purge job curl command

---

src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
src/main/java/org/candlepin/subscriptions/security/ApiSecurityConfiguration.java
src/main/java/org/candlepin/subscriptions/security/OptInChecker.java
swatch-core/src/main/java/org/candlepin/subscriptions/exception/mapper/BaseExceptionMapper.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationFailureHandler.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationFilter.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/JolokiaActuatorConfiguration.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/RestAccessDeniedHandler.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/SecurityConfiguration.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/security/ApiSecurityConfiguration.java

*Note to the reviewer*:  I suggest reviewing the commits individually.  One commit is a simple name change of a class, but it can clutter up the diff viewer when viewed with the other commit.  Also, I would recommend using the side-by-side diff view instead of the unified viewer on this PR.  The changes are substantial enough that a unified diff is going to be difficult to parse mentally.
```
http :8000/api/rhsm-subscriptions/v1/instances/products/RHEL beginning==2022-01-01T00:00:00.000Z ending==2023-01-10T23:59:59.999Z x-rh-identity:$(echo -n '{"identity":{"account_number":"account123","type":"User","user":{"is_org_admin":true},"internal":{"org_id":"org123"}}}' | base64 -w0)
```
```
http :8000/api/rhsm-subscriptions/v1/tally/products/OpenShift-dedicat …
```

SWATCH-389: Remove usage of WebSecurityConfigurerAdapter

---

src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

https://issues.redhat.com/browse/SWATCH-1130
When a system having a null sockets value or null coresPerSocket value and `is_marketplace=true` is normalized, it caused an NPE because a comparison to 0 triggers unboxing.
Testing
-------
```shell
```
Insert a mock aws host:
```shell
bin/insert-mock-hosts --num-aws=1 --hbi --org org123
```
Update the host to have `cores_per_socket=0` and `is_marketplace=true`:
```shell
psql -h localhost -U insights insights <<EOF
update hosts set system_profile_facts=jsonb_set(system_profile_facts, '{cores_per_socket}', 'null') where system_profile_facts->>'cloud_provider'='AWS';
update hosts set system_profile_facts=jsonb_set(system_profile_facts, '{is_marketplace}', 'true') where …
```

SWATCH-1130: Fix NPE due to unboxing w/ marketplace systems

---

swatch-subscription-sync/deploy/clowdapp.yaml

Adding SKUs 
ESA0125 "Red Hat OpenShift Platform Plus, Premium (One Year, Enterprise Program)" and  MW01700F3  "Red Hat OpenShift Platform Plus with Red Hat OpenShift Data Foundation Advanced, Standard (2 Cores or 4 vCPUs)"

Adding SKUs

---

src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
src/main/java/org/candlepin/subscriptions/tally/billing/TallySummaryMessageConsumer.java
src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java

https://issues.redhat.com/browse/SWATCH-1164
This ensures that the messages for a given org_id are processed by the same consumer in order, reducing the risk of concurrency bugs in billable usage production.
Testing
=======
Start the app with debug logging turned on:
```shell
LOGGING_LEVEL_ORG_CANDLEPIN_SUBSCRIPTIONS_TALLY_BILLING=DEBUG \
SUBSCRIPTION_USE_STUB=true \
```
Import some events into the DB:
```shell
bin/import-events.py --file bin/events.csv
```
Run the hourly tally for that the test events:
```shell
type=exec \
mbean=org.candlepin.subscriptions.jmx:name=tallyJmxBean,type=TallyJmxBean \
operation='tallyOrgByHourly(java.lang.String,java.lang.String,java.lang.String)' \
arguments:='["org123", …
```

SWATCH-1164: Use org_id as the message key for tally summary messages

---

clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

https://issues.redhat.com/browse/SWATCH-914
Test Steps:
- Start conduit with: `DEV_MODE=true RHSM_USE_STUB=true ./gradlew :swatch-system-conduit:bootRun`
- Sync org 'maxAllowedMemoryOrg':
```
type=exec \
mbean='org.candlepin.subscriptions.conduit.jmx:name=rhsmConduitJmxBean,type=RhsmConduitJmxBean' \
operation='syncOrg(java.lang.String)' \
arguments:='["maxAllowedMemoryOrg"]'
```
-Check logs for **[WARN ] [org.candlepin.subscriptions.conduit.InventoryController] - System memory bytes value 9042521605783552 greater than max allowed value of 9007199254740991. Setting to null.**

SWATCH-914: Set system_memory_bytes to null when over the max allowed value by hbi

---

README.md
src/main/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResource.java
src/main/java/org/candlepin/subscriptions/metering/profile/OpenShiftWorkerProfile.java
src/main/java/org/candlepin/subscriptions/metering/retention/EventRecordsRetentionProperties.java
src/main/java/org/candlepin/subscriptions/metering/retention/PurgeEventRecordsJob.java
src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
src/main/resources/application.yaml
src/main/spec/internal-metering-api-spec.yaml
src/test/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResourceTest.java
swatch-metrics/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

Invoke the job using a curl container.
See https://issues.redhat.com/browse/SWATCH-1105
---
1. Start the application
```shell
./gradlew :bootRun --args="--spring.profiles.active=api,kafka-queue,worker,metering-jmx,metering-job,rhsm-conduit,openshift-metering-worker --rhsm-subscriptions.auth.swatchPsks.self=secret"
```
2. Run the import events script with the default events.  All these events are very old and long past the default retention period.
```shell
bin/import-events.py --file bin/events.csv
```
3. Verify the events were created
```shell
% psql -h localhost -U rhsm-subscriptions rhsm-subscriptions -c 'select count(*) from events'                                                                      
count …
```

SWATCH-1105: Move PurgeEventRecordsJob to internal metrics resource

---

src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
src/main/java/org/candlepin/subscriptions/product/SyncResult.java
src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceConfiguration.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorkerConfiguration.java
src/test/java/org/candlepin/subscriptions/db/OfferingRepositoryTest.java
src/test/java/org/candlepin/subscriptions/files/ProductAllowlistTest.java
src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/OfferingRepository.java

https://issues.redhat.com/browse/SWATCH-773
- Delete offering from db if already existing: `DELETE FROM offering WHERE sku = 'MW01485'`
- Start app with: `DEV_MODE=true PRODUCT_USE_STUB=true SUBSCRIPTION_USE_STUB=true SPRING_PROFILES_ACTIVE=capacity-ingress ./gradlew :bootRun`
- Run syncSubscription: 
```
type=exec \
mbean='org.candlepin.subscriptions.subscription:name=subscriptionJmxBean,type=SubscriptionJmxBean' \
operation='syncSubscription(java.lang.String)' \
arguments:='["any"]'
```
- Check db that offering now exists in db: `SELECT * FROM offering WHERE sku = 'MW01485'`
- Run syncAllOfferings:
```
type=exec \
mbean='org.candlepin.subscriptions.product:name=offeringJmxBean,type=OfferingJmxBean' \
operation='syncAllOfferings()' …
```

SWATCH-773: Remove allowList.allProducts and check DB for existing skus

---

swatch-metrics/deploy/clowdapp.yaml

See https://issues.redhat.com/browse/SWATCH-1216
Jira issue: [SWATCH-1216](https://issues.redhat.com/browse/SWATCH-1216)
SWATCH-1105 (PR #2093) added a job to purge the events table according to a retention policy.  There are either too many events or the job just isn't efficient enough.  Regardless, invoking the internal API endpoint results in the pod being OOMKilled.  This PR disabled and suspends (see [Clowder documentation](https://consoledot.pages.redhat.com/clowder/dev/api_reference.html#k8s-api-github-com-redhatinsights-clowder-apis-cloud-redhat-com-v1alpha1-job)) the OpenShift cronjob for now until we can get around to fixing the core issue.
1. Deploy to one of the EEs
1. `oc create job purge-test --from=cj/swatch-metrics-purge-events`
1. Job fails to create:
```
Error from …
```

SWATCH-1216: Disable swatch-metrics-purge-events job as it leads to OOM on the pod

---

.dockerignore
Dockerfile
build.gradle
dependencies.gradle
swatch-api/deploy/clowdapp.yaml
swatch-metrics/deploy/clowdapp.yaml
swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
swatch-subscription-sync/deploy/clowdapp.yaml
swatch-system-conduit/.dockerignore
swatch-system-conduit/Dockerfile
swatch-system-conduit/build.gradle
swatch-system-conduit/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

Jira issue: [SWATCH-1094](https://issues.redhat.com/browse/SWATCH-1094)
Enables spring boot apps to send Opentelemetry traces to a collector using the splunk java agent.
1. Build project and push to quay. Alternatively, use the bonfire config attached which uses an image I uploaded and replace your repo paths. 
[config.zip](https://github.com/RedHatInsights/rhsm-subscriptions/files/11373579/config.zip)
Reserve an ephemeral namespace for testing:
```shell
oc project $(bonfire namespace reserve)
```
Deploy swatch:
```shell
bonfire deploy rhsm --no-remove-resources swatch-contracts --no-remove-resources swatch-api --no-remove-resources swatch-producer-aws --no-remove-resources swatch-producer-red-hat-marketplace --no-remove-resources swatch-metrics --no-remove-resources …
```

Swatch-1094: spring boot OTel instrumentation

---

src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java

Due to the use of multi-argument error logger it was treating the exception as an argument to the formatter and not a throwable to be logged. 
The MDC logger was already logging the org_id so it was extraneous to include it in the string of the error msg. 
Also removed the call to get the account number which is no longer necessary as we are doing all the calculations by org_id.

Clean up error message that is masking an exception trace

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
swatch-contracts/src/main/resources/META-INF/openapi.yaml

Jira issue: [SWATCH-1258](https://issues.redhat.com/browse/SWATCH-1258)
Currently, it's not possible to call the sync APIs because they're set for `test` only. They should be set for `support` and `test` together.
Run swatch-contract.
Execute: 
```
curl -X 'POST' \
'http://localhost:8000/api/swatch-contracts/internal/rpc/sync/contracts/123' \
-H 'accept: application/json' \
-H 'x-rh-identity: ewogICAgICAgICAgICAgICJpZGVudGl0eSI6IHsKICAgICAgICAgICAgICAgICJ0eXBlIjogIkFzc29jaWF0ZSIsCiAgICAgICAgICAgICAgICAiYXNzb2NpYXRlIiA6IHsKICAgICAgICAgICAgICAgICAgImVtYWlsIjogInRlc3RAZXhhbXBsZS5jb20iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgfQogICAgICAgICAgICB9Cg==' \
-d ''
```
You should be able to authorize and see the below response:
> {
>   "message": "123 not found in table",
>   "status": "FAILED"
> …

SWATCH-1258 Enable sync APIs with support role

---

src/main/java/org/candlepin/subscriptions/security/ApiSecurityConfiguration.java
src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/AntiCsrfFilter.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/GetVerbIncludingAntiCsrfFilter.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/JolokiaActuatorConfiguration.java

Jira issue: [SWATCH-1195](https://issues.redhat.com/browse/SWATCH-1195)
Enable anticsrf filter on capacity-ingress API's
1. Start app with: `./gradlew :bootRun --args="--rhsm-subscriptions.security.dev-mode=false --spring.profiles.active=capacity-ingress,kafka-queue"`
1. Curl with bad origin should return 403: `http PUT :8000/api/rhsm-subscriptions/v1/internal/subscriptions/sync/org/123 x-rh-swatch-psk:placeholder origin:bad`
1. Curl with correct origin should start sync: `http PUT :8000/api/rhsm-subscriptions/v1/internal/subscriptions/sync/org/123 x-rh-swatch-psk:placeholder origin:console.redhat.com`

SWATCH-1195: anti csrf filtering

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillingUnit.java
src/main/java/org/candlepin/subscriptions/tally/billing/MetricUnit.java
src/main/java/org/candlepin/subscriptions/tally/billing/Quantity.java
src/main/java/org/candlepin/subscriptions/tally/billing/RemittanceUnit.java
src/main/java/org/candlepin/subscriptions/tally/billing/Unit.java
src/test/java/org/candlepin/subscriptions/tally/billing/QuantityTest.java

Jira issue: [SWATCH-1198](https://issues.redhat.com/browse/SWATCH-1198)
Description
===========
This helps remove some complexity/confusion by having quantities carry `Units` so that it is more clear what unit is applied to a given number.
Initially, I investigated the javax.measure API and reference implementation, but our needs didn't fit cleanly, so instead, I implemented a couple of classes with interfaces loosely inspired by those in javax.measure, `Unit` representing value's unit and capturing the billingFactor, and `Quantity` representing a (value, `Unit`) tuple.
I moved conversions and a couple of key transformations into the `Quantity` class (namely
`positiveOrZero` and `ceil`). This makes the code a bit easier to read.
Testing
=======
Follow the instructions in #2119

SWATCH-1198: Refactor billable usage conversion to use Quantity class

---

swatch-contracts/build.gradle
swatch-contracts/deploy/clowdapp.yaml
swatch-producer-aws/build.gradle
swatch-producer-aws/deploy/clowdapp.yaml

Jira issue: [SWATCH-1095](https://issues.redhat.com/browse/SWATCH-1095)
Enables OTel in quarkus apps
Reserve an ephemeral namespace for testing:
```shell
oc project $(bonfire namespace reserve)
```
Deploy swatch:
```shell
bonfire deploy rhsm --no-remove-resources swatch-contracts --no-remove-resources swatch-api --no-remove-resources swatch-producer-aws --no-remove-resources swatch-producer-red-hat-marketplace --no-remove-resources swatch-metrics --no-remove-resources swatch-subscription-sync --no-remove-resources swatch-system-conduit --no-remove-resources swatch-tally
```
Create a jaeger all-in-one configuration:
```shell
cat <<EOF > /tmp/values.yaml
provisionDataStore:
cassandra: false
allInOne:
enabled: true
storage:
type: none
agent:
enabled: false
collector:
enabled: false
query: …
```

SWATCH-1095: enable otel on quarkus apps

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/java/org/candlepin/subscriptions/tally/filler/TallyReportDataPointAdapter.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

Jira issue: [SWATCH-1150](https://issues.redhat.com/browse/SWATCH-1150)
Update the value of TallyReportDataPoint to integer and round up from double value.
1.Insert test data:
```
INSERT INTO public.events (id, account_number, timestamp, data, event_type, event_source, instance_id, org_id) VALUES ('dcf4adc8-9f23-476a-9c94-9a405ce2facd', 'account123', '2021-10-30 20:00:00.000000 +00:00', '{"sla": "Premium", "role": "osd", "org_id": "org123", "event_id": "dcf4adc8-9f23-476a-9c94-9a405ce2facd", "timestamp": "2021-10-30T20:00:00Z", "event_type": "snapshot_redhat.com:openshift_dedicated:4cpu_hour", "expiration": "2021-11-01T01:00:00Z", "instance_id": "c5mu16smf1c22rn8e730", "display_name": "c5mu16smf1c22rn8e730", "event_source": "prometheus", "measurements": [{"uom": "Cores", "value": 1.25}], …
```

SWATCH-1105: update TallyReportDataPoint value to int and round up

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/main/java/org/candlepin/subscriptions/tally/billing/ContractMissingException.java
src/main/java/org/candlepin/subscriptions/tally/billing/ContractsController.java
src/test/java/org/candlepin/subscriptions/registry/TagProfileFactoryTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/ContractsControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/registry/TagProfile.java
swatch-core/src/main/resources/tag_profile.yaml

Jira issue: [SWATCH-1260](https://issues.redhat.com/browse/SWATCH-1260)
The contract service API is expecting the vendor specific metric
(awsDimension/rhmMetricId) as the metric_id when fetching contracts.
Before making the API call, convert the UOM to the vendor metric
ID by consulting the tag profile.
The configured awsDimension for ROSA was incorrect based on existing contracts
and has been adjusted.
Since the Contracts API retruns an empty list when a contract
is not found based on the search criteria, this should not
result in an ExternalServiceException. Instead we now throw
a ContractMissingException which is handled by the
BillableUsageController.
As part of this change, ContractController.getContractCoverage
now returns a Double instead of Optional, ensuring that if the
call …

 SWATCH-1260 Use vendor specific metric when calling contracts API 

---

src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionJmxBean.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorker.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorkerConfiguration.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionJmxBeanTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java

Jira issue: [SWATCH-1266](https://issues.redhat.com/browse/SWATCH-1266)
Description
===========
Modify subscription syncing to always remove stale subscription and capacity records. Also modify syncing to process all pages of an org at once. Because this process can take quite a while, I changed the kafka acknowledgement to immediate, which means that if there is a restart during a sync, the org in-progress won't be synced again until the next scheduled (nightly sync).
During smoketesting, I found that a large org can take around 30 minutes on a clean database to process locally, this necessitated the acknowledgement change. I did not see a significant difference in memory usage.
Testing
=======
Setup
-----
1. Insert some mock subscription and subscription_capacity records:
```shell
psql …
```

SWATCH-1266: Modify subscription syncing to remove all stale records

---

src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionPruneController.java
src/main/spec/internal-subscriptions-sync-api-spec.yaml
src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java

Jira issue: [SWATCH-1190](https://issues.redhat.com/browse/SWATCH-1190)
We are converting the endpoint to REST based endpoints for swatch-subscription-sync
1.  `DEV_MODE=true SUBSCRIPTION_USE_STUB=true USER_USE_STUB=true PRODUCT_USE_STUB=true PRODUCT_DENYLIST_RESOURCE_LOCATION=file:/tmp/denylist ./gradlew :bootRun`
2. `echo 'MW01485' > /tmp/denylist`
3. 
```
INSERT INTO public.org_config (org_id, opt_in_type, created, updated) VALUES ('123', 'JMX', '2023-05-22 20:12:21.502130 +00:00', '2023-05-22 20:12:21.502130 +00:00');
INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku) VALUES ('MW01485', 'OpenShift Container Platform', 'OpenShift Enterprise', null, null, …
```

SWATCH-1190 Subscriptions sync endpoint JMX to REST

---

README.md

Jira issue: [SWATCH-1161](https://issues.redhat.com/browse/SWATCH-1161)
Description
===========
Add both swagger-ui and source (in-repo) links. I wrote the markdown to be very readable in both plain-text and rendered format.
Verification
============
View README.md through the GitHub UI.

SWATCH-1161: Add all APIs to README.md

---

README.md
swatch-api/deploy/clowdapp.yaml
swatch-contracts/deploy/clowdapp.yaml
swatch-metrics/deploy/clowdapp.yaml
swatch-producer-aws/deploy/clowdapp.yaml
swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
swatch-subscription-sync/deploy/clowdapp.yaml
swatch-system-conduit/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

Jira issue: [SWATCH-1221](https://issues.redhat.com/browse/SWATCH-1221)
Description
===========
JAVA_DEBUG will be set to `true` in EE only to enable remote debugging in EE.. See README.md for usage
Verification
============
Deploy to an EE, try the command in README.md

SWATCH-1221: Enable remote debugging

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

We were doing a soft delete before we had a way to update an endDate of a contract.  Since we have a way to do that now, and not deleting test contracts is now making a mess in stage, it's time to reenable true deletion.
More context: https://redhat-internal.slack.com/archives/C01F7QFNATC/p1685546969765389?thread_ts=1685545352.820649&cid=C01F7QFNATC

Update delete contracts to actually delete contracts for test cleanup purposes

---

src/main/resources/liquibase/202305231003-update-remittance-table-for-history.xml

1. Add granularity to billable_usage_remittance PK
2. Set 'MONTHLY' as the granularity for existing
remittance records.

Update historical remittance schema changeset

---

clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContactsApi.java
src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducer.java
src/main/java/org/candlepin/subscriptions/tally/billing/Quantity.java
src/main/java/org/candlepin/subscriptions/tally/billing/RemittanceUnit.java
src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingController.java
src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingResource.java
src/main/resources/application-worker.yaml
src/test/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/QuantityTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/RemittanceControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntity.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntityPK.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/RemittanceSummaryProjection.java

Prep your DB.
**NOTE** This will truncate/drop some tables.
```
drop table events;
truncate table hosts cascade;
truncate table tally_snapshots cascade;
truncate table billable_usage_remittance;
EOF
```
Use the attached [remittance-billing-factor-event-data.txt](https://github.com/RedHatInsights/rhsm-subscriptions/files/11407548/remittance-billing-factor-event-data.txt) file to import event metric data into your DB for Feb and March.
```
psql -h localhost -U rhsm-subscriptions < remittance-billing-factor-event-data.txt
```
Start tally worker with stub contract api
```
SPRING_PROFILES_ACTIVE=worker,kafka-task-queue CONTRACT_USE_STUB=true DEV_MODE=true ./gradlew :bootRun
```
Perform a nightly tally across the event date ranges and ensure that …

Update billable_usage_remittance to track history

---

swatch-metrics/deploy/clowdapp.yaml

Revert "Disable swatch-metrics-purge-events job as it leads to OOM on the pod" (https://github.com/RedHatInsights/rhsm-subscriptions/pull/2109)
This reverts commit d4e7be695206be5f8f45d84fdbf2aefd31a76ee1.
Jira issue: [SWATCH-1216](https://issues.redhat.com/browse/SWATCH-1216)
Reenabling the cron job after confirming that invoking purge event no longer causes OOM pod restarts after previous PR (https://github.com/RedHatInsights/rhsm-subscriptions/pull/2189).

SWATCH-1216: Reenable event purge cronjob

---

src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java

Jira issue: [SWATCH-1342](https://issues.redhat.com/browse/SWATCH-1342)
Subscription API is not returning capacity for records. The new subscription_measurements are being saved in all uppercase but being compared to the properly cased values of the enums. This PR makes it so we ignore case when checking the capacity.
1. Insert test data:
```
INSERT INTO public.offering VALUES ('RH00005', 'RHEL Server', 'Red Hat Enterprise Linux', 1, 2, 1, 1, 'Red Hat Enterprise Linux Server', 'Self-Support', 'Production', 'Red Hat Enterprise Linux Server Entry Level, Self-support', false, '');
INSERT INTO public.subscription VALUES ('RH00005', '16772552', '12497245', 1, '2022-06-03 04:00:00+00', '2023-10-20 11:05:11+00', NULL, '11476445', '12497402', NULL, NULL, false);
INSERT INTO public.subscription …
```

swatch-1342: subscription api capacity bug
