RedHatInsights/rhsm-subscriptions

- src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepository.java
Jira issue: [SWATCH-932](https://issues.redhat.com/browse/SWATCH-932)
Get the capacity metrics endpoint to support metrics other than sockets/cores
1. Insert into tables:
- INSERT INTO subscription
```
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, account_number, subscription_number, billing_provider, billing_account_id, has_unlimited_usage) VALUES ('RH3413336', '123', '1234576', 2, '2021-12-08 22:21:40.392000 +00:00', '2021-12-08 22:38:20.392000 +00:00', null, 'null', null, null, null, false);
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, account_number, subscription_number, billing_provider, billing_account_id, has_unlimited_usage) VALUES …
```
> SWATCH-932 Get capacity report by metric id

- src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
Jira issue: [SWATCH-1347](https://issues.redhat.com/browse/SWATCH-1347)
After SWATCH-1202 got deployed the response of getSkuCapacityReport > `api/rhsm-subscriptions/v1/subscriptions/products` is showing Product Name instead of Offering Name in subscription table api.
RH00001 - RHEL Server
RH00004 - RHEL Server
instead we want 
RH00001 - Red Hat Enterprise Linux for Virtual Datacenters, Premium
RH00004 - Red Hat Enterprise Linux Server, Standard (Physical or Virtual Nodes)
1. Insert into tables:
- INSERT INTO subscription
```
INSERT INTO public.subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, account_number, subscription_number, billing_provider, billing_account_id, has_unlimited_usage) VALUES ('MW01882', '123', '235252', 1, '2011-01-01 …
```
> SWATCH-1347 Subscription showing Product Name instead of Offering name

- swatch-contracts/src/test/java/com/redhat/swatch/contract/PathUtils.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ConsumerApiSpecEqualityTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
`quarkus test` runs in a different working directory than when running from Intellij or gradle builds. In order to allow tests to run in either, I implemented a lookup of the project directory by walking up the directory tree looking for `src`.
Before this change, running `quarkus test` doesn't work from the `swatch-contracts` directory, and afterwards it works.
1. Install the quarkus cli
2. `cd swatch-contracts`
1. `git checkout main`
2. `quarkus test` (see failures)
3. ctrl+c after tests run
4. `git checkout khowell/quarkus_test_fixes`
5. `quarkus test` (see no failures)
6. ctrl+c after tests run
1. Observe test failures during the first `quarkus test`
1. Observe no test failures during second `quarkus test`.
> Fix path lookups to work for `quarkus test`

- src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsServiceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsService.java
Description
===========
In some places we were granting `RH_INTERNAL` and in some places simply `INTERNAL`. Because of this, it was not sufficient to auth via x509 cert when using internal endpoints.
Testing
=======
Steps
-----
```shell
```
2. Hit the opt-in endpoint w/ a header mimicing turnpike w/ x509 auth:
```shell
http PUT localhost:8000/api/rhsm-subscriptions/v1/internal/rpc/tally/opt-in \
org_id==org123 \
account_number==account123 \
x-rh-identity:$(echo '{"identity":{"auth_type":"x509","type":"X509","x509":{"subject_dn":"CN=test.example.com"}}}' | base64 -w0) \
Origin:console.redhat.com
```
With `main`, you'll get a 403, with this change, you'll get a success.
> Fix incorrect RH_ prefix from some internal roles

- src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsServiceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsService.java
Description
===========
In some places we were granting `RH_INTERNAL` and in some places simply `INTERNAL`. Because of this, it was not sufficient to auth via x509 cert when using internal endpoints.
Testing
=======
Steps
-----
```shell
```
2. Hit the opt-in endpoint w/ a header mimicing turnpike w/ x509 auth:
```shell
http PUT localhost:8000/api/rhsm-subscriptions/v1/internal/rpc/tally/opt-in \
org_id==org123 \
account_number==account123 \
x-rh-identity:$(echo '{"identity":{"auth_type":"x509","type":"X509","x509":{"subject_dn":"CN=test.example.com"}}}' | base64 -w0) \
Origin:console.redhat.com
```
With `main`, you'll get a 403, with this change, you'll get a success.
> [HOTFIX] Fix incorrect RH_ prefix from some internal roles

- clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContactsApi.java
- src/main/java/org/candlepin/subscriptions/tally/billing/ContractsController.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/ContractsControllerTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointIntegrationTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Jira issue: [SWATCH-1345](https://issues.redhat.com/browse/SWATCH-1345)
Given a pure PAYG contract, which comes across with neither dimensions for vCPUs nor instance hours, the billable usage controller is unable to recognize a contract when trying to send usage to AWS. This should be fixed by not filtering the contract lookup by metricId. For this bug we are changing the method signature in contract and swatch-core.
Clean up any existing data.
```bash
psql -U rhsm-subscriptions rhsm-subscriptions << EOF
-- cleanup the tables
truncate events;
truncate tally_snapshots cascade;
truncate hosts cascade;
truncate billable_usage_remittance;
truncate contracts cascade;
EOF
```
Insert the following data into the DB.
```bash
psql -U rhsm-subscriptions rhsm-subscriptions << EOF
-- contracts
INSERT …
```
> SWATCH-1345 Do not filter the contract lookup by metricId

- src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/OfferingRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
The old code was fetching the offerings for the SKUs one at a time as we moved through the subscriptions.  Instead of hitting the DB over and over again for one offering at a time, this patch consolidates the queries so that we fetch all the offerings at once.
See https://issues.redhat.com/browse/SWATCH-1343
Jira issue: [SWATCH-1343](https://issues.redhat.com/browse/SWATCH-1343)
[SWATCH-1202](https://issues.redhat.com/browse/SWATCH-1202) (PR #2180) introduced a performance regression.  Calls to `api/rhsm-subscriptions/v1/subscriptions/products/{product_id}` were taking a very long time.  Analysis in SignalFx revealed numerous hits to the `offering`, `sku_oid`, and `sku_child_sku` tables over the course of the API call.  This PR consolidates those requests into one batch query for all the …
> SWATCH-1343: Improve performance in SubscriptionTableController

- bin/fetch-gcp-marketplace-license-codes.py
- clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResource.java
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
Jira issue: [SWATCH-122](https://issues.redhat.com/browse/SWATCH-122)
Description
===========
I implemented the stub for `/internal/organizations/$org/inventory`. I also added a script that can be used to get an updated list of licenseCodes.
Testing
=======
Steps
-----
1. Run the service:
```shell
RHSM_USE_STUB=true \
./gradlew swatch-system-conduit:bootRun
```
2. Call the conduit debugging API to see what the value for is_marketplace is:
```shell
http ':8000/api/rhsm-subscriptions/v1/internal/organizations/gcpOrg/inventory?limit=10' \
x-rh-swatch-psk:placeholder
```
Verification
------------
Observe `is_marketplace=true`.
> SWATCH-122: Add GCP Marketplace detection to swatch-system-conduit

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
We can have multiple subscriptions with the same subscription ID.  It's the combination of ID and start date that's unique.  To avoid collisions, this patch uses that tuple for a map key instead of the subscription ID alone.
See https://issues.redhat.com/browse/SWATCH-1356
Jira issue: [SWATCH-1356](https://issues.redhat.com/browse/SWATCH-1356)
This PR corrects an ongoing issue in stage.  We're seeing stacktraces that look like
```
2023-06-14 09:43:48,468 [thread=http-nio-8000-exec-4] [ERROR] [org.candlepin.subscriptions.exception.mapper.BaseExceptionMapper] self- SUBSCRIPTIONS1000: An internal server error has occurred. Check the server logs for further details. - Duplicate key 12501973 (attempted merging values Subscription(subscriptionId=12501973, subscriptionNumber=12502130, …
```
> SWATCH-1356: Use subscription compound ID as map key in SubscriptionSyncController

- src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
Jira issue: [SWATCH-1363](https://issues.redhat.com/browse/SWATCH-1363)
Lazy loaded fields causing initialization error when called without a transaction.
Run following curl twice and both requests should be successful:
```
type=exec \
mbean='org.candlepin.subscriptions.product:name=offeringJmxBean,type=OfferingJmxBean' \
operation='syncOffering(java.lang.String)' \
arguments:='["RH00003"]'
```
> swatch-1363: offering hibernate initialization error fix

- src/main/resources/liquibase/202306201611-add-subscription-id-index-for-measurements.xml
- src/main/resources/liquibase/changelog.xml
This is to improve performance of query when we do GET /subscriptions/products/{product_id}
Jira issue: [SWATCH-1364](https://issues.redhat.com/browse/SWATCH-1364)
1.Get three tables(subscription, subscription_measurements, subscription_product_ids) from stage and import to local db in the same order:
- For subscription:
`GABI_URL=https://gabi-subscription-watch-stage.apps.crcs02ue1.urby.p1.openshiftapps.com OCP_CONSOLE_TOKEN=$(oc whoami -t) gabitabi -q "SELECT * from subscription;" --sep "," -o "subscription_full_data.csv"`
- For subscription_measurements:
`GABI_URL=https://gabi-subscription-watch-stage.apps.crcs02ue1.urby.p1.openshiftapps.com OCP_CONSOLE_TOKEN=$(oc whoami -t) gabitabi -q "SELECT * from subscription_measurements;" --sep "," -o "subscription_measurements_full_data.csv"`
- …
> SWATCH-1364 Add subscription_id index to subscription_measurements

- src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
- src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
Jira issue: [SWATCH-865](https://issues.redhat.com/browse/SWATCH-865)
Implement instances guest API to retrieve a hypervisor's guest instances by the hypervisor's instance_id.
1.Insert mock hypervisor and guest instances: 
`bin/insert-mock-hosts  --num-hypervisors 1   --num-guests 1   --org org123`
1. Find the instance_id of created hypervisor:
```
select instance_id from hosts where org_id='org123' and is_hypervisor=true;
EOF
```
1. Run following curl(replacing with generated instance_id from previous step) and should retrieve guest instance:
```
curl -X 'GET' \
'http://localhost:8000/api/rhsm-subscriptions/v1/instances/{hypervisor_instance_id}/guests' \
-H 'x-rh-identity: …
```
> SWATCH-865: Implement instances guest api 

- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/main/java/org/candlepin/subscriptions/tally/billing/RemittanceController.java
- src/main/java/org/candlepin/subscriptions/tally/billing/RemittanceSyncAlignmentException.java
- src/test/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/RemittanceControllerTest.java
- src/test/java/org/candlepin/subscriptions/util/ApplicationClockTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntityPK.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/RemittanceSummaryProjection.java
- swatch-core/src/main/java/org/candlepin/subscriptions/util/ApplicationClock.java
Jira issue: [SWATCH-1298](https://issues.redhat.com/browse/SWATCH-1298)
The existing syncRemittance API has been updated to sync any remittance with a MONTHLY granularity into a set of corresponding HOURLY and DAILY remittance records.
**!!! THIS SHOULD BE RUN IMMEDIATELY AFTER WE DEPLOY TO STAGE/PROD and ideally when the hourly tally has been completed !!!**
This API is intended to be used post-deployment to sync any existing remittance date now that the schema has been changed.
The goal is to break each MONTHLY remittance record down into a set of HOURLY and DAILY remittance records, which yeild the same total remitted pending value when each are summed. This is achieved by fetching the applicable HOURLY tally snapshots for a given MONTHLY remittance record, and running them through the …
> SWATCH-1298: Add post-deployment API support to sync hourly remittance

- deploy/stage-internal-test-job.yaml
- pr_check.sh
Jira issue: [SWATCH-1107](https://issues.redhat.com/browse/SWATCH-1107)
- As per https://gitlab.cee.redhat.com/insights-qe/iqe-core/-/merge_requests/1524 change, IQE_RP_ARGS is boolean value  instead of string. 
- Also making IQE_PARALLEL_ENABLED as false as currently we try to find if any test exists that can run in parallel even if we do not have any test running in parallel on pr_check. This will save around 1 min on every PR.
> SWATCH-1107 - IQE_RP_ARGS is boolean value now

- src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
- src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
Jira issue: [SWATCH-1399](https://issues.redhat.com/browse/SWATCH-1399)
Description
===========
Before this change, the logic was summing rounded values, which gave inaccurate numbers for monthly totals.
Testing
=======
Setup
-----
Insert some test data - 6 data points having 2.2 as the value:
```shell
DO $$
DECLARE id uuid;
BEGIN
FOR i IN 0..5 LOOP
id = gen_random_uuid();
insert into tally_snapshots(id, product_id, account_number, granularity, org_id, snapshot_date, unit_of_measure, sla)
values (id, 'OpenShift-metrics', 'account123', 'DAILY', 'org123',
'2023-06-01T00:00Z'::timestamptz + make_interval(days=>i), null, '_ANY');
insert into tally_measurements(snapshot_id, measurement_type, uom, value)
values (id, 'TOTAL', …
```
> SWATCH-1399: Round monthlyTotals after summation

- src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
- src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionPruneController.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/main/resources/liquibase/202306151541-add-sku-foreign-key-to-subscription.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
- src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionPruneControllerTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerOnDemandTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractOfferingMapper.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/OfferingEntity.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/OfferingRepository.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ServiceLevel.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/StringValueEnum.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionEntity.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/Usage.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractMapperTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SpringDataUtil.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
Adding the FK relationship allows us to remove a cross join that we needed to perform between the offering and subscription tables that had poor performance compared to an inner join.
Also set orphan-removal true on relationship between Subscription and SubscriptionMeasurement.
Jira issue: [SWATCH-1365](https://issues.redhat.com/browse/SWATCH-1365)
1. Save the following as `manualJoin.patch`
```patch
diff --git a/src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java b/src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java
index e624fb98..c47b29d2 100644
--- a/src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java
+++ b/src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepos …
```
> SWATCH-1365: Add FK relationship between Offering and Subscription

- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
Jira issue: [SWATCH-1411](https://issues.redhat.com/browse/SWATCH-1411)
Description
===========
Our JPQL for fetching existing host records has an order by that uses a clause:
```sql
order by
coalesce(h.hypervisorUuid, h.subscriptionManagerId),
h.hypervisorUuid,
h.inventoryId
```
Due to previous bugs, sometimes there are system multiple system records for the same inventory ID. Additionally, the query joins `hosts` with `host_tally_buckets`. Because the `order by` clause does not include a swatch-specific identifier, the rows returned for duplicate system records can be interleaved. This causes some unintuitive behavior. For example, Hibernate builds the buckets collection using contiguous records, and when the interleaving of two swatch systems' data happens, it creates a collection of …
> SWATCH-1411: Fix constraint violation in host_tally_buckets

- src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
Jira issue: [SWATCH-1423](https://issues.redhat.com/browse/SWATCH-1423)
Description
===========
Using specifications generates JPQL, and when using JPQL with collections, in order to eagerly fetch an association, there are three options:
1) Do nothing, and let Hibernate fetch collection per-entity (N+1 queries risk). 2) Add an explicit fetch join to the JPQL.
3) Make the association lazy (appropriate if the association doesn't actually need to be read).
I changed the specification building to make `Subscription.offering` always fetch joined, and I changed `Subscription.subscriptionProductIds` to be lazy fetched, as its not actually referenced in code paths having issues currently.
Testing
=======
Setup
-----
Set in config/application.properties:
```
logging.level.org.hibernate.SQL=DEBUG …
```
> SWATCH-1423: Avoid n+1 issues in subscription queries

- src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/main/resources/liquibase/202306291611-add-extra-index-for-product-ids.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
Jira issue: [SWATCH-1424](https://issues.redhat.com/browse/SWATCH-1424)
Join fetch the offering with the subscription.  We invariably need both.  Also eliminate usage of subscription_product_ids in `equals` on Subscription.  It's not useful and it will end up fetching a lazy-loaded association.
Download [perf.txt](https://github.com/RedHatInsights/rhsm-subscriptions/files/11910213/perf.txt).  I had to name it `.txt` because GitHub says it accepts `.patch` but then it doesn't when you try to upload one.
1. `git checkout main && patch -p1 < perf.txt`
1. `/gradlew :test -i --tests=Swatch1424OfferingRepositoryPerformanceTest.testFindByOfferingSku`
1. Observe the result is
```sql
Hibernate: 
select
subscripti0_.start_date as start_da1_12_,
subscripti0_.subscription_id as subscrip2_12_, …
```
> SWATCH-1424: Improve offering/subscription relationship performance

- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
When processing BillableUsage for a contract enabled product
with an unsupported billing provider, return null usage so that
the process will not be retried and will fail gracefully.
Clean the database and set up data
```
truncate  table events;
truncate table hosts cascade;                                                                                                                                                                 truncate table tally_snapshots cascade;                                                                                                                                                       truncate table billable_usage_remittance;
INSERT INTO public.events VALUES ('1464d3e9-2cb7-44c6-b0b6-8bef0ecb57d8', …
```
> Return null usage when ISE occurs gathering contract

- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/model/Subscription.java
- swatch-product-configuration/src/main/resources/OpenShift/OpenShift-dedicated-metrics.yaml
- swatch-product-configuration/src/main/resources/OpenShift/OpenShift-metrics.yaml
- swatch-product-configuration/src/main/resources/OpenShift/basilisk.yaml
- swatch-product-configuration/src/main/resources/OpenShift/rhacs.yaml
- swatch-product-configuration/src/main/resources/OpenShift/rhods.yaml
- swatch-product-configuration/src/main/resources/OpenShift/rhosak.yaml
- swatch-product-configuration/src/main/resources/OpenShift/rosa.yaml
Adding serviceType values from tag_profile.yaml to help with transition between tag profile and the subscription config registry
> Add serviceType to swatch-product-configuration files

- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/RemittanceControllerTest.java
Jira issue: [SWATCH-928](https://issues.redhat.com/browse/SWATCH-928)
Error was occurring on retally where hourly remittances were not being updated.
1. Insert test data:
```
INSERT INTO public.account_config VALUES ('7147504', 'API', '2023-06-30 11:51:29.323066+00', '2023-06-30 14:05:38.597068+00', '14541308');
INSERT INTO public.contracts VALUES ('b3a5e8b7-6260-48f4-a9eb-63a584763ce9', '12914277', '2023-06-01 18:20:07.717275+00', '2023-06-01 18:20:07.717275+00', NULL, '14541308', 'MW02393', 'aws', 'aws123', 'rosa', 'bcwuzc8ww10vvxfair55mliy8');
INSERT INTO public.contract_metrics VALUES ('b3a5e8b7-6260-48f4-a9eb-63a584763ce9', 'control_plane', 10);
INSERT INTO public.contract_metrics VALUES ('b3a5e8b7-6260-48f4-a9eb-63a584763ce9', 'four_vcpu_hour', 10);
INSERT INTO public.events VALUES …
```
> swatch-928: update existing records if retallying

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/test/java/org/candlepin/subscriptions/db/OfferingRepositoryCachingTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
- swatch-core/build.gradle
- swatch-core/src/main/java/org/candlepin/subscriptions/db/OfferingCacheProperties.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/OfferingRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/RhsmSubscriptionsDataSourceConfiguration.java
- swatch-core/src/main/resources/swatch-core/application.yaml
Jira issue: [SWATCH-1427](https://issues.redhat.com/browse/SWATCH-1427)
For every subscription during a subscription sync, we were making a call to OfferingRepository.existsById just to see if the subscription exists.  This is a lot of work that we don't need to perform over and over again.  I've added a simple in-memory cache to store the SKUs for 30 minutes.
Testing is covered by the unit tests.
> SWATCH-1427: Address excess calls to OfferingRepository.existsById with caching

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
- src/test/java/org/candlepin/subscriptions/db/EventRecordRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/metering/MeteringEventFactoryTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java
Jira issue: [SWATCH-1373](https://issues.redhat.com/browse/SWATCH-1373)
1. To run locally prometheus by pointing to stage follow the steps in: [Connecting  Observatorium to fetch Prometheus ](https://docs.engineering.redhat.com/display/ENT/Connecting+to+Observatorium+to+Fetch+Prometheus+Metrics)
- Copy CLIENT_SECRET and paste it in a file `token-refresher`
- Run: `podman run --name=telemeter-stage --rm -ti -p 8082:8080     quay.io/observatorium/token-refresher:master-2021-02-05-5da9663     --oidc.client-secret=$(cat ~/Downloads/token-refresher)     --oidc.client-id=observatorium-subwatch-staging     --oidc.issuer-url=https://sso.redhat.com/auth/realms/redhat-external     --url=https://observatorium.api.stage.openshift.com`
- Then in separate terminal pointing to the prom_url in the doc …
> SWATCH-1373 Support event lookup by both UOM and metricID

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/config/PrometheusServiceConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/billing/ServiceInstanceMessageConsumer.java
- src/main/resources/application-worker.yaml
- src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/EventRecordConverter.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/TaskQueueProperties.java
- swatch-tally/deploy/clowdapp.yaml
Jira issue: [SWATCH-598](https://issues.redhat.com/browse/SWATCH-598)
- This is an implementation of batch Kafka listener. swatch-tally listens on `platform.rhsm-subscriptions.service-instance-ingress` for event messages, and invokes EventController.saveAll() on them. If the json object is in bad format then we skip and log it as warning and process rest of the event messages in the batch. 
1. Clean up the Events table.
2. Execute the below respective payload values mentioned in each step so that it forms a batch and then run the application `DEV_MODE=true ./gradlew clean :bootRun `
3. Use the Big data Tools of Intellij as producer to test the consumer topic `platform.rhsm-subscriptions.service-instance-ingress`. Payloads are as below make sure to check each Test step on which payload to …
> SWATCH-598 Add worker for event messages to swatch tally

- src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
- src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java
Jira issue: [SWATCH-1500](https://issues.redhat.com/browse/SWATCH-1500)
Description
===========
There were two inconsistencies causing errors when reconciling HBI system data with swatch.
1. When a host has hypervisor UUID information from both the customer portal and from Satellite, swatch prefers the Satellite-derived reported hypervisor. I updated the sorting accordingly.
2. SortKey comparator was implemented as null-first, and should have been nulls-last instead to be consistent with postgresql.
Testing
=======
See private comment in the Jira issue for repro/testing instructions.
> SWATCH-1500: Fix inconsistencies with hypervisor UUID ordering

- src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
- src/main/java/org/candlepin/subscriptions/tally/filler/TallyReportDataPointAdapter.java
- src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
- src/test/java/org/candlepin/subscriptions/tally/filler/TallyReportDataPointAdapterTest.java
Jira issue: [SWATCH-1464](https://issues.redhat.com/browse/SWATCH-1464)
Tally ROSA API Instances and Cores parameters are not summed when the current day is without usage.
1. Insert events into db:
```
INSERT INTO public.events VALUES ('66d3b513-ff98-4ca2-a8e0-6220d587e481', 'account123', '2023-06-19 05:00:00+00', '{"sla": "Premium", "role": "moa-hostedcontrolplane", "org_id": "org123", "event_id": "66d3b513-ff98-4ca2-a8e0-6220d587e481", "timestamp": "2023-03-14T05:00:00Z", "event_type": "snapshot_redhat.com:rosa:cpu_hour", "expiration": "2024-03-14T06:00:00Z", "instance_id": "test02", "display_name": "test02", "event_source": "prometheus", "measurements": [{"uom": "Cores", "value": 78.43902161885251}], "service_type": "rosa Instance", "account_number": "account123", "billing_provider": …
```
> SWATCH-1464: Transform to running total format after filling in gap data

- src/main/java/org/candlepin/subscriptions/tally/filler/TallyReportDataPointAdapter.java
- src/test/java/org/candlepin/subscriptions/tally/filler/TallyReportDataPointAdapterTest.java
This patch guards against null TallyReportDataPoints in the TallyReportDataPointAdapter and against TallyReportDataPoints that have a value field of null.
We actually had a test for this but the flag to do running totals was accidentally set to false.
Jira issue: [SWATCH-1518](https://issues.redhat.com/browse/SWATCH-1518)
Calls to
```
api/rhsm-subscriptions/v1/tally/products/rosa/Cores?endi[…]&use_running_totals_format=true&billing_category=prepaid
```
and similar are throwing `NullPointerExceptions` because the value of `previous` parameter used in the `org.candlepin.subscriptions.tally.filler.TallyReportDataPointAdapter#createDefaultItem` method are null.  We had a check for this but the check was actually testing that the `previous.getValue()` call wasn't null instead of checking that …
> SWATCH-1518: Guard against a null value when calculating running totals

- src/main/resources/liquibase/202305251412-drop-subscription-capacity-table.xml
- src/main/resources/liquibase/202307131511-drop-trigger-on-subscription.xml
- src/main/resources/liquibase/changelog.xml
Jira issue: [SWATCH-1517](https://issues.redhat.com/browse/SWATCH-1517)
During the first phase of the migration to the subscription_measurements table we had to migrate the has_unlimited_usage column from the subscription_measurements table to the subscriptions table.  As part of this migration, we added a trigger to the subscription_measurements table so that subsequent changes to its has_unlimited_usage column would be reflected in the subscription table.
We then added a foreign key relationship between the offering and subscriptions table (SWATCH-1365).  Part of that effort moved the has_unlimited_usage column from the subscriptions table to the offering table.  In that card we dropped the has_unlimited_usage column off subscription entirely since that column is also on the offering …
> SWATCH-1517: Remove erroneous trigger from subscription_capacity table

- CONTRIBUTING.md
- swatch-product-configuration/build.gradle
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/exception/ConfigResourcesLoadingException.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Defaults.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Fingerprint.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Metric.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Subscription.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionRegistry.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift-dedicated-metrics.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift-metrics.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift_Container_Platform.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/basilisk.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhacs.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhods.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhosak.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_ARM.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_IBM_Power.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_IBM_z.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/Satellite_Capsule.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/Satellite_Server.yaml
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionRegistryTest.java
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionTest.java
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/VariantTest.java
Jira issue: [SWATCH-1230](https://issues.redhat.com/browse/SWATCH-1230)
Very important note: The term "Subscription" in the context of this PR (and swatch-product-configuration module in general) is NOT the same as the term "subscription" in swatch-contracts or swatch-subscription-sync.  The terms in this library mirror terms defined by the product management team.  Please see the doc attached to the epic for this card for more information.  There's also short explanations at the top of the java classes.
Created a List<Subscription> that is populated from the yaml config files, provide some common lookup methods, and ensure that Subscriptions can be looked up from other swatch modules.  We only want to read from the disk to populate this list if we haven't done so already.
Moved "POJO" …
> SWATCH-1230: Implement swatch-product-configuration lookup methods

- src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
- src/main/resources/liquibase/202307171013-add-indexes-for-tally-instance-view-queries.xml
- src/main/resources/liquibase/changelog.xml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
Jira issue: [SWATCH-1465](https://issues.redhat.com/browse/SWATCH-1465)
Instance API queries are taking over 1s frequently in stage and prod. This PR is to improve those query times with better indexing.
Was not able to reproduce the very slow queries locally but these before and after execution plans show that there should be improvements since the parallel seq scan on host_tally_buckets (slowest portion previously) is now an index scan. Query times did improve locally as well but never showed above 500ms:
Before: https://explain.dalibo.com/plan/7dfg3894dage6h1g
After: https://explain.dalibo.com/plan/7a94e9a97e36c7e1
> SWATCH-1465: query optimizations for tally_instance_view

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
Jira issue: [SWATCH-1511](https://issues.redhat.com/browse/SWATCH-1511)
Description
===========
We were modifying the subscription entity after a call to `SubscriptionRepository.save(...)`. In some cases, this is fine, as hibernate will reconcile any changes to managed entities. However, for some use cases, the reference passed to Hibernate itself does not become managed, but instead Hibernate will create a new instance and return it. For this reason, it is necessary to either:
1. Use the return value of `Repository.save(...)` for any further modifications.
2. Call `Repository.save(...)` at the end.
I'm choosing to change the ordering, because that is easier to remember, and behaves consistently.
Note: I noticed other inefficiencies, namely that we fetch only the active subscriptions to …
> SWATCH-1511: Fix bug where subscriptions persisted without capacity

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
Jira issue: [SWATCH-1511](https://issues.redhat.com/browse/SWATCH-1511)
Description
===========
We were modifying the subscription entity after a call to `SubscriptionRepository.save(...)`. In some cases, this is fine, as hibernate will reconcile any changes to managed entities. However, for some use cases, the reference passed to Hibernate itself does not become managed, but instead Hibernate will create a new instance and return it. For this reason, it is necessary to either:
1. Use the return value of `Repository.save(...)` for any further modifications.
2. Call `Repository.save(...)` at the end.
I'm choosing to change the ordering, because that is easier to remember, and behaves consistently.
Note: I noticed other inefficiencies, namely that we fetch only the active subscriptions to …
> [HOTFIX] SWATCH-1511: Fix bug where subscriptions persisted without capacity

- src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
- src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
Jira issue: [SWATCH-1530](https://issues.redhat.com/browse/SWATCH-1530)
Description
===========
Bug was caused by a small logic error. When a measurement was being processed, if there was no change, the code attempted to make a new (dupe) measurement and add it to the subscription.
Testing
=======
Steps
-----
Repeat for both `main` and this branch.
1. Clear subscription tables (make a backup if desired):
```shell
truncate table subscription cascade
EOF
```
2. Run the service:
```shell
OFFERING_USE_STUB=true SUBSCRIPTION_USE_STUB=true DEV_MODE=true ./gradlew :bootRun
```
3. Sync an org:
```shell
http PUT :8000/api/rhsm-subscriptions/v1/internal/subscriptions/sync/org/org123 \
x-rh-swatch-psk:placeholder
```
4. Now force a …
> SWATCH-1530: Fix EntityExistsException w capacity reconciliation

- src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
- src/test/java/org/candlepin/subscriptions/metering/MeteringEventFactoryTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
Jira issue: [SWATCH-1374](https://issues.redhat.com/browse/SWATCH-1374)
This code will now create and update Events with the new event_type: snapshot_$productId_$uom. This PR also takes care of the data json object in Events table. Please check the test steps with all the details.
1. To run locally prometheus by pointing to stage follow the steps in: [Connecting  Observatorium to fetch Prometheus ](https://docs.engineering.redhat.com/display/ENT/Connecting+to+Observatorium+to+Fetch+Prometheus+Metrics)
- Copy CLIENT_SECRET and paste it in a file `token-refresher`
- Run: `podman run --name=telemeter-stage --rm -ti -p 8082:8080     quay.io/observatorium/token-refresher:master-2021-02-05-5da9663     --oidc.client-secret=$(cat ~/Downloads/token-refresher) …
> SWATCH-1374 Produce events using UOM-derived eventType

- swatch-system-conduit/deploy/clowdapp.yaml
Jira issue: [SWATCH-1538](https://issues.redhat.com/browse/SWATCH-1538)
Description
===========
We're hitting 403s due to anti-csrf code. Similar to #2059. Probably happening now because of JMX removal.
Testing
=======
1. Deploy:
```shell
./gradlew swatch-system-conduit:bootRun
```
2. Simulate the command used by the job:
```shell
export SWATCH_SELF_PSK=placeholder
/usr/bin/curl --fail -H "x-rh-swatch-psk: ${SWATCH_SELF_PSK}" -X POST "http://localhost:8000/api/rhsm-subscriptions/v1/internal/rpc/syncAllOrgs"
```
(see failure w/ 403)
3. Try the updated command:
```shell
export SWATCH_SELF_PSK=placeholder
/usr/bin/curl --fail -H "Origin: https://console.redhat.com" -H "x-rh-swatch-psk: ${SWATCH_SELF_PSK}" -X POST "http://localhost:8000/api/rhsm-subscriptions/v1/internal/rpc/syncAllOrgs"
``` …
> SWATCH-1538: Add Origin header to conduit cron command

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorker.java
- src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/BillingProvider.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ServiceLevel.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/Usage.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillingProvider.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/ServiceLevel.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Usage.java
Jira issue: [SWATCH-1525](https://issues.redhat.com/browse/SWATCH-1525)
The following changes to optimize subscription syncing:
* Fix incorrect equals method in `SubscriptionCompoundId`
* Consolidate subscription syncing methods (there were two with slightly different implementations).
* Refactor measurement and product ID reconciliation so that previously implemented optimizations are used (namely doing nothing if the swatch data is up-to-date).
* Allow subs without end date to be synced (we expect some PAYG subs to not have an end date).
* Fix inconsistent DB <-> enum mappings, this was causing equality checks to fail, causing extra unnecessary work.
* Fetch associations upfront to avoid n+1 queries during org sub sync.
Some additional commentary in code comments and commit messages.
1. …
> SWATCH-1525: Optimize subscription syncing

- src/test/java/org/candlepin/subscriptions/metering/RhacsTagProfileTest.java
- src/test/java/org/candlepin/subscriptions/metering/RhosakTagProfileTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
- src/test/resources/test_tag_profile.yaml
- swatch-core/src/main/resources/tag_profile.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift-dedicated-metrics.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift-metrics.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/basilisk.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhacs.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhods.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhosak.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Jira issue: [SWATCH-1375](https://issues.redhat.com/browse/SWATCH-1375)
SWATCH-1375 Unify the values of metricId and UOM in tag profile/configuration
There are no testing steps since the goal is to update metricId with uom values. IMO as long as the unit tests passes I assume it should be good.
> SWATCH-1375 Unify the values of metricId and UOM 

- clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/CapacityApiFactory.java
- clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/IdentityHeaderApiClient.java
- clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/IdentityHeaderProvider.java
- src/main/java/org/candlepin/subscriptions/resource/ApiConfiguration.java
- src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
- src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
- src/main/resources/application-api.yaml
- src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java
Jira issue: [SWATCH-1509](https://issues.redhat.com/browse/SWATCH-1509)
When the Tally API generates a tally report with a billing category, capacity is applied to the running total calculations as they are calculated.
The following calculations are applied for the following billing categories:
**PREPAID:** max(running_usage_total_for_date - capacity_for_date, 0)
**ON-DEMAND:** min(running_usage_total_for_date, capacity)
**_NOTE: Testing steps has an example of how this is applied. See below._**
The tally report API now requires use_running_totals_format = true when a billing_category is specified.
When a request is made for a tally report with a billing category, a Capacity client is used to pull back the capacity report for the product/metric, which is then applied during the running …
> SWATCH-1509 Apply capacity to tally report running totals when billing category specified

- src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
- src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
Jira issue: [SWATCH-1047](https://issues.redhat.com/browse/SWATCH-1047)
Min cores/sockets was always being passed to the query as 0,
resulting in the same instance results no matter if the UOM was
sockets or cores.
This patch applies logic from the old API to toggle the min value
based on whether the uom is sockets or cores.
Drop the database
```
dropdb -U rhsm-subscriptions rhsm-subscriptions && createdb -U rhsm-subscriptions rhsm-subscriptions
```
Load the database from the attached test data file: [bug_data_dump_full.txt](https://github.com/RedHatInsights/rhsm-subscriptions/files/11971683/bug_data_dump_full.txt)
```
psql -U rhsm-subscriptions rhsm-subscriptions < bug_data_dump_full.txt
```
Deploy the app from the main branch.
```
```
Opt in the test …
> SWATCH-1047 Properly filter by cores/sockets in instance API

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
When there are multiple subscriptions with the same subscription id & start date, the collecting to map throws a Collectors.duplicateKeyException exception.  This merge function will say "take the first one".
1.
1.
1.
1.
1.
1.
> Add a merge function to Collectors.toMap

- bin/GeneratingPrometheusMetricData.adoc
- bin/prometheus-mock-data.sh
- src/test/java/org/candlepin/subscriptions/metering/RhacsTagProfileTest.java
- src/test/java/org/candlepin/subscriptions/metering/RhosakTagProfileTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
- src/test/java/org/candlepin/subscriptions/registry/TagProfileTest.java
- src/test/resources/test_tag_profile.yaml
- swatch-core/src/main/resources/tag_profile.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift-dedicated-metrics.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift-metrics.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/basilisk.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhacs.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhosak.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Jira issue: [SWATCH-1397](https://issues.redhat.com/browse/SWATCH-1397)
Use the `ocm_subscriptions` prometheus metric as a meta data metric so that OCM can retire the legacy `subscription_labels`. 
This change will affect the prometheus queries for all metered products that utilize the subscription_labels metric. These include:
* OpenShift-metrics
* OpenShift-dedicated-metrics
* rhosak
* rhacs
* basilisk
* rosa
Verify that there are no more references to `subscription_labels` in our codebase.
```
git grep subscription_labels
```
Follow the steps in [bin/GeneratingPrometheusMetricData.adoc](https://github.com/RedHatInsights/rhsm-subscriptions/compare/mstead/SWATCH-1397-migrate-from-subscription-labels-to-ocm_subscriptions?expand=1#diff-56534a771a3af252fd27849f189d077fdc7438869b7fca807e0bfa8 …
> SWATCH-1397 Migrate from subscription_labels to ocm_subscriptions prometheus label

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/config/PrometheusServiceConfiguration.java
- src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
Jira issue: [SWATCH-1591](https://issues.redhat.com/browse/SWATCH-1591)
Opt-in when we receive an event.
**Note: Testing is same as in PR for SWATCH-598: https://github.com/RedHatInsights/rhsm-subscriptions/pull/2298**
1. DEV_MODE=true ./gradlew :bootRun
2. Produce Kafka event using Big Data Tool for :`platform.rhsm-subscriptions.service-instance-ingress`
`{"event_id": "06893602-d1f9-414d-8bf6-a90154e844be", "event_source": "cost-management", "event_type": "Snapshot", "account_number": "10001", "org_id": "1234567", "service_type": "RHEL System", "instance_id": "i-55555556", "timestamp": "2023-08-01T07:00:00Z", "expiration": "2023-08-01T08:00:00Z", "measurements": [{"value": "2", "uom": "vCPUs"}], "cloud_provider": "AWS", "hardware_type": "Cloud", "product_ids": ["479", "70"], "role": "Red …
> SWATCH-1591 swatch-tally opt-in on any incoming events' org IDs

- bin/prometheus-mock-data.sh
Currently whatever billing_provider you pass to bin/prometheus-mock-data.sh, metering events or instances api always consider it "red hat" default billing provider as it should be `billing_marketplace` in Prometheus/RHOBS.
**Before fix:**
export BILLING_PROVIDER=aws and run bin/prometheus-mock-data.sh script, verify billing_provider from events or tally instances.
```
{'id': '234e2e72-46b7-43e0-b3f0-c34fec4e5d13',
'instance_id': 'test01',
'display_name': 'test01',
'billing_provider': 'red hat',   <---------------------
'billing_account_id': 'mktp-123',
'measurements': [1216.0],
'last_seen': datetime.datetime(2023, 8, 3, 12, 0, tzinfo=tzlocal()),
'number_of_guests': 0,
'_labeled_measurements': {'Cores': 1216.0}}
```
**After fix:** 
```
{'id': '65bf4456-ff10-4df7-ab55-ca04b532b87b', …
```
> Fix billing marketplace mock

- src/main/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResource.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManager.java
- src/main/spec/internal-metering-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResourceTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManagerTest.java
Jira issue: [SWATCH-658](https://issues.redhat.com/browse/SWATCH-658)
From Internal metering API, Stop accepting accountNumber and orgId should be marked as required.
Prior to this PR, it was possible to leave both the accountNumber and orgID empty.  It would then try to find all events for the provided range.  However, that feature wasn't currently working and would later throw an exception for the missing orgId.  This PR makes orgId mandatory.
1. To run locally prometheus by pointing to stage follow the steps in: [Connecting  Observatorium to fetch Prometheus ](https://docs.engineering.redhat.com/display/ENT/Connecting+to+Observatorium+to+Fetch+Prometheus+Metrics)
* Copy CLIENT_SECRET and paste it in a file `token-refresher`
* Run: `podman run --name=telemeter-stage --rm -ti -p …
> SWATCH-658: Internal metering API should not support accountNumber.

- src/main/java/org/candlepin/subscriptions/inventory/db/InventoryRepository.java
- src/main/java/org/candlepin/subscriptions/subscription/CustomBatchIterator.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostTallyBucketRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
Jira issue: [SWATCH-1554](https://issues.redhat.com/browse/SWATCH-1554)
Old Flow:
- Create a List of all the Subscription dtos for an org from the Subscription Service
- Create a Map of all the Subscrpition entities for an org from the database
- Loop through the dtos, cross referencing the entities map.  Sync or delete corresponding Subscription entity.
New Flow:
- Create a Map of all the Subscription dtos for an org from the Subscription Service
- Stream Subscription entities from the database.  Added a @QueryHint to  `Stream<Subscription> findByOrgId(String orgId)` to fetch in batches.
- Loop over Stream<Subscription> in batches, allowing us to periodically flush `subscriptionRepository` and clear the entity manager to release already processed Subscription entities hanging out in …
> SWATCH-1554 Reduce subscription sync memory use

- bin/insert-mock-hosts
This is a fix for the insert-mock-hosts script to use the updated schema.
1. First change: The new host_id column must be populated.  And instance_id is now auto-generated.
1. HBI has a groups field that must be populated
1. Ensure you have the latest hbi schema
```
podman-compose down
podman-compose up -d 
```
1. Verify insert will do the insertion and commit
```
bin/insert-mock-hosts --num-aws=1
```
2. Verify can insert into hbi
```
bin/insert-mock-hosts --num-hypervisors=1 --num-guests=1 --hbi --org org123 --clear
```
> Fix errors in insert-mock-hosts

- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryServiceProperties.java
- swatch-system-conduit/src/main/resources/application.yaml
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java
Jira issue: JIRA ticket: https://issues.redhat.com/browse/SWATCH-38
Change the property `rhsm-conduit.inventory-service.staleHostOffsetInDays` which wrongly states it's in days when it's really in hours, to `rhsm-conduit.inventory-service.staleHostOffset` while now it accepts a duration (so users can use hours, days, minutes, ...). 
The test `testStaleTimestampUpdatedBasedOnSyncTimestampAndOffset` already covers this change. 
The system property has changed from `INVENTORY_STALE_HOST_OFFSET_HOURS` to `INVENTORY_STALE_HOST_OFFSET`. We can add a logic to make INVENTORY_STALE_HOST_OFFSET_HOURS backward compatible (see comments).
> SWATCH-38: Rename staleHostOffsetInDays to staleHostOffset

- src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
- src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
- src/main/resources/liquibase/202308151557-fix-subscription-measurement-metric-id-casing.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
Jira issue: [SWATCH-1507](https://issues.redhat.com/browse/SWATCH-1507)
Description
===========
When the capacity API is called for Sockets (e.g.
http://localhost:8000/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Sockets), the generated SQL includes a clause like `where metric_id=?` where the param `?` is populated as `Sockets`.
However, we are recording measurements as `SOCKETS`, so no subscriptions will ever match.
I also fixed a subsequent issue where subscription measurements attempted to lazy-load without an open transaction; instead I changed the repository method to eager fetch subscription measurements.
Testing
=======
Test first with the `main` branch and then with this branch.
1. Truncate subscription tables:
```shell
psql -h localhost -U rhsm-subscriptions …
```
> SWATCH-1507: Fix casing on subscription_measurements.metric_id

- bin/insert-mock-hosts
- src/main/resources/liquibase/202308210806-add-metric-id-instance-measurements.xml
- src/main/resources/liquibase/202308210906-drop-uom-column-instance-measurements.xml
- src/main/resources/liquibase/changelog.xml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/InstanceMonthlyTotalKey.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceViewKey.java
Jira issue: https://issues.redhat.com/browse/SWATCH-371
As a swatch developer, I want swatch to write metric_id to instance_measurements, so that I can remove UOM later on.
The solution renames the existing column "uom" to "metric_id", so the primary key and the existing index got updated as well. This is done for the table `instance_measurements` and the view `tally_instance_view`. 
Moreover, the solution creates a temporary computed column "uom" to take the data from "metric_id", so existing services will keep working as usual meanwhile the migration data takes effect.
The solution follows the same pattern as in https://github.com/RedHatInsights/rhsm-subscriptions/pull/2304. 
Setup
-----
1. Checkout `main`
2. Ensure that the DB schema is in place:
```shell
./gradlew :liquibaseUpdate
``` …
> SWATCH-371: Add metric_id to instance_measurements

- api/rhsm-subscriptions-api-spec.yaml
- src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
- src/main/resources/liquibase/202308211518-rename-rhel-product-ids.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/capacity/CapacityProductExtractorTest.java
- src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
- src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java
- src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
- src/test/java/org/candlepin/subscriptions/resource/SubscriptionResourceTest.java
- src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86.yaml
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/VariantTest.java
Jira issue: [SWATCH-1605](https://issues.redhat.com/browse/SWATCH-1605)
Change variant tag name from `RHEL Server` to `RHEL for x86`
Remove `RHEL`, `RHEL Server`, `RHEL Desktop`, and `Satellite` as ProductId enum options.  These correspond to variant tags that were dropped per PM input during TagProfile to swatch-product-configurtion migration.
Keeping `RHEL Compute Node` and `RHEL Workstation` in the api spec, so users can still retrieve data for those Product Ids, although data with these ProductIds will not be shown in the UI.
Update tally records that were assigned `RHEL Server` to `RHEL for x86`.  To prevent duplicates, retire records that were already assigned `RHEL for x86`. This is done with liquibase by:
Update the product_id values in tally_snapshots and host_tally_buckets …
> SWATCH-1605: Change variant tag name from "RHEL Server" to "RHEL for x86"

- build.gradle
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusQueryWiremockExtension.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusServiceTest.java
Instead of mocking the Prometheus service in the following tests:
- PrometheusMeteringControllerTest
- PrometheusServiceTest
We can configure Wiremock to mock the Prometheus Query API.  The main issue that these changes address is that at the moment, the Prometheus API, the API client (these two are auto-generated by OpenAPI), and the Prometheus service are tightly coupled with each other, so changing one, it would require changing the rest. Moreover, the tests will be more readable and also we can improve them to also mock large content of data. 
Note that we can only use this approach in tests that also use the SpringBootTest extension.
This is related to https://issues.redhat.com/browse/SWATCH-1574 where it was hard to try to test a scenario with a large amount of data in the current …
> Replace tests needing prometheus service to integration tests

- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusQueryWiremockExtension.java
Without this, sometimes the stub fails to match when it should, e.g.
```
Stub:   2023-08-24T12:26:41.963482680Z
Actual: 2023-08-24T12:26:41.96348268Z
```
> Fix time format in prometheus wiremock stub

- buildSrc/src/main/groovy/swatch.spring-boot-conventions.gradle
- buildSrc/src/main/groovy/swatch.spring-boot-dependencies-conventions.gradle
- buildSrc/src/main/groovy/swatch.spring-boot-rest-client-conventions.gradle
- clients-core/build.gradle
- swatch-core/build.gradle
There's some sort of bug where dependencies managed by the `io.spring.dependency-management` gradle plugin don't respect exclusions. Work around by moving select dependencies out of the dependency management section.
> Fix deps so jandex 2.x exclusion works everywhere

- src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
- src/main/java/org/candlepin/subscriptions/capacity/admin/MetricMapper.java
- src/main/java/org/candlepin/subscriptions/capacity/admin/TagMetricMapper.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/main/spec/internal-subscriptions-sync-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformerTest.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
Jira issue: [SWATCH-1237](https://issues.redhat.com/browse/SWATCH-1237)
Description
===========
Subscription syncing used tag profile for the following things:
* Log a warning if a PAYG sub is missing details
* Log a warning if attempting to terminate a PAYG sub more than an hour out
* Lookup the product names used for a PAYG sub lookup
* Provide a lookup for productIds/tags for a SKU.
* Provide a lookup for metrics for a productId/tag.
Testing
=======
```shell
DEVTEST_EVENT_EDITING_ENABLED=true \
SUBSCRIPTION_USE_STUB=true \
PRODUCT_USE_STUB=true \
```
2. Sync subscriptions:
```shell
http PUT :8000/api/rhsm-subscriptions/v1/internal/subscriptions/sync/org/123 \
Origin:console.redhat.com
```
3. …
> SWATCH-1237: Use swatch-product-configuration in subscription syncing

- init_dbs.sh
This is required to load scripts via pqsl using the COPY command.
> Configure users as superusers

- src/main/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResource.java
- src/main/java/org/candlepin/subscriptions/metering/profile/OpenShiftWorkerProfile.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSource.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/config/PrometheusServiceConfiguration.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/promql/QueryBuilder.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/promql/QueryDescriptor.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManager.java
- src/main/java/org/candlepin/subscriptions/metering/task/MeteringTasksConfiguration.java
- src/main/resources/application-openshift-metering-worker.yaml
- src/main/resources/application.yaml
- src/test/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResourceTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSourceTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusServiceTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/QueryHelper.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/promql/QueryBuilderTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/task/PrometheusMetricsTaskManagerTest.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/basilisk.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhacs.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rhosak.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Jira issue: [SWATCH-1234](https://issues.redhat.com/browse/SWATCH-1234)
Refactor prometheus integration to use swatch-product-configuration
1. To run locally prometheus by pointing to stage follow the steps in: [Connecting  Observatorium to fetch Prometheus ](https://docs.engineering.redhat.com/display/ENT/Connecting+to+Observatorium+to+Fetch+Prometheus+Metrics)
- Copy CLIENT_SECRET and paste it in a file `token-refresher`
- Run: `podman run --name=telemeter-stage --rm -ti -p 8082:8080     quay.io/observatorium/token-refresher:master-2021-02-05-5da9663     --oidc.client-secret=$(cat ~/Downloads/token-refresher)     --oidc.client-id=observatorium-subwatch-staging     --oidc.issuer-url=https://sso.redhat.com/auth/realms/redhat-external …
> SWATCH-1234 Refactor prometheus integration to use swatch-product-configuration

- src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
- src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
- src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/VariantTest.java
Jira issue: [SWATCH-1241](https://issues.redhat.com/browse/SWATCH-1241)
Draft until https://github.com/RedHatInsights/rhsm-subscriptions/pull/2369 merged.
Remove deprecated tag_profile and use swatch-product-configuration instead in TallyResource.
1. Start app with : `DEV_MODE=true ./gradlew :bootRun`
1. Ensure account is opted in: 
```
curl -X 'PUT' \
'http://localhost:8000/api/rhsm-subscriptions/v1/opt-in' \
-H 'x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo='
```
1. Run curl with Daily granularity and no errrors should be returned:
```
curl -X 'GET' \
'http://localhost:8000/api/rhsm-subscriptions/v1/tally/products/RHEL%20 …
```
> SWATCH-1241 remove tag profile from tally resource

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
Jira issue: [SWATCH-1571](https://issues.redhat.com/browse/SWATCH-1571)
Description
===========
Subscription syncing currently fetches information only from IT Subscription Service and IT Product Service. (It does not consult the partner subscription API). Contract capacities are recorded only the partner subscription API, so the view from IT Subscription Service is incomplete. This can cause a SaaS-contract subscription to be incorrectly modified during a subscription sync.
Note that the `Subscription.equals` method prevents update of a `Subscription` entity unless one of the following properties changes:
* `subscriptionNumber`
* `quantity`
* `startDate`
* `endDate`
* `billingProviderId`
* `billingAccountId`
* `accountNumber`
* `billingProvider`
Contract service does not record …
> SWATCH-1571: Skip syncing SaaS-contract subscriptions from IT Subscription Service

- clients/prometheus-client/prometheus-api-spec.yaml
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSource.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusService.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/config/PrometheusServiceConfiguration.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/model/QuerySummaryResult.java
- src/main/java/org/candlepin/subscriptions/prometheus/api/PrometheusStubLocator.java
- src/main/java/org/candlepin/subscriptions/prometheus/api/StubQueryRangeApi.java
- src/main/resources/prometheus-stub-data/success.json
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSourceTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusQueryWiremockExtension.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusServiceTest.java
- src/test/java/org/candlepin/subscriptions/prometheus/api/ApiProviderFactoryTest.java
- src/test/resources/__files/prometheus_small.json
Jira issue: [SWATCH-1574](https://issues.redhat.com/browse/SWATCH-1574)
When using a Prometheus dataset with up to 53760 metrics, we were holding up to 129 MB in memory. 
These changes use the Jackson streaming API to process the metrics individually, so it won't ever hold this amount of data. 
I made the following decisions:
- I used the Consumer Java API instead of a more complicated API like the Future API which would require creating threads that would lead to performance penalties.
- I didn't include the scenario to process a large dataset because the file size was too large (up to 20MB). 
- I didn't modify the generation of the Prometheus client API on purpose, because this must match with what the real Prometheus returns (speaking about the QueryResult generated class). Instead, I …
> SWATCH-1574: Use jackson streaming API to parse the response from prometheus

- src/main/resources/liquibase/changelog.xml
We hit issues trying to get this migration to run during production deploy.
> [HOTFIX] Disable RHEL {Server,for x86} migration

- src/main/java/org/candlepin/subscriptions/capacity/admin/UsageContextSubscriptionProvider.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
- src/test/java/org/candlepin/subscriptions/capacity/admin/UsageContextSubscriptionProviderTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
Jira issue: [SWATCH-1569](https://issues.redhat.com/browse/SWATCH-1569)
Removes logic to sync subscriptions when not found in the billing producers (aws and RH marketplace). 
1. Create subscriptions for testing:
```
cat <<EOF | psql -h localhost -U rhsm-subscriptions                                                                                                                                                INSERT INTO offering(
sku, product_name, product_family, sla, usage, description, has_unlimited_usage)
VALUES ('MW01882', 'OpenShift Streams for Apache Kafka', 'JBoss', 'Premium', 'Production', 'Red Hat OpenShift Streams for Apache Kafka (Hourly)', false);
INSERT INTO subscription (sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, account_number, …
```
> SWATCH-1569: Remove force sync logic from billing producers

- src/main/java/org/candlepin/subscriptions/tally/admin/HardwareMeasurementMigration.java
- src/main/resources/liquibase/202308231356-add-metric-id-tally-measurements.xml
- src/main/resources/liquibase/202308231456-drop-uom-column-tally-measurements.xml
- src/main/resources/liquibase/changelog.xml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyMeasurementKey.java
- swatch-producer-aws/README.adoc
Jira issue: [SWATCH-430](https://issues.redhat.com/browse/SWATCH-430)
As a swatch developer, I want swatch to write metric_id to instance_measurements, so that I can remove UOM later on.
The solution renames the existing column "uom" to "metric_id", so the primary key and the existing index got updated as well. 
Moreover, the solution creates a temporary computed column "uom" to take the data from "metric_id", so existing services will keep working as usual meanwhile the migration data takes effect.
The solution follows the same pattern as in https://github.com/RedHatInsights/rhsm-subscriptions/pull/2304.
1.- Start infrastructure: `podman-compose up`
2.- Ensure the database is migrated: `./gradlew :liquibaseUpdate`
3.- Ensure the apps start ok using: `./gradlew :bootRun`
4.- Check both …
> SWATCH-430: Add metric_id to tally_measurements

- build.gradle
- buildSrc/src/main/groovy/swatch.spring-boot-conventions.gradle
- buildSrc/src/main/groovy/swatch.spring-boot-dependencies-conventions.gradle
- buildSrc/src/main/groovy/swatch.spring-boot-rest-client-conventions.gradle
- dependencies.gradle
- swatch-common-config-workaround/build.gradle
- swatch-common-resteasy/build.gradle
- swatch-core/build.gradle
- swatch-product-configuration/build.gradle
- swatch-system-conduit/build.gradle
Having non-BOM entries in dependency management results in transitive dependency exclusions not working properly.  We achieve the intended effect of dependency management (uniform versions of a library across all sub-projects) with the dependencies.gradle file anyway.
Attn @kahowell
> Remove all non-BOM entries from dependency management

- Jenkinsfile
The idea is to register the users that more contribute to the project and not to ask "ok to verify?" to trigger the Jenkins job.
I also checked whether there was a way to check the user organization instead, but I could not find any way.
I took the list of users from the swatch-dev-team slack group and the ones with more contributions.
> [CI] Do not ask "ok to verify?" for some known users

- src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
- src/main/java/org/candlepin/subscriptions/tally/billing/ContractsClientProperties.java
- src/main/java/org/candlepin/subscriptions/tally/filler/ReportFillerFactory.java
- src/main/java/org/candlepin/subscriptions/tally/filler/UnroundedTallyReportDataPoint.java
- src/main/java/org/candlepin/subscriptions/tally/filler/UnroundedTallyReportDataPointAdapter.java
- src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
- src/test/java/org/candlepin/subscriptions/tally/filler/UnroundedTallyReportDataPointAdapterTest.java
Jira issue: [SWATCH-1462](https://issues.redhat.com/browse/SWATCH-1462)
1. Create a clean database
```shell
createdb -h localhost -U postgres -O rhsm-subscriptions swatch-1462
```
2.  Download [SWATCH-1462.zip](https://github.com/RedHatInsights/rhsm-subscriptions/files/12432199/SWATCH-1462.zip) and import it into your database
```shell
zcat SWATCH-1462.zip | psql -h localhost -U rhsm-subscriptions swatch-1462
```
1.  Deploy the `main` branch with 
```shell
DATABASE_DATABASE=swatch-1462 ./gradlew :bootRun
```
2.  I didn't export the `instance_monthly_total` records, but the underlying instances look like
```json
{"data": [
{
"id": "1dce12a3-369f-4b4b-aea6-afb119c4f57c",
"instance_id": "a7730436-5e1c-4122-ad93-a7316ab8fb46",
"display_name": …
```
> SWATCH-1462: Correct mismatch in monthly and running totals

- bin/metering-promql.py
Related: https://issues.redhat.com/browse/SWATCH-1606
I got tired of manually constructing the PromQL when I wanted to verify what swatch generates. This script doesn't do all that was detailed in SWATCH-1606, but is a good starting point.
So I wrote a small python script to consult config and output PromQL. It was also pretty easy to get it to output a link to the query results via Grafana's explore page.
See help text:
```
usage: metering-promql.py [-h] [--url URL] [--product PRODUCT] [--metric METRIC] [--org ORG]
Output PromQL for debugging
options:
-h, --help         show this help message and exit
--url URL          Output links with Grafana base url (e.g. https://grafana.example.com )
--product PRODUCT  Limit to a specific product (e.g. rosa)
--metric METRIC    Limit to a specific …
```
> Add script for debugging metering PromQL

- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataController.java
- src/main/spec/internal-tally-api-spec.yaml
Jira issue: [SWATCH-1621](https://issues.redhat.com/browse/SWATCH-1621)
If a bad billing provider (or any other invalid enumeration) got sent to POST `/internal/rpc/tally/event`, a jackson error would occur, resulting in application/server errors and a stacktrace in the logs.
We want to treat validation of the request body as a client error, and put a WARN in the logs instead - without the whole stacktrace spam.
Reproduce the exception & stack trace 
```
```
```
curl -X 'POST'   'http://localhost:8000/api/rhsm-subscriptions/v1/internal/rpc/tally/events' -H  'x-rh-swatch-psk:placeholder'   -H 'accept: application/json'   -H 'Content-Type: application/json'   -d '[{"event_id":"0998c49b-9552-463f-b363-0a4b046dd6e9","event_source":"prometheus","event_type":"sna …
```
> SWATCH-1621: Throw BadRequestException if error during request body validation

- src/main/resources/liquibase/changelog.xml
Jira issue: [SWATCH-1613](https://issues.redhat.com/browse/SWATCH-1613)
After https://issues.redhat.com/browse/SWATCH-371 is released, we need to fully drop the uom column from the instance measurements.
1.- Run the migration using: `./gradlew :liquibaseUpdate`. The column `uom` should have been dropped from the tables `instance_measurements` and `instance_monthly_totals`.
2.- Test the rollback by calling twice: `./gradlew :liquibaseRollbackCount -PliquibaseCommandValue=2`. The column `uom` should have been back to the tables `instance_measurements` and `instance_monthly_totals`.
> SWATCH-1613: Fully drop uom column from instance measurements table

- src/main/java/org/candlepin/subscriptions/tally/TallyTaskFactory.java
- src/test/java/org/candlepin/subscriptions/tally/tasks/TallyTaskFactoryTest.java
Jira issue: [SWATCH-665](https://issues.redhat.com/browse/SWATCH-665)
This is a part of post org-id clean up and  remove logic to check if a orgId exist in the tally task, as 'orgId' is expected to be given moving forward after the org-Id migration 
This is regression testing only, so only need to test that non of the process is affected by the removal.
> SWATCH-665:Remove Unneeded orgs check for TallyTaskFactory

- src/main/resources/liquibase/changelog.xml
Jira issue: [SWATCH-1657](https://issues.redhat.com/browse/SWATCH-1657)
After https://issues.redhat.com/browse/SWATCH-430 is released, we need to fully drop the uom column from the instance measurements.
1.- Run the migration using: `./gradlew :liquibaseUpdate`. The column `uom` should have been dropped from the table `tally_measurements`.
2.- Test the rollback by calling twice: `./gradlew :liquibaseRollbackCount -PliquibaseCommandValue=2`. The column `uom` should have been back to the table `tally_measurements`.
> SWATCH-1657: Fully drop uom column from tally measurements table

- swatch-tally/deploy/clowdapp.yaml
Also aliased "metric_id" to "uom" so that internal users of "uom" can continue to use it in the short term.
Try the query locally via psql
> Use explicit column names in floorist export

- src/main/java/org/candlepin/subscriptions/resteasy/ResteasyRequestObservationConvention.java
- src/main/java/org/candlepin/subscriptions/resteasy/ResteasyUriExtractionFilter.java
- src/test/java/org/candlepin/subscriptions/resteasy/HttpServerMetricsTest.java
Jira issue: [SWATCH-1651](https://issues.redhat.com/browse/SWATCH-1651)
Description
===========
Spring Boot 3 introduced drastic changes to how the metrics are constructed.
Two classes are now necessary to carry resteasy URIs into metrics:
1. ResteasyUriExtractionFilter - to extract the URI from resteasy
2. ResteasyRequestObservationConvention - to set the URI as the `uri` attribute.
ResteasyUriExtractionFilter was renamed from MicrometerUriHackFilter to better reflect its purpose.
Testing
=======
Setup
-----
```shell
```
2. Ensure opted in:
```shell
http PUT :8000/api/rhsm-subscriptions/v1/opt-in \
x-rh-identity:$(echo '{"identity":{"type":"User","internal":{"org_id":"org123"}}}' | base64 -w0)
```
Verification
------------
Hit an …
> SWATCH-1651: Populate uri label in Spring Boot 3 request metrics

- clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
Jira issue: [SWATCH-1652](https://issues.redhat.com/browse/SWATCH-1652)
Description
===========
This changes the value emitted for cloud_provider from "google" to "gcp" when processing GCP-hosted systems.
Testing
=======
Setup
-----
Deploy the service:
```shell
RHSM_USE_STUB=true ./gradlew swatch-system-conduit:bootRun
```
Verification
------------
Check the output of our debugging output to see what conduit sets for cloud provider for the mocked GCP system:
```shell
http :8000/api/rhsm-subscriptions/v1/internal/organizations/gcpOrg/inventory \
limit=100 \
Origin:console.redhat.com
```
Notice `"cloud_provider": "gcp"`
> SWATCH-1652: Conduit: Set cloud_provider: gcp for GCP systems

- api/rhsm-subscriptions-api-spec.yaml
- build.gradle
- src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
- src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
- src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
- src/main/java/org/candlepin/subscriptions/resource/SubscriptionResource.java
- src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
- src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
- src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java
- src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java
- src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
- src/test/java/org/candlepin/subscriptions/resource/SubscriptionResourceTest.java
- src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerOnDemandTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
- swatch-common-resteasy/build.gradle
- swatch-common-resteasy/src/main/java/com/redhat/swatch/common/resteasy/MetricIdParamConverterProvider.java
- swatch-common-resteasy/src/main/java/com/redhat/swatch/common/resteasy/ProductIdParamConverterProvider.java
- swatch-common-resteasy/src/main/resources/META-INF/services/jakarta.ws.rs.ext.Providers
- swatch-contracts/build.gradle
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/CapacityResource.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/MetricId.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/ProductId.java
Jira issue: [SWATCH-969](https://issues.redhat.com/browse/SWATCH-969)
Description
===========
Remove productId enum in favor of a class that validates against product-config (extremely similar
to #2464). I made these changes on top of that PR in order to avoid merge conflicts, so #2464 must
land first.
Testing
=======
Setup
-----
```shell
```
2. Ensure opted in:
```shell
http PUT :8000/api/rhsm-subscriptions/v1/opt-in \
x-rh-identity:$(echo '{"identity":{"type":"User","internal":{"org_id":"org123"}}}' | base64 -w0)
```
Verification - Happy Path
Try the following APIs, expecting successful responses...
capacity (deprecated):
```shell
http ':8000/api/rhsm-subscriptions/v1/capacity/products/RHEL for x86' \ …
```
> SWATCH-969: Replace ProductId enum with class that checks against product-config

- bin/insert-mock-hosts
- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
- src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/HardwareMeasurementType.java
Jira issue: [SWATCH-1653](https://issues.redhat.com/browse/SWATCH-1653)
Given a host in HBI with cloud_provider=gcp, after a tally for the org, the report for `category=cloud` should increase.
2.- Create hosts for orgId=16790890 in Insights database
```
./bin/insert-mock-hosts --num-gcp 1 --hbi --clear --org 16790890 --account account123
```
3.- createdb -h localhost -U postgres -O rhsm-subscriptions swatch-1653
4.- DEV_MODE=true SUBSCRIPTION_SYNC_ENABLED=true ENABLE_SYNCHRONOUS_OPERATIONS=true DATABASE_DATABASE=swatch-1653 ./gradlew :bootRun
5.- Perform tally snapshot:
```bash
http PUT ":8000/api/rhsm-subscriptions/v1/internal/rpc/tally/snapshots/16790890" \
Origin:console.redhat.com \
x-rh-swatch-synchronous-request:true \ …
```
> SWATCH-1653: Tally should categorise hosts coming from HBI with cloud provider "gcp" as CLOUD

- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/promql/QueryBuilder.java
- src/main/resources/application.yaml
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/PrometheusMetric.java
Jira issue: [SWATCH-1629](https://issues.redhat.com/browse/SWATCH-1629)
Currently, Rhods contains "addonSamples", but application.yaml does not have a template for it. Therefore, it reads everything by "default" using default query and filters it later in the code. 
Now, we have properly configured the "addonSamples" query profile that includes the resource_type and resource_name filters directly in the prometheus query. 
I've verified these changes via:
1.- Run the script:
```
bin/metering-promql.py --product rhods --url https://grafana.app-sre.devshift.net
```
2.- It will generate the following output:
```
Accounts: https://grafana.app-sre.devshift.net/explore?orgId=1&left=%7B%22queries%22%3A+%5B%7B%22refId%22%3A+%22A%22%2C+%22editorMode%22%3A+%22code%22%2C+%22expr%22%3A+%22group%28min_o …
```
> SWATCH-1629: Include addonSamples as a template for accountQueryTemplate

- src/main/resources/liquibase/202309111412-drop-subscription-capacity-table.xml
- src/main/resources/liquibase/changelog.xml
The subscription_capacity table was superseded several months ago by the subscription_measurements table.
Jira issue: [SWATCH-1332](https://issues.redhat.com/browse/SWATCH-1332)
Please also review https://github.com/RedHatInsights/rhsm-subscriptions-egress/pull/28 as the same time as this PR
Be forewarned, there's no rolling back from dropping a table.  If you want to test this on an alternate schema, you can copy your database with
```
createdb -h localhost -U postgres -O rhsm-subscriptions -T rhsm-subscriptions scratch
```
and then modify the `buildSrc/src/main/groovy/swatch.liquibase-conventions.gradle` file to point to `scratch` instead of `rhsm-subscription`.
1. `psql -h localhost -U rhsm-subscriptions scratch -c '\dt` will show the `subscription_capacity` table
1. `psql -h localhost …
> SWATCH-1332: Enable a liquibase script to drop the subscription_capacity table

- src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
- src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/InstanceMonthlyTotalKey.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyMeasurementKey.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/MetricId.java
Jira issue: [SWATCH-1704](https://issues.redhat.com/browse/SWATCH-1704)
Recent changes to replace UOM with MetricId caused an issue where new values in instance_measurements and tally_measurements were being saved in regular case instead of all upper cased. This PR sets them to all UpperCase again.
Follow steps outlined here: https://github.com/RedHatInsights/rhsm-subscriptions/pull/2311
If you run on main and then switch to this branch, the API call to get the data will not return values because the records will be incorrectly cased. After you switch to this branch and run steps again then you should get correct results.
> SWATCH-1704: Uppercase MetricId on tally_measurements and instance_measurements

- .github/workflows/pr.yaml
- Jenkinsfile
- build.gradle
- buildSrc/src/main/groovy/swatch.java-conventions.gradle
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/MeteringMetricsFromPrometheusToDatabaseIT.java
- src/test/java/org/candlepin/subscriptions/resteasy/HttpServerMetricsTest.java
- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- src/test/java/org/candlepin/subscriptions/test/BaseIT.java
- src/test/java/org/candlepin/subscriptions/test/SwatchPostgreSQLContainer.java
- swatch-core-test/src/main/resources/application-test-inventory.yaml
Jira issue: [SWATCH-1734](https://issues.redhat.com/browse/SWATCH-1734)
These changes add a `BaseIT` class that allows writing integration tests using Postgresql and Kafka. Moreover, it brings some other utilities and testing facilities like integration between Spring Boot Security Testing and Awailitily.
> SWATCH-1734: Support integration tests with Postgresql

- pr_check.sh
We were assigning IMAGE_TAG value to IQE_IBUTSU_SOURCE before it is defined. Thus, `bonfire deploy-iqe-cji` command was sending `--ibutsu-source rhsm-ephemeral-`. 
Before fix: 
`bonfire deploy-iqe-cji rhsm --marker ephemeral --filter ''\'''\''' --image-tag rhsm-subscriptions --requirements ''\'''\''' --requirements-priority ''\'''\''' --test-importance ''\'''\''' --plugins rhsm-subscriptions --env clowder_smoke --cji-name rhsm --parallel-enabled false --parallel-worker-count ''\'''\''' --rp-args true --ibutsu-source rhsm-ephemeral- --namespace ephemeral-z703g5`
After fix :
`bonfire deploy-iqe-cji rhsm --marker ephemeral --filter ''\'''\''' --image-tag rhsm-subscriptions --requirements ''\'''\''' --requirements-priority ''\'''\''' --test-importance ''\'''\''' --plugins rhsm-subscriptions …
> Fix IMAGE_TAG value in ibutsu source

- src/main/java/org/candlepin/subscriptions/resteasy/ResteasyConfiguration.java
- swatch-core/src/main/java/org/candlepin/subscriptions/exception/mapper/BadRequestExceptionMapper.java
- swatch-core/src/main/java/org/candlepin/subscriptions/resteasy/ResteasyProviderRegistrar.java
- swatch-core/src/main/resources/swatch-core/application.yaml
Jira issue: [SWATCH-1739](https://issues.redhat.com/browse/SWATCH-1739)
This PR fixes a few issues:
* The "open session in view" warning that Spring prints.
* The warnings about `@Provider`s being registered twice
* Some debug logging that slipped in
* A few comments and correction in semantics for the `BadRequestExceptionMapper`
There are two outstanding issues:
* `RESTEASY004687: Closing a class org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine$CleanupAction instance for you. Please close clients yourself.`  I have no idea what's causing this error.  It's not even getting logged in the main thread.  It's getting logged in a `Cleaner` thread.
My best guess is that when we create the various API clients for subscription service, user service, etc, the generated …
> SWATCH-1739: Fix startup errors

- src/test/java/org/candlepin/subscriptions/test/SwatchPostgreSQLContainer.java
Configure podman-docker and socket using:
```
sudo dnf install podman podman-docker
systemctl --user enable podman.socket --now
podman system service --time=0
```
Check podman socket is listening:
```
podman info | grep -A2 'remoteSocket' 
```
This command should print:
```
remoteSocket:
exists: true
path: /path/to/podman.sock
```
And configure testcontainers to connect to the podman socket:
``` 
export DOCKER_HOST=unix:///run/user/${UID}/podman/podman.sock
export TESTCONTAINERS_RYUK_DISABLED=true
``` 
And then run the tests using `./gradlew clean build`. Eventually, any of the integration tests that use SwatchPostgreSQLContainer will fail with `Broken pipe when creating container`.
> Workaround issue with testcontainers and podman

- Jenkinsfile
- build.gradle
- buildSrc/src/main/groovy/swatch.java-conventions.gradle
- buildSrc/src/main/groovy/swatch.quarkus-conventions.gradle
- swatch-contracts/build.gradle
- swatch-core/build.gradle
- swatch-producer-aws/build.gradle
- swatch-producer-aws/src/test/java/com/redhat/swatch/TestContainerTest.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/com/redhat/swatch/processors/BillableUsageProcessorTest.java
- swatch-system-conduit/build.gradle
Jira issue: [SWATCH-382](https://issues.redhat.com/browse/SWATCH-382)
The pull request includes the following changes:
- Change scope of quarkus-jacoco to test
- Replace the deprecated `sonar.login` to `sonar.token`
Sonar was alerting that `sonar.login` is deprecated and is going to be removed.
- fix code coverage for subprojects
The main issue was that by having: `project.tasks["sonarqube"].dependsOn "jacocoTestReport"` only in the parent build.gradle file, the sub projects were generating the jacoco report. 
I fixed that by appending the tasks directly to the gradle command. 
The problem with the Quarkus projects was caused by a wrong location of the jacoco report and missing the Jacoco plugin.
> SWATCH-382: Aggregate code coverage from sub projects

- swatch-api/deploy/clowdapp.yaml
This is what we set in prod currently. Hoping this resolves some EE test issues.
> Bump swatch-api to 800Mi

- src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/TaskQueueProperties.java
Jira issue: [SWATCH-1751](https://issues.redhat.com/browse/SWATCH-1751)
The wrong qualifier name was being used and the default value (15) for max poll records was getting applied instead of the configured value (500).
I also changed the default value in the configuration class to be 500 since that's the kafka default.
To test, we need to send a lot of Event messages to the topic all at once and verify that batching happens correctly. The attached python script can help with this.
1. Download the attached python script and rename to push-events.py
[push-events.py.txt](https://github.com/RedHatInsights/rhsm-subscriptions/files/12685043/push-events.py.txt)
1. Install the python kafka library. 
```
python -m pip install kafka-python --user
```
1. Make sure that the app is NOT running.
1. …
> SWATCH-1751 Properly configure Event kafka consumer factory

- src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
- src/main/java/org/candlepin/subscriptions/tally/billing/BillingUnit.java
- src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntityPK.java
-MetricId on BillableUsage is all uppercase using hyphens. We need to reformat when doing comparisons to the original metricId values in product-config
Regression
1. Start the app with: `LOGGING_LEVEL_ORG_CANDLEPIN_SUBSCRIPTIONS_RHMARKETPLACE=DEBUG  DEV_MODE=true ./gradlew clean :bootRun`
2. Insert Mock data:
```
$ psql -h localhost -U rhsm-subscriptions rhsm-subscriptions -c "INSERT INTO public.subscription(
sku, org_id, subscription_id, quantity, start_date, end_date, billing_provider_id, account_number, subscription_number, billing_provider, billing_account_id)
VALUES ('MW01882', 'org123', '12351253', '1', '2012-05-13 16:32:00+00', '2032-05-13 16:32:00+00', '1', 'account123', '1235153', 'red hat', '456');"
$ psql -h localhost -U rhsm-subscriptions rhsm-subscriptions -c "INSERT INTO …
```
> Fix MetridId comparisons in RHM and Billing Unit

- swatch-producer-azure/deploy/clowdapp.yaml
So that CI can "deploy" swatch-producer-azure.
This will fix bonfire deploy failures in recent PR checks.
> Add empty template for swatch-producer-azure

- bin/validate-topics.py
- src/main/java/org/candlepin/subscriptions/metering/profile/MeteringJobProfile.java
- src/main/java/org/candlepin/subscriptions/metering/profile/OpenShiftWorkerProfile.java
- src/main/java/org/candlepin/subscriptions/metering/task/MeteringTasksConfiguration.java
- src/main/resources/application-metering-job.yaml
- src/main/resources/application-metrics-rhel-job.yaml
- src/main/resources/application-metrics-rhel.yaml
- swatch-metrics/deploy/clowdapp.yaml
Jira issue: [SWATCH-1718](https://issues.redhat.com/browse/SWATCH-1718)
Defining a new ClowdApp to deploy another instance of swatch-metrics, named swatch-metrics-rhel, that connects to RHEL telemeter instance instead of openshift telemeter instance.  There is no need for a separate purge events job, so I omitted it from the swatch-metrics-rhel definition.
This includes creating separate profiles.  This is necessary to allow each deployment to bind to its dedicated kafka topic, and enable the deployments to scale independently.
The part that "points" to the rhel telemeter instance is actually environment variables on the token-refresher sidecar.  These environment variables are set via vault secrets.
What we're looking to verify here is that the `swatch-metrics-rhel-*` pods deploy, start …
> SWATCH-1717 & SWATCH-1718: Create metering-rhel and metering-rhel-job profiles, and define ClowdApps

- Jenkinsfile
- build.gradle
- buildSrc/src/main/groovy/swatch.java-conventions.gradle
- buildSrc/src/main/groovy/swatch.quarkus-conventions.gradle
Jira issue: [SWATCH-382](https://issues.redhat.com/browse/SWATCH-382)
This is a follow-up task of https://github.com/RedHatInsights/rhsm-subscriptions/pull/2533 that will fully address https://issues.redhat.com/browse/SWATCH-382. 
Here, we're configuring the `jacoco-report-aggregation` for a multi-module project. This way, the sub modules will aggregate all the report in a single report to then submit it to sonar. 
More information about the Jacoco Report Aggregation plugin: https://docs.gradle.org/current/userguide/jacoco_report_aggregation_plugin.html
With these changes, the code coverage increased to almost 70%:
As you can see, some modules like `swatch-core` have up to 65% of code coverage. 
Something for the future: to exclude the swatch-core-test and swatch-common-testcontainers.
> SWATCH-382-followup: Incorporate coverage for transitive dependencies

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/MetricProperties.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
- src/main/resources/application-metering-job.yaml
- src/main/resources/application-metrics-rhel.yaml
- src/main/resources/application-openshift-metering-worker.yaml
- src/test/java/org/candlepin/subscriptions/metering/MeteringEventFactoryTest.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/MeteringMetricsFromPrometheusToDatabaseIT.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- swatch-metrics/deploy/clowdapp.yaml
Jira issue: [SWATCH-1745](https://issues.redhat.com/browse/SWATCH-1745)
The "event_source" column should be configured as an env var, set in the [clowdapp](https://github.com/RedHatInsights/rhsm-subscriptions/blob/main/swatch-metrics/deploy/clowdapp.yaml#L181) file, and the configured value saves in the "events" table appropriately
2.- Mock the prometheus server at localhost:
Create the stub directory:
`mkdir -p stub/__files`
Add a stub file to return some data: `stub/__files/swatch-1745.json`
```
cat > stub/__files/swatch-1745.json <<EOF
{
"status" : "success",
"data" : {
"resultType" : "matrix",
"result" : [
{
"metric" : {
"_id" : "cluster id",
"support" : "sla",
"usage" : "usage",
"product" : "product",
"billing_marketplace" : "billing_marketplace", …
```
> SWATCH-1745: Make "event_source" configurable when saving to the events

- swatch-common-testcontainers/src/main/java/org/candlepin/testcontainers/SwatchPostgreSQLContainer.java
Otherwise we get strange behaviors due to kubedock behavior.
Notably,
> Kubedock flattens all networking, which basicly means that everything will run in the same namespace.
> When a network alias is present, it will create a service exposing all ports that have been exposed by the container.
I *think* this will fix recent ci test failures.
> Randomize testcontainer network aliases

- src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerOnDemandTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
Jira issue: [SWATCH-1767](https://issues.redhat.com/browse/SWATCH-1767)
The problem seems to be because we were using a different property `productName` instead of `description` when creating the inventory when is on demand. 
According to the JIRA description, the right value was `description`,  so I refactored the solution to always use the same method when creating the inventory item. 
Note that I also did some cosmetic changes. You can see the commit about SWATCH-1767 for better reviewing it. 
1.- Deploy the project into an ephemeral namespace
2.- Produce some subscription data for ROSA
3.- Invoke the `/api/rhsm-subscriptions/v1/subscriptions/products/rosa` internal endpoint for the Swatch Tally service.
> SWATCH-1767: Subscription table showing Product Name for MW02393

- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
- src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_EUS.yaml
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Jira issue: [SWATCH-1521](https://issues.redhat.com/browse/SWATCH-1521) & Jira issue: [SWATCH-1775](https://issues.redhat.com/browse/SWATCH-1775)
This is to configure `Rhel for x86 EUS` for traditional subscriptions so it may be queried . Effectively, anywhere you can query/interact with `RHEL for x86`. 
Since the eng ids are same i.e `70` for `Rhel for x86 EUS Payg` and `non-payg` we want to make sure the correct product gets pulled when we do hourly tally and nightly tally. Hence there are two instructions one for nightly tally shouldn't pull payg products and other hourly tally should pull payg products.
1. Add host to Insight DB:
```
INSERT INTO public.hosts (id, account, display_name, created_on, modified_on, facts, tags, canonical_facts, system_profile_facts, ansible_host, …
```
> SWATCH-1521 & SWATCH-1775: Configure Rhel for EUS For Swatch

- src/main/resources/application-metrics-rhel.yaml
- src/main/resources/application-openshift-metering-worker.yaml
Jira issue: [SWATCH-1771](https://issues.redhat.com/browse/SWATCH-1771)
We expect a single cluster per metric.  In case of bad data/misconfiguration by the reporter, it's possible to have multiple values.  When this happens, prometheus throws an exception when trying to join.
In the event that the metric corresponds to multiple clusters/instances (identified by unique instance keys, generally _id), we'll take the max value of those to ensure one-to-many matches and avoid attempting to do a many-to-many grouping.
Get the ORG_ID from the jira card to use for testing.
`./bin/metering-promql.py --org $ORG_ID --product rhacs`
Copy the output of "Cores PromQL" and paste it in grafana
https://telemeter-lts-dashboards.datahub.redhat.com/explore
Use the `historical` data source
Set the timeframe …
> SWATCH-1771 - Update promql templates to handle unexpected duplicate instance results

- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_eus_payg.yaml
This enables the swatch-metrics-rhel service to actually receive results from rhelemeter after [HMS-2713 - [SWATCH] create clients to regularly send data](https://issues.redhat.com/browse/HMS-2713) is completed.  Which ultimately will make the swatch/rhelemeter integration testable.
> Add prometheus query params to rhel-for-x86-eus-payg product config

- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
Jira issue: [SWATCH-1809](https://issues.redhat.com/browse/SWATCH-1809)
Include productIds in org.candlepin.subscriptions.db.model.Subscription#equals and hashCode implementation.
Added a new test that reproduces the issue.
> SWATCH-1809: No updates when changes in subscription.productIds

- src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
- src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
- src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
- src/test/java/org/candlepin/subscriptions/inventory/db/InventoryRepositoryIT.java
Jira issue: [SWATCH-1624](https://issues.redhat.com/browse/SWATCH-1624)
Because Discovery now populates the products elsewhere, it's no longer necessary to look at the qpc_certs fact/field.
There is an integration test covering that the updated query to HBI keeps working.
> SWATCH-1624: Remove qpc_certs from HBI query

- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/MetricProperties.java
- src/main/java/org/candlepin/subscriptions/metering/service/prometheus/promql/QueryBuilder.java
- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/promql/QueryBuilderTest.java
Jira issue: [SWATCH-1801](https://issues.redhat.com/browse/SWATCH-1801)
This is the simplest solution I can think of, to replace the SPeL expression parser which perfectly works for our use case and avoids the usage of reflection (so it's compatible with Quarkus native if in the future we want to use it). 
The drawback is that it lacks many features that regular expression parsers have like conditional expressions and many others. 
Another alternative to SPeL expressions and Quarkus Qute is to use [Mvel2](http://mvel.documentnode.com/) (which is supported by JBoss RedHat team). This framework works in Spring Boot and Quarkus, *but not in Quarkus native*, see [the Quarkus example](https://github.com/Sgitario/quarkus-examples/tree/main/mvel2) I created for this - use `mvn clean install` …
> SWATCH-1801: Use simple solution to replace SPeL expression parser

- swatch-tally/deploy/clowdapp.yaml
Notably this normalizes the metric_id values so that downstream consumers of this data don't have to deal with `SOCKETS` vs. `Sockets`.
Testing
=======
You can try the query with gabi in any environment, please add `limit 10` (or similar) so as to not select too much data at once.
> Add floorplan for subscriptions

- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_eus_payg.yaml
Update eus payg product config to match test data available in rhelemeter stage currently.  This should make the swatch-metrics-rhel-job actually start to get data to do something with.
Manual testing of the promql:
1. Start up a token refresher for rhelemeter stage.  Get the client id and secret from vault under the "rhel-token-refresher" secret
```
RHOBS_STAGE_CLIENT_ID=REDACTED
RHOBS_STAGE_CLIENT_SECRET=REDACTED
RHOBS_STAGE_ISSUER_URL=https://sso.redhat.com/auth/realms/redhat-external
RHOBS_STAGE_SCOPE="openid offline_access"
RHOBS_STAGE_URL=https://observatorium-mst.api.stage.openshift.com/api/metrics/v1/rhel/api/v1
podman run --name=telemeter-stage --rm -ti -p 8082:8080 \
quay.io/observatorium/token-refresher:$TOKEN_REFRESHER_VERSION \
--scope=$(echo $RHOBS_STAGE_SCOPE) \ …
```
> Update payg eus product config so metrics get returned

- swatch-tally/deploy/clowdapp.yaml
Same as #2658, but applied to hotfix branch.
Notably this normalizes the metric_id values so that downstream consumers of this data don't have to deal with `SOCKETS` vs. `Sockets`.
Testing
=======
You can try the query with gabi in any environment, please add `limit 10` (or similar) so as to not select too much data at once.
> [HOTFIX] Add floorplan for subscriptions

- Jenkinsfile
The "continuous-integration/jenkins/pr-merge" used to fail with:
```
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
```
This is a random but quite often failure.
Splitting the build and test stages seems to improve the above random issue.
> ci: run build/test phase sequentially instead of in parallel

- swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointTest.java
- swatch-producer-aws/build.gradle
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/AwsUnprocessedRecordsException.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/DefaultApiException.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/ErrorCode.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/files/AwsCredentialsLookup.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/files/ProfileFileConfiguration.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/resource/KafkaResource.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/splunk/QuarkusHecErrorCallback.java
- swatch-producer-aws/src/main/resources/openapi.yaml
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/BillableUsageResourceIT.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/KafkaResourceIT.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/files/AwsCredentialsLookupTest.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/processors/BillableUsageProcessorTest.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/test/resources/InMemoryMessageBrokerKafkaResource.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/test/resources/PostgresResource.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/test/wiremock/WiremockRunner.java
- swatch-producer-azure/build.gradle
Jira issue: [SWATCH-1818](https://issues.redhat.com/browse/SWATCH-1818)
Use an in-memory message broker following the Quarkus guide: https://quarkus.io/guides/kafka#testing-without-a-broker in Quarkus tests that need Kafka.
Moreover, this pull request includes changes that increase the code coverage for the producer aws project.
> SWATCH-1818: Enable KafkaResource resources in tests for Quarkus modules

- src/main/resources/liquibase/202310041633-fix-placeholder-values-for-rosa.xml
- src/main/resources/liquibase/changelog.xml
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/main/resources/db/202310091227_fix_contract_metrics_for_rosa.xml
- swatch-contracts/src/main/resources/db/changeLog.xml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformerTest.java
Jira issue: [SWATCH-1765](https://issues.redhat.com/browse/SWATCH-1765)
If you observe in prod you will see that `subscription_measurements` for subscription: `13579593` there's old test data in the database has the  incorrect `MetricId` for rosa and not allowing QE to see the capacity after contracts are created.
Liquibase changes will update the affect `contracts_metrics` & `subscription_measurements` and the code changes should remove any unsupported metrics from the processing subscription. `19` records that will be affected by this change.
Gabi Query:
```
http -b https://gabi-subscription-watch-prod.apps.crcp01ue1.o9m8.p1.openshiftapps.com/query Authorization:"Bearer $(oc whoami -t)" query="select * from subscription_measurements where subscription_id = '13579593';" 
```
example:
``` …
```
> SWATCH-1765: Fix Contract capacity population for ROSA

- swatch-core/src/main/resources/swatch-core/application.yaml
- swatch-metrics/deploy/clowdapp.yaml
- swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
- swatch-subscription-sync/deploy/clowdapp.yaml
- swatch-system-conduit/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Why?  To support IQE tests.
Related: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/84923
> Use stage endpoints as EE defaults for subscription sync and conduit

- Jenkinsfile
Jira issue: [SWATCH-1829](https://issues.redhat.com/browse/SWATCH-1829)
Bump kubedock image to a version having deps that are not vulnerable to CVE-2023-39325/CVE-2023-44487.
> SWATCH-1829: Bump kubedock to updated image

- build.gradle
- swatch-system-conduit/build.gradle
Jira issue: [SWATCH-1858](https://issues.redhat.com/browse/SWATCH-1858)
Having the hsql dependency as runtime only, it will hide issues when not providing the overridden database dependency since it will use an in-memory hsql dependency.
No need new testing. All the e2e tests should work as expected.
> SWATCH-1858: Change hsql dependency from runtimeOnly to testImplementation

- swatch-producer-aws/deploy/clowdapp.yaml
Everytime EE get deployed, by default it has wrong endpoint for subscription service in aws worker. We have to manually change it to work fine.
Verify swatch-producer-aws-service pointing to correct subscription service endpoint.
> Fix SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT for aws producer

- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
Jira issue: [SWATCH-1857](https://issues.redhat.com/browse/SWATCH-1857)
There were issues with transmitting usage to AWS since the cost event timestamps were in the past. This modification allows us to send usage to AWS if we get it during the current hour of event tally.
Since we persist remitted date when we send usage, we used it as the date to send usage. There is no need to use record_date since it will be -2 hours, and now() will return around the same value as the remittance date.
**Note: You have to change the record date to current hour and tally for that hour.** 
1. Have some cost events from the past:
```
INSERT INTO public.events (event_id, account_number, timestamp, data, event_type, event_source, instance_id, org_id, metering_batch_id, record_date) VALUES …
```
> SWATCH-1857 Modify the timestamp to remittance_pending_date when we send usage to AWS

- src/main/resources/liquibase/202310131200-remove-account-config.xml
- src/main/resources/liquibase/changelog.xml
Jira issue: [SWATCH-664](https://issues.redhat.com/browse/SWATCH-664)
* This PR is dependent on https://github.com/RedHatInsights/rhsm-subscriptions/pull/2632 being released.   With rolling updates, we need the removed references deployed, before deleting the table.
- Deletes the account_config table which is no longer being used.
- Deletes the account_number column in:
- - subscription: unused as of SWATCH-667
- - host: unused as of SWATCH-661
- - events: unused as of SWATCH-667 
- - tally_snapshot: unused as of SWATCH-667
Unit tests & Regression
> SWATCH-664 Remove account_config table

- swatch-tally/deploy/clowdapp.yaml
Jira issue: [SWATCH-1882](https://issues.redhat.com/browse/SWATCH-1882)
The column "account_config" was removed by https://github.com/RedHatInsights/rhsm-subscriptions/pull/2599 (merged yesterday). This pull request is to update the floorist query accordingly. 
You can try the query with gabi in any environment, please add limit 10 (or similar) so as to not select too much data at once.
> SWATCH-1882: floorist-swatch tally failing "account_number" not exist

- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionEntity.java
Jira issue: [SWATCH-1879](https://issues.redhat.com/browse/SWATCH-1879)
The column "account_config" was removed by https://github.com/RedHatInsights/rhsm-subscriptions/pull/2599 (merged yesterday). This pull request is to update the floorist query accordingly. 
1.- Deploy this pull request into one ephemeral namespace.
2.- Portforward the swatch contracts service using the port 8000, so localhost:8000 will talk to the swatch contracts service.
3.- Create a contract using:
```
POST http://localhost:8000/api/swatch-contracts/internal/contracts with valid payload {"subscription_number": "7620583a-e644-4fb6-8496-f9c609d9da76", "sku": "MW02393", "start_date": "2023-10-25T08:14:52Z", "org_id": 16787820, "billing_provider": "aws", "billing_account_id": "1234", "product_id": "rosa", …
```
> SWATCH-1879: column "account_number" in "subscription" does not exist

- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataController.java
- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
- src/main/java/org/candlepin/subscriptions/tally/billing/ContractsController.java
- src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/ContractsControllerTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractRepository.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Jira issue: [SWATCH-1099](https://issues.redhat.com/browse/SWATCH-1099)
Add a DELETE endpoint to swatch-contracts that's available to the "service" role.
For QE, the new endpoint is: "DELETE: /api/swatch-contracts/internal/rpc/reset/contracts/{org_id}"
Added tests to cover the new endpoint.
> SWATCH-1099: deleteDataAssociatedWithOrg should delete contracts

- swatch-tally/deploy/clowdapp.yaml
Until internal stakeholders can switch to org_id.
> [HOTFIX] Get account_number from account_config table (stop-gap)

- src/main/resources/liquibase/202310131200-remove-account-config.xml
- src/main/resources/liquibase/202310251600-replace-account-config-table.xml
- src/main/resources/liquibase/changelog.xml
Related to Jira issue: [SWATCH-667](https://issues.redhat.com/browse/SWATCH-667)
Related to Jira issue: [SWATCH-664](https://issues.redhat.com/browse/SWATCH-664)
Replacing the account_config table on staging.  It still exists on prod.
Run liquibase and verify the account_config table is re-created.  
Also test that if it already exists, it doesn't throw an error.
> Update swatch-664 replace account_config table

- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_ha.yaml
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
Jira issue: [SWATCH-1522](https://issues.redhat.com/browse/SWATCH-1522)
As a developer, I need tallying to counting of traditional (yearly) subscriptions for RHEL High Availability.   I want to define the configuration for rhel-for-x86-ha and use that to do this work. This is focused on traditional subscriptions. There will be other cards for metered subscriptions. 
I've added a test case that covers these changes. The test case and functionality must be reviewed.
Steps for manual testing (the automatic test case mimics the below steps):
2.- Build the whole project:
```
./gradlew clean build -x test
```
3.- Add host to Insight DB:
```
INSERT INTO hosts (id, account, display_name, created_on, modified_on, facts, tags, canonical_facts, system_profile_facts, …
```
> SWATCH-1522: Configure RHEL for x86 HA - traditional subscriptions

- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_rs.yaml
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
Jira issue: [SWATCH-1523](https://issues.redhat.com/browse/SWATCH-1523)
As a developer, I need tallying to counting of traditional (yearly) subscriptions for RHEL Resilient Storage.  
I've added a test case that covers these changes. The test case and functionality must be reviewed. 
Steps for manual testing (the automatic test case mimics the below steps):
2.- Build the whole project:
```
./gradlew clean build -x test
```
3.- Add host to Insight DB:
```
VALUES ('e5406d59-5cf3-4e83-abf8-84c149f8b6ba', 'account123', 'd125f119-0c98-43f2-a5de-ccf2e8e1ab55', '1993-03-26 …
```
> SWATCH-1523: Configure RHEL for x86 Resilient Storage

- src/test/java/org/candlepin/subscriptions/metering/service/prometheus/MeteringMetricsFromPrometheusToDatabaseIT.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/EventRecord.java
Jira issue: [SWATCH-1853](https://issues.redhat.com/browse/SWATCH-1853)
When sending the same event twice into the service ingress consumer, for example if we mock the prometheus service to return the following content:
```
{
"status" : "success",
"data" : {
"resultType" : "matrix",
"result" : [
{
"metric" : {
"_id" : "cluster id",
"support" : "sla",
"usage" : "usage",
"product" : "product",
"billing_marketplace" : "billing_marketplace",
"billing_marketplace_account" : "billing_marketplace_account",
"ebs_account" : "account"
},
"values": [[ $(date +%s), "1" ]]
}
]
}
}
```
And next we run the metering *twice* via:
```
http POST :8000/api/rhsm-subscriptions/v1/internal/metering/rosa?orgId=16790890 \
Origin:console.redhat.com \
x-rh-swatch-synchronous-request:true \ …
```
> SWATCH-1853: Event consumer throws error when updating existing events

- swatch-tally/deploy/clowdapp.yaml
Until internal stakeholders can switch to org_id. Note this uses data we collected in account_config table when available.
Depends on the recreation of the account_config table in stage (we plan to comment out the changeset that removes it from prod, so that prod will have a populated table).
Depends on: #2710.
Queries tested via gabi, need to adjust the tally snapshot date range to 10 days to get an org_id with a mapped account_number.
> Get account_number from account_config table (stop-gap)

- Jenkinsfile
Kubedock release: https://github.com/joyrex2001/kubedock/releases/tag/0.14.0
Related to https://github.com/RedHatInsights/kubedock/pull/4
> Bump kubedock version to 0.14

- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_SAP_x86.yaml
Jira issue: [SWATCH-1861](https://issues.redhat.com/browse/SWATCH-1861)
Add the engId 389 as part of the RHEL SAP configuration-
I've added a test case that covers these changes. The test case and functionality must be reviewed.
Steps for manual testing (the automatic test case mimics the below steps):
2.- Build the whole project:
```
./gradlew clean build -x test
```
3.- Add host to Insight DB:
```
VALUES ('e5406d59-5cf3-4e83-abf8-84c149f8b6ba', 'account123', 'd125f119-0c98-43f2-a5de-ccf2e8e1ab55', '1993-03-26 00:00:00.000000 +00:00', '1993-03-26 00:00:00.000000 …
```
> SWATCH-1861: Add engid 389 to SAP detection

- Dockerfile
- swatch-contracts/src/main/docker/Dockerfile.jvm
- swatch-producer-aws/src/main/docker/Dockerfile.jvm
- swatch-producer-azure/src/main/docker/Dockerfile.jvm
- swatch-system-conduit/Dockerfile
This is necessary to allow the nebula release plugin to populate the git hash as part of the generated version.
Testing
-------
Look at log output in the fetched container image, e.g.
```shell
export hash=$(git rev-parse --short=7 HEAD)
podman run --rm -ti quay.io/cloudservices/rhsm-subscriptions:$hash
```
Notice a line like:
```
2023-10-30 14:27:52,054 [thread=main] [INFO ] [org.candlepin.subscriptions.BootApplication] - Starting BootApplication v1.1.0-snapshot.202310301421.uncommitted+swatch.664.update.a365244 using Java 17.0.9 with PID 1 (/deployments/rhsm-subscriptions-1.1.0-snapshot.202310301421.uncommitted+swatch.664.update.a365244.jar started by default in /deployments)
```
> Add git to the build container

- .tekton/rhsm-subscriptions-pull-request.yaml
- .tekton/rhsm-subscriptions-push.yaml
- .tekton/swatch-system-conduit-pull-request.yaml
- .tekton/swatch-system-conduit-push.yaml
As part of debugging RHTAP checks, we found cel expression parsing seems to not be working properly for unknown reasons. The downside to not using cel expressions is we have no way to limit the pipeline to run for changed components without using cel. We'll open a PR to move back to using CEL expressions separately.
Just wait for the RHTAP pipelines to finish successfully.
> Change tekton triggers not use cel (temporarily)

- src/main/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResource.java
- src/main/java/org/candlepin/subscriptions/metering/profile/OpenShiftWorkerProfile.java
- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
- src/main/java/org/candlepin/subscriptions/tally/events/EventRecordsRetentionProperties.java
- src/main/java/org/candlepin/subscriptions/tally/events/PurgeEventRecordsJob.java
- src/main/spec/internal-metering-api-spec.yaml
- src/main/spec/internal-tally-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/deployment/MetricsRhelDeploymentTest.java
- src/test/java/org/candlepin/subscriptions/deployment/OpenshiftMeteringWorkerDeploymentTest.java
- src/test/java/org/candlepin/subscriptions/metering/api/admin/InternalMeteringResourceTest.java
- src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
- swatch-metrics/deploy/clowdapp.yaml
- swatch-metrics/deploy/clowdapp_quarkus.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: [SWATCH-1880](https://issues.redhat.com/browse/SWATCH-1880)
Move the purge Events cronjob from swatch-metrics to swatch-tally
You can deploy the application and overwrite the PURGE_EVENTS_SCHEDULE environment property with `PURGE_EVENTS_SCHEDULE=*/5 * * * *` (every 5 min).
Another option is to directly alter the CronJob resource that is generated when installing the Clowd app. The CronJob to modify is named "swatch-tally-purge-events". 
Then, in the logs of the job created, you should see:
```
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
HTTP/1.1 204
Set-Cookie: JSESSIONID=29BD65D44DA4AC8268E64FD218E7B81E; Path=/; HttpOnly
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Cache-Control: …
```
> SWATCH-1880: Move purge Events from swatch-metrics to swatch-tally

- pr_check.sh
- swatch-metrics/build.gradle
- swatch-metrics/deploy/clowdapp_quarkus.yaml
- swatch-metrics/schemas/metrics_task_descriptor.yaml
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/MeteringService.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/MetricsConsumer.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/MetricsProducer.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/task/MetricsTaskDescriptorDeserializer.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/task/MetricsTaskDescriptorSerializer.java
- swatch-metrics/src/main/resources/application.yaml
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/MetricsConsumerTest.java
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/MetricsProducerTest.java
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/test/resources/InMemoryMessageBrokerKafkaResource.java
Jira issue: [SWATCH-1800](https://issues.redhat.com/browse/SWATCH-1800)
We need to be able to queue up tasks (eg sync metrics hourly) for our task framework, but we don't want to have to add swatch-core as a dependency.
I've added unit tests that cover the consumer and producer tasks using an in-memory kafka instance.
> SWATCH-1800: Write a from-scratch equivalent of the task message JSON

- api/rhsm-subscriptions-api-spec.yaml
Jira issue: [SWATCH-873](https://issues.redhat.com/browse/SWATCH-873)
This doesn't close SWATCH-873 but just formally marks these APIs as deprecated so they'll show up with red squiggles in the IDE and with warnings and what not.
> Mark deprecated Host APIs

- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
Jira issue: [SWATCH-1764](https://issues.redhat.com/browse/SWATCH-1764)
This issue was caused by OCP and ROSA offerings sharing the same product_name. In order to fix, rosa has been updated with a unique product_name.
1. Insert following data, including an offering with the new product_name:
```
INSERT INTO public.offering VALUES ('MW02393', 'OpenShift Online', 'OpenShift Enterprise', NULL, NULL, NULL, NULL, NULL, 'Premium', '', 'Red Hat OpenShift Service on AWS Hosted Control Planes (Hourly)', false, NULL, 'rosa');
INSERT INTO public.offering VALUES ('MW01484', 'OpenShift Dedicated', 'OpenShift Enterprise', NULL, NULL, NULL, NULL, NULL, 'Premium', '', 'Red Hat OpenShift Dedicated on Customer Cloud Subscription (Hourly)', false, NULL, 'OpenShift-dedicated-metrics');
INSERT INTO …
```
> SWATCH-1764: update rosa product name

- swatch-producer-aws/deploy/clowdapp.yaml
Convert moto to k8s kind Deployment (which we filter out in stage/prod deployments) in order to cleanly deploy moto to EE but not stage/prod.
1. See that the moto service points to a moto pod still
1. See that the moto deployment is successful.
> Convert moto to a k8s Deployment

- api/rhsm-subscriptions-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/utilization/api/model/InstanceReportSortTest.java
Jira issue: [SWATCH-1930](https://issues.redhat.com/browse/SWATCH-1930)
The recently added metric ID vCPUs was missing in the InstanceReportSort enum.
I've added a unit test to not miss other new metrics in this enumerator in the future. 
To manually verify the changes, follow the same instructions as described in the JIRA ticket.
> SWATCH-1930: Unable to sort by vCPUs on RHEL ELS PAYG

- src/main/resources/liquibase/202311161207-drop-account-config-table.xml
- src/main/resources/liquibase/changelog.xml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: [SWATCH-1936](https://issues.redhat.com/browse/SWATCH-1936)
TeleSense requested that we stop reporting the "account_number" column.  By removing that, it allows us to finally drop the account_config table that we stopped using as part of [the clean up account number usage epic](https://issues.redhat.com/browse/SWATCH-657) . 
You can use gabi to verify the sql queries.  Changes should be reflected in S3 reports the next day.
> SWATCH-1936: Remove account_number from floorist queries

- src/main/java/org/candlepin/subscriptions/resteasy/ResteasyConfiguration.java
- src/main/java/org/candlepin/subscriptions/security/ApiSecurityConfiguration.java
- src/main/resources/static/api/swatch-billing/internal/swagger-ui/index.html
- src/main/resources/static/api/swatch-metrics/internal/swagger-ui/index.html
- src/main/resources/static/api/swatch-producer-red-hat-marketplace/internal/swagger-ui/index.html
- src/main/resources/static/api/swatch-subscription-sync/internal/swagger-ui/index.html
- src/main/resources/static/api/swatch-tally/internal/swagger-ui/index.html
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/ResteasyConfiguration.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/security/ApiSecurityConfiguration.java
- swatch-system-conduit/src/main/resources/static/api/swatch-system-conduit/internal/swagger-ui/index.html
Jira issue: [SWATCH-1925](https://issues.redhat.com/browse/SWATCH-1925)
Currently our internal swagger-ui endpoints for spring-boot services in stage and prod are not accessible. I believe this is due to turnpike rules and not having routes available for /api-docs. This change makes it so the swagger ui files are hosted in a directory structure that matches the expected URL so that no redirect to a new path needs to occur.
Verification
1.Verify each of below URLs brings you to the swagger-ui when running with below command:
http://localhost:8000/api/swatch-tally/internal/swagger-ui
http://localhost:8000/api/swatch-metrics/internal/swagger-ui
http://localhost:8000/api/swatch-subscription-sync/internal/swagger-ui …
> SWATCH-1925: Fix access to swagger-ui in stage/prod

- deploy/dev-clowdenv.yaml
- deploy_ephemeral_env.sh
- swatch-contracts/deploy/clowdapp.yaml
- swatch-contracts/src/main/resources/application.properties
- swatch-producer-aws/deploy/clowdapp.yaml
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/deploy/clowdapp.yaml
- swatch-producer-azure/src/main/resources/application.properties
Jira issue: [SWATCH-1864](https://issues.redhat.com/browse/SWATCH-1864)
The clowder config source already deals with the configuration of the URL, truststore path and the rest of properties for SSL. All we need is to use `${clowder.endpoints.<dependency name>-service.url}` instead of `http://${clowder.endpoints.capacity-ingress.hostname}:${clowder.endpoints.capacity-ingress.port}`. 
And also to properly declare the dependencies.
Note that this strongly depends on the ClowdEnvironment object to be updated with:
```
{
"spec": {
"providers": {
"web": {
"tls": {
"enabled": true,
"port": 8800
}
}
}
}
}
```
With `tls.enabled=true`, the envoy sidecar will be created for all the clowd apps. 
However, if the `tls` flag is not enabled, everything will keep working as usual but using HTTP. The …
> SWATCH-1864: quarkus-based services: consume configuration for TLS for inter-service communication from clowder config

- api/rhsm-subscriptions-api-spec.yaml
- src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
- src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
Jira issue: [SWATCH-893](https://issues.redhat.com/browse/SWATCH-893)
remove deprecated hosts API endpoint __ /hosts/{hypervisor_uuid}/guests
test for regressions, remove any references to this API
> SWATCH-893: remove deprecated hosts API endpoint

- src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
- src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java
Jira issue: [SWATCH-921](https://issues.redhat.com/browse/SWATCH-921)
Subscription Watch logs warnings when a marketplace payload mapper picks up a message that is destined for another marketplace. This creates a lot of warning-level log spam.
Note that I removed some methods and fields that were not used in this class (this was done in a separate commit to ease the review). 
QE is unneeded.
> SWATCH-921: Debug traces when billages are skipped due marketplace

- api/rhsm-subscriptions-api-spec.yaml
- src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
- src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
Jira issue: [SWATCH-57](https://issues.redhat.com/browse/SWATCH-57)
Add a new type `TallyReportTotalMonthly` with the date optional.
These changes are only meant for QE.
> SWATCH-57: Add TallyReportTotalMonthly with date optional

- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/prometheus/PrometheusService.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/processors/BillableUsageProcessor.java
Jira issue: SWATCH-1948
Catching the two exceptions is only meant to be caught for Quarkus rest clients because it will throw ProcessingException instead of ApiException. 
The problem is that the generated sources by the Quarkus REST-Client Reactive extension can only deal with runtime exceptions because it uses reactive flows, however the generated ApiException class by the OpenApi plugin is not a RuntimeException, but Exception.
Extended context in the JIRA ticket. 
No QE is needed here.
> SWATCH-1948: Catch ProcessingException and ApiException exceptions

- clients/rh-partner-gateway-client/rh-partner-gateway-api-spec.yaml
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/RhPartnerClientIntegrationTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
Rename affected field redhatSubscriptionNumber to match the expected response property
Jira issue: SWATCH-1965
Fix for error as we were expecting `redHatSubscritpionNumber` and it is cause null error when syncing because Partner Gateway is sending a value as `subscriptionNumber` and we are changing the spec to reflect that until https://issues.redhat.com/browse/ITPART-1161 and than this change will be reverted.
Run this on `main` branch
Insert contract to sync against:
```
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('94857b05-8e13-4407-90aa-52c2ae676deb', '123456789', '2023-11-02 15:44:22.846502 +00:00', '2023-11-02 15:44:22.846502 +00:00', null, …
```
> SWATCH-1965: Tweak entitlement With subscriptionNumber to match Partner Gateway specs

- swatch-core/src/main/java/org/candlepin/subscriptions/clowder/ClowderJsonPathPropertySource.java
- swatch-metrics/src/main/resources/application.yaml
Jira issue: [SWATCH-1985](https://issues.redhat.com/browse/SWATCH-1985)
Description
===========
There were a couple of recently introduced issues with kafka configuration:
1. swatch-metrics uses yaml config, and we set `kafka.sasl.jaas.config` to `null`, which clowder config source treats as missing, so it doesn't populate this property. (The fix is to set to empty string (`''`)
2. Recent updates to kafka config parsing in spring boot expect the clowder config to always contain kafka config (which doesn't happen if there are no topics specified in the ClowdApp). The fix is to simply not contribute kafka config if missing from clowder config.
Testing
=======
Setup
-----
Start kafka and postgres via podman-compose.
Verification
------------
Create an empty clowder config and then start the …
> SWATCH-1985: Fix kafka configuration issues

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- swatch-model-events/build.gradle
- swatch-model-events/schemas/event.yaml
Jira issue: SWATCH-1928
Finding the product_tag during event ingestion is the goal of this card. Therefore, we get away from determining the product tag at the time of running the tally or any other event-related process. As a result, I removed the code that determined the product tag during the tally process at a later stage. This card just takes care of payg products since there is no way to determine payg or non-payg through an event. There will be a future card https://issues.redhat.com/browse/SWATCH-1993 to handle that use case.
_Note: Since QE may be mocking the event beforehand and it hasn't gone through the event ingestion process, the product_tag will be missing, so they will need to modify their tests.
https://gitlab.cee.redhat.com/smqe/smqe-tools/-/blob/master/smqe_tools/__init_ …
> SWATCH-1928 Payg Event ingestion should write product tag in Events table

- CONTRIBUTING.md
- bin/liquibase-new-changeset.sh
For a recent task I found myself wanting to prototype db changes quickly.
Invoked as `bin/liquibase-new-changeset.sh change set description`.
It takes any args passed, and lower cases them, and replaces spaces with `-`, and then adds the new changeset to our changelog.xml file.
> Add script to generate new changeset xml

- clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
- swatch-system-conduit/schemas/inventory/hbi-system-profile.yaml
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/ConduitFacts.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
- swatch-system-conduit/src/main/spec/internal-organizations-sync-api-spec.yaml
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java
Jira issue: [SWATCH-379](https://issues.redhat.com/browse/SWATCH-379)
Populate the value in the system profile:
<candlepin fact> -> <system profile field>
cpu.cpu(s) -> number_of_cpus: [link to API](https://github.com/RedHatInsights/insights-host-inventory/blob/470f2264ed7be2f5b028f880a7aae2790ca9e660/swagger/system_profile.spec.yaml#L222)
cpu.thread(s)_per_core -> threads_per_core: [link to API](https://github.com/RedHatInsights/insights-host-inventory/blob/470f2264ed7be2f5b028f880a7aae2790ca9e660/swagger/system_profile.spec.yaml#L237)
Added test to cover this change and ensure that the values are persisted. 
I don't think we need QE here (after SWATCH-401 is done, they can verify the end-to-end change).
0.- Start Kafka
`podman-compose up`
1.- Run conduit app with stubs …
> SWATCH-379: Sync new vCPUs field to HBI when present

- src/main/spec/internal-subscriptions-sync-api-spec.yaml
swagger ui just showed "string" as the example, since it's not defined by a schema.  we programatically map the string to another openapi generated "Subscription" object.  We should change that eventually, but in the meantime I added an example payload.  I pulled the example out of a PR comment - https://github.com/RedHatInsights/rhsm-subscriptions/pull/2641#pullrequestreview-1705980261 
Also marking `reconcileCapacity` queryParam as required so swagger-ui makes you set it, otherwise you'll get a NPE in the logs
Verification
- on main branch, see that http://localhost:8000/api/swatch-subscription-sync/internal/swagger-ui/index.html#/internalSubscriptions/saveSubscriptions just had "string"
- on this branch, see that there's an example payload that should actually POST successfully once …
> Add example payload to openapi spec for POST /internal/subscription

- src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
- src/main/spec/internal-subscriptions-sync-api-spec.yaml
Jira issue: SWATCH-2008
Getting the openapi changes for the SWATCH-2006 story to enable testability.  Added corresponding stub method to the resource class.  It will return hardcoded values until SWATCH-2006 is implemented
**_Verification_**
`DEV_MODE=true RHSM_USE_STUB=true ./gradlew :bootRun` (or if deploying to EE, port forward the swatch-subscrpition-sync pod)
Navigate to: http://localhost:8000/api/swatch-subscription-sync/internal/swagger-ui/index.html#/internalSubscriptions/getAzureMarketplaceContext
Check api responds with current hardcoded values
```
http :8000/api/rhsm-subscriptions/v1/internal/subscriptions/azureUsageContext \
accept:application/json \
"orgId==org123" \
"date==2023-10-31T00:00:00Z" \
"productId==rhel-for-x86-els-payg" \ …
```
> SWATCH-2006, SWATCH-2008: openapi definition for getAzureMarketplaceContext

- src/test/java/org/candlepin/subscriptions/resource/api/SwaggerTest.java
I want to rescue some tests I added in https://github.com/RedHatInsights/rhsm-subscriptions/pull/2838 to ensure that the swagger endpoints are functional in spring services (because these are configured in the ResteasyConfiguration class).
There is no functional change here, only a couple of tests were added.
> Add tests to cover the swagger endpoints in Spring services

- clients/rh-partner-gateway-client/rh-partner-gateway-api-spec.yaml
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractSourcePartnerEnum.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Jira issue: [SWATCH-1720](https://issues.redhat.com/browse/SWATCH-1720)
This is to allow SWATCH contract to handle azure contracts from entitlement gateway. For azure subscriptions the subscriptions `azureResourceId` should be sufficient for getting a unique entitlement as it's a unique identifier per SaaS purchase : [slack thread](https://redhat-internal.slack.com/archives/C05M0H1JH7X/p1698352078477369) , as of the time of this change the gateway does not yet[ support search](https://issues.redhat.com/browse/ITPART-1130) by `resourceId`
Add Environment Variables for SWATCH Contracts:
```
QUARKUS_PROFILE=dev;SWATCH_SELF_PSK=placeholder;ENTITLEMENT_GATEWAY_URL=http://localhost:8101/mock/partnerApi;SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8101/mock/internalSubs
``` 
1. Create …
> SWATCH-1720: Update SWATCH Contract To Handle Azure Contracts

- stub/README.md
- stub/wiremock.yaml
- swatch-contracts/src/main/resources/application.properties
Supports testing of #2717 in Ephemeral Environments
The gist here is to optionally shove a wiremock deployment & service into an ephemeral environment, and then you can configure port-forward the pod to create stubs, and then configure other pods to point to wiremock.
This PR gives the yaml for wiremock to be deployed, and creation of a "wiremock" quarkus profile that will set ENTITLEMENT_GATEWAY_URL, SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT, and SUBSCRIPTION_URL to point to a deployed wiremock service.
Example workflow:
Deploy swatch with bonfire.  The template ref for this example is this PR's commit (needed for that mentioned ClowdApp change).  Then follow instructions in the README.md file to deploy wiremock and create a stub.
```
TEMPLATE_REF=f14b85cd8b00d3fc95e48dd3a4f2320cf4ef8398 …
```
> Sample openshift definition for deploying wiremock to ephemeral environment

- src/test/java/org/candlepin/subscriptions/tally/UsageCalculationTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/tally/UsageCalculation.java
Jira issue: [SWATCH-2009](https://issues.redhat.com/browse/SWATCH-2009)
When processing multiple events, we were seeing weird values in the "tally_measurements" table like "9.799999999999999". This issue was caused by manipulating double numbers (see this link for further information: https://floating-point-gui.de/).
To fix the issue, we should use the BigDecimal class to accumulate the values in the UsageCalculation. 
Only regression testing is needed. JUnit tests have been added.
> SWATCH-2009: Fix round issue when dealing with double numbers

- swatch-contracts/deploy/clowdapp.yaml
- swatch-contracts/src/main/resources/application.properties
- swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
- swatch-subscription-sync/deploy/clowdapp.yaml
Jira issue: [SWATCH-2036](https://issues.redhat.com/browse/SWATCH-2036)
Add the `rbac` dependency in the services that use it:
1. swatch-contracts
2. swatch-subscription-sync
3. swatch-producer-red-hat-marketplace
For the services 2. and 3., the rbac URL was already properly configured.
For the service 1 (swatch-contracts), it was being configured like:
```
${clowder.endpoints.rbac-service:http://localhost:8080}
```
And there were two issues here:
- The clowder config does not support default values, 
- The new format needs to end with `.url`
The final configuration should be:
```
RBAC_ENDPOINT=${clowder.endpoints.rbac-service.url}
%dev.RBAC_ENDPOINT=http://localhost:8080
%test.RBAC_ENDPOINT=http://localhost:8080
quarkus.rest-client."com.redhat.swatch.clients.rbac.api.resources.AccessApi". …
```
> SWATCH-2036: Update Contracts service configuration to configure the RBAC service

- buildSrc/src/main/groovy/swatch.quarkus-rest-client-conventions.gradle
- src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
- src/main/spec/internal-subscriptions-sync-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
Jira issue: [SWATCH-470](https://issues.redhat.com/browse/SWATCH-470)
- Rename DefaultResponse to RpcResponse
- Remove status field
- Add result field w/ type "any" (don't specify the type param in spec).
- Document for "result" field, may be null (if unneeded). 
Regression testing only. If there are tests that expect the old format ("Sync started. "), then these tests are to be updated to expect the JSON format (to check if the result was 200 OK).
> SWATCH-470: Internal subscriptions sync org rest api should return json

- dependencies.gradle
Jira issue: [SWATCH-2035](https://issues.redhat.com/browse/SWATCH-2035)
This is the recommended approach after reading https://github.com/dependabot/dependabot-core/issues/2046.
> SWATCH-2035: Use same version for Quarkus BOM and Quarkus Gradle plugin

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
Jira issue: [SWATCH-2046](https://issues.redhat.com/browse/SWATCH-2046)
We should support events without the product_tag field (old functionality) because these events might have been stored in database before https://github.com/RedHatInsights/rhsm-subscriptions/pull/2844
Added test coverage for this use case.
QE should add test automation as well.
> SWATCH-2046: Resolve product tags from configuration for old events

- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Jira issue: SWATCH-2061
"contract-updated" UMB messages will not contain the subscription number on azure contracts so we need to grab it from partner api.
[swatch-2061-test-steps.txt](https://github.com/RedHatInsights/rhsm-subscriptions/files/13812083/swatch-2061-test-steps.txt)
> SWATCH-2061: Get subscriptionNumber from partner api for azure contracts

- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/DefaultExceptionMapper.java
Jira issue: [SWATCH-2043](https://issues.redhat.com/browse/SWATCH-2043)
The root cause of this problem is that the DefaultExceptionMapper is capturing the exception to construct the client response, but won't log the exception. 
- Throw an exception in any of the resources, for example, a null pointer exception when creating entitlement contracts:
```
@Override
@RolesAllowed({"test"})
public StatusResponse createPartnerEntitlementContract(PartnerEntitlementContract contract)
throws ProcessingException {
String s = null;
s.toString(); // BOOM!
return service.createPartnerContract(contract);
}
```
- Start the swatch contracts service:
```
SWATCH_SELF_PSK=placeholder UMB_ENABLED=false RBAC_ENABLED=false ./gradlew :swatch-contracts:quarkusDev
```
- Try to create an entitlement contract:
``` …
```
> SWATCH-2043: Print exceptions in swatch contract resources

- bin/metering-promql.py
This script broke after all the query template app properties got consolidated when swatch-metrics got carved out of the monolith
Before the change
```
./bin/metering-promql.py --product rhel-for-x86-els-payg --org 16787820
```
```
Traceback (most recent call last):
File "/home/lburnett/code/rhsm-subscriptions/./bin/metering-promql.py", line 28, in <module>
account_query_templates = config["rhsm-subscriptions"]["metering"]["prometheus"][
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'metering'
```
After the change
```
./bin/metering-promql.py --product rhel-for-x86-els-payg --org 16787820
```
```
rhel-for-x86-els-payg
---------------------
Accounts PromQL: group(min_over_time(system_cpu_logical_count{product='Red Hat Enterprise Linux Server', external_organization != '', …
```
> Fix broken metering-promql.py script

- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractMapperTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Jira issue: SWATCH-2074
Contracts is failing to save UMB messages because dimensions are coming from the message itself rather than the partner API. This change allows us to get dimension from both the message and partnerApi.
> SWATCH-2074: save dimension from umb message

- init_dbs.sh
Any restart to the DB pod will result in an error since we try to create
the necessary user every time.  Rather than add the more complex logic
to detect whether the user exists or not, I'm just going to set the DB
start-up to keep going even if it encounters an error.
> Don't halt DB pod start-up on error

- swatch-metrics/build.gradle
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
Jira issue: SWATCH-2066
Add a timer to track metrics collection timing.
1. Start a prometheus container
```
podman run -ti --rm -p 9090:9090 quay.io/prometheus/prometheus
```
1. Write a Clowder configuration file to `/tmp/test-clowder.json`
```json
{
"kafka": {
"brokers": [
{
"hostname": "localhost",
"port": 9092
}
],
"topics": []
},
"metricsPath": "/metrics",
"metricsPort": 9000,
"privatePort": 10000,
"publicPort": 8000,
"webPort": 8000
}
```
1. Start swatch-metrics using the clowder and prometheus settings
```
export RHSMSUBSCRIPTIONS_METERING_PROMETHEUS_CLIENT_URL=http://localhost:9090/api/v1
ACG_CONFIG=/tmp/test-clowder.json ../gradlew quarkusDev
```
1. Trigger a run
```
http -v POST :8000/api/swatch-metrics/v1/internal/metering/rhel-for-x86-els-payg orgId==16787820 …
```
> SWATCH-2066: Add timer for metrics collection

- swatch-subscription-sync/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-1968
Allow ability to spin up and interact with Export Service
Switch to this branch before deployment 
Deploy bonfire :
```
bonfire deploy rhsm --source=appsre --ref-env insights-production --set-template-ref rhsm=b45680a1da9ec1335251614ce0d5029564ef2ba3 --set-image-tag quay.io/cloudservices/swatch-system-conduit=pr-2899-b45680a --timeout 900 --optional-deps-method none --frontends false --no-remove-resources rhsm --no-remove-resources swatch-api --no-remove-resources swatch-contracts --no-remove-resources swatch-producer-aws --no-remove-resources swatch-producer-red-hat-marketplace --no-remove-resources swatch-metrics --no-remove-resources swatch-subscription-sync --no-remove-resources swatch-system-conduit --no-remove-resources swatch-tally --no-remove-resources …
```
>  SWATCH-1968: Add Export service as a dependency in Tally & Subscription-sync

- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
- swatch-metrics/src/main/resources/application.yaml
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/util/MeteringEventFactoryTest.java
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg.yaml
Jira issue: SWATCH-1924
**Context**
Getting creative with how we can detect these RHEL payg products with rhelemeter, since the role available on the hosts isn't unique enough to differentiate between different variants.
This change enables hosts to report a list of comma-separated engineering Ids in its "product" label. We'll detect comma-separated engineering Ids and set the swatch event.productIds field accordingly.
During hourly tally, we already match events to swatch subscription definitions by using event.role or event.productIds anyway.
Introduced a new promql query template.  There's a couple of differences than the default template
* removes "metadataMetric" parameter
* adds "productLabelRegex" parameter.
* removes instanceKey parameter (note that instanceKey still needs to be …
> SWATCH-1924: Support querying prometheus/rhelemeter when "product" label has engIds

- .gitignore
- README.md
- config/otel/collector-config.yaml
- config/otel/docker-compose.yml
- config/rabbitmq/docker-compose.yml
- config/rabbitmq/rabbit_enabled_plugins
- config/splunk/docker-compose.yml
- swatch-contracts/src/main/resources/application.properties
Related to Jira issue: [SWATCH-2038](https://issues.redhat.com/browse/SWATCH-2038)
These changes allow us to test the remote logging export locally.
For example, for swatch-contracts, we would need to:
1.- Start kafka, db, ... via:
```
podman-compose up -d
```
2.- Start otel exporter:
```
podman-compose -f config/otel/docker-compose.yml up -d
```
3.- Start rabbitmq:
```
podman-compose -f config/rabbitmq/docker-compose.yml up -d
```
4.- Build swatch contracts:
```
./gradlew clean swatch-contracts:assemble -x test
```
5.- Start the swatch contracts service:
```
java -DSWATCH_SELF_PSK=placeholder -DENABLE_SPLUNK_HEC=false -DSWATCH_TEST_APIS_ENABLED=true -DRBAC_ENABLED=false -DUMB_HOSTNAME=localhost -DUMB_PORT=5672 -DOTEL_ENDPOINT=http://localhost:4317 -DRBAC_ENDPOINT=localhost:8080 -jar …
```
> Add instructions to deploy OTEL exporter, RabbitMQ and Splunk locally

- src/main/resources/application-worker.yaml
Supports user request to see last 5 years of Quarterly tallies from the UI.
Relates to Jira issue: SWATCH-1594, but doesn't close the RFE.
> Update tally retention policy for quarterly snapshots

- src/main/java/org/candlepin/subscriptions/subscription/ActiveMQServiceConfiguration.java
- src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
Jira issue: [SWATCH-2069](https://issues.redhat.com/browse/SWATCH-2069)
The methods "findBySubscriptionNumber" and "findActiveSubscription" expect to find unique results. When multiple entities are found, it returns the IncorrectResultSizeDataAccessException exception.
2.- apply migrations
```
./gradlew :liquibaseUpdate
```
3.- add the required data:
which is the offering and the duplicate subscription with a different start date. 
```
INSERT INTO OFFERING(sku,product_name,product_family,sla,description,has_unlimited_usage) 
VALUES ('MW00332','OpenShift Data Science','OPENSHIFT ENTERPRISE','Premium','Red Hat OpenShift Data Science','false');
INSERT INTO subscription(sku,org_id,subscription_id,quantity,start_date,subscription_number) …
```
> SWATCH-2069: Fix IncorrectResultSizeDataAccessException when saving subs

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
Revert changes of issue: SWATCH-2069
We need to revert the changes that was made for SWATCH-2069 because when having duplications, we might select a subscription with a different start date that might lead to this exception:
```
2024-01-15 12:04:00,970 [thread=org.springframework.jms.JmsListenerEndpointContainer#1-2] [INFO ] [org.candlepin.subscriptions.subscription.SubscriptionWorker] - Received UMB message for subscriptionNumber=12648168 webCustomerId=16767885
2024-01-15 12:04:00,972 [thread=org.springframework.jms.JmsListenerEndpointContainer#1-2] [WARN ] [org.hibernate.orm.query] - HHH90003004: firstResult/maxResults specified with collection fetch; applying in memory
2024-01-15 12:04:01,889 [thread=org.springframework.jms.JmsListenerEndpointContainer#1-2] [WARN ] …
```
> SWATCH-2069: Populate subscription product ids when sync subscriptions

- src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingResource.java
- src/main/resources/liquibase/202401151414-add-retry_after-column-to-billable_usage_remittance-table.xml
- src/main/resources/liquibase/changelog.xml
- src/main/spec/internal-billing-api-spec.yaml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntity.java
Jira issue: SWATCH-2103
Creates stub API for retrying processing of billable usage.  Adds new nullable column to database table as well.  Business logic not yet implemented.
Inspect the database to verify new column.
Here's an httpie request to test the new API.
```
http POST :8000/api/rhsm-subscriptions/v1/internal/rpc/remittance/processRetries as_of==2000-01-01T00:00Z x-rh-swatch-psk:placeholder
```
```
HTTP/1.1 500 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: close
Content-Length: 86
Content-Type: application/vnd.api+json
Date: Mon, 15 Jan 2024 19:06:12 GMT
Expires: 0
Pragma: no-cache
Set-Cookie: JSESSIONID=CD73A3E1CC504CD5A78718B084ABD742; Path=/; HttpOnly
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers …
```
> SWATCH-2103: Schema updates for enabling retry remittance

- swatch-metrics/deploy/clowdapp.yaml
Jira issue: SWATCH-2066
This is necessary so that app-interface can actually find our Prometheus metrics!
1. Write a Clowder configuration file to `/tmp/test-clowder.json`
```json
{
"kafka": {
"brokers": [
{
"hostname": "localhost",
"port": 9092
}
],
"topics": []
},
"metricsPath": "/metrics",
"metricsPort": 9000,
"privatePort": 10000,
"publicPort": 8000,
"webPort": 8000
}
```
1. Start swatch-metrics using the clowder and prometheus settings
```
export RHSMSUBSCRIPTIONS_METERING_PROMETHEUS_CLIENT_URL=http://localhost:9090/api/v1
ACG_CONFIG=/tmp/test-clowder.json QUARKUS_MANAGEMENT_ENABLED=true ../gradlew quarkusDev
```
1. Pull the metrics
```
http :9000/metrics
```
> SWATCH-2066: Expose prometheus data on :9000/metrics for swatch-metrics

- pr_check.sh
Switches `--no-remove-resources` to use the new app syntax supported in bonfire v5.4.0
> Use app syntax for --no-remove-resources

- src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
- swatch-core/src/main/java/org/candlepin/subscriptions/clowder/KafkaSslBeanPostProcessor.java
- swatch-core/src/main/resources/swatch-core/application.yaml
- swatch-core/src/test/java/org/candlepin/subscriptions/clowder/KafkaSslBeanPostProcessorTest.java
Jira issue: SWATCH-2088
Under normal circumstances, if you wanted to use the system truststore, you simply wouldn't set the kafka.ssl.truststore-certificates property at all.  The KafkaProperties.Ssl instance would then have null for the truststoreCertificates field and Kafka would initialize using the default system truststore.
We, however, are using Clowder and we need to set the truststore-certificates property if a certificate is provided to us.  We use the ClowderJsonPathPropertySource class to do this and set the property to something like `${clowder.kafka.brokers.cacert}`. Unfortunately, if the ClowderJsonPathPropertySource can't resolve that JSON path, the property ends up getting set to the literal string "${clowder.kafka.brokers.cacert}" which of course is not a valid …
> SWATCH-2088: Allow Spring Kafka configuration to operate using the system truststore

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorker.java
- src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
Jira issue: [SWATCH-2069](https://issues.redhat.com/browse/SWATCH-2069)
The first attempt to fix SWATCH-2069 was to get the first subscription when multiple entities were found: https://github.com/RedHatInsights/rhsm-subscriptions/pull/2938. However, this fix caused lots of errors about the subscription_product_ids_pk constraint were violated. Therefore, it was reverted by https://github.com/RedHatInsights/rhsm-subscriptions/pull/2967. 
I've detected that we are receiving many UMB message for the same subscription number. For example:
```
{"severity":"INFO","logger":"org.candlepin.subscriptions.subscription.SubscriptionWorker","thread":"org.springframework.jms.JmsListenerEndpointContainer#1-1","message":"2024-01-17T08:17:44.784+0000 …
```
> SWATCH-2069: Skip UMB message when multiple subscriptions are found

- swatch-metrics/deploy/clowdapp.yaml
This change caused this error during ClowdApp reconciliation
```
{"level":"error","ts":1705692365.384922,"msg":"Reconciler error","controller":"clowdapp","controllerGroup":"cloud.redhat.com","controllerKind":"ClowdApp","ClowdApp":{"name":"swatch-metrics-rhel","namespace":"rhsm-stage"},"namespace":"rhsm-stage","name":"swatch-metrics-rhel","reconcileID":"23c6d526-fddf-41d0-abe9-d41f631f087c","error":"error updating resource Deployment swatch-metrics-rhel-service: Deployment.apps \"swatch-metrics-rhel-service\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"app\":\"swatch-me…
```
We want to place the labels on the podSpec instead, but Clowder isn't currently propagating that when those fields are set.
> Revert "SWATCH-2066: Expose prometheus data for swatch-metrics"

- swatch-metrics/README.md
- swatch-metrics/src/main/resources/application.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg.yaml
Jira issue: SWATCH-2109
Human explanation of the new query can be found here: https://github.com/RedHatInsights/rhsm-subscriptions/blob/lburnett/swatch-2109-rhelemeter-promql/swatch-metrics/README.md#querytemplatesrhelemeter
We've opted to not use the recording rule for two reasons.  First, it was only further complicating an already complicated promql query.  Second, we get more accurate data by not using it.  When we requested a recording rule to be made, we expected that its evaluation would happen the same frequency as the openshift telemeter instance.  Since that's not going to be the case, using a recording rule doesn't benefit us much.
>The problem: we have two series: one for a first half of an hour with a label support=premium, and one for the the second half of an hour with a …
> SWATCH-2109 Eliminate double billing scenarios & modify the PromQL for rhel metering to handle system label changes

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
Jira issue: SWATCH-2084
Need to set the billingAccountId for azure events by using the fields azure_tenant_id and azure_subscription_id from cost-mgmt.
1. Start app w/: `DEV_MODE=true ./gradlew :bootRun`
1. Put message on topic platform.rhsm-subscriptions.service-instance-ingress:
`{"sla": "Premium", "role": "Red Hat Enterprise Linux Server", "usage": "Production", "org_id": "org_123", "event_id": "3d363cc8-b2bc-4230-a943-638a4822da70", "timestamp": "2024-01-21T22:00:00Z", "event_type": "snapshot", "expiration": "2024-01-21T23:00:00Z", "instance_id": "test", "product_ids": ["69", "204"], "product_tag": ["rhel-for-x86-els-payg"], "event_source": "cost-management", "measurements": [{"uom": "vCPUs", "value": 1.0}], "service_type": "RHEL System", "hardware_type": "Cloud", "cloud_provider": …
> swatch-2084: update eventController to set the azure billingAccountId

- swatch-tally/deploy/clowdapp.yaml
Jira issue: [SWATCH-2105](https://issues.redhat.com/browse/SWATCH-2105)
Currently, the where clause includes this expression
`snapshot_date > now() - interval '2 day';`
However, depending on timing, this sometimes gathers 1 days data, sometimes 2 days worth.
Instead, change the clause to
`snapshot_date > date_trunc('day', now() - interval '2 day')`
which will force the query to pull only data from tallies for 2 days ago.
1.- `podman-compose up` to start up the PostgreSQL database instance.
2.- `./gradlew liquibaseUpdate` to perform all the migrations
3.- Insert the test data:
```sql
-- Create snapshot 000000000001 from today
INSERT INTO tally_snapshots(id, product_id, granularity, org_id, snapshot_date, sla, "usage", billing_provider, billing_account_id) …
```
> SWATCH-2105: Constrain tally floorist exports to 1 day's range

- src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
- src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
Jira issue: [SWATCH-2127](https://issues.redhat.com/browse/SWATCH-2127)
This endpoint was missing the `@ReportingAccessRequired`
Added a test to cover this endpoint.
For manual testing:
* Create a Servive account with no permissions
* Try and access v1/instances/products/ API on stage
> SWATCH-2127: Secure the endpoint /instances/products/{product_id}

- src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
- src/main/spec/internal-subscriptions-sync-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/processors/BillableUsageProcessor.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/exception/ErrorCode.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/exception/SubscriptionCanNotBeDeterminedException.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/resource/DefaultApiExceptionMapper.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageConsumer.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageDeadLetterTopicProducer.java
- swatch-producer-azure/src/main/resources/application.properties
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Jira issue: [SWATCH-2099](https://issues.redhat.com/browse/SWATCH-2099)
- When swatch-azure-producer receives a billableUsage and the subscription can not be determined (subscriptionId unavailable), a message is produced to billable-usage.dlt with retry_after header set to now() + 1hr
- When the subscriptionId is unavailable and the usage is past 72 hours (configurable) old, log a warning
Log non retriable other errors at either warning or error
Note that then the subscription API does not find the subscription, it returns the HTTP Status Code 404. 
1. `podman-compose up`
2. mock the subscription service:  
`podman run -it --rm -p 8101:8080 --name wiremock -v $PWD/stub:/home/wiremock:z wiremock/wiremock:2.32.0 --verbose`
```
cat > stub/__files/swatch-2099.json <<EOF
{
"errors" : [  { …
```
> SWATCH-2099: Produce failed messages to dlt for swatch-azure-producer

- swatch-metrics/schemas/metrics_task_descriptor.yaml
Rename the "product_id" name from the required list to the right name "product_tag" ("product_id" does not exist).
No need QE here.
> Fix the MetricsTaskDescriptor definition

- bin/liquibase-new-changeset.sh
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractRepository.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/PanacheSpecificationSupport.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/main/resources/db/202401111039_make_subscription_number_nullable.xml
- swatch-contracts/src/main/resources/db/202401121651_add_billingproviderid_to_contracts.xml
- swatch-contracts/src/main/resources/db/202401171354_add_subscription_and_offering_h2_only.xml
- swatch-contracts/src/main/resources/db/changeLog.xml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/AzureContractLifecycleIntegrationTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Jira issue: [SWATCH-2083](https://issues.redhat.com/browse/SWATCH-2083)
With this change, a contract can be ingested before the subscriptionNumber has been assigned.
I made changes to our handling of the end dates, so that the contract records no longer use `null` end date for the most current contracts, but use the passed end date.
I added `billingProviderId` to `ContractEntity`, and changed the upsert to use billingProviderId to lookup the existing record, instead of depending on subscriptionNumber.
I also updated the `bin/liquibase-new-changeset.sh` script to work for swatch-contracts.
I also updated WireMockResource to enable use of the static stubbing methods in any test class using WireMock.
Testing
-------
See AzureContractLifecycleIntegrationTest, which simulates the various …
> SWATCH-2083: Update contract ingestion to require less data

- swatch-metrics/src/main/resources/application.yaml
Jira issue: SWATCH-2066
Increases the Kafka message timeout from 1 minute to 2 minutes.
1.  On a terminal, start a Prometheus instance (note that I bind to my local port 9095 since Cockpit uses 9090):
```
podman run --rm -p 9095:9090 quay.io/prometheus/prometheus
```
1.  Run the `swatch-metrics` app pointing to your prometheus instance
```
RHSM_SUBSCRIPTIONS_METERING_PROMETHEUS_CLIENT_URL=http://localhost:9095/api/v1 ../gradlew quarkusDev
```
1. Enqueue a task
```
http POST localhost:8000/api/swatch-metrics/v1/internal/metering/rhel-for-x86-els-payg orgId==16787820 endDate==2024-01-09T20:00Z
```
1. The task should flow through without a problem.
1. Stop the application and apply the following patch:
```patch
diff --git a/swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/Metric …
```
> SWATCH-2066: Increase Kafka message acknowledgment timeout

- src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageDeadLetterConsumer.java
- src/main/resources/application-worker.yaml
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageDeadLetterConsumerTest.java
Jira issue: SWATCH-2100
Consume billable-usage.dlt messages and add retryAfter to billable_usage_remittance when available.
1. `podman-compose up`
2. mock the subscription service:  
`podman run -it --rm -p 8101:8080 --name wiremock -v $PWD/stub:/home/wiremock:z wiremock/wiremock:2.32.0 --verbose`
```
cat > stub/__files/swatch-2099.json <<EOF
{
"errors" : [  { "code": "SUBSCRIPTIONS1006" }  ]
}
EOF
```
```
curl -X POST --data '{ "priority": 1, "request": { "urlPath": "/api/rhsm-subscriptions/v1/internal/subscriptions/azureUsageContext", "method": "GET"}, "response": { "status": 404, "bodyFileName": "swatch-2099.json", "headers":{"Content-Type":"application/json"} }}' http://localhost:8101/__admin/mappings/new
```
3. Insert remittance data to be updated:
`INSERT INTO …
> SWATCH-2100: Create consumer of billable usage dead letter messages

- swatch-common-kafka/src/main/java/com/redhat/swatch/kafka/EmitterService.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
- swatch-metrics/src/main/resources/application.yaml
Jira issue: [SWATCH-2162](https://issues.redhat.com/browse/SWATCH-2162)
This solution has been agreed with Clement (the maintainer of the Quarkus messaging extensions). He suggested to use the emitter.hasRequests method to be sure the broker can handle more messages. The hasRequests works like a capacity barrier: when we send up to 1024 messages (1024 is the default value) without getting an ack from the broker, we wait until sending more messages).
Update: there seems to be two upper limits, (1) the one configured by the `max-inflight-messages` which is the one used by the `hasRequests` method and default value is 1024; and (2) the buffer limit which is used by the overflow strategy and default value is 128. Therefore, for this solution to work, we need to set the `max-inflight-messages` …
> SWATCH-2162: Send metrics using backpressure mecanisms into Kafka

- swatch-producer-aws/build.gradle
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/processors/BillableUsageProcessor.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/processors/AwsUsageContextLookupApiTest.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/test/resources/WireMockResource.java
We made some tweaks to the API definition at some point and that resulted in the generated method having a different parameter order.
Testing
-------
See `AwsUsageContextLookupApiTest`
> Fix parameter order for getAwsUsageContext

- docker-compose.yml
- pg_hba.conf
- postgresql.conf
This makes it more convenient for development, as the password doesn't need to be specified.
Note: I also updated the port mappings to use only the localhost interface. Generally, firewalls prevent external access, but it felt like a good related improvement.
You'll need to re-provision the database container to get this to work, so backup and restore DB data if you wish.
> Change compose setup to not require postgres password

- swatch-metrics/src/main/java/com/redhat/swatch/metrics/configuration/MetricProperties.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
- swatch-metrics/src/main/resources/application.yaml
Jira issue: [SWATCH-2066](https://issues.redhat.com/browse/SWATCH-2066)
- The property `throttled.unprocessed-record-max-age.ms` needs to be synced with the retry configuration which will retry up to 3 times with a max duration of 120 seconds, so the correct value would be 3 x 120 = 360 seconds for this property
- Change the failure strategy since, by default, when a message is nack, the application stops consuming messages. With the "ignore" strategy, we ignore the error (it's logged internally) and continue processing messages.
- Remove some unused properties in the metrics service
Relates to https://github.com/RedHatInsights/rhsm-subscriptions/pull/3019
> SWATCH-2066: Synchronize the timeout for metrics task messages with the `@Retry` configuration

- .github/workflows/validate-floorplan-queries.yaml
- dependencies.gradle
- pr_check.sh
Jira issue: [SWATCH-2089](https://issues.redhat.com/browse/SWATCH-2089)
Bumps [com.netflix.nebula:nebula-release-plugin](https://github.com/nebula-plugins/nebula-release-plugin) from 18.0.8 to 19.0.4. 
This is related to this change: https://github.com/nebula-plugins/nebula-release-plugin/pull/253
Therefore, we need to configure the user we use in our actions before running the build. 
I also tried to do this as part of a gradle task, but they are running the verification of the git user as part of the release initial task, so we can't configure it. 
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/nebula-plugins/nebula-release-plugin/releases">com.netflix.nebula:nebula-release-plugin's releases</a>.</em></p> <blockquote>
<h2>v19.0.4</h2>
<ul> …
> SWATCH-2089: Bump com.netflix.nebula:nebula-release-plugin from 18.0.8 to 19.0.4

- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
Jira issue: SWATCH-2158
Before this change, the remittance accumulation_period was getting set to the current YYYY-MM, but should have been the month of the incoming usage snapshot.
When performing a re-tally, existing remittance was being determined based on the month of the snapshot, however, was getting recorded in the DB as the current month. This would result in new remittance getting created, and being billed for, every time a re-tally was run that was missing remittance in a past month.
Insert an event into the DB.
```
INSERT INTO public.events VALUES ('3588f50a-9014-4d6a-b542-566717398ade', '2023-12-29 15:00:00-04', '{"sla": "Premium", "role": "osd", "org_id": "org123", "event_id": "3588f50a-9014-4d6a-b542-566717398ade", "timestamp": "2023-12-29T19:00:00+00:00", "event_type": …
```
> SWATCH-2158: Set the usage date to now after remittance is created

- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingController.java
- src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingResource.java
- src/main/resources/liquibase/202402051200-add-id-and-hardware-columns-to-billable_usage_remittance-table.xml
- src/main/resources/liquibase/changelog.xml
- src/main/spec/internal-billing-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntity.java
- swatch-tally/deploy/clowdapp.yaml
Jira issue: [SWATCH-2101](https://issues.redhat.com/browse/SWATCH-2101)
- Query billable_usage_remittance for retry_after > as_of (and non_null) Produce kafka message onto
- platform.billable_usage again Clear retry_after column in the table
- cron job to call the api every 1 hr
2. start tally service: `./gradlew :bootRun`
3. insert billable usage remittance:
INSERT INTO billable_usage_remittance(org_id, product_id, metric_id, accumulation_period, sla, usage, billing_provider, billing_account_id, remittance_pending_date, retry_after, remitted_pending_value)
VALUES ('org123', 'rosa', 'CORES', '2024-02', 'Premium', 'Production', 'azure', '123456', '2024-02-11T04:00:09.620406Z', '2023-12-11T04:00:09.620406Z', '4.0')
4. invoke new endpoint:
```
http POST …
```
> SWATCH-2101: Retry processing billable_usage's with retry_after field populated

- clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
- swatch-system-conduit/schemas/inventory/hbi-host.yaml
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/ProviderFact.java
- swatch-system-conduit/src/main/spec/internal-organizations-sync-api-spec.yaml
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java
Jira issue: [SWATCH-1998](https://issues.redhat.com/browse/SWATCH-1998)
If this is an aws/azure/gcp instance
Canonical facts include: provider_id and provider_type
- provider_id is set to the aws_instance_id/azure_instance_id/gcp_instance_id
- provicer_type is set to aws/azure/gcp depending on whichever is appropriate. 
0.- Start Kafka
`podman-compose up`
1.- Run conduit app with stubs
`RHSM_USE_STUB=true DEV_MODE=true ./gradlew :swatch-system-conduit:bootRun`
2.- Sync organization:
`http :8000/api/rhsm-subscriptions/v1/internal/rpc/syncOrg   x-rh-swatch-psk:placeholder   org_id=org123`
3. Check the message that has been sent to Kafka in http://localhost:3030/#/cluster/default/topic/n/platform.inventory.host-ingress/ .
The stub is configured to add number of cpus to 3 and threads per core …
> SWATCH-1998: conduit - report provider_type & provider_id to HBI

- swatch-metrics/deploy/clowdapp.yaml
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
- swatch-metrics/src/main/resources/application.yaml
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/admin/api/MetricsTest.java
Jira issue: [SWATCH-2192](https://issues.redhat.com/browse/SWATCH-2192)
Configure swatch-metrics to expose the metrics endpoint via the path "/metrics" instead of "/q/metrics" on port 9000 as in Spring services. Note that this implies that the health check endpoints changed as well. 
Moreover, we have added a new gauge metrics to count the number of events fetched from prometheus.
This will be tested in stage.
> SWATCH-2192: Not using the path "/q" for swatch metrics ++ add gauge events counter

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
Jira issue: [SWATCH-2203](https://issues.redhat.com/browse/SWATCH-2203)
In https://github.com/RedHatInsights/rhsm-subscriptions/pull/2905 we changed how to resolve the offering product tags. Before, we were using the product name to get the linked product tags. After these changes, we started using the offering role AND/OR the offering eng IDs. However, it seems that this change was not aligned with the upstream offering data where offerings were missing both role and eng IDs. 
Therefore, we need to keep using the product name when the offering is missing the role and the eng IDs to not break the contract ingestion. 
2.- DEV_MODE=true SPRING_PROFILES_ACTIVE=worker ./gradlew :bootRun
3.- Create offering:
`INSERT INTO …
> SWATCH-2203: Get product tags by product name when no role or eng ids

- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
Jira issue: [SWATCH-2104](https://issues.redhat.com/browse/SWATCH-2104)
During investigation for [BIZ-654](https://issues.redhat.com/browse/BIZ-654), I discovered that ROSA HCP clusters appear to be half-sized when counted via cluster:usage:workload:capacity_physical_cpu_hours. cluster:usage:workload:capacity_virtual_cpu_hours values look fine though.
Note for QE to use cluster:usage:workload:capacity_virtual_cpu_hours.
> SWATCH-2104: Change metric for ROSA HCP

- swatch-metrics/README.md
- swatch-metrics/src/main/resources/application.yaml
Jira issue: SWATCH-2153 rhel-meter promql
Human explanation of the new query can be found here: `swatch-metrics/README.md`
Previous decision:
We've opted to not use the recording rule for two reasons.  First, it was only further complicating an already complicated promql query.  Second, we get more accurate data by not using it.  When we requested a recording rule to be made, we expected that its evaluation would happen the same frequency as the openshift telemeter instance.  Since that's not going to be the case, using a recording rule doesn't benefit us much. 
**Note:** After talking with the RHOBS team, it will be advantageous to have a recording rule in the long run for performance-related reasons. So later on, we will collaborate with them. Using the query in PR we also don't need to …
> SWATCH-2153 Metrics gathering for rhel telemetry had duplicate data

- swatch-metrics/src/main/java/com/redhat/swatch/metrics/configuration/MetricProperties.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
- swatch-metrics/src/main/resources/application.yaml
Jira issue: [SWATCH-2066](https://issues.redhat.com/browse/SWATCH-2066)
These changes are causing a severe lag in the metering task topic:
> Revert changes for SWATCH-2066

- swatch-contracts/src/main/java/com/redhat/swatch/contract/config/DebugClientLogger.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/exception/ContractNotAssociatedToOrgException.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/exception/ContractValidationFailedException.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/AzureContractLifecycleIntegrationTest.java
Jira issue: [SWATCH-2206](https://issues.redhat.com/browse/SWATCH-2206)
Description
===========
In order to handle transient issues with the data coming back from the partner gateway API, as well as provide debug logging to assist the partner gateway engineers in debugging issues.
Note that I added a custom debug logger `DebugClientLogger` that can be configured to log the request and response bodies. See comments in `application.properties` for details. (It's configured for partnerEntitlement requests for `dev`, `test`, and `stage` profiles only).
I changed the contract entity validation to use hibernate validator, to get better messages about which fields are missing. (Each failed field is now logged at a `WARN` level).
I tweaked the API enrichment so that if the contract fails …
> SWATCH-2206: Add retries/debug logs to Partner Gateway processing

- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/prometheus/PrometheusService.java
- swatch-metrics/src/main/resources/application.yaml
To find out what is causing the swatch metrics to became stuck, we need to add some debug traces with the requests and response from the Prometheus call. 
With these changes, we would see the requests:
```
2024-02-12 17:02:54,770 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-0) Request: GET http://localhost:38795/query_range?query=max%28cluster%3Ausage%3Aworkload%3Acapacity_physical_cpu_hours%29+by+%28_id%29+*+on%28_id%29+group_right+min_over_time%28ocm_subscription%7Bproduct%3D%22ocp%22%2C+external_organization%3D%22account%22%2C+billing_model%3D%22marketplace%22%2C+support%3D~%22Premium%7CStandard%7CSelf-Support%7CNone%22%7D%5B1h%5D%29&start=1707757200&end=1707840174&step=3600&timeout=10000 Headers[Accept=application/json User-Agent=Resteasy Reactive …
```
> Add debug traces for Prometheus requests/responses for swatch-metrics

- .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml
- README.md
Jira issue: SWATCH-1339
- Created new dashboard named "Event ingestion"
- Added new panel with title "service instance ingress consumer group lag"
- Moved OpenShift Metering Task Lag and Rhelemeter Metering Task Lag panels to the new dashboard since I think both are more related to the event ingestion
On grafana stage, extract the JSON from the k8s configmap file:
```
oc extract -f .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml --confirm
```
Once you extract it from the .yaml that's checked into this repo, you can import it into the stage instance of grafana by going to `Dashboards -> +Import` from the left nav.
> SWATCH-1339: Create dashboard for service-instance-ingress consumer

- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/prometheus/PrometheusService.java
- swatch-metrics/src/main/resources/application.yaml
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/resources/PrometheusQueryWiremock.java
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
Jira issue: [SWATCH-2066](https://issues.redhat.com/browse/SWATCH-2066)
Sometimes prometheus returns an empty string with HTTP OK status:
```
REQUEST:
2024-02-13 01:30:42,178 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-1) Request: GET http://localhost:8082/query_range?query=max%28cluster%3Ausage%3Aworkload%3Acapacity_physical_cpu_hours%29+by+%28_id%29+*+on%28_id%29+group_right+min_over_time%28ocm_subscription%7Bproduct%3D%22moa-hostedcontrolplane%22%2C+external_organization%3D%223949694%22%2C+billing_model%3D%22marketplace%22%2C+support%3D~%22Premium%7CStandard%7CSelf-Support%7CNone%22%7D%5B1h%5D%29&start=1707786000&end=1707786000&step=3600&timeout=10000 Headers[Accept=application/json User-Agent=Resteasy Reactive Client], Empty body
RESPONSE:
2024-02-13 …
```
> SWATCH-2066: Gracefully fail when prometheus returns empty body

- swatch-metrics/README.md
- swatch-metrics/src/main/resources/application.yaml
Jira issue: SWATCH-2135
The use case is an instance reported a metric with a support label of "Premium", but later started reporting metrics without having the support label set.  Those later metrics weren't returned by the promql, resulting in swatch not counting any usage for that instance anymore.
Prometheus treats an unset label the same as an empty string.  Adding a `|` at the end of the support regex will make the query return results when there isn't a support label set.  When the support label is unset, it should that usage should default to "Premium", as defined in the rhel-for-x86-els-payg product config yaml.
To inspect/verify the generated query, you can use the metering-promql script and then change the 204 to 69 in the output.
```
./bin/metering-promql.py --product …
```
> SWATCH-2135: Update promql to return metrics when support label is unset

- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/util/MeteringEventFactoryTest.java
Jira issue: [SWATCH-2031](https://issues.redhat.com/browse/SWATCH-2031)
When data is sourced from prometheus the "display_name" label is used to populate an event's display_name, if present
2.- start the tally service: ./gradlew :bootRun
3.- Mock the prometheus server at localhost:
Create the stub directory:
`mkdir -p stub/__files`
Add a stub file to return some data: `stub/__files/swatch-2031.json`
```
cat > stub/__files/swatch-2031.json <<EOF
{
"status" : "success",
"data" : {
"resultType" : "matrix",
"result" : [
{
"metric" : {
"_id" : "cluster id",
"support" : "sla",
"usage" : "usage",
"product" : "product",
"billing_marketplace" : "billing_marketplace",
"billing_marketplace_account" : "billing_marketplace_account",
"ebs_account" : "account",
"display_name": "the …
```
> SWATCH-2031: Get the events.display_name from labels in prometheus ingestion

- config/splunk/docker-compose.yml
Jira issue: No issue
The Splunk podman compose wasn't working because of an indentation error.
1. Run the container:
```
podman-compose -f config/splunk/docker-compose.yml up
```
1.  Container runs successfully
> Correct indentation error in Splunk podman-compose

- build.gradle
- clients-core/src/main/java/org/candlepin/subscriptions/http/HttpClient.java
./gradlew -Dhttp.proxyHost=localhost  -Dhttp.proxyPort=8080 :bootRun
This will allow you to start up a tool (like mitmproxy) and inspect the API requests the application in making for debugging.
> Support using a proxy to inspect swatch api client requests

- bin/insert-mock-hosts
- src/main/java/org/candlepin/subscriptions/inventory/db/InventoryRepository.java
- src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
- src/test/java/org/candlepin/subscriptions/inventory/db/InventoryRepositoryIT.java
- swatch-system-conduit/schemas/inventory/hbi-system-profile.yaml
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
- swatch-system-conduit/src/main/spec/internal-organizations-sync-api-spec.yaml
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
Jira issue: [SWATCH-1929](https://issues.redhat.com/browse/SWATCH-1929)
Add support for the recently added system profile fact virtual_host_uuid (https://github.com/RedHatInsights/inventory-schemas/pull/121) which replaces legacy facts rhsm.VM_HOST_UUID.
2.- Create hosts for orgId=16790890 in Insights database
```
./bin/insert-mock-hosts --hbi --clear --org 16790890 --account account123 --num-guests 1 --hypervisor-id 123456
```
3.- DEV_MODE=true SUBSCRIPTION_SYNC_ENABLED=true ENABLE_SYNCHRONOUS_OPERATIONS=true ./gradlew :bootRun
4.- Perform tally snapshot:
```bash
http PUT ":8000/api/rhsm-subscriptions/v1/internal/rpc/tally/snapshots/16790890" \
Origin:console.redhat.com \
x-rh-swatch-synchronous-request:true \
x-rh-identity:$(echo -n …
```
> SWATCH-1929: Replace rhsm.VM_HOST_UUID by system profile.virtual_host_uuid

- .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml
Jira issue: SWATCH-2102
This adds a panel to Grafana to measure the task lag in the `platform.rhsm-subscriptions.billable-usage.dlt` topic.
I'm not really aware of a way to test this. :frowning_face:
> Add Grafana panel to measure billable usage dead letter topic lag

- swatch-system-conduit/schemas/inventory/hbi-host.yaml
Jira issue: [SWATCH-2201](https://issues.redhat.com/browse/SWATCH-2201)
This property is no longer used since we swichted over account to org_id.
2.- RHSM_USE_STUB=true ./gradlew :swatch-system-conduit:bootRun
3.- add host to the inventory database:
```
VALUES ('e5406d59-5cf3-4e83-abf8-84c149f8b6ba', 'account123', 'd125f119-0c98-43f2-a5de-ccf2e8e1ab55', '1993-03-26 00:00:00.000000 +00:00', '1993-03-26 00:00:00.000000 +00:00', '{"rhsm": {"orgId": "org123", "IS_VIRTUAL": null, "VM_HOST_UUID": null}}', null, '{"insights_id": "d125f119-0c98-43f2-a5de-ccf2e8e1ab55", …
```
> SWATCH-2201: Remove the property `account` from the hbi-host schema

- swatch-contracts/deploy/clowdapp.yaml
- swatch-contracts/src/main/java/com/redhat/swatch/contract/config/UmbConfiguration.java
- swatch-contracts/src/main/resources/application.properties
- swatch-subscription-sync/deploy/clowdapp.yaml
Jira issue: SWATCH-1044
The changes to the ephemeral environment base have already been merged, so doing a standard deployment of swatch-contracts to the ephemeral environment should be sufficient to use the new keystore and client certificate.
> SWATCH-1044: Use a separate client certificate for the UMB in the ephemerals

- README.md
- src/main/resources/application-api.yaml
- src/main/resources/application-capacity-ingress.yaml
- src/main/resources/application-rh-marketplace.yaml
- src/main/resources/application-worker.yaml
- swatch-core/build.gradle
- swatch-core/src/main/java/org/candlepin/subscriptions/clowder/ClowderJson.java
- swatch-core/src/main/java/org/candlepin/subscriptions/clowder/ClowderJsonPathPropertySource.java
- swatch-core/src/test/java/org/candlepin/subscriptions/clowder/ClowderJsonEnvironmentPostProcessorTest.java
- swatch-core/src/test/java/org/candlepin/subscriptions/clowder/ClowderJsonPathPropertySourceTest.java
- swatch-core/src/test/resources/test-clowder-config.json
- swatch-metrics/src/main/resources/application.yaml
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
- swatch-system-conduit/src/main/resources/application.yaml
Jira issue: SWATCH-2063
- Uses directly the JsonNode from jackson.
- Replace `${clowder.endpoints[?(@.app == 'rbac')].hostname` to `${clowder.endpoints.rbac-service.url}`
- Replace `${clowder.kafka.topics[?(@.requestedName == 'platform.rhsm-subscriptions.offering-sync')].name}` to `${clowder.kafka.topics."platform.rhsm-subscriptions.offering-sync".name}`
> SWATCH-2063: Remove json-path dependency

- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractRepository.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Jira issue: SWATCH-2226
**Note: Please only run `syncContractsByOrg` endpoint since we want to only run by org first and make sure the sync and its results are okay on prod.** 
It is best to directly to connect with prod and modify some of these data to test against prod. However I will be doing my best to put some wiremock based steps but, reviewer has to be innovative to test it with mocking.
**offering:**
`INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku, metered) VALUES ('MW02393', 'OpenShift Online', 'OpenShift Enterprise', null, null, null, null, '', 'Premium', '', 'Red Hat OpenShift Service on AWS Hosted Control Planes (Hourly)', false, '', true);
` …
> SWATCH-2226 syncContractByOrgId should sync all contracts

- src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
- src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
- src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
- src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
- src/test/java/org/candlepin/subscriptions/inventory/db/InventoryRepositoryIT.java
Jira issue: [SWATCH-2144](https://issues.redhat.com/browse/SWATCH-2144)
Given systems in HBI from any known provider type, after tally, calling `/instances/products/RHEL for x86` should return the appropriate cloud-provider instance ID in the `data.*.instance_id` field.
Note that these changes introduce a breaking change where before the instance ID was the inventory ID and now it's the provider ID. 
2.- Add host to Insight DB:
```
VALUES ('e5406d59-5cf3-4e83-abf8-84c149f8b6ba', 'account123', 'd125f119-0c98-43f2-a5de-ccf2e8e1ab55', '1993-03-26 00:00:00.000000 …
```
> SWATCH-2144: Populate cloud provider instance IDs from HBI when possible

- swatch-contracts/src/main/resources/application.properties
- swatch-metrics/src/main/resources/application.yaml
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
By default, Quarkus does not print any traces when the service rejects a bad request. With this change, we'll print a trace when a request is rejected and the reason.
2. ./gradlew liquibaseUpdate
3. start the contract service:
```
./gradlew :swatch-contracts:quarkusDev
```
4. send an invalid request:
```
curl -v -X POST -H "Content-Type: application/json" -H "Origin: https://cloud.redhat.com" -H "x-rh-swatch-psk: placeholder" --data "{\"subscription_number\": \"895871\", \"sku\": \"MW02393\", \"start_date\": \"2024-03-05T12:27:51Z\", \"org_id\": 123456, \"billing_provider\": \"aws\", \"billing_account_id\": \"nikhil\", \"product_id\": \"rosa\", \"vendor_product_code\": \"03c87bf4-5f9e-49b1-b107-1283270e78af\", \"metrics\": false}" …
```
> Print logs after bad requests in Quarkus services

- clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
- swatch-system-conduit/deploy/clowdapp.yaml
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/rhsm/RhsmService.java
- swatch-system-conduit/src/main/resources/application.yaml
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/rhsm/RhsmServiceTest.java
Jira issue: [SWATCH-2214](https://issues.redhat.com/browse/SWATCH-2214)
After digging into the RateLimiter, I see a couple of disadvantages to limit / contain the RHSM API calls:
1. We did set the limit of calls to 150, but at the same time, this limit is reset every 100 milliseconds, so the limit is too permisive and likely it will ever be reached out.
2. We can't increase the limitRefreshPeriod property to a higher value because we would be too strict and the RateLimiter does not allow to decrement the counter to permit more calls. 
Therefore, I agree with the reporter of SWATCH-2214 that the bulkhead pattern matches better for the purpose of not exhaust the RHSM services. 
This PR replaces the env vars from https://github.com/RedHatInsights/rhsm-subscriptions/pull/2010 with:
* …
> SWATCH-2214 Switch from RateLimiter to BulkLimiter when calling RSHM API

- src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
- src/main/java/org/candlepin/subscriptions/tally/job/CaptureSnapshotsTaskManager.java
- src/main/spec/internal-tally-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/TaskConsumerConfiguration.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/inmemory/ExecutorTaskQueueConfiguration.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskProducerConfiguration.java
Jira issue: [SWATCH-2195](https://issues.redhat.com/browse/SWATCH-2195)
Currently when we are trying to run hourly tally operation on large orgs with synchronous_request: true, we are seeing 504 Server Error: Gateway Time-out for url. We just need a way to skip queues and not to wait for response till operation finish to avoid 504 gateway timeouts.
The idea is to reuse the executor task queue that was in place along with the kafka task queue.  Before these changes, only one task queue was started (when using the kafka-queue profile, it was reading tasks from the topic). After these changes, the in memory task queue will always be started and will be used when running the hourly tally operation when the header "x-rh-swatch-use-thread-pool-executor:true" is provided.
2. …
> SWATCH-2195: Do not wait for hourly tally operation to finish when synchronous_request is true

- swatch-system-conduit/deploy/clowdapp.yaml
- swatch-system-conduit/src/main/resources/application.yaml
Jira issue: [SWATCH-2214](https://issues.redhat.com/browse/SWATCH-2214)
The Spring Retry is configured to perform up to 10 attempts the RHSM API. Plus, the Kafka consumer timeout is configured to 30 min. 
The problem is that in https://github.com/RedHatInsights/rhsm-subscriptions/pull/3126 we configured the RHSM API timeout to be 30 min. So, if one single call hangs up to 30 min, we won't retry and the Kafka consumer will have already rejected the message from the topic.
Therefore, we need to configure the max wait duration to 3 min, so we can meet the 10 number of attempts, and also the kafka timeout which is 30 min. With these changes, when the RHSM API is unresponsive, we will do the following attempts:
```
1. at 0
2. at 3min 1sec
2. at 6min 3sec
3. at 9min 7sec
4. at 12min 15sec
5. at …
```
> SWATCH-2214: Adjust timeout with the kafka consumer timeout and retry

- src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
- src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
- src/main/resources/product-stub-data/engprods-SKU00790.json
- src/main/resources/product-stub-data/tree-SKU00790_attrs-true.json
- src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/OpenShift_Container_Platform.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/Satellite_Capsule.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/Satellite_Server.yaml
JIRA ticket: [SWATCH-1896](https://issues.redhat.com/browse/SWATCH-1896)
With new RHEL add-ons configs, We need to update includedSubscriptions from OpenShift Container Platform  and Satellite products to include new rhel ELS/HA/RS add-ons.
I've added a test case that covers these changes. The test case and functionality must be reviewed.
Steps for manual testing (the automatic test case mimics the below steps):
2.- start service using stubs:
```
PRODUCT_USE_STUB=true SUBSCRIPTION_USE_STUB=true DEV_MODE=true ./gradlew :bootRun
```
Note that as part of these changes, I've added a stub that includes an orgId 790 with two products: 290 (openshift-container-platform) and 70 (rhel-for-x86-eus).
3.- Synchronize the org ID:
```
http PUT …
```
> SWATCH-1896: exclude RHEL rhel ELS/HA/RS from OpenShift and Satellite

- swatch-system-conduit/deploy/clowdapp.yaml
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/SystemConduitProperties.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResource.java
- swatch-system-conduit/src/main/resources/application.yaml
- swatch-system-conduit/src/main/spec/internal-organizations-sync-api-spec.yaml
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResourceTest.java
Jira issue: [SWATCH-2214](https://issues.redhat.com/browse/SWATCH-2214)
We will allow to enable a synchronous operation to sync the organization by skipping the Kafka queue by running the swatch conduit with ENABLE_SYNCHRONOUS_OPERATIONS=true, plus adding our standard "x-rh-swatch-synchronous-request" header when calling "/internal/rpc/syncOrg" endpoint.
Added unit tests to cover this change.
> SWATCH-2214: Synchronize orgs in conduit using tasks

- .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml
Jira issue: [SWATCH-2026](https://issues.redhat.com/browse/SWATCH-2026)
- Added library for Export Requests
- Added a couple of panels for export task lag for swatch-tally and swatch-subscription-sync 
- Added a couple of panels for max duration message consumption for swatch-tally and swatch-subscription-sync
On grafana stage, extract the JSON from the k8s configmap file:
```
oc extract -f .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml --confirm
```
Note that you need to be logged into a OCP cluster.
Once you extract it from the .yaml that's checked into this repo, you can import it into the stage instance of grafana by going to `Dashboards -> +Import` from the left nav.
> SWATCH-2026: Add a grafana dashboard for export requests

- src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/product/OfferingWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerConfiguration.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaConfigurator.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskProducerConfiguration.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/kafka/InventoryServiceKafkaConfigurator.java
Jira issue: [SWATCH-2329](https://issues.redhat.com/browse/SWATCH-2329)
Replace `buildProducerProperties()` by `buildProducerProperties(null)` and `buildConsumerProperties()` by `buildConsumerProperties(null)`.
> SWATCH-2329 Replace the deprecated methods in KafkaProperties

- src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
Jira issue: SWATCH-2244
Allow filtering based on billing provider in calls to `subscriptions/products/<product_id>`
1.  Sync offerings from stage.  You can create the offerings yourself, but it's easier to just pull the stage data.  You'll need to have the keystore and truststore for the stage subscription endpoint along with the password.  You'll also need the stage subscription endpoint.  I can provide all those or you can retrieve them from the `api` pod's environment (`SUBSCRIPTION_URL`) and Vault (`/insights/show/secrets/insights-stage/rhsm-stage/pinhead` and `/insights/show/secrets/insights-stage/rhsm-stage/tls` for the password).
```
http PUT :8000/api/rhsm-subscriptions/v1/internal/rpc/offerings/sync x-rh-swatch-psk:placeholder
```
1.  Create (or find) an org with subscriptions …
> Add billing provider to filterable parameters for subscription resource

- pr_check.sh
Replace hardcoded list of components with a command to derive them based on clowdapp.yaml files found in the repo
> Replace hardcoded list of bonfire components in pr_check.sh

- src/main/java/org/candlepin/subscriptions/ApplicationConfiguration.java
- src/main/java/org/candlepin/subscriptions/capacity/CapacityIngressConfiguration.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceConfiguration.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/subscription/export/ExportClientConfiguration.java
- src/main/java/org/candlepin/subscriptions/subscription/export/ExportSubscriptionConfiguration.java
- src/main/java/org/candlepin/subscriptions/subscription/export/ExportSubscriptionListener.java
- src/main/resources/application.yaml
- src/test/java/org/candlepin/subscriptions/subscription/export/ExportSubscriptionListenerTest.java
- src/test/java/org/candlepin/subscriptions/test/ExtendWithEmbeddedKafka.java
- src/test/java/org/candlepin/subscriptions/test/ExtendWithExportServiceWireMock.java
Jira issue: [SWATCH-2021](https://issues.redhat.com/browse/SWATCH-2021)
Part of SWATCH-2021, we need to move all the export related classes into the same package.
> SWATCH-2021: Move export related classes into the same package

- src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
- src/test/java/org/candlepin/subscriptions/retention/TallyRetentionControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
Instead of doing 6 queries per organization, it will only do 6 queries in total for all organizations.
Jira issue: [SWATCH-2330](https://issues.redhat.com/browse/SWATCH-2330)
Before these changes, a timeout exception is thrown when the purge task takes more than one hour (see splunk query in the linked JIRA).
Checking the orgs in Prod, we have 53231 organizations, and for each organization, we run a query to delete the tally snapshots by variant (we have 6 variants - daily, hourly, etc). According to the explain analysis ran by Postgresql, the query to delete the tally snapshots is quite fast: around 100ms (more or less).
Therefore, doing some maths: 53231 (orgs) x 6 (variants) x 100ms (average time taken to execute the query) = 31938600 ms to complete the task which is 8.8 hours.
Of …
> SWATCH-2330: Reduce the number of queries to purge the tally snapshots

- dependencies.gradle
Jira issue: [SWATCH-2366](https://issues.redhat.com/browse/SWATCH-2366)
The following dependencies are declared in gradle individually:
org.jboss.resteasy:resteasy-multipart-provider
org.jboss.resteasy:resteasy-client
org.jboss.resteasy:resteasy-validator-provider
org.jboss.resteasy:resteasy-jackson2-provider
So, when a new version of resteasy is released, dependabot creates four pull requests for each one.
Unify the resteasy dependencies to use a single property `resteasyVersion` to declare the resteasy version.
> SWATCH-2366: Unify resteasy dependencies into one single property

- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/main/resources/product-stub-data/engprods-MW02164HR.json
- src/main/resources/product-stub-data/tree-MW02164HR_attrs-true.json
- src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
Jira issue: SWATCH-2345
Description
===========
When swatch applies an event to a host record, one of the things it does is update the tally buckets
associated to that host. However, the changes for hourly tally are only additive (compared to the
nightly tally).
The effect is that a system counts towards buckets it should not, and a system's usage gets included
in buckets it shouldn't.
For example, if the billing account id changes, it counts towards both the old billing account ID
and the new one.
To address, I updated the logic to remove buckets that no longer apply.
I also added stub data for RHACS, since that was in the example that Nikhil provided for iqe steps.
Testing
=======
Setup
-----
Run the monolith on port 8000:
```shell
DEV_MODE=true PRODUCT_USE_STUB=true …
```
> SWATCH-2345: Remove stale host buckets during hourly tally

- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/main/resources/product-stub-data/engprods-MW02164HR.json
- src/main/resources/product-stub-data/tree-MW02164HR_attrs-true.json
- src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
NOTE: Same as #3167 but for hotfix branch.
Jira issue: [SWATCH-2345](https://issues.redhat.com/browse/SWATCH-2345)
Description
===========
When swatch applies an event to a host record, one of the things it does is update the tally buckets associated to that host. However, the changes for hourly tally are only additive (compared to the nightly tally).
The effect is that a system counts towards buckets it should not, and a system's usage gets included in buckets it shouldn't.
For example, if the billing account id changes, it counts towards both the old billing account ID and the new one.
To address, I updated the logic to remove buckets that no longer apply.
I also added stub data for RHACS, since that was in the example that Nikhil provided for iqe steps.
Testing
=======
Setup
-----
Run …
> [HOTFIX] SWATCH-2345: Remove stale host buckets during hourly tally

- src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/tasks/EnabledOrgsMessageConsumer.java
- src/main/resources/application-worker.yaml
- src/test/java/org/candlepin/subscriptions/tally/tasks/EnabledOrgsMessageConsumerTest.java
- src/test/java/org/candlepin/subscriptions/test/ExtendWithEmbeddedKafka.java
- swatch-core/schemas/enabled_orgs_request.yaml
- swatch-core/schemas/enabled_orgs_response.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: [SWATCH-2276](https://issues.redhat.com/browse/SWATCH-2276)
Expose the OrgConfigRepository.findSyncEnabledOrgs via Kafka topics.  Added request/response model in swatch-core that will also be used by the swatch-contracts service.
1. start kafka and rest of the services
2. start the tally service:
```
DEV_MODE=true SPRING_PROFILES_ACTIVE=worker ./gradlew :bootRun
```
3. send request to the topic: `platform.rhsm-subscriptions.enabled-orgs-for-tasks`:
```
{"target_topic": "wrong"}
```
4. verify this message is ignored because the target topic is invalid
you should see the following trace in the tally service logs:
```
2024-03-22 10:30:32,560 [thread=rhsm-subscriptions-enabled-orgs-processor-0-C-1] [WARN ] [org.candlepin.subscriptions.tally.tasks.EnabledOrgsMessageConsumer] - …
```
> SWATCH-2276: Expose the OrgConfigRepository.findSyncEnabledOrgs

- .github/workflows/validate-floorplan-queries.yaml
- docker-compose.yml
- swatch-common-testcontainers/src/main/java/org/candlepin/testcontainers/SwatchPostgreSQLContainer.java
Jira issue: SWATCH-2387
The `latest` tag was removed on this container as the container image is no longer maintained.  The patch adds the `centos7` tag as a stop-gap until we can upgrade.
This issue is what's causing the floorist query validation task to fail.
1. **Be sure you are willing to destroy your database**.  Do a `pg_dump` if you are not so you can import later.
1. `podman-compose down`
1. `podman-compose up -d`
1.  You'll see the `quay.io/centos7/postgresql-12-centos7:centos7` image get pulled.
> SWATCH-2387: Update tag on postgresql-12-centos7 database

- api/rhsm-subscriptions-api-spec.yaml
- src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
- src/main/resources/liquibase/202403260830-update-instance-view-to-include-inventory-id.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceView.java
Jira issue: [SWATCH-2326](https://issues.redhat.com/browse/SWATCH-2326)
In SWATCH-2144, we changed the existing instance_id from inventory_id to the actual provider id. However, the UI was using this instance_id to build up the link to the inventory service. So, we need to provide the inventory_id, so the UI can continue building this url.
MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/621
> SWATCH-2326: include the inventory_id in the instances report

- swatch-contracts/src/main/resources/application.properties
- swatch-metrics/src/main/resources/application.yaml
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
The tests all contend over the same port during parallel testing and test failures result.  This patch just disables the separate management port during testing so the tests aren't squabbling amongst each other.
Jira issue: SWATCH-2390
The tests fail when running in parallel because of resource contention over port 9000.
1. Run `./gradlew test` on the `main` branch
1. Run `./gradlew test` on this branch
1.  On `main` the tests will fail and you'll see a message like 
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Unable to start HTTP server
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unable to start the …
```
> SWATCH-2390: Disable separate Quarkus management port during testing

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/VariantTest.java
Jira issue: SWATCH-1957
We were using product name earlier that was causing issue when we were creating aws usage context. This code removes the use of product name and uses product tag instead.
1. Create offering
2. Add rosa subscription
3. Create rosa event
4. Sync hourly tally
5. Check for usage
1. 
`INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku, metered) VALUES ('MW02393', 'OpenShift Online', 'OpenShift Enterprise', null, null, null, null, null, 'Premium', '', 'Red Hat OpenShift Service on AWS Hosted Control Planes (Hourly)', false, null, true);`
`INSERT INTO public.sku_product_tag (sku, product_tag) VALUES ('MW02393', 'rosa');`
`INSERT INTO …
> SWATCH-1957 Remove use of product name while emitting usage

- swatch-core/schemas/tally_snapshot.yaml
Partially reverts https://github.com/RedHatInsights/rhsm-subscriptions/pull/3154 that added a duplicated "metric_id" property.
> Fix tally_snapshot.yaml to remove duplicated metric_id property

- pr_check.sh
- swatch-billable-usage/deploy/clowdapp.yaml
Jira issue: [SWATCH-2285](https://issues.redhat.com/browse/SWATCH-2285)
- copy the swatch-producer-azure service into the new swatch-billable-usage service
- this is necessary to prepare the deployment of the new service in the ephemeral/stage/prod environments
> SWATCH-2285: Add swatch-billable-usage deployment

- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapper.java
- src/main/java/org/candlepin/subscriptions/tally/billing/BillingUnit.java
- src/main/java/org/candlepin/subscriptions/tally/billing/ContractsController.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapperTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/ContractsControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/QuantityTest.java
- swatch-core/schemas/billable_usage.yaml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceFilter.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/kafka/BillableUsageAggregateKey.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/kafka/streams/BillableUsageAggregateKey.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageAggregateConsumer.java
Jira issue: SWATCH-2317
The UOM field is no longer needed as it is redundant to the metric id field
The CI test test_verify_remittance_of_metered_product in IQE will cover this change 
1. Ensure the above test in specific and the  entire suite in general run successfully
> SWATCH-2317: Move use of UOM to MetricId in tally

- dependencies.gradle
- swatch-product-configuration/build.gradle
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Defaults.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Jira issue: [SWATCH-2038](https://issues.redhat.com/browse/SWATCH-2038)
Dependabot stopped bumping Quarkus a while ago because the Quarkus gradle plugin dependency stopped being published at the Maven plugin site, but only at the Gradle plugin site (see question in https://github.com/quarkusio/quarkus/issues/34148).
After registering the Gradle plugin site, the Quarkus Gradle plugin can now be found.
Note that after fixing the above gradle configuration issue, the Spring Boot based services like Tally stopped working because the Jandex dependency was missing. This was caused by the swatch-product-configuration module using the Quarkus platform. Since this module is used in both Spring Boot and Quarkus services, I removed the Quarkus dependencies from it and fixed the dependency conflict …
> SWATCH-2038: Bump Quarkus to 3.9.2 && Update the swatch-product-configuration module to be framework-agnostic

- swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
- swatch-subscription-sync/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
- swatchdog/README.md
Also required since the splunk-otel-javaagent.jar is no longer set in the Dockerfile itself.
This PR commit is a piece that was missing from #3179
1.  Perform an EE deployment.  You can use the pattern below (but be sure to replace the `-i` with the tags for your quay.io namespace.
```
$ bin/build-images.sh
$ VER=$(git rev-parse --short=7 HEAD) ;  bonfire deploy rhsm \
--source=appsre \
--ref-env insights-production \
--optional-deps-method none \
--frontends false \
--no-remove-resources app:rhsm \
--timeout 1800 \
-i quay.io/awood/swatch-metrics=$VER \
-i quay.io/awood/rhsm-subscriptions=$VER \
-i quay.io/awood/swatch-contracts=$VER \
-i quay.io/awood/swatch-producer-aws=$VER \
-i quay.io/awood/swatch-producer-azure=$VER \
-i quay.io/awood/swatch-system-conduit=$VER \
-p …
```
> Add Spring hot deployment to Clowdapps without it

- src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
- src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java
Jira issue: SWATCH-2318
Consumers from billable-usage now use UOM instead of metricId.
Covered by unit test, but insight from QE on *in situ* testing would be appreciated.
> SWATCH-2318: Use metricid instead of UOM from billable usage messages

- bin/insert-mock-hosts
Fixes the `insert-mock-hosts` script (which has been broken for like 6 months since we dropped `account_config` :upside_down_face:)
1.  Run `bin/insert-mock-hosts --org org123 --opt-in`
1.  On `main` this command will fail.  On this branch, it will run.
1. `psql -h localhost -U rhsm-subscriptions rhsm-subscriptions -c "select * from org_config"`
> Remove reference to account_config table in insert-mock-hosts

- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/billing/TallySummaryMessageConsumer.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/TallySummaryMessageConsumerIT.java
- src/test/java/org/candlepin/subscriptions/test/ExtendWithEmbeddedKafka.java
Jira issue: [SWATCH-2412](https://issues.redhat.com/browse/SWATCH-2412)
- Use saveAndFlush to validate the db state when consuming tally snapshots
- Added happy path integration test
Also, the kafka consumer already deals with the error handling, so instead of using a custom RetryTemplate, I've configured the existing mecanism to use the retry related configuration.
To verify these changes is a bit tricky since you need to do manual changes:
2.- apply the changes from the patch: [swatch-2412.PATCH](https://github.com/RedHatInsights/rhsm-subscriptions/files/14916849/swatch-2412.PATCH)
3.- start the service: `DEV_MODE=true CONTRACT_USE_STUB=true ./gradlew :bootRun`
4.- create the following message into the topic …
> SWATCH-2412: Use saveAndFlush when consuming tally snapshots

- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
- src/main/java/org/candlepin/subscriptions/tally/events/EventRecordsRetentionProperties.java
- src/main/resources/application-worker.yaml
- src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-2428
The retention policy configuration was updated to be 6 months. The configuration property type was changed from Duration to Period to make monthly boundaries more accurate.
1. Check out [this version](https://gitlab.cee.redhat.com/smqe/smqe-tools/-/merge_requests/272) of smqe-tools and activate the virtual env.
1. Deploy the monlith on the main branch.
2. Clean out the events table
```
psql -h localhost -U rhsm-subscriptions rhsm-subscriptions -c "truncate events"
```
3. Run the following in the smqe-tools virtual env
```
export ENV_FOR_DYNACONF=local && \
SCRIPT=$(cat << EOF
from time import sleep
from datetime import datetime, timezone
from dateutil.relativedelta import relativedelta
from smqe_tools import create_payg_data, fetch_events_in_range, purge_events …
```
> SWATCH-2428 Update event retention policy to 6 months

- src/main/resources/liquibase/202404051233-fix-bad-tally-state-and-event-data.xml
- src/main/resources/liquibase/changelog.xml
Jira issue: SWATCH-2421
This patch adds a liquibase changeset to fix the data in the events and
tally_state tables caused by a failed deployment. The changeset is
intended to be run in a single transaction.
The changeset will:
1. Set the record_date in the events.data JSON column to the record's record_date when the JSON's record_date is NULL.
2. Set the tally_state.latest_event_record_date to '2024-04-01T01:00Z' when the latest_event_record_date is null.
3. Add a non-null constraint on the tally_state.latest_event_record_date
column
NOTE:
Due to the offset of job runs, an Event's record_date will be
approximately 1.5h after the event timestamp. Therefore, we
set the latest_event_record_date to '2024-04-01T01:00Z' to
ensure that we do not include any events with timestamps in
March.
To …
> SWATCH-2421 Fix event and tally_state data

- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceClientFactory.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceService.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureMarketplaceServiceTest.java
Jira issue: SWATCH-2444
When we have multiple sets of api credentials to use against azure, the code was calling the api with both credentials every time. This code change makes it so we only try the next set of credentials if the first one fails instead of continuing to try more credentials.
To test this you need to use credentials from stage, updated to have another invalid entry.
> SWATCH-2444: Fix bug with multiple azure API credentials 

- swatch-api/deploy/clowdapp.yaml
- swatch-metrics/deploy/clowdapp.yaml
- swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-2336
Some customers have been getting the following error on the call /api/rhsm-subscriptions/v1/tally/products/RHEL for x86/Sockets:
java.lang.IllegalArgumentException: Request header is too large
As this has been "random", it is assumed that the size in error is just above the set limit of 48K. This number has been doubled. This effectiveness of the solution will be reflected in the future frequency of the exception.
> SWATCH-2336: Increased max header size to accomodate actual use

- src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
- src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
Jira issue: [SWATCH-2408](https://issues.redhat.com/browse/SWATCH-2408)
Only the sockets were being returned by default. We also need to provide the cores. 
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/642
2.- Add host to Insight DB:
```
VALUES ('e5406d59-5cf3-4e83-abf8-84c149f8b6ba', 'account123', 'd125f119-0c98-43f2-a5de-ccf2e8e1ab55', '1993-03-26 00:00:00.000000 +00:00', '1993-03-26 00:00:00.000000 +00:00', '{"rhsm": {"orgId": "org123", "IS_VIRTUAL": null, "VM_HOST_UUID": null}}', null, '{"insights_id": …
```
> SWATCH-2408: Return both cores and sockets by default in the instances API

- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingController.java
- src/main/resources/liquibase/202404121601-add-new-columns-billable-usage-remittance.xml
- src/main/resources/liquibase/changelog.xml
- src/main/spec/internal-billing-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingControllerTest.java
- swatch-core/schemas/billable_usage.yaml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntity.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/RemittanceErrorCode.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/RemittanceStatus.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/RemittanceSummaryProjection.java
- swatch-model-billable-usage/src/main/java/org/candlepin/subscriptions/billable/usage/BillableUsageAggregate.java
Jira issue: SWATCH-2287
- Add and maintain a status property to billable usage remittance DB records & messages (having possible values of `pending`, `failed`, `succeeded`).
- Add a `billed_on` property (timestamp) to record the time of successful remittance.
- Add an `error_code` property to record the failure reason if applicable. Error code should have possible values of `inactive`, `redundant`, `unknown` (we'll expand later as needed).
- `GET /internal/remittance/accountRemittances`
Should only show different summary per status like successful , null state{} etc
IQE Test MR: <https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/646>
`iqe tests plugin rhsm_subscriptions  -k test_verify_rhel_payg_via_cost_mgmt`
1. Run swatch-core: …
> SWATCH-2287 Add properties to billable usage remittance DB records

- Dockerfile
- swatch-billable-usage/src/main/docker/Dockerfile.jvm
- swatch-contracts/src/main/docker/Dockerfile.jvm
- swatch-metrics/src/main/docker/Dockerfile.jvm
- swatch-producer-aws/src/main/docker/Dockerfile.jvm
- swatch-producer-azure/src/main/docker/Dockerfile.jvm
See https://access.redhat.com/documentation/en-us/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#con-image-content-requirements_openshift-sw-cert-policy-container-images
Jira issue: related to SWATCH-2133
1. run `/bin/build-images.sh -k`
1. `podman run -ti -rm <container> /bin/ls -al /licenses`
1. The `LICENSE` file is present.
> Add LICENSE to container as required by OpenShift Container Policy

- swatch-billable-usage/src/main/resources/application.properties
- swatch-metrics/src/main/resources/application.yaml
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/SystemConduitConfiguration.java
Jira issue: SWATCH-2464
Kafka in Stage and Production needs to use the system truststore.  We tried to address this with SWATCH-2088 (PR #2950) but missed a few things:
* I forgot to add a necessary bean to `swatch-system-conduit`
* `swatch-producer-azure` and `swatch-billable-usage` were never tested as part of SWATCH-2088 and there were flaws in the configuration of those two components.
1. Add the Kafka server certificate to the system truststore
```
sudo cp config/kafka/test-ca.crt  /etc/pki/ca-trust/source/anchors/ && sudo update-ca-trust
```
**IMPORTANT**: You will need to remove this certificate and re-run `update-ca-trust` after you are finished testing.  If you don't, you'll a) have a certificate in your system truststore that doesn't belong there and b) you'll get a failing unit …
> SWATCH-2464 Allow Kafka to use the system truststore

- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
- src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingResource.java
- src/main/spec/internal-billing-api-spec.yaml
- src/main/spec/internal-tally-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/tally/admin/InternalBillingResourceTest.java
- src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
- swatch-tally/deploy/clowdapp.yaml
Jira issue: [SWATCH-2460](https://issues.redhat.com/browse/SWATCH-2460)
Move the endpoint "/internal/rpc/tally/remittance/purge" from internal tally API to the internal billing API. The new path should be "/internal/rpc/remittance/purge" instead.
1.- setup an EE environment using bonfire
2.- update the swatch-tally-purge-remittances cronJob to be executed every 5 min:
```
spec:
schedule: "*/5 * * * *"
```
Wait up to 5 min and verify that the job invocation of the cronjob was success:
```
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0100 20 100 20 0 0 1538 0 --:--:-- --:--:-- --:--:-- 1538
{"status":"Success"}
```
From: <OCP cluster>/k8s/ns/<OCP …
> SWATCH-2460: Move the /remittance/purge endpoint to the billing API

- src/main/java/org/candlepin/subscriptions/tally/TallySummaryMapper.java
- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapper.java
- src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
- src/test/java/org/candlepin/subscriptions/tally/TallySummaryMapperTest.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageMapperTest.java
- swatch-core/schemas/billable_usage.yaml
- swatch-core/schemas/tally_snapshot.yaml
Jira issue: [SWATCH-2461](https://issues.redhat.com/browse/SWATCH-2461)
The billable usage and snapshot measurements models should contain a new field for the "currentTotal" value. The snapshot measurement one is calculated via SQL query and it's copied over the new billable usage field.
2.- start the tally service:
```
LOGGING_LEVEL_ORG_CANDLEPIN_SUBSCRIPTIONS_TALLY_BILLING=DEBUG \
SUBSCRIPTION_USE_STUB=true \
CONTRACT_USE_STUB=true \
```
3.- send tally summary message into the topic "platform.rhsm-subscriptions.tally":
```
{"org_id": "org123", "tally_snapshots": [{"billing_provider":"aws", "billing_account_id": "123", "snapshot_date": "2023-12-21T01:10:28Z", "product_id": "rosa", "sla": "Premium", "usage": …
```
> SWATCH-2461: Add new field "currentTotal" into the snapshot model

- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/BillableUsageAggregateStreamTopologyTest.java
- swatch-model-billable-usage/src/main/java/org/candlepin/subscriptions/billable/usage/BillableUsageAggregate.java
Jira issue: SWATCH-2288
The uuid from the remittance is passed through the BillableUsage message to the BillableUsageAggregator where it is incorporated into the aggregator message.
1. Run swatch-core:
`RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1 SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8003 SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,rh-marketplace,kafka-queue,rhsm-conduit ./gradlew clean :bootRun`
2. Run swatch-billable-usage:
`SERVER_PORT=8001 QUARKUS_MANAGEMENT_PORT=9001 KSTREAM_BILLABLE_USAGE_AGGREGATION_WINDOW_DURATION=10s KSTREAM_BILLABLE_USAGE_AGGREGATION_GRACE_DURATION=2s ./gradlew :swatch-billable-usage:quarkusDev`
1. Run the core app:
2. Produce …
> SWATCH-2288: Capture billable usage uuids in billable usage hourly aggregates

- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg.yaml
Unneeded and misidentifies some things it shouldn't.
> Drop productName from rhel els identification

- src/main/java/org/candlepin/subscriptions/BootApplication.java
- src/test/java/org/candlepin/subscriptions/subscription/export/PerformanceSubscriptionDataExporterServiceIT.java
- src/test/java/org/candlepin/subscriptions/test/ExtendWithExportServiceWireMock.java
Jira issue: [SWATCH-2328](https://issues.redhat.com/browse/SWATCH-2328)
By default, the RestEasy Client can only handle files up to 50MB. To remove this limitation, the only option is to set the system property "dev.resteasy.entity.file.threshold" to "-1". 
More information in https://github.com/orgs/resteasy/discussions/4085.
Instead of setting this property in the ClowdApp manifests (in tally and subscription sync applications), I decided to set this system property in the BootApplication for a couple of reasons:
- it affects to the RestEasy Client which is only used by the Spring services (Quarkus uses the RestEasy Reactive Client).
- there are other system properties that are also set in the BootApplication
I could reproduce the issue using the test I added. After setting this …
> SWATCH-2328: Configure RestEasy Client to handle un-limited files

- src/main/java/org/candlepin/subscriptions/tally/TallySummaryMapper.java
- src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
- src/test/java/org/candlepin/subscriptions/tally/TallySummaryMapperTest.java
- swatch-core/schemas/tally_snapshot.yaml
Jira issue: [SWATCH-1384](https://issues.redhat.com/browse/SWATCH-1384)
UOM field dropped from message schema.
> SWATCH-1384: Drop UOM from tally summary messages

- .gitleaks.toml
Jira issue: No issue as this is just a very quick fix
Scans for credential leaks were picking up the keys we have in `config/kafka`.  These keys are used for the certificates used for testing TLS connections and are only used on locally running containers, so it's a false positive for a real leak.
1.  You need to have `rh-pre-commit` installed.  Instructions for doing so are on the intranet but contact me if you need help.  It's actually a good idea for everyone to do this, so consider this PR review a little nudge in the right direction.
1.  On `main`, run `rh-gitleaks --path=. -v --additional-config=.gitleaks.toml`
1.  Run the same command on this branch
1.  On this branch, no credentials are identified as being leaked.
> Add .gitleaks.toml to reduce false positives on credential leak scans

- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
The test was checked by using "yesterday". This causes a different result in a monthly calculation when the test is run on the first of a month.
The unit test will need to pass on the first day of the month
1. Run on the first day of a month
> Update unit test for first day of month failure

- swatch-api/deploy/clowdapp.yaml
- swatch-contracts/deploy/clowdapp.yaml
- swatch-contracts/src/main/resources/application.properties
- swatch-core/src/main/resources/swatch-core/application.yaml
- swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
- swatch-subscription-sync/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Adding a common property `LOGGING_SHOW_SQL_QUERIES` in spring boot and quarkus services which is by default false.
In the Spring Boot services, this property will configure:
```
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true
```
In the Quarkus services:
```
quarkus.hibernate-orm.log.sql=true
```
When enabled, this property will be helpful when troubleshooting issues in EE environments.
No needed.
> Configure logging SQL queries by deployment property

- swatch-contracts/build.gradle
- swatch-contracts/deploy/clowdapp.yaml
- swatch-contracts/src/main/java/com/redhat/swatch/contract/config/ApplicationConfiguration.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/EnabledOrgsProducer.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionPruneTaskConsumer.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionSyncTaskConsumer.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/json/EnabledOrgsResponseDeserializer.java
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ContractsTestingResourceTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/EnabledOrgsProducerTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionPruneTaskConsumerTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncTaskConsumerTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/InMemoryMessageBrokerKafkaResource.java
Jira issue: [SWATCH-2356](https://issues.redhat.com/browse/SWATCH-2356)
- The method "pruneUnlistedSubscriptions" from SWATCH-2277 should produce a single message to "platform.rhsm-subscriptions.enabled-orgs-for-tasks" with a message containing the topic name "platform.rhsm-subscriptions.subscription-prune-task".
- The method "syncAllSubscriptions" from SWATCH-2277 should produce a single message to "platform.rhsm-subscriptions.enabled-orgs-for-tasks" with a message containing the topic name "platform.rhsm-subscriptions.subscription-sync-task".
- Create the consumer of "platform.rhsm-subscriptions.subscription-prune-task" that receives a message that includes the orgId. Leave the implementation empty.
- Create the consumer of "platform.rhsm-subscriptions.subscription-sync-task" that …
> SWATCH-2356: Send request to enabled-orgs-for-tasks for prune and sync

- src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
- src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
- src/main/java/org/candlepin/subscriptions/tally/export/InstancesJsonDataMapperService.java
- src/main/resources/liquibase/202404240830-update-instance-view-to-aggregate-metrics.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
- src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
- src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
- swatch-core-test/src/main/resources/application-test.yaml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/RhsmSubscriptionsDataSourceConfiguration.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/EventRecord.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceView.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceViewKey.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/converters/EventRecordConverter.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/converters/TallyInstanceViewMetricsConverter.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/MetricId.java
Jira issue: [SWATCH-2465](https://issues.redhat.com/browse/SWATCH-2465)
Before, we were using the default (first) metric ID by product tag if the user does not specify any. After these changes, we'll be getting all the metrics if the user does not specify any.  
To avoid getting duplicates, I had to update the "tally_instance_view" to aggregate all the metrics in the host into a single record. 
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/664
2.- Add host to Insight DB:
```
INSERT INTO hosts (id, account, display_name, created_on, modified_on, facts, tags, canonical_facts, system_profile_facts, ansible_host, stale_timestamp, reporter, per_reporter_staleness, org_id, "groups") 
VALUES …
```
> SWATCH-2465: Do not filter by metric if not set in the Instances API

- bin/wait-for
- docker-compose.yml
- init_dbs.sh
- postgresql.conf
Jira issue: Part of SWATCH-2475
This patch adds several items:
* The unleash server now starts and runs properly.
* Health checks have been added to the db and kafka containers
* The command for the inventory containers has been altered to better reflect the commands used by the inventory development Dockerfile
* The postgresql container now listens for connections external to the compose network and internal to the compose network
* We no longer override the set_passwords.sh script in the postgresql container.  Instead we add an additional script into a directory where it will be run automatically by the container entrypoint.
1.  If you have a compose already running, `podman-compose down`.  This will **destroy** your database, so if you have data you want to save, do a `pg_dump`
1. …
> SWATCH-2475: Update docker-compose

- swatch-billable-usage/deploy/clowdapp.yaml
Jira issue: SWATCH-2486
KAFKA_BILLABLE_USAGE_PARTITIONS env var is used by the aggregate flush service and was not being added to the deployment.
> SWATCH-2486: Include KAFKA_BILLABLE_USAGE_PARTITIONS in billable usage deployment

- src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
- src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionCsvDataMapperService.java
- src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterService.java
- src/test/java/org/candlepin/subscriptions/export/BaseDataExporterServiceTest.java
- src/test/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterServiceTest.java
- src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Jira issue: [SWATCH-2483](https://issues.redhat.com/browse/SWATCH-2483)
The unlimited subscriptions query is used to populate the total capacity of the skus, and since we are not gathering this information in the export service, we don't need it.
To retrieve the payg subscriptions, the difference is how to filter by product (it's being done one way if the product is non payg, and in a different way if the product is payg). I have a fix for this to retrieve both.
Steps to reproduce and verify using QE tooling:
1.- app.rhsm_subscriptions.create_mock_subscription(product_id="rosa",billing_provider="aws",quantity=10)
2.- app.rhsm_subscriptions.get_skus_report(product_id="rosa")
3.- filters = {"product_id": "rosa"}
4.- export = app.rhsm_subscriptions.create_swatch_export_request(filters=filters …
> SWATCH-2483: Fix export subscriptions service to filter by payg

- src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
- src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
- src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
- src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java
- src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
- src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
Jira issue: SWATCH-2504
- now uses the new product tag identification methods
SubscriptionDefinition.getAllProductTagsWithPaygEligibleByRoleOrEngIds
and
SubscriptionDefinition.getAllProductTagsWithNonPaygEligibleByRoleOrEngIds
- Added unit tests to cover new code
This ensures a common code path for this decision making.
Existing unit and iqe tests cover the code changes.
Please test the statement from the Jira card:
"If data comes from telemetry then treat as metered: Y, if from HBI then metered N, if there is data in both streams then metered Y wins."
The successful run of the test suite.
Confirmation of the above statement.
> SWATCH-2504: Replace the fact normalizer identification

- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/main/resources/liquibase/202405080950-copy-uom-to-metric-id-events-table.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
Jira issue: SWATCH-431
In the transition from UOM to exclusively using metric_id, we need to update the event data. Where there is not currently a value for metric_id in the "measurements" block, but there is one for UOM, the data will be copied to the metric_id. 
The data will be left in the UOM field for now. The code has been modified to look for metricId first and then fall back to UOM.  
1. Start the podman-compose for rhsm-subscriptions while using the main branch.
2. Transfer data from production using ```./import-from-gabi.py --org-id <org_id> --events``` from the swatch-support-scripts directory.
3. Examine the data value json to see that about half of them have uom but not metric_id:
```select count(*) from events;```
```select count(*) from events where …
```
> SWATCH-431: Update event data json to copy uom to metric_id

- src/main/java/org/candlepin/subscriptions/tally/collector/ProductUsageCollectorFactory.java
- src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java
- src/test/java/org/candlepin/subscriptions/tally/collector/ProductUsageCollectorFactoryTest.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_ARM.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_IBM_Power.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_IBM_z.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_SAP_x86.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_EUS.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_ha.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_rs.yaml
- This replaces the use of the id field as the indicator in the factory of which  UsageCollector is needed for processing
Jira issue: SWATCH-2333
The usage collection method's determination is based on the variant tag in the subscription definition. This method is not sufficient as this tag varies between "RHEL for ..." and "rhel-for-...". Instead of relying on that field which is not constrained, the field 'vdcType' is introduced in the definition. This way the determination is based on a boolean value with a specific purpose.
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/672
1. The test is structured to use the known variations of the variant tag. The test will show that the hypervisor usage is properly collected in both cases.
> SWATCH-2333: Added attribute to subcription definition for isVdcType

- .unleash/Dockerfile.unleash
- bin/import-features.sh
- dependencies.gradle
- deploy/unleash-import-clowdapp.yaml
Jira issue: SWATCH-2531
This PR creates a container that can be deployed in the ephemeral environments to populate an Unleash instance from a JSON file.
There are a couple components to this.  One is a shell script that populates an Unleash instance and one is a ClowdApp that creates a job that performs the import in the ephemeral environments.  I'm going to describe the test scenario for the ephemeral environment here but at the end I'll write a little note about running locally.
1.  Build the container that runs the import script and push it to quay.io
```
podman build . -f .unleash/Dockerfile.unleash -t quay.io/awood/unleash-import:latest && podman push quay.io/awood/unleash-import:latest
```
1. You'll need to go to the quay.io URL for that image and mark the repository visibility as …
> SWATCH-2531 Populate unleash in EEs

- src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingController.java
- src/main/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingResource.java
- src/main/spec/internal-billing-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingControllerTest.java
- swatch-billable-usage/deploy/clowdapp.yaml
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResource.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillingProducer.java
- swatch-billable-usage/src/main/resources/META-INF/openapi.yaml
- swatch-billable-usage/src/main/resources/application.properties
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageControllerTest.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/InMemoryMessageBrokerKafkaResource.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillingProducerTest.java
- swatch-model-billable-usage/src/main/java/org/candlepin/subscriptions/billable/usage/AccumulationPeriodFormatter.java
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-2542
- Moved the process remittance cronjob to the billable usage service
- API changes: 
| Old | New  |
|---|---|
|http://swatch-tally-service:8000/api/rhsm-subscriptions/v1/internal/rpc/remittance/processRetries | http://swatch-billable-usage-service:8000/api/swatch-billable-usage/internal/rpc/remittance/processRetries |
You need first to deploy the billable usage and the tally services into an EE environment:
```
bonfire deploy ...
```
1.- update the "swatch-billable-usage-retry-remittances" cronjob with:
```
spec:
schedule: '* * * * *'
```
This will run the job every minute. 
2.- wait for the job to be triggered (up to 1 min). See jobs in `https://<OCP>/k8s/ns/ephemeral-xciphz/cronjobs/
swatch-billable-usage-retry-remittances/jobs`
3.- the pod should see that the …
> SWATCH-2542: Port the process remittance cronjob to the billable usage

- src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
Jira issue: SWATCH-2520
Before, the capacity and total capacity was only calculated for cores and sockets.
2. start service `DEV_MODE=true ./gradlew :bootRun`
3. insert test data:
```
INSERT INTO public.offering VALUES ('MW01486', 'rosa', 'OpenShift Enterprise', NULL, NULL, NULL, NULL, NULL, 'Premium', '', 'Red Hat OpenShift Container Platform (Hourly)', false, NULL, false);
INSERT INTO public.sku_product_tag VALUES ('MW01486', 'rosa');
INSERT INTO public.subscription VALUES ('MW01486', 'org123', '957592', 1, '2024-02-26 00:20:46.986+00', '2025-03-07 00:20:46.986+00', 'testProductCode;testbyf;1234567', '4454946', 'azure', 'testbyf');
insert into public.subscription_product_ids values ('rosa','957592','2024-02-26 01:20:46.986 +0100');
INSERT INTO …
```
> SWATCH-2520: Calculate capacity for all the metrics

- Jenkinsfile
The ci.ext.devshift.net run is stopped immediately. The continuous-integration/jenkins/pr-merge run seems to happen when it gets to a transition.
Either way, it should save a lot of processing time.
> Stop older CI run when a new one is started  for the same branch

- src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
- src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
Jira issue: SWATCH-2494
With the addition of the `status` column to billable usage remittance, we now have several different "types" of billable usage. It's necessary to consider each one as contributing to the total remittance for an accumulation period. Future work can amend what counts as necessary (e.g. fatal failures should not counted towards what was remitted for the accumulation period).
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/684
See iqe test (easiest to just let it run against EE).
> SWATCH-2494: Add all status of billable usage remittance together

- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/OfferingEntity.java
- swatch-contracts/src/main/resources/db/202405222240_add_offering_special_product_tag_h2_only.xml
- swatch-contracts/src/main/resources/db/changeLog.xml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Offering.java
Jira issue: SWATCH-2578
During subscription sync it was not checking for special_pricing_flag hence it was skipping the update.
IQE Test MR: 
Steps are mentioned in Jira card but, copying same here. Partly its manual because we never update the offering table.
1.  Run the swatch-core app:
```
RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1
SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8882 SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,rh-marketplace,kafka-queue,rhsm-conduit ./gradlew clean :bootRun 
```
2. Since stage refresh is going we have make some tweaks and get creative.  Point product_url to qa instead of stage in `application.yaml` 
`url: …
> SWATCH-2578 Offering should get updated when special_pricing_flag is updated

- src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
- src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
- src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
- src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java
- src/main/resources/liquibase/202405061230-remove-duplicated-hosts.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
- src/test/java/org/candlepin/subscriptions/inventory/db/InventoryRepositoryIT.java
- src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java
- src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
- src/test/java/org/candlepin/subscriptions/tally/InventoryHostFactTestHelper.java
- src/test/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollatorTest.java
- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
Jira issue: [SWATCH-2145](https://issues.redhat.com/browse/SWATCH-2145)
- Add a migration script to remove the duplicates based on (1) the presence of the billing_account_id, (2) the more recent last_seen.
- Add an unique constraint for org_id and inventory_id.
- Add an unique constraint for org_id and instance_id.
- When upserting a system during HBI tally, look for possible duplicates via org_id/instance_id. If there is an existing record, it should be treated as a matching system.
Note that this PR adds a performance killer when reconciling the hosts with HBI. 
Also note that I added the list of hosts to be deleted in the linked JIRA ticket. 
I ran the migration scripts using the stage data in local and it took less than 60 seconds. 
2.- load the stage data into …
> SWATCH-2145: Prevent tallies from creating duplicate system/host entries

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
- src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
- src/main/java/org/candlepin/subscriptions/tally/facts/ProductNormalizer.java
- src/main/java/org/candlepin/subscriptions/util/OfferingProductTagLookupService.java
- src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
- src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
- src/test/java/org/candlepin/subscriptions/tally/facts/ProductNormalizerTest.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/Variant.java
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/VariantTest.java
Why? Housekeeping mostly and I needed to make some of these changes for #3362 anyway, but pulled them out into its own branch for review purposes.  There should be no noticeable behavior changes with this PR.
- Combined `getAllProductTagsWithPaygEligibleByRoleOrEngIds` and `getAllProductTagsWithNonPaygEligibleByRoleOrEngIds` into a single method that takes `isMetered` as a parameter
- Updated lookup methods in Variant that were still using findFirst() and returning Optional<String>.  They now return a Set<String> that may or may not be empty.
These are quality of life / maintenance changes.  There should be no noticeable change of behavior - even with that findFirst() change.  There isn't be data in swatch yet that findFirst() wouldn't work on, but would be a bug for ELS if not addressed. …
> Refactor SubscriptionDefinition and Variant lookups and Move Product Tag detection out of FactNormalizer

- src/main/java/org/candlepin/subscriptions/export/CsvExportFileWriter.java
- src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionCsvDataMapperService.java
- src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterService.java
- src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionJsonDataMapperService.java
- src/main/resources/liquibase/202405160950-add-subscription-capacity-view.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/export/BaseDataExporterServiceTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
- src/test/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterServiceTest.java
- src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
- swatch-core/schemas/subscriptions_export_csv_item.yaml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityView.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityViewMetric.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/converters/SubscriptionCapacityViewMetricConverter.java
Jira issue: SWATCH-2518
The new view is used by the export service to process and aggregate all the metrics in a single entry. In the future, the same logic should be used by the Subscription API.
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/706
1.- deploy the app into an EE
2.- create a contract via API. Instructions using the iqe tooling:
```
import random
product_id = "rosa"
// create contract:
contract_data = {
"instance_hours": random.randint(0, 10),
"cores": random.randint(0, 7),
"billing_provider": "aws",
"billing_account_id": "AAA",
}
contract = app.rhsm_subscriptions.create_contract(
product_id=product_id,
**contract_data,
)
```
3.- confirm that the above API creates two subscriptions
4.- create measurements for both …
> SWATCH-2518: Create subscription capacity view for the export service

- src/main/java/org/candlepin/subscriptions/capacity/admin/UsageContextSubscriptionProvider.java
- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/main/resources/liquibase/202405151547-update-events-azure-billable-account-id.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
- src/test/java/org/candlepin/subscriptions/capacity/admin/UsageContextSubscriptionProviderTest.java
- src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/AzureContractLifecycleIntegrationTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractEntityMapperTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
- swatch-model-events/schemas/event.yaml
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Jira issue: SWATCH-2492
The billing account id was a concatenation of the Azure Tenent id and the Azure Subscription id. This was used because the Tenent id was supposed to be immediate while the Subscription id can take as much as 72 hours. The existence of the Tenent id field has been deemed unreliable.
This update only uses the Subscription id for the billing account id field. If no value is available, then the operation is delayed until the value is in place.
1. Run swatch-core:
`RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1 SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8003 SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,rh-marketplace,kafka-queue,rhsm-conduit …
> SWATCH-2492: Remove use of Azure Tenent Id in the billing account id

- clients/rh-partner-gateway-client/rh-partner-gateway-api-spec.yaml
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractSourcePartnerEnum.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/RhPartnerClientIntegrationTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractEntityMapperTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Jira issue: SWATCH-2586
Before, the sourcePartner was an enum with a restricted set of values (aws_marketplace and azure_marketplace).  The problem is that the IT Partner Gateway uses a string and as far as I could see, there are much more valid values like gcp_marketplace, ibm_marketplace, ... And it could be more in the future.  Therefore, we should use a free string instead and check the marketplace we support as we already do nowadays.
Using iqe tooling:
```
from iqe_rhsm_subscriptions.smqe_tools import sync_contract
sync_contract(org_id="11789772")
```
In main, the sync_contract fails because it receives an unrecognised ibm_marketplace value. With this branch, it should fail because:
```
Request '/api/swatch-contracts/internal/rpc/sync/contracts/11789772' failed with error 'Could not …
```
> SWATCH-2586: Change sourcePartner type to string

- src/main/resources/liquibase/202406030700-drop-unique-constraints-in-hosts.xml
- src/main/resources/liquibase/changelog.xml
Jira issue: SWATCH-2594
The existing reconciliation logic limits us to add unique constraints because the logic needs to first (1) insert a host and then (2) delete it, and the unique constraint will be issued at (1).
Since there seems not to be an easy way to fix it, we would need to first adopt the event-driven design logic that will be done in [SWATCH-512](https://issues.redhat.com/browse/SWATCH-512) to prevent inserting duplicated hosts in our systems. 
This pull request adds a migration script to drop the unique constraints.
No need.
> Revert "SWATCH-2145: Prevent tallies from creating duplicate system/host entries (#3330)"

- clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContractsApi.java
- src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
- src/test/java/org/candlepin/subscriptions/capacity/CapacityReconciliationControllerTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
Jira issue: SWATCH-2588
These changes will involve the following services:
- subscription sync to not clear the subscription measurements when the offering is metered and has no sockets and/or no cores.
- contracts service: synchronize the subscription data even when the contract has no changed
- contracts service: new API to force synchronize all the subscriptions for contracts given an org ID. This is necessary to fix the data in stage.
1.- load stage data into your local 
2.- start the API service: `DEV_MODE=true SPRING_PROFILES_ACTIVE=api ./gradlew :bootRun`
3.- confirm you see no capacity for rosa:
```
echo -n '{"identity":{"account_number":"","type":"User","user":{"is_org_admin":true},"internal":{"org_id":"17496113"}}}' | base64 -w 0
-- …
```
> SWATCH-2588: Do not clear measurements for offerings with metered

- src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationController.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
Jira issue: SWATCH-2576
I wasn't able to reproduce issue but, Lazy initialization happens due to following reason. We don't have it on stage and on prod it happens very randomly. Hopefully this resolves the issue.
1) Use FetchType.EAGER: Fetch the collections eagerly. N/A for now since we use EntityGraph.
2) Use Entity Graphs: Specify the collections to be loaded using an EntityGraph. This is what we use and it eagerly loads the producttag.
3) Open Session in View: In web applications, keep the Hibernate session open until the view is rendered. N/A
4) Join Fetch in JPQL/HQL: Explicitly fetch the collections in your queries. - N/A
5) Access Collections within a Transactional Method: Ensure that any access to the lazy collections happens within a method annotated with @ Transactional. - …
> SWATCH-2576 Fix LazyInitializationException during subscription sync

- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-2217
Description
-----------
Add a query to retrieve OCP cluster data
Testing
-------
To smoke-test, copy paste the query and try via gabi.
Also note that we have a GH workflow that validates floorplan queries.
> SWATCH-2217: Add ocp cluster data floorplan

- src/main/resources/liquibase/202405151547-update-events-azure-billable-account-id.xml
Jira issue: SWATCH-2492
Running the existing migration scripts fails on stage with:
```
2024-06-04 10:20:40,457 [thread=restartedMain] [ERROR] [liquibase.changelog] - ChangeSet liquibase/202405151547-update-events-azure-billable-account-id.xml::202405151547-06::wpoteat encountered an exception.
liquibase.exception.DatabaseException: ERROR: duplicate key value violates unique constraint "host_tally_bucket_pkey"
```
Tested using the stage data.
> Prevent unique constraints in the 202405151547-update-events-azure-billable-account-id.xml

- src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
- src/test/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategyTest.java
Jira issue: SWATCH-2583
The CombiningRollupStrategy relies on a DateRange to lookup and catalog
the existing affected snapshots when creating/updating the finest granularity
snapshots. BEFORE the new tally changes, the strategy could always make the
assumption that all Events in that range were (re)pulled and calculated, and
if an existing snapshot does not have a calculation based on an Event,
the tally measurements could be cleared. The new tally changes, however,
does not make that guarantee. Before producing snapshots, it determines the
affected synthetic range based on the produced account calcs (start from the oldest,
end on the newest). Because there may not be a calc for a date in the middle
of this range, it assumes that the affected snapshots will be everything in
between, and …
> SWATCH-2583: Do not remove unseen finest granularity measurements

- src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
- src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
- src/main/java/org/candlepin/subscriptions/tally/export/InstancesJsonDataMapperService.java
- src/main/resources/liquibase/202405300830-split-instance-view-to-payg-and-non-payg-versions.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
- src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceNonPaygViewRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstancePaygViewRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceNonPaygView.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstancePaygView.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceView.java
Jira issue: SWATCH-2590
Since the way to resolve the metrics is different depending on whether the product is payg or not, and also we need this logic to be done in the export service, we need to move this logic onto the query itself. 
Changes:
- Split tally_instance_view into tally_instance_payg_view and tally_instance_non_payg_view (because the way to resolve the metrics is different). 
- Ensure the export service also works
Added tests to cover the changes.
For using the IQE tooling, see the JIRA ticket for the instructions.
> SWATCH-2590: Split tally_instance_view into two versions for payg

- .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml
Consumer group changed from swatch-producer-billing to swatch-billable-usage.
> Update tally consumer group name to new swatch-billable-usage

- docker-compose.yml
- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataController.java
- src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataControllerTest.java
- swatch-model-events/schemas/event.yaml
Jira issue: SWATCH-2601
Description
===========
When events are ingested either through the testing API or via kafka, normalize the attribute used for metric identification to `metric_id`. If an event is ingested having `uom`, then the value is set on `metric_id`, and removed from `uom`.
Testing
=======
IQE Test MR: [!736](https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/736)
> Normalize event measurements to metric_id on receipt

- docker-compose.yml
Sometimes when the HBI container is starting up via podman-compose, it fails to connect to the DB becuase the DB service isn't fully up. This patch tells HBI to attempt to restart on failure so that DB will be ready on the next attempt.
Bring up all services via podman-compose and ensure that the inventory services are up and running.
```
podman-compose up -d 
```
```
podman ps
```
> Work around HBI DB connection failure on startup

- docker-compose.yml
Description
===========
To do this, a few kafka topics need to be created up-front (done via kafka-setup pod).
Testing
=======
Setup
-----
1. `podman-compose down`
Steps
-----
1. `podman-compose up -d`
2. Run an iqe method such as `application.rhsm_subscriptions.create_physical_rhel()`
Verification
------------
1. Check the insights `hosts` table to see the host was created successfully.
> Enable inventory-mq via compose to work with local iqe

- src/main/java/org/candlepin/subscriptions/export/ExportSubscriptionListener.java
- src/test/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterServiceTest.java
- src/test/java/org/candlepin/subscriptions/test/ExtendWithExportServiceWireMock.java
Jira issue: SWATCH-2624
Instead, print a warning trace and properly mark the request as error using the Export API.
Added unit tests for covering this change.
> SWATCH-2624: Don't log errors after missing permissions in exports

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Jira issue: SWATCH-2647
During metric collection, SubscriptionDefinition.getAllProductTagsByRoleOrEngIds returns `RHEL for x86` and `rhel-for-x86-els-payg-addon`.  This was part of the work that ended up getting split out into SWATCH-2634.
There was a condition in the code that said if the productTags.size() != 1, skip creating the event.
Updated the logic to just make sure the product tag we're collecting metrics for appears in the tags returned by getAllProductTagsByRoleOrEngIds.
A more elegant solution will be part of SWATCH-2634.
Run swatch-metrics against stage rhelemeter
```
EVENT_SOURCE=rhelemeter PROM_URL="http://10.0.150.94/api/v1" ./gradlew :swatch-metrics:quarkusDev
```
Kick off metrics gathering
```
curl -X 'PUT' \
'http://localhost:8000/api/swatch-metrics/v1/internal/metering/ …
```
> SWATCH-2647: swatch-metrics no longer skips event creation for els-payg-addon

- swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg.yaml
Jira issue: SWATCH-2658
CostManagement reports a billing_marketplace_instance_id as *instance_id*
Rhelemeter reports subman id as *instance_id*
During event reconciliation, a `billing_marketplace_instance_id` is never going to match a `subman_id`, so deduplication wouldn't happen.
We want to use `billing_marketplace_instance_id` as the `instance_id` when swatch-metrics produces Event messages on the service-instance-ingress topic.
```
./bin/metering-promql.py --product rhel-for-x86-els-payg
```
```
rhel-for-x86-els-payg
---------------------
Accounts PromQL: group(min_over_time({product=~'.*(^|,)(204)($|,).*', external_organization != '', billing_model='marketplace'}[1h])) by (external_organization)
vCPUs PromQL: sum_over_time((max by (billing_marketplace_instance_id) …
```
> SWATCH-2658: Use billing_marketplace_instance_id as instance key for rhelemeter

- src/main/java/org/candlepin/subscriptions/liquibase/LiquibaseCustomTask.java
- src/main/java/org/candlepin/subscriptions/liquibase/PopulateSubscriptionMeasurements.java
- src/main/java/org/candlepin/subscriptions/liquibase/RemoveIncorrectlySegmentedSubscriptions.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/main/resources/liquibase/202406051539-remove-erroneously-duplicated-subscriptions.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
- swatch-billable-usage/build.gradle
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillingProvider.java
- swatch-producer-aws/build.gradle
- swatch-producer-azure/build.gradle
Jira issue: SWATCH-2579
A single quantity changes on a subscription was resulting in the subscription being duplicated on every sync.  When the quantity on a subscription changes, we segment the subscription.  I.e. we terminate the subscription, giving it an end date of `now()`, create a new subscription with the new quantity, same subscription number, and same end date as the original subscription.
Prior to this patch, if the quantity in the subscription service ever changed from the quantity we had on a `subscription` table row, we would segment the subscription on every sync.
IQE Test MR: 
1. Place the [swatch-2579.json](https://github.com/user-attachments/files/15537832/swatch-2579.json) wiremock scenario in `stub/mappings` as `swatch-2579.json`
1. Ensure you have `RH00001` in …
> SWATCH-2579 Prevent subscription duplication on quantity change

- src/main/java/org/candlepin/subscriptions/event/EventConflictResolver.java
- src/main/java/org/candlepin/subscriptions/tally/TallySummaryMapper.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceFilter.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceSummaryProjection.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepositoryTest.java
Jira issue: SWATCH-2670
**Group RemittanceSummaryProjections by hardware measurement type**
When hardware measurement type was added to the remittance table,
we did not update the get remittance totals projection to include
it. Because of this, the remittance totals query was returning the
remittance total matching remittance records with similar criteria
resulting in 0 required remittance (no record created).
This patch adds hardware measurement type to the projection and the
supporting query filter so that the correct totals are returned.
**Start by testing on the main branch to reproduce. Stop at the main branch validation step below. Then test the same against the branch.**
Start with a clean DB.
```
dropdb -h localhost -U rhsm-subscriptions rhsm-subscriptions && createdb -h localhost …
```
> SWATCH-2670 Group RemittanceSummaryProjections by hardware measurement type

- src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionCsvDataMapperService.java
- src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterService.java
- src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionJsonDataMapperService.java
- src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
- src/main/resources/liquibase/202406120950-update-subscription-capacity-view.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/export/BaseDataExporterServiceTest.java
- src/test/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterServiceTest.java
- src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityView.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/ProductId.java
Jira issue: SWATCH-2644
Changes:
- moved the specification to the view repository, so it can be reused in https://github.com/RedHatInsights/rhsm-subscriptions/pull/3423
- improved the view performance by using the WITH clause
- added the has_infinity_quantity and billing_provider_id that will be needed for [SWATCH-2410](https://github.com/RedHatInsights/rhsm-subscriptions/pull/3423)
Added new integration tests to reproduce the bug.
For IQE tooling, follow the instructions from the linked JIRA ticket.
> SWATCH-2644: Add filter for orgId ++ increase performance of view

- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/processors/BillableUsageAggregateProcessor.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageAggregateConsumer.java
Jira issue: SWATCH-2618
IQE Test MR: 
Steps:
```
INSERT INTO public.events (event_id, timestamp, data, event_type, event_source, instance_id, org_id, metering_batch_id, record_date) VALUES ('6c57046a-7071-4fc9-a543-650b868edcc0', '2024-06-12 16:00:00.000000 +00:00', '{"sla": "Premium", "org_id": "12345678", "event_id": "6c57046a-7071-4fc9-a543-650b868edcc0", "timestamp": "2024-06-12T16:00:00Z", "conversion": false, "event_type": "snapshot_rhel-for-x86-els-payg_vcpus", "expiration": "2024-06-12T17:00:00Z", "instance_id": "efe37aa6-ac56-41df-8c8a-c260bd498f5b", "product_ids": ["204", "69"], "product_tag": ["rhel-for-x86-els-payg"], "record_date": "2024-06-21T18:37:40.540859342Z", "display_name": "ip-10-128-200-231.ec2.internal", "event_source": "rhelemeter", "measurements": [{"value": 2.0, …
```
> SWATCH-2618 Add better logging for AWS Azure usage

- swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg_awsdimension.yaml
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
The test listing in AWS has an incorrect dimension identifier (vcpu_hourly) for unconverted ELS.
We've requested this to be updated, but in the meantime we can pull out that product tag into its own file in order to give it a different dimension identifier than the converted version
This commit should be reverted after the AWS ticket is complete.
Unit test results
```
./gradlew clean test
```
```
> Task :test
SUCCESS: Executed 979 tests in 7m 35s (5 skipped)
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:com …
```
> Support E2E testing of els unconverted with AWS

- src/main/resources/liquibase/202406240700-add-subscription-number-index.xml
- src/main/resources/liquibase/changelog.xml
This is being done to speed up a query during subscription-sync which is consuming almost 100% of CPU.
> SWATCH-2686: Add index for subscription-number to the subscription table

- src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
- src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageMapper.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
- swatch-core/schemas/billable_usage.yaml
- swatch-producer-aws/.openapi-generator-ignore
- swatch-producer-aws/build.gradle
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsUsageContextLookupApiTest.java
- swatch-producer-azure/.openapi-generator-ignore
- swatch-producer-azure/build.gradle
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/BillableUsageDeadLetterTopicProducer.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Jira issue: SWATCH-2323
- Add BillableUsage.tally_id to replace BillableUsage.id
- Deprecate BillableUsage.id
- Found that the BillableUsage class was also generated in the swatch-producer-aws and swatch-producer-azure even when the used by the API is the expected one from the swatch-model-billable-usage. This seems to be a known behaviour of the openapi generator but it causes confusion, so to avoid it, I made use of https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#ignore-file-format.
Only regression testing since the billable_usage.id and billable_usage.tally_id are both supported. This is going to be fully removed in SWATCH-2674.
Adding the QE label to update the iqe steps to make use of the tally_id instead.
> SWATCH-2323: Add BillableUsage.tally_id to replace BillableUsage.id

- src/main/java/org/candlepin/subscriptions/tally/export/InstancesCsvDataMapperService.java
- src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
- src/main/resources/liquibase/202406191500-add-hypervisor_uuid-to-tally-instance-view.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
- swatch-core/schemas/instances_export_csv_item.yaml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceView.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/util/MetricIdUtils.java
Jira issue: SWATCH-2020
- added capability to create CSV output for instances 
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/755
1.- start kafka and postgresql: `podman-compose up -d`
2.- start export-service: `podman-compose -f config/export-service/docker-compose.yml up -d`
3.- start the tally service: `RHSM_RBAC_USE_STUB=true DEV_MODE=true SPRING_PROFILES_ACTIVE="worker,api,kafka-queue" ./gradlew :bootRun`
4.- load some data:
```
insert into account_services(org_id, service_type) values ('123', 'test');
insert into hosts(id, org_id, num_of_guests, instance_id, display_name, billing_provider, billing_account_id, instance_type) 
values ('b870dc34-53a3-4634-bfd1-56c227bc36ac','123', 3, '456', 'my host', 'AWS', '789', 'test');
insert …
```
> SWATCH-2020: Add CSV support to instances export

- src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
- src/main/java/org/candlepin/subscriptions/retention/TallyRetentionPolicy.java
- src/main/java/org/candlepin/subscriptions/retention/TallyRetentionPolicyProperties.java
- src/main/resources/application-worker.yaml
- src/test/java/org/candlepin/subscriptions/retention/TallyRetentionControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
Jira issue: SWATCH-2424
I checked the production database and it seems that there are an huge number (we're speaking about more of millions for every month up to 2022) of snapshots that is being tried to be deleted in a single delete query. 
So, we can't split up the delete query to be done by org_id, because we would have the same problem. The only trustable approach is to limit the query by the number of snapshots. This can be defined using a property and by default is 1000000. 
I could test these changes with such amount of data locally, but yes using the stage data. 
Note that to use this limit, I had to turn the delete query into a native query.
0. podman-compose up
1. create schema `./gradlew liquibaseUpdate`
2. insert the small dataset:
```
insert into org_config values …
```
> SWATCH-2424: Limit the snapshots to purge in batches

- swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
Jira issue: SWATCH-2671
swatch-metrics was producing messages with billing_provider, but not cloud_provider or hardware_type
When hourly tally reads the events, it was defaulting the hardware type to PHYSICAL (org.candlepin.subscriptions.tally.MetricUsageCollector#getHardwareMeasurementType)
Now events from swatch-metrics should include a `cloud_provider` and `hardware_type: 'Cloud'`
This will be happening for Events produced by both **swatch-metrics** and **swatch-metrics-rhel**
```bash
EVENT_SOURCE=rhelemeter PROM_URL="http://10.0.150.94/api/v1" ./gradlew :swatch-metrics:quarkusDev
```
```bash
http POST :8000/api/swatch-metrics/v1/internal/metering/rhel-for-x86-els-payg \
orgId==$ORG_ID$ \
endDate==$(date -d '-2 hours' --utc +%Y-%m-%dT%H:00:00Z) \
rangeInMinutes==180 \ …
```
> SWATCH-2671 Set CloudProvider and hardware type on Event messages

- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/main/resources/liquibase/202407091543-set-default-bucket-measurement-type.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
Jira issue: SWATCH-2712
Properly set the measurement type on buckets while updating hosts during the hourly tally. Prior to this patch the bucket measurement type was always getting set to null.
A liquibase changeset was added that updates the measurement_type of any records with a NULL measurement_type to PHYSICAL, since this is our default in code logic.
The changeset also defaults the measurement_type column to PHYSICAL.
The key to reproducing this issue is to have the nightly tally create a host with an instance_type of HBI_HOST with a last_seen date that is more recent than ANY event targeting a host with the same instance_id that will be processed during an hourly tally.
When this happens, the hourly tally does not update the host's metadata (i.e instance_type), but does update any …
> Set the measurement type when creating buckets

- src/main/resources/liquibase/202407160722-drop-subscription-product-ids-table.xml
- src/main/resources/liquibase/changelog.xml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-2738
Some subscriptions are failing to sync because the child subscription_product_ids records are not being deleted. Since we no longer utilize this table this PR drops it.
IQE Test MR: 
Regresssion.
Tested floorist change against gabi.
> SWATCH-2738: Drop subscription_product_ids table that is no longer in use

- poetry.lock
Jira issue: No issue.  Just a maintenance task.
A new version of `crc-bonfire` has been released.  Additionally the version of `requests` we were using had a CVE against it so Poetry upgraded us automatically.
1. `poetry install`
2. `poetry shell`
3. `bonfire version` == 5.10.1
> Update crc-bonfire and requests

- pr_check.sh
Jira issue: SWATCH-2747
Export Service is OOMKilled and pod is restarted when we run tests. Not using the default resource limits set by bonfire/clowder seems to solve the issue. 
IQE Test MR: Tested all export tests in EE multiple times, no OOM observed
1.
1.
1.
1.
1.
1.
> SWATCH-2747: Adding no-remove-resource for deployed export-service

- src/main/resources/liquibase/202407161214-clean-up-non-payg-measurements-on-rhel-systems.xml
- src/main/resources/liquibase/changelog.xml
Jira issue: SWATCH-2739
There are currently RHEL host records being reported by both HBI and other event sources that resulted in non-payg measurements being created on both hosts. This causes the Instances API to return duplicate hosts when looking up the affected products.
This patch removes all non-payg CORES/SOCKETS measurements from any host that has an instance_type of RHEL Server.
1. Do a checkout of a commit that still has the issue.
```
git checkout -b create-bad-data 487978f28ff564a0272e13487a4999772e7f3c45
```
2. Reset the HBI DB
```
psql -h localhost -U insights insights -c "truncate hosts cascade;"
```
3. Insert a single host into the HBI DB.
```
INSERT INTO public.hosts (id, account, display_name, created_on, modified_on, tags, facts, canonical_facts, system_profile_facts, …
```
> SWATCH-2739: Add liquibase script for RHEL non payg measurement cleanup

- src/main/resources/liquibase/202407231110-subscription-capacity-index.xml
- src/main/resources/liquibase/changelog.xml
Jira issue: SWATCH-2744
Description
===========
The throughput of capacity reconciliation is too low in stage to keep up with the task backlog. By modifying indexes, we can make the primary query slowing down the operation much faster.
Setup
-----
Generate some test data (this step took a couple of minutes on my machine):
```shell
insert into offering(sku) (select 'SKU'||sku from generate_series(1, 1000) sku);
insert into subscription(org_id, subscription_id, sku, start_date) (select org_id, sku::text || '/' || org_id, 'SKU'|| sku, now() from generate_series(1, 1000) org_id full outer join generate_series(1, 1000) sku on 1=1);
insert into subscription(org_id, subscription_id, sku, start_date) (select 'org' || …
```
> SWATCH-2744: Optimize the capacity reconciliation query via indexing

- src/main/resources/application-worker.yaml
- swatch-billable-usage/src/main/resources/application.properties
- swatch-contracts/src/main/resources/application.properties
- swatch-core/src/main/resources/swatch-core/application.yaml
Jira issue: SWATCH-2705
Add the application name to the connection string so queries can be traced back to the application.
1. Create a file /tmp/cdappconfig.json:
```{
"database": {
"adminPassword": "rhsm-subscriptions",
"adminUsername": "rhsm-subscriptions",
"hostname": "localhost",
"name": "rhsm-subscriptions",
"password": "rhsm-subscriptions",
"port": 5432,
"sslMode": "disable",
"username": "rhsm-subscriptions"
},
"kafka": {
"brokers": [
{
"hostname": "localhost",
"port": 9092
}
],
"topics": [
{
"name": "platform.rhsm-conduit.tasks",
"requestedName": "platform.rhsm-conduit.tasks"
},
{
"name": "platform.inventory.host-ingress",
"requestedName": "platform.inventory.host-ingress"
}
]
},
"endpoints": [],
"metadata": {
"deployments": [
{
"image": …
```
> SWATCH-2705: Set ApplicationName on postgresql connection

- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
The Predicate class does not have an implementation of toString, so logging instances of it does not provide useful information.
Jira issue: SWATCH-2746
This is a preliminary PR related to SWATCH-2746.  The message this PR adjusts is so numerous in the logs that it makes it very difficult to actually tell what's going on, so I'm aiming to get this merged to aid the debugging effort.
None.
> SWATCH-2746: Adjust log message that was logging an object with no toString

- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/build.gradle
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/configuration/Channels.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceService.java
- swatch-producer-azure/src/main/resources/application.properties
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureMarketplaceServiceTest.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/test/resources/InMemoryMessageBrokerKafkaResource.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/test/resources/InjectWireMock.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/test/resources/WireMockResource.java
Jira issue: SWATCH-2726
According to the Azure Marketplace API documentation: https://learn.microsoft.com/en-us/partner-center/marketplace-offers/marketplace-metering-service-apis, it can return the following HTTP error codes:
- 400: invalid request 
- 403: forbidden 
- 409: conflict, the usage event has already been successfully reported.
The problem is that we're always throwing the "AzureMarketplaceRequestFailedException: AZURE_MARKETPLACE_API_REQUEST_FAILED: Hint: Check Azure credentials" exception regardless the HTTP error code and also trying other client tenant. 
This exception only makes sense after receiving a 403 forbidden. For the rest, we should log a trace for troubleshooting and stop trying to send the usage (since azure will return the same response).
- Do not try to send …
> SWATCH-2726: Prevent send usages to other azure tenants if not forbidden

- src/main/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableController.java
Jira issue: SWATCH-2410
When filtering by different products, the order the metrics might be diferent: for example, for "rosa": ['Instance-hours', 'Cores'] and for "OpenShift-dedicated-metrics": ['Cores', 'Instance-hours'].
This is because the metrics are defined at this order. 
In the Instances API, we're sorting the metrics by alphabetical order, so we should do the same in the new Subscriptions API v2. This will simplify a lot the test automation.
> SWATCH-2410: sort the metrics alphabetically in Subscription API v2

- src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
- src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
When we were sending tally summary messages, we were unnecessarily sending 32 messages since it was getting filtered on Billable usage component. But before that it was querying table 64 times for just one instance. This update filters those messages upfront to avoid redundant processing.
Jira issue: SWATCH-2701
IQE Test MR: 
QE decided to have it as regression only.
1.  `RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1 SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8882 SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,rh-marketplace,kafka-queue,rhsm-conduit ./gradlew clean :bootRun`
2.  Opt-in the org and insert record in events table for hourly tally
```
INSERT INTO …
```
> SWATCH-2701 Reduce number of tally snapshot queries load to db

- swatch-api/deploy/clowdapp.yaml
- swatch-billable-usage/src/main/resources/application.properties
- swatch-contracts/src/main/resources/application.properties
- swatch-metrics/deploy/clowdapp.yaml
- swatch-metrics/src/main/resources/application.yaml
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
- swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
- swatch-subscription-sync/deploy/clowdapp.yaml
- swatch-system-conduit/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-2772
The update to splunk-otel-javaagent from 1.32.2 to 2.50 (e4b293d440c92c3ae4d24c717fb470d14e4a8dac) introduced a breaking change described at
https://github.com/signalfx/splunk-otel-java/blob/main/CHANGELOG.md#%EF%B8%8F%EF%B8%8F-breaking-changes-%EF%B8%8F%EF%B8%8F-2
The protocol default went from grpc to http/protobuf (seemingly without consideration for the port specified in the endpoint URL which should indicate the desired protocol).  This commit sets the protocol to grpc everywhere. It also sets our application configuration to be sensitive to the value of the OTEL_EXPORTER_OTLP_ENDPOINT environment variable. Previously, we were not respecting this environment variable in some places.
1. Check out the `rhsm/splunk-otel-collector` repo from Gitlab.
1. Edit the …
> SWATCH-2772: Set the OTEL protocol to grpc explicitly.

- src/main/java/org/candlepin/subscriptions/subscription/export/SubscriptionDataExporterService.java
- src/main/java/org/candlepin/subscriptions/tally/export/InstancesCsvDataMapperService.java
- src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
- src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
- swatch-core/schemas/instances_export_csv_item.yaml
Jira issue: SWATCH-2730
Changes:
- Export "inventory_id", "subscription_manager_id" for regular and guests instances (this data is also exported in the JSON format)
- Export "number_of_guests" for regular instances
- Export the guests data if and only if the instance is "RHEL for x86" and the category is HYPERVISOR.
- For the guests data, it will export the following information: display_name, inventory_id, inventory_id, hardware_type, instance_id, subscription_manager_id, last_seen
Note that the linked JIRA also asked to export the "hypervisor_uuid" but this was already exported.
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/806
Updated tests to verify the export of the "number_of_guests" field.
> SWATCH-2730: Map instance guests in in CSV format

- src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
- swatch-core/schemas/billable_usage.yaml
Jira issue: SWATCH-2674
Fully remove the property BillableUsage.id that was replaced by BillableUsage.tally_id
We should already be using the tally_id after [SWATCH-2323](https://issues.redhat.com/browse/SWATCH-2323) was merged/released.
> SWATCH-2674: Remove BillableUsage.id

- clients/quarkus/subscription-client/src/main/java/com/redhat/swatch/clients/subscription/SearchApiFactory.java
- clients/quarkus/subscription-client/src/main/java/com/redhat/swatch/clients/subscription/SearchClient.java
- clients/quarkus/subscription-client/src/main/java/com/redhat/swatch/clients/subscription/StubSearchApi.java
- swatch-common-panache/src/main/java/com/redhat/swatch/panache/PanacheSpecificationSupport.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/OfferingRepository.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionService.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionSyncService.java
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ResourceRolesAllowedTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java
Jira issue: SWATCH-2790
The method `persist` will always perform an INSERT in database and this is causing issues when there are subscriptions with no subscription number, but the subscription ID correctly sets (it sounds weird, but it's what is happening in stage).
Using the method `saveOrUpdate` will correctly update the existing subscription if exists (so the subscription without the subscription number will be correctly fixed).
Note that because the `persist` method is a bit problematic (it happened the same when synchorinizing offerings), I replaced all the methods to `saveOrUpdate`. 
Apart from these changes:
- I created the stub search API which is by default false, because it was very convenient to reproduce the issue locally
- And disable the channels that consumed messages from …
> SWATCH-2790: Use saveOrUpdate when syncing subscriptions

- deploy_ephemeral_env.sh
- deploy_kafka_bridge.sh
- kafka-bridge.yaml
Testing
-------
Reserve an ephemeral environment:
```sh
bonfire namespace reserve
```
Deploy the kafka bridge
```sh
./deploy_kafka_bridge.sh
```
Note the deployment may take a few moments before being available.
Smoke test querying topics in the EE:
```sh
oc rsh $(oc get pod -o name | grep kafka-bridge) curl http://kafka-bridge-bridge-service:8080/topics
```
Port-forward and query topics locally:
```sh
oc port-forward svc/kafka-bridge-bridge-service 8080:8080&
sleep 2
curl http://localhost:8080/topics
kill %1
```
Also see EE logs for the CI pr check to confirm the bridge deployed successfully for CI.
> Add kafka-bridge to EE deployment

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- swatch-product-configuration/src/main/resources/subscription_configs/Ansible/ansible-aap-managed.yaml
Jira issue: SWATCH-2760
This is a screenshot taken from the doc: `Ansible Metering Dimensions & Data Flows`
Ansible has two different servicetype for two metrics. This card supports that behavior with a short term fix. 
IQE Test MR: 
1. Event record:
```
{"sla": "Premium", "usage": "Production", "org_id": "12345678", "event_id": "668800cf-8cb6-4066-b95f-4a2ebc52018b", "timestamp": "2024-08-01T10:00:00Z", "conversion": false, "event_type": "managed-host", "expiration": "2024-06-10T11:00:00Z", "instance_id": "d147ddf2-be4a-4a59-acf7-7f222758b47c", "product_tag": ["ansible-aap-managed"], "record_date": "2024-08-05T19:56:20.811609576Z", "display_name": "automation__cluster_d147ddf2-be4a-4a59-acf7-7f222758b47c", "event_source": "Premium", "measurements": [{"value": 4.0, "metric_id": …
```
> SWATCH-2760 Finalize swatch-product-configuration for ansible-aap-managed

- src/main/java/org/candlepin/subscriptions/event/EventController.java
Jira issue: SWATCH-2760
This card is just to correct service_type for instance-hour metric. Since the below PR got approval today there is no dev or qe required and will be merged.
https://github.com/RedHatInsights/rhsm-subscriptions/pull/3585
> SWATCH-2760 Support both service type for Ansible

- swatch-common-panache/src/main/java/com/redhat/swatch/panache/PanacheSpecificationSupport.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/OfferingSyncService.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionSyncService.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingSyncServiceTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java
Jira issue: SWATCH-2790
These changes address some concerns from Alex in https://github.com/RedHatInsights/rhsm-subscriptions/pull/3592.  Also, the saveOrUpdate method will return the entity that is attached to the transaction context.
> SWATCH-2790: Use persist instead of saveOrUpdate in existing subs

- bin/insert-mock-hosts
- src/main/java/org/candlepin/subscriptions/tally/AccountResetService.java
- src/test/java/org/candlepin/subscriptions/tally/AccountResetServiceTest.java
Jira issue: SWATCH-2742
Calls to ` DELETE .../api/rhsm-subscriptions/v1/internal/rpc/tally/{org_id}` were failing because the code attempted to delete the `account_services` rows while they were still referenced from `hosts`.
I also included a small fix to `insert-mock-hosts` since I discovered that script wasn't working when I was trying to replicate the issue.
Unit test only
> SWATCH-2742: key constraint exception during account reset

- src/main/java/org/candlepin/subscriptions/resource/api/v1/CapacityResource.java
- src/main/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableController.java
- src/main/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableController.java
- src/main/java/org/candlepin/subscriptions/util/InMemoryPager.java
Description
===========
Jira issue: SWATCH-2766
When api requests are made w/ parameters that are out-of-bounds (offset > count), some APIs currently throw exceptions.
Note, I also corrected paging implementation in CapacityResource, which was giving an incorrect `count`.
Testing
=======
Perform the steps with both `main` and these changes.
Setup
-----
```shell
DEV_MODE=true RHSM_RBAC_USE_STUB=true ./gradlew :bootRun
```
Steps
-----
Try each of the following requests:
```shell
http :8000/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Cores \
beginning==2024-07-02T00:00:00.000Z \
ending==2024-08-31T23:59:59.999Z \
granularity==Daily \
use_running_totals_format==true \
billing_category==on-demand \
offset==1000 \
x-rh-identity:$(echo …
```
> SWATCH-2766: Fix 500 errors due to out-of-bounds page params

- swatch-contracts/src/main/java/com/redhat/swatch/contract/config/DebugClientLogger.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionService.java
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionServiceTest.java
- Disable autodiscovery of providers in swatch-contracts
This is causing that the exceptions to be thrown by the clients are not the ones from its exception mappers.
- Enable logging of requests-response for the SearchAPI
This change might help to understand what is going on in SWATCH-2805
> SWATCH-2805: disable autodiscovery of providers in swatch-contracts

- swatch-contracts/deploy/clowdapp.yaml
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/WireMockResource.java
And replace TRUSTSTORE_RESOURCE by TRUSTSTORE_PATH which is the one used in the environment
> SWATCH-2805: Add PRODUCT_KEYSTORE and SUBSCRIPTION_KEYSTORE in swatch-contracts

- swatch-contracts/src/main/java/com/redhat/swatch/contract/config/DebugClientLogger.java
Revert the changes that were made in DebugClientLogger to troubleshoot the product API usages in swatch-contracts.
> SWATCH-2805: DebugClientLogger to print the full body response

- swatch-contracts/src/main/resources/application.properties
There is an existing metrics to track these failures named "swatch_subscription_reconcile_org". We might later choose to write a log alert for a message against the metric:
`swatch_subscription_reconcile_org_seconds_count{exception!=''}`. This can be tested in Grafana.
The same thing was done for the offering sync: https://github.com/RedHatInsights/rhsm-subscriptions/pull/3621
> SWATCH-2805: Ack subscription sync messages when the subs sync fails

- src/main/java/org/candlepin/subscriptions/resource/api/v1/CapacityResource.java
- src/test/java/org/candlepin/subscriptions/resource/api/v1/CapacityResourceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/exception/mapper/BadRequestExceptionMapper.java
Description
===========
Certain operations currently cause a 500, when they should cause a 400. This is due to the JAX-RS exception mapper itself throwing an exception. The BadRequestExceptionMapper in particular doesn't handle when a BadRequestException doesn't have a cause.
Testing
=======
Perform the steps with both `main` and these changes.
Setup
-----
```shell
DEV_MODE=true RHSM_RBAC_USE_STUB=true ./gradlew :bootRun
```
Steps
-----
Request tally for an unsupported granularity
```shell
http :8000/api/rhsm-subscriptions/v1/capacity/products/RHEL%20for%20x86/Cores \
beginning==2024-07-02T00:00:00.000Z \
ending==2024-08-31T23:59:59.999Z \
granularity==Hourly \
use_running_totals_format==true \
billing_category==on-demand \
x-rh-identity:$(echo …
```
> Fix NPE in BadRequestExceptionMapper

- src/main/java/org/candlepin/subscriptions/capacity/files/ProductDenylist.java
- src/test/java/org/candlepin/subscriptions/files/ProductDenylistTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/config/ProductDenylist.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/utils/SubscriptionDtoUtil.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/config/ProductDenylistTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java
Jira issue: SWATCH-2766
When the product id is null we need to return false instead of checking against the denylist
Unit tests to cover places where this is found
> SWATCH-2766: Error reading denylist

- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- swatch-metrics/README.md
- swatch-metrics/src/main/resources/application.yaml
Jira issue: SWATCH-2807
There were two issues that we discovered when I investigated the error: There is an error looking up the contract for org 18267845 when remitting usage
1) We were getting events for sla=Self-Support but, that was not supported while reading awsusagecontext. We changed the matching criteria to _ANY
2) We ignored all the events that lower case premium. Hence we decided to remove the support from prometheus query. 
**Note: QE and dev reviewer I need a second set of eyes to make sure this is not getting doubled bill since we removed the sla criteria from prometheus recording rule.**
There is probably some work left to check for Rosa.
IQE Test MR: 
1. Run <swatch-support-script> rhelemeter-prod to connect to thanos/prometheus production. …
> SWATCH-2807 Fix filtering of prometheus events

- swatch-contracts/deploy/clowdapp.yaml
- swatch-contracts/src/main/resources/application.properties
Jira issue: SWATCH-2816
Remove PRODUCT_URL from the clowdapp contracts service, so this property is only populated from the `application.properties`.  Properly configure the PRODUCT_URL for production in swatch contracts.
> SWATCH-2816: Configure the PRODUCT_URL for prod in swatch contracts

- build.gradle
- src/main/resources/application.yaml
- src/test/java/org/candlepin/subscriptions/deployment/ApiDeploymentTest.java
- swatch-api/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-2675
Description
===========
As explained in spring-projects/spring-boot#39527,
```
server.max-http-request-header-size
```
replaced
```
server.max-http-header-size
```
as of Spring Boot 3.2.
I also elected to simplify our deployments by removing the environment variable, and putting the configuration in `application.yaml` instead.
Testing
=======
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/832
Run the integration test:
```shell
./gradlew :test --tests=ApiDeploymentTest.testApiSupportsLargeRequests
```
You can see the test fail by commenting out the property in `src/main/application.yaml`.
> SWATCH-2675: Fix the property name for spring boot request limit

- swatch-contracts/deploy/clowdapp.yaml
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/WireMockResource.java
The Quarkus Rest Client code requires a keystore or truststore reference to begin with either "file:" or "classpath:".  (See io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder#locateStream). This commit changes the references to the keystores to have the correct prefix.
Additionally, it sets the truststore which had previously been going unset.  It also endeavors to create a standard nomenclature for the references: *_PATH for unprefixed file paths and *_RESOURCE for prefixed paths.
> [HOTFIX] Correct errors with keystore references in swatch-contracts

- swatch-contracts/deploy/clowdapp.yaml
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/WireMockResource.java
The Quarkus Rest Client code requires a keystore or truststore reference to begin with either "file:" or "classpath:".  (See io.quarkus.rest.client.reactive.runtime.RestClientCDIDelegateBuilder#locateStream). This commit changes the references to the keystores to have the correct prefix.
Additionally, it sets the truststore which had previously been going unset.  It also endeavors to create a standard nomenclature for the references: *_PATH for unprefixed file paths and *_RESOURCE for prefixed paths.
None, although the various IntegrationTests do touch on it somewhat.
> Correct errors with keystore references in swatch-contracts

- dependencies.gradle
- settings.gradle
Something changed in how dependabot parses the repository definitions and this was preventing dependabot from checking for gradle plugin updates not present in maven central.
Among other things, this prevented quarkus from being updated by dependabot.
Moving it to another supported location seems to have addressed the issue.
I tested by pushing to my `main` branch on my own fork, and verified in the dependabot logs that all expected repos are checked, e.g.
> proxy | 2024/08/15 15:59:43 [650] GET https://repo.maven.apache.org:443/maven2/com/adarshr/gradle-test-logger-plugin/maven-metadata.xml
> proxy | 2024/08/15 15:59:43 [650] 404 https://repo.maven.apache.org:443/maven2/com/adarshr/gradle-test-logger-plugin/maven-metadata.xml
> proxy | 2024/08/15 15:59:43 [652] GET …
> Move repositories to settings.gradle

- src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
- src/main/java/org/candlepin/subscriptions/retention/TallyRetentionPolicy.java
- src/main/java/org/candlepin/subscriptions/retention/TallyRetentionPolicyProperties.java
- src/main/resources/application-worker.yaml
- src/test/java/org/candlepin/subscriptions/retention/TallyRetentionControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
Jira issue: SWATCH-2424
Delete the inner query "(select distinct c.org_id from org_config c)" by queuing the tasks to purge the tally snapshots by org_id.
I checked the explain using the inner query and without using it, and the delete statement cost decreased significantly. Note that I could reproduce the issue locally (by loading a large dataset), but hopefully these changes and making the deletion by organization ID in a single transaction will improve this situation.
Related to https://github.com/RedHatInsights/rhsm-subscriptions/pull/3487
0. podman-compose up
1. create schema `./gradlew liquibaseUpdate`
2. insert the small dataset:
```
insert into org_config values ('10000177','DB','2020-04-14T20:31:41.660008Z','2020-04-14T20:31:41.660008Z');
insert into tally_snapshots values …
```
> SWATCH-2424: Delete inner query to purge the tally snapshots

- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceStatus.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/exceptions/ContractCoverageException.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/ContractsController.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/model/ContractCoverage.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/ContractsControllerTest.java
- swatch-core/schemas/billable_usage.yaml
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
- swatch-product-configuration/src/main/resources/subscription_configs/Ansible/ansible-aap-managed.yaml
Jira issue: SWATCH-2571
- support enableGratisUsage in the metrics definition
- set "enableGratisUsage" to true only for ansible and the metric "Managed-nodes"
- save the gratis remittance records if any applicable contract has the gratis flag enabled
2. setup database schema: `./gradlew liquibaseUpdate`
3. insert test data:
What is important here is that:
- the contract has the product 'ansible-aap-managed': because it's the only product with the gratis flag enabled
- the contract start date starts after the current month (when writing these steps is '2024-08-01')
```
insert into offering(sku) values ('MW02393');
insert into sku_product_tag(sku,product_tag) values ('MW02393','ansible-aap-managed');
INSERT INTO contracts VALUES ('b3a5e8b7-6260-48f4-a9eb-63a584763ce9', …
```
> SWATCH-2571: Implement billable usage "gratis" status

- dependencies.gradle
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/CapacityReconciliationServiceTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/EnabledOrgsProducerTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingSyncServiceTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/WireMockResource.java
- Bump quarkusVersion from 3.9.2 to 3.12.3
- swatch-contracts: fixing out of memory
Using ` InMemoryMessageBrokerKafkaResource` in tests with `restrictToAnnotatedClass = true` causes the out of memory.
Changing it to only be present in one class with `restrictToAnnotatedClass = false` (default value)
More information about this issue which is getting worse over time is here: https://groups.google.com/g/quarkus-dev/c/JNK7rtADElM/m/a8WsyICRAAAJ?utm_medium=email&utm_source=footer
Only regression testing
> Bump quarkusVersion from 3.9.2 to 3.12.3

- build.gradle
- src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
- src/main/java/org/candlepin/subscriptions/capacity/admin/UsageContextSubscriptionProvider.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
- src/main/spec/internal-subscriptions-sync-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
Fixs an issue with the orgId not being required on calls to the internal subscription API and with the `openApiGenerate` task being broken.
1.  Run `./gradlew clean openApiGenerate` on both `main` and this branch.  It works on this branch
1.  Run 
```
/gradlew :bootRun --args="--spring.profiles.active=kafka-queue,capacity-ingress,api,openshift-metering-worker --rhsm-subscriptions.security.dev-mode=true"
``` 
1. Run
```
http \
:8000/api/rhsm-subscriptions/v1/internal/subscriptions/azureUsageContext \
Content-Type:application/json \
x-rh-swatch-synchronous-request:true \
date==2024-08-08T18:00Z \
productId==rhel-for-x86-els-payg-addon \
sla==Premium \
usage==Production \
azureAccountId==10d15b90-a53a-4201-8087-61d52e0dc85b
```
5. You'll get a …
> Quality of Line Improvements: validation and openApiGeneration

- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsUsageContextLookupApiTest.java
By applying the OffsetDateParamConverterProvider, it forces the query param for timestamps to always consistently drop redundant 0s, For example,
> 2024-08-16T16:32:47.61154261Z
vs.
> 2024-08-16T16:32:47.611542610Z
I also updated the test to use a fixed timestamp that is formatted differently depending on whether `OffsetDateTime.toString` or the param converter provider is used, so that the test will consistently fail if there is a regression.
> Fix flaky test involving timestamp format

- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Jira issue: SWATCH-2826
Description
===========
Fix a bug where cost-managed populated role values were unintentionally causing payg values to not be properly identified.
This happened because we refactored the fingerprinting logic in #3496 so that the role/eng id/level/product name identifiers are consulted first, and the first match short-circuits the rest. Then further filtering is done later on to find a more specific match.
Given current product definitions, this meant that a PAYG rhel fingerprint could be inappropriately initially tagged with "RHEL for x86" and then later have that tag filtered out, leading to no matching tags.
This change moves the payg/non-payg filter up-front, so that this doesn't happen.
Testing
=======
IQE Test MR: TODO
See the added test:
```shell
./gradlew …
```
> SWATCH-2826: Fix PAYG fingerprinting bug with role value

- .tekton/rhsm-push.yaml
- .tekton/swatch-api-push.yaml
- .tekton/swatch-contracts-push.yaml
- .tekton/swatch-metrics-push.yaml
- .tekton/swatch-producer-aws-push.yaml
- .tekton/swatch-producer-azure-push.yaml
- .tekton/swatch-producer-red-hat-marketplace-push.yaml
- .tekton/swatch-subscription-sync-push.yaml
- .tekton/swatch-system-conduit-push.yaml
- .tekton/swatch-tally-push.yaml
An update to the task changed the parameters that need to be passed to it. This is causing a failure to initialize the build on push.
> Konflux: Fix image specification for deprecated-base-image-check task

- .tekton/rhsm-push.yaml
- .tekton/swatch-api-push.yaml
- .tekton/swatch-contracts-push.yaml
- .tekton/swatch-metrics-push.yaml
- .tekton/swatch-producer-aws-push.yaml
- .tekton/swatch-producer-azure-push.yaml
- .tekton/swatch-producer-red-hat-marketplace-push.yaml
- .tekton/swatch-subscription-sync-push.yaml
- .tekton/swatch-system-conduit-push.yaml
- .tekton/swatch-tally-push.yaml
See migration guide at https://github.com/konflux-ci/build-definitions/blob/ff4aa95d49db6d0271446ae2b2fe91df06312441/task/buildah/0.2/MIGRATION.md
> Fix task definition for tekton build-source-image

- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsResource.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/DefaultExceptionMapper.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ContractsResourceTest.java
Jira issue: SWATCH-2676
The /internal/rpc/offerings/sync/{sku} always returns code 200 regardless of the outcome.
In scenarios where that is not the correct response the code will be what is expected
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/809
1. The unit tests have been updated for the new response. They should run correctly.
2. An IQE test is added as noted above.
1. Tests pass
> SWATCH-2676: Update to error handling on SKU sync

- clients/quarkus/subscription-client/src/main/java/com/redhat/swatch/clients/subscription/StubSearchApi.java
- clients/subscription-client/subscription-api-spec.yaml
- src/main/java/org/candlepin/subscriptions/subscription/StubSearchApi.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionService.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionServiceTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java
Jira issue: SWATCH-2804
This method is only used in some unit tests, so it's dead code, and also the API does not work (it does not exist in "https://subscription.api.redhat.com/svcrest/subscription/v5".
> SWATCH-2804: Delete getSubscriptionById from SearchApi

- dependencies.gradle
- swatch-common-panache/src/main/java/com/redhat/swatch/panache/PanacheSpecificationSupport.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsResource.java
Jira issue: SWATCH-2827
- Bump quarkusVersion from 3.12.3 to 3.14.1
- Replace JpaOperations.INSTANCE.getEntityManager() by JpaOperations.INSTANCE.getSession()
- Replace ProfileManager by LaunchMode
> SWATCH-2827: Bump quarkusVersion from 3.12.3 to 3.14.1

- src/main/java/org/candlepin/subscriptions/retention/TallyRetentionController.java
- src/test/java/org/candlepin/subscriptions/retention/TallyRetentionControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
Jira issue: SWATCH-2862
After SWATCH-2791, we did limit the number of snapshots to delete using the "limit" clause. The problem is that one snapshot might have too many measurements to be deleted in the same transaction, so we need to first purge the measurements in batches, and then proceed with the snapshots in batches as well.
0. podman-compose up
1. create schema `./gradlew liquibaseUpdate`
2. insert the small dataset:
```
insert into org_config values ('10000177','DB','2020-04-14T20:31:41.660008Z','2020-04-14T20:31:41.660008Z');
insert into tally_snapshots values ('80f53b83-3919-4e15-a97e-884e28817e12','RHEL for x86','DAILY','10000177','1950-03-05T00:00:00Z','','_ANY','','_ANY','_ANY');
insert into tally_measurements values ('80f53b83-3919-4e15-a97e-884e28817e12','VIRTUAL','INSTANCES' …
```
> SWATCH-2862: Purge tally measurements in batches

- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/RhPartnerClientIntegrationTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/WireMockResource.java
Jira issue: SWATCH-2855
The partner gateway uses nanosecond precision timestamps. Postgres/HSQL only support microsecond precision, so there is a loss of precision when the timestamps are persisted. To see a couple of examples of postgres having less precision, you can try in the database:
```
select '2024-08-24T12:00:00.000000501Z'::timestamptz
select '2024-08-24T12:00:00.000000500Z'::timestamptz
```
Notice that they produce different values.
This is causing a number of side-effects, namely, the equals methods on contracts and subscriptions are treating records as unequal when they shouldn't and, when we use the startDate as a key as seen [here](https://github.com/RedHatInsights/rhsm-subscriptions/blob/0da69bb0a921fedb8e7aadea2e0b5cd0b1027729/swatch-contracts/src/main/java/com/redhat/swat …
> SWATCH-2855: Truncate start/end dates when syncing contracts from IT Partner gateway

- CONTRIBUTING.md
- swatch-contracts/src/main/resources/application.properties
Jira issue: SWATCH-2870
When consuming the Subscription API in the monolith, there were no timeout. Now, in Quarkus, the default timeout is 30 seconds.  I think we should keep using a timeout, but 30 seconds is too low.  As part of these changes, I configured it with a timeout of 120 seconds (2 minutes).  Also, we need to configure the kafka consumer commit strategy to not reject messages if we're still within the acceptable window time.
> SWATCH-2870: Configure rest-client timeouts in swatch-contracts

- swatch-contracts/deploy/clowdapp.yaml
Jira issue: SWATCH-2853
Added: MW00420, MW00423, MW00701, MW00784, MW00787, MW00792, MW01426, MW01429, MCT3267, SER0572, SER0573, SER0587
The following ones were already configured: MW00700, MCT3857
This is a config change only, so no need to add new test coverage.
> SWATCH-2853: Add additional SKUs to the deny list

- swatch-contracts/build.gradle
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformer.java
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/model/MeasurementMetricIdTransformerTest.java
Jira issue: SWATCH-2871
Azure contracts were not setting the correct metricId value on subscription measurements causing errors. This change also includes removing the dependency on internalSubscriptionApi.
Should fix failing IQE tests
> SWATCH-2871: Handle azure contracts measurements in MeasurementMetricIdTransformer

- swatch-contracts/src/main/resources/application.properties
Delete unused env vars in swatch-contracts
> delete unused env vars

- api/rhsm-subscriptions-api-v1-spec.yaml
- src/main/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionResourceV1.java
- src/main/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableController.java
- src/test/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionResourceV1Test.java
- src/test/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableControllerTest.java
- src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerOnDemandTest.java
Jira issue: SWATCH-2505
Remove use of uom for Sku Capacity Report from v1. We will remove the v1 API itself since we have a related card in GUI to use v2 APIs. https://issues.redhat.com/browse/SWATCH-2410
I had following data in database but, seems like we may need more testing other than the happy path. I rely on QE test since I am not sure what exact data is needed to get the response and how the UI queries the backend. 
IQE Test MR: 
Insert records:
```
INSERT INTO public.org_config (org_id, opt_in_type, created, updated) VALUES ('org123', 'PROMETHEUS', '2024-08-06 17:51:43.999993 +00:00', '2024-08-06 17:51:43.999993 +00:00');
```
```
INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, …
```
> SWATCH-2505 Remove use of uom for Sku Capacity Report from v1

- swatch-metrics/src/main/resources/application.yaml
- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
- swatchdog/swatchdog/prometheus/command.py
Jira issue: SWATCH-2175
Adjust PromQL queries to meter ROSA Classic.  ROSA Classic is only metered on
cores and not instance-hours which creates an novel condition where different
metrics for the same product can point to different PromQL templates.
Also correct `swatchdog` so that it can handle heterogeneous template usage
within the same product.
1. Check out the `swatch-support-scripts` repo from
GitLab (contact me if you need a link), `cd` to the checkout.
1. Make sure you have a `~/.token-refresher-prod` file with a token in it.  If
you do not, run
```bash
./fetch-vault-credentials
```
Or download the token in the `token-refresher` namespace for `rhsm-prod` in
Vault.
1. Start a telemeter proxy.
```bash
./telemeter-prod
```
1. Open the link that the script outputs.
1. Generate the …
> SWATCH-2175: Meter ROSA Classic

- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/ContractsController.java
- swatch-billable-usage/src/main/resources/application.properties
Jira issue: SWATCH-2755
Enable wiremock proxy for swatch_contract from swatch_billable_usage
Also change the logic to make gratis identification a bit easier.
```
contract starting in Jan
billable usage in Jan -> gratis
'jan 2' != null && 'jan 2'.isAfter(startOfMonth('jan 4'))
-> true && 'jan 2'.isAfter('jan 1')
-> true && true
billable usage in Feb -> not
'jan 2' != null && 'jan 2'.isAfter(startOfMonth('feb 4'))
-> true && 'jan 2'.isAfter('feb 1')
-> true && false
-> false
```
IQE Test MR: 
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/843
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/850
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/117912 …
> SWATCH-2755 Enable wiremock for internal swatch contract url

- swatch-billable-usage/src/main/resources/application.properties
- swatch-contracts/src/main/resources/application.properties
Jira issue: SWATCH-2907
Currently, our usage causes high cardinality fault tolerance metrics, because smallrye fault tolerance is creating a unique `method` label with a random UUID, see https://github.com/smallrye/smallrye-fault-tolerance/blame/2393d05f2576c7c78c8a216503730a4022fe0577/implementation/core/src/main/java/io/smallrye/faulttolerance/core/apiimpl/FaultToleranceImpl.java#L158 ; I'll look for a more comprehensive fix later, but for now, disabling to reduce the impact on our prometheus instances.
I'll self-merge and hotfix since it is a config only change.
> SWATCH-2907: Disable fault tolerance metrics for now

- swatch-billable-usage/src/main/resources/application.properties
- swatch-common-smallrye-fault-tolerance/src/main/java/com/redhat/swatch/faulttolerance/interceptors/RetryWithExponentialBackoffInterceptor.java
- swatch-contracts/src/main/resources/application.properties
Jira issue: SWATCH-2907
This pull request will also revert the changes in https://github.com/RedHatInsights/rhsm-subscriptions/commit/e1893b4a489e16acfcf9bddbd06c123b18c48460. 
The description in RetryWithExponentialBackoffInterceptor is used to properly populate the metrics.
Before these changes, the metric was:
```
ft_retry_retries_total{method="ce6f4e2e-9d9a-4a8f-97b9-46be9b5d4d3b"} 4.0 # {span_id="041b30a82716b919",trace_id="7dd99bae960ff2fcf893f37205788b5e"} 1.0 1726464250.243
```
After these changes:
```
ft_retry_retries_total{method="com.redhat.swatch.billable.usage.services.TallySummaryMessageConsumer.consume"} 4.0 # {span_id="0b5dfec6270bc635",trace_id="8d361b716a7e357c08aeb7c3ded22f7c"} 1.0 1726464785.796
```
Setup
-----
1. Temporarily add to …
> SWATCH-2907: Populate description in RetryWithExponentialBackoff

- clients/azure-marketplace-client/azure-marketplace-api-spec.yaml
- clients/rh-partner-gateway-client/rh-partner-gateway-api-spec.yaml
- src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
- src/main/spec/internal-subscriptions-sync-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/AzureContractLifecycleIntegrationTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractEntityMapperTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceClientFactory.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureMarketplaceService.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/model/AzureClient.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureMarketplaceServiceTest.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/test/resources/WireMockResource.java
Jira issue: SWATCH-2813
As of ITPART-1180, the clientId associated to a given Azure subscription is available in the /partnerEntitlements response.
When swatch-producer-azure looks up azure usage context and the context includes a clientId value, it should immediately use the azure client configured with the value, and not loop through any other clientId's client instances.
0.- Start postgres: `podman-compose up`
1.- Run data migrations: `./gradlew liquibaseUpdate`
And configure the BASILISK offering with an existing product tag:
```
insert into sku_product_tag values ('BASILISK', 'BASILISK');
```
2.- Start the contracts service: 
```
SWATCH_SELF_PSK=placeholder \
ENTITLEMENT_GATEWAY_URL=http://localhost:8101/mock/partnerApi \
SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8101/moc …
```
> SWATCH-2813: Use specific clientId's credential in swatch-producer-azure

- docs/api-documentation.md
Jira issue: SWATCH-2830
Documentation update to describe how the API catalog generates the documentation page for our API.
Docs only
> SWATCH-2830: Update docs with info on how API docs are generated

- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/OfferingProductTagLookupService.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingProductTagLookupServiceTest.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Jira issue: SWATCH-2864
When syncing the sku "MCT3263" that uses the following eng IDs: [69, 645, 70, 290, 579, 872, 874, 588, 518, 519, 311, 240, 458, 603, 604, 317, 318, 608, 610, 180, 326, 686, 329, 473, 546, 185, 479, 408, 194, 197, 271, 201, 561, 491, 205, 857].
Then it results into mapping these three products: OpenShift Container Platform, rhel-for-x86-eus, RHEL for x86.
This is incorrect since the OpenShift Container Platform product is configured using the "includedSubscriptions" that should exclude the rhel-for-x86-eus, RHEL for x86 products.
After these changes, only the OpenShift Container Platform is used.
Using iqe tooling:
```
app.rhsm_subscriptions.add_sku(sku="MCT3263", quantity=1, count=1, wait=True, product_id="OpenShift Container Platform")
```
Checking the …
> SWATCH-2864: Prune included products when syncing offerings

- swatch-billable-usage/deploy/clowdapp.yaml
- swatch-contracts/deploy/clowdapp.yaml
- swatch-metrics/deploy/clowdapp.yaml
- swatch-subscription-sync/deploy/clowdapp.yaml
- swatch-system-conduit/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-2736
The curl containers do not need nearly as much memory and CPU as we were allocating them.
We can get a better idea of the memory requirements by using the following PromQL:
```
1.5 * (
avg(
quantile_over_time(.99, container_memory_working_set_bytes{namespace='rhsm-prod', container!="POD",container!="", container=~'swatch-billable-usage-purge-remittances|swatch-billable-usage-retry-remittances|swatch-billable-usage-sync|swatch-contracts-offering-sync|swatch-contracts-subscription-sync|swatch-metrics-rhel-sync|swatch-metrics-sync|swatch-system-conduit-sync|swatch-tally-hourly|swatch-tally-purge|swatch-tally-purge-events|swatch-tally-tally'}[60d])
) by (container) > 0) / 1000000
```
This query calculates the memory use of the 99th percentile of a job run and then adds …
> SWATCH-2736: Resize resource requests on curl containers.

- swatch-billable-usage/src/main/resources/application.properties
Expose swagger ui for billable usage component
http://localhost:8002/api/swatch-billable-usage/internal/swagger-ui/
> Expose swagger ui for billable usage component

- swatch-contracts/src/main/java/com/redhat/swatch/contract/product/UpstreamProductData.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/product/UpstreamProductDataTest.java
Jira issue: SWATCH-2925
Description
===========
We started receiving messages having "None" as the value for SOCKET_LIMIT, and this caused a crashloop in swatch-contracts.
Instead, log a warning and interpret the value as null if it's not "Unlimited" or an integer.
Testing
=======
```shell
./gradlew -s swatch-contracts:test \
--tests=UpstreamProductDataTest.testOfferingWithNoneSocketsProcessedSuccessfully
```
See logs like:
> Invalid integer value None for attr CORES
> Invalid integer value None for attr SOCKET_LIMIT
> SWATCH-2925: Handle NumberFormatException for cores/sockets

- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
Jira issue: SWATCH-2935
Added Host.orgId to the sub query when looking up
guest Host's by the hypervisor's isntance_id.
This allows the DB to use indexes for the lookup
and improves performance quite a bit.
Testing
======
The org_id and instance_id to used to test the query can be found in the original issue. Be sure to sub in below.
**OLD QUERY**
```
gabi "explain analyse select distinct h1_0.id,h1_0.billing_account_id,h1_0.billing_provider,h1_0.cloud_provider,h1_0.display_name,h1_0.is_guest,h1_0.hardware_type,h1_0.hypervisor_uuid,h1_0.insights_id,h1_0.instance_id,h1_0.instance_type,h1_0.inventory_id,h1_0.is_hypervisor,h1_0.is_unmapped_guest,h1_0.last_applied_event_record_date,h1_0.last_seen,h1_0.num_of_guests,h1_0.org_id,h1_0.subscription_manager_id from hosts h1_0 where …
```
> SWATCH-2935: Improve find guests DB query

- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/HostTallyBucket.java
Jira issue: SWATCH-2887
After the refactor of the event ingestion, we are handling events in batches ordered only by record date. 
Then, when we handle the events for the same host and the buckets need to be either updated/added/deleted in different transactions, hibernate throws an exception because the bucket version to update or delete does not match with the expected (the bucket version has been updated in other transaction).
Therefore, we are adding a transient "stale" field in the host tally buckets, so we can delete them after processing the batch of events. This way when an event is handled, a previously deleted tally bucket can be "restored" preserving the version.
Added test to reproduce the issue.
> SWATCH-2887: Delete host tally buckets after processing event batches

- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
- swatch-core/schemas/billable_usage.yaml
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java
Jira issue: SWATCH-2910
When existing snapshots have metrics that are not supported by the project (for example: the product "rhel-for-x86-els-payg-addon" does not support the metrics "Sockets" or "Cores"),  Then we were creating invalid billable usage remittance entries that were kept indefinetely on pending state.
Also, we are updating the aws and azure producers to properly update these records with status failed.
Added junit tests to cover these changes.
This addresses a production issue containing ol data in the tally_measurements table.
> SWATCH-2910: Filter snapshots by supported metric in the product

- swatch-contracts/src/main/resources/application.properties
Jira issue: SWATCH-2925
Setting failure strategy to ignore when processing messages from UMB. This follows the same strategy as in offering-sync-task.
> SWATCH-2925: Prevent swatch contract service restarts on failures

- swatch-common-smallrye-fault-tolerance/src/main/java/com/redhat/swatch/faulttolerance/api/RetryWithExponentialBackoff.java
- swatch-common-smallrye-fault-tolerance/src/main/java/com/redhat/swatch/faulttolerance/interceptors/RetryWithExponentialBackoffInterceptor.java
- swatch-common-smallrye-fault-tolerance/src/test/java/com/redhat/swatch/faulttolerance/interceptors/RetryWithExponentialBackoffInterceptorTest.java
- swatch-producer-aws/build.gradle
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/build.gradle
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
- swatch-producer-azure/src/main/resources/application.properties
Jira issue: SWATCH-2960
- Increase timeout to get azure/aws context
- Fix the retry policy in the aws producer service
To be verified in stage.
> SWATCH-2960: Increase timeout to get azure/aws context

- README.md
- src/main/resources/application-worker.yaml
- swatch-subscription-sync/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-2952
* Enable ClowdApp parameter for HBI host table schema location
* Add connection parameter to specify the schema to use during the connection
* HBI will be transitioning its host tables from the public schema to enable logical replication of data, in order to still perform tallies using this database subscription watch needs to be able to connect to an alternate schema.
See `currentSchema` connection parameter information here: https://jdbc.postgresql.org/documentation/use/
```
currentSchema (String) Default null
Specify the schema (or several schema separated by commas) to be set in the search-path. This schema will be used to resolve unqualified object names used in statements over this connection.
```
IQE Test MR: 
1. Deploy to ephemeral environment
2. Populate …
> SWATCH-2952: Support alternate schema for HBI tables

- src/main/resources/liquibase/202409251400-update-subscription-capacity-view-org-id.xml
- src/main/resources/liquibase/changelog.xml
Jira issue: SWATCH-2943
The poor performant query for the subscription table v2 is causing timeout issues in prodution. 
To address the issue, the only required change is to also group by org_id. By doing this, it drastically improves the execution plan of the query.
To verify the increase of performance, I loaded the stage data into my local and checked the execution plan. 
Before these changes, it was:
```
Subquery Scan on scv1_0  (cost=57678.75..57678.80 rows=1 width=265) (actual time=660.374..665.947 rows=0 loops=1)
->  GroupAggregate  (cost=57678.75..57678.79 rows=1 width=275) (actual time=660.373..665.945 rows=0 loops=1)
Group Key: s.subscription_id, o.has_unlimited_usage, o.description, o.sla, o.usage, spt.product_tag, s.start_date
->  Sort  (cost=57678.75..57678.75 rows=1 …
```
> SWATCH-2943: Improve performance of query for subscriptions table v2

- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
- swatch-producer-azure/src/main/resources/application.properties
Jira issue: SWATCH-2960
We increased the contracts API timeout to 2 minutes, but we missed to also increase the consumer topic timeout, so we're seeing errors like the following in stage:
```
SRMSG18231: The record 20723 from topic-partition 'platform.rhsm-subscriptions.billable-usage-hourly-aggregate-10' has waited for 62 seconds to be acknowledged. This waiting time is greater than the configured threshold (60000 ms). At the moment 1 messages from this partition are awaiting acknowledgement. The last committed offset for this partition was 20722. This error is due to a potential issue in the application which does not acknowledged the records in a timely fashion. The connector cannot commit as a record processing has not completed.
```
Moreover, I still see some errors getting the …
> SWATCH-2960: Increase usage hourly consumer timeout and context retries

- swatch-billable-usage/src/main/resources/application.properties
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
Jira issue: SWATCH-2970
- Fix the contract API certificate configuration in azure svc
- Not use the wiremock in swatch producer azure in EE
- Configure aws and azure services the same way to deal with the wiremock
The test "test_verify_multi_cloud_provider_usage" should pass in CI.
> SWATCH-2970: Fix the contract API certificate configuration in azure svc

- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/UsageContextSubscriptionProvider.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/UsageContextSubscriptionProviderTest.java
Jira issue: SWATCH-2971
Force syncing subscriptions is slowing down the GET azureUsageContext and awsUsageContext calls which in turn is causing lag in our swatch-producer-azure and swatch-producer-aws components. We no longer need to perform this sync because we have retries in place so we are removing the forceSync logic.
Regression
> Remove logic to force sync an org during UsageContext lookup

- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
Jira issue: SWATCH-2903
IQE Test MR: 
1. Run azure app
```
SERVER_PORT=8004 WIREMOCK_HOSTNAME=localhost ENABLE_AZURE_DRY_RUN=false SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8000 QUARKUS_PROFILE=dev,wiremock ./gradlew :swatch-producer-azure:quarkusDev
```
1. Send kafka message using producer ` billable-usage-hourly-aggregate`
```
{"windowTimestamp":"2023-12-21T01:10:28Z","aggregateId": "e81bc918-6434-4a58-9192-8a8dd73ec8fb","aggregateKey": {"orgId": "org123","billingProvider": "azure","metricId": "CORES","productId": "rosa"}, "remittanceUuids": ["d125f119-0c98-43f2-a5de-ccf2e8e1ab55"]}
```
1. Logs
```
2024-09-23 23:48:10,154 WARN  [com.red.swa.azu.ser.AzureBillableUsageAggregateConsumer] (vert.x-worker-thread-1) Subscription not found for for …
```
> SWATCH-2903 Marketplace throws vague error when handling Default api exception

- swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java
- swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMeteringControllerTest.java
- swatch-model-events/schemas/event.yaml
Jira issue: SWATCH-2958
If the product label on the telemetry feed is (moa-hostedcontrolplane|moa), then force the billing_marketplace to aws.
Added junit test to reproduce the issue.
> SWATCH-2958: Set billing producer aws when role is moa

- src/main/resources/liquibase/202410021300-update_usages_to_unknown.xml
- src/main/resources/liquibase/changelog.xml
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceStatus.java
Jira issue: SWATCH-2611
All existing billable_usage_remittance older than the release where we started populating the statuses ( Prior to October 1) where status='pending' or status is null records updated to have status='unknown'
0. start database
1. checkout the main branch (to not use the migration script from this PR)
2. start api service to migrate the schema: `SPRING_PROFILES_ACTIVE=api DEV_MODE=true ./gradlew :bootRun`
3. stop the api service
4. create the following usages:
```
-- old usage without status: needs to be updated with unknown
INSERT INTO billable_usage_remittance(uuid, org_id, product_id, metric_id, accumulation_period, sla, usage, billing_provider, billing_account_id, remittance_pending_date, remitted_pending_value)
VALUES ('c2d29867-3d0b-d497-9191-18a9d8ee7830', …
```
> SWATCH-2611: Update existing billable_usage_remittance status to unknown

- src/main/java/org/candlepin/subscriptions/event/EventNormalizer.java
- swatch-model-events/schemas/event.yaml
Jira issue: SWATCH-3006
The uom property was fully removed as part of SWATCH-1233, but this was causing issues in production because the cost-management service was still emitting events using the removed uom property (reported by SWATCH-3006).
Therefore, the uom support was re-added only for ingesting the events and COST-5575 was reported for the cost-management to use the metric_id property.
Create event as below (without product_tag) :
```
{
  "event_source": "cost-management",
  "event_type": "snapshot",
  "account_number": "6064760",
  "org_id": "11602918",
  "service_type": "RHEL System",
  "instance_id": "i-06aae2d3343f8b439",
  "timestamp": "2024-10-05T06:00:00Z",
  "expiration": "2024-10-05T07:00:00Z",
  "measurements": [
    {
      "value": "4",
      "uom": "vCPUs"
    }
  ], …
```
> SWATCH-3006: Support back uom in the events ingestion

- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/ConduitFacts.java
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
Jira issue: SWATCH-2915
Our previous implementation was based off the incorrect assumption that the presence of an aws billing code on a system fact indicated that system was tied to a marketplace subscription.  We've since learned that any system provisioned in aws, regardless of if they're paying for the subscription through aws, gets an aws billing code associated with it.
Systems that were provisioned with a red hat gold image get specifically *bp-63a5400a* as a billing product code.  PM identified this product code as indicating BYOS.  If a billing product code is absent, that also indicates BYOS.  A meeting with PM was had, and it was decided that we would maintain a list of product codes to consider BYOS instead of the opposite.  If a billing product code is present and it doesn't …
> SWATCH-2915 Specify BYOS aws product code

- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceErrorCode.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumer.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumerTest.java
- swatch-core/schemas/billable_usage.yaml
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/AwsThrottlingException.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/ErrorCode.java
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
Jira issue: SWATCH-2995
When AwsThrottlingException is thrown we shouldn't hard fail the tuple. We should try resending it next hour.
IQE Test MR: 
1. Insert Event
`INSERT INTO public.events (event_id, timestamp, data, event_type, event_source, instance_id, org_id, metering_batch_id, record_date) VALUES ('6c57046a-7071-4fc9-a543-650b868edcc0', '2024-06-12 16:00:00.000000 +00:00', '{"sla": "Premium", "org_id": "12345678", "event_id": "6c57046a-7071-4fc9-a543-650b868edcc0", "timestamp": "2024-06-12T16:00:00Z", "conversion": false, "event_type": "snapshot_rhel-for-x86-els-payg_vcpus", "expiration": "2024-06-12T17:00:00Z", "instance_id": "efe37aa6-ac56-41df-8c8a-c260bd498f5b", "product_ids": ["204", "69"], "product_tag": ["rhel-for-x86-els-payg"], "record_date": …
> SWATCH-2995 Retry billable usage when it gets marketplace retry error

- clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApi.java
- clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApiException.java
- clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApiFactory.java
- clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacApiImpl.java
- clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacClient.java
- clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/RbacService.java
- clients/quarkus/rbac-client/src/main/java/com/redhat/swatch/clients/rbac/StubRbacApi.java
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/rbac/RbacApiConfigurationUsingStubsTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/RbacUseStubService.java
Jira issue: SWATCH-3026
At the moment, we have some rbac utilities implemented in swatch-core (see package org.candlepin.subscriptions.rbac).
These changes copy this logic into the Quarkus client rbac module.
Usage:
```java
@RbacClient RbacApi rbacApi;
``` 
If the property "rhsm-subscriptions.rbac-service.use-stub" is true, then the stub rbac api will be used. 
As in the monolith, the "rhsm-subscriptions.rbac-service.stub-permissions" can be used to stub the permissions (a comma separated list of permissions). Default value is "subscriptions:*:*".
Added JUnit test in swatch-contracts to ensure the stub RbacApi works fine.
> SWATCH-3026: Create RbacApi and RbacService into the Quarkus Rbac Client

- swatch-common-panache/src/main/java/com/redhat/swatch/panache/Specification.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/exception/ErrorCode.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/exception/SubscriptionsException.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/SubscriptionCapacityViewMetricConverter.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/HardwareMeasurementType.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityView.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityViewMetric.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityViewRepository.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionRepository.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/InMemoryPager.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/JsonNonNull.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ResourceUtils.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/ApiModelMapperV1.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionResourceV1.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionTableControllerV1.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/ApiModelMapperV2.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionResourceV2.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/security/Identity.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/security/RbacRolesAugmentor.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionResourceV1Test.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionTableControllerV1Test.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionResourceV2Test.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/security/RbacRolesAugmentorTest.java
Jira issue: SWATCH-2843
Moving this endpoint to swatch-contracts while allowing it to still work in the monolith
IQE Test MR: 
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/900
To check locally from this branch with the iqe pr
1. Modify iqe_rhsm_subscriptions/conf/rhsm_subscriptions.default.yaml lines 273, 498, and 502 to match your port of choice for swatch-contracts [8003 for this example]
2. Start swatch-contracts
`SERVER_PORT=8003 QUARKUS_MANAGEMENT_PORT=9003 ./gradlew :swatch-contracts:quarkusDev`
3. Start the monolith (for opt in call)
` DEV_MODE=true SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,kafka-queue,rhsm-conduit ./gradlew clean :bootRun`
4. Create an entry in the org_config table for an org
`insert …
> SWATCH-2843: Implement logic for subscription table endpoints to swatch-contracts

- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceStatus.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumer.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumerTest.java
- swatch-core/schemas/billable_usage.yaml
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java
Jira issue: SWATCH-3024
The scenario we need to test involves the following steps:
Step 1. Tally Summary -> Billable Usage -> Billable Usage Aggregate -> AWS -> Status: Failed with retry after timestamp due to subscription_not_found.
Step 2. Retry Mechanism API Request -> Billable Usage -> Aggregate -> AWS -> Status: Failed with retry after timestamp. The intermediate state transitions from pending to failed instead of failed with not retry after.
Step 3. Tally Summary -> Billable Usage -> Billable Usage Aggregate -> AWS -> Status: Failed with retry after timestamp  due to subscription_not_found (this should exclude usage from the first step).
Step 4. Add a subscription
Step 5. Tally Summary -> Billable Usage -> Billable Usage Aggregate -> AWS -> Status: Success
Step 6. Retry should also …
> SWATCH-3024 Usage doubled due to incorrect retry status

- .tekton/swatch-metrics-hbi-pull-request.yaml
- .tekton/swatch-metrics-hbi-push.yaml
Jira issue: SWATCH-2990
This PR modifies the Tekton files for `swatch-metrics-hbi` so that Konflux
builds occur when PRs are opened against the `hotfix` branch.
Testing was performed in #3849.  `swatch-metrics-hbi` isn't actually present in
the `hotfix` branch so I made the same modifications this PR has to
`swatch-contracts`.  I confirmed that builds occurred with the modified
`on-cel-expression` and did not occur when the commit was reverted.
> SWATCH-2990: Build swatch-metrics-hbi in Konflux on hotfix branch

- src/main/resources/liquibase/202410211200-retry-after-billable-usage-index.xml
- src/main/resources/liquibase/changelog.xml
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/configuration/ApplicationConfiguration.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
- swatch-billable-usage/src/main/resources/application.properties
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageControllerTest.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java
Jira issue: SWATCH-3036
Changes:
- Add an index for billable_usage_remittance.retry_after column
- Query the remittances to be retried in batches and single transactions
- Perform update operations in single transactions (after sending the remittance to kafka)
- If the send operation fails, we need to rollback the remittance to its previous state. 
Added unit test to reproduce the issue.
> SWATCH-3036: Use separated transactions when processing retry remittance

- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageControllerTest.java
When asking for next pages, since at the same time, we're also updating the remittances to clear the retry_after, we won't be consuming all the remittances. 
To address this issue, we'll always asking for the first page which eventually reach zero. Moreover, we will first count the number of remittances and won't process more than this count (this is to avoid edge conditions and process new usages that might lead in endless
IQE Test MR: 
1.
1.
1.
1.
1.
1.
> [HOTFIX] SWATCH-3036: Fix pagination to process remittances retries

- src/main/java/org/candlepin/subscriptions/resource/api/v1/InstancesResource.java
- src/main/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterService.java
- src/test/java/org/candlepin/subscriptions/db/TallyInstanceViewRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/resource/api/v1/InstancesResourceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstanceNonPaygView.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstancePaygView.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyInstancesDbReportCriteria.java
Jira issue: SWATCH-2951
The payg and non payg views are aggregating all the metrics into a single row in jsonb format. And the problem is that we can't easily filter and order using these metrics because it is in jsonb.
So, instead of dealing with the metrics jsonb column, we're now adding a left join to the measurements table (for payg is "instance_monthly_totals" and for non payg is "instance_measurements") - note about performance: that these tables are indexed.
Therefore, we're now using this relationship to filter and also to order the result set. These relationships will not be used when mapping the query result set to the DTO.
Changes
- Removed the distinct in the query since it wasn't necessary (the distinct is done in the view).
- Implement the order using the Hibernate Criteria …
> SWATCH-2951: Allow to filter by metrics in the Instances Table API

- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageControllerTest.java
Jira issue: SWATCH-3036
When asking for next pages, since at the same time, we're also updating the remittances to clear the retry_after, we won't be consuming all the remittances. 
To address this issue, we'll always asking for the first page which eventually reach zero. Moreover, we will first count the number of remittances and won't process more than this count (this is to avoid edge conditions and process new usages that might lead in endless
Added a test to reproduce the pagination issue.
> SWATCH-3036: Fix pagination to process remittances retries

- buildSrc/src/main/groovy/swatch.quarkus-rest-client-conventions.gradle
- buildSrc/src/main/groovy/swatch.spring-boot-rest-client-conventions.gradle
The `withXml` argument was causing the task not to instantiate correctly and so
when you run `gradlew tasks`, you wouldn't get a task list.
1. Run `./gradlew tasks` on `main` and then on this branch.
1. It works on this branch
> Fix `gradlew tasks`

- src/main/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableController.java
- src/main/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableController.java
- src/test/java/org/candlepin/subscriptions/resource/api/v1/SubscriptionTableControllerTest.java
- src/test/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableControllerTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityViewRepository.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionTableControllerV1.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionTableControllerV1Test.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/ProductId.java
Jira issue: SWATCH-2899
The criteria for the On-Demand subscription type needs to be Prometheus enabled or Pay As You Go
1. Start swatch-contracts
`SERVER_PORT=8003 QUARKUS_MANAGEMENT_PORT=9003 ./gradlew :swatch-contracts:quarkusDev`
2. Start the monolith
` DEV_MODE=true SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,kafka-queue,rhsm-conduit ./gradlew :bootRun`
3. Create an entry in the org_config table for an org
`insert into org_config (org_id, opt_in_type,created, updated) values ('5345257','API','2024-06-21T12:50:39.496954Z','2024-06-21T12:50:39.496954Z')`
4. Run the opt-in
`http :8000/api/rhsm-subscriptions/v1/opt-in x-rh-identity:$(echo '{"identity":{"internal":{"org_id":"5345257"}}}' | base64 -w0)
`
1. Run from command line to exercise endpoint …
> SWATCH-2899: Subscription type is On-demand for Paygo products

- src/main/resources/liquibase/202410241408-clear-retryable.xml
- src/main/resources/liquibase/changelog.xml
Description
===========
Clear existing retryable remittances via update statement
Testing
=======
You can run `./gradlew :liquibaseUpdateSql` to see the statement generated:
```sql
UPDATE public.billable_usage_remittance SET retry_after = NULL, status = 'failed' WHERE status='retryable';
```
or you can just run `./gradlew :liquibaseUpdate` and see the resulting changes if you have some test data locally.
> Set existing retryable remittances to failed

- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResource.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
- swatch-billable-usage/src/main/resources/META-INF/openapi.yaml
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageControllerTest.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java
Jira issue: SWATCH-3054
Update billable usage remittance records. Use org_ids to update by orgs, or billing_account_ids to update by billing accounts. Only one of these parameters should be specified at a time, do not provide both.
IQE Test MR: 
1. `SERVER_PORT=8002 QUARKUS_MANAGEMENT_PORT=9002 DEV_MODE=true ./gradlew :swatch-billable-usage:quarkusDev`
2. Insert into billable_usage_remittance table
```
INSERT INTO public.billable_usage_remittance (account_number, org_id, product_id, metric_id, accumulation_period, sla, usage, billing_provider, billing_account_id, remitted_pending_value, remittance_pending_date, retry_after, tally_id, hardware_measurement_type, uuid, billed_on, error_code, status) VALUES (null, '12345678', 'rhel-for-x86-els-payg', 'vCPUs', '2024-06', 'Premium', …
```
> SWATCH-3054 Update reset remittance API to include billing_account_id

- swatch-core/build.gradle
- swatch-core/src/main/java/org/candlepin/subscriptions/resteasy/TraceResponseFilter.java
- swatch-core/src/test/java/org/candlepin/subscriptions/resteasy/TraceResponseFilterTest.java
Jira issue: SWATCH-3041
Added the "traceresponse" header as similarly as done in Quarkus services: https://github.com/RedHatInsights/rhsm-subscriptions/pull/3660
I also spotted that we were not populating the tracing context in spring boot, to fix this, I had to add the `micrometer-tracing-bridge-otel` and `opentelemetry-api`. 
With these two dependencies, we can now get access to the span context, and the trace ID/span ID will be populated when exporting the logs into splunk.
Note that jira SWATCH-3041 also asked for the "Server-Timing" header which is not supported by spring boot services. There are some extensions to enable it like https://github.com/sercasti/spring-httpserver-timings, but we need to carefully evaluate this change, that's why I prefer doing this as a separate task. fyi …
> SWATCH-3041: Populate traceresponse header in spring boot services

- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistry.java
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
- swatch-product-configuration/src/test/resources/cve_2022_1471_product.yaml
- swatch-product-configuration/src/test/resources/cve_2022_1471_swatch_config_index.txt
Jira issue: SWATCH-718
[CVE-2022-1471][1] describes an issue where versions of SnakeYAML prior to
2.0 would deserialize a YAML document and instantiate a class based on
the document contents.  This behavior can lead to issues like
```
!!javax.script.ScriptEngineManager [!!java.net.URLClassLoader [[!!java.net.URL ["http://localhost:8080/"]]]]
```
where untrusted code can be loaded over the internet into the
ClassLoader.
This issue is addressed in version 2.0 where SnakeYAML was altered to no
longer allow so-called "global tags" which are the mechanism used for
this arbitrary deserialization.  There is also the `SafeConstructor`
class which does not do any deserialization beyond primitive Java types
and basic collections.
We, however, need to deserialize to an object of our choice, …
> SWATCH-718: Ensure SnakeYAML does not deserialize arbitrary classes

- CONTRIBUTING.md
- clients/rbac-client/rbac-api-spec.yaml
Jira issue: SWATCH-3034
Changes:
- Join the PermissionsAPI to the AccessAPI (which is related). This way the AccessAPI gets fixed because the `@Path` annotation is now placed at method level
- Added a documentation item in the Quarkus migration section explaining this. 
This change has no effects because we're not using the PermissionsAPI.
Regression testing. 
I applied this change in https://github.com/RedHatInsights/rhsm-subscriptions/pull/3864 and it fixed the CI.
> SWATCH-3034: Fix the Quarkus AccessApi generated client interface

- src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
- src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerMetricsTest.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
The tally counters are tagged by product, metric ID, and billing
provider.  The counter should only be incremented at the finest
granularity level to prevent over-counting.
Jira issue: SWATCH-2299
Recording tally values for product, metrics, and billing providers will allow us to create Grafana dashboards to monitor PAYG metrics and create alerts for PAYG metric discrepancies.
To improve the performance of looping through all the tally snapshots, I used `parallelStream()`.  `parallelStream()` is not a magic bullet though and it can actually be slower in cases where the overhead of delegating to the worker thread pool exceeds the cost of basic iteration.  I did some benchmarking on my machine and found `parallelStream()` to be superior in most cases.  However, my machine is not a pod.  I …
> SWATCH-2299: Use micrometer to count tally values by product, metric, and billing ID

- .pre-commit-config.yaml
- docs/pre-commit.md
Install `rh-multi-pre-commit`.  It's on Gitlab under the `infosec-public/developer-workbench/tools` repo.  The README has information on installation.
Alternatively, you can just install [pre-commit](https://pre-commit.com/) alone, but the RH variant has useful tooling to check for credential leaks and to apply global configuration which I find useful.
If you are using the `rh-multi-pre-commit`, you need to enable local hooks for the rhsm-subscriptions repo with the command `git config --bool rh-pre-commit.enableLocalConfig true`.
You can modify the `~/.config/pre-commit/config.yaml` file to add your own global hooks if you like.
Mine looks like
```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
rev: v4.5.0
hooks:
- id: check-merge-conflict
- id: …
```
> Configure pre-commit hook to run spotlessCheck task

- CONTRIBUTING.md
- buildSrc/src/main/groovy/swatch.quarkus-rest-client-conventions.gradle
- dependencies.gradle
- swatch-billable-usage/build.gradle
- swatch-billable-usage/src/main/resources/application.properties
- swatch-common-kafka/build.gradle
- swatch-common-trace-response/build.gradle
- swatch-contracts/build.gradle
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ResourceRolesAllowedTest.java
- swatch-metrics-hbi/build.gradle
- swatch-metrics/build.gradle
- swatch-model-billable-usage/build.gradle
- swatch-producer-aws/build.gradle
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/build.gradle
- swatch-producer-azure/src/main/resources/application.properties
Bump quarkusVersion from 3.15.1 to 3.16.1
Quarkus 3.16 fixes the opentelemetry traces exporter issue: https://github.com/quarkusio/quarkus/pull/43752
> Bump quarkusVersion from 3.15.1 to 3.16.1

- swatch-metrics/build.gradle
- swatch-metrics/src/main/resources/application.yaml
- swatch-producer-aws/build.gradle
- swatch-producer-aws/src/main/resources/application.properties
Jira issue: SWATCH-2969
These changes do not have effects in stage/production, it's only for better dev experience (pod logs should be in plain text, instead of json format).
1. podman-compose up -d
2. ./gradlew clean build -x test
3. podman-compose -f config/splunk/docker-compose.yml up -d
1. Run application in production mode:
```
java -jar -DENABLE_SPLUNK_HEC=true -DSPLUNK_HEC_URL=https://localhost:8088 -DSPLUNK_HEC_TOKEN=29fe2838-cab6-4d17-a392-37b7b8f41f75 -DSPLUNK_DISABLE_CERTIFICATE_VALIDATION=true -DEVENT_SOURCE=telemeter -DSWATCH_SELF_PSK=placeholder -DSERVER_PORT=8001 swatch-metrics/build/quarkus-app/quarkus-run.jar
```
2. Check traces in splunk: browse to "localhost:8000" and search by "source=swatch-metrics". You should see the same messages formatting as previously. 
1. Build …
> SWATCH-2969: Configure the logging to NOT use json format in Quarkus

- src/main/java/org/candlepin/subscriptions/tally/admin/DataMigrationRunner.java
- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyDataController.java
- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
- src/main/java/org/candlepin/subscriptions/tally/admin/MergeHostsMigration.java
- src/main/spec/internal-tally-api-spec.yaml
- src/test/java/org/candlepin/subscriptions/tally/admin/MergeHostsMigrationTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
Jira issue: SWATCH-2145
We have hosts in the rhsm-subscription table 'hosts' that have duplicate instance ID's. This migration will merge those entries into a single host entry. This will be followed by a new constraint put on the table as well as new logic to determine if a host already exists in this table.
1. import from production:
```
./import-from-gabi.py --host --org-id='5345257'
```
1. Find an instance id that is repeated:
```
select id,instance_id, org_id from hosts where instance_id in (
select instance_id from hosts group by instance_id having count(instance_id) > 1)
and org_id = '5345257'
order by instance_id asc
```
2. Look at the host entries [keep track of the host ids]:
```
select * from hosts where instance_id = 'i-0002481e85a633e0c' order by last_seen desc
```
3. Look at …
> SWATCH-2145: Merge duplicate hosts from different sources in tally

- .tekton/swatch-metrics-hbi-push.yaml
The pipeline was being triggered on pull_request instead of on push.
> Fix event trigger for swatch-metrics-hbi-push pipeline.

- swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/ExportServiceWireMockResource.java
No JIRA. 
The ExportServiceWireMockResource was using a wrong property and hence the wiremock was not receiving requests.
> Fix swatch-contracts test error due to wrong property when stub exports

- .gitignore
- README.md
- config/otel/docker-compose.yml
- config/wiremock/__files/prometheus_success.json
- config/wiremock/docker-compose.yml
- config/wiremock/mappings/prometheus_query_success.json
- config/wiremock/mappings/prometheus_queryrange_success.json
- docs/playbooks/observability.md
- src/main/java/org/candlepin/subscriptions/capacity/CapacityIngressConfiguration.java
- src/main/java/org/candlepin/subscriptions/resource/ApiConfiguration.java
- src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
- stub/mappings/README.md
- swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/TaskConsumerConfiguration.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaConfigurator.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskConsumerFactory.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskProcessor.java
- swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaTaskProducerConfiguration.java
- swatch-core/src/main/java/org/candlepin/subscriptions/tracing/TracingConfiguration.java
- swatch-core/src/main/java/org/candlepin/subscriptions/tracing/TracingService.java
- swatch-core/src/main/resources/logback-spring.xml
- swatch-core/src/main/resources/swatch-core/application.yaml
- swatch-metrics/src/main/resources/application.yaml
Jira issue: SWATCH-3049
Depends on https://github.com/RedHatInsights/rhsm-subscriptions/pull/3883
- Started a playbook to deploy splunk and all the dependant services locally in order to see how the trace is propagated
For now, I've included two integrations:
(1) swatch-metrics <-> swatch-tally: this integration won't propagate the tracing context because we're consuming the events in batches. 
(2) swatch-tally <-> swatch-billable-usage: with these changes, the same trace ID will be used along all the tally hourly operation. 
I foresee that we'll be extending the playbook to verify other integrations in the future.
- Added new SPLUNK_DISABLE_CERTIFICATE_VALIDATION property to disable the certificate validation when posting logs into splunk. This is the same property as used in Quarkus …
> SWATCH-3049: Enable observation in Spring Boot services for Kafka

- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Jira issue: SWATCH-3062
Replace the condition to use "isPaygEligible" instead of "isPrometheusEnabled" to filter by granularity HOURLY in PAYG products. Added test to cover this scenario.
Added a test to reproduce and fix the issue.
IQE steps:
- `application.rhsm_subscriptions.get_today_tally_report(product_id="ansible-aap-managed",granularity="Hourly", metric_id="Managed-nodes", )`
The above call should not fail with:
```
2024-10-30 16:05:39.778 [   ERROR] [iqe_rhsm_subscriptions] (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Server': 'openresty', 'Content-Type': 'application/vnd.api+json', 'Content-Length': '160', 'x-rh-insights-request-id': 'e5567897fb824bad96c994fb02487329', 'traceresponse': '00-718e36745ed04f8f4b2706faeb884561-9ab1e4ac5c2c55cc-00', …
```
> SWATCH-3062: Use isPaygEligible when doing tally hourly in payg products

- swatch-api/deploy/clowdapp.yaml
- swatch-metrics/deploy/clowdapp.yaml
- swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
- swatch-subscription-sync/deploy/clowdapp.yaml
- swatch-system-conduit/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-3066
When investaging the random failure of the test "test_export_instances_payg_product_filters" in SWATCH-3066, I found that we're only seeing the WARN traces when handling the export requests. 
This is because we moved the export handling into a separated module that uses the package "com.redhat.swatch" and the spring boot services are only configured to print the info traces for the package "org.candlepin".
For the Quarkus services, this is already working fine because it's configured as:
```
quarkus.log.level=${LOGGING_LEVEL_ROOT}
quarkus.log.category."com.redhat.swatch".level=${LOGGING_LEVEL_COM_REDHAT_SWATCH}
```
After these changes, the package "com.redhat.swatch" should also be configured for the spring services to print the info traces and see them in splunk. …
> SWATCH-3066: Log traces for "com.redhat.swatch" in spring services

- Dockerfile
- swatch-billable-usage/src/main/docker/Dockerfile.jvm
- swatch-contracts/src/main/docker/Dockerfile.jvm
- swatch-metrics-hbi/src/main/docker/Dockerfile.jvm
- swatch-metrics/src/main/docker/Dockerfile.jvm
- swatch-producer-aws/src/main/docker/Dockerfile.jvm
- swatch-producer-azure/src/main/docker/Dockerfile.jvm
The Quay Security Scanner has shown issues in openssl as high risk. An update on the container will get the security fix needed
.  
View quay.io for advisories for this branch.
The advisory will no longer show high-level security issues around openssl.
> Container update to apply openssl security fix

- dependencies.gradle
- swatch-product-configuration/build.gradle
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java
This dependency was used only in swatch-product-configuration for testing purposes and we don't really need it if we use the ParameterMessageInterpolator configuration instead.
Confirmed that the validations still work.
> Remove the tomcat-embed-el dependency

- src/main/java/org/candlepin/subscriptions/export/ExportRequestConsumer.java
- swatch-common-export/src/main/java/com/redhat/swatch/export/ExportRequestHandler.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/export/ExportRequestConsumer.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/export/SubscriptionDataExporterServiceTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/ExportServiceWireMockResource.java
Jira issue: SWATCH-2936
Log an error trace when this happens when the export request thas has failed. Change the log warn trace when the request does not contain the needed data.  
Added unit tests to cover these scenarios.
> SWATCH-2936: Prevent retries when handling export requests

- README.md
- buildSrc/src/main/groovy/swatch.java-conventions.gradle
- swatch-core/src/main/java/org/candlepin/subscriptions/actuator/CertInfoContributor.java
- swatch-core/src/main/java/org/candlepin/subscriptions/clowder/ClowderJsonEnvironmentPostProcessor.java
- swatch-core/src/main/java/org/candlepin/subscriptions/clowder/ClowderJsonPropertySource.java
- swatch-core/src/main/java/org/candlepin/subscriptions/clowder/KafkaSslBeanPostProcessor.java
- swatch-core/src/test/java/org/candlepin/subscriptions/clowder/ClowderJsonPropertySourceTest.java
Jira issue: SWATCH-3072
Handle unresolved Clowder truststore references better
Truststore handling for the Clowder configuration is complex.  The
Clowder json looks like:
```
"endpoints": [
{
"app": "foo",
"name": "service",
"hostname": "localhost",
"tlsPort": 9443
}
],
"tlsCAPath": "/tmp/ca.pem"
}
```
However, our code generally doesn't want just a bare PEM file.
Instead, we take that path and construct a temporary Java truststore (a
PKCS12 file) from it.  We pass the reference to that keystore along.
Following the pattern of clowder-quarkus-config-source, we also
configure the truststore information on a per-endpoint basis.  To do
that, *if and only if* the endpoint has a `tlsPort` key, then we
generate three synthetic properties: trust-store-path,
trust-store-password, and …
> SWATCH-3072: Better clowder truststore handling

- .tekton/swatch-contracts-pull-request.yaml
- .tekton/swatch-contracts-push.yaml
Jira issue: [KONFLUX-5392](https://issues.redhat.com/browse/KONFLUX-5392)
Increase amount of requested memory for build step as that memory is actualy being used. See this graph from `stone-prd-rh01`:
```
sum by (namespace, pod, container) (
max_over_time(
container_memory_working_set_bytes{container=~".*step-build.*", pod=~".*-build-container-pod", namespace="rh-subs-watch-tenant", pod=~"swatch-contracts-.*"}
[1d])
)
```
Other components might need that change as well (only change in the query below is that `!~`):
```
sum by (namespace, pod, container) (
max_over_time(
container_memory_working_set_bytes{container=~".*step-build.*", pod=~".*-build-container-pod", namespace="rh-subs-watch-tenant", pod!~"swatch-contracts-.*"}
[1d])
)
```
1. IMHO it is just necessary that build job in …
> build: Increase amount of requested memory for build step

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
Jira issue: SWATCH-2297
Relates to https://github.com/RedHatInsights/rhsm-subscriptions/pull/3888
These changes include:
- Rename metric from "rhsm-subscriptions.swatch_metrics_ingested_usage_total" to "swatch_metrics_ingested_usage_total"
- Rename tag from "product_tag" to "product"
- Use Counter.Builder for better readibility. 
This is to follow the same convention as written in the document attached in the JIRA ticket epic.
1. Start the needed services
`RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1 SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8003 SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,kafka-queue,rhsm-conduit ./gradlew :bootRun`
1. Input event messages to …
> SWATCH-2297: Rename metric for ingested usage data from Prometheus

- Jenkinsfile
Jira issue: No JIRA
Use latest tag for kubedock image. 
> Configure Jenkins pipelines to use kubedock latest image

- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
Jira issue: SWATCH-3108
Before these changes, when the system was not an openshift cluster, we were not setting the display name.  When sending the message without display name, the inventory service in [here](https://github.com/RedHatInsights/insights-host-inventory/blob/b4b3f1d6d6ad79cc5ad93ac09f5bbe4df684e232/app/models.py#L97) uses the instance ID as display name.
To prevent the inventory service to use the instance ID as display name, conduit service needs to populate the display name always regardless if it's an openshift system.
Added a test to reproduce the issue.
> SWATCH-3108: Use feeds name when openshift cluster uuid does not exist

- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
`hostedcluster:hypershift_cluster_vcpus:vcpu_hours` is not valid for classic clusters. `rosa:cluster:vcpu_hours` is defined as `hostedcluster:hypershift_cluster_vcpus:vcpu_hours` if it exists, otherwise `cluster:usage:workload:capacity_virtual_cpu_hours`
See the definition at https://github.com/Nikokolas3270/telemeter/blob/086530ffb35ecadbc986c0fca465f362c1bfdcd3/jsonnet/telemeter/rules.libsonnet#L218-L221
> SWATCH-3106: Switch to rosa:cluster:vcpu_hours

- clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
- docs/playbooks/observability.md
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/SystemConduitConfiguration.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/tasks/UpdateOrgInventoryTask.java
Jira issue: SWATCH-3126
- Add orgId MDC to sync orgs workflow
- Add traceId for every logs
- Support for traceresponse for HTTP requests
- Fixed stub rhsm API to work fine with the offset: before these changes, it was using the uuid which is not correct; after these changes the id is used and this identifier should not be autogenerated, so the equal condition works 
When doing a sync for one account. Example:
```
http :8005/api/rhsm-subscriptions/v1/internal/rpc/syncOrg   x-rh-swatch-psk:placeholder   org_id=org123
```
We should see the trace ID in the "traceresponse" response:
```
HTTP/1.1 200 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Content-Length: 20
Content-Type: application/vnd.api+json
Date: Wed, 20 Nov 2024 06:12:47 GMT
Expires: 0 …
```
> SWATCH-3126: Improve traceability for swatch conduit service

- swatch-billable-usage/src/main/resources/application.properties
- swatch-contracts/src/main/resources/application.properties
- swatch-metrics-hbi/src/main/resources/application.properties
- swatch-metrics/src/main/resources/application.yaml
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
In the Prometheus metering endpoint, we will benefit from the response content being JSON formatted instead of plain text. This will allow built-in JSON parsers to be used.
IQE Test MR: 
1. Startup one of the Quarkus apps locally
`./gradlew :swatch-producer-aws:quarkusDev`
1. Run against the Prometheus metrics endpoint
`http :9000/metrics Accept:application/json`
1. The response should be in JSON format
2. You should get the plain text response if the Accept header is left off.
> Allow response content to be json formatted

- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/UsageContextSubscriptionProvider.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ContractsResourceTest.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/UsageContextSubscriptionProviderTest.java
Related to Jira issue: SWATCH-3050 and SWATCH-3125
These changes are about to update the existing counters when getting the subscription usage for aws and azure:
- swatch_missing_subscriptions
- swatch_ambiguous_subscriptions
By adding the "product" dimension. 
After merging these changes, we could add a plot to see the numbers by product to early detect misconfigurations.
Apart from these changes, I converted the existing UsageContextSubscriptionProviderTest to a QuarkusTest, to better cover the SQL query.
> SWATCH-3050: Update usage context subscriptions counters by product

- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java
Jira issue: SWATCH-2303
When usage is processed by swatch-producer-azure, it should increment a counter named "swatch_producer_metered_total" with the amount in metric units, having labels:
product (swatch product tag)
metric_id (metric ID)
billing_provider
status (failed or succeeded)
What about retry: we only care about the final state after Azure returns
Added junit test to ensure the metric is populated.
2. start azure service:
```
SERVER_PORT=8001 QUARKUS_MANAGEMENT_PORT=9001 ./gradlew :swatch-producer-azure:quarkusDev
```
3. send message to topic "platform.rhsm-subscriptions.billable-usage-hourly-aggregate":
```
{"windowTimestamp":"2023-12-21T01:10:28Z","aggregateId": "e81bc918-6434-4a58-9192-8a8dd73ec8fb","aggregateKey": {"orgId": "org123","billingProvider": …
```
> SWATCH-2303: Add a metric to swatch-producer-azure for metered usage

- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
Jira issue: SWATCH-2302
When usage is processed by swatch-producer-aws, it increments a counter named
"swatch_producer_metered_total" with the amount in metric units, labeled with
* product (swatch product tag)
* metric_id (metric ID)
* billing_provider
* status (failed/succeeded/duplicate)
Unit tests are in the PR.
1. 
```
SERVER_PORT=8001 QUARKUS_MANAGEMENT_PORT=9001 ./gradlew :swatch-producer-aws:quarkusDev
```
1. Verify the counters are zero
```
http localhost:9001/metrics | grep swatch_producer_metered_total
```
1. Produce a message for `platform.rhsm-subscriptions.billable-usage-hourly-aggregate`.  I do it with IntelliJ, but use whatever tool you like.
```json
{"windowTimestamp":"2023-12-21T01:10:28Z","aggregateId": "e81bc918-6434-4a58-9192-8a8dd73ec8fb","aggregateKey": {"orgId": …
```
> SWATCH-2302: Capture AWS message transmission statuses in micrometer

- .rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml
- CONTRIBUTING.md
- swatch-contracts/src/main/resources/application.properties
Fixes:
- Production issue: Unlink the panel Export Requests Task Lag (the first panel)
In Prod:
The problem was that this panel was linked to another which didn't exist in prod. Unlinking the panel should fix this.
- Export Requests: update panels for Subscriptions and Instances
- Rename swatch-subscriptions-sync to "Subscriptions & Contracts"
- "Subscriptions & Contracts"
- Added swatch-contracts Memory Used
- Fixed "Subscription Sync Task Lag"
- Added panels for ambiguous and missing subscriptions by product
- Billing Provider Integration
- Added "Azure Marketplace Batch Stats"
- Added "Azure Billable Usage Lag"
- Replaced "Billable Usage Dead Letter Task Lag" by "Billable Usage Status Task Lag"
To extract the JSON from the k8s configmap file:
```
oc extract -f …
```
> Fix grafana dashboard after subscriptions and contracts porting

- bin/caddy.yaml
- bin/iqe-ee-proxy.sh
This proxy will allow us to run iqe tests on a local machine against an Ephemeral instance.
The testing can be done on the command line or in PyCharm and enables line break debugging.
1. https://docs.google.com/document/d/1m5ittnVQjPSs2b4HNtCO7QEeykSqsLeXqLJYw8Cmmxw
2. Please comment on the doc for questions or clarifications.
1. Documented instructions 
1. Once set up, all ephemeral specified tests should run successfully. This mirrors our CI configuration.
> Use Caddy to create iqe test proxy for ephemeral instances

- buildSrc/src/main/groovy/swatch.quarkus-conventions.gradle
This is a workaround for https://github.com/quarkusio/quarkus/issues/38996 which seems to be happening only randomly. Note that disabling the parallel build, it also works.
> Force the compileJava order when building the projects in parallel

- docs/playbooks/observability.md
- swatch-core/src/main/resources/logback-spring.xml
Jira issue: SWATCH-3185
Changes:
- Rename SplunkAppender to FileAppender since this is nothing to do with splunk
- Remove the "org.candlepin" logger in the splunk appender which is causing the duplicates
1.- start kafka, database...: `podman-compose up`
2.- start local splunk: `podman-compose -f config/splunk/docker-compose.yml up -d`
3.- build: `./gradlew clean build -x test`
4.- start the tally service:
```
java -DENABLE_SPLUNK_HEC=true \
-DSERVER_PORT=8003 \
-DMANAGEMENT_PORT=9003 \
-DSPLUNK_HEC_URL=https://localhost:8088 \
-DSPLUNK_HEC_TOKEN=29fe2838-cab6-4d17-a392-37b7b8f41f75 \
-DSPLUNK_DISABLE_CERTIFICATE_VALIDATION=true \
-DSPLUNK_SOURCE_TYPE=springboot_server \
-DINVENTORY_DATABASE_SCHEMA=hbi \
-Dspring.profiles.active=worker,api,kafka-queue \
-jar …
```
> SWATCH-3185: Fix duplicated traces in splunk for spring boot services

- swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryService.java
- swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java
Jira issue: SWATCH-3015
The key in a Kafka message ensures that the messages the same key are delivered to the same Kafka partition and the order of messages arrival is maintained.  This should help host-inventory to to avoid host-duplication.
Add "key: org_id" to Kafka messages destined for "Host-Inventory" for creating/update hosts.
2. RHSM_USE_STUB=true DEV_MODE=true ./gradlew :swatch-system-conduit:bootRun
3. http :8000/api/rhsm-subscriptions/v1/internal/rpc/syncOrg   x-rh-swatch-psk:placeholder   org_id=7687094
4. verify key is now the org_id in http://localhost:3030/#/cluster/default/topic/n/platform.inventory.host-ingress/
Before these changes, the key was empty:
After these changes, the key is property setup:
> SWATCH-3015: Add the kafka key with "org_id" to host-inventory topic

- swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml
`hostedcluster:hypershift_cluster_vcpus:vcpu_hours` is not valid for classic clusters. `rosa:cluster:vcpu_hours` is defined as `hostedcluster:hypershift_cluster_vcpus:vcpu_hours` if it exists, otherwise `cluster:usage:workload:capacity_virtual_cpu_hours`
See the definition at https://github.com/Nikokolas3270/telemeter/blob/086530ffb35ecadbc986c0fca465f362c1bfdcd3/jsonnet/telemeter/rules.libsonnet#L218-L221
> [HOTFIX] Switch to rosa:cluster:vcpu_hours

- Dockerfile
- swatch-api/deploy/clowdapp.yaml
- swatch-billable-usage/src/main/docker/Dockerfile.jvm
- swatch-contracts/src/main/docker/Dockerfile.jvm
- swatch-metrics-hbi/src/main/docker/Dockerfile.jvm
- swatch-metrics/src/main/docker/Dockerfile.jvm
- swatch-producer-aws/src/main/docker/Dockerfile.jvm
- swatch-producer-azure/src/main/docker/Dockerfile.jvm
- swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
- swatch-subscription-sync/deploy/clowdapp.yaml
- swatch-system-conduit/Dockerfile
- swatch-system-conduit/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-3128
I confirmed that we're already using kafka-clients >=3.8.0, so we need to explicitly set the JVM system property "org.apache.kafka.automatic.config.providers=none" to avoid this security risk. 
> SWATCH-3128: Disabling Kafka client config providers

- Dockerfile
- swatch-billable-usage/src/main/docker/Dockerfile.jvm
- swatch-contracts/src/main/docker/Dockerfile.jvm
- swatch-metrics-hbi/src/main/docker/Dockerfile.jvm
- swatch-metrics/src/main/docker/Dockerfile.jvm
- swatch-producer-aws/src/main/docker/Dockerfile.jvm
- swatch-producer-azure/src/main/docker/Dockerfile.jvm
- swatch-system-conduit/Dockerfile
Jira issue: SWATCH-3134
The “OmitStackTraceInFastThrow” was first introduced in JDK5. According to the release note of JDK5, the compiler in the server VM stops outputting the stack trace of the exceptions which have been thrown a few times. This is a one of optimizations which happens in C2 compile. And by adding “-XX:-OmitStackTraceInFastThrow”, we can disable this optimization.
This seems to be the cause why we're not getting the full stacktraces in production.
> SWATCH-3134: Adding JVM config to disable the trimming of stack traces

- src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
- src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceWorkerConfiguration.java
- src/main/java/org/candlepin/subscriptions/tally/contracts/ContractsConfiguration.java
Starting in late August, a commit got introduced that added a bean with a name
already in use.  Normally, that type of issue would lead to an immediate
deployment failure, but in this case, the redundant bean is only present in a
lesser used profile: rh-marketplace.
This commit renames the conflicting bean.
1. Deploy the application with only the stock configuration.  I was unaware of
this issue for a long time as I have a custom
`confign/application.properties` file with a reduced set of profiles.
Consequently, I never saw this error until someone else brought it to my
attention.
```
./gradlew :bootRun --args="--spring.config.location=classpath:application.yaml"
```
1. Run the above command on `main`.  Deployment fails.
1. Run the above command on this branch. …
> Fix gradle bootRun command

- src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java
- src/test/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollatorTest.java
Jira issue: SWATCH-3186
From the Peeking Collections javadocs, the `.peek()` method might return null values, so we need to prevent the null pointers to happen.
Digging further into this issue, the root cause is that when peeking elements, we're also consuming the inner iterator without checking the iterator.hasNext() method: https://github.com/google/guava/blob/3644d6155fdeca4c97d51329b66d1272d2905735/guava/src/com/google/common/collect/Iterators.java#L1220
So, it sounds like a bug in the peeking collection.
Added JUnit test to reproduce scenario.
To reproduce exactly the same issue than in production, you would need to load the HBI and Swatch data of a given organization (more details in the JIRA ticket) and run the tally snapshots:
```
http PUT …
```
> SWATCH-3186: Fix null pointer exception when tallying snapshots

- init_dbs.sh
- postgresql.conf
- src/main/resources/liquibase/202412041537-primary-keys-on-all-tables.xml
- src/main/resources/liquibase/changelog.xml
- swatch-common-testcontainers/src/main/java/org/candlepin/testcontainers/SwatchPostgreSQLContainer.java
- swatch-contracts/src/main/resources/db/202412051144-primary-keys-on-changelog-table.xml
- swatch-contracts/src/main/resources/db/changeLog.xml
Jira issue: SWATCH-3167
For logical replication, Postgres requires that all tables have a
primary key.  This commit adds primary keys to tables like the
databasechangelog and join tables.  It also adds the
"pg_stat_statements" library to our database container so that we can
monitor queries in development.
"A published table must have a 'replica identity' configured in order to
be able to replicate UPDATE and DELETE operations, so that appropriate
rows to update or delete can be identified on the subscriber side. By
default, this is the primary key, if there is one."
From https://www.postgresql.org/docs/12/logical-replication-publication.html
On my system, adding the PKs on a fully loaded database took a couple seconds.
1. Run the following query and observe the tables lacking a primary …
> SWATCH-3167: Add primary keys to all tables

- swatch-common-panache/build.gradle
Some CI jobs are randomly failing due to:
```
Execution failed for task ':swatch-common-panache:quarkusAppPartsBuild'.
> There was a failure while executing work items
> A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
> Configuration validation failed:
java.util.NoSuchElementException: SRCFG00011: Could not expand value platform.quarkus.native.builder-image in property quarkus.native.builder-image
```
These changes try to fix these failures.
> Fix random build failure in swatch-common-panache

- swatchdog/swatchdog/deploy/command.py
Version 2.0 of the openshift Python library changed the import name from
`openshift` to `openshift_client`.  See
https://github.com/openshift/openshift-client-python/issues/75
1. `poetry install` to make sure you have the latest dependencies
1. `poetry run swatchdog prometheus promql --product rosa`
1. The above command will fail on `main` with an import error
1. It will succeed on this branch
> Fix swatchdog

- src/main/resources/liquibase/202412041537-primary-keys-on-all-tables.xml
- swatch-contracts/src/main/resources/db/202412051144-primary-keys-on-changelog-table.xml
The "is not a superuser" problem crops up more in the ephemeral environments.  In stage and production, we run as the postgres user and have superuser permissions.
> Update a comment to make it more accurate

- Jenkinsfile
Since new jenkins cluster default service account do not have enough permissions, this PR is to fall back to using old cluster in the meanwhile. 
Old cluster definition added in https://gitlab.cee.redhat.com/smqe/swatch-ci/-/merge_requests/332 
This change can be revered once Kubedock issues/122 or CCITJEN-2066 fixed.
> Use ocp-c1 cloud for running pr checks

- src/main/resources/liquibase/202501081035-remove-backup-tables.xml
- src/main/resources/liquibase/changelog.xml
Jira issue: SWATCH-3167
There are 3 backup tables in stage and production that we do not need any
longer.  These tables do not have primary keys and would, therefore, interfere
with logical replication.
1. `./gradlew liquibaseUpdate`
1. In a dev set up, liquibase will run, but nothing will happen because it's
unlikely you'll have those tables.  You'll be able to see the changesets as
records in the `databasechangelog` table, however.
> SWATCH-3167: Remove unused tables

- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceErrorCode.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageMapper.java
- swatch-billable-usage/src/main/resources/application.properties
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageMapperTest.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/TallySummaryMessageConsumerTest.java
Jira issue: SWATCH-3211
Using `mp.messaging.incoming.tally-summary.failure-strategy=ignore` will prevent the service to enter in a crash loop exceptions state when consuming invalid messages.
An invalid message might be a message using an unexisting metric.
With these changes, we prevent remittances to be created for invalid snapshots and configure the tally snapshot consumer to ignore failures.
IQE Test MR will be added as part of [SWATCH-3141](https://issues.redhat.com/browse/SWATCH-3141)
1.- podman compose -f docker-compose.yml up
2. apply liquibase migrations: `./gradlew liquibaseUpdate`
3.- start billable usage service: `./gradlew :swatch-billable-usage:quarkusDev`
4.- send message to the topic "platform.rhsm-subscriptions.tally" with invalid metric ID: 
```json
{"org_id": "org123", …
```
> SWATCH-3211: Ignore failures when consuming tally summary messages

- swatch-producer-azure/src/main/resources/application.properties
Jira issue: SWATCH-3152
IQE Test MR: 
[MR 987](https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/987)
1. I used an ephemeral instance and the local IQE proxy
1. Run the tests in the IQE MR
1. Tests pass
2. Observe the swatch-azure-producer-service pod for a few minutes to confirm that it does not restart. You will also see the bad and good messages in the logs for that pod.
> SWATCH-3152: Configure swatch-producer-azure to skip bad messages

- src/main/resources/liquibase/202412091327-drop-hardware-measurement-type-from-billable-usage-remittance.xml
- src/main/resources/liquibase/changelog.xml
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceEntity.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceFilter.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceSummaryProjection.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageMapper.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepositoryTest.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageMapperTest.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
- swatch-core/schemas/billable_usage.yaml
- swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
Jira issue: SWATCH-3177
This bug happens when the incoming events are in conflict (2 events with the same instance, metric and timestamp) and the hardware measurement type (HMT) is different. In the case of the reproducer events, the rhelemeter event does not specify the HMT which will get defaulted to PHYSICAL, not AWS. Since remittance uses the HMT to determine the current total remittance, it returns an incorrect value for the total when the usage for the second event is received.
This only happens when a conflict occurs and the value changes, since the measurements for the hour are replaced when tallied.
When determining the current remittance total, the billable usage
component no longer considers the hardware_measurement_type. As
such, when TallySummary messages are created during …
> SWATCH-3177 Fix invalid remittance calculation when an amendment is applied

- swatch-producer-aws/src/main/resources/application.properties
Jira issue: SWATCH-3153
IQE Test MR: 
IQE tests will come later. This needs to be expedited.
1. I used an ephemeral instance and the local IQE proxy
1. Run the tests in the IQE MR
1. Tests pass
2. Observe the swatch-producer-aws-service pod for a few minutes to confirm that it does not restart. You will also see the bad and good messages in the logs for that pod.
> SWATCH-3153: Configure swatch-producer-aws to skip bad messages

- src/main/java/org/candlepin/subscriptions/tally/export/InstancesCsvDataMapperService.java
- src/test/java/org/candlepin/subscriptions/tally/export/InstancesCsvDataMapperServiceTest.java
- src/test/java/org/candlepin/subscriptions/tally/export/InstancesDataExporterServiceTest.java
- swatch-core/schemas/instances_export_csv_item.yaml
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/util/MetricIdUtils.java
Jira issue: SWATCH-3247
When exporting instances that use the "ansible-aap-managed" product, we were not exporting the configured Managed-nodes metric.
I've added a test, so we don't forget to add the mapping when adding a new metric in the future. Also, I covered the ansible export in our integration tests.
MR test: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1008
Added integration tests as part of the pull request changes.
> SWATCH-3247: Add missing "Managed-nodes" metric when exporting instances

- bin/iqe-ee-proxy.sh
- docs/iqe-ee-proxy.md
- stub/wiremock.yaml
After following the guide for standing up the iqe proxy, I was encountering errors running my IQE tests that were due to not being able to connect to various services.  This PR:
- Updates the name of the wiremock service when it's deployed to match the naming convention of the other pods we deploy
- Updates the iqe proxy script so wiremock-service:8101 and swatch-mock-prometheus-test-service:9090 get their ports forwarded
- Adds a reminder to the docs/iqe-ee-proxy.md guide that you need to make sure all the parts and pieces are 
Following the iqe-ee-proxy.md guide and then running this iqe test locally is successful
```
iqe tests plugin rhsm_subscriptions -m ephemeral -k test_verify_metering_operation_for_events_received_from_prometheus_for_openshift_products
```
> Add test helper pods to iqe proxy

- docs/iqe-ee-proxy.md
Follow the iqe ee proxy steps and when running a test directly from pycharm, you should see the logs as in:
Before these changes, when not adding the "--log-cli-level" argument, I only saw Passed or Failed :/
> Update iqe ee proxy documentation to enable live logging

- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/AwsThrottlingException.java
- swatch-producer-aws/src/main/resources/application.properties
Jira issue: SWATCH-3147
Depends on https://github.com/RedHatInsights/wiremock-consoledot/pull/6
Configure swatch-producer-aws to use wiremock proxy in ephemeral.
By default, wiremock is configured to keep using the moto instance. 
Only when the usage request contains the text marker "_UseWiremock_" in any field, then the wiremock instance will be used.
MR Test: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1021
> SWATCH-3147: Configure swatch-producer-aws to use wiremock proxy in ephemeral

- deploy_ephemeral_env.sh
- swatch-contracts/src/main/resources/application.properties
Jira issue: SWATCH-3267
he errors at the swatch contracts service start up:
```
2025-01-31 06:44:51,427 INFO [io.sma.rea.mes.amqp] (executor-thread-1) {} SRMSG16212: Establishing connection with AMQP broker
2025-01-31 06:44:51,532 ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-0) {} javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
```
SWATCH contracts should be able to start up correctly in EE.
> SWATCH-3267: Disable UMB in swatch-contracts in ephemeral environment

- swatch-billable-usage/src/main/resources/application.properties
Jira issue: SWATCH-3141
IQE Test MR: 
[IQE MR](https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/992)
1. I used an ephemeral instance and the local IQE proxy
1. Run the tests in the IQE MR
1. Tests pass
2. Observe the swatch-billable-usage-service pod for a few minutes to confirm that it does not restart. You will also see the bad and good messages in the logs for that pod.
> SWATCH-3141: Configure swatch-billable-usage to skip bad messages

- docker-compose.yml
Without this fix, using podman-compose 1.3.0, `podman-compose up -d` hangs.
Note that I still get an error when running `podman-compose up -d`, but it doesn't seem to affect the overall environment:
```
Error: generating dependency graph for container 60ea07ff4907cf77c664182241a3b4a66b6ade80d88d00b4be40197be97b6ef2: container b05578d38195fd57a77aef16d5e54d606d880af91b48f74e31f9c8a620a7ad6c depends on container 7d69dc95d14b6902ee820274f671eb63bd6420c660d0071a02a8c22404c08edd not found in input list: no such container
Error: unable to start container "60ea07ff4907cf77c664182241a3b4a66b6ade80d88d00b4be40197be97b6ef2": generating dependency graph for container 60ea07ff4907cf77c664182241a3b4a66b6ade80d88d00b4be40197be97b6ef2: container …
```
> Fix health check and dependency in compose file

- swatch-contracts/src/main/resources/application.properties
Jira issue: SWATCH-3267
This reverts commit 9467194ebbc2596525b3fbe0f72428c7a4293079 after the merge of
MR 131623 now that the certificates have been renewed.
> SWATCH-3267: Re-enable UMB in ephemeral

- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/BillableUsageAggregateStreamTopologyTest.java
Jira issue: SWATCH-3294
This is caused because the tickets SWATCH-2301 and SWATCH-2304 were about to create the same metric in two different places, but the changes in SWATCH-2304 didn't include an special status "aggregated", so we're couting the same metric twice with the same values.
After speaking with Kevin Howell, we aggreed to replace the one from SWATCH-2304 to use a new metric counter named "swatch_billable_usage_total_aggregated" to avoid confusions.
2. setup database schema: `./gradlew liquibaseUpdate`
3. start the tally worker: `RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1 SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8003 SERVER_PORT=8000 …
> SWATCH-3294: Rename "swatch_billable_usage_total" to aggregated

- src/main/java/org/candlepin/subscriptions/event/EventController.java
- src/main/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducer.java
- src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
- src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java
- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerMetricsTest.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
- swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/model/Quantity.java
- swatch-billable-usage/src/main/resources/application.properties
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/BillableUsageAggregateStreamTopologyTest.java
- swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java
- swatch-contracts/src/main/resources/application.properties
- swatch-metrics-hbi/src/main/resources/application.properties
- swatch-metrics/src/main/resources/application.yaml
- swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
- swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
- swatch-producer-azure/src/main/resources/application.properties
- swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/MetricId.java
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
Jira issue: SWATCH-3295
Depends on https://github.com/RedHatInsights/rhsm-subscriptions/pull/4157
All the payg metrics should have the same tags, units and use the same format to be used in the grafana dashboard.
This pull request addresses the following changes:
- Change format of metric ID to use the metric ID code instead of the uppercase format
Some metrics were using one format or the another. All the metrics should use the same one. 
- Wrong billing_provider_id in "swatch_tally_tallied_usage_total", it should be "billing_provider"
- The metric "swatch_tally_tallied_usage_total" was double counting. Fixed by reusing the logic to exclude duplicate snaps.
- The metrics "swatch_contract_usage_total", "swatch_billable_usage_total" and "swatch_producer_metered_total" were expressed in …
> SWATCH-3295: Normalize the payg metrics to use the same tags and format

- .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.configmap.yaml
Jira issue: SWATCH-2306
The metrics to use for each are:
- Metered, which is the first "phase". It's swatch_metrics_ingested_usage_total: Added by SWATCH-2297
- Tallied, which is the second one: It's swatch_tally_tallied_usage_total: Added by SWATCH-2299
- Covered by contract: It's swatch_contract_usage_total : Added by SWATCH-2300
- Billing pending: It's swatch_billable_usage_total Added by SWATCH-2301
- Remitted: It`s swatch_producer_metered_total  Added by SWATCH-2302
The new "Metered end-to-end stats" panels look like as:
Which displays the values by the select product(s), metric and billing provider.
As part of this task, I found the following issues:
- The metric "swatch_billable_usage_total" is being counting twice: SWATCH-3294
- The metric "swatch_tally_tallied_usage_total" is …
> SWATCH-2306: Create grafana dashboard for PAYG metrics

- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityViewRepository.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
Jira issue: SWATCH-2536
IQE Test MR: 
../rhsm-subscriptions/bin/iqe-ee-proxy.sh
iqe tests plugin rhsm_subscriptions -k test_unlimited_sku_capacity --pdb
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1056
1. Insert data from stage using the script or manually 
Using script
`import-from-gabi.py --org-id='17685818' --subscriptions --offerings --contracts`
`GABI_URL=https://gabi-subscription-watch-stage.apps.crcs02ue1.urby.p1.openshiftapps.com OCP_CONSOLE_TOKEN=$(oc whoami -t) gabitabi -q "SELECT * from sku_product_tag;" --sep "," -o "sku_producttag_full_data1.csv"`
Using manually:
Offering
```
INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, …
```
> SWATCH-2536 Subscription doesn't show if sku socket limit is unlimited

- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionCapacityViewRepository.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
Reverts RedHatInsights/rhsm-subscriptions#4188
To check what was the outcome of the stage before the merge
> Revert "SWATCH-2536 Subscription doesn't show if sku socket limit is unlimited"

- .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.configmap.yaml
In order to make it easier to see the nature of changes in the graphs over time and so that they don't appear monotonically increasing, make the interval configurable at the dashboard level & include $__range so that you can still see the view over the full date range being viewed, but also the change over the past 1,2,6,12, or 24 hours.
Extract the new dashboard json using `oc extract -f .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.configmap.yaml --confirm`
Once you extract it from the .yaml that's checked into this repo, you can import it into the stage instance of grafana by going to `Dashboards -> +Import` from the left nav.
> Update the Subscription Watch - PAYG metrics Grafana dashboard to make the interval configurable

- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java
This test was failing because we were adding two months in the test, but comparing this date with 60 days which is not the same for months that do not have 30 days.
CI is green.
> Fix shouldSyncSubscriptionsSkipSubIfTooExpired

- api/rhsm-subscriptions-api-v2-spec.yaml
- src/main/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableController.java
- src/test/java/org/candlepin/subscriptions/resource/api/v2/SubscriptionTableControllerTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionTableControllerV2Test.java
Jira issue: SWATCH-3338
When querying subscriptions for a given product id, the billing_account_id should be included in the result. This will enable filtering the subscription list on the GUI side without separate calls every time the billing_account_id is changed.
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1060
1.- Make sure you have a subscription in your database
2.- Start API service or swatch-contracts service
3.- Opt In for org ID of the subscription present in database
3.- Call the subscription api v2 endpoint:
```
curl -X GET \
'http://localhost:8101/api/rhsm-subscriptions/v1/subscriptions/products/rosa' \
-H 'x-rh-identity: <IDENTITY>'
```
And the reponse should include the new …
> SWATCH-3338: Add billing_account_id to SkuCapacity in subscriptions api v2

- .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.configmap.yaml
Jira issue: SWATCH-3358
Before these changes, the products and metrics to be filtered are dynamically inspected using the metric "swatch_metrics_ingested_usage_total". The problem is that this metric is used when processing the events in the swatch-metrics, but only for the events coming from the "prometheus" event source (see [here](https://github.com/RedHatInsights/rhsm-subscriptions/blob/169b8b0d6cd935e0549be40bf37205650a0a70ba/src/main/java/org/candlepin/subscriptions/event/EventController.java#L380)). 
Therefore, let's use the "swatch_billable_usage_total" metric for all the variables in the dashboard, so we can see a more stable list of products, metrics, and others.
Extract the new dashboard json using oc extract -f .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.c …
> SWATCH-3358: Use the metric "swatch_billable_usage_total" in the grafana dashboard to resolve all the variables

- swatch-billable-usage/src/main/resources/application.properties
- swatch-contracts/src/main/resources/application.properties
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
This is a workaround for an issue running quarkusDev gradle task after bumping the quarkusVersion to 3.19.1.
See https://github.com/quarkusio/quarkus/issues/46662
The quarkusDev gradle tasked stopped working because of that version bump.  It was resulting in this stack trace
```
./gradlew :swatch-contracts:quarkusDev
```
```
2025-03-06 15:34:26,557 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[error]: Build step io.quarkus.devui.deployment.menu.EndpointsProcessor#createEndpointsPage threw an exception: java.lang.IllegalArgumentException: Specified path is an invalid URI. Path was /api/${quarkus.application.name}/internal/swagger-ui
at …
```
> Hardcode the quarkus application name in quarkus.swagger-ui.path property

- swatch-contracts/src/main/java/com/redhat/swatch/contract/product/UpstreamProductData.java
- swatch-contracts/src/main/resources/product-stub-data/engprods-RH02781MO.json
- swatch-contracts/src/main/resources/product-stub-data/engprods-SVCRH02781.json
- swatch-contracts/src/main/resources/product-stub-data/tree-RH02781MO_attrs-true.json
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingSyncServiceTest.java
Jira issue: SWATCH-3348
The problem is when having the root sku with an attribute METERED: 'N', and a derived sku with an attribute METERED: 'Y', we're overwriting the root attribute with the derived attribute.
This is because we're ignoring the attributes with value 'n'.
Added a test that reproduces the issue.
> SWATCH-3348: When offering sync, allow attributes with values 'N'

- api/rhsm-subscriptions-api-v1-spec.yaml
- src/main/java/org/candlepin/subscriptions/resource/api/v1/InstancesResource.java
- src/main/java/org/candlepin/subscriptions/security/OptInChecker.java
- src/main/java/org/candlepin/subscriptions/security/auth/ReportingAccessOrInternalRequired.java
- src/test/java/org/candlepin/subscriptions/db/HostTallyBucketRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/resource/api/v1/InstancesResourceTest.java
- src/test/java/org/candlepin/subscriptions/security/OptInCheckerTest.java
- src/test/java/org/candlepin/subscriptions/security/WithMockAssociatePrincipal.java
- src/test/java/org/candlepin/subscriptions/security/WithMockAssociateSecurityContextFactory.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostTallyBucketRepository.java
Jira issue: SWATCH-3029
This endpoint allows for a list of billing account ids filtered by product tag and/or billing provider for a given org.
IQE Test MR: 
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1057
Additional MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/134043
1. Start local pods
`podman-compose up -d`
3. Import tally data from stage or prod for a given org
` swatch-support-scripts/import-from-gabi.py --tallies --org-id=[org_id]`
4. Start monolith
`DEV_MODE=true SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=api ./gradlew clean :bootRun`
5. opt in
`curl -X PUT 'http://localhost:8000/api/rhsm-subscriptions/v1/opt-in' -H x-rh-identity:$(echo '{"identity":{"internal":{"org_id":"[org_id]"}}}' | base64 -w0)`
Run the …
> SWATCH-3029: Create API to query billing_account_ids for instances connected to usage

- .github/workflows/pr.yaml
- deploy/dev-clowdenv.yaml
- docker-compose.yml
- swatch-common-testcontainers/src/main/java/org/candlepin/testcontainers/SwatchPostgreSQLContainer.java
Jira issue: SWATCH-3372
Since we have upgrade in production to Postgresql 13, we need to update our podman compose and test containers to match.
The test containers will be verified using the CI.
About the podman compose changes:
- start: `podman compose -f docker-compose.yml up`
- execute the migrations to verify the database is up and running: `./gradlew liquibaseUpdate`
> SWATCH-3372: Update podman compose and test containers to use Postgresql 13

- .dockerignore
By excluding some of the directories that are constantly being updated due to IDE activity or Gradle activity, we can take better advantage of layer caching in our builds.
With this change in place, the `COPY . .` command in most of our Dockerfiles no longer has to rerun almost every time.  On my system, this brings the total runtime of `bin/build-images.sh` from 9m30s down to 8m40s.  It's a modest savings, but a welcome one.
1.  Just run `bin/build-images.sh` to verify the builds occur correctly.  CI will do the same for its container build process.
> Reduce layer churn during builds

- swatch-database/deploy/clowdapp.yaml
There is a chicken and egg problem with the creation of a new ClowdApp.  CI won't pass without the app being present in the App Interface YAML files, but we can't update the YAML files until the app is present in the repo.  This is a simple placeholder so that we can then add the app to the App Interface YAML files.
> SWATCH-2820: Placeholder swatch database

- src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
Jira issue: SWATCH-3370
We were not updating the measurement type (the physical or virtual...) and because the measurement type is not part of the bucket key, this was not removed.
After adding b.setMeasurementType(bucket.getMeasurementType());  and syncing the org again, I see this host as physical as expected according to the HBI facts.
1. `podman compose -f docker-compose.yml up`
2. start tally and api: `INVENTORY_DATABASE_SCHEMA=hbi ENABLE_SYNCHRONOUS_OPERATIONS=true LOGGING_SHOW_SQL_QUERIES=true DEV_MODE=true ./gradlew :bootRun`
3. insert the following data into the swatch database:
The host which is physical:
```
insert into account_services (account_number, org_id,service_type) values ('account123', 'org123','HBI_HOST');
```
```
INSERT INTO hosts …
```
> SWATCH-3370: Host tally buckets sync is not updating the measurement type

- Jenkinsfile
Last step of the Jenkins pipeline is consistently failing because of this.
```
java.lang.OutOfMemoryError: Java heap space
at java.base/java.lang.StringUTF16.newBytesFor(Unknown Source)
at java.base/java.lang.AbstractStringBuilder.inflate(Unknown Source)
at java.base/java.lang.AbstractStringBuilder.putStringAt(Unknown Source)
at java.base/java.lang.AbstractStringBuilder.putStringAt(Unknown Source)
```
> Resolve OOM issue with archiving junit tests step in Jenkins job

- src/main/java/org/candlepin/subscriptions/tally/facts/ProductNormalizer.java
- src/main/java/org/candlepin/subscriptions/tally/facts/product/ProductRule.java
- src/main/java/org/candlepin/subscriptions/tally/facts/product/QpcProductRule.java
- src/main/java/org/candlepin/subscriptions/tally/facts/product/RhsmProductsProductRule.java
- src/main/java/org/candlepin/subscriptions/tally/facts/product/SatelliteRoleProductRule.java
- src/main/java/org/candlepin/subscriptions/tally/facts/product/SystemProfileProductIdsProductRule.java
- src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTallyTest.java
- src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
- src/test/java/org/candlepin/subscriptions/tally/facts/ProductNormalizerTest.java
- src/test/java/org/candlepin/subscriptions/tally/facts/product/QpcProductRuleTest.java
Jira issue: SWATCH-3364
In order to improve the troubleshooting and to avoid duplicating logic here and there, I had to refactor the ProductNormalizer class to split out the rules into ProductRule implementations.
This way I can loop over these rules to:
- aggregate the matching product tags as done before these changes.
- aggregate the configured product tags to detect when a product tag was a candidate for the host or not
Also, these changes improve the responsibility segregation chain of the product normalizer. Before, this normalizer contained different logic/rules to aggregate the products, and to reconcile the matching products. Now, it delegates the aggregation to the product rules as mentioned before.
IQE tests and regression
After these changes, when no products are matched for a …
> SWATCH-3364: Improve troubleshooting when hosts didn't match any products

- .tekton/rhsm-pull-request.yaml
- .tekton/run-tests-task.yaml
- .tekton/swatch-api-pull-request.yaml
- .tekton/swatch-contracts-pull-request.yaml
- .tekton/swatch-metrics-hbi-pull-request.yaml
- .tekton/swatch-metrics-pull-request.yaml
- .tekton/swatch-producer-aws-pull-request.yaml
- .tekton/swatch-producer-azure-pull-request.yaml
- .tekton/swatch-producer-red-hat-marketplace-pull-request.yaml
- .tekton/swatch-subscription-sync-pull-request.yaml
- .tekton/swatch-system-conduit-pull-request.yaml
- .tekton/swatch-tally-pull-request.yaml
JIRA Ticket: https://issues.redhat.com/browse/SWATCH-3341
Provision a EaaS name to run kubedock (https://konflux.pages.redhat.com/docs/users/testing/namespace-provisioning.html)
Create a `run-tests` custom Task to run after the eaas space is provisioned.  Use a kubedock sidecar that uses the kubeconfig that was generated from the eaas space.  The `run-tests` task will run the gradlew test task via CLI script.
Depends on https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/5167
https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/5183
> SWATCH-3341: Update konflux pipelines to run junit tests

- swatch-api/deploy/clowdapp.yaml
Jira issue: SWATCH-2844
Endpoints to route:
- /api/rhsm-subscriptions/v1/subscriptions/billing_account_ids            ->  /api/swatch-contracts/v1/subscriptions/billing_account_ids
- /api/rhsm-subscriptions/v1/subscriptions/products/{product_id}          ->  /api/rhsm-subscriptions/v1/subscriptions/products/{product_id}
- /api/rhsm-subscriptions/v1/capacity/products/{product_id}/{metric_id}   ->  /api/rhsm-subscriptions/v1/capacity/products/{product_id}/{metric_id}
- /api/rhsm-subscriptions/v2/subscriptions/products/{product_id}          ->  /api/rhsm-subscriptions/v2/subscriptions/products/{product_id}
Regression testing.
1. Deploy EE project using these changes
2. Run the iqe test "test_subscription_table_api_subscription_type"
> SWATCH-2844: Update nginx routing send capacity queries directly to swatch-contracts

- swatch-api/deploy/clowdapp.yaml
This reverts commit 2859248a9c7478d307f3922530af7818c26e1f3c.
Jira issue: SWATCH-3419
We're reverting the changes in https://github.com/RedHatInsights/rhsm-subscriptions/pull/4292 because Quarkus does not distinguish between empty and null. This issue was introduced in Quarkus 3.18 and reported by https://github.com/quarkusio/quarkus/issues/44885.
Note that before reverting the changes, I tried to make this query param optional, but the openapi does not generate it as optional. 
Other solutions imply to use the raw request param to check what was the original query value (either unset or empty), but I see this solution as flaky/workaround (since there are many query types affected). Let's wait for what is the reply from Quarkus about this issue, since they seem to be keen to not revert …
> Revert "SWATCH-2844: Update nginx routing send capacity queries directly to swatch-contracts"

- .github/workflows/ci.yml
Jira issue: SWATCH-3418
Before these changes, when a step failed, another later step was marked as failure, having to navigate and inspect all the previous steps to check what was the cause.
After these changes, a step is properly marked as failure and following steps continue if it makes sense (for ex: the upload of the tests report continues even when the previous step fails because we want to see this report).
Regression testing.
> SWATCH-3418: Ensure a step is marked as failure when it fails

- swatch-contracts/src/main/java/com/redhat/swatch/contract/config/Channels.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/product/umb/ProductStatusUMBMessageConsumer.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/OfferingSyncService.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/OfferingSyncTaskConsumer.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/OfferingSyncServiceTest.java
- swatch-contracts/src/test/resources/mocked-product-event.json
The offering topic owned by ESB (i.e. "Canonical") is being retired (the goal-date being within a month or so) and consumers need to use the topic owned by the product service. However, the topic owned by the product service does not publish any attributes or hierarchy information, just the sku/product code.
So in addition to the topic change, there is a behavioral change as well because SWatch will no longer to able to compare the message contents to the copy in the DB and will now have to call product service for every single message that is consumed.
This is an MR intended to help kickstart the investigation process, since the request for the topic switch is coming in last-minute.
IQE Test MR: 
1.
1.
1.
1.
1.
1.
> WIP: Add new consumer for the product service-owned offering topic

- renovate.json
By default, the Konflux task images are bumped once a week, however the verify build fails when it detects that there are newer version.
To prevent the verify build to fail, we need to update the Konflux task images as soon as there is a new image (not wait for the weekly pull request).
> Configure renovate to update the Konflux tasks at any time when there are new versions

- swatch-producer-azure/deploy/clowdapp.yaml
The service swatch-producer-azure was failing to be deployed with the following error `Error: couldn't find key credentials in Secret ephemeral-tkc06t/azure-marketplace-credentials`.
The problem is that indentation was wrong. Note sure how this was not spotted earlier, maybe clowder was fixing it automagically.
CI is green. Regression testing.
> Fix secret azure-marketplace-credentials indent that makes swatch-producer-azure to fail

- swatch-billable-usage/deploy/clowdapp.yaml
Jira issue: SWATCH-3461
In the ephemeral environments, the pod kept crash looping.  After
bumping up the memory request, I see that the total memory used is about
583 MiB so this patch should give us a little breathing room.
1. Do an ephemeral deployment from this branch
1. Do an `oc edit` on the swatch-billable-usage-service pod and set the memory
request and limit back to 512.  The billable-usage pod will start
crash-looping.
1. Set the memory limit back to 750 and the billable usage pod will stop
crash-looping.
> SWATCH-3461: Increase Billable Usage Memory Limit

- api/rhsm-subscriptions-api-v1-spec.yaml
- src/main/java/org/candlepin/subscriptions/resource/api/v1/CapacityResource.java
- src/main/java/org/candlepin/subscriptions/resource/api/v1/TallyResource.java
- src/test/java/org/candlepin/subscriptions/resource/api/v1/CapacityResourceTest.java
- src/test/java/org/candlepin/subscriptions/resource/api/v1/TallyResourceTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/CapacityResourceV1.java
- swatch-contracts/src/main/resources/META-INF/openapi.yaml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/CapacityResourceV1Test.java
Jira issue: SWATCH-3405
We want to filter the results in the capacity report, optionally by billing_account_id.
This change is in both the monolith version and the swatch-contracts version.
IQE Test MR: 
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1115
1. Start the core services in rhsm-subscriptions with podman
```podman-compose up -d```
2. oc login to the prod environment and use the project rhsm-prod
```oc login --token=[token] --server=https://api.crcp01ue1.o9m8.p1.openshiftapps.com:6443```
3. Make sure you have the latest version of swatch-support-scripts
4. Import data from org 18284865 to the local db:
```
../swatch-support-scripts/import-from-gabi.py --offerings --org-id='18284865'
../swatch-support-scripts/import-from-gabi.py …
```
> SWATCH-3405: Add billing_account_id as param for Capacity

- .rhcicd/grafana/grafana-dashboard-subscription-watch-payg-metrics.configmap.yaml
Failure deploying to prod because there's already another template with the same ConfigMap name.
```
17:27:58 [2025-04-16 17:27:58] [ERROR] [DRY-RUN] [saasherder.py:populate_desired_state_saas_file:1376] - [appsrep09ue1/****-observability-production] Duplicate resources in your deployment template detected. The following is defined multiple times in your deployment template: ConfigMap/grafana-dashboard-subscription-watch. saas file name: rhsm, resource template name: insights-subscription-watch.
```
> Update ConfigMap name because of naming conflict

- swatch-database/deploy/clowdapp.yaml
If a ClowdJobInvocation with the same name is applied again, the job doesn't trigger.  This patch adds a unique suffix so the job will run each time.
None
> SWATCH-2820: Add IMAGE_TAG to swatch-database job to ensure unique name

- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/dtos/hbi/HbiHostCreateUpdateEvent.java
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/dtos/hbi/HbiHostDeleteEvent.java
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/normalization/MeasurementNormalizer.java
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/services/HbiEventConsumer.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/normalization/MeasurementNormalizerTest.java
Fix an NPE that was occurring when processing incoming HBI messages and calculating measurements. Also log the incoming HBI events in JSON format.
> Fix NPE in swatch-metrics-hbi when normalizing measurements for incoming events

- pr_check.sh
Jira issue: SWATCH-3530
Jenkins PR provides the following "GIT_COMMIT" property to get the full sha commit, however it does not work when using it with the GitHub API because this commit sha belongs to a local cloned repository.
Moreover, we can't use the git log or any other git command utility for the same reason than above.
Therefore, the only option is to use the branch name which is provided by Jenkins by GIT_BRANCH.
Depends on https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1150.
In the "ci.ext.devshift.net PR build" job , check that contains this trace:
```
INFO:root:Fetching swatch-product-configuration from jcarvaja/SWATCH-3530 ...
```
> SWATCH-3530: Use branch to resolve product configuration

- .github/workflows/ci.yml
Jira issue: SWATCH-3453
We need to add pull-request write permissions to the Job Summary task.  See the documentation [here](https://github.com/marketplace/actions/sticky-pull-request-comment#error-resource-not-accessible-by-integration)
None really.  We just need to make sure the workflow passes on this PR and then we'll have to see if it passes when Dependabot opens a pull request since that is where it was failing.
> SWATCH-3453: Add write permissions for GitHub Actions summary task

- swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
Jira issue: SWATCH-3391
swatch-metrics logic is written with the assumption that a product label was always going to match the role of a product.  We now have products that don't have roles.
Improves handling of mismatched product tags in metering events. Instead of simply logging a warning and clearing the productTag when the starting tag doesn't match the derived tags, the logic now differentiates between no matching tags and some matching tags. If no tags match, the role is also cleared to trigger fallback logic. If some tags match, only the productTag is cleared to allow the ingestion process to rederive the correct context. This prevents incorrect tag assignments and ensures accurate metering data.
create Offering
```sql
INSERT INTO public.offering (sku, product_name, product_family, …
```
> SWATCH-3391: Fix logic to not assume `role` is always the same as the `product` label

- dependencies.gradle
This reverts commit 7fbeb1f8cd159c163a484d8aa2c2b165d0a2dd58, reversing changes made to a050daa6b47c72e9fe1390d544557d104a9cfc53.
The quarkus version is causing the swatch-common-panache build to fail much more often than before.
Reported by https://issues.redhat.com/browse/SWATCH-3541
> Revert "chore(deps): Bump quarkusVersion from 3.21.3 to 3.22.1 (#4446)"

- swatch-contracts/src/main/java/com/redhat/swatch/contract/model/SubscriptionCapacityViewMetricConverter.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/service/export/SubscriptionCsvDataMapperService.java
- swatch-contracts/src/main/resources/db/202504301500-update-subscription-capacity-view_h2_only-to-set-defaults.xml
- swatch-contracts/src/main/resources/db/changeLog.xml
- swatch-contracts/src/test/java/com/redhat/swatch/contract/service/export/SubscriptionDataExporterServiceTest.java
Jira issue: SWATCH-3507
Before these changes, we only exported subscriptions with metrics in CSV. Now, we'll export all the subscriptions regardless whether it has metrics or not.
1.- Deploy the changes from the branch into an EE environment
2.- Port forward the database and the export-service services:
```
oc port-forward $(oc get pods | grep tally-db | cut -d' ' -f1) 5432:5432
oc port-forward $(oc get pods | grep export-service-service | cut -d' ' -f1) 8002:8000
```
3.- Get the credentials from the tally-db and connect to the database from localhost
4.- Create an export request:
```
curl -sS -X POST http://localhost:8002/api/export/v1/exports -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6IjEwMDAxIiwib3JnX2lkIjoiMTIzIiwiaW50ZXJuYWwiOnsib3JnX2lkIjoiMTMyNTk3NzUifSwidHlwZSI6IlVz …
```
> SWATCH-3507: Export subscriptions without metrics in CSV

- .tekton/swatch-database-pull-request.yaml
- .tekton/swatch-database-push.yaml
Disable swatch-database konflux pipelines for now which will be merged next week (after prod release) by https://github.com/RedHatInsights/rhsm-subscriptions/pull/4409
CI is green.
> Disable swatch-database konflux pipelines for now

- src/test/java/org/candlepin/subscriptions/db/AccountServiceInventoryRepositoryTest.java
- src/test/java/org/candlepin/subscriptions/resource/api/v1/InstancesResourceTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostTallyBucketRepository.java
Jira issue: SWATCH-3542
For example, having the following data in the tally_buckets:
```
"billing_provider":"_ANY","billing_account_id":"746157280291"
"billing_provider":"_ANY","billing_account_id":"_ANY"
"billing_provider":"aws","billing_account_id":"746157280291"
"billing_provider":"aws","billing_account_id":"_ANY"
"billing_provider":"_ANY","billing_account_id":"746157280292"
"billing_provider":"_ANY","billing_account_id":"_ANY"
"billing_provider":"azure","billing_account_id":"746157280292"
"billing_provider":"azure","billing_account_id":"_ANY"
```
For the same product and account, it should return only two records:
```
"billing_provider":"aws","billing_account_id":"746157280291"
"billing_provider":"azure","billing_account_id":"746157280292"
```
Refactored the test to run real queries …
> SWATCH-3542: Filter out billing_provider and billing_account_id with values _ANY from the instances/billing_account_ids API

- swatch-contracts/src/main/resources/application.properties
This PR updates the `application.properties` for the `swatch-contracts` service to reduce log clutter and splunk storage impact.  The logger currently emits thousands of large entries daily, some over a megabyte each, consuming excessive log volume.  
Slack thread for context: https://redhat-internal.slack.com/archives/C01F7QFNATC/p1745590531531909
Changes:
* Removed verbose HTTP client debug logging from the `%stage` profile:
* Specifically, `DebugClientLogger` log level has been removed.
* This was initially added under SWATCH-2206 to help troubleshoot an issue with `redhat-subscription-created` messages from the Partner Gateway failing due to a missing `orgId`.
* Since the issue has not reoccurred and hasn't required troubleshooting support for quite some time, the debug logs are no …
> Remove DebugClientLogger from %stage to Reduce Log Noise

- swatch-contracts/src/main/resources/application.properties
Jira issue: SWATCH-3456
Allow to mock product API using wiremock + removing unnecesary extra configuration to set the AMQP topic names. 
Related to https://github.com/RedHatInsights/wiremock-consoledot/pull/19
> SWATCH-3456: Allow to mock product api responses for offering sync

- .tekton/swatch-api-push.yaml
- .tekton/swatch-billable-usage-push.yaml
- .tekton/swatch-contracts-push.yaml
- .tekton/swatch-database-push.yaml
- .tekton/swatch-metrics-hbi-push.yaml
- .tekton/swatch-metrics-push.yaml
- .tekton/swatch-producer-aws-push.yaml
- .tekton/swatch-producer-azure-push.yaml
- .tekton/swatch-producer-red-hat-marketplace-push.yaml
- .tekton/swatch-subscription-sync-push.yaml
- .tekton/swatch-system-conduit-push.yaml
- .tekton/swatch-tally-push.yaml
Updated multiple Tekton pipeline configuration files to enable automatic cancellation of in-progress runs when a new push event is triggered.
> Enable in-progress pipeline cancellation for push triggers

- .tekton/swatch-api-pull-request.yaml
- .tekton/swatch-billable-usage-pull-request.yaml
- .tekton/swatch-contracts-pull-request.yaml
- .tekton/swatch-database-pull-request.yaml
- .tekton/swatch-metrics-hbi-pull-request.yaml
- .tekton/swatch-metrics-pull-request.yaml
- .tekton/swatch-producer-aws-pull-request.yaml
- .tekton/swatch-producer-azure-pull-request.yaml
- .tekton/swatch-producer-red-hat-marketplace-pull-request.yaml
- .tekton/swatch-subscription-sync-pull-request.yaml
- .tekton/swatch-system-conduit-pull-request.yaml
- .tekton/swatch-tally-pull-request.yaml
Temporarily disable all the "on pull request" pipelines because of the resource/quota impact of having them run.
> Disable all konflux on-pull-request pipelines

- src/main/resources/liquibase/202505131100-update-subscription-capacity-view-to-filter-start-date.xml
- src/main/resources/liquibase/changelog.xml
- src/test/java/org/candlepin/subscriptions/db/SubscriptionMeasurementRepositoryTest.java
- swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/SubscriptionEntity.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/repository/SubscriptionRepositoryTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
Jira issue: SWATCH-2579
These changes affect to the following endpoints:
- /api/rhsm-subscriptions/v1/subscriptions/products/{product}
- /api/rhsm-subscriptions/v2/subscriptions/products/{product}
- /api/rhsm-subscriptions/v1/capacity/products/{product}/{metric}
in swatch-api and swatch-contracts.
The root cause of the problem is that we might have multiple active subscriptions, and we're double counting them even when the subscription number (subscription ID) is the same.
The general fix is to always select the most recent active subscription (the one with earliest start_date).
Note that to get the actual subscriptions values (API: /api/rhsm-subscriptions/v2/subscriptions/products/), this was already working fine, but I found that we were not filtering by start_date when getting the …
> SWATCH-2579: Filter Capacity API by the most recent active subscription

- swatch-contracts/src/main/java/com/redhat/swatch/contract/config/DebugClientLogger.java
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/config/DebugClientLoggerTest.java
Jira issue: SWATCH-3527
Replaced Quarkus-based ClientLogger API with standard JAX-RS API: ClientRequestFilter, ClientResponseFilter, which works when using the resteasy rest-client framework.
Note that I added a new property "rest-client-debug-logging.log-responses" to log also the responses, since this is a very dangerous operation (we now need to copy the response in a temporal stream, log it, and copy it back to the original stream, so it's consumed by the following handlers).
Added JUnit tests. Only regression testing.
> SWATCH-3527: Convert DebugClientLogger to use standard the JAX-RS API

- buildSrc/src/main/groovy/swatch.quarkus-rest-client-conventions.gradle
- clients/quarkus/product-client/src/main/java/com/redhat/swatch/clients/product/ProductService.java
- clients/quarkus/product-client/src/test/java/com/redhat/swatch/clients/product/ProductServiceTest.java
- swatch-contracts/src/main/resources/application.properties
Jira issue: SWATCH-3586
When consuming OfferingSync tasks, because the consumer is annotated with `@Blocking`  Quarkus manages the ack() automatically only after the method completes successfully (i.e., no exception is thrown).
The problem could be caused when the Product API call takes more than 60 seconds (which is the current timeout setting). When this happens, since 60 seconds exceeds the allowed unacknowledged time, the kafka record is unack and throws the TooManyMessagesWithoutAckException causing the service to be restarted. 
After the service is restarted, the OfferingSync tasks are reprocessed causing the topic lag to increase even more. 
Changes:
- Increase the kafka allowed unacknowledged time to 90 seconds.
- Explicitly set the commit strategy to throttled (which was already …
> SWATCH-3586: when sync offering, increase timeout to handle messages plus metrics in the Product API rest client

- swatch-database/src/main/docker/Dockerfile.jvm
In an earlier incarnation, swatch-database used a script to monitor the
progress of a Job.  The script called kubectl, so the container included
the Kubernetes RPM repository.  When I removed the job-polling
functionality, I neglected to remove the inclusion of the third-party
repository.  Including this repository causes failures in our build
system since the repo is not approved.
This patch removes the traces of the job-polling functionality that
manifested in the Dockerfile.
> SWATCH-2820: Remove k8s repo from database migrations

- swatch-database/src/main/docker/Dockerfile.jvm
This is consistent with all our other Dockerfiles
IQE Test MR: 
1.
1.
1.
1.
1.
1.
> SWATCH-2820: swatch-database image should install tar & rsync from ubi-9-baseos-rpms

- swatch-database/deploy/clowdapp.yaml
Clowder allows a fallback name for the database.  With the deployment of
swatch-database we want to fall back to our old database name initially
and then change the name in RDS in the future.  This process will allow
us to avoid any outage.  I was not sure if the fallback name would be
"swatch-tally-db" or "swatch-tally".  The former did not work, so this
commit tries the latter.
> SWATCH-2820: Update database fallback name

- docker-compose.yml
- nginx.conf
- swatch-billable-usage/src/main/resources/application.properties
Jira issue: SWATCH-3532
Run it with internet if you want to call stage apis with dev mode and run with/without internet for wiremock profile that does local testing.
IQE MRs to enable local testing: 
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1180
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1177
Github supporting PRs:
https://github.com/RedHatInsights/rhsm-subscriptions/commit/467cb0d83c4e7826bd619ed4bb1c49e7a897e230
1. `podman-compose down`
2. `podman-compose up -d`
3. `./gradlew liquibaseUpdate`
4. Pycharm add env file that is located at iqe-rhsm-subscriptions-plugin/iqe_rhsm_subscriptions/conf/iqe_env
5. Run applications on different ports like 
swatch-billable-usage: `QUARKUS_HTTP_HOST=0.0.0.0 …
> WIP SWATCH-3532 Enable local testing for wiremock profile

- .github/workflows/ci.yml
- deploy/dev-clowdenv.yaml
- docker-compose.yml
- swatch-common-testcontainers/src/main/java/org/candlepin/testcontainers/SwatchPostgreSQLContainer.java
Jira issue: SWATCH-3619
Our podman compose and test containers use unsupported Postgress 13 image based on CentOS7. We should use supported image from https://github.com/sclorg/postgresql-container?tab=readme-ov-file#versions:
- CentOS Stream 9 - quay.io/sclorg/postgresql-13-c9s
Additionally, most of these images (except CentOS 8) are multiarch, which would make it easier for running on MacOS.
> SWATCH-3619: Update postgresql image to quay.io/sclorg/postgresql-13-c9s

- swatch-common-resteasy-client/src/main/java/com/redhat/swatch/resteasy/client/DebugClientLogger.java
- swatch-contracts/src/main/resources/application.properties
- swatch-contracts/src/test/java/com/redhat/swatch/contract/config/DebugClientLoggerTest.java
- swatch-metrics/src/main/resources/application.properties
The DebugClientLogger is incredibly helpful to troubleshoot rest-client errors, but at the moment, it's only defined in swatch-contracts.
Let's move it to swatch-common-resteasy-client to be used by all our swatch services.
> Move DebugClientLogger into swatch-common-resteasy-client

- .github/workflows/ci.yml
Removing the step "Publish Test Results" which is consistently failing and it does not add much value. 
CI is green.
> CI: Remove Publish Test Results because it's consistently failing

- config/checkstyle/checkstyle.xml
- pom.xml
Correct the path reference to the Checkstyle XPath suppressions file.  This
patch defines a property with the location and then sets that property to the
proper location within the pom.xml.
```
cd clients-core
../mvnw install
```
Build runs
> Correct reference to Checkstyle XPath suppressions

- .tekton/swatch-api-pull-request.yaml
- .tekton/swatch-billable-usage-pull-request.yaml
- .tekton/swatch-billable-usage-push.yaml
- .tekton/swatch-contracts-pull-request.yaml
- .tekton/swatch-contracts-push.yaml
- .tekton/swatch-database-pull-request.yaml
- .tekton/swatch-database-push.yaml
- .tekton/swatch-metrics-hbi-pull-request.yaml
- .tekton/swatch-metrics-hbi-push.yaml
- .tekton/swatch-metrics-pull-request.yaml
- .tekton/swatch-metrics-push.yaml
- .tekton/swatch-producer-aws-pull-request.yaml
- .tekton/swatch-producer-aws-push.yaml
- .tekton/swatch-producer-azure-pull-request.yaml
- .tekton/swatch-producer-azure-push.yaml
- .tekton/swatch-producer-red-hat-marketplace-pull-request.yaml
- .tekton/swatch-producer-red-hat-marketplace-push.yaml
- .tekton/swatch-subscription-sync-pull-request.yaml
- .tekton/swatch-subscription-sync-push.yaml
- .tekton/swatch-system-conduit-pull-request.yaml
- .tekton/swatch-system-conduit-push.yaml
- .tekton/swatch-tally-pull-request.yaml
- .tekton/swatch-tally-push.yaml
After accepting konflux bot updates, started to get errors with builds 
```
[User error] Validation failed for pipelinerun swatch-api-on-push-tpf49 with error invalid input params for task apply-tags: missing values for these params which have no default values: [IMAGE_URL IMAGE_DIGEST]
```
https://issues.redhat.com/browse/KFLUXSPRT-3675
> KFLUXSPRT-3675: Add IMAGE_URL and IMAGE_DIGEST to all apply-tags tasks

- swatch-billable-usage/src/main/resources/application.properties
- swatch-contracts/src/main/resources/application.properties
- swatch-metrics-hbi/src/main/resources/application.properties
- swatch-metrics/src/main/resources/application.properties
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
Jira issue: SWATCH-3663
Since we don't need splunk when running the service in DEV mode, we can disable it and at the same time, we avoid the linked issue reported by SWATCH-3663.
1.- podman compose -f docker-compose.yml up -d
2.- run migrations: `mvn -f swatch-database/pom.xml exec:java`
3.- run swatch contracts: `SERVER_PORT=8001 ./mvnw -pl swatch-contracts quarkus:dev`
It should now work consistently.
> SWATCH-3663: Disable splunk DEV services to avoid random failures at start up

- clients/pom.xml
- swatch-billable-usage/pom.xml
- swatch-contracts/pom.xml
- swatch-metrics/pom.xml
- swatch-model-billable-usage/pom.xml
- swatch-producer-aws/pom.xml
- swatch-producer-azure/pom.xml
Before these changes we used `<output>${project.build.directory}/generated</output>` plus the `build-helper-maven-plugin` plugin to "register" this path, so Maven can use the generated sources.
However, IntelliJ does not take into account this generated path if the plugin `build-helper-maven-plugin` is not properly configured (this is what was happening in the swatch-contracts module).
To avoid missing to configure the `build-helper-maven-plugin` plugin, let's replace `<output>${project.build.directory}/generated</output>` by using the standard generated sources folder `<output>${project.build.directory}/generated-sources</output>`, so it works fine from command line and intellij without needing to use the `build-helper-maven-plugin`.
> Change generated folder for the openapi plugins

- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/dtos/hbi/HbiEvent.java
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/dtos/hbi/HbiHostUnknownEvent.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/HbiEventDeserializationTest.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/services/HbiEventConsumerTest.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/test/helpers/HbiEventTestData.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/test/helpers/HbiEventTestHelper.java
- swatch-metrics-hbi/src/test/resources/data/hbi_physical_rhel_host_updated_event.json
- swatch-metrics-hbi/src/test/resources/data/hbi_unknown_event.json
I found an issue that when the event is not supported, we were still serializing to a create/update event which is wrong.
The logic should be based on the event type, not by deduction. 
1.- podman compose up -d
2.- mvn install -Prun-migrations
3.- mvn clean install -DskipTests
4.- SERVER_PORT=8005 QUARKUS_MANAGEMENT_PORT=9005 mvn -pl swatch-metrics-hbi quarkus:dev
- Unsupported event
```
curl -X POST \
http://localhost:9080/topics/platform.inventory.events \
-H "Content-Type: application/vnd.kafka.json.v2+json" \
-H "Accept: application/vnd.kafka.v2+json" \
-d '{
"records": [
{
"key": "12345678",
"value": {
"type": "unknown"
}
}
]
}'
```
Then, you should see that the event is discarded because unknown is unsupported.
- Supported event by type
```
cat > rhel_guest.json <<EOF
$(jq -n --arg …
```
> SWATCH Metrics HBI: change the json deserialization strategy to not fail on unknown types

- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/TestingApplicationConfiguration.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/processing/handlers/CreateUpdateHostHandlerTest.java
The problem is that the clock used by the service was the fixed one, instead of the default one, what was causing the host not being considered stale.
> fix: CreateUpdateHostHandlerTest test

- src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
- src/main/java/org/candlepin/subscriptions/tally/admin/MergeHostsMigration.java
- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerIT.java
- src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java
- swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
- swatch-database-migrations/src/main/resources/liquibase/202506191100-add-host-service-type-table.xml
- swatch-database-migrations/src/main/resources/liquibase/changelog.xml
Jira issue: SWATCH-3664
Before these changes, when we ingested events into the tally buckets table for different products like rosa and rhacs, we were only processing the events for one product.
After these changes, we need to refactor the solution, so one instance can be mapped to different products.
For doing this:
- Create new table "host_tally_service_type" to store the service_type and the last_applied_event_record_date (in the future, we could drop the instance_type from the hosts table which is replaced by this mapping now).
- Only delete buckets when the buckets belong to the same event service type.
- Check whether the last_applied_event_record_date from the new table host_tally_service_type.
Added an integration test that reproduces the issue and confirmed the fix.
MR: …
> SWATCH-3664: Support instances to be mapped to different products/servide types

- swatch-contracts/src/main/java/com/redhat/swatch/contract/security/RolesAugmentor.java
- swatch-contracts/src/test/java/com/redhat/swatch/contract/security/RolesAugmentorTest.java
Jira issue: SWATCH-3345
We want to move our tests to use X509 based authentication rather than a PSK.
However, the swatch-contracts code doesn't give an X509 authed user the
"service" role like PSK auth does.
Unit test
> SWATCH-3345: Mark X509 authed users with service role

- docker-compose.yml
With this change we propose to pin Kafka bridge  version in docker compose file.
This fixes a compatibility issue running local component test.
Also using latest is considered a bad practice.
[Testing local deployment of billable usage service](https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/blob/master/iqe_rhsm_subscriptions/tests/component/swatch_billable_usage/test_verify_ansible_usage.py#L19) resulted in an error during [consumer group creation](https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/blob/master/iqe_rhsm_subscriptions/internal_apis/kafka_bridge.py#L21).
The error we got was `400 Validation error on: The format of the request body is not supported`.
After this change, redeploying locally Kafka bridge and the service, the test …
> chore: Update and pin Kafka bridge version

- config/wiremock/__files/contract_service_response.json
- nginx.conf
- swatch-producer-azure/src/main/resources/application.properties
Jira issue: SWATCH-3623
These changes focus on enabling local testing for the Azure Producer using the Wiremock profile.
1.- podman compose -f docker-compose.yml up -d
2.- mvn clean install -Prun-migrations
3.- Pycharm add env file that is located at iqe-rhsm-subscriptions-plugin/iqe_rhsm_subscriptions/conf/iqe_env
4.- QUARKUS_PROFILE=wiremock ./mvnw -pl swatch-producer-azure quarkus:dev
5.- And run all the tests from test_swatch_azure_producer.py
The tests should work as it is.
> SWATCH-3623: Enable wiremock profile for azure producer for local component testing

- swatch-billable-usage/src/main/resources/application.properties
- swatch-contracts/src/main/resources/application.properties
- swatch-metrics-hbi/src/main/resources/application.properties
- swatch-metrics/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
Jira issue: SWATCH-3663
The Quarkus services are randomly failing when starting the Splunk dev service which we have it disabled using the following property:
```
quarkus.log.handler.splunk.devservices.enabled=false
```
Yet, sometimes the splunk container was trying to start.
Checking the source code of the splunk Quarkus extension, this property is checked when the dev service is executed which might cause inconsistencies.
On the other hand, if we disable all the DEV services using `quarkus.devservices.enabled`, the Splunk Dev Service should not be executed at all.
Note that I've verified that all the Quarkus services worked fine in DEV mode with these changes.
Regression testing.
> SWATCH-3663: Disable all DEV services

- Dockerfile
- pom.xml
- swatch-billable-usage/src/main/docker/Dockerfile.jvm
- swatch-contracts/src/main/docker/Dockerfile.jvm
- swatch-database/src/main/docker/Dockerfile.jvm
- swatch-metrics-hbi/src/main/docker/Dockerfile.jvm
- swatch-metrics/src/main/docker/Dockerfile.jvm
- swatch-producer-aws/src/main/docker/Dockerfile.jvm
- swatch-producer-azure/src/main/docker/Dockerfile.jvm
- swatch-system-conduit/Dockerfile
The RUN command has an option to cache directories.  The directories persist between builder invocations without invalidating the instruction cache.  Additionally, we can improve build performance by downloading as many dependencies as possible into a layer prior to copying over the project source.
On my machine, these improvements result in about 80s savings to rebuild (i.e. the cache is getting used) an image for swatch-contracts.  Building all the images with the `bin/build-images.sh` script results in about a 40s savings.
1. Install the `perf` package.
1. In the `bin/build-images.sh` script, add `--no-cache` to the `podman build` line.
1. Run `perf stat -B ./bin/build-images.sh` on `main`
1. Remove the `--no-cache` and rerun the command from step 1.
1. Repeat for …
> Improve caching during container builds

- swatch-metrics-hbi/src/main/resources/application.properties
Relates to Jira issue: SWATCH-3630
In order to avoid flaky IQE tests when testing against the local environment, the quarkus.unleash.fetch-toggles-interval configuration variable was updated to be 1 second for the dev environment. This is similar to what was done for the EE.
> Update the unleash fetch-toggles-interval in swatch-metrics-hbi

- .gitignore
- config/prometheus/docker-compose.yml
- docker-compose.yml
- swatch-metrics/src/main/resources/application.properties
Jira issue: SWATCH-3628
This card focuses on enabling local testing for the swatch metrics using the Wiremock profile.
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1259
1. podman compose up -d
2. make run-migrations
3. make build swatch-metrics
Run all the tests within the file test_mock_event_via_prometheus.py
> SWATCH-3628: Enable wiremock profile for swatch-metrics for local component testing

- config/prometheus/docker-compose.yml
Jira issue: SWATCH-3774
Created new API to import prometheus files in https://github.com/RedHatInsights/prometheus-consoledot/pull/12
These changes use this API to connect with Prometheus. So, now, local and ephemeral environments will use the same logic.
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1260
1. podman compose up -d
2. make run-migrations
3. make build swatch-metrics
Run all the tests within the file test_mock_event_via_prometheus.py
> SWATCH-3774: Bump prometheus image to use internal /import API

- src/main/resources/application-wiremock.yaml
- swatch-billable-usage/src/main/resources/application.properties
- swatch-contracts/src/main/resources/application.properties
- swatch-metrics-hbi/src/main/resources/application.properties
- swatch-metrics/src/main/resources/application.properties
- swatch-producer-aws/src/main/resources/application.properties
- swatch-producer-azure/src/main/resources/application.properties
Jira issue: SWATCH-3754
By default, the Quarks services use 8000 on a local instance. The Nginx service uses that port when the Podman containers are started, which leads to a conflict. This would start the services on unique ports by default.
1. Start the containers
```podman -compose up -d```
2. Run the liqubase update
```./mvnw -f swatch-database/pom.xml exec:java```
1. Start any of the Quarkus services, e.g.
``` ./mvnw -pl swatch-contracts quarkus:dev```
4. Run against the URL with the expected port
```http GET :8011/api/swatch-contracts/internal/offerings/MCT2342/product_tags```
1. You will get the correct response on the port
```
HTTP/1.1 404 Not Found
Content-Type: application/json
content-length: 83
traceresponse: 00-00000000000000000000000000000000-0000000000000000-00
{
"code": …
```
> SWATCH-3754: Update default ports on Quarkus and Spring services

- nginx.conf
Jira issue: SWATCH-3691
The new nginx configuration replicates what the SWATCH API (nginx service) does in production.
1.- podman compose up -d
2.- make run-migrations
3.- make swatch-contracts
Then, run the tests:
- test_subscription_table_api_subscription_type_contracts
- test_subscription_table_api_subscription_type_contracts_v2
Both should work fine using the changes from this branch. In main, both failed.
> SWATCH-3691: Fix mapping rules in nginx for local testing

- .pre-commit-config.yaml
- CONTRIBUTING.md
Adds pre-commit hooks that automatically run spotless formatting and checkstyle validation before each commit. This should help catch formatting and style issues early, reducing CI failures.
- **`.pre-commit-config.yaml`**: Added three hooks:
- `spotless-apply` - formats Java code automatically
- `spotless-check` - verifies formatting is correct  
- `checkstyle` - validates Google Java Style compliance
- **`CONTRIBUTING.md`**: Added setup instructions and usage guide for the pre-commit hooks
The hooks run automatically before each commit and only process Java files. If any validation fails, the commit is blocked until the issues are fixed.
```bash
pip install pre-commit
pre-commit install
```
That's it - the hooks will now run automatically on every commit.
- Catches formatting/style …
> Add pre-commit hooks for automated code formatting and style validation

- src/main/java/org/candlepin/subscriptions/resteasy/ResteasyConfiguration.java
- src/main/resources/static/api-docs/index.html
- Add ResourceHandlerRegistry import
- Add addResourceHandlers method to serve webjars from classpath
- This enables Swagger UI to load CSS and JS files properly
- Fixes 404 errors when accessing `/api/swatch-tally/internal/swagger-ui/`
- Update `/api-docs/index.html` to show all SWATCH service APIs in one interface
- Add service selection dropdown to switch between different APIs
- Include direct links to all OpenAPI specs for easy access
- Use environment-agnostic relative URLs that work across all environments
- No manual OpenAPI spec maintenance required - uses existing endpoints dynamically
- Quarkus services use the `quarkus-smallrye-openapi` extension which automatically provides Swagger UI endpoints and handles webjars serving with zero configuration
- Spring Boot services (like …
> Fix Swagger UI for swatch-tally service in stage/prod environments

- src/main/java/org/candlepin/subscriptions/event/EventConflictResolver.java
- src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
- src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
Jira issue: SWATCH-3545
While investigating bug SWATCH-3545, I noticed that we are not setting the org_id as the message key when creating events via the internal tally API. This is critical in ensuring that all events are processed in order for a given org_id.
**NOTE:** This was discovered while investigating this issue. The patch should not be considered as a 'fix' for the bug as we are still unable to reliably reproduce this issue.
1. After deploying the main branch, create an event using the admin API.
```bash
$ ./mvnw -f swatch-database/pom.xml exec:java
$ MANAGEMENT_SERVER_PORT=9002 SERVER_PORT=8002 DEV_MODE=true ./mvnw -pl swatch-tally spring-boot:run
```
```
$ curl -s "http://localhost:8002/api/rhsm-subscriptions/v1/internal/rpc/tally/events"  -H "Content-Type: application/json" …
```
> SWATCH-3545: Use org_id as message key when creating events via tally API

- .tekton/swatch-api-pull-request.yaml
- .tekton/swatch-api-push.yaml
- .tekton/swatch-billable-usage-pull-request.yaml
- .tekton/swatch-billable-usage-push.yaml
- .tekton/swatch-contracts-pull-request.yaml
- .tekton/swatch-contracts-push.yaml
- .tekton/swatch-database-pull-request.yaml
- .tekton/swatch-database-push.yaml
- .tekton/swatch-metrics-hbi-pull-request.yaml
- .tekton/swatch-metrics-hbi-push.yaml
- .tekton/swatch-metrics-pull-request.yaml
- .tekton/swatch-metrics-push.yaml
- .tekton/swatch-producer-aws-pull-request.yaml
- .tekton/swatch-producer-aws-push.yaml
- .tekton/swatch-producer-azure-pull-request.yaml
- .tekton/swatch-producer-azure-push.yaml
- .tekton/swatch-system-conduit-pull-request.yaml
- .tekton/swatch-system-conduit-push.yaml
- .tekton/swatch-tally-pull-request.yaml
- .tekton/swatch-tally-push.yaml
- kafka-bridge/deploy/template.yaml
Update buildah-oci-ta task to trusted version 6971ff364b06fc3fb30c04951bf956be03b8178ae842a21b355cc9c632264a4d
This fixes Enterprise Contract violations:
- slsa_build_scripted_build.image_built_by_trusted_task
- tasks.required_untrusted_task_found
- trusted_task.trusted
> Update buildah-oci-ta task to trusted version

- api/rhsm-subscriptions-api-v1-spec.yaml
- swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java
- swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionTest.java
Jira issue: SWATCH-3824
~~Date filtering was failing for PAYG openshift products in the instance API. This was occurring because isPaygEligible() only checked for aws or azure metrics but these where rh marketplace only products. In order to properly check for payg eligibility I added a new field to explicitly set it per product.~~
This is working as expected but isPaygEligible was not including azureDimensions which is updated in this PR. No functional changes since all azure products are also on aws currently.
IQE Test MR: [] https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1295
1. Create snapshots for OpenShift-dedicated-metrics
2. Query instances API for date outside of snapshot_date month
3. No data should return
> SWATCH-3824: Date Filtering Not Working for OpenShift Products Instances API

- swatch-metrics-hbi/pom.xml
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/model/OutboxRecordMapper.java
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/repository/HbiEventOutbox.java
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/repository/converters/EventConverter.java
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/resources/InternalResource.java
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/services/HbiEventOutboxService.java
- swatch-metrics-hbi/src/main/resources/META-INF/openapi.yaml
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/repository/HbiEventOutboxRepositoryTest.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/resources/InternalResourceTest.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/services/HbiEventOutboxServiceTest.java
Jira issue: SWATCH-3778
Changes:
- Added service and test security schemas following the same pattern as in swatch-contracts.
- Followed the controller->service->repository pattern to implement this endpoint.
- Added "swatch_event_json" property in the request what was initially missing.
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1307
Added JUnit tests to cover these changes.
> SWATCH-3778: Implement POST /api/swatch-metrics-hbi/internal/outbox

- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/processing/handlers/CreateUpdateHostHandler.java
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/processing/handlers/DeleteHostHandler.java
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/services/HbiEventConsumer.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/processing/HbiEventProcessorTest.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/services/HbiEventConsumerTest.java
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/services/HbiEventConsumerTransactionBoundaryTest.java
Jira issue: SWATCH-3785
When swatch-metrics-hbi processes an HBI event, the resulting SWatch events are stored as JSON in persisted outbox records.
If an outbox record fails to persist, the DB transaction should get rolled back and the HBI event will be retried.
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/1321
Create the following test JSON files.
***NOTE:***
* Make sure that the stale_timestamp of the facts is not in the past, otherwise, these facts will not be considered during normalization.
* Make sure that the SYNC_TIMESTAMP of the **rhsm** facts less than 24h ago, otherwise the rhsm facts will not be considered and will not apply RHEL specific rules to the measurement (they will be normalized as is without considering …
> SWATCH-3785: Store SWatch events produced by SMHBI in outbox table

- swatch-common-security/src/main/java/com/redhat/swatch/common/security/RbacRolesAugmentor.java
- swatch-common-security/src/main/resources/application.properties
To avoid loading this Augmentor when not in use. The augmentor load is causing the RBAC configuration to be exercised, which leads to other issues. As the augmentor is not needed in all scenarios, this is the simplest solution.
> Add swatch-common-security.include-rbac for inclusion of RbacRolesAugmentor

- swatch-common-security/src/main/java/com/redhat/swatch/common/security/PskHeaderAuthenticationMechanism.java
- swatch-common-security/src/main/java/com/redhat/swatch/common/security/RolesAugmentor.java
- swatch-common-security/src/main/java/com/redhat/swatch/common/security/SecurityConfiguration.java
- swatch-metrics-hbi/pom.xml
- swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/resources/InternalResource.java
- swatch-metrics-hbi/src/main/resources/META-INF/openapi.yaml
- swatch-metrics-hbi/src/main/resources/application.properties
- swatch-metrics-hbi/src/test/java/com/redhat/swatch/hbi/events/resources/InternalResourceTest.java
Jira issue: SWATCH-3862
Enable the createOutboxRecord endpoint for the role 'test' only
IQE Test MR: No new tests needed
Run the tests locally in ```iqe_rhsm_subscriptions/tests/component/swatch_metrics_hbi/test_internal_api.py```
They will pass unless the SWATCH_TEST_APIS_ENABLED variable is set to false on the local swatch-metrics-hbi application, as is described below.
1.  ```podman-compose up -d```
2.  ```QUARKUS_SECURITY_AUTH_ENABLED_IN_DEV_MODE=true make build swatch-metrics-hbi```
1. ```
http POST :8015/api/swatch-metrics-hbi/internal/outbox --raw '{
"event_source": "HBI_HOST",
"event_type": "test",
"org_id": "org123",
"instance_id": "test-instance-id",
"service_type": "RHEL System",
"timestamp": 1756912842.587640403,
"conversion": false,
"isHypervisor": false,
"isVirtual": false, …
```
> SWATCH-3862: Configure swatch-common-security in swatch-metrics-hbi

- bin/dev-argfile.conf
The name of this configuration property changed at some point.
Run `bin/build-images.sh` and do an EE deployment.  Prior to this patch, Quarkus
apps would throw a ClassCastException complaining about
HibernateOrmDevIntegrator.
> Correct configuration property used for live-reload container builds

- Makefile
- docs/component-tests.md
- swatch-test-framework/src/main/java/com/redhat/swatch/component/tests/api/configuration/ServiceConfiguration.java
- swatch-test-framework/src/main/java/com/redhat/swatch/component/tests/configuration/ServiceConfiguration.java
- swatch-test-framework/src/main/java/com/redhat/swatch/component/tests/configuration/ServiceConfigurationBuilder.java
- swatch-test-framework/src/main/java/com/redhat/swatch/component/tests/core/ServiceContext.java
- swatch-test-framework/src/main/java/com/redhat/swatch/component/tests/logging/ContainerLoggingHandler.java
- swatch-test-framework/src/main/java/com/redhat/swatch/component/tests/logging/FileServiceLoggingHandler.java
- swatch-test-framework/src/main/java/com/redhat/swatch/component/tests/logging/OpenShiftLoggingHandler.java
- swatch-test-framework/src/main/java/com/redhat/swatch/component/tests/logging/ServiceLoggingHandler.java
- swatch-test-framework/src/main/java/com/redhat/swatch/component/tests/resources/containers/LocalContainerManagedResource.java
- swatch-test-framework/src/main/java/com/redhat/swatch/component/tests/resources/quarkus/LocalQuarkusManagedResource.java
Jira ticket: [SWATCH-4011](https://issues.redhat.com/browse/SWATCH-4011)
Allow attaching the debugger when running the component tests from:
- Intellij using debug mode
- from command line using "-Dswatch.component-tests.services.all.debug=true"
Note that this will only work when running the component tests locally. In the future, we can make it compatible when running the tests against an ephemeral environment. 
When running the tests in debug mode, all the logs will be printed even when the service has not started yet.
See video demostration here: 
https://github.com/user-attachments/assets/9f791a18-6339-425f-93d9-1a29ae43044f
> SWATCH-4011: Allow debugging SWATCH services when running component tests in debug mode

- build_deploy.sh
- pr_check.sh
- swatch-utilization/src/main/resources/application.properties
Jira issue: SWATCH-4003
Uncommit some TODO tasks to build the container for swatch-utilization and deploy it.
Additionally, I fixed a config issue that was causing the swatch-utilization service not to deploy.
CI is green
and running `bonfire deploy rhsm --source=appsre --ref-env insights-stage --component swatch-utilization --remove-dependencies swatch-utilization --component swatch-kafka-bridge` should work using the image tag generated as part of this pull request
> SWATCH-4003: Build image and deploy the swatch-utilization in EE

- swatch-core/src/test/java/org/candlepin/subscriptions/clowder/ClowderJsonPropertySourceTest.java
In mac, the temporal folder is created at 'file:/var/folders/0b/_8m7gctd65x5kpqd4rpv_7w80000gn/T/truststore1231686984112883276.trust instead of file:/tmp/truststore.*.trust in Linux.
These changes will cause the test to pass in both systems.
> ci: fix ClowderJsonPropertySourceTest in mac

- swatch-billable-usage/deploy/clowdapp.yaml
- swatch-contracts/deploy/clowdapp.yaml
- swatch-metrics/deploy/clowdapp.yaml
- swatch-system-conduit/deploy/clowdapp.yaml
- swatch-tally/deploy/clowdapp.yaml
Jira issue: SWATCH-4034
The IT team asked us to increase the memory limit for these jobs, and also configure it so the limits and the requests have the same constraint.
Apart from these changes, remove activeDeadlineSeconds which might be causing containers to be killed
No new pods triggered for jobs should be in error in Stage. 
We cannot test the changes in EE or local.
> SWATCH-4034: Remove activeDeadlineSeconds property and increase the memory requests/limits for jobs

- deploy/stage-internal-test-job.yaml
jira issue: SWATCH-4037 and SWATCH-4029
The iqe-tests: curiosity image has both the rhsm-subscriptions plugin and the rhsm-curiosity plugin.
Switching to use it for the stage tests for access to curiosity.
To be considered:
https://issues.redhat.com/browse/SWATCH-3463 enhances this change by ensuring the curiosity image is built more often.  Until that is complete, a new iqe-tests:curiosity image is only built when a change is made to the iqe-curiosity repo.
Current stage pipelines should no longer get the error message _AttributeError: 'Application' object has no attribute 'curiosity'_
> Fixes AttributeError: 'Application' object has no attribute 'curiosity'

- deploy/stage-internal-test-job.yaml
This reverts commit 83de898c753b29a298543360445e84a2b410446d.
Jira issue: SWATCH-4029
Using the iqe-tests:curiosity to run the iqe-rhsm-subscriptions tests doesn't work.  Both plugins are there but now rhsm-subscriptions tests fail with: AttributeError: 'Application' object has no attribute 'rhsm_subscriptions'
A new issue will be created to split the post-deploy job into 2.  One for curiosity and one for rhsm-subscriptions.
> Revert Fixes AttributeError: 'Application' object has no attribute 'curiosity'
