src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactSetNamespace.java
src/main/java/org/candlepin/subscriptions/tally/facts/normalizer/QpcFactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/normalizer/QpcFactNormalizerTest.java

Yupana is the system delivering the data, but the data itself is from
QPC.

Rename Yupana to QPC in the code.

---

Jenkinsfile

I set up webhook forwarding using smee.io, so we can actually gate on the tests again. :smile:

Analyze with sonarcloud.io

---

src/main/java/org/candlepin/subscriptions/jobs/CaptureSnapshotsJob.java
src/main/java/org/candlepin/subscriptions/tally/ProductUsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/UsageSnapshotProducer.java
src/main/java/org/candlepin/subscriptions/tally/roller/DailySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/MonthlySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/QuarterlySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/WeeklySnapshotRoller.java
src/main/java/org/candlepin/subscriptions/tally/roller/YearlySnapshotRoller.java

This change make the snapshot production process a little less noisy.

Improved logging for snapshot production

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

In terms of priority, system profile facts are lowest, we can adjust
this in the future though.

Gather cores/sockets from system profile

---

api/rhsm-subscriptions-api-spec.yaml

It is designed to be symmetric with the tally API for consistency.

Add capacity API

---

src/main/java/org/candlepin/subscriptions/jmx/TallyJmxBean.java
src/main/java/org/candlepin/subscriptions/tally/UsageSnapshotProducer.java

To test, run jconsole against a running instance and observe that the
operation is available under org.candlepin.subscriptions.jmx ->
TallyJmxBean -> tallyJmxBean -> Operations -> tallyAccount.

Add TallyJmxBean

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java

Also, add these fields to the mock responses.

Differentiate physical/hypervisor sockets in API

---

src/main/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapper.java
src/main/java/org/candlepin/subscriptions/capacity/CapacityProductExtractor.java
src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacity.java
src/test/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapperTest.java
src/test/java/org/candlepin/subscriptions/capacity/CapacityProductExtractorTest.java

Depends on #59 ... so marking as draft until #59 merged.

Add component to map candlepin pools to capacity

---

api/rhsm-subscriptions-api-spec.yaml

These descriptions are pretty elementary.  I'd be interested in opinions on improving them.  Especially `instance_count` and its relatives.

Add description field to API spec for TallySnapshot,

---

src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java

Fixes
```
org.springframework.orm.jpa.JpaSystemException: Could not resolve column name in result set [system_profile_infrastructure_type]
```

Prepend sytem_profile_ to infrastructure_type

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepository.java
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java

If the SLA is not a good value, then the response will be a bad request.

Add SLA to capacity API

---

src/main/java/org/candlepin/subscriptions/capacity/CandlepinPoolCapacityMapper.java

I've got a follow up that will go to subscription-conduit as well.  Sorry this took me awhile.  I had kind of forgotten how all the ingress stuff works.  We should probably write a doc on it :)

Store Candlepin product ID as the SKU in the capacity table.

---

src/main/java/org/candlepin/subscriptions/files/PerLineFileSource.java
src/main/java/org/candlepin/subscriptions/files/ProductWhitelist.java

I did this by adding a secondary cache to the per-line file source which
creates a Set rather than a list.

Respect TTL for product whitelist cache

---

src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacity.java
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/db/model/Usage.java
src/main/resources/liquibase/202005041611-add-usage-column-to-snapshot-and-capacity-tables.xml
src/main/resources/liquibase/changelog.xml

To test, launch the application, and observe that DB changes were applied successfully.

Add usage fields to capacity and snapshot tables

---

api/rhsm-subscriptions-api-spec.yaml
bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/db/HostRepository.java
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/db/model/HostBucketKey.java
src/main/java/org/candlepin/subscriptions/db/model/HostTallyBucket.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/resources/liquibase/202006180903-add-usage-to-host.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java

To test
-------
Insert some rows in the db to mock systems:
```
bin/insert-mock-hosts --num-physical 2 --num-hypervisors 1 --num-guests 3
```
Then try out the API via swagger UI or use curl (e.g.):
```
curl -H "x-rh-identity: eyJpZGVudGl0eSI6eyJhY2NvdW50X251bWJlciI6ImFjY291bnQxMjMiLCJ0eXBlIjoiVXNlciIsInVzZXIiOnsiaXNfb3JnX2FkbWluIjp0cnVlfSwiaW50ZXJuYWwiOnsib3JnX2lkIjoib3JnMTIzIn19fQo" "http://localhost:8080/api/rhsm-subscriptions/v1/hosts/products/RHEL?usage=Production&limit=1"
```

Implement hosts API

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java

Fixes a number of small issues reported by @ntkathole:
- granularity not used in hosts API (was causing generated client issues).
- usage not populated
- usage, sla not validated

Hosts API fixes

---

src/main/java/org/candlepin/subscriptions/security/SecurityConfig.java

To test, delete opt-in, and observe `SUBSCRIPTIONS1004`.
Opt-in and observe regular responses.

Apply opt-in filter to hosts APIs

---

build.gradle

To test, try `./gradlew -q dependencyJson | python -m json.tool`.

Add dependencyJson gradle task

---

README.md
gradle.properties
templates/rhsm-subscriptions-api.yml
templates/rhsm-subscriptions-capacity-ingress.yml
templates/rhsm-subscriptions-jobs.yml
templates/rhsm-subscriptions-scheduler.yml
templates/rhsm-subscriptions-worker.yml

See README.md changes for details.

Add templates for app-interface

---

bin/insert-mock-hosts

This was done to match the host creation functionality when a
tally is performed.

Update import script to add _ANY sla/usage bucket records

---

templates/rhsm-subscriptions-worker.yml

They don't do anything as just template parameters. Doh!

Move hawtio/jolokia env vars to proper place

---

templates/rhsm-subscriptions-api.yml

New service limit ratio between limit and request is 2 or less.

Bump memory request to satisfy service limit

---

api/rhsm-subscriptions-api-spec.yaml
bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/db/model/HostHardwareType.java
src/main/java/org/candlepin/subscriptions/db/model/TallyHostView.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/main/resources/liquibase/202009211317-add-additional-host-fields.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

Added DB/API fields:
* is_unmapped_guest
* is_hypervisor
* cloud_provider
HardwareType is one of 3 values:
* CLOUD
* PHYSICAL
* VIRTUALIZED
Fix broken script and set new fields

Make changes to system table API to support GUI

---

src/main/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollector.java

Previously systems were confusingly classified as either physical or
"total".

Classify systems as either virtual or physical.

---

src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

Regression introduced in #218, doh!

Fix NPE on cloudmeter flag population

---

build.gradle
src/main/java/org/candlepin/subscriptions/rbac/RbacApiClient.java

Run: **./gradlew clean test** and make sure that everything still compiles.

Upgrade openapi codegen gradle plugin

---

src/main/java/org/candlepin/subscriptions/task/queue/inmemory/ExecutorTaskQueue.java

In order to avoid potential ConcurrentModificationException...

Change ExecutorTaskQueue to ConcurrentHashMap

---

src/main/java/org/candlepin/subscriptions/db/model/Offering.java
src/main/resources/liquibase/202101081600-tweak-offering.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/OfferingRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/model/OfferingTest.java

Part of collaboration w/ @mstead @lindseyburnett @jdhrh @redsaz

Tweak offering model and add some docs

---

src/main/java/org/candlepin/subscriptions/capacity/PoolIngressController.java
src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
src/main/resources/liquibase/202101121122-add-subscription-table.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/capacity/PoolIngressControllerTest.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java

Add subscription entity

---

templates/rhsm-subscriptions-worker.yml

To fix https://issues.redhat.com/browse/ENT-3423

Apply kakfa-queue to worker deployment

---

build.gradle

Needed to add a plugin to perform downloads in order to fetch the
OpenAPI spec files.

Update openapi generator

---

src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java

Added a counter to record the total number of hosts processed, and register it to "rhsm-subscriptions.capacity.records_total" in Micrometer.  Please see the reference card for live test instructions.

ENT-2192: added a counter for total hosts.

---

build.gradle
src/main/resources/static/api-docs/index.html

See https://www.webjars.org/documentation#springboot
Without this change, #265 and similar require extra work.

Use webjars-locator to decouple from swagger-ui version

---

src/main/java/org/candlepin/subscriptions/capacity/PoolIngressController.java
src/test/java/org/candlepin/subscriptions/capacity/PoolIngressControllerTest.java

Small oversight, we were grouping existing subscriptions by SKU rather than by subscription ID, which causes problems when there is more than one sub for a given SKU.

ENT-3430: Fix regression: allow multiple subscriptions per SKU

---

src/main/java/org/candlepin/subscriptions/db/AccountRepository.java
src/main/java/org/candlepin/subscriptions/db/model/Account.java
src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/db/model/HostBucketKey.java
src/main/java/org/candlepin/subscriptions/db/model/TallyMeasurementKey.java
src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
src/main/java/org/candlepin/subscriptions/tally/AccountUsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/UsageCalculation.java
src/main/java/org/candlepin/subscriptions/tally/roller/BaseSnapshotRoller.java
src/main/resources/liquibase/202101260823-add-measurements-tables.xml
src/main/resources/liquibase/202101291558-modify-hosts-for-non-hbi-sources.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/AccountRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/SnapshotRollerTester.java

Given that this is not yet integrated generally, unit tests will have to suffice for now.

Add MetricUsageCollector

---

src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/main/java/org/candlepin/subscriptions/tally/UsageSnapshotProducer.java
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java

Depends on #311 (to actually get the hourly producer invoked).
To test, insert some events into the DB with this SQL:
```sql
insert into events(id, account_number, timestamp, data) values ('033a45b7-e8c4-440a-b0bb-76c3f3f67d85','account123', '2021-01-01T00:00Z', '{"account_number":"account123","event_id":"033a45b7-e8c4-440a-b0bb-76c3f3f67d85","service_type":"OpenShift Cluster","instance_id":"4e8534b5-42b5-4f00-9969-29046e2b1986","measurements": [{"uom":"Cores","value":4.0}]}');
insert into events(id, account_number, timestamp, data) values ('a66ac2a1-17c0-4bc3-bc29-0430953d626c','account123', '2021-01-01T01:00Z', '{"account_number":"account123","event_id":"a66ac2a1-17c0-4bc3-bc29-0430953d626c","service_type":"OpenShift Cluster","instance_id":"4e8534b5-42b5-4f00-9969-29046e2b1986","measurem …
```

Produce hourly for each hour

---

src/main/java/org/candlepin/subscriptions/db/model/Host.java
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHostFacts.java
src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
src/test/java/org/candlepin/subscriptions/db/model/HostTest.java

Fixing a file where this occurs, adding some backstop code for future
occurrences (credit lburnett)

ENT-3562: null while collecting existing snapshot of account.

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/HostsResource.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/HostsResourceTest.java

Fix sorting for hourly instances

---

src/main/java/org/candlepin/subscriptions/files/ProductProfile.java
src/main/java/org/candlepin/subscriptions/files/ProductProfileRegistry.java
src/test/java/org/candlepin/subscriptions/files/ProductProfileRegistryTest.java

Include the swatch product IDs defined by roles
in the product registry.

Include swatch product IDs defined in roles

---

src/main/java/org/candlepin/subscriptions/files/MarketplaceMetric.java
src/main/java/org/candlepin/subscriptions/files/ProductProfile.java
src/main/java/org/candlepin/subscriptions/files/ProductProfileRegistry.java
src/main/java/org/candlepin/subscriptions/files/ProductUom.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapper.java
src/main/resources/product_profile_registry.yaml
src/test/java/org/candlepin/subscriptions/files/ProductProfileRegistryTest.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapperTest.java
src/test/resources/test_product_profile_registry.yaml

The testing for this is mainly unit testing, but I'm open to suggestions.

ENT-3610: Put usage metric id in the product registry yaml

---

src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceJmxBean.java
src/main/java/org/candlepin/subscriptions/marketplace/MarketplaceProperties.java
src/main/resources/application-marketplace.yaml
src/test/java/org/candlepin/subscriptions/marketplace/MarketplaceJmxBeanTest.java

Allow toggling submitTallySummary JMX operation via
configuration or environment variable.
```bash
DEV_MODE=true ./gradlew clean bootRun
$ curl 'http://localhost:8080/actuator/hawtio/jolokia/' -H 'Content-Type: application/json' -d '{"type":"exec","mbean":"org.candlepin.subscriptions.marketplace:name=marketplaceJmxBean,type=MarketplaceJmxBean","operation":"submitTallySummary(java.lang.String)","arguments":[""]}'
{"request":{"mbean":"org.candlepin.subscriptions.marketplace:name=marketplaceJmxBean,type=MarketplaceJmxBean","arguments":[""],"type":"exec","operation":"submitTallySummary(java.lang.String)"},"error_type":"com.fasterxml.jackson.databind.exc.MismatchedInputException","error":"com.fasterxml.jackson.databind.exc.MismatchedInputException : No content to map due to end-of-input\n at …
```

Allow toggling submitTallySummary JMX operation

---

build.gradle
src/main/java/org/candlepin/subscriptions/db/HostSpecification.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java

Fairly extensive unit testing was added.

ENT-3686: sorting by monthlyTotals may be incorrect

---

src/main/resources/liquibase/202104091791-insert-openshift-skus.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/OfferingRepositoryTest.java

Future work will sync this data from upstream services.
Related: #369.
Testing
-------
`./gradlew bootRun`
Then check the DB for the new records:
```sql
select * from offering
```

ENT-3739: Insert osd, ocp SKU data

---

templates/marketplace-worker.yml
templates/metrics-worker.yml

Not pressing, overridden in the meanwhile in app-interface.

Make unique hawtio paths for new workers

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionService.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionServiceProperties.java
src/main/resources/application.yaml
templates/marketplace-worker.yml

Testing: set env var, run in debug, see property get set by env var :-)

Add page size subscription config property

---

src/main/resources/product_profile_registry.yaml

Testing
-------
This is really just a data update, but if desired, you can repeat
testing steps from #350 to see the metric applied.

ENT-3737: Update metricIds for OCP and OSD

---

src/main/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapper.java
src/test/java/org/candlepin/subscriptions/marketplace/MarketplacePayloadMapperTest.java

[ENT-3757](https://issues.redhat.com/browse/ENT-3757)
When marketing ID of redhat.com:openshift_dedicated:4cpu_hour is processed,
divide Cores by 4 when creating marketplace UsageMetrics.
This is required since RHM does not have a way to do the automatic divide by 4
for OSD SKUs.

ENT-3757: Divide cores by 4 when creating RHM payload

---

templates/metrics-worker.yml
templates/rhsm-subscriptions-worker.yml

Add keystore info for user service

---

api/rhsm-subscriptions-api-spec.yaml
rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java
src/test/java/org/candlepin/subscriptions/conduit/inventory/DefaultInventoryServiceTest.java

Looking for feedback on the scope of changes for this card.  Testing instructions are forthcoming.

ENT-3750: Add Billing Type to Host Based Inventory

---

src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java
src/main/java/org/candlepin/subscriptions/db/model/Offering.java
src/main/java/org/candlepin/subscriptions/db/model/Subscription.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionRepositoryTest.java

ENT-3773: If two or more subscriptions exist in Marketplace, pick the newest

---

src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

To be addressed in https://issues.redhat.com/browse/ENT-3818

Disable running total format for now

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

Note that there's RHSM API work that needs to happen before this can be tested with real data (see linked issue in Jira).

ENT-3308: Populate displayName via openshift.cluster_id

---

src/main/java/org/candlepin/subscriptions/files/ProductMappingConfiguration.java
src/main/java/org/candlepin/subscriptions/files/TagMapping.java
src/main/java/org/candlepin/subscriptions/files/TagMetaData.java
src/main/java/org/candlepin/subscriptions/files/TagMetric.java
src/main/java/org/candlepin/subscriptions/files/TagProfile.java
src/main/resources/tag_profile.yaml
src/test/java/org/candlepin/subscriptions/files/TagProfileFactoryTest.java
src/test/java/org/candlepin/subscriptions/files/TagProfileTest.java

Unit tests included.  Regression tests not needed for this stage of development.

ENT-3836: Update our configuration so that we can support multi-metric products

---

src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java

Already handled by existing code, so this change is unit test only

ENT-3841: Add tests for instance-hour events

---

src/main/java/org/candlepin/subscriptions/files/TagProfile.java
src/main/resources/tag_profile.yaml
src/test/java/org/candlepin/subscriptions/files/TagProfileFactoryTest.java

https://issues.redhat.com/browse/ENT-3838
https://issues.redhat.com/browse/ENT-3839
I went ahead and removed the small bit of RHEL config we had from the file, since it's not in use yet (Let's handle remaining pieces in one big batch).
I also reworked the tests to check consistency of the tag profile file rather than looking for explicit values.
Testing
-------
Given this is a just a config change, needs to be tested w/ changes from https://issues.redhat.com/browse/ENT-3871

ENT-3838, ENT-3839: Update tag profile for OCD and OCP

---

src/main/resources/application-capacity-ingress.yaml

Fixes:
```
2021-07-09 16:53:34,051 [thread=restartedMain] [ERROR] [org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter] -
***************************
APPLICATION FAILED TO START
***************************
Description:
Failed to bind properties under 'rhsm-subscriptions.subscription-sync-enabled' to boolean:
Property: rhsm-subscriptions.subscription-sync-enabled
Value: ${SUBSCRIPTION_SYNC_ENABLED}
Origin: class path resource [application-capacity-ingress.yaml] - 3:30
Reason: failed to convert java.lang.String to boolean (caused by java.lang.IllegalArgumentException: Invalid boolean value [${SUBSCRIPTION_SYNC_ENABLED}])
Action:
Update your application's configuration
```

Default SUBSCRIPTION_SYNC_ENABLED to true for dev purposes

---

src/main/java/org/candlepin/subscriptions/conduit/tasks/UpdateOrgInventoryTask.java

A better log message to help narrow down what's going on with ENT-3953

Log which org caused an APIException in RhsmService

---

insights-inventory-client/src/main/java/org/candlepin/subscriptions/inventory/client/InventoryServiceProperties.java

Remove redundant getter/setter annotations

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/SubscriptionResource.java
src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionTableController.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/SubscriptionResourceTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SearchCriteria.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SearchOperation.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewSpecification.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/SubscriptionCapacityView.java

- Create SubscriptionResource to implement SubscriptionAPI
- Add SubscriptionTableController to accept inputs from resource and generate a SkuCapacityReport
- Add SubscriptionCapacityView that creates a view that's a join between SubscriptionCapacity, Subscription and Offering
- Add SubscriptionCapacityRepository that uses a SubscriptionCapacityViewSpecification to find capacities
- Add tests at all layers

API for subscription table

---

src/main/java/org/candlepin/subscriptions/jmx/SubscriptionJmxBean.java

So we can access/trigger them from the Hawtio console

Make Subscription JMX methods public 

---

templates/rhsm-subscriptions-capacity-ingress.yml

so spring actuator jolokia can work

Turn off in built Jolokia for capacity-ingress 

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java

- PoolIngressController does not reconcile capacities if the sku is not on the product allowlist
- To match, we need to not add a subscription or reconcile capacity for subscription sync as well
- Because the sku will never be added to the offering table because it's not on the allowlist and will cause exceptions while creating subscriptions and capacities

Skip syncing a subscription if it's not on the allow list

---

src/main/resources/application-capacity-ingress.yaml
src/main/resources/application.yaml
templates/rhsm-subscriptions-scheduler.yml

This allows the "sync all offerings" operation to work during the periodic sync cron job.

ENT-4259 Move product whitelist config to core app config

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java

**NOTE: Plucked this change out of 'develop' to be included in the next RC.**
Throw exception if Subscription received from subscription service does not sku on it
Skip syncing subscription of offering is not present in Offering repository and continue syncing next subscription

Skip syncing a subscription if it's not on the allowlist

---

templates/rhsm-subscriptions-capacity-ingress.yml

- Add subscription_url to integrate with subscription service
- Add product_url to integrate with product service

Add subscription and product params to openshift env

---

src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/test/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepositoryTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SearchOperation.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionCapacityViewSpecification.java

Update subscription capacity view repository specification to allow filtering by UOM
Fixes issue described in https://issues.redhat.com/browse/ENT-4343

Add filtering by UOM

---

src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java

https://issues.redhat.com/browse/ENT-4506
I found we aren't actually generating a monthly snapshot at all. So
instead of doing that, I opted to aggregate in-memory since we typically
pull in the whole months worth of data anyways, and I put some
safeguards in around this (see NOTEs in TallyResource).
Testing
-------
1. Start the application:
```
SPRING_PROFILES_ACTIVE=worker,api DEV_MODE=true ./gradlew :bootRun
```
2. Insert a mock event:
```
curl 'http://localhost:8080/actuator/hawtio/jolokia' \
-H 'Content-Type: text/json' \
-d '{
"type":"exec",
"mbean":"org.candlepin.subscriptions.jmx:name=eventJmxBean,type=EventJmxBean",
"operation":"saveEvents(java.lang.String)",
"arguments":["[{
\"event_source\": \"prometheus\",
\"event_type\": …
```

ENT-4506 Tally API: Populate totalMonthly using daily data

---

build.gradle
deploy/rhsm-clowdapp.yaml
src/main/java/org/candlepin/subscriptions/BootApplication.java
swatch-core/build.gradle
swatch-core/src/main/java/org/candlepin/subscriptions/logback/RhsmSplunkHecEventHeaderSerializer.java
swatch-core/src/main/java/org/candlepin/subscriptions/logback/RhsmSplunkHecUtil.java
swatch-core/src/main/resources/logback-spring.xml

Relates to: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/29062
Testing:
1.  Pull branch
2.  Build image and push to quay
3.  Deploy to ephemeral environments using bonfire
```
bonfire deploy rhsm-subscriptions \
--no-remove-resources=all \
-i quay.io/lburnett/rhsm=splunk_hec \
-p rhsm-subscriptions/IMAGE=quay.io/lburnett/rhsm \
-i quay.io/awood/swatch-system-conduit=latest \
-p rhsm-subscriptions/CONDUIT_IMAGE=quay.io/awood/swatch-system-conduit \
--timeout 3600
```
4.  Take note of ephemeral environment it deployed to and go see that the logs are getting sent to splunk
https://splunk.corp.redhat.com/en-US/app/search/search
`index=rh_rhsm namespace="ephemeral*"`

ENT-4530: Splunk HEC MVP

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

Candlepin has a limit of 255 chars for a given fact. When a fact is sent
that has a longer value, the value is truncated, and the last 3
characters are replaced with "...".
In ENT-4260, we began to populate network interfaces. However, the code
did not filter out truncated IP addresses. This commit corrects that
issue and also refactors some of the IP address handling code to better
isolate logic in methods.

ENT-4607: Handle truncated IP addresses when gathering NIC info for HBI

---

bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
src/test/java/org/candlepin/subscriptions/tally/collector/DefaultProductUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

https://issues.redhat.com/browse/ENT-4663
Add new field for Marketplace in NormalizedFacts
Add new test parameters for marketplace field
Add populating logic for isMarketplace.
Add logic to applied sockets to ignore zeros for marketplace
Create new test case for expected behavior of marketplace instances for RHEL or other products
Add logic for ismarketplace in mock host script
1.Environment Variables:
```
SPRING_PROFILES_ACTIVE=worker,api DEV_MODE=true
```
2. Login to insights database and than insert mock data
```
insert into hosts(
id,
account,
display_name,
created_on,
modified_on,
facts,
canonical_facts,
system_profile_facts,
stale_timestamp,
reporter
) values (
gen_random_uuid(),
'account123',
'marketplace-test',
now(),
now(),
'{"rhsm": {"orgId": "org123", …
```

ENT-4663: Add logic to applied sockets to ignore zeros from marketplace

---

bin/insert-mock-hosts
src/main/java/org/candlepin/subscriptions/inventory/db/model/InventoryHost.java

https://issues.redhat.com/browse/ENT-4625
Test Steps:
- Create hbi hosts using insert-mock-hosts scripts and set --host-type to 'edge'
- Run a tally for the account
- Check db to ensure edge systems were not tallied for

ENT-4625: Filter out edge systems from HBI

---

templates/rhsm-subscriptions-capacity-ingress.yml

Fixes
```
MountVolume.SetUp failed for volume "ingress" : secret "ingress" not found
```

Remove remaining ingress secret references

---

src/main/java/org/candlepin/subscriptions/metering/MeteringEventFactory.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/test/java/org/candlepin/subscriptions/metering/MeteringEventFactoryTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java
swatch-core/schemas/event.yaml

https://issues.redhat.com/browse/ENT-4683

ENT-4683: add support for billing_provider label to event schema

---

podman_run.sh

Bump max lifetime on podman for tests to 1 hour

---

podman_run.sh

Our CI *build* infrastructure runs an older version of podman.
The only downside is being not being able to launch additional containers from inside the command invoked with podman_run.sh, but this doesn't matter for the container image builds.

Tolerate older podman in podman_run.sh

---

src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java

Fix a potential NPE during fact normalization.
I was not able to reproduce the issue in [ENT-4755](https://issues.redhat.com/browse/ENT-4755) but identified/addressed a potential place for an NPE to occur.

ENT-4755 Fix potential NPE on syncTimestamp check

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/ReportCriteria.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/main/resources/liquibase/202203241102-add-billing-provider-column-to-tally-snapshots.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/TallySnapshotRepositoryTest.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
src/test/java/org/candlepin/subscriptions/tally/roller/SnapshotRollerTester.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallySnapshotRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillingProvider.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
swatch-core/src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java

https://issues.redhat.com/browse/ENT-4687
Update ReportCriteria with BillingProvider field.
Add new method for sanitizing billing provider in ResourceUtils.
Update yaml for Tally metadata to include billing provider.
Add implementation for billing provider for TallyResource.
Rework Unit tests to include billing provider as a parameter.
Update Tally db model for billing provider & repository.

Update Tally Api with Billing Provider

---

templates/rhsm-subscriptions-capacity-ingress.yml
templates/rhsm-subscriptions-worker.yml

Required for exposing the internal service to test

expose worker api through openshift service

---

dependencies.gradle
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallySnapshot.java
swatch-core/src/main/java/org/candlepin/subscriptions/tally/UsageCalculation.java

Closes #938
I started with the dep update from that PR and then simply ran:
```
./gradlew spotlessApply
```

Bump spotless-plugin-gradle from 6.4.2 to 6.5.1

---

src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
src/main/resources/liquibase/202205191543-recreate-billing-columns.xml
src/main/resources/liquibase/changelog.xml

Recreate billing columns with default values to resolve error in liquibase on startup

Fix db issues around billing columns

---

Jenkinsfile

To workaround odd issues where sonar cannot figure out where to cache
things.

Set user.home to /tmp for sonar steps

---

src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java

https://issues.redhat.com/browse/ENT-5050
Testing
-------
First, repro on `develop`, then switch to this branch and observe no errors:
```
DEV_MODE=true SPRING_PROFILES_ACTIVE=worker ./gradlew :bootRun
```
Add an event:
```
curl \
http://localhost:9000/hawtio/jolokia \
-H 'Content-Type: application/json' -d '{
"mbean": "org.candlepin.subscriptions.jmx:name=eventJmxBean,type=EventJmxBean",
"arguments": ["[{
\"event_source\": \"prometheus\",
\"event_type\": \"snapshot_redhat.com:openshift_dedicated:4cpu_hour\",
\"account_number\": \"account123\",
\"instance_id\": \"9942bc07-e93e-4ff6-99e3-c85a73604d67\",
\"timestamp\": \"2022-05-27T01:00:00Z\",
\"expiration\": \"2022-05-27T02:00:00Z\",
\"billing_account_id\": null,
\"measurements\": [{
\"uom\": \"Cores\", \"value\": 1
}],
\"role\": \"osd\", …
```

ENT-5050: Handle Optional.empty in MetricUsageCollector

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/test/java/org/candlepin/subscriptions/metering/RhosakTagProfileTest.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java
swatch-core/schemas/event.yaml
swatch-core/schemas/tally_snapshot.yaml
swatch-core/src/main/resources/tag_profile.yaml
swatch-producer-aws/src/test/java/com/redhat/swatch/com/redhat/swatch/processors/BillableUsageProcessorTest.java
swatch-producer-aws/src/test/java/com/redhat/swatch/files/TagProfileTest.java

Update Tag profile with new configuration for rhosak
Add new Unit Test to verify that configuration is working.
Update event.yaml & tally_snapshot.yaml for new UOM

ENT-5016: Add Monthly Storage metric to rhosak tag metrics

---

deploy/rhsm-clowdapp.yaml
templates/metrics-worker.yml
templates/rhsm-conduit.yaml
templates/rhsm-subscriptions-api.yml
templates/rhsm-subscriptions-capacity-ingress.yml
templates/swatch-billing-provider-rh-marketplace.yml

https://issues.redhat.com/browse/ENT-4999 
Test steps: Deployed to EE and checked that YAML was updated

ENT-4999: Update liveness probes to use liveness endpoint

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/OfferingRepository.java

https://issues.redhat.com/browse/ENT-5065

ENT-5056: log when billing provider is missing on payg subs

---

src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceSubscriptionIdProvider.java
src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResourceTest.java
src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplaceSubscriptionIdProviderTest.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java

https://issues.redhat.com/browse/ENT-5083
Tested using StubSearchAPI and debugged to see that the standard subscription gets filtered and the AWS one is not.

ENT-5083: sync only payg subscriptions

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java

Updated the logs so what we debug all required information on a single
log entry.

Update monthly billing logs in Tally

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/OfferingRepository.java

https://issues.redhat.com/browse/ENT-5065
Test Steps:
- Add MW01882 Red Hat OpenShift Streams for Apache Kafka (Hourly) SKU in account
- Sync capacity
- Check SKU populated in subscription table and log displays

ENT-5056: Use productName to get tagProfile 

---

docker-compose.yml

Hints from https://hellokube.dev/posts/three-ways-zookeepeerless-kafka/

Run kafka in kraft mode (zookeeper-free)

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResource.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/EnumParamConverterProvider.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/JaxrsApplication.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/JaxrsApplicationServletInitializer.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/MicrometerUriHackFilter.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/ObjectMapperContextResolver.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/OffsetDateTimeParamConverterProvider.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/PageLinkCreator.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/ResteasyConfiguration.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/security/ApiSecurityConfiguration.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/security/RbacConfiguration.java
swatch-system-conduit/src/main/resources/application.yaml
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResourceTest.java

https://issues.redhat.com/browse/ENT-5028

ENT-5028 PULL Sync single org method API implementation

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResource.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/admin/InternalOrganizationSyncResourceTest.java

https://issues.redhat.com/browse/ENT-5029

API Sync all Orgs Implementation

---

swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java

This also makes it easier to sort the info & the error logs.

Replace duplicate log msg in a simpler form

---

dependencies.gradle
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringController.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSourceTest.java
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusMeteringControllerTest.java

https://issues.redhat.com/browse/ENT-5067

ENT-5067: Update openapi-generator to 6.0.1

---

deploy/rhsm-clowdapp.yaml
templates/rhsm-conduit.yaml

https://issues.redhat.com/browse/ENT-5030

rhsm-conduit-cron job Openshift def is converted to use rest endpoint

---

deploy/rhsm-clowdapp.yaml
swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-453
Tested by deploying to EE

SWATCH-453: fix clowder db secrets

---

swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-452

SWATCH-452: add missing splunk env vars to swatch-producer-rh clowdapp

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/CapacityResource.java
src/test/java/org/candlepin/subscriptions/resource/CapacityResourceTest.java

https://issues.redhat.com/browse/SWATCH-103
This MR is specifically to fix the response of the API to match expected in the above card.
Original MR with test steps: https://github.com/RedHatInsights/rhsm-subscriptions/pull/1206

SWATCH-103: update Capacity by metricId response to match expected

---

swatch-metrics/deploy/clowdapp.yaml

Corresponding MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/44434

Parameterize the host-inventory db secret key name

---

swatch-metrics/deploy/clowdapp.yaml

Should fix failure to deploy in EE.

Fix EE deployment issues

---

Jenkinsfile

Add manual approval for forks

---

src/main/resources/liquibase/202207051557-transition-deprecated-columns.xml

NOTE: I was unable to reproduce. Hoping to get this into stage, and see if it helps.

Limit trigger recursion to (hopefully) avoid deadlock

---

templates/rhsm-subscriptions-scheduler.yml

Add missing DB_CHANGELOG_CLEANUP_SQL env var

---

src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/test/java/org/candlepin/subscriptions/metering/RhacsTagProfileTest.java
swatch-core/schemas/event.yaml
swatch-core/src/main/resources/tag_profile.yaml

Draft to add RHACS metrics configuration to Subscription Watch. @kahowell could you take a look and advise if this looks correct?

Add RHACS metrics configuration

---

swatch-system-conduit/deploy/clowdapp.yaml

See appropriate service name in stage (e.g. svc/swatch-system-conduit-service).
I also removed a redundant IMAGE_TAG template parameter.

Fix hostname in curl command for conduit cronjob

---

swatch-subscription-sync/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-511
Test Steps:
- Deploy to EE
- Check config map capacity-allowlist for new entries

SWATCH-511: add rhacs skus to product allow list

---

src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/resources/liquibase/202208231107-update-account-service-with-orgId.xml
src/main/resources/liquibase/202208231227-add-org-id-to-account-service-table.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/AccountServiceInventory.java

Created new changelog for Account service table
Add new field for AccountServiceInventory
Add new logic for UsageCollector for both Inventory & Metrics
Add Draft changelog for future cards are completed.

SWATCH-279: Add OrgId to Account services table and implement placeholders

---

src/main/resources/liquibase/202209121018-update-primary-key-of-account-config.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/AccountConfigRepositoryTest.java
src/test/java/org/candlepin/subscriptions/security/OptInControllerTest.java

https://issues.redhat.com/browse/SWATCH-488

SWATCH-488: set account_config pk to org_id

---

swatch-tally/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-520

SWATCH-502: use specific image tag for org id populator

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryServiceProperties.java
swatch-system-conduit/src/main/resources/application.yaml
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java

This appears to be the only topic we missed when having our code reference actual topic names from clowder config.

Fix inventory host ingress references

---

swatch-core/src/main/java/org/candlepin/subscriptions/clowder/RdsSslBeanPostProcessor.java

https://issues.redhat.com/browse/SWATCH-102

SWATCH-102: add logging for ssl mode connection

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java

https://github.com/RedHatInsights/rhsm-subscriptions/pull/1527

Add accountnumber to DTO for subscription force sync to subscription table

---

src/main/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategy.java
src/test/java/org/candlepin/subscriptions/tally/CombiningRollupSnapshotStrategyTest.java

Same as #1560, but cherry-picked to hotfix branch.
This corrects a bug where we were clearing hourly measurements on processing each successive hour in a given day. This was happening because we adjust the range of fetched existing snapshots to include enough to aggregate the next granularity (hourly -> daily), and we were treating all fetched snapshots as affected by the gathered usage (rather than just the given hour).
Testing
=======
Run through these steps once on `hotfix` or `main`, and then on this branch.
Run mock prometheus:
```shell
bin/prometheus-mock-data.sh
```
Clear state:
```shell
delete from tally_snapshots cascade;
delete from hosts cascade;
EOF
```
```shell …
```

SWATCH-654: [hotfix] bugfix: only a single set of measurements kept per day

---

src/main/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/main/java/org/candlepin/subscriptions/tally/facts/NormalizedFacts.java
src/test/java/org/candlepin/subscriptions/db/model/HostTest.java
src/test/java/org/candlepin/subscriptions/tally/collector/RHELProductUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/collector/TestHelper.java

I've got a few points to discuss with the reviewer:
* How should QE plan on testing this?
* Do we need to worry about migrating existing HostTallyBuckets?

SWATCH 408: Tally hypervisors as hypervisors, not virtual systems

---

swatch-subscription-sync/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-607
https://issues.redhat.com/browse/SWATCH-606

Add skus to allow list MW01802, SER0705

---

swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java

Updating this in hotfix in order to enable fixes for alerting.

[hotfix] Add more information to logging

---

swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java

This is an experimental add to set OrgId and account_id when processing BillableUsage events in swatch-producer-aws. This will create a properties block on the event in splunk that contains each of the MDC attributes. After verification of how well this works we can examine whether it is worth spreading the pattern more widely or reverting.

Add MDC properties for  BillableUsage messages

---

src/test/java/org/candlepin/subscriptions/validator/MacAddressValidatorTest.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/ConduitFacts.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

SWATCH-575: Apply MAC address validation on HbiNetworkInterface object creation

---

swatch-subscription-sync/deploy/clowdapp.yaml

There were a few SKUs added to the internal repo not yet present in this repo.

Sync allowlist with internal repo

---

swatch-subscription-sync/deploy/clowdapp.yaml

There were some SKUs present in our internal repo not yet in this repo's copy.

[hotfix] Sync allowlist with internal repo

---

dashboards/grafana-dashboard-subscription-watch.configmap.yaml

Turn on syncing of cross-hairs between widgets
Enable shared crosshair to make investigating events across widgets easier

Update dashboard to use new timeseries widgets & enable shared crosshair

---

dashboards/grafana-dashboard-subscription-watch.configmap.yaml

The divide by 1000000 in the equation is to convert to Mi used by app-interface specification.

Add pod level memory widget for the tally services

---

src/main/java/org/candlepin/subscriptions/capacity/CapacityReconciliationConfiguration.java
src/main/java/org/candlepin/subscriptions/product/ProductConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/billing/BillingProducerConfiguration.java
src/main/resources/application.yaml
swatch-core/src/main/java/org/candlepin/subscriptions/task/queue/kafka/KafkaConfigurator.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/kafka/InventoryServiceKafkaConfigurator.java

Will do a parameterized version for `main` after this.

hotfix kafka timeouts to 30 minutes

---

swatch-tally/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-520

SWATCH-520: remove org_id populator job from swatch-tally

---

dependencies.gradle
src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

https://issues.redhat.com/browse/SWATCH-558

SWATCH-558: Update openapi-generator-gradle to 6.2.1 and fix null pointer issue

---

dashboards/grafana-dashboard-subscription-watch-metric-validation.configmap.yaml

https://issues.redhat.com/browse/SWATCH-678
Testing
-------
Install `yq` and then use the following command to get the dashboard JSON:
```
cat dashboards/grafana-dashboard-subscription-watch-metric-validation.configmap.yaml | yq '.data["subscription-watch-metric-validation.json"]' > /tmp/test.json
```
(You can also use `oc extract -f dashboards/grafana-dashboard-subscription-watch-metric-validation.configmap.yaml --confirm` to extract the JSON)
Import the JSON into stage grafana.
Fill out parameters appropriately (see the top panel of the dashboard for details).

Add dashboard for validating metrics

---

swatch-api/deploy/clowdapp.yaml

Related: https://issues.redhat.com/browse/SWATCH-438

Apply REPLICAS to nginx deployment

---

swatch-api/deploy/clowdapp.yaml

Related: https://issues.redhat.com/browse/SWATCH-438

[HOTFIX] SWATCH-438: Apply REPLICAS to nginx deployment

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java

https://issues.redhat.com/browse/SWATCH-589
Execute> `DEV_MODE=true ./gradlew clean :bootRun`
```
INSERT INTO public.hosts (id, inventory_id, account_number, insights_id, org_id, display_name, subscription_manager_id, cores, sockets, is_guest, hypervisor_uuid, hardware_type, num_of_guests, last_seen, is_unmapped_guest, is_hypervisor, cloud_provider, instance_type, instance_id, billing_provider, billing_account_id) VALUES ('8f8037e7-93ba-47a9-8979-3e1dfb4106d3', '71d1aec3-8592-4da2-ab23-fb61593bf90c', 'account123', '2778cc4d-a5e7-4556-a9f4-9dbd1ac3a95c', 'org123', '2778cc4d-a5e7-4556-a9f4-9dbd1ac3a95c', null, null, null, true, null, 'VIRTUALIZED', 7, '1993-03-26 00:00:00.000000 +00:00', true, false, null, 'HBI_HOST', '71d1aec3-8592-4da2-ab23-fb61593bf90c', null, null);
INSERT INTO …
```

SWATCH-589 In instances API allow sorting by guest-count

---

deploy/rhsm-clowdapp.yaml
deploy/stage-post-deployment-tests.yaml
swatch-api/deploy/clowdapp.yaml
swatch-metrics/deploy/clowdapp.yaml
swatch-producer-aws/deploy/clowdapp.yaml
swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml
swatch-subscription-sync/deploy/clowdapp.yaml
swatch-system-conduit/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

Otherwise we face issues with newer `oc` clients.

Change templates apiVersion to template.openshift.io/v1

---

swatch-tally/deploy/clowdapp.yaml

https://consoledot.pages.redhat.com/docs/dev/getting-started/ephemeral/smoke/smoke-intro.html#_clowdapp_settings

Define IQE plugin association with ClowdApp

---

src/main/java/org/candlepin/subscriptions/inventory/db/InventoryDatabaseOperations.java
src/main/java/org/candlepin/subscriptions/tally/HypervisorData.java
src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/facts/FactNormalizer.java
src/test/java/org/candlepin/subscriptions/db/AccountServiceInventoryRepositoryTest.java
src/test/java/org/candlepin/subscriptions/db/HostRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorTest.java
src/test/java/org/candlepin/subscriptions/tally/facts/FactNormalizerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/AccountServiceInventory.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/AccountServiceInventoryId.java

These are quality of life improvements to help make the `InventoryAccountUsageCollector.collect` method easier to read and with more logical separation between the operations.

InventoryAccountUsageCollector quality of life

---

swatch-api/deploy/clowdapp.yaml

In order to support frontend testing in EE

Add apiPath to swatch-api-nginx-proxy

---

deploy/rhsm-clowdapp.yaml

Similar to https://github.com/RedHatInsights/rhsm-subscriptions/pull/1647 
Required for gitlab MR - /insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/347

Define iqe plugin name for rhsm clowdapp

---

src/main/resources/liquibase/202212121039-create-tally-instance-view.xml
src/main/resources/liquibase/changelog.xml

https://issues.redhat.com/browse/SWATCH-587
Creating liquibase to query in stage/prod and ensure performance is acceptable before finishing implementation.

SWATCH-587: add liquibase to create tally_instance_view for use in instance API

---

src/main/java/org/candlepin/subscriptions/umb/ParentProduct.java
src/main/java/org/candlepin/subscriptions/umb/ProductRelationship.java
src/test/java/org/candlepin/subscriptions/umb/OperationalProductMessageTest.java
src/test/resources/mocked-product-message.xml
src/test/resources/mocked-svc-product-message.xml

https://issues.redhat.com/browse/SWATCH-335
Best way to know whether the models are correct is to run the OperationalProductMessageTest class. This class ingests two xml files and parses them to Canonical form.

SWATCH-335 model for OperationalProductMessage with unit test

---

src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
src/main/resources/liquibase/202212011334-add-billing-factor-column-to-remittance-table.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepositoryTest.java
swatch-core/schemas/billable_usage.yaml
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntity.java
swatch-core/src/main/java/org/candlepin/subscriptions/registry/TagMetric.java
swatch-core/src/main/resources/tag_profile.yaml
swatch-producer-aws/src/main/java/com/redhat/swatch/files/TagMetricYaml.java
swatch-producer-aws/src/main/java/com/redhat/swatch/files/TagProfile.java

This change is for phase 1 for https://issues.redhat.com/browse/SWATCH-582
Adding new tag metric for a field for BIllingFactor, which is going to be use to calculate the units that are a multiple of what we collect.

SWATCH-582: Add New TagMetric Field For OSD

---

swatch-subscription-sync/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-717

SWATCH-717 Add MW01484 and MW01485 to the allowlist

---

.rhcicd/grafana/grafana-dashboard-subscription-watch-metric-validation.configmap.yaml
.rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml

https://issues.redhat.com/browse/SWATCH-278

SWATCH-278: move grafana dashboard to .rhcicd folder

---

src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java

See https://issues.redhat.com/browse/SWATCH-745

SWATCH-745: Only require instance API to enforce "same month" rule on PAYG products

---

swatch-subscription-sync/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-732
https://issues.redhat.com/browse/SWATCH-798

SWATCH-798 & SWATCH-732: Add SKUs to allowlist

---

pr_check.sh
swatch-contracts/deploy/clowdapp.yaml

https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/57142

SWATCH-801 Add placeholder file to make MR happy

---

swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java

See https://issues.redhat.com/browse/SWATCH-866

SWATCH-866: Adjust log level on AWS credentials missing exception

---

deploy/stage-internal-test-job.yaml

This job should give us ability to run tests on internal jenkins, this is a still developing process and may need tweaks. 
A sre job will use this template to spin up a tekton job in an internal cluster. Definitions can be found in app repo in sre project on gitlab

Create a job to use internal cluster for testing

---

deploy/stage-internal-test-job.yaml

Job Template is now tested and fixing some nitpicks and update the selenium image used.

fix job template to update the sel image and secrets

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java

See https://issues.redhat.com/browse/SWATCH-867

SWATCH-867: Lower log level of a input validation failure

---

swatch-contracts/src/test/java/com/redhat/swatch/BaseUnitTest.java
swatch-contracts/src/test/java/com/redhat/swatch/ContractMapperTest.java
swatch-contracts/src/test/java/com/redhat/swatch/ContractRepositoryTest.java
swatch-contracts/src/test/java/com/redhat/swatch/ContractsHttpEndpointIntegrationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/QuarkusTransactionalTest.java

Follow up to https://github.com/RedHatInsights/rhsm-subscriptions/pull/1821

SWATCH-803: Updates to unit tests per code review feedback

---

swatch-subscription-sync/deploy/clowdapp.yaml

RHACS is using an additional SKU.

SWATCH-965: [HOTFIX] Add MW02291 to allowlist

---

swatch-subscription-sync/deploy/clowdapp.yaml

SWATCH-957 Adding SKU MW01807F3

---

src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java
src/test/java/org/candlepin/subscriptions/resource/InstancesResourceTest.java

https://issues.redhat.com/browse/SWATCH-912
Test Steps:
```
INSERT INTO public.hosts VALUES ('ba0d9a20-ca1c-4ec6-a22d-78987a228b30', '4a1b9879-7304-4d8c-9376-48f295be780e', '11472998', '11472998', 'org123', 'virtual_xuxwxqyn.example.info', 'a66347b2-854b-4cbf-8d07-14852b8300ad', true, NULL, 'VIRTUALIZED', NULL, '2023-02-27 13:21:11.41413+00', true, false, NULL, 'HBI_HOST', '4a1b9879-7304-4d8c-9376-48f295be780e', NULL, NULL);
INSERT INTO public.host_tally_buckets VALUES ('ba0d9a20-ca1c-4ec6-a22d-78987a228b30', '_ANY', 'RHEL for x86', 'Premium', true, 2, 1, 'VIRTUAL', '_ANY', '_ANY', 0);
INSERT INTO public.host_tally_buckets VALUES ('ba0d9a20-ca1c-4ec6-a22d-78987a228b30', '', 'RHEL for x86', 'Premium', true, 2, 1, 'VIRTUAL', '_ANY', '_ANY', 0);
INSERT INTO …
```

SWATCH-921: Update instances API to return sockets from host_tally_buckets.sockets

---

swatch-core/src/main/resources/tag_profile.yaml

https://issues.redhat.com/browse/SWATCH-941
Test Steps
```
INSERT INTO public.hosts VALUES ('ba0d9a20-ca1c-4ec6-a22d-78987a228b30', '4a1b9879-7304-4d8c-9376-48f295be780e', '11472998', '11472998', 'org123', 'virtual_xuxwxqyn.example.info', 'a66347b2-854b-4cbf-8d07-14852b8300ad', true, NULL, 'VIRTUALIZED', NULL, '2023-02-27 13:21:11.41413+00', true, false, NULL, 'HBI_HOST', '4a1b9879-7304-4d8c-9376-48f295be780e', NULL, NULL);
INSERT INTO public.host_tally_buckets VALUES ('ba0d9a20-ca1c-4ec6-a22d-78987a228b30', '_ANY', 'Satellite', '_ANY', true, 2, 1, 'VIRTUAL', '_ANY', '_ANY', 0);
INSERT INTO public.host_tally_buckets VALUES ('ba0d9a20-ca1c-4ec6-a22d-78987a228b30', '', 'Satellite', '_ANY', true, 2, 1, 'VIRTUAL', '_ANY', '_ANY', 0);
INSERT INTO public.host_tally_buckets …
```

SWATCH-941: add satellite metric tags

---

swatch-contracts/src/main/resources/openapi.yaml
swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointIntegrationTest.java

https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/60736

Update CRUD test apis to use routes consistent with swatch-producer-aws

---

clients/rh-partner-gateway-client/rh-partner-gateway-api-spec.yaml
swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractMetricEntity.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/main/resources/application.properties
swatch-contracts/src/main/resources/openapi.yaml
swatch-contracts/src/test/java/com/redhat/swatch/contract/RhPartnerClientIntegrationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

https://issues.redhat.com/browse/SWATCH-805
1. **Description:**
Currently, we can test using JMS endpoint. This code expects a json contract UMB message. The message doesn't contain all the fields that we need to persist in table. So, we call the Partner Gateway API and Swatch core to fill other information.
**Partner Gateway API:** https://ibm-entitlement-gateway.stage.api.redhat.com/swagger-ui/index.html?configUrl=/api-docs/swagger-config#/All%20Partners/getPartnerEntitlements
**SWATCH Core:** http://localhost:8000/q/swagger-ui/#/default/get_internal_offerings__sku__product_tags
2. **Steps to integrate with APIs for stage before test steps:** 
- `%stage.SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8001/api/rhsm-subscriptions/v1`
- Set `server.port=8001` in …

SWATCH-805_integrate Upstream integration with swatch

---

swatch-core/src/main/resources/tag_profile.yaml

https://issues.redhat.com/browse/SWATCH-948
Test Steps:
```
INSERT INTO public.hosts VALUES ('ba0d9a20-ca1c-4ec6-a22d-78987a228b30', '4a1b9879-7304-4d8c-9376-48f295be780e', '11472998', '11472998', 'org123', 'virtual_xuxwxqyn.example.info', 'a66347b2-854b-4cbf-8d07-14852b8300ad', true, NULL, 'VIRTUALIZED', NULL, '2023-02-27 13:21:11.41413+00', true, false, NULL, 'HBI_HOST', '4a1b9879-7304-4d8c-9376-48f295be780e', NULL, NULL);
INSERT INTO public.hosts VALUES ('a12edde1-111c-40b1-8712-fd677283b191', '13b97249-d466-4f35-8b83-ca9b7bf5dd76', '11472998', '11472998', 'org123', 'virtual_qerqwgil.example.info', '824956dc-223e-49ad-959b-f33fc019b285', true, NULL, 'VIRTUALIZED', NULL, '2023-02-27 13:21:11.41413+00', true, false, NULL, 'HBI_HOST', …
```

SWATCH-948: add OpenShift Container Platform tag metrics

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/exception/BadUpdateContractRequestException.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/exception/ContractMissingException.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/exception/ContractsException.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/exception/ErrorCode.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsExceptionMapper.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/DefaultExceptionMapper.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/main/resources/META-INF/openapi.yaml
swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointIntegrationTest.java

https://issues.redhat.com/browse/SWATCH-1033

SWATCH-1033, SWATCH-951 Implement error responses consistent with the monolith

---

swatch-core/src/main/resources/tag_profile.yaml

Subtasks for configuring product
https://issues.redhat.com/browse/SWATCH-1058
https://issues.redhat.com/browse/SWATCH-1060

SWATCH-1058, SWATCH-1060 Update Tag profile with the metrics for product

---

swatch-core/src/main/resources/tag_profile.yaml

https://issues.redhat.com/browse/SWATCH-1101

SWATCH-1101 - Add billingFactor for rosa core hour config

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractSourcePartnerEnum.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractUMBMockProducer.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/main/resources/META-INF/openapi.yaml
swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointIntegrationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

SWATCH-1102 
**Description:**
Modify mapping from UMB message for awsCustomerId and sourcepartner with cleanups
**Prereq:**
- `%stage.SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8001/api/rhsm-subscriptions/v1`
- Set `server.port=8001` in application.properties or yaml for swatch-core and start the application using ` DEV_MODE=true ./gradlew :bootRun`.
- Create an entry in Offering table with SKU as below:
`
INSERT INTO public.offering (sku, product_name, product_family, cores, sockets, hypervisor_cores, hypervisor_sockets, role, sla, usage, description, has_unlimited_usage, derived_sku) VALUES ('RH00001', 'OpenShift Dedicated', null, 0, 0, 0, 0, 'osd', 'Premium', 'Production', 'Red Hat OpenShift Dedicated on Customer Cloud Subscription (Hourly)', null, null);
`
This is because …

SWATCH-1102 Modify mapping from UMB message 

---

clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContactsApi.java
src/main/java/org/candlepin/subscriptions/tally/billing/ContractsController.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/ContractsControllerTest.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/repository/ContractEntity.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsTestingResource.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/main/resources/META-INF/openapi.yaml
swatch-contracts/src/main/resources/db/202304061624_add_vendorproductcode_to_contracts_table.xml
swatch-contracts/src/main/resources/db/changeLog.xml
swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointIntegrationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/repository/ContractRepositoryTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java
swatch-core/schemas/billable_usage.yaml

This is to address https://issues.redhat.com/browse/SWATCH-1111. The reminder will be address in another PR, as this is need to have for integration test & https://issues.redhat.com/browse/SWATCH-1118
Testing Steps:
DB Setup:
```
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, billing_account_id, product_id, vendor_product_code) VALUES ('469c5d31-8b07-4826-bcf5-cb23419a7b5f', '123456789', '2023-04-07 15:33:58.249887 +00:00', '2023-04-07 15:32:46.568558 +00:00', '2023-04-07 15:33:58.249887 +00:00', '16764785', 'RH00001', 'aws', '568056954830', 'rosa', '6n58d3s3qpvk22dgew2gal7w3');
INSERT INTO public.contracts (uuid, subscription_number, last_updated, start_date, end_date, org_id, sku, billing_provider, …
```

 SWATCH-1111: Add vendorcode to contract table

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/SubscriptionSyncService.java
swatch-contracts/src/main/resources/META-INF/openapi.yaml
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

Hotfix version of https://github.com/RedHatInsights/rhsm-subscriptions/pull/2044

SWATCH-1134: Allow subscriptionsync rest endpoint for service and support roles 

---

swatch-tally/deploy/clowdapp.yaml

TEMPORARY COMMIT FOR DEBUGGING PURPOSES
* Schedule job to run every 5m
* Count characters of PSK and output count when running curl.

Purge snapshot job debugging

---

swatch-tally/deploy/clowdapp.yaml

Reverts RedHatInsights/rhsm-subscriptions#2055

Revert "DEBUG COMMIT: Purge snapshot job debugging"

---

swatch-tally/deploy/clowdapp.yaml

TO BE REMOVED AFTER DEBUGGING SESSION
Schedule job to run every 5m
Include origin header in curl command.

DEBUG COMMIT: Purge snapshot job debugging stage

---

swatch-tally/deploy/clowdapp.yaml

Reverts RedHatInsights/rhsm-subscriptions#2057

Revert "DEBUG COMMIT: Purge snapshot job debugging stage"

---

deploy/stage-internal-test-job.yaml

I am updating screen resolution used by iqe-curiosity-plugin to 1920x1080. Current 1600x900 is not widely used and causes various problems with graph skipping dates for us.
See MR 178 in smqe/swatch-ci repo in CEE GitLab for rationale and details.
CC @san7ket

Update Selenium resolution to 1920x1080

---

src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java

https://issues.redhat.com/browse/SWATCH-943

SWATCH-943: change delete stale host logging to info

---

.github/dependabot.yml
swatch-system-conduit/Dockerfile

And explicitly version the base image

Add dependabot config for swatch-system-conduit

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java

Jira issue: [SWATCH-1206](https://issues.redhat.com/browse/SWATCH-1206)
Snapshots store usage values in measured units. Contract values coming from the contract service are in billing units.
When calculating remittance, the contracted value must be converted into measured units so that it can be deducted from the measured usage coming from the snapshots. This defines the applicable measured usage that should be used when determining remittance and billed for when required.
applicable_usage = snapshot_total - (contract / billing_factor)
For example, given a contract with 1 4vCPU capacity (billing factor of 0.25), and a tally measurement of 4 vCPUs, the contract should cover the entire tally measurement (assuming it's the first measurement covered by the contract).
applicable_usage = 4 - (1 …

Adjust contract units to measured units before calculating remittance

---

deploy_ephemeral_env.sh
pr_check.sh

Force sidecars to be enabled in pr check

Force sidecars to be enabled in pr check

---

clients/rh-partner-gateway-client/rh-partner-gateway-api-spec.yaml
swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/RhPartnerClientIntegrationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/WireMockResource.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

Jira issue: [SWATCH-1257](https://issues.redhat.com/browse/SWATCH-1257)
Instead of ingesting the dimensions from UMB message we will use Partner API to populate dimensions into metrics. We will get persist those contracts that doesn't have an endDate since those will be active contracts. The old contracts with no endDates are tests so we can ignore it. Also if the dimensions are empty we will not do anything.
- `%stage.SWATCH_INTERNAL_SUBSCRIPTION_ENDPOINT=http://localhost:8001/api/rhsm-subscriptions/v1`
- Set `server.port=8001` in application.properties or yaml for swatch-core and start the application using ` DEV_MODE=true ./gradlew :bootRun`.
- Set env variable for contract app: ENABLE_SPLUNK_HEC=false; KEYSTORE_PASSWORD=<Password>; …

SWATCH-1257 Ingest contract dimensions from Partner API

---

swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml

Jira issue: [SWATCH-1269](https://issues.redhat.com/browse/SWATCH-1269)
Missing env var for clowdapp

Swatch-1269: red hat marketplace producer incorrect product_url

---

swatch-subscription-sync/deploy/clowdapp.yaml

Jira issue: [SWATCH-1284](https://issues.redhat.com/browse/SWATCH-1284)
Doesn't resolve the underlying issue, but will cut down on noise in the logs for the time being

SWATCH-1284: Add problematic skus to denylist

---

swatch-subscription-sync/deploy/clowdapp.yaml

https://issues.redhat.com/browse/SWATCH-1300

SWATCH-1300 - Add RH01157 to deny list & resort the list order

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/inventory/kafka/KafkaEnabledInventoryServiceTest.java

Jira issue: [SWATCH-1243](https://issues.redhat.com/browse/SWATCH-1243)
Error was caused due to `"` empty being placed as a value for Os version and the current logic would produce a Operating system with a name, but null major & minor versions. So we will just return the OS has null. 
1. Run Rhsm-conduit with these environment viables:
```
DEV_MODE=true;RHSM_USE_STUB=true
```
2. Go to `StubRhsmApi` and make the `distribution.version` =`""`.
3. Run `syncOrg(String)` in Hawtio for conduit, the input string can be anything as we will be leveraging the mock values here.
```
http://localhost:9000/hawtio/jmx/operations?nid=root-org.candlepin.subscriptions.conduit.jmx-RhsmConduitJmxBean-rhsmConduitJmxBean
```
Make sure Kafka pods are running and use either Big Data tools in the IDE or Kafka UI: …

SWATCH-1243: Fixing Missing Release version for Operating System

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java

Jira issue: [SWATCH-1331](https://issues.redhat.com/browse/SWATCH-1331)
Exception occurs when org has an updated subscription with 2 records both sharing a subscriptionId. This fixes the syncOrg method to prevent error from occurring by mapping the subscriptions by their primary key (subscriptionID, startDate) instead of just subscriptionID.
1. Insert some mock subscription and subscription_capacity records:
```shell
insert into subscription(sku, org_id, subscription_id, quantity, start_date, end_date)
values ('extra', '123', 'sub123', 1, now(), now()),
('MW01882', '123', '235252', 1, '2011-01-01T01:02:33Z', now()),
('MW01882', '123', '235252', 1, now(), now()),
('MW01485', '123', '235251', 1, now(), now());
EOF
```
2. …

SWATCH-1331: Handle duplicate subscriptionId in syncOrg process

---

deploy/stage-internal-test-job.yaml
pr_check.sh

Jira issue: [SWATCH-756](https://issues.redhat.com/browse/SWATCH-756)
- Uploads results to report portal
- Added ibutsu source to filter results specific to pipeline

SWATCH-756 - Enable ibutsu and reportportal option

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java
src/test/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepositoryTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/RemittanceControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/billing/admin/InternalBillingControllerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntity.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/BillableUsageRemittanceEntityPK.java

Jira issue: [SWATCH-1165](https://issues.redhat.com/browse/SWATCH-1165)
Insert test events:
```
INSERT INTO public.events VALUES ('c77461ca-1949-47cd-b408-da48f6542c30', 'account123', '2023-03-14 23:00:00+00', '{"sla": "Premium", "role": "moa-hostedcontrolplane", "org_id": "org123", "event_id": "c77461ca-1949-47cd-b408-da48f6542c30", "timestamp": "2023-03-14T23:00:00Z", "event_type": "snapshot_redhat.com:rosa:cpu_hour", "expiration": "2023-03-15T00:00:00Z", "instance_id": "test02", "display_name": "test02", "event_source": "prometheus", "measurements": [{"uom": "Cores", "value": 66.3149034729778}], "service_type": "rosa Instance", "account_number": "account123", "billing_provider": "aws", "billing_account_id": "mktp-123"}', 'snapshot_redhat.com:rosa:cpu_hour', 'prometheus', 'test02', …
```

SWATCH-1165: Create daily remittance roll up records

---

api/rhsm-subscriptions-api-spec.yaml
clients/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContactsApi.java
src/main/java/org/candlepin/subscriptions/resource/ReportCriteria.java
src/main/java/org/candlepin/subscriptions/resource/TallyResource.java
src/test/java/org/candlepin/subscriptions/resource/TallyResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/resource/ResourceUtils.java

Jira issue: [SWATCH-929](https://issues.redhat.com/browse/SWATCH-929)
Add billing_category param to tally api. Billing_category has values Prepaid and On_demand. If prepaid we will set the data point value to the snapshot value - remittance and if it is On_Demand the value will be the remittance alone.
1. Insert Test Events:
```
INSERT INTO public.events VALUES ('c77461ca-1949-47cd-b408-da48f6542c30', 'account123', '2023-03-14 23:00:00+00', '{"sla": "Premium", "role": "BASILISK", "org_id": "org123", "event_id": "c77461ca-1949-47cd-b408-da48f6542c30", "timestamp": "2023-03-14T23:00:00Z", "event_type": "snapshot_redhat.com:BASILISK:transfer_gb", "expiration": "2023-03-15T00:00:00Z", "instance_id": "test02", "display_name": "test02", "event_source": "prometheus", "measurements": [{"uom": …
```

swatch-929: update tally api with billing category

---

api/rhsm-subscriptions-api-spec.yaml
src/main/java/org/candlepin/subscriptions/resource/InstancesResource.java

Jira issue: [SWATCH-1043](https://issues.redhat.com/browse/SWATCH-1043)
This card just covers spec changes for the new api for guests by instance id. There no test steps other than making sure the spec looks correct.

SWATCH-1043 New api spec for guests by instance id

---

src/main/java/org/candlepin/subscriptions/tally/InventorySwatchDataCollator.java

Jira issue: [SWATCH-1362](https://issues.redhat.com/browse/SWATCH-1362)
Description
===========
PR #2152 revealed a bug in the sorting of records during collation. The result is the HBI stream and the swatch stream get out of sync, which results in attempts to create redundant records (and attempts to delete the existing record). This surfaced as a unique constraint violation, because the redundant insert now fails.
Collation was relying solely on the inventory ID to decide which stream should be advanced, so when one system had systems that other did not (e.g. HBI having an extra system), and that extra system having a lexicographically larger inventory ID, the wrong stream could be advanced.
Fixing this involved making sure the collator uses a key equivalent to what the database queries …

SWATCH-1362: Use SortKey for collating HBI and swatch systems

---

swatch-tally/deploy/clowdapp.yaml

Applying #2271 to the hotfix branch

query change for pulling data of 2 days

---

src/main/java/org/candlepin/subscriptions/retention/RemittanceRetentionController.java
src/main/java/org/candlepin/subscriptions/retention/RemittanceRetentionPolicy.java
src/main/java/org/candlepin/subscriptions/retention/RemittanceRetentionPolicyProperties.java
src/main/java/org/candlepin/subscriptions/tally/TallyWorkerConfiguration.java
src/main/java/org/candlepin/subscriptions/tally/admin/InternalTallyResource.java
src/main/resources/application-worker.yaml
src/main/spec/internal-tally-api-spec.yaml
src/test/java/org/candlepin/subscriptions/retention/RemittanceRetentionControllerTest.java
src/test/java/org/candlepin/subscriptions/retention/RemittanceRetentionPolicyTest.java
src/test/java/org/candlepin/subscriptions/tally/admin/InternalTallyResourceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/BillableUsageRemittanceRepository.java
swatch-tally/deploy/clowdapp.yaml

This PR is dependent on https://github.com/RedHatInsights/rhsm-subscriptions/pull/2181 merging first.
Jira issue: [SWATCH-1114](https://issues.redhat.com/browse/SWATCH-1114)
New internal api and cron job to delete remittances older configurable retention policy.
1. Deploy app in EE:
```
NAMESPACE=$(bonfire namespace reserve -d 12h)
bonfire deploy rhsm --no-remove-resources swatch-contracts --no-remove-resources swatch-api --no-remove-resources swatch-producer-aws --no-remove-resources swatch-producer-red-hat-marketplace --no-remove-resources swatch-metrics --no-remove-resources swatch-subscription-sync --no-remove-resources swatch-system-conduit --no-remove-resources swatch-tally
```
2. Insert test data:
```
oc exec $(oc -n $NAMESPACE get -o name pod | grep swatch-tally-db | sed -e …
```

SWATCH-1114: internal delete remittance api

---

CONTRIBUTING.md
build.gradle
buildSrc/src/main/groovy/swatch.liquibase-conventions.gradle
dependencies.gradle
gradle.properties
swatch-contracts/build.gradle
swatch-contracts/src/main/java/com/redhat/swatch/contract/config/Main.java

See CONTRIBUTING.md for details

Add liquibase gradle plugin for dev productivity

---

swatch-tally/deploy/clowdapp.yaml

query change for floorist swatch-tally

---

swatch-contracts/deploy/clowdapp.yaml
swatch-metrics/deploy/clowdapp.yaml
swatch-producer-aws/deploy/clowdapp.yaml
swatch-subscription-sync/deploy/clowdapp.yaml
swatch-system-conduit/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

Decoded value update to "placeholder" instead of "dummy"

Updating expected value of x-rh-swatch-psk

---

swatch-core/schemas/event.yaml

Change event_type schema description

---

swatch-core/src/main/java/org/candlepin/subscriptions/db/SubscriptionRepository.java

[HHH-17040](https://hibernate.atlassian.net/browse/HHH-17040) is a Hibernate issue that can cause a single root entity to be returned in duplicate depending on the row order of the result set.  We can side-step the issue by adding an "order by" clause based on the composite primary key we use for Subscription.  That "order by" will ensure all rows of the same Subscription are grouped together.
Jira issue: [SWATCH-1557](https://issues.redhat.com/browse/SWATCH-1557)
This is actually a follow on PR based on some additional research and investigation.  We augmented the `Collectors.toMap` call in `SubscriptionSyncController` to handle multiple copies of the same `Subscription` being returned.  However, as I was looking into this bug, I noticed that when we run into the issues with duplicate …

SWATCH-1557: Add order by clauses on SubscriptionRepository to avoid Hibernate issue

---

.tekton/rhsm-subscriptions-pull-request.yaml
.tekton/rhsm-subscriptions-push.yaml

Needed to perform the gradle build step prior to doing a container build.

Add gradle build to RHTAP pipelines

---

src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollectorReconcileTest.java

Jira issue: [SWATCH-1561](https://issues.redhat.com/browse/SWATCH-1561)
**Code flow:**
- Send nightly tally request for an orgId
- Kafka with groupid: `platform.rhsm-subscriptions.tasks` will retrieve it for further processing. There is a retry template if it fails
- First it pulls stream of records from HBI Host table using orgid and days. We don't pull all the records at the same time by implementing FETCH_SIZE=1024. The entity manager will load all the same host_ids along with other records so total records can be >1024 but total of only host_ids will be loaded. To debug the `HINT_FETCH_SIZE` its good to put debug point in PgStatement. For more details check in Extra notes at the end.
- Second we pull all the subscription_manager_id also called activeSubmanIdStream in code using orgid …

SWATCH-1561 Fix ObjectOptimisticLockingFailureException in nightly tally

---

src/main/java/org/candlepin/subscriptions/event/EventController.java
src/test/java/org/candlepin/subscriptions/db/EventRecordRepositoryTest.java
swatch-core/schemas/event.yaml

Jira issue: [SWATCH-1608](https://issues.redhat.com/browse/SWATCH-XXXX)
No test step required

SWATCH-1608 change the event_type schema to required

---

Jenkinsfile

In order to get to the feedback faster :-)

Change sonar results link to PR summary

---

src/main/java/org/candlepin/subscriptions/metering/job/MeteringJob.java
src/main/java/org/candlepin/subscriptions/metering/profile/MeteringJobProfile.java
src/test/java/org/candlepin/subscriptions/metering/job/MeteringJobTest.java
swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/SubscriptionDefinition.java

Jira issue: [SWATCH-1646](https://issues.redhat.com/browse/SWATCH-1646)
Unit & Regression Testing

SWATCH-1646: Remove TagProfile from Metering Job

---

src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusAccountSource.java
src/main/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusService.java
src/main/resources/application-metering-job.yaml
src/test/java/org/candlepin/subscriptions/metering/service/prometheus/PrometheusServiceTest.java
src/test/resources/__files/prometheus_empty_result.json

Also reduce maxAttempts on Prometheus queries to 3 to make this type of error easier to debug.

[HOTFIX] Fix exception when parsing empty results from Prometheus

---

src/main/java/org/candlepin/subscriptions/resource/SubscriptionTableController.java
src/main/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapper.java
src/test/java/org/candlepin/subscriptions/rhmarketplace/RhMarketplacePayloadMapperTest.java

Jira issue: [SWATCH-1236](https://issues.redhat.com/browse/SWATCH-1236)
Unit tests & Regression

SWATCH-1236: Refactor RHM integration to use swatch-product-configuration

---

swatch-subscription-sync/deploy/clowdapp.yaml

Jira issue: [SWATCH-1625](https://issues.redhat.com/browse/SWATCH-1625)
Jira issue: [SWATCH-1641](https://issues.redhat.com/browse/SWATCH-1641)

SWATCH-1625 & SWATCH-1641: Add MW00700 and SER0419 to denylist

---

src/main/java/org/candlepin/subscriptions/tally/InventoryAccountUsageCollector.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/main/resources/liquibase/202309181629-fix-measurement-metric-id-formatting.xml
src/main/resources/liquibase/changelog.xml
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionTableControllerTest.java
src/test/java/org/candlepin/subscriptions/tally/SnapshotSummaryProducerTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/TallyInstanceViewRepository.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/Host.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/InstanceMonthlyTotalKey.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/model/TallyMeasurementKey.java
swatch-core/src/main/java/org/candlepin/subscriptions/util/MetricIdUtils.java
swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/MetricId.java
swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/MetricIdTest.java

Jira issue: [SWATCH-1744](https://issues.redhat.com/browse/SWATCH-1744)
1.
1.
1.
1.
1.
1.

SWATCH-1744: Fix format of metricId on tally_measurements and instance_measurements

---

src/main/resources/liquibase/changelog.xml

comment out liquibase that fails

---

dependencies.gradle

#2540 
#2551 
#2550 
#2549 
#2548

Consolidate dependabot PRs

---

swatch-producer-aws/src/main/java/com/redhat/swatch/processors/BillableUsageProcessor.java
swatch-producer-aws/src/test/java/com/redhat/swatch/com/redhat/swatch/processors/BillableUsageProcessorTest.java
swatch-product-configuration/src/main/java/com/redhat/swatch/configuration/registry/MetricId.java

Fix comparison of uppercased uom in swatch-producer-aws

---

CONTRIBUTING.md
README.md

Update the CONTRIBUTING.md guide to explain how to build the repository and requirements.
Moreover, I included some sections for formatting and code style.

Provide instructions about how to build the repository

---

src/main/java/org/candlepin/subscriptions/event/EventController.java
src/main/java/org/candlepin/subscriptions/tally/MetricUsageCollector.java
src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/db/EventRecordRepository.java

Check end date based on timestamp and stop by record date
1.
1.
1.
1.
1.
1.

Avoid retally by fetching correct events

---

src/test/java/org/candlepin/subscriptions/security/IdentityHeaderAuthenticationDetailsServiceTest.java
swatch-core/src/main/java/org/candlepin/subscriptions/security/RoleProvider.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/ResteasyRequestObservationConvention.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/resteasy/ResteasyUriExtractionFilter.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/resteasy/HttpServerMetricsTest.java

Jira issue: [SWATCH-1651](https://issues.redhat.com/browse/SWATCH-1651)
The same changes as https://github.com/RedHatInsights/rhsm-subscriptions/pull/2489 but applied to the conduit service.

SWATCH-1651 (for conduit service): Populate uri label in Spring Boot 3

---

swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_eus_payg.yaml

Jira issue: [SWATCH-1776](https://issues.redhat.com/browse/SWATCH-1776)
This is a change in product name since we now have a SKU RH02780HR 
The E2E test steps are still blocked because we haven't got a subscription and contract from Partner API team on stage.

SWATCH-1776 Add product name based on SKU

---

swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_eus_payg.yaml

Jira issue: [SWATCH-1776](https://issues.redhat.com/browse/SWATCH-1776)
1.
1.
1.
1.
1.
1.

SWATCH-1776 disable RHEL metering product to check for saas contract

---

src/main/java/org/candlepin/subscriptions/event/EventController.java

Service instance ingress events logging

---

src/test/java/org/candlepin/subscriptions/tally/MetricUsageCollectorTest.java
swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg.yaml

Jira issue: [SWATCH-1851](https://issues.redhat.com/browse/SWATCH-1851)
Jira issue: [SWATCH-1839](https://issues.redhat.com/browse/SWATCH-1839)
1.
1.
1.
1.
1.
1.

SWATCH-1851 Add swatch-product-configuration for RHEL ELS

---

.github/workflows/validate-floorplan-queries.yaml

Jira issue: [SWATCH-1884](https://issues.redhat.com/browse/SWATCH-1884)
The idea is to ensure that the queries declared in the floorplan are checked to avoid issues like [SWATCH-1882](https://issues.redhat.com/browse/SWATCH-1882).
We use yaml-path which is a command line tool powered by Jbang. Yaml-path allows to extract elements from YAML resources. Here, we're extracting the queries and then executing them individually against a Postgresql database to confirm that it's working fine.

SWATCH-1884: Validate the floorish queries per pull request

---

.tekton/rhsm-subscriptions-pull-request.yaml
.tekton/rhsm-subscriptions-push.yaml
.tekton/swatch-system-conduit-pull-request.yaml
.tekton/swatch-system-conduit-push.yaml

This reverts commit a51bae8a632b02d17e821a87f1c8bafe66dd58da.
Move back to CEL so that we can define criteria for when each component's pipeline should run.
Look for successful pipeline runs.

Change tekton triggers to use cel

---

swatch-subscription-sync/deploy/clowdapp.yaml

Adding per email thread with PM regarding ROSA testing.

Add new SKUs to deny list

---

.github/pull_request_template.md

See
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls and https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources

Simplify PR template by taking advantage of autolinking

---

Jenkinsfile

Will self-merge assuming tests pass, as this is just a bump of kubedock image.

Update kubedock to f8452a8

---

swatch-contracts/src/main/docker/Dockerfile.jvm
swatch-metrics/src/main/docker/Dockerfile.jvm
swatch-producer-aws/src/main/docker/Dockerfile.jvm
swatch-producer-azure/src/main/docker/Dockerfile.jvm

Otherwise, other java options are overwritten, see https://access.redhat.com/solutions/7041059

Use JAVA_OPTS_APPEND in quarkus Dockerfiles

---

buildSrc/src/main/groovy/swatch.quarkus-rest-client-conventions.gradle
swatch-contracts/build.gradle
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractUMBMessageConsumer.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/security/Identity.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/security/RhIdentityHeaderAuthenticationMechanism.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/security/RhIdentityPrincipal.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/security/RhIdentityPrincipalFactory.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/security/RbacRolesAugmentorTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/security/RhIdentityDeserializationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/security/RhIdentityHeaderAuthenticationMechanismTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/security/RolesAugmentorTest.java
swatch-metrics/build.gradle
swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/json/MetricsTaskDescriptorDeserializer.java
swatch-producer-aws/build.gradle
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/kafka/BillableUsageDeserializer.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/kafka/BillableUsageSerializer.java
swatch-producer-aws/src/test/java/com/redhat/swatch/aws/test/wiremock/WiremockRunner.java
swatch-producer-azure/build.gradle
swatch-producer-azure/src/main/java/com/redhat/swatch/azure/kafka/BillableUsageDeserializer.java
swatch-producer-azure/src/main/java/com/redhat/swatch/azure/kafka/BillableUsageSerializer.java

Jira issue: SWATCH-1945
Removes JSON-B and uses Jackson everywhere instead.

SWATCH-1945: Remove JSON-B and replace with Jackson

---

dependencies.gradle

SWATCH-1977: Bump spring-boot dependency to 3.1.6

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractMapper.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/main/resources/META-INF/openapi.yaml
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

UMB message for contracts contains azureOfferId instead of just offerId

Update azure contract offerId to azureOfferId to match Partner gateway

---

swatch-tally/deploy/clowdapp.yaml

Will self-merge once it passes.

Add distinct keyword to floorist subscriptions query

---

swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

Jira issue: SWATCH-1983
This PR will merge after QE approval to add the test coverage. Since the PR Merged
[SWATCH-2083: Update contract ingestion to require less data](https://github.com/RedHatInsights/rhsm-subscriptions/pull/2994#top) is already taking care of many issues the contract and subscription was getting saved. Hence there is no code change required but, QE can test the steps to close the ticket.
This problem arises when we follow a specific order of action. This occurs when we initially receive a contract for a specific date. When the UMB subscription message arrives and syncs the subscription, that is the second step. The final phase is receiving an updated contract with a new start date. I'll enumerate the output that I recorded both before and after the correction. When you …

SWATCH-1983 Contract upgrades do not perform capacity reconciliation

---

src/main/java/org/candlepin/subscriptions/subscription/SubscriptionSyncController.java
src/test/java/org/candlepin/subscriptions/subscription/SubscriptionSyncControllerTest.java

Cherry-pick of https://github.com/RedHatInsights/rhsm-subscriptions/pull/3044

Cherry Pick: SWATCH-2203: Get product tags by product name when no role or eng ids

---

swatch-producer-aws/src/test/java/com/redhat/swatch/aws/processors/AwsUsageContextLookupApiTest.java

Fix flaky test due to date formatting

---

swatch-metrics/src/main/java/com/redhat/swatch/metrics/configuration/MetricProperties.java
swatch-metrics/src/main/java/com/redhat/swatch/metrics/service/PrometheusMeteringController.java
swatch-metrics/src/main/resources/application.yaml

In order to stabilize swatch-metrics

Hotfix SWATCH-2066

---

swatch-contracts/src/main/resources/db/202402161401_fix_contract_product_for_rosa.xml
swatch-contracts/src/main/resources/db/changeLog.xml

SWATCH-2219 Fix product id in contracts for rosa sku

---

swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml

SWATCH-2104: Change metric for ROSA HCP

---

swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml

This reverts commit 58cc1cb28123bce2a40cb04dfdb45f5bb0c851b9.

Revert "SWATCH-2104: Change metric for ROSA HCP"

---

swatch-product-configuration/src/main/resources/subscription_configs/OpenShift/rosa.yaml

This reverts commit 8df152e00df915290b5b58977af6779e24fbc73f.

Reapply "SWATCH-2104: Change metric for ROSA HCP"

---

CONTRIBUTING.md

Document PR labels

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/rhsm/RhsmService.java

Jira issue: [SWATCH-2214](https://issues.redhat.com/browse/SWATCH-2214)
As per the documentation: "Should only be used when a permission was acquired but not used. Otherwise use {@link Bulkhead#onComplete()} to signal a completed call and release a permission.".
Moreover, replacing the "tryAcquirePermission" to "acquirePermission" because it handles better the thread interrumption.

SWATCH-2214: Replace bulkhead.releasePermission by onComplete

---

.unleash/flags.json
docker-compose.yml
init_dbs.sh
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

Jira issue: SWATCH-2346
Added check of dmi.bios.vendor in addtion to dmi.bios.version to determine if the host is aws. Some fact sets now have the needed information in this other fact.
Covered by a unit test
1. A unit test run
2. Use a consumer that has the alternative field and confirm that its cloud provider value is 'aws'

SWATCH-2346: Also check dmi.bios.vendor for aws host detection

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/AzureContractLifecycleIntegrationTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/model/ContractEntityMapperTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/ContractServiceTest.java

Jira issue: SWATCH-2364
For testing purposes we need to save the azureCustomerId which will be used to clean up test accounts.
Covered in Integration test.

SWATCH-2364: Append azureCustomerId to the end of billingProviderId

---

src/main/java/org/candlepin/subscriptions/tally/billing/BillableUsageController.java

IQE Test MR: 
1.
1.
1.
1.
1.
1.

[HOTFIX] SWATCH-2494: Add all status of billable usage remittance together

---

src/test/java/org/candlepin/subscriptions/tally/billing/BillableUsageControllerTest.java

Unit test to insure getTotalRemitted considers all statuses

---

docker-compose.yml
docs/unleash.md

Jira issue: SWATCH-2475
I changed the default client token and forgot to update it in the insights containers.
None.

Correct Unleash client token in docker-compose.yml

---

clients/rhsm-client/src/main/java/org/candlepin/subscriptions/conduit/rhsm/client/StubRhsmApi.java
swatch-system-conduit/schemas/inventory/hbi-system-profile-conversions.yaml
swatch-system-conduit/schemas/inventory/hbi-system-profile.yaml
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/ConduitFacts.java
swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/inventory/InventoryService.java
swatch-system-conduit/src/main/spec/internal-organizations-sync-api-spec.yaml
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

Jira issue: [SWATCH-2361](https://issues.redhat.com/browse/SWATCH-2361)
- forward the conversions.activity fact
2.- start conduit service:
```
RHSM_USE_STUB=true DEV_MODE=true ./gradlew :swatch-system-conduit:bootRun
```
3.- sync the org ID:
```
http :8000/api/rhsm-subscriptions/v1/internal/rpc/syncOrg   x-rh-swatch-psk:placeholder   org_id=org123
```
4.- check the new message that is sent into the Kafka topic "platform.inventory.host-ingress":
```
{
"org_id": "org123",
"subscription_manager_id": "f665078c-bc8c-473d-b3c6-b4e315f2bd9e",
"bios_uuid": "89462a07-32f8-4d75-a70c-77c2bd85a496",
"ip_addresses": [
"192.167.11.2",
"192.168.1.1",
"192.168.122.1",
"10.0.0.1"
],
"fqdn": "host1.test.com",
"facts": [
{
"namespace": "rhsm",
"facts": {
"SYNC_TIMESTAMP": …
```

SWATCH-2361: rhsm-conduit should forward the conversions.activity to HBI

---

swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_EUS.yaml

Jira issue: SWATCH-2514
- Added engineering product to subscription_configs

SWATCH-2514: SAP variant showing incorrect usage graph

---

.rhcicd/grafana/grafana-dashboard-subscription-watch.configmap.yaml

Update grafana dashboard config from latest stage export

Update grafana dashboard to latest in stage

---

config/application-kafka-bridge.properties
docker-compose.yml

`podman-compose up -d`
Usage example:
```bash
curl -X POST \
http://localhost:9080/topics/platform.rhsm-subscriptions.service-instance-ingress \
-H 'Content-Type: application/vnd.kafka.json.v2+json' \
-H 'Accept: application/vnd.kafka.v2+json' \
-d '{
"records": [
{
"key": "12345678",
"value": {
"service_type": "RHEL System",
"timestamp": "2024-06-03T14:00:00Z",
"expiration": "2024-07-03T15:00:00Z",
"display_name": "aws1.host-metering.test",
"measurements": [
{
"value": 1,
"uom": "vCPUs",
"metric_id": "vCPUs"
}
],
"product_ids": [
"204",
"69"
],
"sla": "Premium",
"usage": "Production",
"billing_provider": "aws",
"billing_account_id": "customerAccount12345678",
"product_tag": [
"rhel-for-x86-els-payg"
],
"conversion": true,
"event_source": "rhelemeter",
"event_type": …
```

Add strimzi kafka bridge to compose file

---

src/main/resources/liquibase/202406130700-add-index-in-sku-product-tag.xml
src/main/resources/liquibase/changelog.xml

Jira issue: SWATCH-2649
The execution time will definitely increase by adding index to sku_product_tag table plus it was needed anyways.

SWATCH-2649 Add sku_product_tag index for performance

---

swatch-producer-aws/src/main/java/com/redhat/swatch/aws/configuration/ProfileFileConfiguration.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/file/AwsCredentialsLookup.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/resource/BillableUsageResource.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsMarketplaceMeteringClientFactory.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/BillableUsageProducer.java
swatch-producer-aws/src/test/java/com/redhat/swatch/aws/file/AwsCredentialsLookupTest.java
swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsUsageContextLookupApiTest.java
swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java

Superficial changes for maintainability purposes.

Updates to closer align the swatch_producer_aws structure with swatch_producer_azure

---

swatch-product-configuration/src/main/resources/subscription_configs/RHEL/RHEL_for_x86_els_payg_addon.yaml
swatch-product-configuration/src/test/java/com/redhat/swatch/configuration/registry/SubscriptionDefinitionRegistryTest.java

AWS listing in prod still hadn't been corrected.  In the event we continue to have issues getting that updated, we can change the configuration on our side.

[HOTFIX] Update to make awsDimension for RHEL for x86 ELS On-Demand

---

swatch-metrics/src/main/java/com/redhat/swatch/metrics/util/MeteringEventFactory.java

…ages (#3454)"
This reverts commit dd1030d8234a574ec1e127ef6b10fffe2b28d77f, reversing changes made to 8392739c0f1e21d102b0991927fb2b14071b3eef.
Jira issue: SWATCH-2752
IQE Test MR: 
1.
1.
1.
1.
1.
1.

SWATCH-2752: Revert "SWATCH-2671 Set CloudProvider and hardware type on Event messages (#3454)

---

swatch-contracts/build.gradle
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/CapacityReconciliationService.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/CapacityReconciliationIntegrationTest.java

https://issues.redhat.com/browse/SWATCH-2744
See inline comments for more details.
Testing
-------
See `CapacityReconciliationIntegrationTest`. To reproduce the issue, revert the fix and run the test.

SWATCH-2744: Fix capacity reconciliation when another task is queued

---

swatch-contracts/src/main/resources/application.properties

Bump swatch-contracts tx timeout to 5 minutes

---

src/main/java/org/candlepin/subscriptions/capacity/admin/InternalSubscriptionResource.java
src/main/java/org/candlepin/subscriptions/product/OfferingSyncController.java
src/test/java/org/candlepin/subscriptions/product/OfferingSyncControllerTest.java

Jira issue: SWATCH-2676
The /internal/rpc/offerings/sync/{sku} always returns code 200 regardless of the outcome.
In scenarios where that is not the correct response the code will be what is expected
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/809
1. The unit tests have been updated for the new response. They should run correctly.
2. An IQE test is added as noted above.
1. Tests pass

SWATCH-2676: Return status code 404 for non-existing sku when syncing

---

build_deploy.sh

Jira issue: [RHCLOUD-34383](https://issues.redhat.com/browse/RHCLOUD-34383)
some refactor to build_deploy: 
- set ephemeral docker config file
- remove deprecated --config parameter
- add cleanup function for credentials wipe on EXIT
- reduce the number of commands needed to build the image
- shellcheck fixes
IQE Test MR: 
1.
1.
1.
1.
1.
1.

RHCLOUD-34383: refactor: update build_deploy.sh

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/config/DebugClientLogger.java

Log absolute URI in DebugClientLogger

SWATCH-2805: log absolute URI in DebugClientLogger

---

swatch-contracts/deploy/clowdapp.yaml
swatch-contracts/src/main/resources/application.properties

Cherrypick of https://github.com/RedHatInsights/rhsm-subscriptions/commit/08c415e2fc4d4bcf4e5b25f9c9e0f0f681d4d6b3

[HOTFIX] SWATCH-2816: Configure the PRODUCT_URL for prod in swatch contracts

---

swatch-product-configuration/src/main/resources/subscription_configs/RHEL/rhel_for_sap_x86.yaml

Jira issue: SWATCH-2823
We do not need counts for the EUS engineering Id

SWATCH-2823: Update SAP product config to remove EUS

---

clients/quarkus/contracts-client/src/main/java/com/redhat/swatch/contracts/client/StubContractsApi.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/ContractsResource.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java
swatch-contracts/src/main/resources/META-INF/openapi.yaml

Jira issue: SWATCH-2855
Need to work around an issue where existing data prevents contracts from syncing.
Planning to self-merge and deploy to hotfix for troubleshooting purposes

SWATCH-2855: Add delete_contracts_and_subs param to sync contracts endpoint

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java

IQE Test MR: 
1.
1.
1.
1.
1.
1.

Fix NPE in previous hotfix

---

.tekton/rhsm-pull-request.yaml
.tekton/rhsm-push.yaml
.tekton/swatch-api-pull-request.yaml
.tekton/swatch-api-push.yaml
.tekton/swatch-contracts-pull-request.yaml
.tekton/swatch-contracts-push.yaml
.tekton/swatch-metrics-pull-request.yaml
.tekton/swatch-metrics-push.yaml
.tekton/swatch-producer-aws-pull-request.yaml
.tekton/swatch-producer-aws-push.yaml
.tekton/swatch-producer-azure-pull-request.yaml
.tekton/swatch-producer-azure-push.yaml
.tekton/swatch-producer-red-hat-marketplace-pull-request.yaml
.tekton/swatch-producer-red-hat-marketplace-push.yaml
.tekton/swatch-subscription-sync-pull-request.yaml
.tekton/swatch-subscription-sync-push.yaml
.tekton/swatch-system-conduit-pull-request.yaml
.tekton/swatch-system-conduit-push.yaml
.tekton/swatch-tally-pull-request.yaml
.tekton/swatch-tally-push.yaml

Per request from the konflux team, we shoudl remove the sbom-json-check task from all of our pipelines

Remove the sbom-json-check task per ask from the konflux team

---

dependencies.gradle

Jira issue: SWATCH-2811
Update to keep current with the plugin
A successful CI run will signify success

SWATCH-2811: Bump liquibase-gradle-plugin from 2.2.2 to 3.0.0

---

swatch-billable-usage/src/main/resources/application.properties
swatch-contracts/src/main/resources/application.properties

Jira issue: SWATCH-2907
See #3741

[HOTFIX] SWATCH-2907: Disable fault tolerance metrics for now

---

swatch-billable-usage/build.gradle
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResource.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceFilter.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/model/RemittanceMapper.java
swatch-billable-usage/src/main/resources/META-INF/openapi.yaml
swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java

Jira issue: SWATCH-2897
IQE Test MR: 
https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/861
1.` INSERT INTO public.billable_usage_remittance (account_number, org_id, product_id, metric_id, accumulation_period, sla, usage, billing_provider, billing_account_id, remitted_pending_value, remittance_pending_date, retry_after, tally_id, hardware_measurement_type, uuid, billed_on, error_code, status) VALUES (null, '17795559', 'ansible-aap-managed', 'Managed-nodes', '2024-09', 'Premium', 'Production', 'aws', 'aws123', 2, '2024-09-16 16:25:56.198009 +00:00', null, '140a676c-86b0-4883-9b33-e6ac44dbef92', 'PHYSICAL', 'bb5afb2c-e2ea-4e56-9c9c-415b7641fa22', null, null, 'gratis');`
2. `SERVER_PORT=8002 QUARKUS_MANAGEMENT_PORT=9002 DEV_MODE=true ./gradlew clean …

SWATCH-2897 Internal api to provide remittance response based on tally_id

---

kafka-bridge/deploy/template.yaml

Add kafka-bridge stub template

---

swatch-system-conduit/src/main/java/org/candlepin/subscriptions/conduit/InventoryController.java
swatch-system-conduit/src/test/java/org/candlepin/subscriptions/conduit/InventoryControllerTest.java

Jira issue: SWATCH-2917
- Uniform the logs made by InventoryController, so all the logs print the same format (including the network fdqn if exists)
- Also, include into the MDC, the org_id

SWATCH-2917: Improve logging to identify system being updated in conduit

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/model/PartnerEntitlementsRequest.java

Jira issue: SWATCH-2925
IQE Test MR: 
1.
1.
1.
1.
1.
1.

SWATCH-2925 Avoid NPE and Array out of bound exception

---

swatch-producer-aws/deploy/clowdapp.yaml
swatch-producer-aws/src/main/resources/application.properties
swatch-producer-azure/deploy/clowdapp.yaml
swatch-producer-azure/src/main/resources/application.properties

Disable otel while it is failing in stage/prod

Kflahert/disable otel hotfix (#3784)

---

swatch-billable-usage/deploy/clowdapp.yaml
swatch-billable-usage/src/main/resources/application.properties
swatch-contracts/deploy/clowdapp.yaml
swatch-contracts/src/main/resources/application.properties
swatch-metrics/deploy/clowdapp.yaml
swatch-metrics/src/main/resources/application.yaml
swatch-producer-aws/deploy/clowdapp.yaml
swatch-producer-azure/deploy/clowdapp.yaml

add flag to turn off otel logging

add flag to disable otel in quarkus apps

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/product/UpstreamProductData.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/OfferingSyncService.java

IQE Test MR: 
1.
1.
1.
1.
1.
1.

Contract offering upstream unhandled exception

---

swatch-core/src/main/java/org/candlepin/subscriptions/db/HostRepository.java

Hotfix PR for Jira issue: [SWATCH-2935](https://issues.redhat.com/browse/SWATCH-2935)
See https://github.com/RedHatInsights/rhsm-subscriptions/pull/3770

SWATCH-2935: HOTFIX Improve guest lookup query

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/service/ContractService.java

IQE Test MR: 
1.
1.
1.
1.
1.
1.

Check null pointer for sku

---

swatch-metrics-hbi/deploy/clowdapp.yaml

Initial step to deploying the new service. Will prevent other CI breakages on other PRs.

Add stub swatch-metrics-hbi template

---

swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java

Jira issue: SWATCH-2994
IQE Test MR: 
1.
1.
1.
1.
1.
1.

SWATCH-2994 Show meaningful message along with DefaultApiException

---

src/main/java/org/candlepin/subscriptions/event/EventNormalizer.java
swatch-model-events/schemas/event.yaml

Jira issue: SWATCH-3007
Since https://issues.redhat.com/browse/COST-5575 is done and released, we can now revert this commit dbdfa91ff15f80c9d3e7515e9976ac647913503c.

SWATCH-3007: Remove uom usage in the EventNormalizer and EventController classes

---

swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceErrorCode.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/RemittanceStatus.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumer.java
swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumerTest.java
swatch-core/schemas/billable_usage.yaml
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/AwsThrottlingException.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/exception/ErrorCode.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumerTest.java
swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageConsumerTest.java

Jira issue: SWATCH-3024 and SWATCH-2995
IQE Test MR: 
1.
1.
1.
1.
1.
1.

Hotfix aws throttling and retry issue

---

swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageStatusConsumer.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java
swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumerTest.java

Adding some logging statements and logging full BillableUsageAggregate in consumer classes

Improve billable usage logging to include full aggregate object

---

src/main/resources/liquibase/202410211200-retry-after-billable-usage-index.xml
src/main/resources/liquibase/changelog.xml

IQE Test MR: 
1.
1.
1.
1.
1.
1.

Apply index from SWATCH-3036

---

src/main/resources/liquibase/202410241408-clear-retryable.xml
src/main/resources/liquibase/changelog.xml
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageController.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResource.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/data/BillableUsageRemittanceRepository.java
swatch-billable-usage/src/main/resources/META-INF/openapi.yaml
swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageControllerTest.java
swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java

IQE Test MR: 
1.
1.
1.
1.
1.
1.

[HOTFIX] Overbilling refund stuff

---

src/main/java/org/candlepin/subscriptions/event/EventController.java
src/test/java/org/candlepin/subscriptions/event/EventControllerTest.java

Jira issue: SWATCH-2297
We need to collect statistics as a means of cross-checking our usage counts so we can discover issues more quickly.
1. Start the needed services
`RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1 SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8003 SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api,capacity-ingress,kafka-queue,rhsm-conduit ./gradlew :bootRun`
1. Input event messages to the Kafka queue. Remember to increment the hour for each submission.
`{
"sla": "Premium",
"org_id": "111111111",
"timestamp": "2024-10-24T15:00:00.0000+04:00",
"conversion": false,
"event_type": "snapshot_rhel-for-x86-els-payg-addon_vCPUs",
"expiration": "2025-06-10T11:00:00.0000+04:00", …

SWATCH-2297: Add a metric for ingested usage data from Prometheus

---

.tekton/rhsm-pull-request.yaml
.tekton/rhsm-push.yaml
.tekton/swatch-api-pull-request.yaml
.tekton/swatch-api-push.yaml
.tekton/swatch-contracts-pull-request.yaml
.tekton/swatch-contracts-push.yaml
.tekton/swatch-metrics-hbi-pull-request.yaml
.tekton/swatch-metrics-hbi-push.yaml
.tekton/swatch-metrics-pull-request.yaml
.tekton/swatch-metrics-push.yaml
.tekton/swatch-producer-aws-pull-request.yaml
.tekton/swatch-producer-aws-push.yaml
.tekton/swatch-producer-azure-pull-request.yaml
.tekton/swatch-producer-azure-push.yaml
.tekton/swatch-producer-red-hat-marketplace-pull-request.yaml
.tekton/swatch-producer-red-hat-marketplace-push.yaml
.tekton/swatch-subscription-sync-pull-request.yaml
.tekton/swatch-subscription-sync-push.yaml
.tekton/swatch-system-conduit-pull-request.yaml
.tekton/swatch-system-conduit-push.yaml
.tekton/swatch-tally-pull-request.yaml
.tekton/swatch-tally-push.yaml

Adding this due to request from konflux team

Add rpm-signature-check task to tekton pipelines

---

swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/kafka/BillableUsageAggregateStreamTopologyTest.java

Jira issue: SWATCH-2304
When usage is aggregated, it should increment a counter named "swatch_billable_usage_total" with the billable amount in metric units, having labels:
product (swatch product tag)
metric_id (metric ID)
billing_provider (aws/azure)
status (aggregated)
2. setup database schema: `./gradlew liquibaseUpdate`
3. start the tally worker: `RHSM_SUBSCRIPTIONS_ENABLE_SYNCHRONOUS_OPERATIONS=true DEV_MODE=true PROM_URL=http://localhost:8082/api/metrics/v1/telemeter/api/v1 SWATCH_CONTRACTS_INTERNAL_SERVICE=http://localhost:8003 SERVER_PORT=8000 SPRING_PROFILES_ACTIVE=worker,kafka-queue,api ./gradlew clean :bootRun`
4.- start the contracts service: `SERVER_PORT=8003 QUARKUS_MANAGEMENT_PORT=9003 ./gradlew :swatch-contracts:quarkusDev`
5.- start the azure …

SWATCH-2304: Add a metric for usage aggregated per hour

---

swatch-metrics-hbi/build.gradle
swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/normalization/FactNormalizer.java
swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/normalization/MeasurementNormalizer.java
swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/normalization/facts/HostFacts.java

Remove swatch-core dependency from swatch-metrics-hbi

Remove swatch-core dependency from swatch-metrics-hbi

---

swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/model/Quantity.java
swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/services/BillableUsageServiceTest.java

Jira issue: SWATCH-2300 SWATCH-2301
This adds metrics for billable amounts and contract coverage when the monthly tally is calculated.
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/959
1. I used an EE and the new iqe proxy tool
1. A successful run of the test

SWATCH-2300: Add a metric for usage covered by a contract

---

swatch-common-export/build.gradle
swatch-common-export/src/main/java/com/redhat/swatch/export/ExportRequestHandler.java
swatch-common-export/src/main/java/com/redhat/swatch/export/utils/FileUtils.java
swatch-common-export/src/test/java/com/redhat/swatch/export/utils/FileUtilsTest.java

Jira issue: SWATCH-2941
Changes:
- Add logs with the URLs we're hitting (or the request ID)
- Add also the file size to be uploaded

SWATCH-2941: Improve the export service logging to better troubleshoot

---

swatch-common-export/src/main/java/com/redhat/swatch/export/utils/FileUtils.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/service/SubscriptionSyncServiceTest.java

There were only two places where we should set the timezone / locate format to fix the tests. This is only reproducible when building in a different time zone like in Spain.

Fix build to work in any location and timezone

---

swatch-tally/deploy/clowdapp.yaml

In preparation for upcoming work with Snowflake, I want to export a table that doesn't include sensitive information to use in order to test adding an S3 connector in Fivetran.

Export `sku_product_tag` table with Floorist

---

swatch-producer-aws/src/main/resources/application.properties

Jira issue: SWATCH-3079
IQE Test MR: https://gitlab.cee.redhat.com/insights-qe/iqe-rhsm-subscriptions-plugin/-/merge_requests/978
1.
1.
1.
1.
1.
1.

Add EE Wiremock contract Endpoint to aws-producer

---

swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
swatch-billable-usage/src/main/resources/application.properties
swatch-billable-usage/src/test/java/com/redhat/swatch/billable/usage/admin/api/InternalBillableUsageResourceTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/InMemoryMessageBrokerKafkaResource.java
swatch-metrics/src/main/resources/application.yaml
swatch-metrics/src/test/java/com/redhat/swatch/metrics/service/PrometheusMetricsTaskManagerTest.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/configuration/Channels.java
swatch-producer-aws/src/main/resources/application.properties
swatch-producer-aws/src/test/java/com/redhat/swatch/aws/service/BillableUsageStatusProducerTest.java
swatch-producer-aws/src/test/java/com/redhat/swatch/aws/test/resources/InMemoryMessageBrokerKafkaResource.java
swatch-producer-azure/src/main/resources/application.properties
swatch-producer-azure/src/test/java/com/redhat/swatch/azure/service/BillableUsageStatusProducerTest.java

These changes will ensure that containers are not used when not needed and hence will speed up running tests.

Clean up configuration for Quarkus services in tests

---

.github/workflows/pr.yaml
docker-compose.yml

This will help to have a quick feedback about the formatting and to better spot format issues. Context: https://redhat-internal.slack.com/archives/C01F7QFNATC/p1736361810374569
Checking the checks in PRs, we should now see two pipelines: the new one about running only the format validation and the previous one to validate the floorplan queries.

CI: Add isolated job to validate format in GitHub actions

---

.sonarlint/connectedMode.json

This is the link to the Sonar rules used in the CI
When using Intellij, you should see real-time Sonar reporting for .java files that match the CI.
It does require the SonarQube for IDE plugin.

Configuration for SonarCloud rules

---

.tekton/swatch-metrics-hbi-pull-request.yaml
.tekton/swatch-metrics-hbi-push.yaml

Run clair-scan and sast-snyk-check tasks after build-container in swatch-metrics-hbi as it's defined in the other pipelines.
All pipelines should be green.

Run clair-scan, sast-snyk-check tasks after build-container in swatch-metrics-hbi

---

bin/delete_comment_iqe_summary.sh
bin/post_comment_iqe_summary.sh
pr_check.sh

Jira issue: SWATCH-3280
See the comment generated automatically by InsightsDroid.

SWATCH-3280: Add a comment including the tests image

---

src/main/java/org/candlepin/subscriptions/event/EventController.java

IQE Test MR: 
1.
1.
1.
1.
1.
1.

Improve logging when we receive event

---

Jenkinsfile

Jira issue: SWATCH-3217
The "continuous-integration/jenkins/pr-merge" should be green.

SWATCH-3217: CI: Configure Jenkins to use the upshift cloud

---

.tekton/verify-snapshot-components-pipeline.yaml
.tekton/verify-snapshot-components-task.yaml

Jira issue: SWATCH-2133
More details in the JIRA description

SWATCH-2133: Add test-snapshot-component task definition

---

src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerTest.java

Jira issue: SWATCH-3373
The snapshots difference could be because when running the test, the day changed (midnight). Therefore, so making the test more consistent, I've mocked the clock to be in a fixed date/time. I also added some logs, so in case this test fails again, we can see why the snapshots were different than expected.
CI is green.

SWATCH-3373: Fix flaky test verifyCorrectUpdatesWhenRetryOccurs

---

mkdocs.yaml

IQE Test MR: 
1.
1.
1.
1.
1.
1.

Testing inscope

---

Jenkinsfile

Remove Kevin Howel and Nikhil who left the team.

Update Jenkinsfile to remove Kevin H and Nikhil

---

src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/test/java/org/candlepin/subscriptions/tally/AccountResetServiceTest.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/model/ContractEntityMapper.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/model/SubscriptionEntityMapper.java
swatch-core-test/src/main/resources/application-test.yaml

Make some tests more stable and fix a potential null pointer in tally snapshot.
Only regression testing

Make some tests more stable and fix potential null pointer in tally snapshot

---

.tekton/rhsm-pull-request.yaml
.tekton/rhsm-push.yaml
.tekton/swatch-api-pull-request.yaml
.tekton/swatch-api-push.yaml
.tekton/swatch-contracts-pull-request.yaml
.tekton/swatch-contracts-push.yaml
.tekton/swatch-metrics-hbi-pull-request.yaml
.tekton/swatch-metrics-hbi-push.yaml
.tekton/swatch-metrics-pull-request.yaml
.tekton/swatch-metrics-push.yaml
.tekton/swatch-producer-aws-pull-request.yaml
.tekton/swatch-producer-aws-push.yaml
.tekton/swatch-producer-azure-pull-request.yaml
.tekton/swatch-producer-azure-push.yaml
.tekton/swatch-producer-red-hat-marketplace-pull-request.yaml
.tekton/swatch-producer-red-hat-marketplace-push.yaml
.tekton/swatch-subscription-sync-pull-request.yaml
.tekton/swatch-subscription-sync-push.yaml
.tekton/swatch-system-conduit-pull-request.yaml
.tekton/swatch-system-conduit-push.yaml
.tekton/swatch-tally-pull-request.yaml
.tekton/swatch-tally-push.yaml

Fix Konflux jobs by fixing the violations. 
Don't know why these tasks were bumped by an automated pull request, if it happens again, we should ask Konflux team and/or require further investigation.
Konflux pipelines are green.

Bump build-container and rpms-signature-scan konflux tasks

---

swatch-metrics-hbi/deploy/clowdapp.yaml

Added missing config preventing successful deployment

Updating swatch-metrics-hbi clowdapp configuration

---

docs/swatch-internal-docs.md
docs/swatch-support-scripts.md
mkdocs.yml

All docs will be navigable from docs_dir instead of nav

Remove mkdocs nav for docs_dir to work

---

.tekton/rhsm-pull-request.yaml
.tekton/rhsm-push.yaml
.tekton/swatch-api-pull-request.yaml
.tekton/swatch-api-push.yaml
.tekton/swatch-contracts-pull-request.yaml
.tekton/swatch-contracts-push.yaml
.tekton/swatch-metrics-hbi-pull-request.yaml
.tekton/swatch-metrics-hbi-push.yaml
.tekton/swatch-metrics-pull-request.yaml
.tekton/swatch-metrics-push.yaml
.tekton/swatch-producer-aws-pull-request.yaml
.tekton/swatch-producer-aws-push.yaml
.tekton/swatch-producer-azure-pull-request.yaml
.tekton/swatch-producer-azure-push.yaml
.tekton/swatch-producer-red-hat-marketplace-pull-request.yaml
.tekton/swatch-producer-red-hat-marketplace-push.yaml
.tekton/swatch-subscription-sync-pull-request.yaml
.tekton/swatch-subscription-sync-push.yaml
.tekton/swatch-system-conduit-pull-request.yaml
.tekton/swatch-system-conduit-push.yaml
.tekton/swatch-tally-pull-request.yaml
.tekton/swatch-tally-push.yaml

More info in https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/conforma/new-sast-tasks-mar25.md.

Add new required tasks to Konflux pipelines

---

src/main/java/org/candlepin/subscriptions/event/EventController.java
src/main/java/org/candlepin/subscriptions/tally/TallySnapshotController.java
src/test/java/org/candlepin/subscriptions/tally/TallySnapshotControllerMetricsTest.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/kafka/streams/StreamTopologyProducer.java
swatch-billable-usage/src/main/java/com/redhat/swatch/billable/usage/services/BillableUsageService.java
swatch-producer-aws/src/main/java/com/redhat/swatch/aws/service/AwsBillableUsageAggregateConsumer.java
swatch-producer-azure/src/main/java/com/redhat/swatch/azure/service/AzureBillableUsageAggregateConsumer.java

Jira issue: SWATCH-3476
In order to not miss any counters and because it's the recommended approach by the Micrometer official documentation.
Regression testing: we have fully covered all these metrics.

SWATCH-3476: Replace Counter.builder by registry.counter

---

.tekton/swatch-contracts-pull-request.yaml
.tekton/swatch-metrics-hbi-pull-request.yaml
.tekton/swatch-metrics-hbi-push.yaml

Required change for: https://github.com/RedHatInsights/rhsm-subscriptions/pull/4363
The update of task-sast-snyk-check 0.3 -> 0.4
drops the default for image-url and makes it required.
https://github.com/konflux-ci/build-definitions/blob/main/task/sast-snyk-check/0.3/sast-snyk-check.yaml#L33
https://github.com/konflux-ci/build-definitions/tree/main/task/sast-snyk-check/0.4

Add required param to konflux pipeline

---

swatch-metrics-hbi/deploy/clowdapp.yaml

Increase resource allocations to stop crash looping.

Increase swatch-metrics-hbi resource allocations

---

.tekton/swatch-contracts-pull-request.yaml
.tekton/swatch-contracts-push.yaml
.tekton/swatch-database-pull-request.yaml
.tekton/swatch-database-push.yaml
.tekton/swatch-metrics-hbi-pull-request.yaml
.tekton/swatch-metrics-hbi-push.yaml
.tekton/swatch-metrics-pull-request.yaml
.tekton/swatch-metrics-push.yaml
.tekton/swatch-producer-aws-pull-request.yaml
.tekton/swatch-producer-aws-push.yaml
.tekton/swatch-producer-azure-pull-request.yaml
.tekton/swatch-producer-azure-push.yaml
.tekton/swatch-producer-red-hat-marketplace-pull-request.yaml
.tekton/swatch-producer-red-hat-marketplace-push.yaml
.tekton/swatch-subscription-sync-pull-request.yaml
.tekton/swatch-subscription-sync-push.yaml
.tekton/swatch-system-conduit-pull-request.yaml
.tekton/swatch-system-conduit-push.yaml
.tekton/swatch-tally-pull-request.yaml
.tekton/swatch-tally-push.yaml

Jira issue: SWATCH-3535
IQE Test MR: 
1.
1.
1.
1.
1.
1.

SWATCH-3535: Accept all Konflux-generated PipelineRun definitions

---

swatch-api/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

Jira issue: SWATCH-3549
To support seamless cutover with app-interface updates
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/141535

SWATCH-3549: Parameterize some IMAGE urls that were missing

---

swatch-metrics-hbi/src/main/java/com/redhat/swatch/hbi/events/services/HbiEventConsumer.java

https://redhat-internal.slack.com/archives/C04LP3BKBU3/p1746822429716329?thread_ts=1746822075.946309&cid=C04LP3BKBU3

Update HbiEventConsumer.java to log HBI events at DEBUG level

---

swatch-contracts/src/main/java/com/redhat/swatch/contract/product/umb/ProductStatusUMBMessageConsumer.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/service/OfferingSyncService.java

SWATCH-3456
Increase logging for the new consumer ProductStatusUMBMessageConsumer

swatch-3456: Increase logging for new umb product consumer

---

swatch-billable-usage/deploy/clowdapp.yaml
swatch-contracts/deploy/clowdapp.yaml
swatch-metrics/deploy/clowdapp.yaml
swatch-subscription-sync/deploy/clowdapp.yaml
swatch-system-conduit/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

The maximum ratio is 2
Jira issue: SWATCH-3578

SWATCH-3578: Adjust memory limit to memory limit ratio

---

.tekton/swatch-api-push.yaml
.tekton/swatch-billable-usage-push.yaml
.tekton/swatch-contracts-push.yaml
.tekton/swatch-database-push.yaml
.tekton/swatch-metrics-hbi-push.yaml
.tekton/swatch-metrics-push.yaml
.tekton/swatch-producer-aws-push.yaml
.tekton/swatch-producer-azure-push.yaml
.tekton/swatch-producer-red-hat-marketplace-push.yaml
.tekton/swatch-subscription-sync-push.yaml
.tekton/swatch-system-conduit-push.yaml
.tekton/swatch-tally-push.yaml

IQE Test MR: 
1.
1.
1.
1.
1.
1.

Don't cancel builds of main in progress

---

.tekton/swatch-api-push.yaml
.tekton/swatch-billable-usage-push.yaml
.tekton/swatch-contracts-push.yaml
.tekton/swatch-database-push.yaml
.tekton/swatch-metrics-hbi-push.yaml
.tekton/swatch-metrics-push.yaml
.tekton/swatch-producer-aws-push.yaml
.tekton/swatch-producer-azure-push.yaml
.tekton/swatch-producer-red-hat-marketplace-push.yaml
.tekton/swatch-subscription-sync-push.yaml
.tekton/swatch-system-conduit-push.yaml
.tekton/swatch-tally-push.yaml
swatch-producer-red-hat-marketplace/deploy/clowdapp.yaml

SWATCH-3579: Scale down replicas to 0 for swatch-producer-red-hat-marketplace

---

swatch-contracts/build.gradle
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/SubscriptionsExceptionMapper.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/resource/api/v1/CapacityResourceV1.java
swatch-contracts/src/main/java/com/redhat/swatch/contract/security/RhIdentityHeaderAuthenticationMechanism.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/ContractsHttpEndpointTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/ContractsResourceTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/CapacityResourceV1Test.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/ContractsV1ResourceTest.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v1/SubscriptionResourceV1Test.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/resource/api/v2/SubscriptionResourceV2Test.java
swatch-contracts/src/test/java/com/redhat/swatch/contract/test/resources/DisableRbacResource.java

Jira issue: SWATCH-3528
Confirm that the modified unit tests test the scenarios as they did before.
The unit tests pass with the same assertions.

SWATCH-3528: Update swatch-contracts junit tests using the io.quarkus:quarkus-test-security extension

---

.tekton/swatch-database-push.yaml

The swatch-database functionality is no longer limited to a branch.

SWATCH-2820: Inform konflux that swatch-database is no longer bound to a branch

---

swatch-api/deploy/clowdapp.yaml

IQE Test MR: 
1.
1.
1.
1.
1.
1.

SWATCH-2820: Trial and error to figure out secret naming convention

---

swatch-api/deploy/clowdapp.yaml
swatch-billable-usage/deploy/clowdapp.yaml
swatch-contracts/deploy/clowdapp.yaml
swatch-database/deploy/clowdapp.yaml
swatch-subscription-sync/deploy/clowdapp.yaml
swatch-system-conduit/deploy/clowdapp.yaml
swatch-tally/deploy/clowdapp.yaml

https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/144109
IQE Test MR: 
1.
1.
1.
1.
1.
1.

SWATCH-2820: Parameterize DB_POD for clowdapps

---

README.md
docs/playbooks/observability.md

Quick docs update on how to invoke Liquibase now.

Update docs with information about running Liquibase

---

swatch-database/deploy/clowdapp.yaml

SWATCH-3638: Updated definition of ClowdApp/swatch-database for seamless deployment
Need to update prod with changes necessary for Clowder compatibility so the next prod release doesn't have a dependency on a follow-up app-interface MR.
Related to:
-
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/144454
IQE Test MR: 
1.
1.
1.
1.
1.
1.

SWATCH-3638: Updated definition of ClowdApp/swatch-database (#4577)

---

README.md

Update the README and also test that the build process works correctly now that swatch-database has settled.

Update README with swatch-database bonfire config

---

Makefile

Jira issue: SWATCH-3758
With these changes, we can keep using the Makefile as before, for ex: make swatch-tally.
But additionally, I added the following two options:
- make run-migrations: to run the database migrations
- make swatch-tally build: to also build the source of this service and its dependencies
Regression testing.

SWATCH-3758: Allow to build the sources and run migrations using Makefile

---

.github/workflows/ci.yml
bin/test-all-services.sh
bin/test-service-health.sh
docker-compose.yml
swatch-billable-usage/src/main/resources/application.properties

Jira issue: SWATCH-3759
To ensure we don't introduce breaking changes, let's add a new step in our existing GitHub action to start/stop all the services in DEV mode.
CI is green and the new check is passing: "Verify SWATCH services for local testing"

SWATCH-3759: Add a GitHub action to validate that all the services work in DEV mode

---

.tekton/swatch-api-push.yaml
.tekton/swatch-billable-usage-push.yaml
.tekton/swatch-contracts-push.yaml
.tekton/swatch-database-push.yaml
.tekton/swatch-metrics-hbi-push.yaml
.tekton/swatch-metrics-push.yaml
.tekton/swatch-producer-aws-push.yaml
.tekton/swatch-producer-azure-push.yaml
.tekton/swatch-system-conduit-push.yaml
.tekton/swatch-tally-push.yaml

IQE Test MR: 
1.
1.
1.
1.
1.
1.

Run konflux on merge queue checks

---

kafka-bridge/deploy/template.yaml

https://redhat-internal.slack.com/archives/C022YV4E0NA/p1755714816963559?thread_ts=1755072405.016569&cid=C022YV4E0NA

Add KafkaBridge imagePullSecrets configuration

---

.tekton/bonfire-component-tests-pipelinerun.yaml

This is the final piece to use the pipeline manifests that have been previously merged to main
CI is green.

SWATCH-3838: Use main to resolve the pipeline manifest for component tests

---

bin/build-images.sh
build_deploy.sh
pr_check.sh
swatch-utilization/src/main/docker/Dockerfile.jvm

Jira issue: SWATCH-4002
This is needed for the konflux pipelines. 
"./bin/build-images.sh swatch-utilization" should work to create the image (not to push the image to the quay repository which does not exist yet.

SWATCH-4002: Add Dockerfile.jvm for swatch-notifications

---

docs/MacOS.md

Adding MacOS specific section for local development config and troubleshooting.

Docs: Adding MacOS config and troubleshooting section
